### ISSUE TITLE
XSS Execution

### ISSUE THREAD

**Issue by iyenal** [sympa-community/sympa#100]
The execution of XSS is possible through file upload in the document sharing server.
[FILE.zip](https://github.com/sympa-community/sympa/files/1386586/FILE.zip)
The file used is joined in this issue.

**Comment by ikedas** [comment]
Hi @iyenal,

Can you please describe how XSS is possible with Sympa?

**Comment by ikedas** [comment]
Deficient information. I'll tag this invalid.
