### ISSUE TITLE
Missing login form when auth.conf only has a ldap entry

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#1007]
I'm working on a migration from 6.2.16 to 6.2.56. 

The `auth.conf` looks like (redacted for privacy):

```
ldap
    regexp .*
    host ldap.linuxia.de:636
    bind_dn	sympa@linuxia.de
    bind_password nevairbe
    timeout 20
    suffix dc=linuxia,dc=de
    get_dn_by_uid_filter (uid=[sender])
    get_dn_by_email_filter (&(objectcategory=person)(mail=[sender])(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
    email_attribute mail
    scope sub
    use_ssl 1
    ca_file /etc/ssl/linuxia-chain.pem
    ca_verify required
```
This setting works with 6.2.16. 

It doesn't work with 6.2.56 as the form for the email address and password is missing.

The following workaround in `auth.conf` brings it back:

```
user_table  
  regexp .*@example\.com 
```

Installation method: from source.

**Comment by ikedas** [comment]
I couldn't reproduce with 6.2.56.

@racke, please show us:
- The steps to reproduce the bug you reported.
- Screen shot displaying "the form for the email address and password is missing".
- Values of template variables when the form is missing (you may have to login as listmaster, to enable template variable dump, logout once and try to reproduce the bug).

**Comment by racke** [comment]
Turns out that I can't reproduce the problem.
