### ISSUE TITLE
[6.2.16] Welcome message not send after subscription by owner

### ISSUE THREAD

**Issue by nqb** [sympa-community/sympa#101]
Hello,

In 6.2.16, as owner of a list, if you click on **http** link received by mail to add new subscriber, new subscriber don't receive welcome message. However, if you click on **mailto** link, new subscriber receive welcome message.

Steps to reproduce : 
* Create a list with config in [attachment](https://github.com/sympa-community/sympa/files/1387686/config.txt)
* As Foo user with no account in web interface, send an e-mail to sympa@listes.exemple.fr with subject : "sub exemple-temp"
* As Bar owner , click on **http** link received by mail to add Foo subscriber

Results : 
* Foo user is subscriber
* Foo user don't receive welcome message (no mail in /var/log/mail.log, no error in syslog with log_level=4)

I didn't found issue related to this in latest stables releases.

Have you any ideas ?

**Comment by ikedas** [comment]
Hi @nqb,
Can you check recent stable version (currently 6.2.22)?

**Comment by nqb** [comment]
I will check ASAP

**Comment by dverdin** [comment]
This was fixed in 6.2.17b, thanks to @salaun-urennes1 : https://github.com/sympa-community/sympa/pull/1

**Comment by nqb** [comment]
Thanks @dverdin
