### ISSUE TITLE
Upgrade to 6.2.57b.2 fails : dies in _load_include_admin_user_file()

### ISSUE THREAD

**Issue by salaun-urennes1** [sympa-community/sympa#1016]
Sympa.pl --upgrade dies 

Version
-------
from 6.2.54 to 6.2.57b.2

Installation method
-------------------
sources

Expected behavior
-----------------
/usr/local/sympa/etc/data_structure.version should include new version number

Actual behavior
---------------
```
$ /usr/local/sympa/bin/sympa.pl --log_level=3 --upgrade
notice main:: Sympa 6.2.57b.2 Started
notice main:: Upgrade process...
notice main:: Upgrading from 6.2.54 to 6.2.57b.2...
notice Sympa::Upgrade::upgrade() Rebuilding config.bin files for ALL lists...it may take a while...
Use of uninitialized value in regexp compilation at /usr/local/sympa/bin/Sympa/List.pm line 5196, <GEN32> line 119.
err main::#872 > Sympa::Upgrade::upgrade#172 > Sympa::List::get_lists#4609 > Sympa::List::new#179 > Sympa::List::load#690 > Sympa::List::_load_list_config_file#5092 Expecting a paragraph for "creation" parameter in /usr/local/sympa/list_data/listes.univ-rennes1.fr/eco-secret-tech/config, ignore it
err main::#872 > Sympa::Upgrade::upgrade#172 > Sympa::List::get_lists#4609 > Sympa::List::new#179 > Sympa::List::load#690 > Sympa::List::_load_list_config_file#5092 Expecting a paragraph for "creation" parameter in /usr/local/sympa/list_data/listes.univ-rennes1.fr/ecobio/config, ignore it
notice Sympa::Upgrade::upgrade() Rebuilding the admin_table...it may take a while...
notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=droit-2021@listes.etudiant.univ-rennes1.fr;role=owner>
Can't use string ("/usr/local/sympa/etc/listes.etud"...) as a HASH ref while "strict refs" in use at /usr/local/sympa/bin/Sympa/List.pm line 4144.
```

Additional information
----------------------
I checked the code that makes sympa.pl dies : https://github.com/sympa-community/sympa/blob/3f44b653a3c174a29920768e5bab530e76d245f4/src/lib/Sympa/List.pm#L4135

This piece of cade was updated 3 months ago

I tried to add traces in that code with no success

**Comment by racke** [comment]
Can you provide the config for this include?

**Comment by salaun-urennes1** [comment]
Here is an anonymized version of droit-2021 list config file:
[config.txt](https://github.com/sympa-community/sympa/files/5365625/config.txt)

And here is the owner_include data_source:
[owners_editors.incl.txt](https://github.com/sympa-community/sympa/files/5365627/owners_editors.incl.txt)

**Comment by ikedas** [comment]
@salaun-urennes1 , could you please try the PR above?

**Comment by salaun-urennes1** [comment]
Hi Soji,

I had another try upgrading with that line added and it succeeded : 
```
$ /usr/local/sympa/bin/sympa.pl --log_level=3 --upgrade
notice main:: Sympa 6.2.57b.2 Started
notice main:: Upgrade process...
notice main:: Upgrading from 6.2.54 to 6.2.57b.2...
...
notice main:: Upgrade process finished
```
