### ISSUE TITLE
Mail loop for sympa-request address

### ISSUE THREAD

**Issue by StianAndreassen79** [sympa-community/sympa#1018]
Hi Sympa Team,

Thanks for a great product! We have used it for years here at James Cook University. We have recently upgraded from 6.1.4 to 6.2.56, and we're seeing an issue that others have reported with this version. It's pertaining to how messages to sympa-request appear to be delivered to the sympa queue, but rejected as there's no such list, and they never should have been routed there in the first place.

Other bug reports have been logged regarding this;
https://github.com/sympa-community/sympa/issues/995
https://github.com/sympa-community/sympa/issues/957

We saw the same issue on our Sympa once we opened the new production server to mail in and out, it never happened in our test environment that was run for a while before we cut over to the production server. The issue manifested itself in extremely verbose log files, overworked spools and eventually RAM issues leading to paging and RAM initialization issues for the main Sympa threads. The delivery attempt occurred several times pr minute, the worst case I found was 143 times pr minute, all day and all night.

We implemented a workaround of adding a regexp to our virtual.regexp file, which is a virtual_maps regex defined in main.cf, as we don't use sendmail aliases, we use only regexp in our postfix configuration. This line effectively forwards these messages to /dev/null and the issue disappears;
`/^sympa-request\@<list-domain>\.<dc>\.<dc>\.<dc>$/ devnull@localhost`
We then have an entry in /etc/aliases that handles this; 
devnull: /dev/null
as indicated in the other issues logged about this.

The reason why I'm submitting this issue, is that it would appear that the other issues logged seem to point to the root cause of this issue is a postfix misconfiguration where there are emails being routed IN to the Sympa host, sent to "sympa@listdomain.maildomain", evidenced by Sympa's log entries. But how can it be a postfix issue, if the 
"FROM" address entries in both Sympa and postfix's log files show that;
1. maillog has NO value for "from"
2. sympa.log has "recipients=sympa-request@listdomain.maildomain; sender=sympa-request@listdomain.maildomain"

This leads me to believe that the emails appearing to be sent to sympa@listdomain.maildomain are actually being sent by Sympa itself, or may be a result of only using regexp configuration for postfix? Our sympa_aliases file is identical to what's in the documentation, but obviously having the list and mail domains modified. What are the chances you could look at this issue again?

**Comment by ikedas** [comment]
Hi @StianAndreassen79 ,
Could you please show a concrete example of log lines in which there is 'NO value for "from"'?  I cannot understand what you mean.

**Comment by StianAndreassen79** [comment]
Hi @ikedas,

Thanks for getting back to me!

I've attached an extract of the maillog file from our production server from Oct 4 around 3am until the following day at around 09:30am. Extremely verbose due to all the traffic related to sympa-request. I've gzipped it for your convenience.

Sincerely,
[maillog_no_from_for_sympa_requests.gz](https://github.com/sympa-community/sympa/files/5369214/maillog_no_from_for_sympa_requests.gz)

Stian Andreassen
Software Engineer
Technology Solutions Directorate
James Cook University, Australia

**Comment by StianAndreassen79** [comment]
Hi again @ikedas,

I've also attached an extract of sympa.log from the same timeframe. As you can see, a huge file, extremely verbose. The logging reduced by 95% after modifying our virtual map file to send these messages to /dev/null.

sympa-requests still processes commands properly when sent via email.

[sympa.log_sympa_requests_verbose.gz](https://github.com/sympa-community/sympa/files/5369244/sympa.log_sympa_requests_verbose.gz)


Sincerely,

Stian Andreassen
Software Engineer
Technology Solutions Directorate
James Cook University, Australia

**Comment by ikedas** [comment]
Could you please show the log of Sympa in the same period? `log_level` may be `0` (higher log levels are not useful). You may omit log lines for `task_manager` and/or `wwsympa`.

**Comment by StianAndreassen79** [comment]
> Could you please show the log of Sympa in the same period? `log_level` may be `0` (higher log levels are not useful). You may omit log lines for `task_manager` and/or `wwsympa`.

I was already in the process of doing this when you posted the above, my apologies for not omitting those lines.. The file is attached.

Thanks for looking at this!

**Comment by ikedas** [comment]
@StianAndreassen79 , I still have more requests:
- Please tell me the versions of Postfix and Sympa.
- If possible, please show the result of running a command `postconf -n` .  Secret information may be masked.

Thank you.

**Comment by StianAndreassen79** [comment]
Hi again @ikedas,
Here we go;
RHEL 7.8 with;
Postfix 2:2.10.1
Sympa and 6.2.56 installed from EPEL

Redaction legend;
dc = domain component (same notation as for LDAP)
listdomain = our internal list domain name
publicdomain = our public mail domain name

postconf -n;
alias_database = hash:/etc/aliases
alias_maps = hash:/etc/aliases, hash:/etc/sympa/sympa_aliases
config_directory = /etc/postfix
inet_interfaces = all
local_recipient_maps = regexp:/etc/postfix/local_recipient_regexp unix:passwd.byname $alias_maps
mailq_path = /usr/bin/mailq.postfix
masquerade_classes = envelope_sender, envelope_recipient, header_sender, header_recipient
masquerade_domains = maildomain.publicdomain
message_size_limit = 32000000
mydestination = $myhostname, localhost.$mydomain, localhost, sympa-server-host.FQDN
mydomain = publicdomain
myhostname = listdomain.publicdomain
mynetworks = 127.0.0.1 10.20.0.0/16 xxx.xxx.0.0/16
newaliases_path = /usr/bin/newaliases.postfix
recipient_delimiter = +
sendmail_path = /usr/sbin/sendmail.postfix
smtpd_helo_required = yes
smtpd_helo_restrictions = permit_mynetworks, check_helo_access hash:/etc/postfix/helo-access, check_helo_access cidr:/etc/postfix/helo-access-cidr, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname
sympa_destination_recipient_limit = 1
sympabounce_destination_recipient_limit = 1
transport_maps = regexp:/etc/sympa/transport.regexp,hash:/etc/postfix/transport
unknown_local_recipient_reject_code = 550
virtual_maps = regexp:/etc/sympa/virtual.regexp

Other things that might be of importance;

local_recipient_regexp;
/^.*-owner\@listdomain\.dc\.dc\.dc$/  1
/^staff-.*\@listdomain\.dc\.dc\.dc$/  1
/^.*staff\@listdomain\.dc\.dc\.dc$/  1
/^students-.*\@listdomain\.dc\.dc\.dc$/  1
/^.*\@listdomain\.dc\.dc\.dc$/  1

transport.regexp;
#/^.*\-owner\@listdomain\.dc\.dc\.dc$/      sympabounce:
/^.*\+owner\@listdomain\.dc\.dc\.dc$/      sympabounce:
/^.*\-moderator\@listdomain\.dc\.dc\.dc$/      sympafamilymoderators:
/^staff-(all|tsv|cns)\@listdomain\.dc\.dc\.dc$/    sympafamilystaff:
/^staff-(.*)\@listdomain\.dc\.dc\.dc$/ sympafamilyorgu:
/^staff-(.*)\.(.*)\@listdomain\.dc\.dc\.dc$/ sympafamilyorgu:
/^staff-(.*)\.(.*)\.(.*)\@listdomain\.dc\.dc\.dc$/ sympafamilyorgu:
/^students-.*\@listdomain\.dc\.dc\.dc$/    sympafamilystudents:
/^roles-(.*)\.(.*)\@listdomain\.dc\.dc\.dc$/       sympafamilyroles:
/^.*\@lists\.dc\.dc\.dc$/             sympa:

virtual.regexp:
/^noreply\@listdomain\.dc\.dc\.dc$/ devnull@localhost
/^sympa-request\@listdomain\.dc\.dc\.dc$/ devnull@localhost
/^(.*)-owner\@listdomain\.dc\.dc\.dc$/     $1+owner@listdomain.publicdomain
/^([0-9]{2,4})staff@listdomain.publicdomain$/  staff-${1}@listdomain.publicdomain
/^(tsv|cns)([0-9]{2,4})staff@listdomain.publicdomain$/ staff-${2}.${1}@listdomain.publicdomain
/^(acad|gen|other|res|tec)([0-9]{2,4})staff@listdomain.publicdomain$/  staff-${2}.all.${1}@listdomain.publicdomain
/^(tsv|cns)(acad|gen|other|res|tec)([0-9]{2,4})staff@listdomain.publicdomain$/ staff-${3}.${1}.${2}@listdomain.publicdomain

/etc/aliases;
truncated all the standard UNIX/Linux aliases, but at the end of the file we have;
devnull: /dev/null
noreply: /dev/null

sympa_aliases;
sympa:			      "| /usr/libexec/sympa/queue sympa@listdomain.publicdomain"
listmaster:     	              "| /usr/libexec/sympa/queue listmaster@listdomain.publicdomain"
bounce+*:       	      "| /usr/libexec/sympa/bouncequeue sympa@listdomain.publicdomain"
abuse-feedback-report:  "| /usr/libexec/sympa/bouncequeue sympa@listdomain.publicdomain"
sympa-request:  	      postmaster
sympa-owner:    	      postmaster
staff:          	      /dev/null
students:       	      /dev/null

/etc/postfix/transport only contains a "route all" directive to the host of our internal outbound SMTP server, that I don't need to disclose.

**Comment by StianAndreassen79** [comment]
Hi again @ikedas,
Here we go;
RHEL 7.8 with;
Postfix 2:2.10.1
Sympa and 6.2.56 installed from EPEL

Redaction legend;
dc = domain component (same notation as for LDAP)
listdomain = our internal list domain name
publicdomain = our public mail domain name
x = public IP range digit

postconf -n;
alias_database = hash:/etc/aliases
alias_maps = hash:/etc/aliases, hash:/etc/sympa/sympa_aliases
config_directory = /etc/postfix
inet_interfaces = all
local_recipient_maps = regexp:/etc/postfix/local_recipient_regexp unix:passwd.byname $alias_maps
mailq_path = /usr/bin/mailq.postfix
masquerade_classes = envelope_sender, envelope_recipient, header_sender, header_recipient
masquerade_domains = maildomain.publicdomain
message_size_limit = 32000000
mydestination = $myhostname, localhost.$mydomain, localhost, sympa-server-host.FQDN
mydomain = publicdomain
myhostname = listdomain.publicdomain
mynetworks = 127.0.0.1 10.20.0.0/16 xxx.xxx.0.0/16
newaliases_path = /usr/bin/newaliases.postfix
recipient_delimiter = +
sendmail_path = /usr/sbin/sendmail.postfix
smtpd_helo_required = yes
smtpd_helo_restrictions = permit_mynetworks, check_helo_access hash:/etc/postfix/helo-access, check_helo_access cidr:/etc/postfix/helo-access-cidr, reject_invalid_helo_hostname, reject_non_fqdn_helo_hostname
sympa_destination_recipient_limit = 1
sympabounce_destination_recipient_limit = 1
transport_maps = regexp:/etc/sympa/transport.regexp,hash:/etc/postfix/transport
unknown_local_recipient_reject_code = 550
virtual_maps = regexp:/etc/sympa/virtual.regexp

Other things that might be of importance;

local_recipient_regexp;
`/^.*-owner\@listdomain\.dc\.dc\.dc$/  1`
`/^staff-.*\@listdomain\.dc\.dc\.dc$/  1`
`/^.*staff\@listdomain\.dc\.dc\.dc$/  1`
`/^students-.*\@listdomain\.dc\.dc\.dc$/  1`
`/^.*\@listdomain\.dc\.dc\.dc$/  1`

transport.regexp;
`#/^.*\-owner\@listdomain\.dc\.dc\.dc$/      sympabounce:`
`/^.*\+owner\@listdomain\.dc\.dc\.dc$/      sympabounce:`
`/^.*\-moderator\@listdomain\.dc\.dc\.dc$/      sympafamilymoderators:`
`/^staff-(all|tsv|cns)\@listdomain\.dc\.dc\.dc$/    sympafamilystaff:`
`/^staff-(.*)\@listdomain\.dc\.dc\.dc$/ sympafamilyorgu:`
`/^staff-(.*)\.(.*)\@listdomain\.dc\.dc\.dc$/ sympafamilyorgu:`
`/^staff-(.*)\.(.*)\.(.*)\@listdomain\.dc\.dc\.dc$/ sympafamilyorgu:`
`/^students-.*\@listdomain\.dc\.dc\.dc$/    sympafamilystudents:`
`/^roles-(.*)\.(.*)\@listdomain\.dc\.dc\.dc$/       sympafamilyroles:`
`/^.*\@lists\.dc\.dc\.dc$/             sympa:`

virtual.regexp:
`/^noreply\@listdomain\.dc\.dc\.dc$/ devnull@localhost`
`/^sympa-request\@listdomain\.dc\.dc\.dc$/ devnull@localhost`
`/^(.*)-owner\@listdomain\.dc\.dc\.dc$/     $1+owner@listdomain.publicdomain`
`/^([0-9]{2,4})staff@listdomain.publicdomain$/  staff-${1}@listdomain.publicdomain`
`v/^(tsv|cns)([0-9]{2,4})staff@listdomain.publicdomain$/ staff-${2}.${1}@listdomain.publicdomain`
`/^(acad|gen|other|res|tec)([0-9]{2,4})staff@listdomain.publicdomain$/  staff-${2}.all.${1}@listdomain.publicdomain`
`/^(tsv|cns)(acad|gen|other|res|tec)([0-9]{2,4})staff@listdomain.publicdomain$/ staff-${3}.${1}.${2}@listdomain.publicdomain`

/etc/aliases;
truncated all the standard UNIX/Linux aliases, but at the end of the file we have;
`devnull: /dev/null`
`noreply: /dev/null`

sympa_aliases;
`sympa:			      "| /usr/libexec/sympa/queue sympa@listdomain.publicdomain"`
`listmaster:     	              "| /usr/libexec/sympa/queue listmaster@listdomain.publicdomain"`
`bounce+*:       	      "| /usr/libexec/sympa/bouncequeue sympa@listdomain.publicdomain"`
`abuse-feedback-report:  "| /usr/libexec/sympa/bouncequeue sympa@listdomain.publicdomain"`
`sympa-request:  	      postmaster`
`sympa-owner:    	      postmaster`
`staff:          	      /dev/null`
`students:       	      /dev/null`

/etc/postfix/transport only contains a "route all" directive to the host of our internal outbound SMTP server, that I don't need to disclose.

**Comment by ikedas** [comment]
@StianAndreassen79 , I found the solution.

You defined transports in `master.cf` such as (these are examples):

``` code
sympa   unix    -       n       n       -       -       pipe
  flags=hqRu user=sympa argv=$LIBEXECDIR/queue ${nexthop}
sympabounce unix -      n       n       -       -       pipe
  flags=hqRu user=sympa argv=$LIBEXECDIR/bouncequeue ${nexthop}
```

To solve the problem, add empty `null_sender` option as below:

``` code
sympa   unix    -       n       n       -       -       pipe
  flags=hqRu null_sender= user=sympa argv=$LIBEXECDIR/queue ${nexthop}
sympabounce unix -      n       n       -       -       pipe
  flags=hqRu null_sender= user=sympa argv=$LIBEXECDIR/bouncequeue ${nexthop}
```

This option was required for Sympa as of Postfix 2.3.

**Comment by StianAndreassen79** [comment]
Thanks @ikedas, but we're running postfix 2.10.1 as indicated above?

**Comment by ikedas** [comment]
> Thanks @ikedas, but we're running postfix **2.10.1** as indicated above?

Yes, I confirmed with my CentOS 7.  `null_sender` option was _added_ as of Postfix 2.3.

**Comment by StianAndreassen79** [comment]
No problem. I can confirm that adding nullsender= to master.cf as indicated
fixes the issue without having to do patch Sympa.
