### ISSUE TITLE
Very long delay for "kept for auth" auth-messages

### ISSUE THREAD

**Issue by pveith** [sympa-community/sympa#1027]
**Base system:** Debian stretch, mariadb, sympa 6.2.56 build from from source
**What happens:** Usually sympa send the auth-request-messages to release a message to the list quite immediately. But there are two lists, which are an exception. These are the biggest lists on the server (45000 and 9000 subscribers). Both list get their subscribers synced from an read only table form the local database on the server. On other lists, usually the auth-request-message is send almost immediately about 0 to 10 sec. But those two list do get a significant delay! The 9000 sub list gets about 500 seconds and the 45000 sub list gets a whopping 2200 seconds (about 36 min). Is that a known problem? Are we doing something wrong? 
Here are some entries from my sympa.log
9000 subsriberlist:
`Oct 22 12:41:00 example sympa_msg[31710]: notice Sympa::Spindle::ToHeld::_twist() Message Sympa::Message <900subs@example.de.1603362731.12510> for Sympa::List <900subs@example.de> from sender@mail.example.de kept for authentication with key 6f1ecef045a285882d6df09efc907126 (527.24 seconds)
`
for the 45000 subscriberlist:
`Oct 26 16:19:46 example sympa_msg[23228]: notice Sympa::Spindle::ToHeld::_twist() Message Sympa::Message <45000subs@example.de.1603723404.24225> for Sympa::List <45000subs@example.de> from sender@mail.example.de kept for authentication with key 9a717c2b96ab3122595c0e325b5377b3 (2178.67 seconds)`

We have to delete old logs, so i can only go back 7 days. But in this time frame those two list seem to be the only ones affected by that much delay, even though there are other larger lists. We just discovered this, as we enforced authentification on our bigger newsletter list.

This is our send-scenario:
```
title.gettext Newsletter, restricted to moderators after confirmation

is_editor([listname],[sender])                 smime,md5           -> do_it
is_editor([listname],[sender])                 smtp,dkim  -> request_auth

true()					       smtp,dkim,smime,md5     -> reject(reason='send_editor')

```
Hopefully this is the information needed.
Regards, Patrick Veith.

**Comment by ikedas** [comment]
Hi @pveith, could you please show all lines of Sympa's log including information about those messages, `Sympa::Message <900subs@example.de.1603362731.12510>` and `Sympa::Message <45000subs@example.de.1603723404.24225>` ?

**Comment by pveith** [comment]
Here is the complete 45000 example. I will look up a 9000sub one.
```
Oct 26 15:43:28 example sympa_msg[23228]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <45000subs@example.de.1603723404.24225>; envelope_sender=sender@mail.example.de; message_id=720933bc-7f63-cf64-4edb-e8ba3748bb36@uni-bonn.de; sender=sender@mail.example.de

Oct 26 16:19:46 example sympa_msg[23228]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <45000subs@example.de.1603725587.23228,2171/shelved:dkim_sign>; envelope_sender=uni-studis-owner@example.uni-bonn.de; message_id=sympa.1603725586.23228.396@example.uni-bonn.de; recipients=sender@mail.example.de; sender=sympa@example.uni-bonn.de; template=send_auth;

Oct 26 16:19:46 example sympa_msg[23228]: notice Sympa::Spindle::ToHeld::_twist() Message Sympa::Message <45000subs@example.de.1603723404.24225> for Sympa::List <45000subs@example.de> from sender@mail.example.de kept for authentication with key 9a717c2b96ab3122595c0e325b5377b3 (2178.67 seconds)

Oct 26 16:21:24 example sympa_msg[23228]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <sympa@example.uni-bonn.de.1603725680.27600>; envelope_sender=sender@mail.example.de; message_id=b926f91a-d725-b68b-ed16-2ebf1df1d135@uni-bonn.de; sender=sender@mail.example.de

Oct 26 16:21:24 example sympa_msg[23228]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <sympa@example.uni-bonn.de.1603725685.23228,1629/shelved:dkim_sign>; envelope_sender=sympa-request@example.uni-bonn.de; message_id=sympa.1603725684.23228.385@example.uni-bonn.de; recipients=sender@mail.example.de; sender=sympa@example.uni-bonn.de; template=command_report;

Oct 26 16:22:26 example sympa_msg[23228]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <sympa@example.uni-bonn.de.1603725744.27696>; envelope_sender=sender@mail.example.de; message_id=4b695aee-e54a-28a4-406f-7f48a92de201@uni-bonn.de; sender=sender@mail.example.de

Oct 26 16:22:26 example sympa_msg[23228]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <sympa@example.uni-bonn.de.1603725747.23228,8091/shelved:dkim_sign>; envelope_sender=sympa-request@example.uni-bonn.de; message_id=sympa.1603725746.23228.39@example.uni-bonn.de; recipients=sender@mail.example.de; sender=sympa@example.uni-bonn.de; template=command_report;

Oct 26 16:24:20 example sympa_msg[23228]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <sympa@example.uni-bonn.de.1603725858.27841>; envelope_sender=sender@mail.example.de; message_id=0915ae11-a0a9-f3f3-c005-a1e152d1e5c0@uni-bonn.de; sender=sender@mail.example.de

Oct 26 17:00:50 example sympa_msg[23228]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <45000subs@example.de.1603728051.23228,4075/shelved:dkim_sign>; envelope_sender=uni-studis-owner@example.uni-bonn.de; message_id=sympa.1603728050.23228.86@example.uni-bonn.de; recipients=sender@mail.example.de; sender=sympa@example.uni-bonn.de; template=message_report; type=success

Oct 26 17:00:50 example sympa_msg[23228]: info Sympa::Spindle::ToList::_twist() Message Sympa::Message <45000subs@example.de_9a717c2b96ab3122595c0e325b5377b3> for Sympa::List <45000subs@example.de> from sender@mail.example.de accepted (2189.70 seconds, 1396 sessions, 34884 subscribers), message ID=720933bc-7f63-cf64-4edb-e8ba3748bb36@uni-bonn.de, size=1274270

Oct 26 17:00:50 example sympa_msg[23228]: info Sympa::Request::Handler::confirm::_twist() CONFIRM 9a717c2b96ab3122595c0e325b5377b3 from sender@mail.example.de accepted (2189.72 seconds)
```

**Comment by ikedas** [comment]
@pveith , did you enable personalization ("merge_feature") of 45000subs list?  If you did, can you try with disabling personalization?

**Comment by pveith** [comment]
Yes, it is active. Good point, i will disable it.
One other question on Sympa::Spindle::ToHeld:
This does not mean, that all inidividual 45000 messages are generated and held in the spool folder? That would have required ~65GB of disk space in the spool folder.

**Comment by pveith** [comment]
Okay, i tested it with the personalization feature disabled and that was the mistake.
Time personalization deactivated:
No attachment: 0.03 seconds
1000KB attachment: 0.13 seconds
Timepersonalization activated:
No attachment: 74.77 seconds
1000KB attachment: Takes way longer (still waiting here).

**Comment by pveith** [comment]
Timepersonalization activated:
No attachment: 74.77 seconds
1000KB attachment: 2556.81 seconds
