### ISSUE TITLE
List configuration file reading order

### ISSUE THREAD

**Issue by MargoM** [sympa-community/sympa#103]
Hi!

Could someone explain how Sympa reads the list configuration files? Is it same with sympa.conf? 

> sympa.conf parameters, https://www.sympa.org/manual/conf-parameters/part1 
> Comments start with the # character at the beginning of a line. Empty lines are also considered as comments and are ignored. There should only be one directive per line, but their order in the file is of no importance. 

I'm planning Sympa update (version 3 to 6), so I need to modify list configuration files. Is there any specific line (before or after line) where the Sympa 6 archive list parameters should be?

**Comment by racke** [comment]
You can use sympa itself to upgrade config files, database etc from one version to another, e.g.:

`sympa --upgrade --from=6.1.22 --to=6.2.22`

Not sure if that works all the way from version 3, but you can try it in a test instance.

**Comment by ikedas** [comment]
Hi @MargoM,

In addition to instruction by racke, if you are planning upgrade from Sympa prior to 6.2, you should read these pages:
- [Upgrading instruction](https://www.sympa.org/faq/upgrade-to-v6.2)
- [Release notes](https://github.com/sympa-community/sympa/blob/6.2.22/NEWS.md)
- [Earlier release notes](https://github.com/sympa-community/sympa/blob/6.2.22/ONEWS)

and you may find out how you have to do.
