### ISSUE TITLE
Drop support for Perl earlier than 5.16.x

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#1030]
Expected Behavior
--------------------
Sympa will support Perl 5.16.0 or later.

Current Behavior
-------------------
Sympa has to support Perl 5.10.1 or later.

Additional information
----------------------
EPEL 6 repository that requires Perl 5.10.x will be [at end of life in this month](https://fedoraproject.org/wiki/EPEL#What_packages_and_versions_are_available_in_EPEL.3F).  OTOH EPEL 7 that requires Perl 5.16.3 is still available.  AFAIK the other distributions support later versions of Perl.

My suggestion is that the next release of Sympa (maybe 6.2.60) will be the last version that supports Perl earlier than 5.16.

See also: #620

**Comment by xavierba** [comment]
From the RHEL/Fedora ecosystem point of view, perl 5.16 is fine. RHEL/CentOS 7 has perl 5.16.
Debian 8 (Jessie) has perl 5.20.
I'm not sure about the other "Enterprise" OSes like SuSE, but SLE 12 seems to use perl-5.16 as well.
I expect perl 5.16 or later do be shipped in all currently supported distributions.
