### ISSUE TITLE
Data sources: owner_include: privileged owners doesn't seem to work.

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1034]
Version
-------
6.2.58

Installation method
-------------------

RHEL 7 RPM based on:

https://dl.fedoraproject.org/pub/epel/7/SRPMS/Packages/s/sympa-6.2.58-1.el7.src.rpm

Expected behaviour
-----------------

Edit list config
  -> Data sources setup
  -> Owners defined in an external data source (owner_include)

has a field with a drop down dialogue selection box with two values.

```
profile (profile)
￼ privileged owner (privileged)
  normal owner (normal)
```
I would expect "privileged owner" to create owners defined by this data source as "privileged owner"

Actual behaviour
---------------

The data source works, but the owners are "normal owner"s:

1) No star indicating privileged owner on the owners page, after "Synchronize owners with data sources" is clicked.
2) Observed access permissions are "normal owner"

Additional information
----------------------

LDAP data source. 

In fact two different LDAP data sources: I see the same effect with a Microsoft AD server and a traditional Unix LDAP server.

**Comment by ikedas** [comment]
@dpc22, by any chance did you try to update an existing owner? If that is the case, profile won't be updated.

**Comment by dpc22** [comment]
Afraid not.

I was trying out a new data source on a freshly created test list. After observed the behaviour that I describe I ran a few experiments to confirm to myself that it only seems to be possible to add privileged owners manually.

I also have about 15 owners defined on this list (two separate data sources), and they are all listed as normal owners, despite:
  
  profile ￼
  privileged owner

on the data source entries which define the two sets of owners

I have just tried taking away the existing two data sources and adding a third which has a different set of email addresses. The existing owners all disappeared, and two new owners appeared, just as I would expect. The two replacement owners were also just "normal" owners.

**Comment by ikedas** [comment]
@dpc22 , please show us the configuration of the list, i.e. `config` and `*.incl` files.

And please make sure that version of Sympa is the latest one, running such as
``` bash
sympa.pl --version
```
Because the bug you report is similar to a bug #969 that was fixed by 6.2.58.

**Comment by dpc22** [comment]
lists-1[dpc22:~]$ sympa.pl --version
Sympa 6.2.58

this was upgraded from a system running 6.2.56 a few weeks back.

**Comment by dpc22** [comment]
Okay, so I just repeated the test in order to create a minimal test case, and this time it worked. This looks like a foul-up in testing on my part. Sorry about that.

I spent some time yesterday convincing myself that I had found a bug. I would close this ticket until I actually manage to come up with a reproducible test case.
