### ISSUE TITLE
Shared repository not accepted into sympa.conf Sympa 6.2.40

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1035]
The shared_feature off into sympa.conf is not accepted with 6.2.40 version.
How can i disable the shared repositories options for all users?

**Comment by khaoula-abaidi** [comment]
![repository_shared](https://user-images.githubusercontent.com/37698060/99505177-c6098f00-2980-11eb-8f94-ca799f413080.png)
![shared_repository](https://user-images.githubusercontent.com/37698060/99505185-c73abc00-2980-11eb-89fc-eeee85953b89.png)

**Comment by ikedas** [comment]
The `shared_feature` parameter is available on Sympa 6.2.42 or later.  Please see also #555 for more details.

**Comment by khaoula-abaidi** [comment]
Thank you for your response

**Comment by ikedas** [comment]
Closed for now
