### ISSUE TITLE
Feedback to users who want to subscribe to a list in which this e-mail address is already entered

### ISSUE THREAD

**Issue by Salo15** [sympa-community/sympa#1047]
When a user wants to subscribe to a list he has already subscribed to via the list's subscribe link (in our case https://www.listserv.dfn.de/sympa/subscribe/listenname ), the website then displays the information that an email with a confirmation link has been sent to the specified address. However, Sympa seems to simply ignore the request and the user does not receive a message that this email address is already a subscriber to the list.

We use Sympa version 6.2.16 and Sympa is installed as Debian Package.

I would expect Sympa to inform the user either directly on the website or by sending an email to the user that this email address is already subscribed to the list.
(If a user wants to subscribe to a list he has already subscribed to via email command, he will receive an email back with the information that this email address is already subscribed to the list).
Instead, the user does not receive any information/feedback at all and his subscription request is apparently simply ignored by Sympa without comment.

The Sympa-Log contains only the following lines:
Nov 30 09:30:04 lists3.scc.kit.edu wwsympa[5511]: info main::do_subrequest(sabine.lorenz@kit.edu, ) [robot listserv.dfn.de] [session 19727187523263] [client 2a00:1398:300:306::115e] [list sabinetest-l] [list sabinetest-l].
Nov 30 09:30:04 lists3.scc.kit.edu wwsympa[5511]: info main::do_subrequest(sabine.lorenz@kit.edu, ) [robot listserv.dfn.de] [session 19727187523263] [client 2a00:1398:300:306::115e] [list sabinetest-l] [list sabinetest-l]

Kind regards,
Sabine

**Comment by ikedas** [comment]
Hi @Salo15 ,
Please see a discussion on #386.  On recent (6.2.36 or later) Sympa, fake comment such as "confirmation link has been sent" is shown intentionally.

**Comment by Salo15** [comment]
Ok, thanks for this answer and the hint.
I did not find this discussion when I looked for it yesterday.

Kind regards,
Sabine
