### ISSUE TITLE
Missing language on edit subscriber view

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#1048]
So you create an user with editsubscriber in WWSympa. That leaves the `lang_user` in `user_table` empty.

Version
-------
6.2.58, 6.2.22

Expected behavior
-----------------
At least an indicator that the language is not set. Probably better to initialize the user with the default language.

Actual behavior
---------------
No information at all beneath "Language".

![9096f142_d4f2_5675_8881_4e8578ec3c7e_Test_list_editsubscriber](https://user-images.githubusercontent.com/143678/100646611-88bcde00-333e-11eb-98d5-a8736af0a68d.png)

**Comment by ikedas** [comment]
@racke, please check the PR above.
