### ISSUE TITLE
Add "bouncers reset", "bouncers del" and "bouncers [--status] review" commands to sympa.pl

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#1058]
Due to recent gmail problems, a lot of gmail.com subscribers are in error status in a lot of our lists.

Having a command line tool to cancel errors (and unsubscribe users in error status, since the option exists in the web UI) would be useful.

Note: I intend to code it myself next week, I’m creating this issue to think about it.

Expected Behavior
-----------------
Being able to cancel errors on unsubscribe users in error status from command line with `sympa.pl`.

Current Behavior
----------------
Such option does not exist.

**Comment by ikedas** [comment]
My ideas:
- The option like `--show_status_of_members` may also be useful.
- Sympa's CLI prefers `_` instead of `-` for separators of options (execpt leading ones).  I don't know exact reason.

**Comment by racke** [comment]
There is certainly no good reason for the underscores :roll_eyes:.

**Comment by ikedas** [comment]
> There is certainly no good reason for the underscores .

I agree. Perhaps this custom is inspired by Perl's syntax: Identifiers can contain `_` but never `-`.  Since someone began, followers adhered to keep consistency.

**Comment by ldidry** [comment]
> The option like --show_status_of_members may also be useful.

How would you like it? I can list the users without errors, then the users with errors, sorted alphabetically or sorted by the number of bounces, or list all users alphabetically with `[BOUNCE(S): 13]` before of after the address for those who have errors (13 is just an exemple, here).

**Comment by ikedas** [comment]
@ldidry, flexible querying is nice idea, however we'd be better to start with minimum feature that dumps the bounce status of all subscribers in a list.

**Comment by ikedas** [comment]
* The word "subscribe"/"unsubscribe" has been used for the actions by the user to add/remove themselves.  The word "add"/"del" has been used for the actions by administrators.
* I feel the options are way too long.

**Comment by racke** [comment]
Comment on option names: they are too long :-). The `from-list` part is superfluous. Also "reset" is more appropriate than "cancel" in my opinion. On top of that errors = bounces?

So my two cents:

- reset_subscriber_bounces
- unsubscribe_bounced_users
- show_members_status

**Comment by ldidry** [comment]
> So my two cents:
> - reset_subscriber_bounces
> - unsubscribe_bounced_users
> - show_members_status

Ok for me. @ikedas, is that ok for you?

**Comment by ikedas** [comment]
In my idea,

> * reset_member_bounce
> * del_bounced_member
> * show_member_status

`subscriber`, `user` -> `member`
`subscribe` -> `del`

I don't know whether plural or singular is better ("members" or "member").

**Comment by ldidry** [comment]
I think plural is better, it won’t surprise admins that all bounced members will be deleted, and they will not be surprised either if there is only one. Singular would mean "specify the member to delete" to me.

**Comment by racke** [comment]
Yes, I also think plural is better.

**Comment by ikedas** [comment]
> I think plural is better, it won’t surprise admins that all bounced members will be deleted, and they will not be surprised either if there is only one. Singular would mean "specify the member to delete" to me.

I see.  I’m not familiar with distinction of plural/singular... Besides in my idea, FYI,

* reset_member_bounces
* del_bounced_members
* show_members_status (perhaps show_member_statuses ?)

**Comment by ldidry** [comment]
> perhaps show_member_statuses

That would imply that the members have more than one status. Do they? Can they have `bounce` *and* `suspend` attributes set at the same time? (I have no idea what the `suspend` attribute is for, or what triggers it)

**Comment by ikedas** [comment]
> > perhaps show_member_statuses
> 
> That would imply that the members have more than one status. Do they? Can they have `bounce` _and_ `suspend` attributes set at the same time? (I have no idea what the `suspend` attribute is for, or what triggers it)

It's just an idea:
If we would integrate it with Sympa::Request framework by the future refactoring, the function to list the subscribers may be called "`review`", such as:
``` code
sympa.pl --review --list=list@domain
```
and to show them with status, either
``` code
sympa.pl --review --list=list@domain --verbose
sympa.pl --review --list=list@domain --status
```

**Comment by ldidry** [comment]
I suggest dropping the `--list`:
```
sympa.pl --review list@domain [--status]
```

`--verbose` could be used in the future to print the informations of the web table: name, reception, sources, subscribed from, updated at.

**Comment by racke** [comment]
Sounds like a good idea, so I suggest to create a separate issue for --review and remove shows_member_status from #1098.

**Comment by ldidry** [comment]
I’m ok. I’ll wait for @ikedas’ opinion.

**Comment by ikedas** [comment]
I'm ok too.

**Comment by ldidry** [comment]
PR #1098 modified with `--reset_members_bounces` and `--del_bounced_members` options

**Comment by ikedas** [comment]
Sorry to rehash this discussion, but things like the following is also possible.

> `sympa` `bouncers` `reset` _list_`@`_domain_
> `sympa` `bouncers` `del` _list_`@`_domain_
> `sympa` `review` [`--status`] _list_`@`_domain_

**Comment by racke** [comment]
Yeah that is definitely more concise :+1:

**Comment by ldidry** [comment]
Seems good to me. I will update the PR.

**Comment by ldidry** [comment]
I updated my [PR](https://github.com/sympa-community/sympa/pull/1098/files).

I followed your suggestion for

> `sympa` `bouncers` `reset` _list_`@`_domain_
> `sympa` `bouncers` `del` _list_`@`_domain_
> `sympa` `review` [`--status`] _list_`@`_domain_

I just have a small problem: `sympa review _list_` (without domain) works well, but `sympa bouncers reset _list_` does not work (`del` does not work either), it does not add the domain to the list’s name.
Do you have an idea on how could I make it work?

**Comment by ikedas** [comment]
I confirmed it works (with domain for a list in a virtual domain).  How it didn't work on your side?

**Comment by ldidry** [comment]
I thought it was because of my development VM, so I tried on my production server: still not working without the domain :thinking: 

```
# /home/sympa/bin/sympa bouncers reset foo
Invalid command 'foo'
# /home/sympa/bin/sympa bouncers reset foo@mydomain.org
No bounce errors to cancel.
```

The domain is defined in `/etc/sympa/sympa.conf`, though.

**Comment by ikedas** [comment]
@ldidry , please check #1344.
