### ISSUE TITLE
version 6.2.22, problem with virtual hosts

### ISSUE THREAD

**Issue by igorzigorz** [sympa-community/sympa#106]
Could not configure version 6.22 to work with virtual hosts. FreeBSD, --with-confdir, sysconfdir=/usr/local/etc/sympa
apache 2.4 + mod_fcgid
simple robot.conf with others  title.
Shows only the main config.
When  replace  with version 6.2.16 same config all works.

**Comment by ikedas** [comment]
Hi @igorzigorz,

You would be better to create two directories named by domain:
- EXPLDIR/_domain_ (see Sympa/Constants.pm to know where is EXPLDIR).
- SYSCONFDIR/_domain_ (where `robot.conf` is placed).
Note that these directories have to be writable by user `sympa`.

**Comment by igorzigorz** [comment]
Thanks!
I created directory EXPLDIR/domain and it worked.
Why is it better if it's mandatory?

**Comment by ikedas** [comment]
EXPLDIR/_domain_ will contain the configurations of all lists in virtual domain _domain_.  That's why this is mandatory for virtual domain.

**Comment by igorzigorz** [comment]
In any case it is bad behavior. SYSCONFDIR/domain a sufficient condition for the web interface. About EXPLDIR/domain should be a warning.
