### ISSUE TITLE
Regression in personalization feature

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#1066]
Only the **body** is processed with _web_apply_on_ set to `all`, but header and footer are skipped. So it will be not possible to restore the current behaviour with release 6.2.60.

**Comment by ikedas** [comment]
@racke, isn't it the case of `mail_apply_on`?

**Comment by racke** [comment]
I didn't yet test mail_apply_on.

On December 26, 2020 12:56:31 PM GMT+01:00, IKEDA Soji <notifications@github.com> wrote:
>@racke, isn't it the case of `mail_apply_on`?
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sympa-community/sympa/issues/1066#issuecomment-751348747

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ikedas** [comment]
Racke, could you please show the process you could reproduce the problem? Finding a reproducible case by the tester again is waste of time (that's why I usually won't start tackling the bug report before asking for the process and the logs).

**Comment by racke** [comment]
Reproducing should be relatively easy:

List configuration:

``
personalization_feature on

personalization
web_apply_on all
mail_apply_on all

```
Add `message_footer` with TT2:
`
This was sent to [% user.email %] for list [% listname %].
`
Now compose an email from the web interface with TT2 in the body. The footer of the resulting message still shows the unprocessed TT2 content.

There are no log entries telling us which part are merged.

It studied the code and I can see that two different paths are used for "all" and "footer", but the code is quite convoluted so I thought I would be easier for you to fix the problem.

If you need help, I can try an attempt on fixing that.

**Comment by racke** [comment]
Same problem for messages sent by email.

**Comment by ikedas** [comment]
Please show the log _from when_ you posted the message _to when_ the message was delivered. (log_level need not be positive).

**Comment by ikedas** [comment]
Using config and message_footer racke shown.

**Case 1**: wwsympa. On "Post" menu, clicking "Send to me" button:
``` code
Dec 28 17:05:04 xxx wwsympa[25064]: info main::do_send_mail() [robot xxx.xxx.xxx] [session 29452740266185] [client 14.3.53.137] [user xxx@xxx.xxx] [list test+001]
Dec 28 17:05:04 xxx wwsympa[25064]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message <sympa.1609142538.22441.438@xxx.xxx.xxx/shelved:decorate;merge=all> is stored into bulk spool as <1.5.1609142704.1609142704.777879.test+001@xxx.xxx.xxx_s,25064,2306>
Dec 28 17:05:04 xxx wwsympa[25064]: info main::do_compose_mail(subaction=) [robot xxx.xxx.xxx] [session 29452740266185] [client 14.3.53.137] [user xxx@xxx.xxx] [list test+001]
Dec 28 17:05:05 xxx bulk[18180]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <1.5.1609142704.1609142704.777879.test+001@xxx.xxx.xxx_s,25064,2306/s/shelved:decorate;merge=all> to Sympa::List <test+001@xxx.xxx.xxx> (priority 1) (starting 1 seconds after scheduled expedition date)
Dec 28 17:05:05 xxx bulk[18180]: notice Sympa::Mailer::store() Forked process 25727: /usr/sbin/sendmail -oi -odi -oem -f 'sympa-request@xxx.xxx.xxx' -- xxx@xxx.xxx
Dec 28 17:05:05 xxx bulk[18180]: notice Sympa::Mailer::store() Done sending message Sympa::Message <1.5.1609142704.1609142704.777879.test+001@xxx.xxx.xxx_s,25064,2306/s> for Sympa::List <test+001@xxx.xxx.xxx> (priority 1) in 1 seconds since scheduled expedition date
```
In distributed message, body was interpolated (personalized), but footer was not.

**Case 2**: wwsympa. On "Post" menu, clicking "Send to list" button (list is not moderated):
Now testing.

**Case 3**: wwsympa. On "Post" menu, clicking "Send to list" button (list is moderated):
Now testing.

**Case 4**: Posted to the list via e-mail (list is not moderated):
Now testing.

**Case 5**: Posted to the list via e-mail (list is moderated):
Now testing.

**Comment by ikedas** [comment]
Racke, if possible, could you please test the cases 2bis and so on?

> There are no log entries telling us which part are merged.

This is not accurate.  Serialized `shelved` attributes are logged.

**Comment by racke** [comment]
Indeed `shelved` is logged. Not much of help if you didn't read the code beforehand though. I will try to run some tests when I can find the time.

**Comment by ikedas** [comment]
BTW the cases I listed in above are tye case with `footer_type mime`. According to #501, the results reported by now are the same as previous version, aren't they? We have to check the cases with `footer_type append`. 

I'll check them tomorrow.  Good night.

**Comment by racke** [comment]
Same problem with `footer_type append` and moderated email. Looks like it only depends on whether _apply_on_ is set to `all `or not.

**Comment by ikedas** [comment]
I found another regression with Case 2bis.  I'll submit additional PR.

**Comment by ikedas** [comment]
* I confirmed racke's PR fixes Stanza 1 Case 1.
* I confirmed my PR fixes Stanza 1 Case 2bis.
