### ISSUE TITLE
Generation Lists Aliases 

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1077]
I m using a new server with sympa 6.2.40 on Ubuntu 20.04 after a migration from an old server sympa 6.1.24 Ubuntu 16.04
I want regenerate the lists aliases for the migrated lists into the new server, will you tell me what are the steps that i have to do ?
Note:  The aliases for new created lists is generated normally.
THank you for your response

**Comment by racke** [comment]
You can produce a complete list of aliases from the command line, e.g. `sympa --make_alias_file`.

**Comment by khaoula-abaidi** [comment]
--make_alias_file Create an aliases file in /tmp/ with all list aliases. It uses the list_aliases.tt2 template (useful when list_aliases.tt2 was changed) .
How do i have to have the aliasess into /etc/sympa/sympa_transport directly ? Or is it possible to create them into /tmp/ and then simply move them where i want without generating a new problem ?
Thank you for your response

**Comment by racke** [comment]
You can create the file with `--make_alias_file`. The output will tell you the exact location of the generated file. You can copy it to `/etc/sympa/sympa_transport`. This shouldn't cause a problem unless a list is created / changed in the meantime. It is also a good idea to run a diff between two versions.

I would also very much recommend to install etckeeper to keep track of changes in /etc.

**Comment by ikedas** [comment]
The problem looks solved.  Close.
