### ISSUE TITLE
Database tables no longer used remain after upgrade

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1078]
At first, you'd be better to fix up configuration manually.  Please read [Upgrading notes](https://sympa-community.github.io/manual/upgrade/notes.html).
- [Upgrading from Sympa 6.1.x or earlier](https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-61x-or-earlier)
- Then [Upgrading from Sympa 6.2.x or earlier](https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-62x-or-earlier)

_Originally posted by @ikedas in https://github.com/sympa-community/sympa/issues/1054#issuecomment-741633130_

**Comment by ikedas** [comment]
@khaoula-abaidi , what is the question you want to ask?

**Comment by khaoula-abaidi** [comment]
i followed the notes for the migration but the structure of the database (sympa 6.2.40) still contains the 16 tables when they should be 14 (bulkspool_table and bulkmailer_table more tables).
When I applied the commands upgrade_bulk_spool.pl and upgrade_bulk_send.pl does not change anything on the structure of the database.

**Comment by ikedas** [comment]
Existing tables won't be removed, even if they won't be used anymore by the new version of Sympa.  That's why still there are `bulkspool_table` and `bulkmailer_table`.

**Comment by ikedas** [comment]
There seem no more questions.  Close.
