### ISSUE TITLE
HTML hyperlinks not working in web archive (MHonArc)

### ISSUE THREAD

**Issue by MargoM** [sympa-community/sympa#108]
Hello!
Location: wws/arc/listname (web archive)
I discovered that HTML hyperlinks are not working (if I tried to rebuild old archives). Also I reproduced this issue in demo.sympa.org. E-mail links (mailto) works fine, but not HTML links (href). All hyperlinks work when I read list e-mails in email client (Thunderbird).

Some "href" will disappear, see second line:
```
</span>For registration please follow the</b> </span><a rel="nofollow"><b><span style="font-family:&quot;Book Antiqua&quot;">link</span></b></a><span style="font-family:&quot;Book Antiqua&quot;">.
</span>For registration please follow the</b> </span><a rel="nofollow" href="http://link.com/"><b><span style="font-family:&quot;Book Antiqua&quot;">link</span></b></a><span style="font-family:&quot;Book Antiqua&quot;">.
```

Or this problem is related to MHonArc?

MHonArc 2.6.19
Sympa 6.2.22

**Comment by ikedas** [comment]
Duplicate of PR #48, #45.

Please check [allowed_external_origin](https://sympa-community.github.io/man/sympa.conf.5.html#allowed_external_origin) introduced on Sympa 6.2.20.

**Comment by MargoM** [comment]
Thanks again ikedas! Case closed.
