### ISSUE TITLE
Digest.tt2

### ISSUE THREAD

**Issue by JCEYMER** [sympa-community/sympa#1080]
Hello,
For people who want group messages, I used "X-Sympa-Attach: yes" in the gigest.tt2 file.
The result is correct, except that the message is systematically attached when sending.
This causes several access providers to refuse "spam".
I wish I could test messages with attached files, but I can’t find the instruction.
Thank you.

Bonjour,
Pour les personnes qui veulent des messages groupés, j'ai utilisé "X-Sympa-Attach: yes" dansle fichier gigest.tt2.
Le résultat est correct, sauf que le message est systématiquement attaché lors de l'envoi. 
Cela provoque chez plusieurs fournisseurs d'accès des refus "Spam".
J'aimerais pouvoir tester les messages ayant des fichiers attachés mais je ne trouve pas l'instruction.
Merci.
Mon fichier digest.tt2 / My file digest.tt2 above :
From: [% to %]
To: [% to %]
Reply-to: [% to %]
Subject: [% FILTER qencode %][%|loc(list.name,date)%]%1 Digest %2[%END%] [% IF total_group > 1 -%]([% current_group %]/[% total_group %])[% END %][%END%]
Content-Type: multipart/mixed; boundary="[% boundary1 %]"

--[% boundary1 %]
Content-Disposition: inline
Content-Type: text/html; 

<html lang="fr">
<head><body>
<p><b><font color="#0000ff">Le Cybergroupe Généalogique de Charentes Poitou</font></b></p>
<p>[%|loc(list.name,date)%] Forum : %1  %2[%END%];<br /> <font color="#0000ff"> [%|loc%]Table of contents:[%END%] </font></p>
<ul>
[% FOREACH m = msg_list -%]
<li><a name="N0"><a href="#N[% m.id %]">[% m.id %] - [% m.subject %]</a> - [% FOREACH patronyme IN m.from.split('\ \(')%]  [% patronyme.replace('"','') %] [% BREAK %][% END%]
 </li>
[% END %]
</ul>
<hr color="#0000ff">
[% FOREACH m = msg_list -%]
    <p><b><a name="N[% m.id %]">[% m.id %] -</a><font color="#0000ff"> [% m.subject %]</b></font> transmis par  : <b> [% FOREACH patronyme IN m.from.split('\ \(')%]  [% patronyme.replace('"','') %] <br/></b>Date: [% m.date %]  [% BREAK %]
[% END%] <br/>
<hr  COLOR="red" SIZE="2">
<p>
<br>

--[% boundary1 %]
Content-Type: multipart/digest; boundary="[% boundary2 %]"
Mime-Version: 1.0

This is a multi-part message in MIME format...

--[% boundary2 %]
Content-Type: message/rfc822
Content-Disposition: inline
X-Sympa-Attach: yes

[%m.msg_body%] 

--[% boundary2 %]--

--[% boundary1 %]
Content-Disposition: inline
Content-Type: text/html; 
<br>

<hr  COLOR="red" SIZE="4">
<br>

<table align="center">
<tr>
<td><a href="[%|loc(m.from.replace('"',''))%]mailto: %1[%END%]?Subject= [% m.subject.replace('"','') %] "> Répondre  à l'expéditeur</a></td>
<td> <--></td>
<td><a href="mailto: [% to %]?Subject= [% m.subject.replace('"','') %] "> Répondre à la liste</a></td>
<td> <--> </td>
<td><a href="#N0">Revenir à la liste</a></td>
</tr>
</table>
<br>
<hr  COLOR="red" SIZE="4">
[% END %]

[%|loc(list.name,date)%]End of %1 Digest %2[%END%]
<br>
<br>
<h4>*********************************************<br />
Le Cybergroupe Généalogique de Charentes Poitou<br />
https://www.cgcp.asso.fr/ (optimisé PC, iPod, iPad, iPhone…) et présent sur Facebook et Twitter comme Généalogie Charentes Poitou<br />
Réglage de la réception des messages dans "Mon Espace" puis "Mon Compte Personnel" : <br />
• Mails individuels : vous recevrez chaque message individuellement au fur et à mesure de leur envoi.<br />
• Envoi groupé au format texte : Vous recevrez les messages groupés par 25 le matin vers 8 heure (messages de la veille et de la nuit).<br />
• Pas de mails : vous ne recevez aucun message. Vous pouvez toujours lire les messages en vous connectant sur la liste. (Utile pendant vos vacances.)</h4>
</body></html>

--[% boundary1 %]--
--

**Comment by ikedas** [comment]
Duplicate issue.  Close.
