### ISSUE TITLE
Unable to find Scenario file After Migration 6.1.24 and Scenari 6.2.40

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1081]
At first, you'd be better to fix up configuration manually.  Please read [Upgrading notes](https://sympa-community.github.io/manual/upgrade/notes.html).
- [Upgrading from Sympa 6.1.x or earlier](https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-61x-or-earlier)
- Then [Upgrading from Sympa 6.2.x or earlier](https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-62x-or-earlier)

_Originally posted by @ikedas in https://github.com/sympa-community/sympa/issues/1054#issuecomment-741633130_

I followed the documentation for the migration for the scenarios and renamed the scenarios as shown (original scenari name to final scenari names).
I receive as an error that the scenario access_web_archive.*  cannot be found.
On the old server (sympa 6.1.24) the scenarios are access_web_archive.* 
On the new server (sympa 6.2.40) renamed to archive.web_access. *.
While for the documentation web_archive.access.* to archive.web_access.*.
Did i miss any step so  i have to rename access_web_archive.*  to web_archive.access.* then rename it to archive.web_access.* ?
As a note : the owner of the scenario files is sympa into /etc/sympa/scenari/ directory

**Comment by khaoula-abaidi** [comment]
I followed the documentation for the migration for the scenarios and renamed the scenarios as shown (original scenari name to final scenari names).
I receive as an error that the scenario access_web_archive.*  cannot be found.
On the old server (sympa 6.1.24) the scenarios are access_web_archive.* 
On the new server (sympa 6.2.40) renamed to archive.web_access. *.
While for the documentation web_archive.access.* to archive.web_access.*.
Did i miss any step so  i have to rename access_web_archive.*  to web_archive.access.* then rename it to archive.web_access.* ?

**Comment by ikedas** [comment]
On 6.1:
  - Parameters in list `config` file may be written as below:
    Getting archive by mail:
    ``` code
    archive
      ...
      access XXX
      ...
    ```
    In above, XXX is either `public` (`open`), `private`, `owner` or `closed`.

    Reading archive via web:
    ``` code
    web_archive
      ...
      access XXX
      ...
    ```
  - Scenario file:
    Getting archive by mail: _No scenario files_
    Reading archive via web: ``scenari/access_web_archive.XXX``

On 6.2.40 and later:
  - Parameters in list `config` file may be written as below:
    ``` code
    archive
      ...
      mail_access XXX
      ...
      web_access XXX
      ...
    ```
  - Scenario files:
    Getting archive by mail: ``scenari/archive_mail_access.XXX``
    Reading archive via web: ``scenari/archive_web_access.XXX``

**Comment by ikedas** [comment]
There seem no more questions.  Close.
