### ISSUE TITLE
No mail to listmasters after renaming a mailing list

### ISSUE THREAD

**Issue by Salo15** [sympa-community/sympa#1083]
When renaming a mailing list, in some cases no mail is sent to the listmasters with the information that the list has been renamed and the link to the web page to approve/reject the list.

We use Sympa version 6.2.16 and Sympa is installed as Debian Package.

This problem has been occurring for a few months. We run 2 mailing list servers on different machines and the problem occurs on both machines.
But it does not occur in all cases. In some cases an email is sent to the list masters when renaming a mailing list.
On the other hand, when creating a new list via a template and when copying a list, an e-mail is sent to the listmasters in all cases.

If the e-mail is sent to the list masters, the following log entry can be found in the Sympa log, for example:
Nov 9 09:40:59 lists4.scc.kit.edu wwsympa[3815]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <abc@lists.kit.edu.16049112
59,3815,6911>; envelope_sender=abc@lists.kit.edu; message_id=sympa.1604911259.3815.189@lists.kit.edu; recipients=sabine.lorenz@kit.edu; sender=sympa@lists.k
it.edu; template=listmaster_notification; type=request_list_renaming

In cases where no email is sent to the listmasters, there is no entry of this type in the Sympa log either. From this you can see that the error actually already occurs in Sympa and it is not just a problem of incorrect mail delivery.

Do you have any idea what could be the reason that this email is not sent in all cases?

Kind regards,
Sabine

**Comment by ikedas** [comment]
If newly created list (by renaming or copying a list) was kept pending, notification to listmaster with `request_list_renaming` type will be sent.  Otherwise notification won't be sent to listmaster.

By default, `create_list` parameter in `sympa.conf` is `public_listmaster` by which newly created lists will be kept pending, _when_ the user who created list _was not the listmaster_.

**Comment by ikedas** [comment]
> Normally the emails to the listmasters are also sent correctly, but we noticed that after renaming lists in the last months sometimes no mails information mail was sent.
> The users who renamed the mailing list were also not listmasters and the list also remains in the pending status.
> Only no information mail is sent to the listmasters.
> As I wrote in my first mail there is no entry in the logs for this notification and it seems that this email is not sent by Sympa and this seems to be a bug.

Indeed it's strange.  Just in case, could you please show the log of Sympa _from when_ the user visited "Rename list" page _to when_ the renaming completed?  (If you don't mind disclosing the logs to public, please email it to me.)

**Comment by Salo15** [comment]
Thank you for your offer.

I will send you the log entries if the problem occurs again. The last time was a little more than a week ago, so we no longer have the log entries.

 

What is your e-mail address, where I can write to you directly?

 

Kind regards,

Sabine

 

Von: IKEDA Soji <notifications@github.com> 
Gesendet: Mittwoch, 20. Januar 2021 03:18
An: sympa-community/sympa <sympa@noreply.github.com>
Cc: Lorenz, Sabine (SCC) <sabine.lorenz@kit.edu>; Author <author@noreply.github.com>
Betreff: Re: [sympa-community/sympa] No mail to listmasters after renaming a mailing list (#1083)

 

Normally the emails to the listmasters are also sent correctly, but we noticed that after renaming lists in the last months sometimes no mails information mail was sent.
The users who renamed the mailing list were also not listmasters and the list also remains in the pending status.
Only no information mail is sent to the listmasters.
As I wrote in my first mail there is no entry in the logs for this notification and it seems that this email is not sent by Sympa and this seems to be a bug.

Indeed it's strange. Just in case, could you please show the log of Sympa from when the user visited "Rename list" page to when the renaming completed? (If you don't mind disclosing the logs to public, please email it to me.)

**Comment by ikedas** [comment]
> What is your e-mail address, where I can write to you directly?

Please see the link on [my personal page](https://github.com/ikedas).  Thank you.

**Comment by ikedas** [comment]
Hi @Salo15 ,
I checked the log you sent to me.  In conclusion, the message looks sent to the listmaster(s).

Notifications for the listmasters are sometimes "stacked" (multiple messages are sent in batch) to avoid flooding of messages.  Perhaps your listmaster(s) may have received a message including some messages, with the subject "_You have xx "list_renaming_request" tagged notifications_" (or similar phrase in the other language).  Could you please try to see if there are any such messages?

**Comment by Salo15** [comment]
Hi,

 

I checked again and the listmasters didn’t get the message with the information that the list is renamed and can be activated.

After activating the mailing list via the website they get the message that the mailinglist is activated but they didn’t get the first information mail with the link to activate the mailinglist.

 

Moreover I see this e-mail also still in the queue /var/spool/sympa/bulk/bad/msg:

 

[root@lists4(KIT) msg]# ls -la /var/spool/sympa/bulk/bad/msg/*testliste_umbenennen_*

-rw-r----- 1 sympa sympa 786 Jan 25 11:25 /var/spool/sympa/bulk/bad/msg/1.5.1611570334.1611570334.801600.testliste_umbenennen_1@lists.kit.edu_s,10548,3380 <mailto:/var/spool/sympa/bulk/bad/msg/1.5.1611570334.1611570334.801600.testliste_umbenennen_1@lists.kit.edu_s,10548,3380> 

 

[root@lists4(KIT) msg]# more /var/spool/sympa/bulk/bad/msg/1.5.1611570334.1611570334.801600.testliste_umbenennen_1@lists.kit.edu_s,10548,3380

X-Sympa-Message-ID: sympa.1611570334.10548.407@lists.kit.edu

X-Sympa-Sender: sympa@lists.kit.edu

X-Sympa-Display-Name: "SYMPA"

Return-Path: <sympa-request@lists.kit.edu>

Message-Id: <sympa.1611570334.10548.407@lists.kit.edu>

Date: Mon, 25 Jan 2021 11:25:34 +0100

From: "SYMPA" <sympa@lists.kit.edu>

MIME-Version: 1.0

Content-Type: text/plain; charset="UTF-8"

Content-Transfer-Encoding: QUOTED-PRINTABLE

Auto-Submitted: auto-generated

To: Listenadministrator <listmaster@lists.kit.edu>

Subject: Liste "testliste_umbenennen_1" wird umbenannt

Content-length: 202

X-Mailer: Sympa 6.2.16

 

sabine.lorenz@kit.edu hat Liste "testliste_umbenennen_1" in

"testliste_umbenennen_2" umbenannt

 

 

Zum Aktivieren/L=C3=B6schen dieser Mailingliste:

https://www.lists.kit.edu/sympa/ticket/72443258117747

 

 

 

 

 

So it seems that the email cannot be processed in the bulk queue.

Unfortunately, however, I do not see any entries in the Sympa log that and why this email cannot be processed and is moved to bad.

 

Kind regards,

Sabine

 

 

 

 

Von: IKEDA Soji <notifications@github.com> 
Gesendet: Dienstag, 26. Januar 2021 09:27
An: sympa-community/sympa <sympa@noreply.github.com>
Cc: Lorenz, Sabine (SCC) <sabine.lorenz@kit.edu>; Mention <mention@noreply.github.com>
Betreff: Re: [sympa-community/sympa] No mail to listmasters after renaming a mailing list (#1083)

 

Hi @Salo15 <https://github.com/Salo15>  ,
I checked the log you sent to me. In conclusion, the message looks sent to the listmaster(s).

Notifications for the listmasters are sometimes "stacked" (multiple messages are sent in batch) to avoid flooding of messages. Perhaps your listmaster(s) may have received a message including some messages, with the subject "You have xx "list_renaming_request" tagged notifications" (or similar phrase in the other language). Could you please try to see if there are any such messages?

**Comment by ikedas** [comment]
I checked the log again, and found that sending of notification message was aborted, This is probably due to a bug in Sympa 6.2.16.

  * To send the message, you may restore it from `bad` directory (Note that `bulk.pl` daemon should be stopped during this operation):
    ``` bash
    # cd /var/spool/sympa/bulk/
    # mv bad/msg/1.5.1611570334.1611570334.801600.testliste_umbenennen_1@lists.kit.edu_s,10548,3380 msg/
    # mv bad/pct/1.5.1611570334.1611570334.801600.testliste_umbenennen_1@lists.kit.edu_s,10548,3380 pct/
    ```
  * To fix this bug, upgrade Sympa to recent version.

**Comment by Salo15** [comment]
Ok, thanks for your help in finding the error and the informations.

Regards,
Sabine
