### ISSUE TITLE
Unable to include ',' characters in params to data source.

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1088]
Expected Behavior
-----------------

Given an LDAP data source of the form:
```
filter (&(objectClass=user)(memberOf=[% param.0 %]))
```
I would hope to be able to supply param.0 of the form:
```
CN=foo,OU=Groups,OU=UIS,OU=Inst,DC=blue,DC=cam,DC=ac,DC=uk
```

Current Behaviour
----------------

param.0 seems to be trimmed at the first comma, so effectively just  " CN=foo". Possibly a security concern? I don't know if '.' is considered special

Possible Solution
-----------------

Allow  commas in param.0

Context
-------

I am attempting to extract a list of email addresses from an Active Directory LDAP source without having to resort to include_ldap_2level_query, which involves a separate LDAP query for each member of the list to turn DN into mail.

The following  **include_ldap_query** works nicely:

```
include_ldap_query
name  Blue AD (filter on groupName)
host  blue.cam.ac.uk
port  636
user  XXX@blue.cam.ac.uk
passwd XXX
use_ssl yes
ssl_version tls
suffix DC=blue,DC=cam,DC=ac,DC=uk
filter (&(objectClass=user)(memberOf=CN=foo,OU=Groups,OU=UIS,OU=Inst,DC=blue,DC=cam,DC=ac,DC=uk)) 
scope sub
select first
attrs mail
timeout 10
```
but I would like to be able to replace the DN with a param.0 which can be supplied by the listmaster/owner using wwsympa.

Alternately a include_ldap_2level_query which can map CN to DN for an active directory group, and then expand that as a single LDAP query (see my message to sympa-users, dated 2021-01-11)

**Comment by dverdin** [comment]
Hi,
Could you please provide your Sympa version?
Also, do your logs show anything relevant (such as an error) when you try to synchronize your list?

Thanks!

**Comment by dpc22** [comment]
6.2.60 (plus one patch, provided by Soji).

No errors, but if I add a quick debug statement of the form:
```
$log->syslog('info', 'Filter: %s', $ldap_filter)
```
to /usr/share/sympa/lib/Sympa/DataSource/LDAP.pm, I am told:
```
Jan 19 11:12:06 lists-2 wwsympa[9393]: info Sympa::DataSource::LDAP::_open_operation() Filter:
  (&(objectClass=user)(memberOf=CN=UIS-Hermes.Migration-access)) 
```
which is everything in param.0 up until the first comma character. wwsympa reports 0 results for that filter:
```
Jan 19 11:12:06 lists-2 wwsympa[9393]: info Sympa::Request::Handler::include::_twist() Sympa::Request 
  <action=include;context=test-blue@lists.cam.ac.uk;role=owner>: Success, 0 added, 0 deleted, 0 updated
```
which isn't a surprise as it isn't a full DN.

**Comment by dverdin** [comment]
I see; Actually, it was obvious: the parameters for data sources are comma-separated.
Meaning you would define, in your member_include parameter:

source_parameters param.0,param.1,param.2,etc.

I'll look if there is workaround.

**Comment by dverdin** [comment]
Ideally, enclosing the parameters between quotes should prevent splitting them.

For example:

`source_parameters 'CN=foo,OU=Groups,OU=UIS,OU=Inst,DC=blue,DC=cam,DC=ac,DC=uk'`

would be a single parameter without the quotes:

`param.0 : CN=foo,OU=Groups,OU=UIS,OU=Inst,DC=blue,DC=cam,DC=ac,DC=uk`

But it can be more complex, such as:

`source_parameters 'CN=foo,OU=Groups,OU=UIS,OU=Inst,DC=blue,DC=cam,DC=ac,DC=uk',tagada
`
Which should give two parameters:

```
param.0 : CN=foo,OU=Groups,OU=UIS,OU=Inst,DC=blue,DC=cam,DC=ac,DC=uk
param.1 tagada
```

**Comment by dverdin** [comment]
I think this code could be a start:

```
my $param = 'CN=foo\,OU=Groups\,OU=UIS\,OU=Inst\,DC=blue\,DC=cam\,DC=ac\,DC=uk,tagada';
my @params;
my $index = 0;
my @subparts;
foreach my $part (split ',', $param) {
    if ($part =~ m{\\\Z}) {
        $part =~ s{\\\Z}{};
        push @subparts, $part;
    } else {
        push @subparts, $part;
        $params[$index] = join ',', @subparts;
        $index++;
        @subparts = ();
    }
}

```
Just a quickstart. It certainly needs ironing.

**Comment by ikedas** [comment]
Duplicazte of #466.  See that issue and related discussions.
