### ISSUE TITLE
Document cookie parameter obsolescence

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa#1089]
The `cookie` parameter is now obsolete but still used in older instances and required to upgrade to newer versions of Sympa.

If I understand correctly, Sympa now uses salted hashes, which don't need the cookie parameter, so it is useless. I might be wrong.

If I'm right, as suggested in #1086, it would be useful to document it.

### Point 1 : what to document?

The informations to display should be:

1. the parameter is now obsolete. Fresh install should not use it.
2. When upgrading to the latest version of Sympa, people will need to keep the cookie parameter in their config if they had it before. But immediately after the upgrade and before restarting Sympa, the can remove it.

This last point needs more work. We need to be sure there are no consequences to remove the cookie parameter. Only code inspection can reveal it.

As far as I understand, it is only used in four places:

- in the creation of the initial temporary password (Sympa::tools::Password).
- In creating the checksum used for upgrade_send_spool.pl
- In computing the old password value in upgrade_sympa_password.pl
- In creating the attachment URL for archived messages (Sympa::Archive)

For the archives: is is only when building the HTML view. So it is a one shot: archives built with the cookie parameter still work when it disappears from the config. If you rebuild the archives, links are created without the cookie parameter and that's it.

For the passwords: new passwords can be created without the cookie parameter. Old passwords can't be used wihtout it BUT, the upgrade_sympa_password.pl script will move the old encryption to MD5 salted hash. So after this script has been run, the cookie parameter is no longer needed to validate passwords.

Finally, in upgrade_send_spools.pl, the cookie parameter is used to get a checksum of the message. This checksum must be the same as the one used to initially store the message in the msg spool, so it is mandatory for this operation. But never after.

All in all, it looks safe to tell users to remove the cookie parameter after the next upgrade to the latest stable Sympa.

### Point 2: how to document?

To have an up-to-date documentation, we need to change Sympa::Conf::Schema.

1. add "obsolete => 1," to the parameter description,
2. Modify the "gettext_comment" to add an explanation about precautions to take before removing it from the config file.

Afterwards, the gpldoc will be generated from the sources.
Is it correct?

**Comment by ikedas** [comment]
Main issue: #1091

**Comment by dverdin** [comment]
OK. Moving to #1091. I think it is safe to close the current issue.
