### ISSUE TITLE
Failed to load senario topics_visibility Sympa 6.2.40  && Sympa 6.1.24

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1096]
Using Sympa 6.2.40:
I have into my sympa.log file this error : 
Jan  1 07:18:56 my_vm wwsympa[36884]: err Scenario::request_action() Failed to load scenario for 'topics_visibility'
I had change my topics_visibility* files into -rw-r--r-- 1 sympa sympa  :
/etc/sympa/scenari/topics_visibility.intranet
/etc/sympa/devlistes.my_robot.fr/scenari/topics_visibility.intranet
like the default files : 
/usr/share/sympa/default/scenari/topics_visibility.identified
/usr/share/sympa/default/scenari/topics_visibility.noconceal
/usr/share/sympa/default/scenari/topics_visibility.default
/usr/share/sympa/default/scenari/topics_visibility.conceal

I had also change the permissions to (-rw-r--r-- 1 sympa sympa ) same thing for my topics.conf files /etc/sympa/topics.conf
/etc/sympa/devlistes.my_robot/topics.conf
like the default topics.conf
/usr/share/sympa/default/topics.conf

Then i have reload with restarting sympa and apache services 
Note : I have the same problem (err Scenario::request_action() Failed to load scenario for 'topics_visibility') into my sympa.log file
using Sympa 6.1.24 version.
Is it possible to resolve this error ?

**Comment by ikedas** [comment]
Hi @khaoula-abaidi ,

Could you please show us these things?
* the log _from when_ you accessed to the page in your Sympa site _to when_ the log message in question was output.
* the content of scenario file in question, maybe `topics_visibility.intranet`.

**Comment by khaoula-abaidi** [comment]
Hi @ikedas ,
Log message:
Jan 25 08:34:44 localhost wwsympa[2832817]: err main::#1525 > main::check_param_in#2791 > main::export_topics#15721 > Sympa::Scenario::request_action#493 Failed to load scenario for "topics_visibility"
Content scenario:
title.gettext intranet access
match([env->remote_host],/insa-lyon\.fr$/)       smtp,dkim,md5,smime    -> do_it
match([sender],/insa-lyon\.fr$/)            smtp,dkim,md5,smime    -> do_it
is_subscriber([listname],[sender])         smtp,dkim,md5,smime    -> do_it
is_owner([listname],[sender])              smtp,dkim,md5,smime    -> do_it
is_editor([listname],[sender])             smtp,dkim,md5,smime    -> do_it
is_listmaster([sender])                    smtp,dkim,md5,smime    -> do_it
true()                                     smtp,dkim,md5,smime     -> reject,quiet

**Comment by ikedas** [comment]
In `topics_visibility.intranet`
``` code
is_subscriber([listname],[sender]) smtp,dkim,md5,smime -> do_it
is_owner([listname],[sender]) smtp,dkim,md5,smime -> do_it
is_editor([listname],[sender]) smtp,dkim,md5,smime -> do_it
```
these lines seem the root of error.  `topics_visibility` scenario doesn't work under context of particular list.
Though I can't test soon with versions you are using, perhaps listmasters may receive the messages reporting errors in scenario.

**Comment by khaoula-abaidi** [comment]
To have a list of lists that use this scenario (topics_visibility.intranet)  into my sympa6.2.40 I had used into the list_data directory /var/lib/sympa/list_data/ :$  grep "topics" */*/config
then 
grep "visibility intranet" */*/config
But i want had all lists that use topics_visibility.intranet
Is there a solution ether than grep -E "topics|visibility intranet" */*/config because it lists for me lists which have a topic into their config file or "visibility intranet"

**Comment by ikedas** [comment]
* `topics_visibility` scenario (configured by `visibility` parameter in `topics.conf` file under SYSCONFDIR directory) controls visibility of topic items on "Browse lists by categories" page.
* Visibility of list items on "Index of lists" page is controled by `visibility` scenario (configured by `visibility` parameter in `config` file under list directory).

Currently, list items on "Index of lists" page cannot be filtered by the topics which each list belongs to.

**Comment by ikedas** [comment]
There seem no more questions.  Close.
