### ISSUE TITLE
Duplicate precedence header tripping up Amazon SES

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#110]
```
Precedence: list
Precedence: bulk
```

This is causing Amazon SES to reject the message, thus it is a quite serious problem.

`status=bounced (host email-smtp.eu-west-1.amazonaws.com[52.30.4.9] said: 554 Transaction failed: Duplicate header 'Precedence'. (in reply to end of DATA command))`

**Comment by racke** [comment]
See https://github.com/sympa-community/sympa/blob/master/src/lib/Sympa/Spindle/TransformOutgoing.pm#L89.

**Comment by ikedas** [comment]
`Precedence:` field has no standard definition. Duplicate fields with values `list` and `bulk` were intended (See also below).

I suppose a better solution is removing this (these) field, if we can confirm that the other measures to prevent mail loop are sufficiently effective.

----
1. [RFC 2076, 3.9](https://tools.ietf.org/html/rfc2076#section-3.9). "Precedence:".
2. [[sympa-users] Handling out/of/office replies to list](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2007-12/476C0EB8.7010605%40electricembers.net). Dec. 2007.
3. [Commit](https://github.com/sympa-community/sympa/commit/0a7fb7f6586fb91469ace25da0579d9dc8944fa8).

**Comment by racke** [comment]
We actually need this field to prevent autoreplies hitting the list, but it should be configurable instead of hardcoded. That would solve my problem.

**Comment by ikedas** [comment]
@racke, does PR #152 solve the problem?

**Comment by ikedas** [comment]
As PR #152 was merged, this issue is closed.
