### ISSUE TITLE
Add --review list@domain [--status] to sympa.pl

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#1102]
Follow-up of #1058 

Sympa should have a `--review list@domain [--status]` option to list all subscribers of the list, and `--status` would show the regular, bounced and suspended users separately.

**Comment by ikedas** [comment]
I made another proposal #1303 (a part of it has been submitted as PR).  According to it, the command line would be:
> `sympa` `review` [ `--status` ] _list_`@`_domain_

**Comment by ikedas** [comment]
Fixed. Close.

**Comment by Stupidpeopleicoming** [comment]
786

**Comment by Stupidpeopleicoming** [comment]
****

**Comment by Stupidpeopleicoming** [comment]
> Follow-up of #1058
> 
> Sympa should have a `--review list@domain [--status]` option to list all subscribers of the list, and `--status` would show the regular, bounced and suspended users separately.

Delete devices

**Comment by Stupidpeopleicoming** [comment]
-l
