### ISSUE TITLE
an endless email

### ISSUE THREAD

**Issue by toto1825** [sympa-community/sympa#1103]
I've been receiving the following email every day for some time now (1728/24= 72 days). Thank you for taking the necessary action to stop this endless loop... 

Sujet : | Warning: message 1kfN6Y-008w0k-CK delayed 1728 hours
Date : Fri, 29 Jan 2021 10:13:31 -0300
De: Mail Delivery System <Mailer-Daemon@sympa.traversees.org>
A : ddupuis@d2consult.fr

This message was created automatically by mail delivery software.
A message that you sent has not yet been delivered to one or more of its
recipients after more than 1728 hours on the queue on sympa.traversees.org.

The message identifier is: 1kfN6Y-008w0k-CK
The subject of the message is: UNSUBSCRIBE liste
The date of the message is: Wed, 18 Nov 2020 14:02:33 +0100

The address to which the message has not yet been delivered is: sympa@forums.fabriquedestransitions.net

No action is required on your part. Delivery attempts will continue for
some time, and this warning may be repeated at intervals if the message
remains undelivered. Eventually the mail delivery software will give up,
and when that happens, the message will be returned to you.

Version
-------

Installation method
-------------------

Expected behavior
-----------------

Actual behavior
---------------

Additional information
----------------------

**Comment by racke** [comment]
That actually looks like a problem with your mail server configuration (Exim?). It should stop delivery attempts after a couple of days and discard the original message.

**Comment by dpc22** [comment]
1kfN6Y-008w0k-CK  is definitely Exim. The delay warning messages are controlled by:

# single warning after 24h (30d will never be reached)
delay_warning                   = 24h:30d

while retry with exponential backoff and a 5 day timeout backupstop looks something like:

begin retry
*@*                     *               F,2h,15m; G,24h,15m,1.1; F,5d,3h

The warning messages should have a null return path <>. Presumably  Mailer-Daemon@sympa.traversees.org isn't routed to Sympa.

**Comment by toto1825** [comment]
Please confirm that this is indeed a problem! 
I am actually not a developer but a user. I have written directly to the list facilitator but it seems he doesn't know who to report the problem to. I don't know who to contact either. How are things organised? Who takes care of the server configuration for a given list?

**Comment by ikedas** [comment]
Hi @toto1825 ,

The message triggered warnings seems related to the mailing list named "liste".  In fact [there is such a [list on noticed domain](https://www.forums.fabriquedestransitions.net/sympa/info/liste).  Does this list look familiar to you?
Anyway you'd be better to contact the owners (propriétaires) of this list. --- Perhaps the owners may not fix the problem, however, through them they can communicate the problem to listmasters (system administrators).

**Comment by ikedas** [comment]
Stagnating issue.  Close for now.
