### ISSUE TITLE
Default Config Breaks Web GUI Post

### ISSUE THREAD

**Issue by olivov** [sympa-community/sympa#1104]
The use_html_editor config option by default is set to 'off'. In 6.2.60, this appears to break the logic for whether or not a message posted throught the Sympa web interface should be text/plain or text/html. The particular block that I believe is the pain point:

https://github.com/sympa-community/sympa/blob/3392c83931aee27cbe7db61b7673b0816d1a7f27/src/cgi/wwsympa.fcgi.in#L14869-L14876

Our current config has use_html_editor commented out and uses the default value of 'off' which causes messages posted from the web interface to be sent out as 'text/html' and mucks with newlines in the text.

Version
-------
6.2.60

Installation method
-------------------
Source

Expected behavior
-----------------
Messages posted through the web interface should be sent as 'text/plain' when use_html_editor is set to off or 0.

Actual behavior
---------------
Messages posted through the web interface are sent as 'text/html' when use_html_editor is set to 'off'.

**Comment by ikedas** [comment]
Hi @olivov ,
[This patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1105.patch) may fix the bug you reported.  Could you please check it?  This fix will be included in the next stable release.
