### ISSUE TITLE
Protect web archive against spam harvesters: "only show gecos" doesn't seem to work

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1107]
Version
-------
6.2.60

Installation method
-------------------
rpm

Expected behavior
-----------------

A message with:

```From: David Carter <dpc22@cam.ac.uk>```

should be displayed as:

```From: David Carter```

in the list archives  when the web_archive_spam_protection list setting is "gecos" (only show Gecos)

Actual behavior
---------------

The full email address is displayed. 

```From: David Carter <dpc22@cam.ac.uk>```

If I pick: "at" (replace @ characters) instead, I see:
 
```From: David Carter <dpc22 AT cam.ac.uk>```

which is what I would expect

Additional information
----------------------

None

**Comment by dpc22** [comment]
src/cgi/wwsympa.fgi.in
```
# DEPRECATED.  Use [%|obfuscate()%] in template.
#sub get_protected_email_address;
```
./src/lib/Sympa/Template.pm
```
sub _obfuscate {
    my ($context, $mode) = @_;

    return sub {shift}
        unless grep { $mode eq $_ } qw(at javascript);
```
no mention of gecos there.

**Comment by ikedas** [comment]
You are right.  That fix will be included in the next release.  Thank you!
