### ISSUE TITLE
Replace 'blacklist' with more neutral term 'blocklist' or 'denylist'

### ISSUE THREAD

**Issue by toonmaster** [sympa-community/sympa#1111]
Expected Behavior
-----------------
Rename 'blacklist' terms in the code to be a more neutral term such as 'blocklist' or 'denylist'.

Current Behavior
----------------
Currently, there is a blacklist feature to block sender addresses. There is a menu item under this name and code that utilizes the term in various ways.

Possible Solution
-----------------
Rename 'blocklist' to a more neutral term.

Context
-------
In our university setting, a directive has been given to cease using 'blacklist' and 'whitelist' in favor of other terms.

**Comment by ikedas** [comment]
FYI:
  * An external plugin for Sympa (however it is [described in official documentation](https://sympa-community.github.io/manual/customize/template-plugins-modwhitelist.html)) uses the term "whitelist".
  * In [a test case in the test suite](https://github.com/sympa-community/sympa/blob/6.2.56/t/Scenario.t#L44), the word "sender_whitelist" is used as the name of a custom variable.

IMHO alternative wording would be better also to consider those usages.

**Comment by ikedas** [comment]
Another FYI:

  * I compiled [translation of "blacklist" on Sympa](https://gist.github.com/ikedas/8ced555f43c42fbb27c59ed1b0621814).
    However, even in languages that use the word corresponding to "black," the meaning of such word is not exactly the same as in US English, so  in languages other than English, each language should decide whether or not to replace it.

**Comment by dverdin** [comment]
For information, you can perfectly modify the template in the web interface to change the wording.
You can access templates customization through the "template" section of the listmaster administration.

**Comment by ldidry** [comment]
> so in languages other than English, each language should decide whether or not to replace it.

If we replace `blacklist` with `denylist`, there is few risk that translators keep the blacklist translation.

**Comment by ikedas** [comment]
> > so in languages other than English, each language should decide whether or not to replace it.
> 
> If we replace `blacklist` with `denylist`, there is few risk that translators keep the blacklist translation.

On Sympa, US English messages are the keys of all translated (localized) messages in the other languages.  However, there is no worry changing US English messages.  A bit long description follows ---

If English "translation" in the gettext object file for US English `en_US.po` was changed, [`correct_msgid` script](https://github.com/sympa-community/sympa/blob/6.2.60/support/README.support.md) will keep the translation of all the other languages in sync.  For example, `en_US.po` was changed to
``` gettext
#: src/lib/Sympa/Config/Schema.pm:1383
msgid "Use blacklist"
msgstr "Use denylist"

```
`correct_msgid` modifies an entry in `fr.po`
``` gettext
#: src/lib/Sympa/Config/Schema.pm:1383
msgid "Use blacklist"
msgstr "Utilise la liste noire"

```
to add a new entry
``` gettext
#: src/lib/Sympa/Config/Schema.pm:1383
msgid "Use denylist"
msgstr "Utilise la liste noire"

```
Thus, localized messages won't be broken.

**Comment by racke** [comment]
I think that's a bad idea, why don't we change the gettext_id in Schema.pm?

**Comment by ikedas** [comment]
> I think that's a bad idea, why don't we change the gettext_id in Schema.pm?

I didn't explain it well enough.  correct_msgid will modify corresponding sopurce files too.
Thus, only thing we have to do is to change entry(ies) of en_US.po on [translation site](https://translate.sympa.org/).

**Comment by racke** [comment]
OK can you provide an example for `correct_msgid` which replaces blacklist with denylist?

**Comment by ikedas** [comment]
> OK can you provide an example for `correct_msgid` which replaces blacklist with denylist?

[Here](https://github.com/sympa-community/sympa/compare/sympa-6.2...ikedas:example-correct_msgid) is an example.
  - [Step 1](https://github.com/sympa-community/sympa/commit/a16317c2958882fdc594200396b7ba6a85439b5c): Modify "translation" of US Engliash catalog (en_US.po). In reality these changes would be done on [Sympa Translation site](https://translate.sympa.org/en_US/sympa/en_US.po).
  - [Step 2](https://github.com/sympa-community/sympa/commit/6d5eba5bc5fb0404af438b8d9165ae5194065318): Run correct_msgid script.

    As the results by this:
      - Entries to keep po files of the other languages in sync with modification of US English on Step 1 will be added.
      - The messages in source codes will be changed according to the changes on US English catalog (If you wanbt to see the changes on source codes in advance, run correct_msgid with --dry_run option).

    In this demo commit, you can see the changes described in above.

Thus, messages in US English catalog may be changed as catalogs for the other languages may be.

**Comment by racke** [comment]
But that wouldn't get rid of blacklist in Sympa::Config::Schema.

**Comment by ikedas** [comment]
> But that wouldn't get rid of blacklist in Sympa::Config::Schema.

Pardon?   `correct_msgid` also [corrects `Sympa::Config::Schema`](https://github.com/sympa-community/sympa/commit/6d5eba5bc5fb0404af438b8d9165ae5194065318#diff-8dd9804b19791594daebd689bd0d9f340be84493e7c20a8ec967dd2f2f01ce68).

**Comment by ikedas** [comment]
There are two features called "blacklist" on Sympa.
  - The implicit scenario rules enabled by [`use_blacklist`](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#use_blacklist) parameter.
    It refers to an address list contained in the file named `blacklist.txt`.
  - Preventing people to subscribe to a list with adresses using these domains, enabled by [`domains_blacklist`](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#domains_blacklist) parameter.

We would also change these names of parameters and files.

**Comment by ikedas** [comment]
Hi @toonmaster,

As you see, technically speaking, we can replace the words "blacklist" that appear in Sympa software.  However, since what word(s) to replace them is a cultural issue, we need specific suggestions for changes from you.

  * On the messages the software may output, please modify "translation" of US English as you suggest, using US English sections of Sympa translation site:
      * [The messages](https://translate.sympa.org/en_US/sympa/en_US.po)
      * [Online help](https://translate.sympa.org/en_US/web_help/en_US.po)

    At first, sign-up is needed to use translation site.  Please use search form to find messages to be modified.  You may not modify the texts not related to your suggestion.  When you complete the modification, please let us know on this issue page.

  * Suggested names to replace names of these parameters and file:
      * `use_blacklist` parameter and `blacklist.txt` file
      * `domains_blacklist` parameter

    According to your suggestion, we will change these names by modifying Sympa.

  * There also are some of this word in the source code, but please leave it to us to fix them.

Thank you!

**Comment by toonmaster** [comment]
I have provided suggestions for The messages and Online help references (i.e., change 'blacklist' to 'blocklist'). The parameters and file can match:

use_blocklist parameter and blocklist.txt file
domains_blocklist parameter

**Comment by ikedas** [comment]
> I have provided suggestions for The messages and Online help references (i.e., change 'blacklist' to 'blocklist'). The parameters and file can match:

I understand we can just mechanically replace "blacklist" in any messages with "blocklist" (taking into account the case difference, of course).

> use_blocklist parameter and blocklist.txt file
> domains_blocklist parameter

OK.  I'll work for the changes.
