### ISSUE TITLE
Assistance in Finding Source of Automated E-mail from Sympa

### ISSUE THREAD

**Issue by BCCHR-IT** [sympa-community/sympa#1117]
Hi there,

We currently have a mailing list that sends out the below confirmation message:

>Someone, probably you, requested to create or renew your password for your
list server account wellbeing. (This request cames from host <hostname> at
<client IP>).
You may ignore this request or click on the following URL in order to choose
your password. : <link>

The message above is only sent to users who initially subscribe and who use external e-mail providers (Gmail, Hotmail, etc.).

The issue is that we are looking to change the wording and formatting of this e-mail message but are unable to locate the source. Attempts to search for matching text strings in the install directory of Sympa only yield matches to binaries:

`#: grep --color -R -H "Someone, probably you, requested to create or renew your password for your" /opt/sympa/
Binary file /opt/sympa/locale/en/LC_MESSAGES/sympa.mo matches
Binary file /opt/sympa/locale/en_US/LC_MESSAGES/sympa.mo matches`

We were wondering if anyone has any suggestions in locating this message template source either on the server directly or any options in the web interface that we need to verify?

Thank you so much in advance.

**Comment by ikedas** [comment]
Hi @BCCHR-IT ,

That text is included in a mail template file `mail_tt2/sendpasswd.tt2`.  You may customize it.

See [description in the manual](https://sympa-community.github.io/manual/customize/basics-templates.html#location) to know where you may locate customized template file.

Note: The basic directory locations appearing in the description ($EXPLDIR, $SYSCONFDIR etc.) are vary by how you installed Sympa.  The locations specific to your installation are defined in $MODULEDIR/Sympa/Constants.pm file.

**Comment by ikedas** [comment]
No more questions.  Close.
