### ISSUE TITLE
Can't get access to Listmaster Admin Panel

### ISSUE THREAD

**Issue by EduardoOsquel** [sympa-community/sympa#1119]
I've installed the Sympa debian package via. I was able to log in for the first time using the option to send a link to the email address provided. Then in sympa.conf I put that user registered as listmaster. However when I log in again it doesn't show up as Super (Listmaster). I am doing something wrong? Is there a default username and password for Listmaster user?

**Comment by EduardoOsquel** [comment]
Honestly, I have not found a conventional way to log in as a Super Listmaster, to delete a test list created with that user that I registered

**Comment by racke** [comment]
Did you restart Sympa and WWSympa/Apache after changing sympa.conf? What is the version of your Debian package?

**Comment by EduardoOsquel** [comment]
> 
> 
> Did you restart Sympa and WWSympa/Apache after changing sympa.conf? What is the version of your Debian package?

Restarting both seems to be the solution. Thanks my friend.
