### ISSUE TITLE
Can't configure message.global_footer on my Sympa instance

### ISSUE THREAD

**Issue by ValentinDrean** [sympa-community/sympa#1121]
Hi,

My instance version is 6.2.40 and I can't make this global footer feature work on my lists where there is no footers set. I think this issue is related to this pull request but I'm not sure, https://github.com/sympa-community/sympa/pull/494

The idea is to create a default footer file when no footer have been set on a list in this path here : `/var/lib/sympa/expl/list-instance/list-name/message.footer`, I have more than a thousand lists where not all have an unsubscribre link in footer so it's not really « RGPD friendly » ;\

Web feature (`https://list-site.tld/wws/serveradmin/templates`) to change default/global footer does not work either, when I save it goes back blank/empty again.

I tried directly editing several configuration files to add these `message.global_footer` and `message.global_footer.mime` in :

- `/usr/share/sympa/default/mail_tt2/` (extension files here are `.tt2`)
- `/etc/sympa/mail_tt2`
- `/etc/sympa/list-site.tld/mail_tt2`

`merge_feature` is `on` in my  `/etc/sympa/sympa/sympa.conf`

I'm not sure which logs and other conf files I need to look for to make this global footer setting work, I'm pretty sure I'm missing something here and I don't want to create a dirty bash script ^^

Thanks for all that crazy work on Sympa anyway <3

**Comment by ikedas** [comment]
With Sympa 6.2.40, global footer may be placed only on either
  - `$SYSCONFDIR/mail_tt2/message.global_footer.mime`
  - `$SYSCONFDIR/mail_tt2/message.global_footer`

Could you please use these locations? (About `$SYSCONFDIR` please check "[Directory Layout](https://sympa-community.github.io/manual/layout.html#sysconfdir)".)

BTW with Sympa 6.2.42 or later, global footer may be placed on either of
  - `$SYSCONFDIR/DOMAIN/message_global_footer.mime`
  - `$SYSCONFDIR/DOMAIN/message_global_footer`

and either of
  - `$SYSCONFDIR/message_global_footer.mime`
  - `$SYSCONFDIR/message_global_footer`

(Note that file names have been changed.)

**Comment by ValentinDrean** [comment]
Thanks a lot for your concern.

I'm a debian user so `$SYSCONDIR` is `/etc/sympa`, I think I messed up with my file names or didn't restart sympa.service after adding these, because this totally worked this morning \o/
```
mailor:/etc/sympa/mail_tt2# ls -la
-rw-r-----  1 sympa sympa  288 févr. 19 19:29 .message.global_footer
-rw-r-----  1 sympa sympa  288 févr. 19 19:30 .message.global_footer.mime
```

I'll close the issue, thanks again,
