### ISSUE TITLE
Use enterprise email server(MTA) for sympa mailing list setup

### ISSUE THREAD

**Issue by droy30** [sympa-community/sympa#1123]
Hi,
We would like to use sympa to create the mailing list feature.
But in the documentation, it mentions to install the mail server along with the product.
We have our enterprise mail server and do not want to install additional mail server for this purpose.
Can you please guide on how to integrate the sympa installation with the already existing enterprise mail server?

**Comment by racke** [comment]
Yes, Sympa needs a mail server in the same system as that is needed for local delivery. 
You can use your enterprise mail server to send and receive all emails going in and out of the Sympa system.

**Comment by droy30** [comment]
How do I configure that since sympa will not be installed on the same system where the enterprise mail server resides.

**Comment by racke** [comment]
On 2/24/21 11:34 AM, droy30 wrote:
> How do I configure that since sympa will not be installed on the same system where the enterprise mail server resides.
> 

You need to relay all emails for the Sympa domains to the Sympa server.

Install and configure the local MTA on the Sympa server:

https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html

And add relay config to the Postfix configuration, e.g.

relayhost = [send.enterpri.se]:25
relay_domains = $mydestination, $mydomain

Regards
         Racke

-- 
Ecommerce and Linux consulting + Perl and web application programming.
Debian and Sympa administration. Provisioning with Ansible.

**Comment by droy30** [comment]
Thanks for the suggestion.
Can the postfix configuration on the sympa server be used to relay to a different relay server which is already existing?
IF so, how can that be achieved?

**Comment by racke** [comment]
Yes, you can certainly relay to a different relay server. The main setting is "relayhost" in the Postfix configuration but you might also need SASL settings.

If you can give a concrete example, I can help you with the Postfix setup (here or per PM).

**Comment by droy30** [comment]
Thanks , we have successfully built the configuration.
