### ISSUE TITLE
Sympa soap response error

### ISSUE THREAD

**Issue by droy30** [sympa-community/sympa#1126]
I am trying to use Python zeep soap client to interact with our sympa soap server.
But I receive the following error on connect.

lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: link line 13 and head, line 74, column 32

My sympa soap server is running on "http://{fqdn}/sympasoap"

From the python zeep client, the url I am providing is: "http://{fqdn}/sympa"

If I change the url to: "http://{fqdn}/sympasoap", it is giving the following error:

411 Client Error: Length Required for url: "http://{fqdn}/sympasoap"

**Comment by racke** [comment]
Can you please share the script / commandline that you use?

**Comment by droy30** [comment]
After configuring the sympasoap , I checked with sympa_soap_client.pl (as mentioned in the official sympa guide) to connect to the soap endpoint and it works fine. 

sympa_soap_client.pl --soap_url=http://{sympa-server-fqdn}/sympasoap \
--service=createList \
--trusted_application='xxxxx' \
--trusted_application_password='xxxxxxxx' \
--proxy_vars='USER_EMAIL=xxx@domain' \
--service_parameters='lista'

But when I am using python zeep to connect to the soap endpoint, it's giving error.

python -mzeep 'http://{sympa-server-fqdn}/sympa'

Error:
XMLSyntaxError: Opening and ending tag mismatch: link line 13 and head, line 74, column 32

Can you please let me know whether the soap endpoint I am using is valid?
Is there any way to check the endpoint (from the sympa.wsdl maybe ?)

**Comment by ikedas** [comment]
Hi @droy30 ,
Please show us these things:
  - Everything you configured: Especially `sympa.wsdl` file, if you customized it.
  - Everything you did: Full of command line you executed, full of source you run, etc.
  - Everything you saw as the results: Full of message displayed by the program you run.

**Comment by ikedas** [comment]
Hi again @droy30 ,

> But when I am using python zeep to connect to the soap endpoint, it's giving error.
> 
> python -mzeep 'http://{sympa-server-fqdn}/sympa'

Do you mean this?

> python -mzeep 'http://{sympa-server-fqdn}/sympasoap'

**Comment by ikedas** [comment]
No updates.  Close.
