### ISSUE TITLE
Immediate notification of bounces

### ISSUE THREAD

**Issue by pasqualemandato** [sympa-community/sympa#1128]
Hi.
Some owners of operational mailing lists would need to know if a message has not been delivered to a recipient as soon as possibile and not when the warn_rate threshold is exceeded. Is there any way to do this in sympa?
Thank you

**Comment by ikedas** [comment]
Hi,

The [message tracking](https://sympa-community.github.io/manual/customize/message-tracking.html) may be used.  By this feature, the owner will know as soon as someone bounces (and someone successfully receives the message).

**Comment by pasqualemandato** [comment]
> Hi,
> 
> The [message tracking](https://sympa-community.github.io/manual/customize/message-tracking.html) may be used. By this feature, the owner will know as soon as someone bounces (and someone successfully receives the message).

Thank you.
We will try your suggestion.

Regards
