### ISSUE TITLE
Is there a way to resend the bounced message?

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#1134]
Hello.

If a message sent in Sympa bounces, is there a way to resend the bounced message?
Normally, in MTA such as Postfix, if a bounce occurs, I think that it will try to resend periodically, but it seems that Sympa does not.
Or am I misunderstanding something?
The environment is Ubuntu 20.04, Sympa 6.2.60.

Best regards.

**Comment by ikedas** [comment]
There is nothing.

It is the role of the MTA to resend messages bouncing softly.  When the MTA give up resending (or receiving MTA reports permanent error), Sympa receives a error message reporting hard bounce, and the MTA no longer will retry resending.

**Comment by riku22** [comment]
Hello.

I see.
Thank you.

Best regards.
