### ISSUE TITLE
LDAP Data Source - Ability for group in group

### ISSUE THREAD

**Issue by robertbln** [sympa-community/sympa#1137]
Hi,

I have a question about the LDAP Data Source (include_ldap_query, include_ldap_2level_query). I'm able to get listed users from an LDAP group, but it only works if that group has just users, but not if that group has also a further group inside.

Does somebody know if there is a way to be able to get users from a group in a group?

My current configuration is:

```
include_ldap_2level_query
name  group_[% param.0 %]
host  ldap.example.com
port  636
user  binduser
passwd xxxxxxxxx
use_ssl yes
ssl_version tls
suffix1 OU=SYMPA,OU=GROUPS,OU=GLOBAL,DC=example,DC=com
filter1 (&(cn=[% param.0 %])(objectClass=group))
attrs1  distinguishedName
select1 all
timeout1 600
scope1 sub
suffix2 DC=example,DC=com
filter2 (&(memberOf=[attrs1])(objectClass=person))
attrs2 mail
select2 first
scope2 sub
timeout2 600
```

Thanks,
Robert

**Comment by racke** [comment]
What kind of LDAP server do you use?

**Comment by robertbln** [comment]
Active Directory

**Comment by racke** [comment]
I had a similar problem this week and I found this article helpful: https://confluence.atlassian.com/crowdkb/active-directory-user-filter-does-not-search-nested-groups-715130424.html.

So your problem might be fixed by:

`filter2 (&(memberOf:1.2.840.113556.1.4.1941:=[attrs1])(objectClass=person))`

**Comment by robertbln** [comment]
I've test it and it works well. Thanks very much for the link, it saved me a lot of time!
