### ISSUE TITLE
WWSympa: Apache: Returns 404 despite `Location` directives

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#1142]
I am trying to get WWSYmpa working after upgrading Sympa in Debian from 6.2.40~dfsg-1+deb10u1 to 6.2.60~dfsg-4. After seeing that the FCGI wrapper was removed, and adapting the configuration files, it still didn’t work. After following the upstream documentation, the Apache HTTPD returns the error 404, that `/sympa` cannot be found.

> The requested URL was not found on this server.

```
$ systemctl status wwsympa
● wwsympa.service - WWSympa - Web interface for Sympa mailing list manager
     Loaded: loaded (/etc/systemd/system/wwsympa.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-04-04 21:54:05 UTC; 30min ago
   Main PID: 25607 (wwsympa.fcgi)
      Tasks: 5 (limit: 2362)
     Memory: 448.5M
        CPU: 7.071s
     CGroup: /system.slice/wwsympa.service
             ├─25607 /usr/bin/perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi
             ├─25608 /usr/bin/perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi
             ├─25609 /usr/bin/perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi
             ├─25610 /usr/bin/perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi
             └─25611 /usr/bin/perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi

Apr 04 21:54:05 redcape spawn-fcgi[25606]: spawn-fcgi: child spawned successfully: PID: 25608
Apr 04 21:54:05 redcape spawn-fcgi[25606]: spawn-fcgi: child spawned successfully: PID: 25609
Apr 04 21:54:05 redcape spawn-fcgi[25606]: spawn-fcgi: child spawned successfully: PID: 25610
Apr 04 21:54:05 redcape spawn-fcgi[25606]: spawn-fcgi: child spawned successfully: PID: 25611
Apr 04 21:54:05 redcape systemd[1]: Started WWSympa - Web interface for Sympa mailing list manager.
Apr 04 21:54:09 redcape wwsympa[25609]: info main:: WWSympa started, process 25609
Apr 04 21:54:09 redcape wwsympa[25610]: info main:: WWSympa started, process 25610
Apr 04 21:54:09 redcape wwsympa[25607]: info main:: WWSympa started, process 25607
Apr 04 21:54:09 redcape wwsympa[25611]: info main:: WWSympa started, process 25611
Apr 04 21:54:09 redcape wwsympa[25608]: info main:: WWSympa started, process 25608
```

```
$ ls -l /run/sympa/wwsympa.socket
srw-------. 1 www-data www-data 0 Apr  4 21:54 /run/sympa/wwsympa.socket
```

```
$ more /etc/apache2/conf-enabled/sympa.conf # matches all configured sites
#
# Apache >> 2.4 configuration for Sympa
#

<IfModule mod_fcgid.c>
    Alias /static-sympa /usr/share/sympa/static_content

    <Location /sympa>
        SetHandler "proxy:unix:/run/sympa/wwsympa.socket|fcgi://"
        Require all granted
    </Location>
    
    <Location /static-sympa>
        Require all granted
    </Location>
</IfModule>
```

So, the socket should work, but it does not and seems to cause the 404?

Thank you in advance for your help.

**Comment by ikedas** [comment]
I guess this is an issue with Debian package.  @racke, do you have any idea?

**Comment by paulmenzel** [comment]
`ScriptAlias` line is not needed anymore?

**Comment by racke** [comment]
I will take a look at this problem and Debian bugs recently filed by @paulmenzel.

**Comment by racke** [comment]
> Is the `ScriptAlias` line from earlier versions not needed anymore?

No, I don't think so.

**Comment by racke** [comment]
@paulmenzel Can you please check the Apache logs about the 404?

**Comment by paulmenzel** [comment]
Sorry for not posting it.

`access.log`:

    2a02:8109:b5c0:1dc8:6f36:7093:e6d4:XXXX - - [05/Apr/2021:18:25:30 +0000] "GET /favicon.ico HTTP/1.1" 404 589 "https://listen.XXX.de/sympa" "Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0"

`error.log` (debug level):

```
[Mon Apr 05 18:25:30.371520 2021] [ssl:debug] [pid 31020] ssl_engine_kernel.c(415): [client 2a02:8109:b5c0:1dc8:6f36:7093:e6d4:2f8c:59084] AH02034: Subsequent (No.2) HTTPS request received for child 8 (server listen.gw90.de:443), referer: https://listen.XXX.de/sympa
[Mon Apr 05 18:25:30.371642 2021] [authz_core:debug] [pid 31020] mod_authz_core.c(815): [client 2a02:8109:b5c0:1dc8:6f36:7093:e6d4:XXXX:59084] AH01626: authorization result of Require all granted: granted, referer: https://listen.XXX.de/sympa
[Mon Apr 05 18:25:30.371658 2021] [authz_core:debug] [pid 31020] mod_authz_core.c(815): [client 2a02:8109:b5c0:1dc8:6f36:7093:e6d4:XXXX:59084] AH01626: authorization result of <RequireAny>: granted, referer: https://listen.XXX.de/sympa
[Mon Apr 05 18:25:30.371704 2021] [core:info] [pid 31020] [client 2a02:8109:b5c0:1dc8:6f36:7093:e6d4:XXXX:59084] AH00128: File does not exist: /home/www/listen.gw90.de/favicon.ico, referer: https://listen.XXX.de/sympa
[Mon Apr 05 18:25:30.371728 2021] [headers:debug] [pid 31020] mod_headers.c(899): AH01503: headers: ap_headers_error_filter()
```

Maybe, I am missing something very basic regarding Apache HTTPD’s configuration. But as I understand the directive `Location` it should work as given in Sympa’s example documentation.

**Comment by racke** [comment]
That is a 404 on favicon.ico, not on /sympa.

**Comment by paulmenzel** [comment]
Sorry, probably wrong line from logs (but it’s clear from the browser message).

Anyway, here again from `curl https://listen.XXX.de/sympa`:

2a02:8109:b5c0:1dc8:6f36:7093:e6d4:XXXX - - [05/Apr/2021:18:36:50 +0000] "GET /sympa HTTP/1.1" 404 4347 "-" "curl/7.74.0"

**Comment by racke** [comment]
And the corresponding line from the error.log?

**Comment by paulmenzel** [comment]
95.90.232.XXX - - [05/Apr/2021:18:55:22 +0000] "GET /sympa HTTP/1.1" 404 4347 "-" "curl/7.74.0"

    [Mon Apr 05 18:55:22.122677 2021] [core:info] [pid 29263] [client 95.90.232.XXX:35448] AH00128: File does not exist: /home/www/listen.gw90.de/sympa

**Comment by racke** [comment]
It looks to me as if sympa.conf is not considered or overridden in a virtual host.

**Comment by paulmenzel** [comment]
Thank you for analyzing this. Just to be sure, it’s not a configuration problem on my system, and you could reproduce it?

**Comment by racke** [comment]
I actually think that it is a configuration problem on your system :thinking:

**Comment by ikedas** [comment]
@paulmenzel , by any chance, haven't you enable mod_fcgid module yet?

**Comment by paulmenzel** [comment]
It is enabled. Somehow the `Location` directive does not work.

Trying it with the directive `FilesMatch`, accessing https://example.org/wwsympa.fcgi, the script is executed using the socket, but it’s denied permission to access `/etc/sympa/sympa.conf`.

            <FilesMatch "\.(cgi|pl)$">
                    SetHandler "proxy:unix:/run/sympa/wwsympa.socket|fcgi://"
                    #SetHandler cgi-script
                    Options -ExecCGI
            </FilesMatch>

```
notice Conf::_load_config_file_to_hash() Unable to open /etc/sympa/sympa/sympa.conf: Permission denied
Unable to load sympa configuration, file /etc/sympa/sympa/sympa.conf or one of the vhost robot.conf files contain errors. Exiting.
[Thu Apr 08 16:08:46.140366 2021] [fcgid:warn] [pid 152571] (104)Connection reset by peer: [client 2a02:8109:b5c0:1dc8:6f36:7093:e6d4:XXXX:43452] mod_fcgid: error reading data from FastCGI server
```

    $ ls -lh /etc/sympa/sympa/sympa.conf
    -rw-r-----. 1 sympa sympa 8.4K Apr  4 11:45 /etc/sympa/sympa/sympa.conf

The FCGI suid wrapper is not needed anymore, right?

**Comment by ikedas** [comment]
@paulmenzel , please remove everything you have added to Apache's configuration (everything including settings to enable Syma's functions), then install sympa again, and check if the problem will be reproduced.

**Comment by paulmenzel** [comment]
I had to run `a2enmod proxy_fcgi` to get it working. I missed that, not thinking it changed between 6.2.40 and 6.2.60.

**Comment by racke** [comment]
Problem solved.

**Comment by paulmenzel** [comment]
Well, kind of. Though it’s probably a Debian packaging bug, as the upgrade from Debian 10 (buster) to 11 (bullseye) broke the Sympa service.

1.   The shipped [Apache HTTPD configuration](https://salsa.debian.org/sympa-team/sympa/-/blob/f34a733a902270b3ef0074265f07362b04478e64/debian/conf/apache2/sympa.conf#L5) still has the condition below:

        <IfModule mod_fcgid.c>

    Shouldn’t that be `mod_proxy_fcgi.c`?

2.  There are no upgrade notes (`NEWS.Debian.gz`).

3.   No idea if `/usr/lib/sympa/bin/sympa_wizard.pl --check` should have noticed the problem.

Should I submit a bug report to the Debian BTS?

**Comment by racke** [comment]
Yes, please submit a bug report to the Debian BTS.
