### ISSUE TITLE
Sympa 6.2.61b.2 upgrade fails to rename blacklist.txt to blocklist.txt

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1144]
Version
-------

6.2.61b.2 

Installation method
-------------------

My own rpm, derived from "official" RHEL 7 source rpm

Expected behavior
-----------------

Sympa upgrade process should rename search_filters/blacklist.txt to search_filters/blocklist.txt for every list in the system

Actual behavior
---------------

No blacklist.txt files are renamed.

Additional information
----------------------

Pretty sure that this is just two simple typos in  src/lib/Sympa/Upgrade.pm:

```
$ cd <sympa git repo>
$ git grep search_filter 
Makefile.am:            mail_tt2 scenari search_filters web_tt2; do \
doc/samples/README:employees.ldap is a named filter (should be located in ~sympa/etc/search_filters
src/cgi/wwsympa.fcgi.in:    my $file = $list->{'dir'} . '/search_filters/blocklist.txt';
src/cgi/wwsympa.fcgi.in:        my $dir = $list->{'dir'} . '/search_filters';
src/cgi/wwsympa.fcgi.in:    my $dir = $list->{'dir'} . '/search_filters';
src/lib/Sympa/Scenario.pm:            subdir => 'search_filters');
src/lib/Sympa/Scenario.pm:            subdir => 'search_filters');
src/lib/Sympa/Scenario.pm:            subdir  => 'search_filters',
src/lib/Sympa/Upgrade.pm:            'search_filter/blacklist.txt',
src/lib/Sympa/Upgrade.pm:                my $newfile = 'search_filter/blocklist.txt';
```

Note "search_filter/bl*" rather than "search_filters/bl*" on the last two lines. If  I change those both to "search_filters" (plural) it works as I would expect.

I confess that I only noticed because I was attempting to adapt src/lib/Sympa/Upgrade.pm to also rename whitelist.txt to allowlist.txt (see my recent message to sympa-users).  As a complete aside: I don't suppose there is an chance that Steve Shipway's whitelist patch could be merged: https://github.com/sympa-community/sympa/issues/992. This would make my life simpler. Is there anything that I could do to help with the merge process? Thanks.

**Comment by ikedas** [comment]
It's due to typos.  @dpc22 , thanks for pointing it out!
