### ISSUE TITLE
display of threads based on Reference and in-Reply-To fields?

### ISSUE THREAD

**Issue by PhilLAL** [sympa-community/sympa#1145]
Hello,
I would like to understand how mails are gathered into threads into archive page of sympa.
Are they considered in a same thread if they have same message-ID in References or In-Reply-To fields?

To give a bit of context, i have been informed by a colleague that a new mail sent on sympa-fr is displayed as in an already existing thread in his client (thunderbird 78.9.0/Ubuntu 20.04).
However, in the thread displayed in sympa archives (https://listes.renater.fr/sympa/arc/sympa-fr/2021-04/) this mail is the first of its thread.
I checked the Reference and In-Reply-To fields to check if i sent it as an answer of a formerly received mail but it does not seem so. 

Thank you

**Comment by ikedas** [comment]
Hi @PhilLAL ,
Currently, the thread is shown as below.  Could you please describe how the thread is expected to be shown?

![image](https://user-images.githubusercontent.com/5743546/113980694-c2b86680-9881-11eb-9f92-c1cc338c9b65.png)

**Comment by PhilLAL** [comment]
It's shown as it should.
My colleague checked and rebuilt its thunderbird mail, and it solved his issue so the behaviour he saw was a mistake.

Could you confirm that sympa archive are gathered by Message-ID?

**Comment by ikedas** [comment]
As you see, within Sympa archives, the messages are gathered by message IDs in References and/or In-Reply-To fields.

**Comment by PhilLAL** [comment]
Thank you very much for this confirmation, I close the ticket. :)
