### ISSUE TITLE
DKIM canonicalization in Sympa 6.2.20

### ISSUE THREAD

**Issue by MorenoUniTN** [sympa-community/sympa#1147]
Hi everyone,
we are implemented the DKIM feature in Sympa 6.2.20.
Our configuration is:
dkim_feature    on
dkim_add_signature_to   robot
dkim_signature_apply_on any
dkim_private_key_path   /etc/sympa/dkim-keys/namedomain-key.private
dkim_signer_domain      domain.it
dkim_selector   selector-domain

In this situation the DKIM Signature in a header email result with the canonicalization setting in relaxed only in the subject (example below)
"DKIM-Signature: v=1; a=rsa-sha1; **c=relaxed**; d=domain.it; h= mime-version:.........."

I don't find any possible configuration to add canonicalization in the body of the message too, so with a typical result
"DKIM-Signature: v=1; a=rsa-sha1; **c=relaxed/relaxed**; d=domain.it; h= mime-version:.........."

How can it be done?
Thanks in advanced.

Moreno

**Comment by ikedas** [comment]
Currently canonicalization is fixed to be “relaxed”.

Can you describe the case in which “relaxed/relaxed” is necessary?

**Comment by MorenoUniTN** [comment]
Hi @ikedas our organization is a university and the use of sympa lists happens with a modification of the message body where Sympa adds a footer with a description of how to unsubscribe from the list.
In this way, analyzing the headers of the emails sent by sympa I see errors of "dkim = fail reason =" signature-key hash mismatch "on the mail systems through which the mail passes

**Comment by ikedas** [comment]
I think your problem may not be solved by applying `relaxed` rule to the body.  
Sympa add the DKIM signature at the final stage of the message delivery process, so I guess the signature should not be broken even if Sympa has added the footer to the body.

BTW currently `relaxed` rule is hardcoded [here](https://github.com/sympa-community/sympa/blob/6.2.20/src/lib/Sympa/Message.pm#L497) in the source.  You may edit it to change it to `relaxed/relaxed` and see if what you expect will occur.

**Comment by MorenoUniTN** [comment]
Hi @ikedas Thnak's for the answers...
my doubt was that dkim was applied before the Sympa changes. Now I understand.


Please, can I ask you another my question?
In the message.pm I see the parameter:
Algorithm => "rsa-sha1"
this is means that the creation of the dkim keys must not have the value "h = sha256" ?

**Comment by ikedas** [comment]
> In the message.pm I see the parameter:
> Algorithm => "rsa-sha1"
> this is means that the creation of the dkim keys must not have the value "h = sha256" ?

The link above point to the code at the time of Sympa 6.2.20.  It has been updated to `rsa-sha256` at Sympa 6.2.34 (see also #357).

**Comment by ikedas** [comment]
There seems no more question. Close.
