### ISSUE TITLE
The method to test/run wwsympa.fcgi from command line

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#1151]
Debian 11 (bullseye/testing): sympa 6.2.60~dfsg-4

As `wwsympa.fcgi` is a Perl script, I’d like to run it on the command line (with the appropriate user), and best check if it can access all configuration files for example. I only found a way to check the syntax.

    $ sudo -u sympa perl -wc /usr/lib/cgi-bin/sympa/wwsympa.fcgi
    [Thu Apr 15 15:01:59 2021] wwsympa.fcgi: "my" variable $result masks earlier declaration in same scope at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 2931, <DATA> line 960.
    [Thu Apr 15 15:01:59 2021] wwsympa.fcgi: "my" variable $result masks earlier declaration in same scope at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 2940, <DATA> line 960.
    /usr/lib/cgi-bin/sympa/wwsympa.fcgi syntax OK

Running it without any arguments fails:

    $ sudo -u sympa perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi
    Status: 421 Misdirected Request
    
    

How can I call it from the command line to see for example all lists?

**Comment by paulmenzel** [comment]
That error occurs, when the environment variable `SYMPA_DOMAIN` is not set. Unfortunately, it does not seem to work with sudo.

https://github.com/sympa-community/sympa/blob/1b6f21fb3cbbc72513cbd336592d5ee22813430e/src/cgi/wwsympa.fcgi.in#L1118-L1125

    sudo -u sympa SYMPA_DOMAIN=example.net perl /usr/lib/cgi-bin/sympa/wwsympa.fcgi

gives the same error.

Editing that line to `$robot = example.net;`, the script runs and outputs HTML.

**Comment by racke** [comment]
Yes, it is a  Perl script. But it doesn't get the environment variables in the normal way, but derives it from the HTTP request. 
The command line interface for Sympa is sympa.pl. Unfortunately it doesn't have a command to display all lists. Please create another issue if you fancy such a command.
