### ISSUE TITLE
Listmaster: the X_name_list@robot_list list is 100% error

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1155]
Since the migration to the new server from sympa 6.1.24 to 6.2.40,
I have much lists in 100% error after sending mails.
And a many spams sended into the lists.
The subscribers have 5.7.1 code errors.
![subcriber_error](https://user-images.githubusercontent.com/37698060/115347118-4ee75980-a1b1-11eb-9135-f643f69c832a.png)

**Comment by racke** [comment]
That doesn't look like a problem with the newer Sympa version. Check that the local MTA on the Sympa host is set up properly and get in touch with the administrator of the relay server about the specific "Policy reason".

A few tips:

   - Mailserver needs an MX record
   - Reverse DNS record (PTR) which is not a boilerplate one
   - Domain name resolves to mail server's IP
   -  HELO needs sane hostname too
   - SPF/DKIM for your domain

**Comment by khaoula-abaidi** [comment]
> Mailserver needs an MX record

As a beginner will you please tell me how do check it for more details 
Very thankfull for your help

**Comment by racke** [comment]
First thing would be to contact the administrator of the relay host and find out about the "policy reason". 
Aside of that, this is a topic for the sympa-users mailing list and not as a bug report here. There also more people to help you with the problem. Please include details about your local MTA in your post to the mailing list.
