### ISSUE TITLE
default/ca-bundle.crt is outdated

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#116]
```
$ head -3 default/ca-bundle.crt
##
##  ca-bundle.crt -- Bundle of CA Root Certificates
##  Last Modified: Fri Oct 22 17:15:27 CEST 1999
```

The file should be updated with more current content.
Also, as distributions are shipping this file in various locations (eg. /etc/pki/tls/certs/ca-bndle.crt in Fedora, /etc/ssl/certs/ca-certificates.crt in Debian), it could be made a build time configure option, this would help packagers.

**Comment by racke** [comment]
Does Sympa still use that file? At any rate, using the file provided by the OS makes way more sense.

**Comment by ikedas** [comment]
> Does Sympa still use that file? At any rate, using the file provided by the OS makes way more sense.

[Here](https://github.com/sympa-community/sympa/blob/sympa-6.2/src/lib/Conf.pm#L1913).

**Comment by ikedas** [comment]
Ok, it seems fixed. Close.
