### ISSUE TITLE
Created Mailing List, but cannot find option to Add subscribers or Members.

### ISSUE THREAD

**Issue by BenzirInterHyve** [sympa-community/sympa#1162]
Created a mailing list in Sympa -ecma-testdl@my-safe-cloud.ch

We are not able to add members or subscribers for the list as the Add subscriber option is not showing and please find the screen shot below.

![image](https://user-images.githubusercontent.com/83277660/116223356-132e3000-a76d-11eb-8b2b-e01e2540969a.png)

could you kindly help on the same?

Thanks a lot in advance.

Regards,
Benzir Mohammed

**Comment by ikedas** [comment]
Hi @BenzirInterHyve ,

This issues page is intended for system administrators who manage mailing list systems.
At first, could you please contact the support desk of the provider hosting services on `my-safe-cloud.ch`?

**Comment by BenzirInterHyve** [comment]
Hi,

Thank you for your email.

Could you please confirm, if it’s the sympa support we have contacted now or its github?

If add members option is missing in Symba console, not sure whats the point in contacting the hosting services of my-safe-cloud.ch
Could you please provide some more info on this?


Also it will be really great if you can help us with right technical support of Sympa mailing list as we cannot find any help online.


Thanks a lot.

Regards,


Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73B7C.993D3DB0]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by racke** [comment]
On the list menu you see "List not activated yet."  In order to add members the list needs to be activated by the listmaster of my-safe-cloud.ch.

You may contact me by private email about technical support.

**Comment by BenzirInterHyve** [comment]
Okay may I have your private email to contact you in this case.

Also do you have any steps to activate this list?


Thanks in advance.

Regards,

Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73B7E.EF7A3280]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by BenzirInterHyve** [comment]
I am the listmaster, and haven’t received any email to activate the list. So it will be great if you can help me with steps to activate this.

Also kindly share your private email to contact you for technical support.


Thank you.

Regards,


Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73B7F.49B1BF70]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>



From: Benzir Mohammed
Sent: 27 April 2021 16:04
To: sympa-community/sympa ***@***.***>; sympa-community/sympa ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [sympa-community/sympa] Created Mailing List, but cannot find option to Add subscribers or Members. (#1162)

Okay may I have your private email to contact you in this case.

Also do you have any steps to activate this list?


Thanks in advance.

Regards,

Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73B7F.49B1BF70]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by racke** [comment]
Select "Listmaster Admin" from the top menu, click on View Pending (Requested) lists and select the list in question, and confirm the list.

Email: see my Github account.

**Comment by ikedas** [comment]
@BenzirInterHyve , sorry, I misunderstood you are using an installation of Sympa which is provided by the hosting providor.

To request helps, could you please provide these things?

- Version of Sympa.
- Installation method: apt, RPM, FreeBSD port, comileation using source tarball or ...
- What you expected.
- What you really saw.
- The procedure step-by-step by which you can reproduce the problem: "I opened the URL xxx, clicked xxx button, entered 'xxxx' into XXX textbox, and ... "

Support on this GitHub site is basically voluntary work.  Sharing your experiences will also benefits the other users.

**Comment by BenzirInterHyve** [comment]
*   Version of Sympa. – 6.2.24
  *   Installation method: apt, RPM, FreeBSD port, comileation using source tarball – Installed the package on a Linux server
  *   What you expected – Expecting an option to add members in created Mailing List.
  *   What you really saw. – Cannot find the option to add the members/subscribers.
  *   The procedure step-by-step by which you can reproduce the problem: "I opened the URL https://www.my-safe-cloud.ch/wws/home, clicked MY LIST button, entered 'ECMA-TESTDL’  and don’t have the Add members options. The List might be not active as informed yesterday. So kindly let me know how to get this activated??

Regards,


Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73C1C.9DDFA6F0]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by racke** [comment]
You need to be listmaster to activate the list. Check "listmaster" value in your Sympa configuration file (sympa.conf)

**Comment by BenzirInterHyve** [comment]
Yes I am the list admin in our case and could you please advise the steps to activate the list as I am the list admin in my case.

Also is the activation is done via email? Do sympa send email to my account for activation? Could you kindly provide some more info

Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73C38.2D5E9F50]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by racke** [comment]
This done from the web interface as follows:

Select "Listmaster Admin" from the top menu, click on View Pending (Requested) lists and select the list in question, and confirm the list.

**Comment by BenzirInterHyve** [comment]
Hello Stefan,

Really sorry to bother you … I don’t have any such options in web interface ☹ and please find the screen shot below.

***@***.***D73C39.FA3C7EB0]

Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73C39.FA3C7EB0]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by ikedas** [comment]
@BenzirInterHyve , according to the screen shot in the first post, you are not the **listmaster**.  Listmaster is not the admin of specific list.

Did you install Sympa by yourself?  If you did, please check [the Administration Manual](https://sympa-community.github.io/manual/install.html) again and confirm if you have done necessary settings.

If you didn't, please ask the person who installed Sympa.

**Comment by BenzirInterHyve** [comment]
Thanks a lot for your email and steps.

As advised, we changed the account to listmaster now and signed in and was successfully seeing the list admin option and activated the DL mailing list too.

***@***.******@***.***>

I was testing sending emails to the active mailing list we created – but it looks they are rejecting with below NDR/

Is there any thing else we have to do make the list active?





Diagnostic information for administrators:

Generating server: GV0P278MB0516.CHEP278.PROD.OUTLOOK.COM

***@***.******@***.***>
Remote Server returned '554 5.1.0 < #5.1.10 smtp;550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient ***@***.******@***.***> not found by SMTP address lookup>'

Original message headers:

Received: from GV0P278CA0068.CHEP278.PROD.OUTLOOK.COM (2603:10a6:710:2a::19)

 by GV0P278MB0516.CHEP278.PROD.OUTLOOK.COM (2603:10a6:710:2e::11) with

 Microsoft SMTP Server (version=TLS1_2,

 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4087.25; Thu, 29 Apr

 2021 05:21:29 +0000

Received: from GV0CHE01FT017.eop-che01.prod.protection.outlook.com

 (2603:10a6:710:2a:cafe::be) by GV0P278CA0068.outlook.office365.com

 (2603:10a6:710:2a::19) with Microsoft SMTP Server (version=TLS1_2,

 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4087.27 via Frontend

 Transport; Thu, 29 Apr 2021 05:21:29 +0000

Authentication-Results: spf=none (sender IP is 85.115.54.190)

 smtp.mailfrom=sinara.ch; my-safe-cloud.ch; dkim=none (message not signed)

 header.d=none;my-safe-cloud.ch; dmarc=none action=none header.from=sinara.ch;

Received-SPF: None (protection.outlook.com: sinara.ch does not designate

 permitted sender hosts)

Received: from cluster-j.mailcontrol.com (85.115.54.190) by

 GV0CHE01FT017.mail.protection.outlook.com (20.128.123.108) with Microsoft

 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id

 15.20.4087.27 via Frontend Transport; Thu, 29 Apr 2021 05:21:29 +0000

Received: from SRVSINMAIL01.sinara.local (26.186.62.81.static.wline.lns.sme.cust.swisscom.ch [81.62.186.26])

        by rly02j.srv.mailcontrol.com (MailControl) with ESMTPS id 13T5LSG8153133

        (version=TLSv1.2 cipher=ECDHE-RSA-AES256-SHA384 bits=256 verify=FAIL)

        for ***@***.******@***.***>>; Thu, 29 Apr 2021 06:21:28 +0100

Received: from SRVSINMAIL01.sinara.local (192.168.0.32) by

 SRVSINMAIL01.sinara.local (192.168.0.32) with Microsoft SMTP Server

 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id

 15.1.2176.2; Thu, 29 Apr 2021 07:21:27 +0200

Received: from SRVSINMAIL01.sinara.local ([fe80::9860:895a:4adb:6c6]) by

 SRVSINMAIL01.sinara.local ([fe80::9860:895a:4adb:6c6%15]) with mapi id

 15.01.2176.012; Thu, 29 Apr 2021 07:21:27 +0200

From: Administrator ***@***.******@***.***>>

To: ***@***.******@***.***>" ***@***.******@***.***>>

Subject: test

Thread-Topic: test

Thread-Index: Adc8t33bmEwxVKaYR3Cm5lK6bBL+xQ==

Date: Thu, 29 Apr 2021 05:21:27 +0000

Message-ID: ***@***.******@***.***>>

Accept-Language: en-US, fr-CH

Content-Language: en-US

X-MS-Has-Attach:

X-MS-TNEF-Correlator:

x-originating-ip: [27.57.20.104]

Content-Type: multipart/alternative;

        boundary="_000_7b506e43bd2b40b2bd0fa318e8fe5e5fsinarach_"

MIME-Version: 1.0

X-MailControl-OutInfo: MTYxOTY3MzY4ODpGUEtleTEucHJpdjoxl778QqeUTyOapKRYx3JQcbnxvcriJRTgVGW6q/ysBNmidv2VUJ+DXJddCmvzh2ZQRDJyqJmeCp6nT5reqE3czBaXzNSMRoKqWroSVUO6I7VJurFqxD24NcfMBD7bp8W4EbqL3ghhnT1OEwUB99QXJ88nLktbbYuPsKas7a3zmrQhNqkXLd5wWLm2j1/V4TH8hZ31SABUIcjXY90WaREhQg7F742yI0z6Pwx5yjxbjE4CJQJygGexm0Xg6wDe8AF5A8prLeHSM2tAwKpZKDlLfdXMKF7/zl42Vn5qSusLZghVfTcrEv4FPsWPVNqw221Wo6HA5X+qWJ/acbKRssgJ

X-Scanned-By: MailControl 44278.2108 (www.mailcontrol.com<http://www.mailcontrol.com>) on 10.74.0.112

Return-Path: ***@***.******@***.***>

X-EOPAttributedMessage: 0

X-EOPTenantAttributedMessage: 15561f24-2574-42ae-a238-a90a85b408f1:0

X-MS-PublicTrafficType: Email

X-MS-Office365-Filtering-Correlation-Id: 211042f2-760e-4324-c3b9-08d90acea4d4

X-MS-TrafficTypeDiagnostic: GV0P278MB0516:



Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73CE6.4A1BCEC0]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by racke** [comment]
@BenzirInterHyve  Glad to hear that the list works now. Please submit a **separate issue** on the mail  problem, including details about your mail server setup on the Sympa server and the NDR as attachment.
