### ISSUE TITLE
Error emails to listmaster from repeated set_netidtoemail_db calls

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1163]
Version
-------

6.2.62

Installation method
-------------------

My own rpm, derived from "official" source RPM for RHEL 7.

Expected behavior
-----------------

We have SSO (Shibboleth) enabled for our Sympa installation. This should not generate spurious emails to listmaster of the form:

```User  has encountered an internal server error
(Web interface - ACTION: Command process):

db_update_failed

See the logs for more details.
```
Actual behavior
---------------

Once in a while someone manages to generate two separate confirmmail emails with different ticket numbers when attempting to create a new account on Sympa. I infer that they are either looking at the same page in two different browers or (more likely) opening links in new browser tabs:
```
XX.XX.XX.XX - XXX [27/Apr/2021:17:55:39 +0100] "GET /sympa/sso_login/ucam_federation/validateemail/XXX%40cam.ac.uk HTTP/1.1" 200 9923 "https://lists.cam.ac.uk/sympa/sso_login/ucam_federation/init" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
XX.XX.XX.XX - XXX [27/Apr/2021:17:56:26 +0100] "GET /sympa/sso_login/ucam_federation/validateemail/XXX%40cam.ac.uk HTTP/1.1" 200 10102 "https://lists.cam.ac.uk/sympa/sso_login/ucam_federation/init" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
```
If they click on both confirmemail links:
```
XX.XX.XX.XX - XXX [27/Apr/2021:17:56:03 +0100] "GET /sympa/sso_login/ucam_federation/confirmemail/XXX%40cam.ac.uk/20685874072473 HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
XX.XX.XX.XX - XXX [27/Apr/2021:17:56:40 +0100] "GET /sympa/sso_login/ucam_federation/confirmemail/XXX%40cam.ac.uk/31585752071920 HTTP/1.1" 200 11350 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0"
```

listmaster receives an error email as indicated above. The Sympa logs reveal:

```Apr 27 17:56:40 lists-1 wwsympa[9282]: err main::#1556 
> main::do_sso_login#3568 
> Sympa::Robot::set_netidtoemail_db#130 Unable to set email address XXX@cam.ac.uk in netidmap_table for id XXX, service ucam_federation, robot lists.cam.ac.uk
```

The user also sees an error in wwsympa but everything works fine if they just try to log in with the newly created account.

Additional information
----------------------

This would appear to be down to lib/Sympa/Robot.pm set_netidtoemail_db (or something calling that function) failing to check whether a row already exists in the netidmap_table. Replacing:
  
```     $log->syslog(
            'err',
            'Unable to set email address %s in netidmap_table for id %s, service %s, robot %s',
```
with:
```     $log->syslog(
            'info',
            'Unable to set email address %s in netidmap_table for id %s, service %s, robot %s',
```
would presumably stop the noise to listmaster, but the error would still be there.

**Comment by ikedas** [comment]
@dpc22 , could you please let us know what RDBMS are you using?

**Comment by dpc22** [comment]
PostgreSQL.

Specifically postgresql-9.2.24-4.el7_8.x86_64, which is what RHEL 7 provides right now.

**Comment by ikedas** [comment]
@dpc22, could you please check [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1173.patch) ?  Thank you.

**Comment by dpc22** [comment]
Yes, I think that has fixed it. Thanks.

**Comment by dpc22** [comment]
Oops: clicked the wrong button and closed the ticket before the patch was committed

**Comment by ikedas** [comment]
@dpc22, thank you for reporting bug and confirming fixes!
