### ISSUE TITLE
Mails cannot deliver to Mailing List

### ISSUE THREAD

**Issue by BenzirInterHyve** [sympa-community/sympa#1164]
Hello Support team,

We are getting the below NDR while sending to a mailing list created in Sympa.

For your information  - Sympa package has been installed on a linux server and using version 6.2.24

**NDR**
``` code
Diagnostic information for administrators:
Generating server: GV0P278MB0516.CHEP278.PROD.OUTLOOK.COM
ecma-testdl@my-safe-cloud.ch
Remote Server returned '554 5.1.0 < #5.1.10 smtp;550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient ecma-testdl@my-safe-cloud.ch not found by SMTP address lookup>'
Original message headers:
Received: from GV0P278CA0068.CHEP278.PROD.OUTLOOK.COM (2603:10a6:710:2a::19)
 by GV0P278MB0516.CHEP278.PROD.OUTLOOK.COM (2603:10a6:710:2e::11) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4087.25; Thu, 29 Apr
 2021 05:21:29 +0000
Received: from GV0CHE01FT017.eop-che01.prod.protection.outlook.com
 (2603:10a6:710:2a:cafe::be) by GV0P278CA0068.outlook.office365.com
 (2603:10a6:710:2a::19) with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.4087.27 via Frontend
 Transport; Thu, 29 Apr 2021 05:21:29 +0000
Authentication-Results: spf=none (sender IP is 85.115.54.190)
 smtp.mailfrom=sinara.ch; my-safe-cloud.ch; dkim=none (message not signed)
 header.d=none;my-safe-cloud.ch; dmarc=none action=none header.from=sinara.ch;
Received-SPF: None (protection.outlook.com: sinara.ch does not designate
 permitted sender hosts)
Received: from cluster-j.mailcontrol.com (85.115.54.190) by
 GV0CHE01FT017.mail.protection.outlook.com (20.128.123.108) with Microsoft
 SMTP Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.4087.27 via Frontend Transport; Thu, 29 Apr 2021 05:21:29 +0000
Received: from SRVSINMAIL01.sinara.local (26.186.62.81.static.wline.lns.sme.cust.swisscom.ch [81.62.186.26])
        by rly02j.srv.mailcontrol.com (MailControl) with ESMTPS id 13T5LSG8153133
        (version=TLSv1.2 cipher=ECDHE-RSA-AES256-SHA384 bits=256 verify=FAIL)
        for <ecma-testdl@my-safe-cloud.ch>; Thu, 29 Apr 2021 06:21:28 +0100
Received: from SRVSINMAIL01.sinara.local (192.168.0.32) by
 SRVSINMAIL01.sinara.local (192.168.0.32) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384) id
 15.1.2176.2; Thu, 29 Apr 2021 07:21:27 +0200
Received: from SRVSINMAIL01.sinara.local ([fe80::9860:895a:4adb:6c6]) by
 SRVSINMAIL01.sinara.local ([fe80::9860:895a:4adb:6c6%15]) with mapi id
 15.01.2176.012; Thu, 29 Apr 2021 07:21:27 +0200
From: Administrator <Administrator@sinara.ch>
To: "ecma-testdl@my-safe-cloud.ch" <ecma-testdl@my-safe-cloud.ch>
Subject: test 
Thread-Topic: test 
Thread-Index: Adc8t33bmEwxVKaYR3Cm5lK6bBL+xQ==
Date: Thu, 29 Apr 2021 05:21:27 +0000
Message-ID: <7b506e43bd2b40b2bd0fa318e8fe5e5f@sinara.ch>
Accept-Language: en-US, fr-CH
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-originating-ip: [27.57.20.104]
Content-Type: multipart/alternative;
        boundary="_000_7b506e43bd2b40b2bd0fa318e8fe5e5fsinarach_"
MIME-Version: 1.0
X-MailControl-OutInfo: MTYxOTY3MzY4ODpGUEtleTEucHJpdjoxl778QqeUTyOapKRYx3JQcbnxvcriJRTgVGW6q/ysBNmidv2VUJ+DXJddCmvzh2ZQRDJyqJmeCp6nT5reqE3czBaXzNSMRoKqWroSVUO6I7VJurFqxD24NcfMBD7bp8W4EbqL3ghhnT1OEwUB99QXJ88nLktbbYuPsKas7a3zmrQhNqkXLd5wWLm2j1/V4TH8hZ31SABUIcjXY90WaREhQg7F742yI0z6Pwx5yjxbjE4CJQJygGexm0Xg6wDe8AF5A8prLeHSM2tAwKpZKDlLfdXMKF7/zl42Vn5qSusLZghVfTcrEv4FPsWPVNqw221Wo6HA5X+qWJ/acbKRssgJ
X-Scanned-By: MailControl 44278.2108 (www.mailcontrol.com) on 10.74.0.112
Return-Path: Administrator@sinara.ch
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 15561f24-2574-42ae-a238-a90a85b408f1:0
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 211042f2-760e-4324-c3b9-08d90acea4d4
X-MS-TrafficTypeDiagnostic: GV0P278MB0516:

```

**Comment by racke** [comment]
The mail for the domain my-safe-cloud.ch is hosted by Outlook. How do you expect the email going from there to the list server?

**Comment by BenzirInterHyve** [comment]
As an expert, let me know where this needs to be hosted to make this work.





Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73D14.496ED700]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by BenzirInterHyve** [comment]
Okay from below i understood, it should be hosted some where else to make this work.


We are asking clarifications because we are not much aware of the tool. Rather than giving such one line questions ,it will be really if you can help us with some correct pointers or steps which will save my time and YOURS TOO.

Hope its clear.

Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73D15.01CDA1A0]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>



From: Benzir Mohammed
Sent: 29 April 2021 16:27
To: 'sympa-community/sympa' ***@***.***>; sympa-community/sympa ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [sympa-community/sympa] Mails cannot deliver to Mailing List (#1164)

As an expert, let me know where this needs to be hosted to make this work.





Benzir Mohammed


 [A screen shot of a person  Description automatically generated] <https://www.youtube.com/watch?v=zN9nang5aQI&t=3s>
***@***.***D73D15.01CDA1A0]
37/39 rue de Vermont
1202 Genève
T: +41 (22) 740 28 29
***@***.******@***.***>
www.interhyve.com<http://www.interhyve.com/>

**Comment by racke** [comment]
On 4/29/21 1:01 PM, BenzirInterHyve wrote:
> Okay from below i understood, it should be hosted some where else to make this work.
> 
> 
> We are asking clarifications because we are not much aware of the tool. 
Rather than giving such one line questions ,it
> will be really if you can help us with some correct pointers or steps which will save my time and YOURS TOO.
> 
> Hope its clear.
> 
> Benzir Mohammed

You can use a separate domain for the Sympa server or a smarthost that passes emails back and from to the Sympa server.

The pointers can only be as good as the information your provide, which was just a NDR.

Also please remember that this project is run by volunteers, so it is expected to at least some homework.

If that isn't sufficient, contract a professional Sympa expert.

Regards
       Racke

-- 
Ecommerce and Linux consulting + Perl and web application programming.
Debian and Sympa administration. Provisioning with Ansible.

**Comment by ikedas** [comment]
@BenzirInterHyve ,

Please read the [“Network requirements” section](https://sympa-community.github.io/manual/requirements.html#network-requirements) in “Requiments” page of the Administration manual. It says:
> * Finally, at least one **mail domain name** for the mailing list service is indispensable. Appropriate DNS resource record (MX, A, AAAA or any of them) for that domain must be advertised.

Please ask the person in charge of DNS for the domain “my-safe-cloud.ch”.

**Comment by ikedas** [comment]
There seem no more questions.  Close.
