### ISSUE TITLE
arc_srvid and arc_signer_domain settings

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1169]
Expected Behavior
-----------------

I should be able to set up ARC signing without having to update /etc/sympa/sympa.conf

Current Behavior
----------------

There appear to be two separate settings defined in  /etc/sympa/sympa.conf

arc_srvid   lists.cam.ac.uk
arc_signer_domain lists.cam.ac.uk

both of which are required for ARC to work. The second of these can also be updated on a per list basis in wwsympa:

  Edit List  Configuration ->   DKIM/DMARC/ARC

ARC signing only starts to work when I define arc_srvid in  /etc/sympa/sympa.conf: that  doesn't appear to be exposed at all in the wwsympauser interface.  

Possible Solution
-----------------

Merge the two settings using arc_signer_domain (defaulting to the DKIM signer_domain) everywhere?

 It isn't clear to be why two different values exist when they both seem to be the same thing. You should be able to enable (arc_feature) the second that DKIM is configured as they typically use the same keys and selectors.

**Comment by ikedas** [comment]
Please see [the description about the parameters for ARC](https://sympa-community.github.io/manual/customize/dkim-arc.html#incoming-messages-arc).  `arc_srvid` parameter may be different from `arc_signer_domain` parameter, and former is the same as latter by default.  `arc_srvid` may not be configured by each list.

**Comment by dpc22** [comment]
Got something working that I am happy with
