### ISSUE TITLE
mbox to sympa : doc about changes between old version (2006) and current version

### ISSUE THREAD

**Issue by PhilLAL** [sympa-community/sympa#117]
Hello,
I am interested into using http://www.sympa.org/distribution/contrib/import_mbox.sh to import MBOX into the archives of a list.
However, this script has been written in 2006 and makes some references to path which do not exist anymore : 
* "$SYMPA_ROOT/expl/$LIST_NAME/archives" 
* "$SYMPA_ROOT/bin/arc2webarc.pl" seems to refer to be by default into directory /usr/share/sympa/bin/arc2webarc.pl so $SYMPA_ROOT should be /usr/share/sympa
* "$SYMPA_ROOT/arc/$LIST_NAME@$SYMPA_DOMAIN" 
* $SYMPA_ROOT/spool/outgoing/.rebuild.$LIST_NAME@$SYMPA_DOMAIN"

From https://github.com/sympa-community/sympa/blob/6.2.22/configure.ac it seems: 
* "$SYMPA_ROOT/expl/$LIST_NAME/archives" is now "$SYMPA_ROOT/list_data/$LIST_NAME/archives" (cf. line 91), a solution would be to add a $SYMPA_EXPL variable set to "expl" or "list_data" depending on the Sympa version 
* "$SYMPA_ROOT/arc/$LIST_NAME@$SYMPA_DOMAIN" refers to "$SYMPA_ROOT/arc/$LIST_NAME@$SYMPA_DOMAIN" 
* $SYMPA_ROOT/spool/outgoing/.rebuild.$LIST_NAME@$SYMPA_DOMAIN" is still the same.

However, "$SYMPA_ROOT/arc/" is empty directory and "$SYMPA_ROOT/spool" does not exists.
Moreover, if $SYMPA_ROOT should be set to /usr/share/sympa, then $SYMPA_ROOT/list_data and $SYMPA_ROOT/arc do not exists anymore.

- Do you confirm some of these points?
- Do you know if there is any updated version somewhere?
- If not, is there somewhere a doc to understand how to convert this script for newer version?

Thank you.

**Comment by ikedas** [comment]
> If not, is there somewhere a doc to understand how to convert this script for newer version?

See [Directory layout](https://sympa-community.github.io/layout.html). To know these paths specific to your environment, see content of ``Sympa/Constants.pm`` under MODULEDIR directory.

Format of the file to trigger off rebuilding has been changed.  To know the newer format, request rebuilding from web interface with archived.pl being stopped, and see content of SPOOLDIR/outgoing directory.

**Comment by PhilLAL** [comment]
Thank you for your fast answer.
I add that these comments are based on a Debian installation (I just saw that several variables are not defined for Debian: $EXPLDIR , $SPOOLDIR, $LOCALEDIR , $STATICDIR, $ARCDIR, $BOUNCEDIR).
In addition $SPOOLDIT does not exist.

I am not sure to understand your suggestion. Could you confirm I should:
- kill archived.pl process
-go into "sympa admin" and then into "Archives"
-enter the name of a list even without putting anything into arc directory (it is currently empty)
-ask rebuild
-go into $SPOOLDIR/outgoing to look for something (what exactly will be the output?)
-start again archived.pl

**Comment by ikedas** [comment]
> I add that these comments are based on a Debian installation (I just saw that several variables are not defined for Debian: $EXPLDIR , $SPOOLDIR, $LOCALEDIR , $STATICDIR, $ARCDIR, $BOUNCEDIR).
> In addition $SPOOLDIT does not exist.

Directories marked "???" are under investigation. Please check your ``Sympa/Constants.pm`` and give feedback.

> I am not sure to understand your suggestion. Could you confirm I should:
> - kill archived.pl process
> -go into "sympa admin" and then into "Archives"
> -enter the name of a list even without putting anything into arc directory (it is currently empty)
> -ask rebuild
> -go into $SPOOLDIR/outgoing to look for something (what exactly will be the output?)
> -start again archived.pl

That's what I wanted to say. If archive.pl is running, it will immediately process the file and remove it.

**Comment by PhilLAL** [comment]
For debian directories, it seems to me they can be found here : https://packages.debian.org/stretch/amd64/sympa/filelist

**Comment by ikedas** [comment]
@PhilLAL, perhaps the script have to be modified as below (Replace `USER`, `GROUP` etc. with values in Sympa/Constants.pm):

| In import_mbox.sh                           | Would be modified to |
| --- | --- |
| `sympa:webserver`                            | `USER:GROUP` |
| `$SYMPA_ROOT/expl/$LIST_NAME` | `EXPLDIR/$SYMPA_DOMAIN/$LIST_NAME` (recommended) or `EXPLDIR/$LIST_NAME`  |
| `$SYMPA_ROOT/bin/arc2webarc.pl` | `SCRIPTDIR/arc2webarc.pl` [See Note below] |
| `$SYMPA_ROOT/arc`                         | `ARCDIR` |
| `$SYMPA_ROOT/spool`                     | `SPOOLDIR` |

  - [Note]  If list directory is `EXPLDIR/$SYMPA_DOMAIN/$LIST_NAME`, additional argument will be required to execute arc2webarc.pl, like:
    ```
    arc2webarc.pl $LISTNAME $SYMPA_DOMAIN
    ```

**Comment by ikedas** [comment]
Looks No more updates. Closed.
