### ISSUE TITLE
Raleway font

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1180]
Version
-------

6.2.62

Installation method
-------------------

My own rpm, derived from "official" RHEL 7 source rpm.

Actual behavior
---------------

One of my users reports:

> I’ve taken some time to look at Sympa interface.  I have an initial bit of constructive feedback about the font used for the system. 
> 
> The current font makes number nine (9) look like a lowercase letter g as it goes below the line the text is on.  This caused me to look a good few times to see if there was mistakes.   I think when Sympa is released to the wider community we’ll get a number people noticing the same issue.  See below for an example
> 
> Sympa list font (Raleway) makes numbers more difficult to see – note how numbers 9, 7 and 3 go below the line of letters making it harder to read.
> 

For reference they are referring to:
![Raleway](https://user-images.githubusercontent.com/1552579/119816381-8c43b300-bee4-11eb-9f45-d14eed141b89.jpg)

which looks like the following if I disable Raleway:
![NoRaleway](https://user-images.githubusercontent.com/1552579/119816390-8fd73a00-bee4-11eb-8917-bb89e39cae42.jpg)

Rather to my surprise, the user interface isn't  a complete disaster if I just disable the various mentions of Raleway in the CSS. Even the responsive theme works. However various elements in the above have obviously changed size.

My question: Am I going to regret just disabling Raleway?

**Comment by ikedas** [comment]
No problem.  You may freely override font families by customization.  In fact, style sheets for some particular languages override font families by default, for exact the reason you wrote.

**Comment by dpc22** [comment]
Thanks, I have done this.
