### ISSUE TITLE
Remove incomplete example intranet scenario

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#119]
According to @ikedas, intranet scenario are incomplete examples and should not be used.
This would mean removing the following files :
default/create_list_templates/intranet_list/comment.tt2
default/create_list_templates/intranet_list/config.tt2
default/create_list_templates/intranet_list/
default/scenari/access_web_archive.intranet
default/scenari/create_list.intranet
default/scenari/review.intranet
default/scenari/send.intranet
default/scenari/send.intranetorprivate
default/scenari/subscribe.intranet
default/scenari/subscribe.intranetorowner
default/scenari/visibility.intranet

**Comment by racke** [comment]
Can you please elaborate why they are incomplete? Some people might already use them.

**Comment by ikedas** [comment]
It's about [customization](https://github.com/ikedas/sympa-rpm/blob/78986b3fb04a399e0afa4c4c3a24f14b7ed68b4b/SPECS/sympa-6.2.spec.in#L433-L450) I made on rpm spec. I remember why I did it.

Intranet scenarios does not always work as expected (see [`default/scenari/*.intranet*`](https://github.com/sympa-community/sympa/tree/df8fef001a3a05799031e2f354fdf61b091b3f3b/default/scenari) scenarios: E.g. host names `list.example.org` and `client.example.org` never match), and they have to be modified on many sites. However, they are enabled by default and confused several users.

So I thought it would be better to be removed, moved to `doc/smaples`, or (as I did in spec above) disabled by default.

**Comment by qosobrin** [comment]
I absolutely agree with the removal. In my humble opinion a better solution would be the one I proposed in https://github.com/sympa-community/sympa/issues/171: implement a text box where the owners could add a list of domains from where the list could be added, viewed, etc.

**Comment by ikedas** [comment]
I'm reviewing intranet scenarios, and found they imply many weird behaviors.  For example, `archive_web_access.intranet`:
```
title.gettext restricted to local domain users

is_subscriber([listname],[sender])         md5,smime  -> do_it
is_listmaster([sender])                    md5,smime  -> do_it
match ([env->remote_host],/[conf->host]$/) md5,smime  -> do_it
match([sender],/[conf->host]$/)            md5,smime  -> do_it
true()                                     md5,smime  -> reject(reason='web_archive_local_user_sub')
```
  * This scenario is used only by web interface.  As `is_subscriber()` and `is_listmaster()` fail with anonymous (unauthenticated) users, `md5,smime` in the first and second rules are unnecessary.
  * The first `match()` fails in some cases, e.g. REMOTE_HOST `client.example.org` and `host` parameter `list.example.org`.
  * The second `match()` succeeds in some cases, e.g. `user@surrealist.example.org` and `list.example.org`.
  * If user has not logged in, they may be informed error instead of rejection message.

I suppose we would be better to do away with these scenarios rather than keeping them as samples.

**Comment by ikedas** [comment]
I decided to postpone correction of current intranet scenarios: They will be moved to `doc/samples/intranet`.:

``` code
doc/samples/intranet/create_list_templates/intranet_list/comment.tt2
doc/samples/intranet/create_list_templates/intranet_list/config.tt2
doc/samples/intranet/scenari/archive_web_access.intranet
doc/samples/intranet/scenari/create_list.intranet
doc/samples/intranet/scenari/review.intranet
doc/samples/intranet/scenari/send.intranet
doc/samples/intranet/scenari/send.intranetorprivate
doc/samples/intranet/scenari/subscribe.intranet
doc/samples/intranet/scenari/subscribe.intranetorowner
doc/samples/intranet/scenari/visibility.intranet
```
