### ISSUE TITLE
Unable to find scenario file "archive_web_access.intranet"

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#1193]
Using Debian bullseye/testing with package *sympa* 6.2.60~dfsg-4 (upgraded from earlier releases before), logging in over the Web interface, Sympa logs the error below (`journalctl -b -f`):

    wwsympa[1221323]: err main::#1825 > main::send_html#2436 > Sympa::Template::parse#461 > Template::process#66 > Template::Service::process#91 > (eval)#94 > Template::Context::process#321 > (eval)#351 > Template::Document::process#161 > (eval)#163 > Template::Document::__ANON__#3 > (eval)#2 > Template::Context::process#321 > (eval)#351 > Template::Document::process#161 > (eval)#163 > Template::Document::__ANON__#7 > (eval)#2 > Template::Context::process#321 > (eval)#351 > Template::Document::process#161 > (eval)#163 > Template::Document::__ANON__#7 > (eval)#75 > (eval)#58 > (eval)#58 > main::__ANON__#1640 > Sympa::Scenario::new#213 Unable to find scenario file "archive_web_access.intranet"

**Comment by ikedas** [comment]
Please see [the description](https://sympa-community.github.io/manual/upgrade/notes.html#from-version-prior-to-6250) in Upgrading notes.  Some scenarios and list creation templates for “intranet” use cases have been moved into samples.

**Comment by paulmenzel** [comment]
Thank you for the quick reply.

    $ dpkg -S intranet | sort
    sympa: /usr/share/doc/sympa/examples/samples/intranet
    sympa: /usr/share/doc/sympa/examples/samples/intranet/create_list_templates
    sympa: /usr/share/doc/sympa/examples/samples/intranet/create_list_templates/intranet_list
    sympa: /usr/share/doc/sympa/examples/samples/intranet/create_list_templates/intranet_list/comment.tt2
    sympa: /usr/share/doc/sympa/examples/samples/intranet/create_list_templates/intranet_list/config.tt2
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/archive_web_access.intranet
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/create_list.intranet
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/review.intranet
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/send.intranet
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/send.intranetorprivate
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/subscribe.intranet
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/subscribe.intranetorowner
    sympa: /usr/share/doc/sympa/examples/samples/intranet/scenari/visibility.intranet

Then I moved those:

    $ sudo cp -a /usr/share/doc/sympa/examples/samples/intranet/scenari/*intranet* /usr/share/sympa/default/scenari/
    $ sudo cp -a /usr/share/doc/sympa/examples/samples/intranet/create_list_templates/intranet_list /usr/share/sympa/default/create_list_templates

The error seems to be gone now (without restarting the Sympa processes).

But, I wonder if these are the right directories as they are controlled by the distribution package manager. Do you know the path for custom changes?

**Comment by racke** [comment]
Customizations are going into /etc/sympa, so save scenari into directory /etc/sympa/scenari.

**Comment by ikedas** [comment]
There seem no more questions. Close.
