### ISSUE TITLE
Add summary of outstanding moderation requests in "My lists" page

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1194]
Version
-------

6.2.62

Installation method
-------------------

My own rpm, derived from "official" RHEL source rpm.

My question
----------------

We are currently migrating 7,500 lists from Mailman  to Sympa.

One of my users, who is owner/moderator for around 50 lists, commented that there is no easy way to get a summary of outstanding moderation requests. Instead they have to go to the "/sympa/my" page and drill down onto each list in turn.

Vanilla Mailman has the same problem, but I created a custom "mylists" landing page, similar to (and in fact probably modelled on) the Sympa "my" page. This provides direct links to the Mailman "listinfo" and "admin" pages for each list, and a simple count of outstanding moderation requests for each list in the link to the moderation page, e.g: "Moderate (4 messages)".

Would something similar be possible in Sympa?

The complexWhich method in the SOAP API is very close to what I am looking for, but doesn't contain any information about outstanding moderation requests for each list in the response. I couldn't immediately find an API method that gave a count of outstanding moderation requests for a given list.

**Comment by dpc22** [comment]
Just to add. I can implement this using the following patch which generates $which->{$l}{mod_count} for all of the lists where someone is a owner/moderation/subscriber. The my.tt2 template can then decide precisely what to display.

[mod_count.patch.txt](https://github.com/sympa-community/sympa/files/6925796/mod_count.patch.txt)

I appreciate that my current approach is an awful hack, but there doesn't appear to be an obvious method that I can use in the Sympa::Spool::Moderation class that would give me a quick summary without having to interact through the actual messages using
Sympa::Spool->new()->next()

**Comment by ikedas** [comment]
Hi @dpc22 ,

Counting moderation requests on particular list may be done by
``` perl
$mod_count = Sympa::Spool::Moderation->new(context => $list)->size;
```

**Comment by dpc22** [comment]
Which would seem to be the attached, which is a bit less efficient but a lot more sensible than my initial effort. Thanks

[sympa-6.2.64-dpc_mod_count.patch.txt](https://github.com/sympa-community/sympa/files/6928945/sympa-6.2.64-dpc_mod_count.patch.txt)

The objective is something looking like:

![1](https://user-images.githubusercontent.com/1552579/128129757-a8734f19-3ffb-451b-97c4-3020878e08c0.jpg)

which works well when people admin or moderate _lots_ of lists.

I'm just going to deploy this on our lists server. I will come back later and work out how to submit a PR. Thanks,
