### ISSUE TITLE
A script for maintenance no longer works with Sympa 6.2.40

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1198]
I'm using sympa 6.2.40.
I have change owners and editors parameters into LDAP that related to 100 lists.
I need a script or a command or a feature into sympa.pl that updates owners, moderators lists into my lists
I was using a script for that with sympa 6.2.24 using sympa.pl but with sympa 6.2.40 , it doesn't update owners and moderators, only list members.
Thank you for your response.

**Comment by ikedas** [comment]
@khaoula-abaidi , can you show us the script you have been using for 6.2.24?

**Comment by khaoula-abaidi** [comment]
My script bash was : 

#!/bin/bash
#  $1 is the directory of lists + $2 is the robot
cd $1
robot=$2
list_lists=`ls`

for list in $list_lists
do
	/opt/sympa/bin/sympa.pl --sync_include=$list@$robot
done

**Comment by ikedas** [comment]
You may have to invoke this script as:

  - If you have setup Sympa with "single domain setting",
    ``` bash
    # path_of_script EXPLDIR mail.example.org
    ```
  - or, if you have setup Sympa with "virtual domain setting",
    ``` bash
    # path_of_script EXPLDIR/mail.example.org mail.example.org
    ```
where `EXPLDIR` and `mail.example.org` have to be replaced with the "list home" directory and the name of "robot", respectively (The "list home" directory is defined in the file `Constants.pm`).

I think the above does not change whether the version is 6.2.24 or 6.2.40.

**Comment by ikedas** [comment]
No more questions. Close.
