### ISSUE TITLE
custom_attributes are not transferred when subscribe action wasn't forwarded to the owner

### ISSUE THREAD

**Issue by mohicanb** [sympa-community/sympa#1199]
Sympa Version 6.2.40 supplied by ouvaton.coop

custom_attributes have been defined for the list

values of attributes can be inputted if the subscriber logs himself to the Sympa web interface : works OK

values of attributes can be inputted from the subscribe screen:
- values are transferred to the database when parameter "subscribe"=smimeorowner
- values are NOT transferred to the database when parameter "subscribe"=open_notify

My provider (ouvaton.coop) reported to me that nothing shows in the logs.

Thank you for investigating this.

**Comment by ikedas** [comment]
Hi @mohicanb ,

Could you please show us the process step-by-step that can reproduce the problem you reported?

**Comment by mohicanb** [comment]
Hi,
1. create a new list
2. set parameter subscribe to open_notify
3. create at least one custom_attribute
4. disconnect
5. go to the subscribe page for the list (as a not connected user)
6. input all the fields (email, name, custom_attribute)
7. subscribe to the list and confirm
8. confirm again when the confirmation email arrives
9. connect as list owner
10. go to the table of subscribers ("abonnés")
11. the new subscriber is in the table but the custom_attribute is empty.

**Comment by ikedas** [comment]
Hi @mohicanb , could you please check [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1216.patch)?  This will be included in the next beta released in this week.
