### ISSUE TITLE
Sympa does not start correctly after rebooting (debian package)

### ISSUE THREAD

**Issue by Salo15** [sympa-community/sympa#1200]
Hello, 

I have a question for the Debian packager.

After installing Sympa 6.2.40 as a Debian package on a Debian 10 machine, Sympa does not start correctly after rebooting the machine.
According to the log entries, Sympa cannot access the database (mariaDB):

Jun 24 06:37:04 lists-test task_manager[526]: err main::#148 > Sympa::Spindle::spin#78 > Sympa::Spool::next#124 > Sympa::Spool::Task::_load#57 > Sympa::Spool::Task::_create_all_tasks#93 > Sympa::List::get_lists#7525 > Sympa::DatabaseManager::instance#54 > Sympa: :DatabaseDriver::MySQL::connect#58 > Sympa::Database::connect#157 Can't connect to Database Sympa::DatabaseDriver::MySQL <db_host=localhost;db_name=sympa;db_port=3306;db_user=sympa>: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld. sock' (2)

The https://sympa-community.github.io/manual/install/automate-startup.html page documents how to configure systemd for automatic startup, but these instructions are actually for non-packaged installations.
I would expect the configuration of systemd to be included in the Debian package.
(But there is not even a directory /etc/systemd/system/sympa.service.d.)
Is this a bug in this debian package?

Kind regards,
Sabine

**Comment by ikedas** [comment]
Hi @Salo15 ,

Could you please try:

  1. stopping all of the services corresponding to Sympa, then
  2. starting the services.

Please see [Stopping and starting services](https://sympa-community.github.io/manual/admin/services.html#stopping-and-starting-services) in the manual for details.

**Comment by racke** [comment]
@Salo15 You can use "systemctl edit sympa.service"  to create this file.
Arguably this is a bug in the Debian package, so please open a bug report.

**Comment by Salo15** [comment]
Hello,

 

I stopped Sympa, Aapche2 and exim4 (in that order) and started them again in reverse.

There is no error message in the log and Sympa runs without error afterwards.

 

However, the error actually only occurs after a restart of the computer. It looks like the mariaDB database is not yet ready to accept connections at the time Sympa is started after the computer restart.

After a short time Sympa seems to be restarted again automatically. This works and Sympa then runs, but of course the error after the reboot still has to be fixed.

 

I suspect, as I said, that it is a problem with the Sympa Debian package.

 

Kind regards,

Sabine

 

Von: IKEDA Soji ***@***.***> 
Gesendet: Donnerstag, 24. Juni 2021 11:23
An: sympa-community/sympa ***@***.***>
Cc: Lorenz, Sabine (SCC) ***@***.***>; Mention ***@***.***>
Betreff: Re: [sympa-community/sympa] Sympa does not start correctly after rebooting (debian package) (#1200)

 

Hi @Salo15 <https://github.com/Salo15>  ,

Could you please try:

1.	stopping all of the services corresponding to Sympa, then
2.	starting the services.

Please see Stopping and starting services <https://sympa-community.github.io/manual/admin/services.html#stopping-and-starting-services>  in the manual for details.

**Comment by Salo15** [comment]
Hei,

 

thanks for your response.

 

where and how can I create and report the bug report for the Debian package?

 

As a workaround, can I also create the file /etc/systemd/system/sympa.service.d directly via Ansible.

Since we are using Ansible, we cannot use "systemctl edit sympa.service" to create the file.

 

Kind regards,

Sabine

 

Von: Stefan Hornburg (Racke) ***@***.***> 
Gesendet: Donnerstag, 24. Juni 2021 11:33
An: sympa-community/sympa ***@***.***>
Cc: Lorenz, Sabine (SCC) ***@***.***>; Mention ***@***.***>
Betreff: Re: [sympa-community/sympa] Sympa does not start correctly after rebooting (debian package) (#1200)

 

@Salo15 <https://github.com/Salo15>  You can use "systemctl edit sympa.service" to create this file.
Arguably this is a bug in the Debian package, so please open a bug report.

**Comment by racke** [comment]
Instructions for bug report: https://www.debian.org/Bugs/Reporting

**Comment by ikedas** [comment]
@Salo15 , could you please check if the drop-in unit fle in `/etc/systemd/system/sympa.service.d/` directory is configured appropriately?  For details see "[Automate startup](https://sympa-community.github.io/manual/install/automate-startup.html)" in the manual.

**Comment by Salo15** [comment]
Hello,

 

No, the directory /etc/system/system/sympa.service.d/ does not exist on the server.

I assumed that the description on the page is actually for non-packaged installations and expected the configuration of systemd to be included in the Debian package.

For this reason the question is also mainly directed to the Debian packagers and Stefan Hornburg has also already confirmed to me that it is probably a bug in the Debian package and I have created a bug report.

 

Kind regards,

Sabine

 

Von: IKEDA Soji ***@***.***> 
Gesendet: Freitag, 25. Juni 2021 23:53
An: sympa-community/sympa ***@***.***>
Cc: Lorenz, Sabine (SCC) ***@***.***>; Mention ***@***.***>
Betreff: Re: [sympa-community/sympa] Sympa does not start correctly after rebooting (debian package) (#1200)

 

@Salo15 <https://github.com/Salo15>  , could you please check if the drop-in unit fle in /etc/systemd/system/sympa.service.d/ directory is configured appropriately? For details see "Automate startup <https://sympa-community.github.io/manual/install/automate-startup.html> " in the manual.

**Comment by ikedas** [comment]
> No, the directory /etc/system/system/sympa.service.d/ does not exist on the server.

Please create a direftory `/etc/systemd/system/sympa.service.d/` and then create the file in it.

**Comment by racke** [comment]
@ikedas The recommended way is using  "systemctl edit sympa.service". No need to worry about the directory.

Closing the ticket in favor of the Debian bug report (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990441).

**Comment by Salo15** [comment]
For your information:

 

I tested it and the error stopped occurring only after I created /etc/systemd/system/sympa.service.d/, /etc/systemd/system/sympa-archived.service.d/, /etc/systemd/system/sympa-bounced.service.d/, /etc/systemd/system/sympa-bulk.service.d/ and /etc/systemd/system/sympa-task_manager.service.d/ with the same dependencies in addition to the /etc/systemd/system/sympa.service.d/ directory.

 

Kind regards,

Sabine

 

Von: Stefan Hornburg (Racke) ***@***.***> 
Gesendet: Dienstag, 29. Juni 2021 11:14
An: sympa-community/sympa ***@***.***>
Cc: Lorenz, Sabine (SCC) ***@***.***>; Mention ***@***.***>
Betreff: Re: [sympa-community/sympa] Sympa does not start correctly after rebooting (debian package) (#1200)

 

@ikedas <https://github.com/ikedas>  The recommended way is using "systemctl edit sympa.service". No need to worry about the directory.

Closing the ticket in favor of the Debian bug report (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=990441).

**Comment by ikedas** [comment]
> For your information: I tested it and the error stopped occurring only after I created /etc/systemd/system/sympa.service.d/, /etc/systemd/system/sympa-archived.service.d/, /etc/systemd/system/sympa-bounced.service.d/, /etc/systemd/system/sympa-bulk.service.d/ and /etc/systemd/system/sympa-task_manager.service.d/ with the same dependencies in addition to the /etc/systemd/system/sympa.service.d/ directory. 

You only have to create the first one.

Anyways please continue with Debian bug tracker.  This issue was closed.
