### ISSUE TITLE
missing parameters after upgrading from 6.1.11 to 6.2.62

### ISSUE THREAD

**Issue by JPBarriere** [sympa-community/sympa#1203]
missing parameters after upgrading from 6.1.11 to 6.2.62

Version
-------
6.2.62

Installation method
-------------------
install from sources

Expected behavior
-----------------
full migration of lists configuration

Actual behavior
---------------
some parameters missing
  - include_list
  - web_archive

Additional information
----------------------
the configuration methods for this have change and actually the upgrade process doesn't makes the necessary changes:

old version :
web_archive
access private

new version :
archive
web_access private
mail_access closed (ou private pour donner accès aux membres)

--------old  version
include_list liste1
include_list liste2
 
 
-------new version
include_sympa_list
name liste1
listname liste1
 
include_sympa_list
name liste2
listname liste2

**Comment by ikedas** [comment]
Hi @JPBarriere ,

As you told, `web_archive` and `include_list` have been obsoleted and replaced with their alternatives.  I guess the configuration had been modified automatically by running `sympa.pl --upgrade`.

**Comment by ikedas** [comment]
@JPBarriere , please read "(Upgrading notes)[https://sympa-community.github.io/manual/upgrade/notes.html] before upgrading.  Several things won't be upgraded automatically and will require manual intervention.  Especially, (upgrading from 6.1.x to recent version)[https://sympa-community.github.io/manual/upgrade/notes.html#upgrading-from-sympa-61x-or-earlier] requires some adjustments including modification of config files.

**Comment by ikedas** [comment]
No more questions. Close.
