### ISSUE TITLE
RFC 8058 One Click Unsubscribe

### ISSUE THREAD

**Issue by bcchrisupp** [sympa-community/sympa#1210]
Hello, 

I was wondering if there is a way to turn on "one click unsubscribe" headers as per RFC 8058. I know Sympa adds other list related headers but I couldn't find much about it's support for this particular one.

**Comment by ikedas** [comment]
Hi @bcchrisupp ,

How about using [unsubscription links](https://sympa-community.github.io/manual/customize/message-personalization.html#adding-unsubscription-links) in each distributed messages instead?

**Comment by bcchrisupp** [comment]
Hey @ikedas this isn't a bad approach functionally, but we were hoping that the RFC 8058 implementation might be possible/supported as it's one of the recommendations put forth by gmail for improving the deliverability of list mail https://support.google.com/mail/answer/81126?hl=en

**Comment by ikedas** [comment]
@bcchrisupp , please check the PR above.  Perhaps this will be part of the next beta.

**Comment by ikedas** [comment]
I checked with some MUAs.
  - Surprisingly, Gmail doesn't seem to support One-Click feature (nor even just the simple List-Unsubscribe field).  [Inbox](https://gmail.google.com/inbox/) used to support One-Click, but that didn't seem to carry over to Gmail when they were shut down.
  - iPhone Mail app supports this feature.

Naturally, MUAs that support only the simple List-Unsubscribe field will work as before.
