### ISSUE TITLE
Sympa does not like "`" chars in email addresses within include file

### ISSUE THREAD

**Issue by agouaux** [sympa-community/sympa#1217]
I noticed error messages like this when sympa tried to sync an include file that had a "`" in the local part of the address.  At first I was surprised that Office365 (location of our mailboxes) allowed it, but then I discovered that it was technically OK with the RFCs.  (I can re-dig up the references I found if necessary.)

```
Jun 25 23:20:14 sympa01 sympa[53065]: err main::#849 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#201 > Sympa::Request::Handler::include::_update_users#372 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#75 Skip badly formed line: "first1`.last1@x.org First1` Last1"

```

Version
-------
6.2.60

Installation method
-------------------
Source (that locally build into our own rpm)

Expected behavior
-----------------
I think so long as the "`" is in the local part, it should be considered ok, despite it being a bit odd.

Actual behavior
---------------
The sync of the include file never completes successfully.

Additional information
----------------------

**Comment by ikedas** [comment]
FYI.
### Sympa

Currently, Sympa allows the local part of e-mail to include either:
`0`-`9`, `a`-`z` (case-insensitive), `_`, `-`, `.`, `/`, `+`, `=`, `'` or `&`

or to match:
`".*"`

And it doesn't allow to include either:
`|`, `$`, `*`, `?` nor `!`

https://github.com/sympa-community/sympa/blob/e1555fc14e1e88d6c148a270295501bbb4928b11/src/lib/Sympa/Tools/Text.pm#L505-L515

https://github.com/sympa-community/sympa/blob/e1555fc14e1e88d6c148a270295501bbb4928b11/src/lib/Sympa/Regexps.pm#L33-L37

### RFC

OTOH, RFC 5322 allows "dot-atom-text" below in local part (except when it is enclosed in `"`...`"`) [\[1\]](https://datatracker.ietf.org/doc/html/rfc5322#section-3.2.3):

``` code
   atext           =   ALPHA / DIGIT /    ; Printable US-ASCII
                       "!" / "#" /        ;  characters not including
                       "$" / "%" /        ;  specials.  Used for atoms.
                       "&" / "'" /
                       "*" / "+" /
                       "-" / "/" /
                       "=" / "?" /
                       "^" / "_" /
                       "`" / "{" /
                       "|" / "}" /
                       "~"

   atom            =   [CFWS] 1*atext [CFWS]

   dot-atom-text   =   1*atext *("." 1*atext)

   dot-atom        =   [CFWS] dot-atom-text [CFWS]

   specials        =   "(" / ")" /        ; Special characters that do
                       "<" / ">" /        ;  not appear in atext
                       "[" / "]" /
                       ":" / ";" /
                       "@" / "\" /
                       "," / "." /
                       DQUOTE

```
