### ISSUE TITLE
What are the variables we can use in message personalization?

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#1221]
Version
-------
Sympa version 6.2.64

Installation method
-------------------
Source package

Expected behavior
-----------------
I want to use the personalization_feature with custom_attribute but it doesn't work.
I have defined :

db_additional_subscriber_fields	server_subscriber, skey01

and 

db_additional_user_fields ukey01

I send an email with (or posted through the web interface)

 - :  [% user.custom_attribute.ukey01 %] ou  [% user.ukey01 %] ou [% user.email %]

 - :  [% subscriber.custom_attribute.skey01 %] ou  [% subscriber.ukey01 %] ou [% subscriber.email %]

but only [% user.email %] is personalized

How can I use the custom_attribute ?

Actual behavior
---------------
only [% user.email %] is personalized

**Comment by ikedas** [comment]
Hi @pascalmaes ,

You may define "Custom user attributes" (`custom_attribute` parameters) in list config to use `custom_attribute`  with personalization_feature.  Please see also [Custom user attributes](https://sympa-community.github.io/manual/customize/custom-user-attributes.html).

**Comment by pascalmaes** [comment]
Thanks,

But with a text like

[% user.custom_attribute.ukey01 %] ou [% user.email %]

I get

HASH(0x72605a0) ou pascal.maes@uclouvain.be

**Comment by ikedas** [comment]
Please show us the `custom_attribute` paragraphs in the list config.

**Comment by pascalmaes** [comment]
Here it is

custom_attribute
type string
optional optional
name ukey01
id ukey01

and the content of the subscriber_table

<?xml version="1.0" encoding="UTF-8" ?><custom_attributes><custom_attribute id="ukey01"><value>pascal.maes@uclouvain.be</value></custom_attribute></custom_attributes>

**Comment by pascalmaes** [comment]
Hello,

Any idea why I get a HASH instead of the string value ?

Thanks

**Comment by ikedas** [comment]
Hi @pascalmaes ,

Please try
``` code
: [% user.custom_attribute.ukey01.value %] ou [% user.email %]
```

**Comment by pascalmaes** [comment]
Hello Ikeda,


Well done!

Thanks

**Comment by pascalmaes** [comment]
Hi

What are the variables we can use in message personalization?
There are custom_attribute, [% user.email %], [% listname %], what else?

**Comment by ikedas** [comment]
The manual has been updated.  Please see "[List of template variables](https://sympa-community.github.io/manual/customize/message-personalization.html#list-of-template-variables)".
