### ISSUE TITLE
Robot listmasters can edit site templates

### ISSUE THREAD

**Issue by svenseeberg** [sympa-community/sympa#1224]
A robot listmaster is able to copy a template and set scope to "site".
![image](https://user-images.githubusercontent.com/15197000/130049797-84737021-70b6-4f66-89dd-be8743d496a0.png)

Version
-------
6.2.40~dfsg-1+deb10u1

Installation method
-------------------
Debian Buster package

Expected behavior
-----------------
Robot listmasters should only be able to copy & edit templates in the robot and lists scope, not site scope. Only the Super listmasters should be able to change site (global) templates.

Actual behavior
---------------
A robot listmaster is able to copy a template and set scope to "site". The changes are then visible in all robots, even if they're not managed by the same robot listmaster. 

Workaround
---------------
Remove write permissions to `/etc/sympa/web_tt2`. This will prevent robot listmaster from writing files to this directory. As the global listmaster is probably also the server admin, the server admin can write files to this directory.

**Comment by svenseeberg** [comment]
Thanks a lot. I did not have a test server at hand so quickly and the production server is hard to patch as it is running with the Debian Buster package.

**Comment by ikedas** [comment]
@svenseeberg , it's ok.  The patch was included in the recent beta release, and we will try testing it.  Thank you for reporting bug!
