### ISSUE TITLE
Alias creation does not work without files migrating 6.2.58 to 6.2.64

### ISSUE THREAD

**Issue by Bbertatum** [sympa-community/sympa#1228]
Version
-------
sympa.pl --version
6.2.58 to 6.2.64

Installation method
-------------------
rpm packages

Expected behavior
-----------------

Generate postfix/sendmail aliases from database information.

Actual behavior
---------------

Instead of picking up information about lists to generate postfix/sendmail aliases  sympa.pl --make_alias_files is based on the directories in "list_data" directory nothing printed as error message (coherence between DB and files) or error message. The alias files generated is just empty.

It seems comfortable and easier to understand that the software at least print an error message about missing directories. 
Ideally the alias file could be generated using database information instead of directories. This to have a more "understandable" or one way to do these thing.

**Comment by ikedas** [comment]
No more questions. Close.
