### ISSUE TITLE
Automatic list validation

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1229]
Is there a feature or a program that allow validation list creation automatically ? 
For example it verify some parameters ( mail of the owner  : who create the list and ask for validation, mail of the owner from an external source : LDAP, Database .....) ?

Sympa version 
-----------------
6.2.40

Expected Behavior
-----------------
The list is for waiting validation
Listmaster receive an email for the request and the automatic process ( validation or not)

Current Behavior
----------------
Listmaster receive an email and validate the list after a manual verification of the owner ( if its on the external resource and the availability of his mail)

Possible Solution
-----------------
Sympa perl program ( process) 
Script 
Plugin 
-------
Thank you for your response

**Comment by khaoula-abaidi** [comment]
Hi, 
Thank you for your response.
Is it possible to customize the validation for a specific filter from LDAP.
For example accept only an automatic validation for teachers and employees (Source : filter from LDAP)
Thank you for your response ?

**Comment by racke** [comment]
You could create a custom scenari for create_list with a LDAP search filter, see https://sympa-community.github.io/manual/customize/basics-scenarios.html "Named Filters".
