### ISSUE TITLE
Customize response closed list

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1233]
Hi,
Is it possible to send an automatic customized response from a closed list using sympa 6.2.40 ?
Thank you for your response

**Comment by ikedas** [comment]
Currently no.

If you use aliases file, i.e. you are setting parameters including `sendmail_aliases`, `aliases_program`, alias entries for closed lists will be removed from aliases file.  You may manually add alternative entries for these lists to direct incoming messages to any autoresponding program.

**Comment by khaoula-abaidi** [comment]
Indeed,
 I wanted to know if there is not an alternative without adding manual changes for aliases or adding rules in the MTA.
Thanks for your response
