### ISSUE TITLE
tracking=verp generates multiple messages for each tracked user

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1249]
Version
-------
6.2.66

Installation method
-------------------
My own rpm, derived from "official" Redhat rpm.

Expected behavior
-----------------

 Sympa should only send a single message to each subscriber where we use tracking=verp because of previous bounce state.

Actual behavior
---------------

These addresses receive multiple messages. If a list has several hundred bouncing subscribers using tracking=verp that is a lot of extra messages.

Additional information
-------

The following are the same Sympa:Message processed by Sympa::Spindle::ProcessOutgoing::_twist(), all generated by
a single message with Message-ID:

LO3P123MB289038B43701E5A8D1C317F095B19@LO3P123MB2890.GBRP123.PROD.OUTLOOK.COM

```
Oct  7 09:35:03 lists-1 bulk[11316]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <5.5.1633595548.1633595553.612842.YYY@lists.cam.ac.uk_0,11305,8061/0/shelved:arc_cv=pass;decorate;dkim_sign;dmarc_protect;tracking=verp> to Sympa::List <YYY@lists.cam.ac.uk> (priority 5) (starting 155 seconds after scheduled expedition date)
Oct  7 09:59:26 lists-1 bulk[23312]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <5.5.1633595548.1633595553.612842.YYY@lists.cam.ac.uk_0,11305,8061/0/shelved:arc_cv=pass;decorate;dkim_sign;dmarc_protect;tracking=verp> to Sympa::List <YYY@lists.cam.ac.uk> (priority 5) (starting 1618 seconds after scheduled expedition date)
Oct  7 10:59:21 lists-1 bulk[14089]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <5.5.1633595548.1633595553.612842.YYY@lists.cam.ac.uk_0,11305,8061/0/shelved:arc_cv=pass;decorate;dkim_sign;dmarc_protect;tracking=verp> to Sympa::List <YYY@lists.cam.ac.uk> (priority 5) (starting 5213 seconds after scheduled expedition date)
```
I have censored the list name as "YYY@lists.cam.ac.uk". This is the same list in all three cases.

This generated three separate messages to each subscriber using tracking=verp on the list.  Exim logs demonstrating three VERP deliveries for the same user and the same Message-ID:
```
2021-10-07 09:45:15 +0100 1mYP1B-0005wU-AB <= bounce+XXX==a==cam.ac.uk==YYY@lists.cam.ac.uk U=sympa P=local S=9524890 id=LO3P123MB289038B43701E5A8D1C317F095B19@LO3P123MB2890.GBRP123.PROD.OUTLOOK.COM for XXX@cam.ac.uk
2021-10-07 10:17:56 +0100 1mYPWE-0002ey-VH <= bounce+XXX==a==cam.ac.uk==YYY@lists.cam.ac.uk U=sympa P=local S=9524890 id=LO3P123MB289038B43701E5A8D1C317F095B19@LO3P123MB2890.GBRP123.PROD.OUTLOOK.COM for XXX@cam.ac.uk
2021-10-07 11:17:59 +0100 1mYQSK-0006SP-Vt <= bounce+XXX==a==cam.ac.uk==YYY@lists.cam.ac.uk U=sympa P=local S=9524890 id=LO3P123MB289038B43701E5A8D1C317F095B19@LO3P123MB2890.GBRP123.PROD.OUTLOOK.COM for XXX@cam.ac.uk
```
I have censored username@cam.ac.uk as XXX@cam.ac.uk (the same XXX in all three cases).

My solution/workaround was to disable tracking=verp entirely.

**Comment by dpc22** [comment]
I will see what I can find. 

The obvious thing that jumped out at me (as reported in the other thread) is that each bulk.pl reported _nothing at all_ while they were processing these tracking=verp requests, until the process was interrupted by a higher priority message:
```
Oct  7 09:31:13 lists-1 bulk[14089]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <5.5.1633595335.1633595335.189988.YYY@lists.cam.ac.uk_0,11305,5650/0/shelved:arc_cv=pass;decorate;dkim_sign;dmarc_protect;tracking=verp> to Sympa::List <YYY@lists.cam.ac.uk> (priority 5) (starting 138 seconds after scheduled expedition date)
<no further mentions of bulk[14089] until:>
Oct  7 10:56:00 lists-1 bulk[14089]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <1.5.1633597195.1633597194.442549.sympa@lists.cam.ac.uk_s,11305,8526/s/shelved:dkim_sign> to lists.cam.ac.uk (priority 1) (starting 3365 seconds after scheduled expedition date)
```
In the intervening 85 minutes, that bulk.pl process was generating VERP messages one at at time, presumably 103 times.

Each message took at least 30 seconds to process: I could watch it spin up a sendmail (actually Exim) process and pipe the message each. Each message took a long time to complete simply because a 9.5 MByte message was involved.

**Comment by racke** [comment]
@ikedas It would be good if the lock errors could bubble at the top and appear in the log file. Currently it seems they are just discarded.
