### ISSUE TITLE
No attach recived from mailing list where subscribes are set hmtl-only mode option

### ISSUE THREAD

**Issue by MorenoUniTN** [sympa-community/sympa#125]
Hi,
i have much list configured with subsriber are in html-only mode setting on you recived option, but in this case if i send an attachment to te list it's not sed it.
The body of the sended mail is ok , but not recive any attach

If view the maillog i see a first size correct, but the second is more less than first

MailLog
----------------
```
Nov 13 08:46:01 list sendmail[23747]: vAD7k1UG023747: from=<nome.cognome@dominio.it>, **size=24332**, class=0, nrcpts=1, msgid=<d5518074c55c5d97xxxx@mail.domain.com>, proto=ESMTP, daemon=IPv4, relay=[192.168.119.9]
Nov 13 08:46:02 list sendmail[23748]: vAD7k1UG023747: to="| /usr/libexec/sympa/queue namelist@list.domain.it", ctladdr=<namelist@list.domain.it> (8/0), delay=00:00:01, xdelay=00:00:01, mailer=prog, pri=54518, dsn=2.0.0, stat=Sent
Nov 13 08:46:04 list sendmail[23752]: vAD7k4Gv023752: Authentication-Warning: list.unitn.it: sympa set sender to acn-lab-students-owner@list.cimec.unitn.it using -f
Nov 13 08:46:04 list sendmail[23752]: vAD7k4Gv023752: from=namelist@list.doimain.it, **size=9115**, class=-30, nrcpts=12, msgid=<d5518074c55c5d97xxxx@mail.domain.com>, relay=sympa@localhost
Nov 13 08:46:04 list sendmail[23754]: vAD7k4Dn023754: from=<namelist@list.domain.it>, **size=9354**, class=-30, nrcpts=12, msgid=<d5518074c55c5d97xxxx@mail.domain.com>, proto=ESMTP, daemon=MTA, relay=localhost [127.0.0.1]
```
----------------

**Comment by ikedas** [comment]
[Discussion on sympa-users](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2017-11/e56c4696-43f0-e6f1-2a38-08b44bfa944f%40renater.fr).

I suppose ``htmlonly`` mode would be better to be removed. If there no objection, I'll do it.

**Comment by racke** [comment]
Yes please remove it 👍

**Comment by MorenoUniTN** [comment]
Yes for me.
Thanks for all!

**Comment by ikedas** [comment]
Please check if [this patch](https://github.com/sympa-community/sympa/commit/a47309b62c339cf5a69c76dcb9f6ce6423931969.patch) will solve the problem.

**Comment by ikedas** [comment]
Ok, it seems fixed. Close.
