### ISSUE TITLE
Login button does not work as expected with FastCGI service

### ISSUE THREAD

**Issue by Philippe34** [sympa-community/sympa#1257]
Version
-------
Sympa 6.2.58 RPM on CentOS 7.9.2009

Installation method
-------------------
Until now, my sympa web interface is configured with wwsympa-wrapper.fcgi and it works good.
I know it is unsecure and depricated. So I tried to configure with fastCGI service and I have a bug with the login button.

Expected behavior
-----------------
When I click on login button, I should have the login windows with email address and password, as I have with the wrapper)

Logs with the wrapper:

> wwsympa[1997]: info main::**do_login()** [robot ies.univ-montp2.fr] [session 31559278677057] [client 162.xxx]
> wwsympa[1997]: info main::**do_login()** [robot ies.univ-montp2.fr] [session 31559278677057] [client 162.xxx]

Actual behavior
---------------
Instead, the clic on the login button shows me the lists

Logs:

> wwsympa[2024]: info main::**do_lists(, )** [robot ies.univ-montp2.fr] [session 31559278677057] [client 162.xxx]
> wwsympa[2024]: info main::**do_lists(, )** [robot ies.univ-montp2.fr] [session 31559278677057] [client 162.xxx]

I have this issue since sympa 6.2.40
All the rest of the interface seem to work.

What could I do to fix the issue ?
Thanks for your help

Additional information
----------------------

The wwsympa.service is loaded and works  :

```
#systemctl status wwsympa.service
● wwsympa.service - WWSympa - Web interface for Sympa mailing list manager
   Loaded: loaded (/usr/lib/systemd/system/wwsympa.service; disabled; vendor preset: disabled)
   Active: active (running) since mar. 2021-10-19 12:14:30 CEST; 17min ago
  Process: 2022 ExecStart=/usr/bin/spawn-fcgi -F $FCGI_CHILDREN -P /run/sympa/wwsympa.pid -s /run/sympa/wwsympa.socket -u $FCGI_USER -g $FCGI_GROUP $FCGI_OPTS -- /usr/libexec/sympa/wwsympa.fcgi (code=exited, status=0/SUCCESS)
 Main PID: 2023 (wwsympa.fcgi)
   CGroup: /system.slice/wwsympa.service
           ├─2023 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
           ├─2024 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
           ├─2025 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
           ├─2026 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
           └─2027 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
```

The sympa.conf httpd is:

```
<IfModule mod_proxy_fcgi.c>
        <Location /sympa>
        SetHandler "proxy:unix:/run/sympa/wwsympa.socket|fcgi://"
        Require all granted
    </Location>
</IfModule>

## Other static contents
<Location /static-sympa>
    Require all granted
</Location>
Alias /static-sympa/fonts/font-awesome/css /usr/share/font-awesome-web/css
Alias /static-sympa/fonts/font-awesome/fonts /usr/share/fonts/fontawesome
Alias /static-sympa/css /var/lib/sympa/css
Alias /static-sympa/pictures /var/lib/sympa/pictures
Alias /static-sympa /usr/share/sympa/static_content
```

apache can access to the socket:
```
# ll /run/sympa/ww*
-rw-r--r--. 1 root   root   24 19 oct.  12:14 /run/sympa/wwsympa.pid
srw-------. 1 apache apache  0 19 oct.  12:14 /run/sympa/wwsympa.socket
```

**Comment by Philippe34** [comment]
I have switched to the  wwsympa.service and I can click on the loggin button anywhere.
So I send the code source of the page when I'm going to the URL https://listhost.ies.univ-montp2.fr
[https _listhost.ies.univ-montp2.fr_sympa_FastCGI.htm.txt](https://github.com/sympa-community/sympa/files/7379363/https._listhost.ies.univ-montp2.fr_sympa_FastCGI.htm.txt)

After I have clicked, I have this code source:
[https _listhost.ies.univ-montp2.fr_sympa_afterclickLoginButton.htm.txt](https://github.com/sympa-community/sympa/files/7379399/https._listhost.ies.univ-montp2.fr_sympa_afterclickLoginButton.htm.txt)

It seems there are no differences.
So obstensibly the login button does nothing

**Comment by ikedas** [comment]
@Philippe34 ,
- Please clear the cache and cookies of your web browser, and restart it then try again.
- If any kind of proxies are working between Sympa server and your browser, try connecting without going through those proxies and so on.

**Comment by Philippe34** [comment]
@ikedas 

I don't think it is cache or cookies problems of my web browser. I did what you said, but nothing changed whatever the browser, Firefox, Chrome ...
At this moment my config works with the wwsympa.service. Yourself, you should see the bug. But if again, I switch to the wrapper, you could see that the button works again.

I can not understand why there is a difference in operation of Sympa between the wrapper and the mod_proxy_fcgi of apache. Maybe a bug in the version of this httpd module in centOS 7 (2.4.6-97.el7.centos.1)

Hum ... I can stay to work with the wrapper. But could you confirm me that I could continue to upgrade to the last release of sympa without using the wwsympa.service ?

Thanks for your advices.

**Comment by Philippe34** [comment]
No proxy between Sympa server and my browser. The link https://listhost.ies.univ-montp2.fr is direct

**Comment by ikedas** [comment]
@Philippe34 ,

  - Can you show the content of `wwsympa.service`?

  - Can you add these lines at the beginning of httpd's `sympa.conf`?
    ```
    LoadModule alias_module modules/mod_alias.so
    LoadModule proxy_module modules/mod_proxy.so
    LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so
    ```

**Comment by Philippe34** [comment]
/usr/lib/systemd/system/wwsympa.service:
```
[Unit]
Description=WWSympa - Web interface for Sympa mailing list manager
After=syslog.target sympa.service

[Service]
Type=forking
PIDFile=/run/sympa/wwsympa.pid
ExecStart=/usr/bin/spawn-fcgi -F $FCGI_CHILDREN \
    -P /run/sympa/wwsympa.pid \
    -s /run/sympa/wwsympa.socket \
    -u $FCGI_USER -g $FCGI_GROUP $FCGI_OPTS -- \
    /usr/libexec/sympa/wwsympa.fcgi
Environment="FCGI_CHILDREN=5"
Environment="FCGI_USER=sympa"
Environment="FCGI_GROUP=sympa"
Environment="FCGI_OPTS=-M 0600 -U nginx"
EnvironmentFile=-/etc/sysconfig/sympa
Restart=always

[Install]
WantedBy=multi-user.target
```

If I add the lines below in sympa.conf, that confirms me that the modules are already loaded:

```
# apachectl configtest
[Mon Nov 01 22:46:17.764017 2021] [so:warn] [pid 644] AH01574: module alias_module is already loaded, skipping
[Mon Nov 01 22:46:17.764389 2021] [so:warn] [pid 644] AH01574: module proxy_module is already loaded, skipping
[Mon Nov 01 22:46:17.764424 2021] [so:warn] [pid 644] AH01574: module proxy_fcgi_module is already loaded, skipping
Syntax OK
```

**Comment by ikedas** [comment]
@Philippe34 , with sympa-6.2.60 on CentOS7, I cannot reproduce the problem you reported.

  - Update sympa & sympa-httpd to the most recent RPM.
  - Remove _all_ settings in `sympa.conf` _except_ `domain`, `listmaster`, `db_XXX` and `wwsympa_url`, restart all services, and then check if Sympa and web interface will work as expected.
  - After the success, make sure it works correctly, changing  single parameter at a time.

**Comment by Philippe34** [comment]
All right @ikedas 
I'll do it as soon as possible.

**Comment by ikedas** [comment]
No more information.  This issue is closed for now.  If you got additional information, please request re-open.
