### ISSUE TITLE
Sympa 6.2.66 not available on EPEL repository

### ISSUE THREAD

**Issue by RENR0b1** [sympa-community/sympa#1258]
Version
-------
Sympa 6.2.58 on CentOS7

Installation method
-------------------
rpm 

Expected behavior
-----------------
'yum upgrade sympa' command should propose me release 6.2.66

Actual behavior
---------------
'yum upgrade sympa' command propose me release 6.2.64

Additional information
----------------------

**Comment by xavierba** [comment]
sympa 6.2.68 is on its way to EPEL 7.
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-15c9e0d58d
Sorry for forgetting to push 6.2.66.

**Comment by RENR0b1** [comment]
No problem. Thank you verry much for your job.
