### ISSUE TITLE
migration from virtual robot into same server

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1274]
SYMPA VERSION : 6.2.40
WEB SERVER: APACHE
DATABASE: MYSQL 
To migrate 400 lists from one virtual robot to another on the same server.
I am in the process of developing a script where :

1. I transfer the scenarios, the data sources, the topics to the new robot
2. I move the lists by the rename_list option of sympa.pl
3. I modify options into sympa.conf
4. I remove the old virtual host into Apache configuration

Did I forget a step ?

**Comment by racke** [comment]
You might have to adjust your mail server configuration.

Which options are you going to modify in sympa.conf?

**Comment by khaoula-abaidi** [comment]
> You might have to adjust your mail server configuration.
> 
> Which options are you going to modify in sympa.conf?

Sorry i mean into robot.conf like listmasters 
Thank you for your response

**Comment by ikedas** [comment]
Stale issue.  Close.
