### ISSUE TITLE
Is there a way to prevent Sympa from using alias addresses with suffixes (like "-request")?

### ISSUE THREAD

**Issue by qulien** [sympa-community/sympa#1275]
Version
-------
 - Sympa 6.4.20

Expected behavior
-----------------
I assumed the `anonymous_sender` address would always be used when the system sends out any kind of communication. 

Actual behavior
---------------
Automatic messages, like welcome or unsubscribe messages, will come from aliases like `listname-request@example.com`. 

Additional information
----------------------
There might already be a way to customize this, but I don't know it and couldn't figure it out via the documentation.

**Comment by ikedas** [comment]
No answer.  I.e. there seem no ways to make Sympa to use arbitrary address for originator of the automatic messages.

This issue will be cloase for now.

**Comment by racke** [comment]
You can rewrite the sender address through your local MTA.
