### ISSUE TITLE
Force Spool digest

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1280]
Hello,
I'm using Sympa 6.2.40.
I have mails into /var/spool/sympa/digest/name_liste.
How can i force sending these mails ? Or to deplace them into postfix queue ?
Yours Faithfully

**Comment by ikedas** [comment]
Hi @khaoula-abaidi ,

You may use `sympa.pl --send_digest`.  Please read the [manual page of `sympa.pl`](https://sympa-community.github.io/gpldoc/man/sympa.1.html).

**Comment by khaoula-abaidi** [comment]
Thank you for your response. 
Into the manual this option is used to force send_digest for all lists into /var/spool/sympa/digest ? 
Is it possible to use it only for  a specific list ?

**Comment by ikedas** [comment]
No, this option is used to force sending digest for all of lists.

**Comment by ikedas** [comment]
Duplicate of #1097 .
