### ISSUE TITLE
error create_list

### ISSUE THREAD

**Issue by sweetnight19** [sympa-community/sympa#1281]
Version 6.2.40
-------

Installation method
-------------------
I have followed the installation process of the official page 

Actual behavior
---------------
Sympa web:
![image](https://user-images.githubusercontent.com/24542429/143435270-b06c5a47-fd1f-44a8-b359-66f6254ada41.png)

check syslog:
![image](https://user-images.githubusercontent.com/24542429/143435368-5f3bde1c-3b93-4979-895d-b7e129b02af6.png)

**Comment by ikedas** [comment]
Hi @sweetnight19 ,

> Installation method
> I have followed the installation process of the official page

There are more than one methods to install Sympa.  Please write what you actually did in details.

> Actual behavior

- Please write _everything_ you did ("I opened the URL xxx, clicked the button 'xxx', ..." and so on),
- and please show the log _from when_ you started the operation _to when_ the error message was shown.

**Comment by ikedas** [comment]
Not enough infomration. Close for now.
