### ISSUE TITLE
Hide create list template

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1284]
Hi,
I m using sympa 6.2.40 and i'm using the manual https://sympa-community.github.io/manual/admin/list-creation.html#typical-list-profile
I can modify a templates for creation list and get them into the interface web.
My templates are into /etc/sympa/myrobot/create_list_templates
But i can't hide some templates.
How can i do it ?
Thank you for your response

**Comment by racke** [comment]
You can configure that in `create_list.conf`. For example, if you want to hide all standard list templates and only show your "distributionlist" template:

```
default hidden
distributionlist read
```
