### ISSUE TITLE
create a list as copy does not copy all configuration (template files)

### ISSUE THREAD

**Issue by igoltz** [sympa-community/sympa#1290]
Creating a new list as copy of an existing one then this does not
1. copy multipart mime footer/header (*.mime files)
2. copy template directories

Version
-------
probably all new, seen in 6.2.64

Installation method
-------------------
from source package

Expected behavior
-----------------
If creating a new list as copy of an existing one then this should also

1. copy multipart mime footer/header (*.mime files)
2. copy template directories

Actual behavior
---------------
Creating a new list as copy of an existing one then this does not
1. copy multipart mime footer/header (*.mime files)
2. copy template directories

Additional information
----------------------
See PR #1289 for a simple fix
The fix (PR) does this by adding both *.mime files to the list of file.
And by fixing the copy logic to also copy template directories.

**Comment by ikedas** [comment]
@igoltz , your fix has been merged.  Thank you for reporting and fixing the bug!
