### ISSUE TITLE
Listmaster Admin's menu entry "Edit Robot Config" missing when in "Skins, CSS and colors"

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1291]
Version
-------
sympa-6.2.66
debian 11
apache 2.4.51

Installation method
-------------------
From source
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --enable-fhs --sysconfdir=/etc/sympa --sbindir=/usr/lib/sympa/bin --libexecdir=/usr/lib/sympa/bin --with-cgidir=/usr/lib/cgi-bin/sympa --with-staticdir=/usr/share/sympa/static_content --with-cssdir=/var/lib/sympa/css --with-picturesdir=/var/lib/sympa/pictures --datadir=/usr/share --localedir=/usr/share/locale --mandir=/usr/share/man --with-unitsdir=/usr/lib/systemd/system --without-initdir --docdir=/usr/share/doc/sympa --with-piddir=/run/sympa --with-perl=/usr/bin/perl --with-user=sympa --with-group=sympa --with-aliases_file=/etc/mail/sympa/aliases --disable-setuid-fcgi

Expected behavior
-----------------
All Listmaster Admin's menu entries should be visible no matter the entry you are at.

Actual behavior
---------------
"Edit Robot Config" menu entry becomes unavailable when pressing on "Skins, CSS and colors".

**Comment by ikedas** [comment]
@qosobrin , could you please apply [this patch](https://github.com/ikedas/sympa/commit/7846ff1553c23f796f8fb4a920bc3718a14ffbd6.patch) and check if the problem will be solved?  Thanks.

**Comment by qosobrin** [comment]
Hi, @ikedas, I patched the file and everything works fine now. Thank you for your prompt answer and for the solution. Close this issue as you wish.

Best regards.
