### ISSUE TITLE
Is it possible to add a member on to a mailing list for a limited duration ? 

### ISSUE THREAD

**Issue by olanag1** [sympa-community/sympa#1298]
Hello, 

Does anybody know if it is possible to add members to a list for a determined duration in sympa mailing lists ? 

We have internships who stays for a short duration from 4 weeks to 6 month. We are looking for a solution to include them to our mailing list, but adding manually the subscription and unsubscription for ~40 persons per year seems to be quite a lot to think about, so I'm looking for a solution if can make this automatically. 

Thanks in advance for your solutions, 
Regards, 
Olga

**Comment by racke** [comment]
Hello Olga,

I suggest to use list inclusions (https://sympa-community.github.io/manual/customize/data-sources.html). If you add / remove the intern from the external source it will be added / removed from the list after a short time.

Regards,
     Racke

**Comment by olanag1** [comment]
Thanks Racke, 

That means that somebody still need to think to remove the person from the list when the internship is ended. If there were a feature that we can precise the end date for that person to be removed, it can be very helpful, because in general people forget to remove them from the list once they are left.

**Comment by ikedas** [comment]
There seem no more information.  This issue is closed.

@olanag1 , when the users in external data source (e.g. text file, database table) are removed in some ways (such as periodical cron job), included users in the list of Sympa will be removed.  The way for removal in the data source itself has to be prepared by your own.
