### ISSUE TITLE
Sympa::Mailer::_safefork DIED Cannot allocate memory

### ISSUE THREAD

**Issue by iulistadmin** [sympa-community/sympa#1302]
We have been running into crashes with Sympa where the log entry states, "Sympa::Mailer::_safefork#255 DIED: Exiting because cannot create new process for list-name@list.indiana.edu.1638915844.18166: Cannot allocate memory at /usr/share/sympa/lib/Sympa/Mailer.pm line 255."

What is normal regarding wwsympa? We often have a few of the processes running and consuming a high amount of RAM. Here is a look at the current processes as seen in the 'top' command output.

1797 sympa 20 0 1348796 946584 4620 S 0.0 11.8 191:22.24 wwsympa.fcgi
1793 sympa 20 0 1321960 891972 4612 S 0.0 11.1 192:30.26 wwsympa.fcgi
1796 sympa 20 0 1268412 858660 4560 S 4.3 10.7 191:44.33 wwsympa.fcgi
1798 sympa 20 0 1279568 852936 4420 S 0.0 10.6 200:52.87 wwsympa.fcgi

Version
-------
6.2.64

Installation method
-------------------
RPMs in the repos from EPEL.

Expected behavior
-----------------
Sympa won't crash.

Actual behavior
---------------
Sympa dies. Starting the service is successful and memory usage has dropped due to long-running, high-memory usage processes having been killed.

Additional information
----------------------
OS is CentOS 7. The app server running Sympa is configured with 8 GB of RAM.

**Comment by racke** [comment]
Can you tell us how many lists and subscribers you have?

**Comment by iulistadmin** [comment]
@racke We have 10,111 active lists and 2215583 subscribers.

**Comment by racke** [comment]
I suppose that the number of lists is the main contributor to the memory usage due to caching. So IMHO 8GB is not sufficient for your amount of lists and subscribers.

**Comment by iulistadmin** [comment]
OK. We appreciate the input. We will schedule a time to add more memory.

**Comment by iulistadmin** [comment]
Sorry for the late follow-up. Adding more memory to the system resolved this issue.
