### ISSUE TITLE
Nested mails not being archived

### ISSUE THREAD

**Issue by bensmrs** [sympa-community/sympa#1304]
I have defined the lists `test` and `test-2`. `test-2` is subscribed to `test` (I know about `include_sympa_list`, but `test-2` may perform additional stuff on the mail, such as adding a header or running a hook). Mails sent to `test` are received where they need to be and are archived on `test`. However, when `test-2` receives the mail from `test`, it does not archive it.

Version
-------
6.2.40

Installation method
-------------------
deb

Expected behavior
-----------------
`test-2` should archive the mails it receives through `test`.

Actual behavior
---------------
`test-2` does not archive the mails it receives through `test`. It only archives the mails sent directly to it.

**Comment by racke** [comment]
How did you define the "nested" list?

**Comment by bensmrs** [comment]
Both lists have the same configuration:
```
clean_delay_queuemod 15

remind listmaster

archive
web_access private
mail_access owner

subject List to test the mail infrastructure

invite closed

reject_mail_from_automates_feature on

digest 5 20:56

status open

serial 4

subscribe closed

unsubscribe open

visibility conceal

del auth

review private

update
date_epoch 1612481471
email XXXXXXXXXX

creation
date_epoch 1567597840
date 04 sept. 2019 at 13:50:40
email XXXXXXXXXX

process_archive on

custom_subject test

shared_doc
d_read private
d_edit private

info conceal

send privateoreditorkey

add auth

owner
reception mail
email XXXXXXXXXX
gecos Benjamin Somers
profile privileged
visibility noconceal

pictures_feature on

reply_to_header
value list
apply respect
```
No fancy stuff, to easily reproduce the behavior.

**Comment by racke** [comment]
OK can you provide the relevant log entries for this action (increase log_level if needed) ?

**Comment by bensmrs** [comment]
I had read the log a bit too fast.
```
déc. 14 11:28:48 narayan sympa_msg[22981]: info Sympa::Spindle::ToArchive::_twist() Do not archive message with no-archive flag for list Sympa::List <test-2@XXXXXXXX>
```
Sympa sets the `X-no-archive` header to `yes` as soon as it processes a mail. I found a discussion from 2002 <https://listes.renater.fr/sympa/arc/sympa-fr/2002-09/msg00092.html> about that. Is it possible to prevent Sympa from adding this header (without patching it manually) or are nested lists such a bad practice that I have to find another solution?

**Comment by racke** [comment]
List inclusion would probably be better. 

You could write a plugin as solution for your problem, example: https://github.com/racke/sympa-plugin-distribution-notification/blob/master/lib/Sympa/Message/Plugin/DistributionNotification.pm.

**Comment by bensmrs** [comment]
Ok, thanks for your time. Is there any plan to allow Sympa not to define `X-no-archive` in the future in the list configuration or should I just close the issue because the use case is too specific?

**Comment by racke** [comment]
Seems quite specific for me. Maybe @ikedas can offer his opinion too.

**Comment by ikedas** [comment]
Hi.  Could you please check this parameter?

[ignore_x_no_archive_feature in sympa_config(5)](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#ignore_x_no_archive_header_feature):
> Sympa’s default behavior is to skip archiving of incoming messages that have an “X-no-archive:” header field set. This parameter allows one to change this behavior.

**Comment by bensmrs** [comment]
Hi!
I know about this parameter, but I actually wanted to continue to respect it. Preventing Sympa from automatically adding the header while continuing to respect it if set.

**Comment by ikedas** [comment]
> Hi! I know about this parameter, but I actually wanted to continue to respect it. Preventing Sympa from automatically adding the header while continuing to respect it if set.

You may also unset `X-no-archive` field by setting [`remove_outgoing_headers`](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#remove_outgoing_headers).

**Comment by bensmrs** [comment]
Awesome, that's exactly what I was looking for :)
Thanks for your help
