### ISSUE TITLE
WWSympa: Predefined fonts are hard to read comfortably

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#1305]
Version
-------

6.2 to current.

Installation method
-------------------

Source and almost all binary packages.

Expected behavior
-----------------

The text on the web interface should be easily read.

Actual behavior
---------------

Due to ugly rendering or inappropriate use of the fonts, it is often difficult to read text comfortably on a web interface.

Note that this is not the case for languages that specify their own fonts (`ja`, `ko`, `zh-CN` & `zh-TW`).

Additional information
----------------------

Below is a sample and comments by the reporter.

![image](https://user-images.githubusercontent.com/5743546/146316891-567cd29d-8377-48a1-811a-6ca048be622a.png)

  * The text in the body is difficult to read:
      - Digits are ornate and sometimes illegible.
      - The text is faint on devices with relatively low resolution.
      - In any case, this typeface seems suitable for headlines, but not for body text.
  * The monospace font is not properly selected:
      - Rendering is messy  (See the texts "`sympa.pl`" and so on).
      - Also, it doesn't have appropriate weight, i.e. it's too bold (In fact, the style sheet [specifies](https://github.com/sympa-community/sympa/blob/9ef3ebe5d0ce2c3715724ad250db84786366c3e6/default/web_tt2/css.tt2#L1948-L1950) that it should always be bold.).

**Comment by ikedas** [comment]
![image](https://user-images.githubusercontent.com/5743546/147400711-6a199226-5b39-4078-8014-4ba38d609197.png)

Replacement of the fonts by the PR above: Fonts for body text are changed (Headlines and menus aren't changed).

**Comment by racke** [comment]
Great, looks better! :+1:
