### ISSUE TITLE
Migration from MySQL to Postgres, error in boolean = int comparison

### ISSUE THREAD

**Issue by Ygreneb** [sympa-community/sympa#1317]
I upgraded from an old (6.1.something) Sympa installation to the current Debian package (6.2.60) and migrated from MySQL to PostgreSQL at the same time. I used pgloader for this. Everything works and seems fine, except for one small error I get in the logs (see copy below). I guess that pgloader turned a "bit" column into a "boolean" column, and comparing the read_stat column (now boolean) to an integer therefore fails. These are my questions:

1. What is the "good" way handling this? Should I re-migrate turning bit columns into int columns? Or does Sympa actually use boolean columns in Postgres and the SELECT command (see log below) can/should be fixed?
2. Can this happen with other columns, too?

Version: 6.2.60 on Debian 11 with PostgreSQL 13.5
Installation method: Debian apt packages
Migration: From MySQL/MariaDB to PostgreSQL with pgloader

Logfile error:
```
task_manager: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_purge_logs_table#445 > Sympa::Log::aggregate_stat#609 > Sympa::DatabaseDriver::PostgreSQL::do_prepared_query#105 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "SELECT date_stat FROM stat_table WHERE read_stat = 0 ORDER BY date_stat ASC": (42883) ERROR:  Operator does not exist: boolean = integer#012LINE 1: SELECT date_stat FROM stat_table WHERE read_stat = 0 ORDER B...#012
task_manager: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_purge_logs_table#445 > Sympa::Log::aggregate_stat#617 Unable to retrieve oldest non processed stat
```

pgloader command file:
```
LOAD DATABASE
  FROM mysql://sympa:*********@localhost/sympa
  INTO postgresql://sympa:*********localhost/sympa;
```

**Comment by ikedas** [comment]
Hi @Ygreneb ,

I'm not familiar with pgloader, but using it, `tinyint-to-boolean` rule is enabled by default (see the [documentation](https://pgloader.readthedocs.io/en/latest/ref/mysql.html) for details).  On Sympa, boolean type won't be used: integral types will be used instead.

Mapping between data types for MySQL and those for PostgreSQL is defined in [Sympa::DatabaseDriver::PostgreSQL](https://github.com/sympa-community/sympa/blob/6.2.60/src/lib/Sympa/DatabaseDriver/PostgreSQL.pm#L633-L652).  You may not always have to follow this rule strictly (especially, the column size is fine as long as it is _not smaller than_ the original size).  But as general rules, integer should be converted to integer, and textual types (`varchar(*)`, `text` or `enum(*)`) to `varchar(*)` or `text`.

Additionally, you'd be better to run `sympa.pl --health_check` after the migration. This will do some adjustment of the data types.

**Comment by Ygreneb** [comment]
Hey @ikedas ,

thank you for your valuable hints. A `sympa --health_check` failed and the logs showed, that it was unable to change the data type. Trying to manually change it failed, too, as it is not possible to cast `boolean` to `smallint`.

So I rewrote my pgloader command file based on the data type mapping you have linked to. I reimported the MySQL data and the `sympa --health_check` afterwards worked and changed column types as needed. So far (24h+) there are no errors in the log. So thank you very much for your help!

Only one question remains: How to map enums (if Sympa uses any enums in MySQL)? By default pgloader creates an enum type for PostgreSQL based on table and column name (see the [documentation](https://pgloader.readthedocs.io/en/latest/ref/mysql.html#default-mysql-casting-rules) you have already linked to, at the very bottom). Could this cause in any problems?

**Comment by ikedas** [comment]
> thank you for your valuable hints. A `sympa --health_check` failed and the logs showed, that it was unable to change the data type. Trying to manually change it failed, too, as it is not possible to cast `boolean` to `smallint`.
> 
> So I rewrote my pgloader command file based on the data type mapping you have linked to. I reimported the MySQL data and the `sympa --health_check` afterwards worked and changed column types as needed. So far (24h+) there are no errors in the log. So thank you very much for your help!

Good!

> Only one question remains: How to map enums (if Sympa uses any enums in MySQL)? By default pgloader creates an enum type for PostgreSQL based on table and column name (see the [documentation](https://pgloader.readthedocs.io/en/latest/ref/mysql.html#default-mysql-casting-rules) you have already linked to, at the very bottom). Could this cause in any problems?

enum type onMySQL should be mapped to varchar on PostgreSQL.  For example: If a column has the type `enum('privileged','normal')` on MySQL, it should have the type such as `varchar(15)` on PostgreSQL and the value of the column in each row is either of string  `'privileged'` or `'normal'`.

**Comment by Ygreneb** [comment]
The data was successfully migrated using the suggested mapping.
