### ISSUE TITLE
include_list deleted during 6.1.23 > 6.2.64 upgrade

### ISSUE THREAD

**Issue by tmclaren** [sympa-community/sympa#1321]
Description
-------------
I upgraded Sympa 6.1.23 to a new 6.2.64 server and the include_list setting was deleted from all of the lists configs in 6.2.64.

I moved the list_data directory to the new server, successfully migrated the mysql db and ran sympa.pl --upgrade.   Everything appeared to go smoothly except for the include_list setting for all lists that used it.    The syntax for this setting had changed in 6.2.x and the old setting was not translated to the new 6.2.x syntax during the upgrade.  

6.1.23
include_list CCSP

6.2.64
include_sympa_list
listname ccsp
name ccsp

Installation method
-------------------
centOS 7, mysql/mariadb 12, postfix

Expected behavior
-----------------
I expected this setting to persist and get translated to the new syntax.

Actual behavior
---------------
The setting, include_list,  was deleted from all lists that had it defined.

**Comment by ikedas** [comment]
@tmclaren , if possible, please apply [this patch](https://github.com/sympa-community/sympa/commit/c234157.patch) and retry upgrading from previous version (6.1.23).

**Comment by ikedas** [comment]
@tmclaren , additional info:

previous versions of list config files are kept as `confg.0`, `config.1`, ... and so on.  _If you cannot restore backup data of previous version of Sympa_ (6.1.23), you may follow the steps below to retry upgrading:
1. Stop the Sympa services.
2. Rename the newest `config.XXX` of each list to `config`.
3. Edit `data_structure.version` to change the current version (6.2.64) to the previous one (6.1.23).
4. Run `sympa.pl --upgrade`.
5. Restart the Sympa services.
