### ISSUE TITLE
Sympa 6.2.67b.3 build failure

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1326]
Version
-------

Sympa 6.2.67b.3 from https://github.com/sympa-community/sympa/releases/download/6.2.67b.3/sympa-6.2.67b.3.tar.gz

Installation method
-------------------

My own rpm, derived from official RHEL 7 rpm

Expected behavior
-----------------

6.2.67b.3 should build

Actual behavior
---------------

"make check" fails with:

```
Test Summary Report
-------------------
t/Request_Handler_add+del.t (Wstat: 512 Tests: 1 Failed: 0)
  Non-zero exit status: 2
  Parse errors: No plan found in TAP output
Files=24, Tests=1205, 58 wallclock secs ( 0.19 usr  0.02 sys + 48.61 cusr  5.04 csys = 53.86 CPU)
Result: FAIL
Failed 1/24 test programs. 0/1205 subtests failed.
```

It is possible that this is a stupid error on my part and I am just missing a dependency. However I haven't run into this sort of build failure before. Maybe the following is significant?

https://github.com/sympa-community/sympa/pull/1299

That is the only mention of "make check" on https://github.com/sympa-community/sympa/blob/6.2.67b.3/NEWS.md

**Comment by ikedas** [comment]
@dpc22, please try running:
```bash
cd (top of source tree)
./configure (options...)
make
PERL5LIB=src/lib:${PERL5LIB} /path/to/perl t/Request_Handler_add+del.t
```

**Comment by dpc22** [comment]
```
lists-2[dpc22:sympa-6.2.67b.3]$ PERL5LIB=src/lib:${PERL5LIB} /usr/bin/perl t/Request_Handler_add+del.t
ok 1 - add subscriber: List not open
Cannot create : No such file or directory at src/lib/Sympa/Spool/Outgoing.pm line 88.
# Tests were run but no plan was declared and done_testing() was not seen.
```

**Comment by ikedas** [comment]
@dpc22,
Could you please change a file:
```diff
diff --git a/t/Request_Handler_add+del.t b/t/Request_Handler_add+del.t
index 7b0231e..feaa22a 100644
--- a/t/Request_Handler_add+del.t
+++ b/t/Request_Handler_add+del.t
@@ -86,7 +86,7 @@ open my $fh, '>', $Conf::Conf{etc} . '/data_sources/include_fi
 print $fh "include_file $tempdir/source\n";
 close $fh;

-Sympa::Log->instance->{level} = -1;
+#Sympa::Log->instance->{level} = -1;
 do {
     no warnings 'redefine';
     local (*Sympa::send_notify_to_listmaster) = sub {1};
```
and then retry?

**Comment by dpc22** [comment]
```
lists-2[dpc22:sympa-6.2.67b.3]$ PERL5LIB=src/lib:${PERL5LIB} /usr/bin/perl t/Request_Handler_add+del.t 2> ~/tmp/test.out
ok 1 - add subscriber: List not open
```
Plus a lot of output to stderr which may or may not be relevant, attached below:

[stderr.txt](https://github.com/sympa-community/sympa/files/7888108/stderr.txt)

**Comment by ikedas** [comment]
@dpc22, please check [this patch](https://github.com/sympa-community/sympa/commit/c732ce9.patch).  It'll be included in the next stable (6.2.68).

**Comment by dpc22** [comment]
Okay, that seems to have fixed the build problem. Thanks,

Are there any other showstopper bugs in 6.2.67b.3 which  have been fixed in GIT?

I plan to kick the tires for  day or two in expectation of 6.2.68.

**Comment by ikedas** [comment]
Thanks @dpc22! Please check [Milestone 6.2.68](https://github.com/sympa-community/sympa/milestone/19) about changes/fixes before 6.2.68.

---
Other than that, it would be greatly appreciated if you could confirm the operation with CAS: Code for this feature has been heavily refactored in #1255, and I would like as many people as possible to verify it.

**Comment by dpc22** [comment]
Underway.

Immediate concern: ```sympa --close_list``` and ```sympa -purge_list``` seem to have disappeared as part of the rewrite. 

I have also run into some kind of issue with the CAS stuff, but I will open another ticket once I work out what is going on there

**Comment by dpc22** [comment]
Okay, so the CAS problem turned out to be my own fault: it just redirected me back to a page that I didn't expect.

I will open a ticket about a separate problem that I have found, and I think that it will be worth my time to work through and test every option in turn to see if I pick up anything else.
