### ISSUE TITLE
Add  owner with non-default options, e.g. "privileged" profile, not working in Sympa 6.2.67b.3 

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1329]
Version
-------

6.2.67b.3 

Installation method
-------------------

My own rpm.

Expected behavior
-----------------

If I add a new owner to a list with "privileged owner" set, they should be added as a privileged owner.

Actual behavior
---------------

The new owner is added as a normal owner, which I then have to go in and change via the edit owner dialogue.

**Comment by dpc22** [comment]
The two checkboxes on the "Add moderators" dialogue seem to have the same problem:

no notifications
concealed from list menu

**Comment by dpc22** [comment]
I infer that this is in some way related to:

default_owner_options		owner				read
default_editor_options		owner				read

which are new in 6.2.67

**Comment by ikedas** [comment]
Owner addition specifying their attributes has not yet implemented.  It will be postponed to the next stable.

**Comment by dpc22** [comment]
Okay, I think that this will confuse my users unless the various checkboxes (which currently do not function) are removed.

I can always wait until 6.2.70

**Comment by iulistadmin** [comment]
Another vote to fix this bug. We have had this issue called to our attention. We are running 6.2.68 on CentOS 7.

**Comment by ikedas** [comment]
@dpc22, @iulistadmin (#1329) and @renesepp (#1361), could you please apply [this patch](https://github.com/sympa-community/sympa/commit/73cc995.patch) to check if the problem will be solved? Thank you.

**Comment by dpc22** [comment]
Will do, although it will probably be a couple of weeks now because of Easter and other leave.

Thanks for fixing this. It was stopping me from upgrading to 6.2.68.

**Comment by iulistadmin** [comment]
Thanks @ikedas! We don't seem to have wwsympa.fcgi.in. In our installation, there is /usr/libexec/sympa/wwsympa.fcgi. It looks like this is the file to modify, but when I applied the patch, it broke the web UI.

**Comment by ikedas** [comment]
@iulistadmin , is the permission (file mode) of wwsympa.fcgi correct?  If patch is applied, sometimes execution bits are cleared.  The mode should be 755 (rwxr-xr-x).

**Comment by iulistadmin** [comment]
@ikedas, that was the problem. I should have been more careful and checked the permissions on that file. Having the correct permissions set, the patches applied, it is now setting the privileged owners correctly. So, this has resolved the issue for us. Thank you!

**Comment by ikedas** [comment]
@iulistadmin , thank you for confirming!  The patch will be merged soon.
@dpc22, this issue will be closed soon, but if you noticed anything, please feel free to comment on this page.

**Comment by dpc22** [comment]
A bit late, but I can confirm that this seems to have fixed the problem for me. Thanks.

**Comment by dpc22** [comment]
Oh, one small thing.  "default_owner_options"  and "default_editor_options" are grouped under "Sending/receiving setup":

    default_owner_options => {
        context         => [qw(list domain site)],
        order           => 20.06_02,
        group           => 'sending',
[...]
    default_editor_options => {
        context         => [qw(list domain site)],
        order           => 20.06_03,
        group           => 'sending',

I would have expected these two options  to appear under "Privileges" or maybe "Miscellaneous". It doesn't really seem to be a "sending" option.

**Comment by ikedas** [comment]
Makes sense.  It'll be fixed.

**Comment by ilf** [comment]
Can we get a new release with this fix included?
