### ISSUE TITLE
HELP - Error No list in Log 

### ISSUE THREAD

**Issue by LANFDETROY** [sympa-community/sympa#1333]
Error No list in Log

Version
-------
Sympa 6.2.66
Debian 11

Installation method
-------------------
source package

Expected behavior
-----------------
I updated the sympa server from 6.1 to 6.2.54 to 6.2.66 and just saw errors in the logs but I
don't understand what it is.
Can anyone help me?

Jan 20 14:04:26 listes task_manager[1048]: notice Sympa::Spool::store() Sympa::Task <date=1642683866;label=INIT;model=sync_include;context=sympa@listes.toto.fr> is stored into Sympa::Spool::Task as <1642683866.INIT.sync_include.sympa@listes.toto.fr>
Jan 20 14:04:26 listes task_manager[1048]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1642683866;label=INIT;model=sync_include;context=*>
Jan 20 14:04:26 listes task_manager[1048]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 No list
Jan 20 14:04:26 listes task_manager[1048]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1642683866;label=INIT;model=sync_include;context=*> is now useless. Removing it

I looked in sympa's task directory (/usr/local/var/spool/sympa/task), and there are no tasks of type xxxxx.INIT.sync_include.sympa@listes.toto.fr
is this normal? is the error caused by this?

**Comment by ikedas** [comment]
@LANFDETROY , please shoiw us these things:
- The setting (list config and/or files in data_sources directory) of the list which have configuration for inclusion (also, please check if the setting has been changed or removed during upgrading).
- The actual steps you can reproduce the problem ("opened 'xxx' page, clicked 'xxx' button, ..." and so on).
- The log _from when_ you started the operation _to when_ the problem occurred.

**Comment by LANFDETROY** [comment]
Hello,

No list has been modified since the sympa version upgrade.

We have 236 listings, most with listing inclusions or Oracle queries.

This does not prevent the operation of the list server. This message appears every 2 minutes in the logs.

Log : 

Jan 21 08:07:02 listes sympa/health_check[6150]: info main:: Configuration file read, default log level 0
Jan 21 08:07:02 listes sympa_msg[6156]: info main::_load() Configuration file read, default log level 0
Jan 21 08:07:02 listes sympa_msg[6156]: notice Sympa::Process::daemonize() Starting sympa/msg daemon, PID 6159
Jan 21 08:07:03 listes sympa_msg[6159]: notice main:: Sympa/msg 6.2.66 Started
Jan 21 08:07:03 listes bulk[6163]: info main:: Configuration file read, default log level 0
Jan 21 08:07:03 listes bulk[6163]: notice Sympa::Process::daemonize() Starting bulk daemon, PID 6166
Jan 21 08:07:03 listes bulk[6166]: notice main:: Bulk 6.2.66 Started
Jan 21 08:07:03 listes archived[6173]: notice main:: Archived 6.2.66 Started
Jan 21 08:07:04 listes bounced[6180]: notice main:: Bounced 6.2.66 Started
Jan 21 08:07:04 listes task_manager[6184]: info main:: Configuration file read, default log level 0
Jan 21 08:07:04 listes task_manager[6184]: notice Sympa::Process::daemonize() Starting task_manager daemon, PID 6187
Jan 21 08:07:04 listes task_manager[6184]: notice main:: Task_Manager 6.2.66 Started
Jan 21 08:07:07 listes task_manager[6184]: notice Sympa::Spool::store() Sympa::Task <date=1642748824;label=INIT;model=sync_include;context=sympa@listes.toto.fr> is stored into Sympa::Spool::Task as <1642748824.INIT.sync_include.sympa@listes.toto.fr>
Jan 21 08:07:07 listes task_manager[6184]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1642748824;label=INIT;model=sync_include;context=*>
Jan 21 08:07:07 listes task_manager[6184]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 No list
Jan 21 08:07:07 listes task_manager[6184]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1642748824;label=INIT;model=sync_include;context=*> is now useless. Removing it
Jan 21 08:09:07 listes task_manager[6184]: notice Sympa::Spool::store() Sympa::Task <date=1642748947;label=INIT;model=sync_include;context=sympa@listes.toto.fr> is stored into Sympa::Spool::Task as <1642748947.INIT.sync_include.sympa@listes.toto.fr>
Jan 21 08:09:07 listes task_manager[6184]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1642748947;label=INIT;model=sync_include;context=*>
Jan 21 08:09:07 listes task_manager[6184]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 No list
Jan 21 08:09:07 listes task_manager[6184]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1642748947;label=INIT;model=sync_include;context=*> is now useless. Removing it
Jan 21 08:11:08 listes task_manager[6184]: notice Sympa::Spool::store() Sympa::Task <date=1642749067;label=INIT;model=sync_include;context=sympa@listes.toto.fr> is stored into Sympa::Spool::Task as <1642749067.INIT.sync_include.sympa@listes.toto.fr>
Jan 21 08:11:08 listes task_manager[6184]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1642749067;label=INIT;model=sync_include;context=*>
Jan 21 08:11:08 listes task_manager[6184]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 No list
Jan 21 08:11:08 listes task_manager[6184]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1642749067;label=INIT;model=sync_include;context=*> is now useless. Removing it

What does the "No list" value that is returned correspond to?

Is it related to the Sympa list or another one?

**Comment by ikedas** [comment]
@LANFDETROY , please show us config of at least one list that contains inclusion settings.

And, please check if it has _really_ not been modified: Earlier version of `config` files are saved as `config.0`, `config.1`, `config.2` and so on.

**Comment by LANFDETROY** [comment]
Hello, 

extract from a list with inclusion :

owner
reception mail
email christophe.xxx@toto.fr
profile privileged
visibility noconceal

web_archive
max_month 3
access listmaster

subject Liste des Personnels INSA-CVL

visibility insa_personnels

topics computing

send insa_personnels

digest 5 20:56

available_user_options
reception mail

custom_subject personnels

max_size 20485760

reject_mail_from_automates_feature on

rfc2369_header_fields archive,help,owner,post,subscribe,unsubscribe

info open

subscribe intranet

add auth

unsubscribe closed

del auth

invite closed

remind listmaster

review insa_personnels

shared_doc
d_read private
d_edit owner

archive
mail_access closed
access owner
period month
web_access closed

owner_include
profile normal
visibility noconceal
source proprietaires
reception mail

include_sympa_list
name personnels-bourges
listname personnels-bourges

include_sympa_list
listname personnels-blois
name personnels-blois

clean_delay_queuemod 15

creation
date_epoch 1370587470
date 07 jun 13 at 08:44:30
email florent.xxx@toto.fr

update
date_epoch 1642752686
email florent.xxx@toto.fr

status open

serial 53

**Comment by LANFDETROY** [comment]
I compared the config file to config.0 config.1 but no real difference.

**Comment by LANFDETROY** [comment]
What should the header of the /etc/mail/sympa_aliases file look like?

On my side I have:
sympa: "| /usr/local/libexec/queue sympa@listes2.toto.fr"
listmaster: "| /usr/local/libexec/queue listmaster@listes2.toto.fr"
bounce+*: "| /usr/local/libexec/bouncequeue sympa@listes2.toto.fr"
abuse-feedback-report: "| /usr/local/libexec/bouncequeue sympa@listes2.toto.fr"
sympa-request: postmaster@toto.fr
sympa-owner: postmaster@toto.fr

**Comment by racke** [comment]
@LANFDETROY which email server (MTA) do you use?

**Comment by LANFDETROY** [comment]
I found the error, there was no subscriber to the sympa@toto.fr list
I have no more errors now.
