### ISSUE TITLE
ADD old alias moved list

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1334]
Hello,
I'm using sympa 6.2.40.
I had move a list from a robot to an other.
I want temporary add alternative (old entries) entries for these lists .

**Comment by khaoula-abaidi** [comment]
I had used : 
/usr/lib/sympa/bin/alias_manager.pl --add test_double_alias  oldROBOT
but i had the error that list is'nt into the oldROBOT

**Comment by ikedas** [comment]
@khaoula-abaidi , how did you configure Sympa and MTA to integrate both of them? Please show us actual settings.

If you have no idea about what is "configuration to integrate both of them", please refer to the "[Configure mail server](https://sympa-community.github.io/manual/install/configure-mail-server.html)" chapter in the manual.

**Comment by khaoula-abaidi** [comment]
Hello,
Thank you for your response.
Using the manual,
I had manually old aliase for the list to the new ones into sympa_transport file : 
test.khaoula@oldROBOT sympa:test.khaoula@newROBOT
test.khaoula-request@oldROBOT  sympa:test.khaoula-request@newROBOT
Then, update databases for transport map and virtual alias map
postmap hash:/etc/sympa/transport.sympa.sympa
postmap hash:/etc/sympa/virtual.sympa


It works.
I can use old alias as a sender , the new alias list receive the mail.

**Comment by ikedas** [comment]
@khaoula-abaidi , thanks for sharing your experiences!
