### ISSUE TITLE
A way to alter the "To:" header field

### ISSUE THREAD

**Issue by RENR0b1** [sympa-community/sympa#1341]
Hello,

I'm looking for a simple way to alter the "To:" header field to display the subscriber's email address instead of the list address. 

I found this post from 2016 at [https://listes.renater.fr/sympa/arc/sympa-users/2016-02/msg00037.html](https://listes.renater.fr/sympa/arc/sympa-users/2016-02/msg00037.html)

Creating a hook is the only way ? Is there a possible future improvement?

Thank you.

Best regards,

Robin

Version
-------
6.2.58 / 6.2.64

Installation method
-------------------
rpm

**Comment by ikedas** [comment]
Please see #207.
