### ISSUE TITLE
URIs are being split by linewrap in templated emails

### ISSUE THREAD

**Issue by mbattersby** [sympa-community/sympa#1345]
Text::LineFold (at least the version shipping with RedHat 8 in package perl-Unicode-LineBreak-2017.004-6.el8.x86_64) is sensitive to the order of the Prep arguments, and Prep => 'NONBREAKURI' must be last to avoid breaking URIs.

This is causing Sympa to wrap (at least mailto) URIs in outgoing templated emails so that "click to confirm" doesn't work. E.g.,

```
mailto:sympa@lists-dev.unimelb.edu.au?subject=CONFIRM
%20c66653f92d826c5348fad9f06f9a87c3
```

Version
-------
Sympa 6.2.66
perl-Unicode-LineBreak-2017.004-6.el8.x86_64

Installation method
-------------------
From source.

Expected behavior
-----------------
Should not wrap mailto URIs in outgoing emails.

Actual behavior
---------------
URIs are broken before %20 if the line length exceeds 78 characters.

Steps to reproduce
------------------
Create a list with a long name with sending permission requiring moderator approval. Post to the list. Look at the email sent to the moderators. 

Additional information
----------------------
This patch fixes it for me:

```
--- src/lib/Sympa/Tools/Text.pm.orig    2022-02-11 13:56:52.699305810 +1100
+++ src/lib/Sympa/Tools/Text.pm 2022-02-11 13:57:01.315356999 +1100
@@ -177,8 +177,8 @@
 
     my $linefold = Text::LineFold->new(
         Language   => Sympa::Language->instance->get_lang,
+        Prep       => [$email_like_re, sub { shift; @_ }],
         Prep       => 'NONBREAKURI',
-        prep       => [$email_like_re, sub { shift; @_ }],
         ColumnsMax => $cols,
         Format     => sub {
             shift;
```

**Comment by ikedas** [comment]
It's a bug in the earlier version of `Unicode-LineBreak` (See the [fix](https://github.com/hatukanezumi/Unicode-LineBreak/commit/dfdfa454e439107f5e5bbfadc945d62d56edc749)).  Please update that module.

**Comment by ikedas** [comment]
Duplicate of #709.
