### ISSUE TITLE
Keep easy access to (un)subscribe links in owner panel

### ISSUE THREAD

**Issue by SansPseudoFix** [sympa-community/sympa#1347]
Expected Behavior
-----------------

Owner should always have easy access to (un)subscribe links. This way, they can easily share them.

Current Behavior
----------------

At first, links are easily available on list home. **But**, if you modify this page, you lost (un)subscribe links. This is confusing for users who can no longer easily find these links.

Possible Solution
-----------------

Display links in separate section above modified list home page?

Context
-------

One user change list home page and asked for subscribe link.

**Comment by ikedas** [comment]
Hi @SansPseudoFix . Do you have any specific ideas on how to make the link don't disappear even when the owner modified the home page?

**Comment by SansPseudoFix** [comment]
I was thinking of something like:
![ksnip_20220214-111616](https://user-images.githubusercontent.com/6507951/153845029-bf7da0cc-90a2-432f-a3d7-8e6cc86cf6bf.png)
On "List Home" page. Just keep links visible and separated with an horizontal line.

**Comment by ikedas** [comment]
I feel that the user may modify the home page further to add those links.  You could tell them how to do that, I suppose.

**Comment by ikedas** [comment]
Don't worry.  @SansPseudoFix & @ldidry , thanks for shareing your experiences!
