### ISSUE TITLE
two lists in reciepients - delivered only alphabetically first

### ISSUE THREAD

**Issue by stepansantalov** [sympa-community/sympa#135]
Recently i discovered that if one sends message to two maillists, resided on one sympa server 
simultaneously, only one, the alphabetically first is delivered and the second one silently disappears (no track in sympa logs). Is it normal behaviour, misconfiguration of sympa, or misconfiguraton between sympa and MTA?
Am i alone who run into such an issue?

**Comment by ikedas** [comment]
@stepansantalov, could you please show the version and configuration of MTA?

**Comment by stepansantalov** [comment]
Sympa version is 6.1.24~dfsg-1 as package in ubuntu xenial.

The part for sympa in MTA (postfix):

relay_domains = pgsql:sympadomains
transport_maps =  pgsql:sympalist
                  pgsql:sympabounce
sympadomains_user = sympa
sympadomains_password = xxxxx
sympadomains_dbname = sympa
sympadomains_hosts = 192.168.2.2
sympadomains_query = select distinct 1 from list_table where robot_list='%s';

sympalist_user = sympa
sympalist_password = xxxxx
sympalist_dbname = sympa
sympalist_hosts = 192.168.2.2
sympalist_query = select distinct 'sympa' from list_table where (
                     'sympa'                           = '%u' or
                     'listmaster'                      = '%u' or
                     name_list                         = '%u' or
                     concat(name_list, '-request')     = '%u' or
                     concat(name_list, '-editor')      = '%u' or
                     concat(name_list, '-subscribe')   = '%u' or
                     concat(name_list, '-unsubscribe') = '%u') and robot_list='%d';

sympabounce_user = sympa
sympabounce_password = xxxxx
sympabounce_dbname = sympa
sympabounce_hosts = 192.168.2.2
sympabounce_query = select distinct 'sympabounce' from list_table where (concat(name_list, '-owner') = '%u') and robot_list='%d';

**Comment by ikedas** [comment]
@stepansantalov, and what did you added on master.cf?

**Comment by stepansantalov** [comment]
sympa is on the other server, so postfix goes there by ssh.

sympa     unix  -       n       n       -       -       pipe flags=R user=vmail argv=/usr/bin/ssh sympa@192.168.27.15 /usr/lib/sympa/bin/queue ${recipient}
sympabounce unix -      n       n       -       -       pipe flags=R user=vmail argv=/usr/bin/ssh sympa@192.168.27.15 /usr/lib/sympa/bin/bouncequeue ${recipient}

**Comment by ikedas** [comment]
> sympa is on the other server, so postfix goes there by ssh.

Interesting. I'll borrow this magic someday.

> sympa     unix  -       n       n       -       -       pipe flags=R user=vmail argv=/usr/bin/ssh sympa@192.168.27.15 /usr/lib/sympa/bin/queue ${recipient}
> sympabounce unix -      n       n       -       -       pipe flags=R user=vmail argv=/usr/bin/ssh sympa@192.168.27.15 /usr/lib/sympa/bin/bouncequeue ${recipient}

``${recipient}`` is expanded to all recipients, then ``queue`` will take only the first one. Can you try adding these lines to `main.cf`?
```
sympa_destination_recipient_limit = 1
sympabounce_destination_recipient_limit = 1
```
See also [pipe(8)](http://www.postfix.org/pipe.8.html).

**Comment by ikedas** [comment]
@stepansantalov, was your problem solved?

**Comment by ikedas** [comment]
No further reports.  Closed.

**Comment by ptashraf** [comment]
Hello,
Kindly not ignore this message
I have successfully installed and configured Sympa 6.2.16 in Debian machine. Iam using postfix as MTA
The problem is that I can send email from the web interface to the lists and it is ok but when I sent a mail from another client like outlook to the list ,it got failed with  error. “
Remote Server returned '<lists-1.test.TLD #5.1.1 smtp;550 5.1.1 <ashraf-test@lists-1.test.TLD>: Recipient address rejected: User unknown in local recipient table>'
Seems Sympa and postfix integration is not properly. Kindly help me 
Thanks Ashraf

**Comment by ptashraf** [comment]
Sure.Thanks
