### ISSUE TITLE
timeout value not saved in ldap connexion

### ISSUE THREAD

**Issue by goudal-emmk** [sympa-community/sympa#1350]
Version
-------

[6.2.41b.2]
Expected behavior
-----------------

When configuring ldap data source it is possible to set a timeout. On the web interface the value is 30. The value should be used.

Actual behavior
---------------
Looking at the code in /home/sympa/bin/Sympa/DatabaseDriver/LDAP.pm in the _connect method the code is
   my $connection = Net::LDAP->new(
        $self->{_hosts},
        timeout => ($self->{'timeout'} || 3),

But when dumping the object, the timeout attribute is not set to 30 as shown in the webinterface :
 bless( {
                 '_id' => 'bind_dn=supressed;ca_file=/etc/ssl/certs/ca_chain_tcs.pem;ca_verify=required;host=ldaps://ldap.ipb.fr;ssl_ciphers=ALL;ssl_version=tlsv1_2;use_tls=ldaps',
                 'ssl_version' => 'tlsv1_2',
                 '_error_string' => '',
                 'use_tls' => 'ldaps',
                 '_error_code' => 0,
                 'bind_password' => 'supressed',
                 'host' => 'ldaps://ldap.ipb.fr',
                 '_hosts' => [
                               'ldaps://ldap.ipb.fr'
                             ],
                 'ssl_ciphers' => 'ALL',
                 'ca_file' => '/etc/ssl/certs/ca_chain_tcs.pem',
                 'ca_verify' => 'required',
                 'bind_dn' => 'supressed
               }, 'Sympa::DatabaseDriver::LDAP' );

Steps to reproduce
----------------

Create an ldap source, look at the value in the ldap object...

**Comment by ikedas** [comment]
@goudal-emmk , please show us what you have done:
* The configuration of Sympa you included the "timeout"
* Steps to reproduce the problem (from beginnig to when the problem occurred)

**Comment by goudal-emmk** [comment]
To show the configuration as it is web interface, I can give you a screenshot, but I can't include an image here. So how do I do ?
Steps to reproduce : as I said, simply add an ldap source, keep the default value of timeout.  I can't say more.

**Comment by ikedas** [comment]
What is "ldap source"? There are at least (AFAIK) four things are possible:
* Inclusion d'une requête LDAP (include_ldap_query)
* Inclusion d'une requête LDAP (2 passes) (include_ldap_2level_query)
* Extraction d'attributs utilisateurs par requête LDAP (include_ldap_ca)
* Extraction d'attributs utilisateurs par requête LDAP (2 passes) (include_ldap_2level_ca)

**Comment by goudal-emmk** [comment]
include_ldap_query

**Comment by ikedas** [comment]
@goudal-emmk , the version of your Sympa is slightly old. Please use the recent version.  Currently the latest stable version is 6.2.68.

**Comment by goudal-emmk** [comment]
Well. Maybe you should understand that upgrading sympa is not an easy task, and that when you have an instance in production you can't do that without weeks of work....  without even knowing if the bug is corrected...

**Comment by racke** [comment]
Upgrading Sympa is usually a smooth process. Of course you need to go to check the list of changes etc. and do a test upgrade.

Weeks of work can certainly blamed only to your infrastructure / environment 😇, but you got a point about the missing information whether the bug has been fixed. @ikedas ?

**Comment by goudal-emmk** [comment]
Smooth process... well... that's a theorical point of view.  First you've got to clone your installation, because it can't be stopped, than to test you have setup all the mail environnement around. Here we have 6 robots, and it's not as smooth as you think. Than you can't test with existing list, but you need to check if it works for distribution, so... difficult without sending test mails to users... than we have to check all the scenarii, and a bit of code because some mutli-domain feature are not present (on cas authentication on one domain and several robots it's not easy to identify users as it may send mail as toto@domain1 but is identified ass toto@maindomain on the web interfaces).
Than another thing is that in France university don't have enough human resources so we can have somebody dedicated just to sympa, so when you have to deal with tens of product, with different languages...

So yes maybe it should be smooth, in real life it is not.

**Comment by ikedas** [comment]
* The code for `include_ldap_query` setting had heavily been rewritten, improved and corrected in these years (correction includes `timeout` feature). Thats why we recommend the stable version as recent as possible.
* On the other hand, there are no reasons to use slightly older beta version: 6.2.41b2 is a _beta release_ in _four years_ ago. None can expect it will work properly.
* You are recommended to keep your systems up-to-date to keep it running securely. So, anyway at some point, you will have to update Sympa to the latest stable.

In fact, I have often experienced updates of Sympa running in several Japanese academic and/or public organizations. French universities cannot be the only exception.

Please read documentation "**[Upgrading Sympa](https://sympa-community.github.io/manual/upgrade.html)**".  If you have any further questions, please submit a new issue (question).

**Comment by racke** [comment]
Thanks for the clarification! I think we can close the issue now, as this bug is fixed in recent releases. I also did a bunch of migrations/upgrades of Sympa and my experience with that is a really good one.

**Comment by goudal-emmk** [comment]
Well yes it's quite old and not a good choice  but I can't change the past of our organisation.

Maybe in Japan they have enough engineers. Here we have been 2 engineers for a 8000 users, 6 schools for years, having to deal with setting up a fusion of the 6 schools and all the services that go with an organisation.  France is not japan.

**Comment by ikedas** [comment]
For example, almost all Debian users experience updates of Sympa through 6.2.16, 6.2.40 and 6.2.60. The actual update procedure is just what the documentation above says. However, there have been very few reports of problems as a result of the updates.

Anyway, please read [the documentation](https://sympa-community.github.io/manual/upgrade.html) before looking for reasons why you won't be able to pull it off.
