### ISSUE TITLE
Customize template create list

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1351]
Hello,
I'm using SYMPA 6.2.40.
I want to personnalize the  template creation lists per persons. 
For example administrators HR : public , newletter and private  lists 
and for other Users public lists .
I had create a custom filters. 
I used it for scenari validation list ( for administrators HR , validation list is automatic) but for others it needs listmaster validation
But i can't understand how to do it to customize template for creation list.
Thanks for your help
Yours faithfully,

**Comment by khaoula-abaidi** [comment]
Right now 
- i have used custom_actions but how can i get the value(true/false) parameter from my search_filters  to use it ? 
- and how to use it into list creation template ? 

If there is an other way, i have no problem.

Thank you for your help
 Yours faithfully,

**Comment by ikedas** [comment]
Currently, Sympa cannot restrict usage of create list templates.

Instead (I've not confirmed), displayed templates may be controlled by modification on web template, for example:
``` diff
--- a/default/web_tt2/create_list_request.tt2
+++ b/default/web_tt2/create_list_request.tt2
@@ -11,6 +11,15 @@
     <label for="list_type">[%|loc%]List type:[%END%]</label>
     <ul id="list_type">
-    [%~ FOREACH tpl_info = list_list_tpl %]
+    [% IF is_owner %]
+        [% tpls = list_list_tpl %]
+    [% ELSE %]
+        [% FOREACH tpl_info = list_list_tpl %]
+            [% IF tpl_info.key == 'public' %]
+                [% tpls.push(tpl_info) %]
+            [% END %]
+        [% END %]
+    [% END %]
+    [%~ FOREACH tpl_info = tpls %]
       <li>
```

**Comment by khaoula-abaidi** [comment]
> Currently, Sympa cannot restrict usage of create list templates.
> 
> Instead (I've not confirmed), displayed templates may be controlled by modification on web template, for example:
> 
> ```diff
> --- a/default/web_tt2/create_list_request.tt2
> +++ b/default/web_tt2/create_list_request.tt2
> @@ -11,6 +11,15 @@
>      <label for="list_type">[%|loc%]List type:[%END%]</label>
>      <ul id="list_type">
> -    [%~ FOREACH tpl_info = list_list_tpl %]
> +    [% IF is_owner %]
> +        [% tpls = list_list_tpl %]
> +    [% ELSE %]
> +        [% FOREACH tpl_info = list_list_tpl %]
> +            [% IF tpl_info.key == 'public' %]
> +                [% tpls.push(tpl_info) %]
> +            [% END %]
> +        [% END %]
> +    [% END %]
> +    [%~ FOREACH tpl_info = tpls %]
>        <li>
> ```

Thank you for your response, 
for me i want to customize the web template per type of user ( student, staff , adminstrator ...). 
How can i have this information to customize the template ?

**Comment by ikedas** [comment]
I have no idea.  Currently, I think, Sympa cannot restrict usage of create list templates according to the "type" of users.
