### ISSUE TITLE
sympa_msg died, pid file remains.

### ISSUE THREAD

**Issue by pacija** [sympa-community/sympa#1353]
Hi,

this morning I noticed my sympa doesn't send list emails. It appears messages were being delivered to sympa, but id did not send them to list members. Checking `service sympa status` showed the following. Restarting with `service sympa restart` sent all the emails that were delivered to it in the meantime.
```
me@mybox:~ % sudo service sympa status
Status of Sympa subsystem: 
Status file for subsystem found.
sympa_msg died, pid file remains.
bulk (pid(s) 13364) is active...
archived (pid(s) 13369) is active...
bounced (pid(s) 13400) is active...
task_manager (pid(s) 13428) is active...
```

Version
-------
sympa-6.2.62

Installation method
-------------------
FreeBSD package from my own repo, built in poudriere.

Expected behavior
-----------------
sympa processes should not die.

Actual behavior
---------------
sympa_msg died for some reason.

Steps to reproduce
------------------
Wait and see.

Additional information
----------------------
I don't see any warnings or errors in sympa log file, or messages log file.

**Comment by ikedas** [comment]
Hi @pacija ,

Please check the log file to find the entry describing reason of death.  The log entry contains stack trace, the keyword "DIED:", error message and code location. And you may search "DIED:".
