### ISSUE TITLE
Data Source Setup - remove owners

### ISSUE THREAD

**Issue by tmclaren** [sympa-community/sympa#1355]
Version
-------
6.2.68

Installation method
-------------------
cent7 rpm

Expected behavior
-----------------
Removing an owner group:   click the delete check box next to a define owner-list, (Admin > Edit List Config > Data Source Setup - Owners defined in an external data source),  click 'apply modificatin' and the owner's group should be removed from the list.

Actual behavior
---------------
After you click the delete check box next to a define owner-list, (Admin > Edit List Config > Data Source Setup - Owners defined in an external data source),  they (synchronize owners with data sources) button on the Owner's page is removed but the previously defined owner group members persist.

Steps to reproduce
------------------
1.  create a mail list for the owners group , populate it with an email address
2. click the (synchronize owners with data sources) button on the Owner's page
3. -- the members of the owners group are added to the list owners
4. remove the owner's data source with the [] delete check box.
5. nav to owner's page and the (synchronize owners with data sources) button on the Owner's page is MISSING but the members of the owner-group persist.

Additional information
----------------------
The work around is to remove the Admin > Edit List Config > Data Source Setup - Owners defined in an external data source - data source parameters, then navigate to the owner's page, the (synchronize owners with data sources) button remains and the sync will remove the previously defined members of the owner's group.   Now, one can remove that data source definition w/o any issues.

**Comment by ikedas** [comment]
Hi @tmclaren.

As a workaround, after the step 4., could you please wait for a while, i.e. one hour or so?

I think the "synchronize owners with data source" button is missing at the step 5. is a bug. Please check [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1356.patch).

**Comment by ikedas** [comment]
Similar to #858.
