### ISSUE TITLE
Services does not start on RHEL8

### ISSUE THREAD

**Issue by Uno-Yu** [sympa-community/sympa#1360]
Version
-------
sympa-6.2.68
OS:RHEL8
DB; SQLite3
MTA: postfix-3.5.8-2.el8.x86_64
Web: nginx-1.14.1-9

Installation method
-------------------

Sympa and DBD-SQLite are installed from Source code
the others are installed by packages.

Expected behavior
-----------------
I've been working on installing sympa on RHEL8 from source code for a couple of days, but the services (wwsympa & sympa) does not started successfully yet.

Actual behavior
---------------

after "systemctl start wwsympa.service", the following repeats 5 times and fails.
``` code
Mar 10 08:00:31 i-0441b8356be4df60a systemd[1]: wwsympa.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 10 08:00:31 i-0441b8356be4df60a systemd[1]: wwsympa.service: Failed with result 'exit-code'.
Mar 10 08:00:32 i-0441b8356be4df60a systemd[1]: wwsympa.service: Service RestartSec=100ms expired, scheduling restart.
Mar 10 08:00:32 i-0441b8356be4df60a systemd[1]: wwsympa.service: Scheduled restart job, restart counter is at 1.
```

 "systemctl start sympa.service"
``` code
Mar 10 08:20:48 i-0441b8356be4df60a sympa_msg[4438]: err main::#221 > Sympa::Spindle::new#42 > Sympa::Spool::new#65 > Sympa::Spool::_create#89 DIED: Cannot create /usr/local/var/spool/sympa/msg/bad: Permission denied at /usr/local/share/sympa/lib/Sympa/Spool.pm line 89.
```
 ls -ld /usr/local/var/spool/sympa/msg/
drwxr-x--- 2 root root 6 Mar 10 17:47 /usr/local/var/spool/sympa/msg/

**Comment by ikedas** [comment]
@Uno-Yu , could you please folow the instruction described in the [manual](https://sympa-community.github.io/manual/install.html), and tell us where you run into the problem?

**Comment by ikedas** [comment]
Please follow the instruction from the beginning to the end, for example "Installed sympa from source code", please check the instruction in "[Install Sympa distribution: Installing from source](https://sympa-community.github.io/manual/install/install-sympa-distribution-source.html)".

**Comment by Uno-Yu** [comment]
This time I ran into a problem when sending emails.
This seems to be a part which I found I didn't execute lastime
[Telnet Example](https://sympa-community.github.io/manual/install/configure-mail-server.html#telnet-example)
According the sample, I sent an email to the three addresses, and got the following error in /var/log/maillog

``` code
Mar 11 21:06:30 i-0441b8356be4df60a postfix/local[1063]: AD77B1951D3C: to=<bounce+hogehoge@mail.example.org>, relay=local, delay=75936, delays=75936/0.11/0/0.03, dsn=4.3.0, status=deferred (temporary failure)
Mar 11 21:06:30 i-0441b8356be4df60a postfix/local[1036]: AD77B1951D3C: to=<sympa@mail.example.org>, relay=local, delay=75936, delays=75936/0.17/0/0.02, dsn=4.3.0, status=deferred (temporary failure. Command output: /usr/local/libexec/queue: while opening queue file 'T.sympa@mail.example.org.1647000390.1076': Read-only file system )
```

In alias file is like this.
```
sympa:                 "| /usr/local/libexec/queue sympa@mail.example.org"
```

On the other hand, I execute the piped command like this, it works and a file is created in $SPOOL/msg directory
```
# echo abc | /usr/local/libexec/queue sympa@mail.example.org 
# sudo -u postfix sh -c 'echo abc | /usr/local/libexec/queue sympa@mail.example.org'
```

I have tried changing the permission of $LIBEXECDIR/queue file and $SPOOLDIR/msg directroy but could not get any clue.

**Comment by ikedas** [comment]
> ```
> Mar 11 21:06:30 i-0441b8356be4df60a postfix/local[1063]: AD77B1951D3C: to=<bounce+hogehoge@mail.example.org>, relay=local, delay=75936, delays=75936/0.11/0/0.03, dsn=4.3.0, status=deferred (temporary failure)
> Mar 11 21:06:30 i-0441b8356be4df60a postfix/local[1036]: AD77B1951D3C: to=<sympa@mail.example.org>, relay=local, delay=75936, delays=75936/0.17/0/0.02, dsn=4.3.0, status=deferred (temporary failure. Command output: /usr/local/libexec/queue: while opening queue file 'T.sympa@mail.example.org.1647000390.1076': Read-only file system )
> ```

The file system on which the queue is located is mounted read-only.  Probably the filesystem may be inconsistent for some reason such as unclean shutdown.
To repair it, read [the knowledge by Red Hat](https://access.redhat.com/solutions/67454) (you have to log in): Briefly, you'd be better to run the tool (fsck or similar) to repair the file system.

**Comment by ikedas** [comment]
Addition: If you use Amazon EFS (NFS), [the knowledge by Amazon Web Services](https://aws.amazon.com/premiumsupport/knowledge-center/efs-enable-read-write-access/) can be useful.

**Comment by cgx** [comment]
I had the same issue on RockyLinux 8. The solution was to disable [ProtectSystem](https://www.redhat.com/sysadmin/mastering-systemd) in `postfix.service`.
