### ISSUE TITLE
Notification is still sent to new list owner when "no notification" check box is active

### ISSUE THREAD

**Issue by renesepp** [sympa-community/sympa#1361]
Version
-------
[6.2.68]

Installation method
-------------------
RPM

Expected behavior
-----------------
Adding list owner and checking "no notification" check box, no email should be sent to newly added owner

Actual behavior
---------------
When adding new owner to a list and checking "no notification" box a notification is still sent to newly added owner

![image](https://user-images.githubusercontent.com/37406029/157640400-657030dc-b3b6-433b-8baf-57663ecdf402.png)

**Comment by ikedas** [comment]
Duplicate of #1329
