### ISSUE TITLE
Update Editors Family Instanciation

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1369]
Hi, 

I'm using sympa 6.2..40
I had add diffuser to my list family xml file.
then i instanciate the family.
The list don't add the new diffuser to the moderator lists.
I have the same problem for an other family list for updating moderators.
I had used synchonize options (for users, db) into sympa.pl program but their is no changes.
Will you help me for a solution or an idea for the source of the problem? 
Yours faithfully,
Khaoula

**Comment by ikedas** [comment]
Hi @khaoula-abaidi ,

Please show us the XML file before after the modification.

(Though I can't find out what is "diffuser"...)

**Comment by khaoula-abaidi** [comment]
Diffusers are moderators who are able to send mails to the lists but not receive the mails for moderation.
I'm using it into other families and it works correctly.
The problem of this family, the lists are not updating with the new changements after instanciation.
For example, if i change the owner abaidk@gmail.com to an other address  mail and i instanciate the family , the new owner isn't appear into configuration list (interface web to the list).
The same problem for moderators , diffusers, etc.

**Comment by ikedas** [comment]
I am sorry, but could you please provide an explanation as to how you have performed the operation so that I can actually try the same thing?

For example,
> ... i change the owner [abaidk@gmail.com](mailto:abaidk@gmail.com) to an other address mail and i instanciate the family, the new owner isn't appear into configuration list (interface web to the list).

Please write such as:
> I edited the file xxxx and changed the line 'xxxx' to 'xxxx' (_or, insead of describing with words, you may attach the files before and after your edition_), then run the command 'xxxx ...'.  Then I visited the list admin page of web interface, selected the menu 'xxx' and checked what was shown in xxxx.  I expected the address 'xxx@xxx.xxx' is shown, but what I saw was ....

Also, when you submit an issue, please fill in the template (i.e. "Version", "Installation method" etc.). Each item in the template is a matter that must be reviewed by the people trying to solve the problem you reported.

**Comment by khaoula-abaidi** [comment]
No problem.
SYMPA version : 6.2.40
For the list "enseignants.gcu" into the web interface i had the owner is "abaidik@gmail.com"
I want to then the owner list "abaidia.test.mail@gmail.com"
So into the xml file i change the list as this : 
```
	<list>
		<listname>enseignants.gcu</listname>
		<subject>enseignants GCU</subject>
		<custom_subject>Enseignants GCU</custom_subject>
		<owner multiple="1">
			<email>abaidia.test.mail@gmail.com</email>
		</owner>
		<editors multiple="1">
			<name>GCU-Moderators</name>
			<source>groupe-ldap</source>
		</editors>
		<diffusers multiple="1">
			<name>ESST - Diffusers</name>
			<source>groupe-ldap</source>
		</diffusers>
          	<topic>formation</topic>
		<ldap>
			<filter>(&amp;(edupersonaffiliation=faculty)(departmentNumber=gcu))</filter>
		</ldap>
	</list>
```
Then
I instanciate the family with the command line : 
sudo /usr/lib/sympa/bin/sympa.pl --instantiate_family="enseignants" --robot="lists.subdomain.fr" --input_file="/etc/sympa/lists.subdomain.fr/families/enseignants.xml"

Then i updated the interface web for the list but it still the same owner "abaidik@gmail.com".
I changed the priority list and update with the interface web , also the same result( the owner isn't updated ) 
I used : 
- sudo /usr/lib/sympa/bin/sympa.pl --sync_list_db --list="enseignants.gcu@lists.subdomain.fr"
- sudo /usr/lib/sympa/bin/sympa.pl --sync_include --list="enseignants.gcu@lists.subdomain.fr"
- sudo /usr/lib/sympa/bin/sympa.pl --restore_users --list="enseignants.gcu@lists.subdomain.fr" --role="owner"
And into the interface web i have the same result ( the owner isn't updated to abaidia.test.mail@gmail.com ) and still abaidik@gmail.com

**Comment by ikedas** [comment]
@khaoula-abaidi , thank you for sharing your experiences.

I’d like to know if you can determin: Which file of either `config_changes` or `owner.dump` was deleted when the owner was updated as you expected?

**Comment by khaoula-abaidi** [comment]
> @khaoula-abaidi , thank you for sharing your experiences.
> 
> I’d like to know if you can determin: Which file of either `config_changes` or `owner.dump` was deleted when the owner was updated as you expected?

It's the  owner.dump file

**Comment by ikedas** [comment]
@khaoula-abaidi , can you show these things?
- The partr(s) about owners in `config.tt2`;
- The entire content of `param_constraint.conf`.

**Comment by khaoula-abaidi** [comment]
I'm sorry i did delete the content of param_constraint.conf file but i remember that it fixes the priority of the list
For the actual config.tt2  file : 
```
visibility intranet

invite closed

review editor

reply_to_header
apply forced
value sender

web_archive
access editorowner


subject [% subject %]

subscribe closed

serial 11

add closed

send editorkey

status closed

shared_doc
d_edit default
d_read owner

available_user_options
reception digest,digestplain,html,mail,nomail,not_me,notice,summary,txt,urlize

clean_delay_queuemod 15

rfc2369_header_fields archive,help,owner,post,subscribe,unsubscribe

[% FOREACH o = owner %]
owner
  email [% o.email %]
  profile privileged
  reception nomail
[% END %]

# diffuser first then editor
[% FOREACH sd = diffuser %]
editor
visibility noconceal
email [% sd.email %]
reception nomail
[% END %]

[% FOREACH d = diffusers %]
editor_include
source [% d.source %]
reception nomail
source_parameters [% d.name %]
[% END %]

[% FOREACH se = editor %]
editor
email [% se.email %]
reception mail
[% END %]

[% FOREACH e = editors %]
editor_include
source [% e.source %]
source_parameters [% e.name %]
reception mail
[% END %]

info open

archive
period month
access owner

del closed

unsubscribe closed

topics [% topic %]

ttl 43200

include_ldap_query
attrs mail
filter [% ldap.filter %]
ssl_ciphers ALL
host myhost
use_ssl no
timeout 180
suffix ou=people,dc=subdomain,dc=fr
ssl_version sslv3
select first
passwd passwrd
user uid=sympa,ou=admins,dc=subdomain,dc=fr
scope sub

digest 1,4 6:56

custom_subject [% custom_subject %]
```

**Comment by ikedas** [comment]
There seem not problem in `config.tt2`, at least the definition about owners.

If `param_constraint.conf` includes restrictions, corresponding parameter cannot be changed (see [documentation](https://sympa-community.github.io/manual/customize/basics-families.html#param_constraintconf)).  This may also be true for owners.  At the moment, this seems to be the most likely reason why the owner has not changed.
