### ISSUE TITLE
Managing (edit, disable) the exclude list in webinterface

### ISSUE THREAD

**Issue by dkntl** [sympa-community/sympa#137]
Dear Sympa developers,

I stumbled upon a behaviour of Sympa that seemed like a bug first. I have a mailing list with a data-source which manages the subscribers of the list automatically. There were also some manually subscribed addresses in the list - some of them were also present in the data-source. Because I wanted them gone when they are gone in the source (and did not want the purely manual subscribed addresses at all), I wanted to delete this manual subscribers. For convenience (not wanting to sort out the hundreds of addresses) I simply deleted all the subscribers, planning to resynchronize the list with the data-source afterwards.

But the subscribers did not appear again. After some research and asking around, I found out that this is a feature of Sympa - the addresses were added to an exclude list. Thus Sympa would not add them even if they were in the data-source.

This feature is ok and I think there are use-cases where it is needed. But it would be much better if the user would
a) Be notified that something like this happens when I simply unsubscribe addresses
b) Have a way to see and manage this exclude list in the webinterface.
c) Be able to disable the feature for a list.

I know subscribing the users again puts them off the list, but there is a problem with that. I still do not know who is actually on the exclude list, even if I go and look up the addresses in the data-source. Because  -apart from not every list owner being able to do that - it can (and in my case it also did) happen that in the meantime the addresses in the data-source changed - some of them dropped out.

This is a problem in the moment the system in the background decides that they shall be in the list again. Sympa would not add them because they are still in the exclude list.
So the only way known to me is look this exclusions up in the Sympa database and get rid of them manually. This is possible for the system administrator, but not for a simple listmaster or owner.

It would be very appreciated if such features could be added to Sympa.

Thank you.

**Comment by ikedas** [comment]
@dkntl, "Exclude" link on review page will show list of exclusion, though it does not suffice...

**Comment by ikedas** [comment]
Stagnated issue. Closed for the present.
