### ISSUE TITLE
Data source configuration interface 

### ISSUE THREAD

**Issue by sylvainbx** [sympa-community/sympa#1371]
Where is it?
Previously, we made a big work to automate the subscriptions to all our lists, with LDAP. We made the entier configuration from the interface and it used to work flawlessly. 
Now, we have to change some elements in the LDAP configuration but I can't find anywhere the LDAP data source configuration interface (previously in https://listes.example.org/sympa/edit_list_request/mylist/data_source). I guess this is due to an update (our current version is 6.2.60) but I cheked the [changelog](https://www.sympa.org/NEWS.md), and I only found [that](https://github.com/sympa-community/sympa/issues/693) but I didn't found anything like "removal of the data source configuration interface".
Our sympa instance in mutualized so we don't have access to the host and the file system, so how can we continue to use the data source now ?

**Comment by ikedas** [comment]
@sylvainbx , first of all, could you please check the settings in [edit_list.conf](https://sympa-community.github.io/gpldoc/man/edit_list.conf.5.html)?
