### ISSUE TITLE
Dissociate list from family

### ISSUE THREAD

**Issue by khaoula-abaidi** [sympa-community/sympa#1372]
I want dissociate a list from a family 
Version
-------

6.2.40

source package => ubuntu 20.04

-----------------

I want had a procedure for dissociating a list from a family properly so the list will be not attached to her family

Yours faithfully

**Comment by ikedas** [comment]
Hi @khaoula-abaidi ,

AFAIK there is no formal procedure to join a single list to a family or to make a instance of a family a single list.

I guess a convenient way to make a list instantiated in a family a single list is editing `config` file of the list to remove (or comment out) the `family_name` parameter.

**Comment by salaun-urennes1** [comment]
I confirm that the procedure suggested by Soji should work fine.
You could have a try with a test family I suppose

**Comment by khaoula-abaidi** [comment]
Thanks for your advise @ikedas and for your confirmation @salaun-urennes1

**Comment by ikedas** [comment]
Please continue disscussion on #1394 that deals with the same issue.
