### ISSUE TITLE
Message content truncation

### ISSUE THREAD

**Issue by tmclaren** [sympa-community/sympa#1374]
We've had a few reports of email content being truncated.  After comparing the inbound, archive and outbound email we noticed:
    IF a period '.' falls on the EOL (76 char)  Sympa will add the line break '=' (see view source in archive), 
    AND IF the author intended to end a paragraph with a return
    THEN all data after that pattern is truncated from the message body.   

Additional testing revealed Sympa will consistently truncates content in a message body after it parses this pattern.  
``` code
---
blank line
.
blank line

```

Version
-------

v6.2.68

Installation method
-------------------
Cent7, RPM install, Mariadb, Postfix

Expected behavior
-----------------
Sympa should not truncate the content in a message payload.

Actual behavior
---------------
Sympa parses the above pattern and truncates message payload to subscribers.  However, the inbound message in the archive retains the entire message content. 

Steps to reproduce
------------------
Send this content to a test list.  Message data before the truncation pattern
``` code
---

.

----
```
Data after the second blank line, including the dashes will be truncated when sent to the subscribers.  Note:  the archive retains the original content.

Additional Information
-------------------------
It appears Sympa interprets this pattern as the end of message and sends to subscribers.

**Comment by ikedas** [comment]
Hi @tmclaren , I edited your post. Please confirm if it shows what you intended.

Additionally, please give us following information:

  1. The samples of raw message both before and after going through Sympa.
        - The "raw message" is  the entire (i.e. including header & body) source text of the message.
       - To get them both before and after going through Sympa, you may send a message CC-ing to both list and yourself.
  3. Setting of Sympa (`sympa.conf` and optionally `robot.conf`) and the list (`config`).

You may mask sensitive information (password, e-mail, host name etc.) if necessary, however addresses and host names different each other could be distinguished (such as address-1, host-2).

**Comment by ikedas** [comment]
As a result on my side, I couldn't reproduce the problem.

Before (i.e. sent to myself):
``` code
Return-Path: <myname@my.domain>
X-Original-To: myname@my.domain
Delivered-To: myname@my.domain
Received: from localhost (localhost [127.0.0.1])
	by mta.my.domain (Postfix) with ESMTP id 857944FB13;
	Wed, 13 Apr 2022 10:39:15 +0900 (JST)
X-Virus-Scanned: amavisd-new at my.domain
Received: from mta.my.domain ([127.0.0.1])
	by localhost (mta.my.domain [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id wj9Y6aMN4pBA; Wed, 13 Apr 2022 10:39:15 +0900 (JST)
Received: from relay.xx.local (xxxxxx.xxxxxxxxxx.xx.jp [nnn.nnn.nnn.12])
	by mta.my.domain (Postfix) with ESMTPSA id 2B2344FB12;
	Wed, 13 Apr 2022 10:39:15 +0900 (JST)
Date: Wed, 13 Apr 2022 10:39:12 +0900
From: IKEDA Soji <myname@my.domain>
To: list-001@sympa.my.domain
Cc: myname@my.domain
Subject: Test messsage
Message-Id: <20220413103912.2bf96d3aae2df1d9b33ab2c4@my.domain>
Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit

---

.

----
```

After (i.e. delivered through the list):
``` code
Return-Path: <bounce+myname==a==my.domain==list-001==460@sympa.my.domain>
X-Original-To: myname@my.domain
Delivered-To: myname@my.domain
Received: from localhost (localhost [127.0.0.1])
	by mta.my.domain (Postfix) with ESMTP id 52BF34FB13
	for <myname@my.domain>; Wed, 13 Apr 2022 10:39:20 +0900 (JST)
X-Virus-Scanned: amavisd-new at my.domain
Received: from mta.my.domain ([127.0.0.1])
	by localhost (mta.my.domain [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id o2XNBOOTdHG6 for <myname@my.domain>;
	Wed, 13 Apr 2022 10:39:20 +0900 (JST)
Received: by mta.my.domain (Postfix, from userid 106)
	id 429514FB12; Wed, 13 Apr 2022 10:39:20 +0900 (JST)
Received: from localhost (localhost [127.0.0.1])
	by mta.my.domain (Postfix) with ESMTP id 857944FB13;
	Wed, 13 Apr 2022 10:39:15 +0900 (JST)
X-Virus-Scanned: amavisd-new at my.domain
Received: from mta.my.domain ([127.0.0.1])
	by localhost (mta.my.domain [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id wj9Y6aMN4pBA; Wed, 13 Apr 2022 10:39:15 +0900 (JST)
Received: from relay.xx.local (xxxxxxx.xxxxxxxxxx.xx.jp [nnn.nnn.nnn.12])
	by mta.my.domain (Postfix) with ESMTPSA id 2B2344FB12;
	Wed, 13 Apr 2022 10:39:15 +0900 (JST)
Date: Wed, 13 Apr 2022 10:39:12 +0900
From: IKEDA Soji <myname@my.domain>
To: list-001@sympa.my.domain
Cc: myname@my.domain
Subject: Test messsage
Message-Id: <20220413103912.2bf96d3aae2df1d9b33ab2c4@my.domain>
Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
Reply-To: list-001@sympa.my.domain
X-Loop: list-001@sympa.my.domain
X-Sequence: 86
Errors-To: list-001-owner@sympa.my.domain
Precedence: list
Precedence: bulk
Sender: list-001-request@sympa.my.domain
X-no-archive: yes
List-Id: <list-001.sympa.my.domain>
List-Help: <https://sympa.my.domain/sympa/help>, <mailto:sympa@sympa.my.domain?subject=HELP>
List-Subscribe: <https://sympa.my.domain/sympa/subscribe/list-001>, <mailto:sympa@sympa.my.domain?subject=SUB%20list-001>
List-Unsubscribe: <https://sympa.my.domain/sympa/signoff/list-001>, <mailto:sympa@sympa.my.domain?subject=SIG%20list-001>
List-Post: <mailto:list-001@sympa.my.domain>
List-Owner: <mailto:list-001-request@sympa.my.domain>
List-Archive: <https://sympa.my.domain/sympa/arc/list-001>
Archived-At: <https://sympa.my.domain/sympa/arcsearch_id/list-001/2022-04/20220413103912.2bf96d3aae2df1d9b33ab2c4%40my.domain>
Disposition-Notification-To: bounce+myname==a==my.domain==list-001==460@sympa.my.domain

---

.

----
```

**Comment by tmclaren** [comment]
We're in the process of pulling together a number of examples.

**Comment by tmclaren** [comment]
Hi @ikedas - We setup a list with examples in the archive, https://lists.illinois.edu/lists/arc/truncate/2022-04/.  What email address will  you use to login?  I'll make you a privileged owner.  The inbound/archive look as expected however when you select a message and click the 're-deliver' option, you'll noticed the message delivered was truncated.   I suspect Sympa is seeing the pattern as an end of message. 
CR LF 
. 
CR LF

Terry

**Comment by ikedas** [comment]
Generally I don't prefer to logging into another organisation's system, especially as an admin. Please show us the messages by yourself.

Also, please let us check the configuration of your Sympa (you can do this first if you can't provide the messages immediately):  (`sympa.conf` and optionally `robot.conf`, and the list's `config`).  You may mask sensitive information (password, e-mail, host name etc.) if necessary,

**Comment by tmclaren** [comment]
Postfix config issue.

**Comment by ikedas** [comment]
What is the detail of the issue? Could you share your experiences with the community?

The setting with Sympa that comes to my mind is the [`sendmail_args`](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#sendmail_args) parameter in `sympa.conf`.  In the modt cases its default value may not be changed.
