### ISSUE TITLE
blocklist sensitive to spurious whitespace

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1377]
Version
-------

6.2.66

Installation method
-------------------

My own rpm, derived from the official rpm

Expected behavior
-----------------

If someone pastes an email address into the blocklist on the list with some spurious whitespace at the end, for example:

"localpart@domain "

(obviously without the quotes), that entry in the block list should still work.

Ideally Sympa would also automatically trim any whitespace at the start and end of each line when the blocklist is updated.

Actual behavior
---------------

One of my users complained that an entry on their blocklist (with 733 entries!) wasn't working. 

The cause turned out to be a stray space at the end of that specific line in the block list.

Additional information
----------------------
lib/Sympa/Scenario.pm:
```
sub do_search {
            [...]
            while (my $pattern = <$ifh>) {
                next if $pattern =~ /\A\s*\z/ or $pattern =~ /\A[#;]/;
                chomp $pattern;
                $pattern =~ s/([^\w\x80-\xFF])/\\$1/g;
```
A quick test reveals that an input of $pattern="localpart@domain " turns into "localpart@domain\ ": the trailing space gets quoted.

I would suggest replacing the chomp() with something that removes all white space at the start and end of each line.

**Comment by ikedas** [comment]
Fixed.  Thank you for reporting bug and suggesting fix!
