### ISSUE TITLE
(Bulk) Resent all non-delivered emails

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#1383]
Using Debian 11 (stable/bullseye) with *sympa* 6.2.60~dfsg-4, sometimes there are delivery failures, due to big email providers thinking they can block email and force their spam problem upon other people. When these issues are addressed, it be great to be able to just send all emails with delivery errors again. I know, a single user can do it, but can it also be done by the administrator for all subscribers, whose provider had problems?

**Comment by ikedas** [comment]
Hi,

Basically you can customize [`nrcpt`](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#nrcpt) and [`avg`](https://sympa-community.github.io/gpldoc/man/sympa_config.5.html#avg) parameters and/or [`nrcpt_by_domain.conf`](https://sympa-community.github.io/gpldoc/man/nrcpt_by_domain.conf.5.html) configuration file.

**Comment by paulmenzel** [comment]
Thank you for the quick replay, but it’s not what I meant. Google Mail didn’t reject the emails because of too many recipients in one delivery attempt, but because my email server didn’t have an SPF record (totally unrelated, as the sender had a gmail.com address).

My feature request is, if I see there were failed delivery attempts, I’d like to tell Sympa to send those messages again just for these recipients. It’d be great to do that either in the Web GUI or the CLI.

**Comment by ikedas** [comment]
> Thank you for the quick replay, but it’s not what I meant. Google Mail didn’t reject the emails because of too many recipients in one delivery attempt, but because my email server didn’t have an SPF record (totally unrelated, as the sender had a gmail.com address).
> 
> My feature request is, if I see there were failed delivery attempts, I’d like to tell Sympa to send those messages again just for these recipients. It’d be great to do that either in the Web GUI or the CLI.

Setting up SPF is one of measures Google recommends (See [the doc by Google](https://support.google.com/a/answer/10583557?hl=en)).

You would be better to do **at least SPF**, the easiest one in the measures above.
(The ideal measure would be to set up [DKIM & ARC](https://sympa-community.github.io/manual/customize/dkim-arc.html) with Sympa, besides).

On the contrary, IMO the feature you are requesting is not recommended. The more your server repeatedly resending, the more your server will look like a malicious spammer.

**Comment by paulmenzel** [comment]
> > Thank you for the quick replay, but it’s not what I meant. Google Mail didn’t reject the emails because of too many recipients in one delivery attempt, but because my email server didn’t have an SPF record (totally unrelated, as the sender had a gmail.com address).
> > My feature request is, if I see there were failed delivery attempts, I’d like to tell Sympa to send those messages again just for these recipients. It’d be great to do that either in the Web GUI or the CLI.
> 
> Setting up SPF is one of measures Google recommends (See [the doc by Google](https://support.google.com/a/answer/10583557?hl=en)).

Yes, I know. I read their 550 error message.

    550-5.7.1 [XXX      19] Our system has detected that\n550-5.7.1 this message is likely suspicious due to the very low reputation of\n550-5.7.1 the sending domain. To best protect our users from spam, the message\n550-5.7.1 has been blocked. Please visit\n550 5.7.1  https://support.google.com/mail/answer/188131 for more information.

Why should anyone care what Google deems good or bad? Only because they were able to acquire a big market share, and are unable to deal with unsolicited email, they burden operators of totally valid email servers.

> You would be better to setup **at least SPF** on your domain, the easiest one among the measures above. (The ideal measure would be to set up [DKIM & ARC](https://sympa-community.github.io/manual/customize/dkim-arc.html) with Sympa, besides).

At least in my experience spam messages did not decrease, so these measures are all a waste, and add unwanted complexity.

> On the contrary, IMO the feature you are requesting is not recommended. The more your server repeatedly resending, the more your server will look like a malicious spammer.

Well, obviously the operator would only use it, after making sure the setup was improved, and not repeatedly click on the resent button. I think, you should trust the list operator/admin to carefully use such a feature.

**Comment by ikedas** [comment]
> > > Thank you for the quick replay, but it’s not what I meant. Google Mail didn’t reject the emails because of too many recipients in one delivery attempt, but because my email server didn’t have an SPF record (totally unrelated, as the sender had a gmail.com address).
> > > My feature request is, if I see there were failed delivery attempts, I’d like to tell Sympa to send those messages again just for these recipients. It’d be great to do that either in the Web GUI or the CLI.
> > 
> > 
> > Setting up SPF is one of measures Google recommends (See [the doc by Google](https://support.google.com/a/answer/10583557?hl=en)).
> 
> Yes, I know. I read their 550 error message.
> 
> ```
> 550-5.7.1 [XXX      19] Our system has detected that\n550-5.7.1 this message is likely suspicious due to the very low reputation of\n550-5.7.1 the sending domain. To best protect our users from spam, the message\n550-5.7.1 has been blocked. Please visit\n550 5.7.1  https://support.google.com/mail/answer/188131 for more information.
> ```
> 
> Why should anyone care what Google deems good or bad? Only because they were able to acquire a big market share, and are unable to deal with unsolicited email, they burden operators of totally valid email servers.
> 
> > You would be better to setup **at least SPF** on your domain, the easiest one among the measures above. (The ideal measure would be to set up [DKIM & ARC](https://sympa-community.github.io/manual/customize/dkim-arc.html) with Sympa, besides).
> 
> At least in my experience spam messages did not decrease, so these measures are all a waste, and add unwanted complexity.

You probably misunderstand.  The purpose of setting SPF _on your domain_ (i.e. adding a DNS record for SPF to your domain nme server) is not to reduce the amount of spam you receive, but to ensure that your sending server is not suspected of spam.

> > On the contrary, IMO the feature you are requesting is not recommended. The more your server repeatedly resending, the more your server will look like a malicious spammer.
> 
> Well, obviously the operator would only use it, after making sure the setup was improved, and not repeatedly click on the resent button. I think, you should trust the list operator/admin to carefully use such a feature.

I think adding an SPF record is far less complex. If you don't know how to do it, please ask your organisation's administrator of DNS (domain name server).

**Comment by racke** [comment]
SPF and DKIM are essential for a mail server. PTR record is also required.

**Comment by paulmenzel** [comment]
I do not understand, why this thread turned into sharing opinions on how to operate email servers. ;-) (But here you go with my opinion, no, they are not essential technically, and only exist because big email providers force policies on other operators, because they are unable to deal with spam.)

SPF was just an example at hand, but delivery can fail due to a number of problems (hardware, network, configuration), making it convenient to resent the message to those subscribers, where delivery failed.

**Comment by ikedas** [comment]
Hi @paulmenzel ,

To learn more about SPF, see [The SPF Project](http://www.open-spf.org/) web site.

Just to be clear, they don't work for Google (only).

**Comment by paulmenzel** [comment]
Thanks, I know very well, how SPF works.

Can you please enlighten me, why you closed the issue. It looks like we totally misunderstood each other.

**Comment by racke** [comment]
@paulmenzel Your request for redeliver emails is the first I'm am aware of in the Sympa context. Please understand that we don't pursue it and look at more relevant issues. And setting up your mail server with the standard measurements is your job.
