### ISSUE TITLE
Receiving error "create_list [user] XXX Could not create list" when I attempt to create a list from command prompt

### ISSUE THREAD

**Issue by SympaNovice** [sympa-community/sympa#1388]
Version
-------
 6.2.68

Installation method
-------------------
Someone else installed so not sure ...I'm guessing rpm
PLEASE NOTE: It has two robots ...domain1_robot and domain2_robot
domain1_robot is the primary

Expected behavior
-----------------
I want to create a list from a script rather than the web-ui ...I'm following the instructions outlined in the documentation

Actual behavior
---------------
When I run the command 
sympa create --input_file=/path_to_my_xmlfiles/myfile.xml domain2_robot

I receive the error ...
"create_list [user] XXX
Could not create list"

Additional information
----------------------

Example of myfile.xml attached in zipped file myfile.zip....

PLEASE NOTE: the type "my_private_working_grp" contains a comment.tt2 and config.tt2 file. It is an exact copy of "/home/sympa/default/create_list_templates/private_working_group" (I haven't changed any of the tt2 files)

[myfile.zip](https://github.com/sympa-community/sympa/files/8562339/myfile.zip)

**Comment by SympaNovice** [comment]
[myfile.zip](https://github.com/sympa-community/sympa/files/8562142/myfile.zip)
Please see a copy of myfile.xml in attached zip file

**Comment by ikedas** [comment]
Hi @SympaNovice , can you show us the log during execution of the command?

**Comment by racke** [comment]
Try to add a description for your list.

**Comment by SympaNovice** [comment]
Thanks @ikedas for your reply.
 I will look up the logs and get back to you.

**Comment by SympaNovice** [comment]
Thanks @racke for your reply.
I did test with a description in the xml file but received the same error.
The format I used for the description was as follows....
"<description>This list is created by script</description>"
If this is incorrect you might let me know the syntax?
Thanks again.

**Comment by SympaNovice** [comment]
Sorry @racke, the format I copied into last message is not displaying properly in the message

I put the list description within description tabs see attached for format 
[description-in-xml-file.txt](https://github.com/sympa-community/sympa/files/8582562/description-in-xml-file.txt)

**Comment by racke** [comment]
I think in your first line you need to quote 1.0:

`<?xml version="1.0" ?>`

Also a full path is not allowed in the type element.

**Comment by SympaNovice** [comment]
Thanks a million @racke. I will make those changes and let you know how I get on.

**Comment by SympaNovice** [comment]
Hi @racke,
I had to also change the owner and editor tags as it did not like the "multiple=1" option ...it was not seeing the start tag as a result.
Please see the revised xml file attached.

Now when I run the following command:

/home/sympa/bin/sympa create --input_file=/home/sympa/etc/xmlfiles/listcreation_tmp.xml domain_robot2

I receive the error: Not an ARRAY reference at /home/sympa/bin/Sympa/Request/Handler/create_list.pm line 91.


sympa logs excerpt:

Apr 29 09:05:04 testlserv sympa[1339]: info Sympa::CLI::arrange() Configuration file read, default log level 0
Apr 29 09:05:04 testlserv sympa[1339]: notice Sympa::CLI::arrange() Sympa 6.2.68 Started
Apr 29 09:05:04 testlserv sympa[1339]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=create_list;context=domain_robot2>
[MyXMLFile.txt](https://github.com/sympa-community/sympa/files/8589229/MyXMLFile.txt)

**Comment by SympaNovice** [comment]
Hi All, 

Just letting you know, I tried it again today and it works now...I don't remember changing anything else. Thanks @racke and @ikedas for getting back to me and your help.
