### ISSUE TITLE
Upgrade mySQL Dump from 6.2.24 to PSQL Sympa 6.2.68

### ISSUE THREAD

**Issue by Safin85** [sympa-community/sympa#1390]
I have to import a mysql dump from sympa 6.2.24 into psql runing sympa 6.2.68

Version
-------
6.2.24 -> 6.2.68

Installation method
-------------------
I installed it on RedHat with dfn and https://copr.fedorainfracloud.org/coprs/xavierb/sympa/

Expected behavior
-----------------
Hello,

I had to switch off a server with Sympa 6.2.24 for security reasons and can no longer switch it on. Sympa ran on the server with MySQL. I have a dump from that too.

Now I have to use RedHat and it doesn't have Sympa in its repository. So I resorted to Xavierb (https://copr.fedorainfracloud.org/coprs/xavierb/sympa/) with dfn. Sympa 6.2.68 was installed for me and it runs fine. Now I wanted to import the old dump from MySQL into PSQL and I noticed that some columns in the tables had changed.

I have now tried Sympa downgrade. But apparently xavierb doesn't offer an older version. How can I now import my dump from the old Sympa into the new one?

I have now tried Sympa downgrade. But apparently xavierb doesn't offer an older version. How can I now import my dump from the old 

Thanks very much

**Comment by racke** [comment]
Using a dump from an older server is common task when migrating to a new server, so my recipe for that is:

1. Import SQL dump
2. Edit /etc/sympa/data_structure.version with the version of the older server (in your case 6.2.24).
3. Run sympa --upgrade

No guarantee that it works in your case, but my two cents.

**Comment by Safin85** [comment]
I just tried that and it worked for me too. But that in MySQL. 
Is there a way to get the data in pSQL now?

**Comment by ldidry** [comment]
For that, you should have a look à [PgLoader](https://pgloader.io/).

**Comment by ikedas** [comment]
@Safin85 , I think you'd be better to check #1317 also.
