### ISSUE TITLE
dkim_signature_apply_on has only effect in list config

### ISSUE THREAD

**Issue by Ygreneb** [sympa-community/sympa#1391]
Version
-------

6.2.60 on Debian 11

Installation method
-------------------

apt install

Expected behavior
-----------------

Sympa should apply signature to all outgoing messages of all lists, if `dkim_signature_apply_on any` is set in `sympa.conf`.

Actual behavior
---------------

Sympa only applies signature to lists that have `dkim_signature_apply_on any` set in their list config. `dkim_parameters` are correctly 'inherited' and shown on individual list config website, but `dkim_signature_apply_on` remains empty.

Steps to reproduce
------------------

1. DKIM-related settings in `sympa.conf`:
```
dkim_parameters.private_key_path </path/to/key.private>
dkim_parameters.selector <selector>
dkim_parameters.signer_domain <sympa domain>
# Prevent the default:
dkim_signature_apply_on none
```
2. Create list and set `dkim_signature_apply_on` to `any`
3. Send mail via newly created list and check headers in mail client -> DKIM-signature passed (providing selector, DNS, etc. was set up correctly)
4. Set `dkim_signature_apply_on any` in `sympa.conf`
5. Create second list, don't touch `dkim_signature_apply_on`
6. Send mail via newly created second list and check headers in mail client -> no DKIM-signature

Additional information
----------------------

`dkim_feature` was intentionally not set, which results in the default `dkim_feature off`, as I don't want to check DKIM signatures of incoming messages. Also, as DKIM signatures are created for the first list, this setting does not seem to be a requirement for _creating_ DKIM signatures.

**Comment by ikedas** [comment]
Hi @Ygreneb ,
Just in case, did you restart the all services of Sympa after changing `sympa.conf`?

**Comment by Ygreneb** [comment]
Hey @ikedas ,
Yes, I've restarted all services.

**Comment by ikedas** [comment]
@Ygreneb , you'd be better to set `dkim_feature` as `on`.

If it is `on`, Sympa will remove DKIM signatures which are invalid. So, if the DKIM feature is enabled, signature should be checked anyways.

**Comment by Ygreneb** [comment]
If I set `dkim_feature` as `on`, will Sympa only remove an invalid DKIM signature but process/distribute the mail nevertheless?

**Comment by ikedas** [comment]
> @ikedas If I set `dkim_feature` as `on`, will Sympa only remove an invalid DKIM signature but process/distribute the mail nevertheless? The [docs](https://sympa-community.github.io/manual/customize/dkim-arc.html) are a bit unclear about this, it says:
> 
> > Processing of DKIM status of incoming messages is done by the MTA (Mail transfer agent) that delivers emails to the Sympa server Sympa domain (in order to reject some messages). This topic is not addressed in the chapter of the documentation.
> 
> So the MTA decides what to do with incoming mail with invalid DKIM signature, but Sympa removes it if the MTA passes it?

In other case, the signature may be invalidated because Sympa itself has altered the message (e.g. altering subject). Anyways if DKIM feature is enabled, Sympa will remove invalid signatures before signing the outgoing message.  See also "[Message alteration](https://sympa-community.github.io/manual/customize/basics-alterations.html)" in the doc (especially "Encrypting and signing").
