### ISSUE TITLE
when generating a list from command prompt, I cannot get the ldap2 query include to work

### ISSUE THREAD

**Issue by SympaNovice** [sympa-community/sympa#1392]
PLEASE HELP: when generating a list from command prompt, I cannot get the ldap2 query include to work

Version
-------
6.2.68

Installation method
-------------------
not sure...rpm possibly...I did not install

Expected behavior
-----------------
I want to populate the list subscribers from an LDAP 2-level query inclusion from a SCRIPT rather than the web interface
NOTE: I can manually update the web interface config option "LDAP 2-level query inclusion (include_ldap_2level_query) " and then "synchronize members with data sources" and this successfully updates the list subscribers

Actual behavior
---------------
When I run my script, it successfully creates the list but the LDAP 2-level query inclusion (include_ldap_2level_query) in the web-interface is NOT POPULATED with the ldap data from my  myfile.incl file

Qs. Please let me know what I am doing wrong? 
Qs. What parameter should I use in the XML file to include subscribers from ldap2 include?

Note: The script runs the command:
/home/sympa/bin/sympa create --input_file=/home/sympa/etc/xmlfiles/myXMLfile.xml domain_robot2

I assumed I tell it about the ldap query in the xml file ...I don't know what the parameter for the members should be...I have guessed and tried various options including "data_source" but without success.

Additional information
----------------------

I hope I have removed sensitive info...please see excerpt from log files and examples of files attached...
May  4 17:27:49 testlserv sympa[28862]: info Sympa::CLI::arrange() Configuration file read, default log level 0
May  4 17:27:49 testlserv sympa[28862]: notice Sympa::CLI::arrange() Sympa 6.2.68 Started
May  4 17:27:49 testlserv sympa[28862]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=create_list;context=mydomain_robot2>
May  4 17:27:54 testlserv sympa[28862]: notice Sympa::Request::Handler::create_list::_twist() Synchronizing list members...
May  4 17:27:54 testlserv sympa[28862]: notice Sympa::Request::Handler::create_list::_twist() ...done

[myfile.incl.txt](https://github.com/sympa-community/sympa/files/8622187/myfile.incl.txt)
[myXMLFile.xml.txt](https://github.com/sympa-community/sympa/files/8622188/myXMLFile.xml.txt)

PLEASE NOTE: On the server the location of .....
.incl file is /home/sympa/etc/data_sources 
.xml file is /home/sympa/etc/xmlfiles

**Comment by SympaNovice** [comment]
I have since edited the config.tt2 of my_private_working_grp with the entry in the attached txt file
[config.tt2.txt](https://github.com/sympa-community/sympa/files/8632556/config.tt2.txt)
 please see log excerpt...
May  5 16:19:29 testlserv sympa[543]: err main::#39 > Sympa::CLI::run#176 > Sympa::CLI::create::_run#59 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_list::_twist#215 > Sympa::List::new#181 > Sympa::List::load#699 > Sympa::List::_load_list_c
onfig_file#5038 Bad entry "  source myFile.incl" for key "source", paragraph "member_include" in file "/home/sympa/expl/domain_robot2/tstgrp4-staff/config"
May  5 16:19:29 testlserv sympa[543]: info Sympa::List::_load_list_config_file() Missing key "source" in param "member_include" in /home/sympa/expl/domain_robot2/tstgrp4-staff/config

Qs. Am I going about this incorrectly? 
Any help/guidance would be greatly appreciated

Qs. What steps do I need to follow in order to get it to populate the new list's ldap2 query parameters from a script?

Qs. Could you confirm the syntax for each file (xml, incl and config.tt2) I should be using to get it to populate the new list's ldap2 query parameters ?

Note: 
1. I've created an entry in the XML file for the member_include (see xml file in previous comment), 
2. I've created the .incl file which details the values for each ldap2 query parameter in /home/sympa/etc/data_sources (see incl file in previous comment)
3. I've updated the config.tt2 with the include member details (as per xml and incl files)...see the entry I added to the tt2 file attached 
4. I run the following command from my script:
/home/sympa/bin/sympa create --input_file=/home/sympa/etc/xmlfiles/myXMLfile.xml domain_robot2

**Comment by ikedas** [comment]
@SympaNovice , if you use the separate `*.incl` file including definition of inclusion (this method is recommended), you have to add a `member_include` parameter to list `config` file so that the list will use that definition, such as:

``` code
member_include myfile
```
(or you may add "Subscribers defined in an external data source" setting in list admin page.)

`myfile.incl` has to be placed in `data_sources` directory.

For more details see "[Data sources](https://sympa-community.github.io/manual/customize/data-sources.html)" in the manual.

**Comment by SympaNovice** [comment]
Thanks @ikedas, 

I'm afraid my efforts were unsuccessful when i tried to use the incl file:

sympa log excerpt:

May 25 16:13:58 testlserv sympa[7608]: info Sympa::List::_load_list_config_file() Missing key "source" in param "member_include" in /home/sympa/expl/robot2/tstgrp7-staff/config
May 25 16:13:59 testlserv sympa[7608]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=tstgrp7-staff@robot2;role=member>

PLEASE NOTE: the config file contains "member_include tstgrp7.incl"

My script with the steps below ....

 1. generate the xml file used in the creation of the new list
echo "<?xml version=\"1.0\" ?>
<list>
    <listname>$strListName</listname>
    <type>my_private_working_grp</type>
    <subject>Test group</subject>
    <description>$strDescription</description>
    <status>open</status>
    <shared_edit>editor</shared_edit>
    <shared_read>private</shared_read>
    <language>en_US</language>
    <owner multiple=\"1\">
        <email>myemail@list.mydomain.ie</email>
        <gecos>My Name</gecos>
    </owner>
    <editor multiple=\"1\">
        <email>myemail@list.mydomain.ie</email>
    </editor>
    <topic>$strTopic</topic>
</list> " >/home/sympa/etc/xmlfiles/listcreation_$strID.xml

2. Change ownership of xml file to sympa
chown -R sympa.sympa /home/sympa/etc/xmlfiles/listcreation_$strID.xml

3. Create the new list
/home/sympa/bin/sympa create --input_file=/home/sympa/etc/xmlfiles/listcreation_$strID.xml $strRobot

4. Backup the new list's config file
cp /home/sympa/expl/$strRobot/$strListName/config /home/sympa/expl/$strRobot/$strListName/config.bkup

5. make datasource directory
mkdir /home/sympa/expl/$strRobot/$strListName/data_sources
#Change ownership
chown -R sympa.sympa /home/sympa/expl/$strRobot/$strListName/data_sources


6. generate the incl file
echo "include_ldap_2level_query
select2 all
scope2 sub
suffix1 cn=$strID,$strDefaultEmailGroup
suffix2 $strDefaultEmailPeople
attrs1 memberUid
select1 all
filter2 uid=[attrs1]
timeout1 30
ca_verify none
ssl_ciphers ALL
attrs2 mail
name $strListName
scope1 sub
host ldap-server
filter1 objectClass=inetLocalMailRecipient
ssl_version tlsv1
timeout2 30
use_tls starttls" >>/home/sympa/expl/$strRobot/$strListName/data_sources/$strID.incl

7. change ownership of incl file
chown -R sympa.sympa /home/sympa/expl/$strRobot/$strListName/data_sources/$strID.incl


8. append the include ldap2 query to the new list's config file
echo "member_include $strID.incl" >>/home/sympa/expl/$strRobot/$strListName/config

9. Force the task manager to run in order to update the new list with the subscribers from the ldap2 include
/home/sympa/bin/sympa include --role=member $strListName@$strRobot

PLEASE NOTE: The only way I can get it to work is if I append the content of the incl file (ie. include_ldap_2level_query
select2 all etc. etc.) into the list "config" file like I mentioned previously

**Comment by SympaNovice** [comment]
[Generate-myXML-file.txt](https://github.com/sympa-community/sympa/files/8772591/Generate-myXML-file.txt)

**Comment by ikedas** [comment]
My mistake.  Correct setting in list `config` file is such as:

``` code
member_include
  source myfile
```

**Comment by SympaNovice** [comment]
Thanks @ikedas,
 
I did try using the syntax you recommend with word "source"  in the config file but I'm still receiving an error in the logs....
e.g.
member_include source tstgrp7.incl

and also split it over two lines...

member_include 
   source tstgrp7.incl

sympa log excerpt: 
May 27 09:32:47 testlistserv sympa[1623]: info Sympa::List::_load_list_config_file() Missing key "source" in param "member_include" in /home/sympa/expl/robot2/tstgrp7-staff/config


PLEASE NOTE: As a last attempt, I also added the following line to the template file that I am using to create the list in my xml file i.e.  "/sympa/home/etc/create_list_templates/my_private_working_grp" template config.tt2 file
member_include
  source [% source %]

Is the syntax correct for this? Is it needed or should I remove it?

Thanks,
Mary

**Comment by ikedas** [comment]
* Please omit `.incl‘ in file name.
  * Instead of `[% source %]`, use file name (without `.incl`).
``` code
member_include
source myfile
```

**Comment by SympaNovice** [comment]
Thanks @ikedas for all your help ...that worked!

The following outlines the steps involved should anyone else need to do it...

#0. Edited my customised template file that I am using to create the list in my xml file i.e. "/sympa/home/etc/create_list_templates/my_private_working_grp" template config.tt2 file and added the two lines...

member_include
source ldap2IncludeFile

I  then changed my script as follows...

#1. generate the incl file in the sysconfig directory structure (which will be overwritten every time I run the script)
/home/sympa/etc/data_sources/ldap2IncludeFile.incl

#2. generate the xml file used in the creation of the new list

#3. Change ownership of xml file to sympa
chown -R sympa.sympa /home/sympa/etc/xmlfiles/listcreation_$strID.xml

#4. Create the new list
/home/sympa/bin/sympa create --input_file=/home/sympa/etc/xmlfiles/listcreation_$strID.xml $strRobot

#5. make data_sources directory under the list directory structure and change it's ownership
mkdir /home/sympa/expl/$strRobot/$strListName/data_sources
chown -R sympa.sympa /home/sympa/expl/$strRobot/$strListName/data_sources

#6. copy the incl file from sysconfig directory to list directory and change ownership of list include file
cp /home/sympa/etc/data_sources/ldap2IncludeFile.incl /home/sympa/expl/$strRobot/$strListName/data_sources/ldap2IncludeFile.incl
chown -R sympa.sympa /home/sympa/expl/$strRobot/$strListName/data_sources/ldap2IncludeFile.incl

#7. Force the task manager to run in order to update the new list with the subscribers from the ldap2 include
/home/sympa/bin/sympa include --role=member $strListName@$strRobot
