### ISSUE TITLE
User menu width should adapt to its contents

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1393]
Version
-------
6.2.60

Installation method
-------------------
Debian Bullseye Package

Expected behavior
-----------------
Every entry in the user menu (the one on the top right corner) should only occupy one line, no wrap should be used for longer lines. For that, the user menu's width should automatically increase according to the menu contents.

Actual behavior
---------------
The user menu is not wide enough to accommodate long entries and some of them have to wrap their lines.

Steps to reproduce
------------------
For example, create a list in which the listmaster is a privileged user. Access to that list as the list master and open the User menu

![image](https://user-images.githubusercontent.com/6613431/166909570-9e203818-e686-48c8-b12d-8ab356560402.png)

**Comment by racke** [comment]
Or even better get rid of the information. IMHO they shouldn't appear in a menu.

**Comment by qosobrin** [comment]
> Or even better get rid of the information. IMHO they shouldn't appear in a menu.

Then both should be taken into account since there can be internationalized strings that can be too long for the menu width.

**Comment by racke** [comment]
Yes, I agree.  The question is who can fix the layout.

**Comment by ikedas** [comment]
I agree to @racke.  IMO this information may not appear in this place: It also is shown in the info page of each list.

**Comment by ikedas** [comment]
@racke's PR has been merged!
