### ISSUE TITLE
Add a link to "Lost password" in the support entry of the main menu

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1396]
Version
-------
6.2.60

Installation method
-------------------
Debian 11 package

Expected behavior
-----------------
I'd like to have an easy way for users to access the password change feature so I decided to add an entry for that in the support entry of the main menu

Actual behavior
---------------
There is no easy way for sympa users to change their passwords.

Additional information
----------------------
For that I copied `sympa_menu.tt2` file from `/usr/share/sympa/default/web_tt2` to `/etc/sympa/web_tt2` and edited it adding these lines:

```
            <li class="[% class %]">
                <a href="[% 'renewpasswd' | url_rel([escaped_init_email]) %]">[%|loc%]Lost password?[%END%]
                </a>
            </li>
```
Now I would like to change the support entry color in the main menu to a selected state when users press on the "Lost password?" menu entry. I understand that it is related to adding a block of code similar to this one but I can not figure out what the WHATEVER_THE_CONDITION should be:

```
            [% IF WHATEVER_THE_CONDITION %]
                [% SET class = 'active' %]
            [% ELSE %]
                [% SET class = '' %]
            [% END %]
```
Any ideas would be very welcome. Also. if you consider that this feature should be added to the standard release of sympa I would contribute my changes without hesitation.

Thank you very much in advance.
Best regards.

**Comment by ikedas** [comment]
> For that I copied `sympa_menu.tt2` file from `/usr/share/sympa/default/web_tt2` to `/etc/sympa/web_tt2` and edited it adding these lines:
> 
> ```
>             <li class="[% class %]">
>                 <a href="[% 'renewpasswd' | url_rel([escaped_init_email]) %]">[%|loc%]Lost password?[%END%]
>                 </a>
>             </li>
> ```

I think it'd be better to be:
``` html
            <li class="[% class %]">
                <a href="[% 'renewpasswd' | url_rel([],{email=>user.email}) %]">[%|loc%]Lost password?[%END%]
                </a>
            </li>
```

> Now I would like to change the support entry color in the main menu to a selected state when users press on the "Lost password?" menu entry. I understand that it is related to adding a block of code similar to this one but I can not figure out what the WHATEVER_THE_CONDITION should be:
> 
> ```
>             [% IF WHATEVER_THE_CONDITION %]
>                 [% SET class = 'active' %]
>             [% ELSE %]
>                 [% SET class = '' %]
>             [% END %]
> ```

It would be:
``` html
            [% IF action == 'renewpasswd' %]
                [% SET class = 'active' %]
            [% ELSE %]
                [% SET class = '' %]
            [% END %]
```
FYI: Actual values of template variables may be shown, if you are a listmaster, by clicking [Enable template variables dump] in [Listmaster admin]->[Templates].

**Comment by qosobrin** [comment]
Thank you, @ikedas for you help. I added the the code as you proposed and it worked fine.

```
            [% IF action == 'renewpasswd' %]
                [% SET class = 'active' %]
            [% ELSE %]
                [% SET class = '' %]
            [% END %]
            <li class="[% class %]">
                <a href="[% 'renewpasswd' | url_rel([],{email=>user.email}) %]">[%|loc%]Lost password?[%END%]
                </a>
            </li>
```

I'm in the process to understand the logic on how to set the background color of the word "Support" in the main menu when the user selects the "Lost password" entry in the drop down menu, but that's a matter for another support case. Meanwhile I'm closing this one.

Thank you very much.
Best regards.

**Comment by ikedas** [comment]
Thank you for your suggestive question!
