### ISSUE TITLE
sympa_newaliases.pl does not create aliases database in multidomain installation

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1399]
Version
-------
6.2.60

Installation method
-------------------
Debian Bullseye package

Expected behavior
-----------------
sympa_newaliases.pl execution should create the aliases database for the aliases file defined in every robot.conf of a multidomain installation

Actual behavior
---------------
sympa_newaliases.pl execution only creates the aliases database for the alias file defined in the sympa.conf file

Steps to reproduce
------------------
1. Configure a Sympa installation using virtual domain settings (multidomain).
2. Set a value for `sendmail_aliases` in sympa.conf for the default settings.
3. Set a different value for `sendmail_aliases` in each robot.conf file.
4. Execute `sympa_newaliases.pl`
5. An alias database file should be created for every file defined in every `sendmail_aliases` variable.

Additional information
----------------------
In my case I have the following variable definitions in:

**/etc/sympa/sympa/sympa.conf**:
```
sendmail_aliases        /etc/mail/sympa/aliases
```

**/etc/sympa/domain1.example.com/robot.conf**
```
sendmail_aliases        /etc/mail/sympa/aliases-domain1
```

**/etc/sympa/domain2.example.com/robot.conf**
```
sendmail_aliases        /etc/mail/sympa/aliases-domain2
```

When I executed `/usr/lib/sympa/bin/sympa_newaliases.pl` I expected to have these three files created:

```
/etc/mail/sympa/aliases.db
/etc/mail/sympa/aliases-domain1.db
/etc/mail/sympa/aliases-domain2.db
```

but only the first one was created. The funny thing is that, when I created a new list on any of the domains, the aliases file for that domain was correctly modified and the proper aliases database file was created.

**Comment by ikedas** [comment]
According to [the man page of sympa_newaliases](https://sympa-community.github.io/gpldoc/man/sympa_newaliases.1.html), running
``` bash
sympa_newaliases.pl --domain=domain1.example.com
```
seems referring to `sendmail_aliases` parameter in `robot.conf` for `domain1.example.com` domain.

**Comment by qosobrin** [comment]
Oh, I didn't see that coming. I tested it and it worked as expected.  Thank you very much for your help and sorry for my incompetence. I'm closing this ticket.

Best regards.
