### ISSUE TITLE
is there any script to import googlegroups to sympa ?

### ISSUE THREAD

**Issue by PhilLAL** [sympa-community/sympa#14]
It could be useful to propose a tool to import data (configuration and content) from googlegroups to a sympa server.

- Do you know if there is anything existing currently?
- If not, could it be a tool proposed with sympa?

Thank you

**Comment by ikedas** [comment]
Hi,

Google Groups itself provides no way to export content, except names and e-mails of members:
* Export a list of names and email addresses
https://support.google.com/groups/answer/60652

To export other contents, somebodies write scraping tools:
https://www.google.co.jp/search?q=scraping+Google+Groups

I have not found the tools to import content got by those tools.  I suppose you may process them by yourself to be fit for Sympa.

**Comment by PhilLAL** [comment]
I get back to let readers know that I found 2 tools (https://github.com/icy/google-group-crawler and https://github.com/himanshukhantwal/google-grp-scraper) but I finally found another solution: I have an email account which received all mails from mailing lists I want to import so I will try to use http://www.sympa.org/distribution/contrib/import_mbox.sh to import these mails

**Comment by ikedas** [comment]
This issue has not been updated anymore. Closed.
