### ISSUE TITLE
Delete alias list

### ISSUE THREAD

**Issue by abkayla** [sympa-community/sympa#1404]
I had deleted a virtual robot from my sympa server.
I had deleted the lists ,  records into database related to the robot , spool related to the robot.
I want a procedure, if it exists, to delete list aliases (postfix configuration = /etc/sympa//etc/sympa_transport , /etc/sympa/etc/transport.sympa , /etc/sympa/virtual.sympa )

My SYMPA Version is 6.2.40

Thank you for your response

**Comment by ikedas** [comment]
Hi @khaoula-abaidi , 

The manual [says](https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html) that
> By these settings, `sympa_transport` file will be updated automatically when any lists are created, closed, restored or purged.

Conversely, closing (deleting) an existing list will delete the corresponding aliases in `sympa_transport`.    However, if you deleted the list in unusual way, e.g. deleting its directory manually, the aliases will remain undeleted.

How did you deleted "a virtual robot" and the other things? Did you simply delete files, directories and rows of tables?

**Comment by ikedas** [comment]
> Then the informations into the database didn't deleted,

What weren't deleted?

> The same thing for the archives and the /etc/sympa/my_robot_for_delete directories, i had deleted them manually

I think it makes sense that they won't be deleted even if all the lists were deleted.

> But it still the aliases per each seach into my sympa_transport , transport.sympa , virtual.sympa

What lines in these files weren't deleted?

**Comment by khaoula-abaidi** [comment]
Hello,
For example, to delete a list, i used this command line  /usr/lib/sympa/bin/sympa.pl --purge_list='name_list'

All information list weren't deleted into the database (inclusion_table, exclusion_table, admin_table, stat_counter_table, etc..)
=> So i deleted, all records related to the list deleted manually from database

I deleted manually , the arc  directory list into /var/lib/sympa/arc/name_list@robot_for_delete

Now, i want to delete, all list aliases into /etc/sympa/sympa_transport : 

name_list-unsubscribe@robot_for_delete sympa:name_list-unsubscribe@robot_for_delete
name_list-owner@robot_for_delete sympabounce:name_list@robot_for_delete
name_list@drobot_for_delete sympa:name_list@robot_for_delete
name_list-request@robot_for_delete sympa:name_list-request@robot_for_delete
name_list-editor@robot_for_delete sympa:name_list-editor@robot_for_delete
#name_list-subscribe@robot_for_delete sympa:name_list-subscribe@robot_for_delete

My question is, is there an option to regenerate the aliases lists or to update them ?

Thank you for your response

**Comment by ikedas** [comment]
> Hello, For example, to delete a list, i used this command line /usr/lib/sympa/bin/sympa.pl --purge_list='name_list'
> 
> All information list weren't deleted into the database (inclusion_table, exclusion_table, admin_table, stat_counter_table, etc..) => So i deleted, all records related to the list deleted manually from database

I think some parts of things you reports can be bugs (lack of consideration on the programming) and the other parts can be expected behavior.  So I want to know what _exactly_ was not deleted on deletion (purge) of the list. --- What are "All information list weren't deleted into the database"?

> I deleted manually , the arc directory list into /var/lib/sympa/arc/name_list@robot_for_delete
> 
> Now, i want to delete, all list aliases into /etc/sympa/sympa_transport :

I think it makes sense that archives won't be deleted even if corresponding list was deleted.

> name_list-unsubscribe@robot_for_delete sympa:name_list-unsubscribe@robot_for_delete name_list-owner@robot_for_delete sympabounce:name_list@robot_for_delete name_list@drobot_for_delete sympa:name_list@robot_for_delete name_list-request@robot_for_delete sympa:name_list-request@robot_for_delete name_list-editor@robot_for_delete sympa:name_list-editor@robot_for_delete #name_list-subscribe@robot_for_delete sympa:name_list-subscribe@robot_for_delete

I think it can be  bug that these lines weren't deleted.


> My question is, is there an option to regenerate the aliases lists or to update them ?
> 
> Thank you for your response

**Comment by ikedas** [comment]
@khaoula-abaidi ,

Additionally, if possible, please show the log _from when_ you started deletion _to when_ the deletion finished?

**Comment by khaoula-abaidi** [comment]
Hi, 
When i run sudo /usr/lib/sympa/bin/sympa.pl ----purge_list="3ifa.2021@robot-domain.fr"
I get as a log : 
`

Jun  2 09:33:24 insa-sympa sympa[2289286]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=close_list;context=led.insa-lyon.fr;current_list=3ifa.2021@robot-domain.fr;mode=purge>
Jun  2 09:33:24 insa-sympa sympa[2289286]: info Sympa::Request::Handler::close_list::_twist() The list Sympa::List <3ifa.2021@robot-domain.fr> is purged
`
The result : 
close_list is OK
- list is deleted 
- into database (list isn't exist into list_table but it exists in all other tables and also its aliases)

**Comment by ikedas** [comment]
Thanks for information!

If possible, additionally could you try below?
  - create a new list and check what entries in aliases file and what rows in database tables are created.
  - then delete (purge) that list and check whethere things above will be deleted or not.

Also, please check the log during the process above.

**Comment by khaoula-abaidi** [comment]
Hello,
I did what you told me: 
- create a list (test-list-purge-alias@mydomain.fr)
Result : aliases are created and all records related to the database into + admin_table, list_table and stat_table


sympa_transport:test-list-purge-alias@mydomain.fr sympa:test-list-purge-alias@mydomain.fr
sympa_transport:test-list-purge-alias-request@mydomain.fr sympa:test-list-purge-alias-request@mydomain.fr
sympa_transport:test-list-purge-alias-editor@mydomain.fr sympa:test-list-purge-alias-editor@mydomain.fr
sympa_transport:#test-list-purge-alias-subscribe@mydomain.fr sympa:test-list-purge-alias-subscribe@mydomain.fr
sympa_transport:test-list-purge-alias-unsubscribe@mydomain.fr sympa:test-list-purge-alias-unsubscribe@mydomain.fr
sympa_transport:test-list-purge-alias-owner@mydomain.fr sympabounce:test-list-purge-alias@mydomain.fr

- then purge it (sudo /usr/lib/sympa/bin/sympa.pl --purge_list="test-list-purge-alias")
=> Result : the list is purged with all records related and the aliases. 

Note : i did not use the list for sending mails, add members , exclude members ....

Do you think my aliases problem is related to something that i did forgot ? or its related to list use ? 

Thanks for your response

**Comment by ikedas** [comment]
I have no idea just now... Can you find any difference between both of list?
For now all I can say is that, for a while, it would be good to keep an eye on what happens when you create or delete lists.
