### ISSUE TITLE
The owner sees the pop-up stating a message is waiting for moderation even if moderators are defined separately

### ISSUE THREAD

**Issue by tmclaren** [sympa-community/sympa#1406]
6.2.68
-------

Installation method
-------------------
Cent7, mariadb, postfix, rpm

Expected behavior
-----------------
The left menu should reflect a message is waiting for moderation (Moderate > Message (N)).  

Actual behavior
---------------
The web UI reflects a popup window stating a message is awaiting moderation but the left menu is blank and does NOT reflect a Message is awaiting moderation.     I also noticed the 'Message (0)' is missing after one changes the 'who can send message' to a moderated scenari.  See the attached screen shots.

Steps to reproduce
------------------
1. create a new list, note the left menu reflects Moderate with three options (Messages, Subscriptions, Unsubscriptions)
2. change the list to a moderate 'who can send messages' scenario.   
3. send an email to the new list address
4. log into web ui, goto the list home page and a popup display stating there is a message awaiting moderation. 
5. click on the Moderate option in the left menu.  The left menu only displays (Subscriptions, Unsubscriptions) and the Messages option is missing.

Additional information
----------------------
The functionality of a Moderated works as designed but the Web UI does not.   
<img width="1090" alt="sympa 6 2 moderate UI w-messages" src="https://user-images.githubusercontent.com/3075370/170515858-bed12fec-db26-4176-ad50-773533e3370e.png">
This image shows the Moderate > Message () UI in left menu.

-------------
<img width="1286" alt="6 2 moderated message UI bug" src="https://user-images.githubusercontent.com/3075370/170515826-27ec8fe5-e9c6-4a28-990b-8da07f3a1156.png">
This image shows the Moderate > Message UI is missing from the left menu.  The 'who can send message' scenari is "Private, moderate for non subscribers.

---- scenario -----
title.gettext Private, moderated for non subscribers

is_subscriber([listname],[sender]) smtp,dkim,md5,smime    -> do_it
is_editor([listname],[sender])     smtp,dkim,md5,smime    -> do_it
true()                             smtp,dkim,md5,smime    -> editorkey

**Comment by ikedas** [comment]
Hi @tmclaren ,

If the moderator is designated separately from the owner (i.e. the second image), moderation of the messages is not the owner's job.  Otherwise (i.e. the first image), the owner doubles as moderator.  It looks making sense for me that "Message" link is not shown in the second image.

**Comment by tmclaren** [comment]
The display is inconsistent since the owner is the 'default' moderator if no moderators are defined.   When a moderator is defined the owner still sees the inline pop-up dialog box stating a message is waiting for moderation.  However, the left Moderate > messages is missing.     Since the owner is still authorized to moderate a message via the pop-up link I recommend the Moderate > message link also get displayed to keep the UX consistent between owners and moderators.   

Attached is a screen shot of what a privileged owner sees when they go to their list's home page.  They get a pop-up but no Moderate > message in left menu.

<img width="1288" alt="6 2 moderator - owner vs  moderator Web UI" src="https://user-images.githubusercontent.com/3075370/170703062-2838db90-c318-41eb-b7d1-35ffa70a48c8.png">

**Comment by ikedas** [comment]
I see. I understand that the owner who does not double moderator should not see the pop-up about "message(s) awiting moderation", as they does not see about such messages in the side menu.  Do you agree?

**Comment by tmclaren** [comment]
Since the owner is responsible for the list, they should have access rights and privileges for all aspects of the mail list.  Ultimately, the owner is the moderator when no moderators are defined.   Looking at it from a Prof / TA (teaching assistants) perspective, the Prof (privileged owner) will check on the TA's (moderators) to make sure they are moderating email from the class list so need to be able to see the moderation events even though they assigned TAs to do the review the inbound email.   This is especially true during semester breaks, when TAs are off and the Prof takes moderation responsibility; they need to be able to see the events in order to moderate the inbound email without removing the TAs from the moderator list.

**Comment by ikedas** [comment]
> Since the owner is responsible for the list, they should have access rights and privileges for all aspects of the mail list.  Ultimately, the owner is the moderator when no moderators are defined. 

I agree.  But, in fact ---
  1. Only (privileged) owners can designate the moderators.  In other words, the owner can delegate moderator privileges to the other user(s).
  2. Moreover, owner can disignate _themselves_ as the moderator.  In othere words, the owner can exercise the moderator's privileges whenever they like.
  3. The third case is when there are no moderators. In this case, the owner literally has moderator privileges.

> Looking at it from a Prof / TA (teaching assistants) perspective, the Prof (privileged owner) will check on the TA's (moderators) to make sure they are moderating email from the class list so they need to be able to see the moderation events even though they assigned TAs to do the review the inbound email. This is especially true during semester breaks, when TAs are off and the Prof takes moderation responsibility; they need to be able to see the events in order to moderate the inbound email without removing the TAs from the moderator list.

According to my description above, I think prof may designate TAs (case 1.), and also designate prof by their own (case 2.), as moderators.

In general, the possible configuration options the owner may want to adopt are:
  * case1 only --- any owners are _not_  moderators, and there are some moderators. 
  * both case 1 & 2 --- owners are also moderators, and there are some more moderators. 
  * case 3 --- all owners are also moderators.

I think your proposal does not address owners who need case 1 only.
