### ISSUE TITLE
Unable to set priviledged owner via GUI after 6.2.68 update

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#1408]
Version
-------
v6.2.68

Installation method
-------------------

installed via sympa-ja.org.rhel.repo

Expected behavior
-----------------

When selecting "privileged owner" tick box and adding an owner, the added user become a privileged owner. This was working on v6.2.64 before the latest update

Actual behavior
---------------

When selecting "privileged owner" tick box and adding an owner, the user is added as owner, but not a privileged one.

Steps to reproduce
------------------

Select "privileged owner" when adding a new owner.

Additional information
----------------------

Apache error logs indicate the following:
```
[Wed Jun 01 16:38:45 2022] [error] [pid 30077] mod_proxy_fcgi.c(851): [client x.x.x.x:45882 AH01071: Got error 'Use of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 503.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse '
[Wed Jun 01 16:38:45 2022] [error] [pid 30077] mod_proxy_fcgi.c(851): [client x.x.x.x:45882 AH01071: Got error 'of uninitialized value in pattern match (m//) at /usr/share/sympa/lib/Sympa/Config.pm line 533.\nUse of uninitialized value $owner_domain in concatenation (.) or string at /usr/share/sympa/lib/Sympa/List/Users.pm line 66.\nUse of uninitialized value $owner_domain in pattern match (m//) at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.\n'
```
Any pointers welcome. Until this issue is resolved, is there an alternative way of adding a privileged user? Via CLI for example?

Thanks for your help.

Kind regards,

 Chris

**Comment by laerm** [comment]
Thank you @ikedas, the patch works and I'm able to add privileged owners again. However, I'm still getting the errors in the Apache log concerning uninitialized values. Do you want me to open another issue?

**Comment by ikedas** [comment]
How about posting the report on #1325 ?

**Comment by laerm** [comment]
Oops, I'd already posted an error there but had forgotten. Thanks again for your tireless work!
