### ISSUE TITLE
"Use of uninitialized value in concatenation" apache error during user search

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1414]
Version
-------
6.2.60

Installation method
-------------------
Debian 11 (Bullseye) Package

Expected behavior
-----------------
When I login as an listmaster and do a user search I get the correct results.

Actual behavior
---------------
When I login as an listmaster and do a user search I get the correct results but an error comes up in apache logs. 

```
[Fri Jun 10 10:01:20.138070 2022] [proxy_fcgi:error] [pid 70601:tid 140264135964416] [client 192.168.23.18:58413] AH01071: Got error [Fri Jun 10 10:01:20 2022] wwsympa.fcgi: Use of uninitialized value in concatenation (.) or string at /usr/share/sympa/default/web_tt2/search_user.tt2 line 48.\n', referer: http://sympa-prepro.domain.com/wws/serveradmin/users
```

Steps to reproduce
------------------
Login to sympa as as listmaster
Click on "Listmaster Admin"
Click on "Users"
Perform an user search
Check apache error log for this entry

Additional information
----------------------
There is a Debian bug report for this error since April 2017 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860807).  This error was already present in 6.2.16 (from Debian Stretch) as you can see from my production server here:

```
[Fri Jun 10 10:26:35.993510 2022] [fcgid:warn] [pid 20534:tid 140205113669376] [client 192.168.23.18:59243] mod_fcgid: stderr: [Fri Jun 10 10:26:35 2022] wwsympa.fcgi: Use of uninitialized value in concatenation (.) or string at /usr/share/sympa/default/web_tt2/search_user.tt2 line 42., referer: https://sympa.domain.com/wws/serveradmin/users
``` 

The issue is related to this line in `web_tt2/search_user.tt2`

`[%|optdesc('reception')%][% l.value.reception %][% END %]`

that I believe is trying to output an empty string. Changing it to:

`[% IF l.value.reception %][%|optdesc('reception')%][% l.value.reception %][% END %] [% END %]`

solves the problem. I haven't done further testing if my solution breaks any other thing but I guess it should be safe. I let you evaluate it.

**Comment by ikedas** [comment]
@qosobrin , thank you for reporting.
I'm sorry but would you please re-post this report to #1325 ?  Sorry for the hassle.
