### ISSUE TITLE
[CLI] Site '*' argument fails when a command has both site|domain and domain* argument

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa#1419]
Version
-------
Latest HEAD revision

Installation method
-------------------
Installation from the sources

Expected behavior
-----------------
running `sympa make_alias_file '*'` should output the Sympa aliases in a temporary file.

Actual behavior
---------------
The temporary file is created but it is empty and we find logs : 'Robot * undefined; no /usr/local/sympa/etc/* directory'.
This is due to the fact that '*' is considered a robot argument.

Steps to reproduce
------------------
Run `sympa make_alias_file '*'`
Output: `Sympa aliases file /var/spool/sympa/tmp/sympa_aliases.25018 was made.  You probably need to install it in your SMTP engine.`

Additional information
----------------------
[EDIT: Changing last comment: what happens after the arguments parsing is due to my setup, not Sympa, but the argument parsing problems still stands]
The following PR could fix the problem:
https://github.com/sympa-community/sympa/pull/1418

This does not fix the make_alias_file problem: I still find an empty alias file BUT is is due to my alias manager, not to the argument parsing.

**Comment by ikedas** [comment]
> The temporary file is created but it is empty and we find logs : 'Robot * undefined; no /usr/local/sympa/etc/* directory'. This is due to the fact that '*' is considered a robot argument.

No.  It is not considered a domain parameter (See the [code](https://github.com/sympa-community/sympa/blob/545bc3ac3638feda16e8b213eddfa0de81788a8b/src/lib/Conf.pm#L769-L775)).

----
Besides please show us the `accurate` information:
* Instead of "Latest HEAD revision" actual hash you pulled; 
* Minimum set of configuration parameters required to reproduce the phenomenon.

**Comment by dverdin** [comment]
Sorry, I was not accurate: '*' is considered a robot argument _by CLI.pm_, not by conf.pm.

[In this part of the code](https://github.com/sympa-community/sympa/blob/545bc3ac3638feda16e8b213eddfa0de81788a8b/src/lib/Sympa/CLI.pm#L180-L183), if the command accepts 'domain*' as __second argument__ (as, in our case, [here](https://github.com/sympa-community/sympa/blob/545bc3ac3638feda16e8b213eddfa0de81788a8b/src/lib/Sympa/CLI/make_alias_file.pm#L36)) any character string given as argument is considered a robot name.

The actual hash I used is 657e10b7a851ca50579dd0760cc7f373637630f4

Configuration has no effect here, as far as I understand the problem. This is simply an argument parsing effect.

**Comment by ikedas** [comment]
> EDIT: The file is empty if I use a custom alias manager. the file does not come empty with the basic alias manager. So it just gives an error in the logs but the generation succeeds.

OK.  This issue and the PR you submitted are closed.

**Comment by dverdin** [comment]
Consequently to my previous edit, this is not really a problem. Just noise in the logs.
I'll close the issue.
