### ISSUE TITLE
[CLI] -f|--config option ignored

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa#1420]
Version
-------
Sympa 6.2.68, hash 657e10b7a851ca50579dd0760cc7f373637630f4

Installation method
-------------------
Install from the sources using the follwing commands:
```
apt install autoconf -y
automake --add-missing
autoconf
autoreconf -i

apt install gettext -y
./configure --prefix /usr/local/sympa/ --with-lockdir=/var/lock --without-initdir --with-unitsdir=/lib/systemd/system --with-spooldir=/var/spool/sympa --with-expldir /var/lib/sympa/list_data/
make
make install
cpanm --installdeps --with-recommends .
/usr/local/sympa/bin/sympa --upgrade

systemctl daemon-reload
systemctl restart sympa
systemctl restart wwsympa
systemctl restart sympasoap
```

Expected behavior
-----------------
First of all, I don't want to be a hassle. I'm just trying to install the stabilization branch in production so I am testing it.

Just a bit of context: We use a custom alias manager script, because we store aliases in three different places: locally, in an LDAP directory and in a shared adress book.

I need a way to call this custom alias manager on a whole domain when migrating existing domain to our infrastructure, in order to batch create the aliases in the three places.

I understand now that `/usr/local/sympa/bin/sympa make_alias_file "*"` creates local aliases only. Is the alias_manager is of type External, it is ignored. That makes sense considering the name of the command.

Consequently, I am writing a custom script that is based on local aliases: I use the make_alias_file command to create all local aliases, then parse this file to call our custom alias manager for each address, in order to store them in the LDAP and the address book.

Problem: our sympa.conf uses our custom script as value for alias_manager parameter. I I use this file, local aliase won't be created because they are not the default alias manager. So I created a dummy config file (`/etc/sympa/sympa-aliasmanager.conf`) for calling make_alias_manager with the default alias manager.

While running the following command:
`/usr/local/sympa/bin/sympa make_alias_file "*" -f /etc/sympa/sympa-aliasmanager.conf`

Sympa should use my custom config file and create local aliases.

Actual behavior
---------------
Sympa still uses the default configuration file.

Steps to reproduce
------------------
  - Create two config files. `sympa.conf` with a custom script for the alias_manager parameter, and `sympa-aliasmanager.conf` without value for alias_manager.
  - run `/usr/local/sympa/bin/sympa make_alias_file "*"` : no alias file is created because sympa.conf does not use the default alias_manager.
  - run `/usr/local/sympa/bin/sympa make_alias_file "*" -f /etc/sympa/sympa-aliasmanager.conf` : same result.

Additional information
----------------------
In the `arrange` sub of Sympa::CLI, `Conf::load` is called two times. Only the first one uses the `$options{config}` value.
Adding this parameter to `Conf::load` fixes the problem.
That's what I did in the associated PR #1421

**Comment by racke** [comment]
In a situation like that, I would write a custom script loading Sympa  modules and configuration. This is fairly easy and saves you from the constraints of the Sympa CLI.

**Comment by dverdin** [comment]
Yes, it would probably be cleaner than having this dummy config file.
However, the CLI is pretty useful because all the Sympa logic is in there. For example, I won't be creating aliases for closed or error config list.
In comparison, the script that fills the gap with my needs is very short.

**Comment by ikedas** [comment]
Congratulations, you stumbled upon a bug that has been preserved for many years. I'll merge the pr later.
Please close this Issue, when you will be done discussing alias management innovations that are not related to the bug.

**Comment by dverdin** [comment]
Thank you Soji.
