### ISSUE TITLE
Deprecate conf_2_db feature

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#1424]
Expected Behavior
-----------------

The feature to save configuration into database table should be deprecated.

Current Behavior
----------------

There are two use cases:

  * Content of `sympa.conf` and/or `robot.conf` may be imported into `conf_table` in database with `sympa.pl --conf_2_db`, and they may override default values of configuration.
    However, configuration in database affects only `sympa_msg.pl` and `sympa_automatic.pl` daemons and `sympa.pl` command line utility.  The other daemons and most of command line tools seem not affected. 

  * Color setting (`color_*` parameters) on web UI are saved into `conf_table`, and they override configuration in each `robot.conf`.
    These settings are shared by possible multiple FastCGI servers through the database.

Possible Solution
-----------------

  * [x] Deprecate `conf_2_db` feature to import configuration into database table.
  * [x] ~~The setting imported into database should be exported to the configuration files during upgrade process.~~
  * [x] Color setting will be kept in the database.

[EDIT] It turned out that this feature has not dealt with the parameters other than CSS colors, so exporting parameters to the configuration files is unnecessary.

Context
-------

This feature was introduced in Sympa 6.1.  cf. [the initial commit](/sympa-community/historic-sympa/commit/2f6f8df0a618ed61bcd0a3e541e0f37b1a51c503).

Probably it has been rarely used, except for color settings.

Deprecating this, configuration will be independent from database.  It will make the code simpler.

**Comment by racke** [comment]
Sounds good to me :+1:

**Comment by racke** [comment]
Yes that makes sense to me.
