### ISSUE TITLE
Logs reflect Failure when include from SQL is carried out during nosync_time_ranges

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1429]
Version
-------
6.2.60

Installation method
-------------------
Debian Bullseye Package

Expected behavior
-----------------
We have plenty of lists with subscribers defined in a SQL external database; all these definitions contain nosync_time_ranges. In my understanding, inclusion of subscribers should not be even started during this periods and logs should not collect any entry related to this. But if the desing of sympa does not allow to prevent this inclusion from being started and logs to be collected, then logs should not reflect a Failure since this is not a failure in the process but an regular behaviour. 

Actual behavior
---------------
Logging collects entries like this one:

```
Jun 22 07:05:41 hostname task_manager[1210995]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=list_name@domain.com;role=member>: Failure, 0 added, 720 held, 0 updated
```

Steps to reproduce
------------------
Define an include_sql_query with nosync_time_ranges.

```
include_sql_query
name students
db_name expxcm-dsn
db_type ODBC
db_passwd PASSWORD
nosync_time_ranges 06:30-07:45
sql_query SELECT email FROM table WHERE role = 1
db_user USERNAME
```

**Comment by ikedas** [comment]
Hi @qosobrin ,

The section "Steps to reproduce" should contain enough necessary and sufficient information to make the reader actually reproducing it.  For example, please show us the lines you actually added to the configuration file.

**Comment by qosobrin** [comment]
> Hi @qosobrin ,
> 
> The section "Steps to reproduce" should contain enough necessary and sufficient information to make the reader actually reproducing it. For example, please show us the lines you actually added to the configuration file.

OK, @ikedas. I've just corrected my mistake.

**Comment by ikedas** [comment]
@qosobrin , if possible, could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1431.patch) and check if the problem will be solved?

**Comment by qosobrin** [comment]
> @qosobrin , if possible, could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1431.patch) and check if the problem will be solved?

Sorry, @ikedas. I've been busy lately at work and had no time to check github. I will let you know as soon as I try your patch. Thank you very much. Best regards.

**Comment by ikedas** [comment]
I see. I'll merge my patch for now. If you notice any problems, please report them again.

Thank you for reporting bug!

**Comment by qosobrin** [comment]
Sorry for the delay, @ikedas I have just tested the patch and it worked as expected:

`Nov 23 10:17:34 hostname task_manager[2795]: info Sympa::Request::Handler::include::_twist() : Skipped`

Thank you very much for your work.
Best regards.

**Comment by ikedas** [comment]
@qosobrin , thank you for confirming bug fix!
