### ISSUE TITLE
Broken links on `sympa-users` mailing list page

### ISSUE THREAD

**Issue by fingolfin** [sympa-community/sympa#1430]
Apologies if this is not the right place to report it, but: on <https://listes.renater.fr/sympa/info/sympa-users> the text says:
> Please check documentation and FAQ for your problem

with "documentation" and "FAQ" supposedly links -- except the `<a>` tags are missing an href attribute, so these links don't work.

**Comment by dverdin** [comment]
Woopsie, sorry.
I set the parameter to allow github URL.
