### ISSUE TITLE
Privileged owner should be ale to add another privileged owner

### ISSUE THREAD

**Issue by SansPseudoFix** [sympa-community/sympa#144]
Hi,
right now, sympa doesn't allow this, as mentioned [here:](https://www.sympa.org/manual_6.2/list-creation#list_editing)

> privileged owners can change owners' emails, but they cannot grant the responsibility of list management to others without referring to the listmaster. 

Is there any plan to do it? As listmaster can do it, why not privileged owners?

BTW: thanks for your software :)

**Comment by ikedas** [comment]
@SansPseudoFix, what version of Sympa you are using?

**Comment by SansPseudoFix** [comment]
Oh, yep, sorry: 6.2.16.

**Comment by ikedas** [comment]
And if you customized `edit_list.conf`, please show it (at least the part about `owner` parameter).

**Comment by ldidry** [comment]
We (I work with @SansPseudoFix) have this:
```
owner               owner                     read
owner               privileged_owner          write
owner.profile       owner,privileged_owner    read
owner.info          owner                     hidden

owner_include       owner                     read
```

**Comment by ikedas** [comment]
Can you try this?
```
...
owner.profile       owner    read
owner.profile       privileged_owner    write
...
```

**Comment by ikedas** [comment]
Hey, does your problem solved?

**Comment by SansPseudoFix** [comment]
> Hey, does your problem solved?

Yes, sorry! It did the trick! Thank you and sorry for the delay.

**Comment by okainov** [comment]
It should be available out-of-the-box, why this issue is closed?
