### ISSUE TITLE
The default_ttl parameter is no longer used in Sympa 6.2.22

### ISSUE THREAD

**Issue by aepli** [sympa-community/sympa#145]
Hello,

The **default_ttl** parameter in the /etc/sympa/sympa.conf configuration file is not used as the default value for the **Inclusion timeout** (ttl) parameter of a list.

The default value of the **ttl** parameter remains at **3600** seconds.

Comparing between 6.1.17 and 6.2.22, I noticed that the definition of the ttl parameter has changed.

With the 6.1.17 in the List.pm library, we had:

#### List.pm
```
'ttl' => {'format' => '\d+',
          'length' => 6,
          'gettext_unit' => 'seconds',
          'default' => {'conf' => 'default_ttl'},
          'gettext_id' => "Inclusions timeout",
          'group' => 'data_source'
          },
```

With the 6.2.22 in the ListDef.pm library, we have:

#### ListDef.pm
```
'ttl' => {
    order          => 60.12,
    'group'        => 'data_source',
    'gettext_id'   => "Inclusions timeout",
    'gettext_comment' =>
        'Sympa caches user data extracted using the include parameter. Their TTL (time-to-live) within Sympa can be controlled using this parameter. The default value is 3600',
    'gettext_unit' => 'seconds',
    'format'       => '\d+',
    'default'      => 3600,
    'length'       => 6
},
```

As you can see on the 6.2.22 there isn't anymore the reference "default_ttl" in the key "default".

Regards.

_Debian 9.2
Perl 5.24.1
exim4 4.89
mariadb 15.1
apache2 2.4.25
sympa 6.2.22_

**Comment by ikedas** [comment]
Hi @aepli,

I found these `default_*` parameters has been unused in trunk before 6.2alpha. There seem no reason.  if it is useful, I feel `ttl` may be restored.

**Comment by ikedas** [comment]
There seem significant problem restoring this parameter, and I’ll restore it.
