### ISSUE TITLE
How to force stats file production in list directory

### ISSUE THREAD

**Issue by b3** [sympa-community/sympa#1451]
Version
-------
6.2.60~dfsg-4 on Debian bullseye (11.4)

Installation method
-------------------
apt install inside a docker image

Expected behavior
-----------------
As stated in [doc](https://sympa-community.github.io/manual/customize/basics-list-config.html#other-files) stats file should be present in each list directory.

Actual behavior
---------------
File is absent.

Additional information
----------------------
Sympa is working correctly.

**Comment by ikedas** [comment]
Among the files under the list directory, described in [doc](https://sympa-community.github.io/manual/customize/basics-list-config.html), only the `config` file always exists.  The others may not necesarily exist.

In case of the `stats` file, it is created at the time of the first message delivery through the list.

**Comment by b3** [comment]
Thank's.
Any idea where this may be documented ?
Is there any way to force the `stats` file creation based on archive for instance (I just migrated our data from one instances to another conserving all archives through arctxt directory copy and a `sympa --rebuildarc` call) ?

**Comment by ikedas** [comment]
Documentation is good idea.  Could you please [propose](https://github.com/sympa-community/sympa-community.github.io/issues) it?

I cannot figure out what you mean.  If a list has archives, as any messages have been delivered, it should already have `stats` file.

**Comment by b3** [comment]
> I cannot figure out what you mean. If a list has archives, as any messages have been delivered, it should already have `stats` file.

The fact is that as we migrated the installation to a new host, in order to conserve the archives we:

1. recreate all lists with same name and config
2. copy all list archives directoryt (arctxt)
3. call `sympa --rebuildarc`

**Comment by ikedas** [comment]
> 1. recreate all lists with same name and config

After this, you may also copy the `stats` files in the directory of old lists to the new one.

There can be some other files to be migrated.  See "[Configuration for each list](https://www.sympa.community/manual/customize/basics-list-config.html)".

See also "[Moving to another server](https://www.sympa.community/manual/upgrade/move.html)" to know general steps upgrading and moving to another server at the same time.
