### ISSUE TITLE
Subscribe page doesn't work on Firefox on iPhone

### ISSUE THREAD

**Issue by rwiltfon** [sympa-community/sympa#1458]
When going to a subscribe link using Firefox on iPhone (iOS 15.6), (i.e. https://lists.physics.illinois.edu/lists/subscribe/[name of list]), you can enter your email and name, but clicking the "You've been subscribed to list [list name]" button, nothing happens.  There's no error message but you don't get subscribed either.

Version
-------

Sympa 6.2.68

Installation method
-------------------

installed by Tech Services at Illinois

Expected behavior
-----------------

Clicking the subscribe button should subscribe a person to the list.  The name of the button seems weird too - why does it say I've been subscribed before I click subscribe?

Actual behavior
---------------

When clicking on the "You've been subscribed to list [list name]" button, nothing happens.

Steps to reproduce
------------------

Go to https://lists.physics.illinois.edu/lists/subscribe/labescape-c2e2-waitlist and see if you can subscribe, while on a phone.  Other users had similar issues, but I'm not sure what kinds of phones they had, or which browsers they were using.

Additional information
----------------------

**Comment by racke** [comment]
Yes, the text is indeed confusing. Also it doesn't show an error when an invalid email is entered (tested on my own 6.2.68 instance).

**Comment by ikedas** [comment]
Hi @rwiltfon ,

I couldn’t reproduce the problem.  The text I see is “I subscribe to list [list]”.

Could you please show us what you see, i.e. screen shot?

**Comment by ikedas** [comment]
Hi @rwiltfon  again,

First, please contact Tech Services at Illinois. They appear to have customized Sympa they installed.

This issue is closed since it cannot be solved on the development side.

**Comment by AskFeeds** [comment]
I am a French teacher who give to my students their first course in Computer Science, which include learning Caml (as the first language).
I give them strong advice to offer a entry-level friendly client that senior citizens like me can use it more easily. Sympa failed to work on my iPhone 7P ([iOS 15.6](https://www.minicreo.com/iphone-problems/ios-14-problems.html)). wait for a fix though.

**Comment by ikedas** [comment]
Hi @AskFeeds , 
Your report is not clear enough and we cannot help you.
Could you please [submit a new issue](https://github.com/sympa-community/sympa/issues/new/choose)?

**Comment by racke** [comment]
> Hi @rwiltfon again,
> 
> First, please contact Tech Services at Illinois. They appear to have customized Sympa they installed.
> 
> This issue is closed since it cannot be solved on the development side.

I don't think so. On my Sympa test instance (more or less running current code >= 6.2.68) I also the see that text:

![Screenshot 2022-08-12 at 08-40-18 a03a17db-ed2e-50ef-a4d5-85852ee8fdda - Test list - subscribe](https://user-images.githubusercontent.com/143678/184298972-2002e3f7-daa3-48c3-ae89-eb3422ffaf05.png)

Subscribe scenario is "open".

**Comment by ikedas** [comment]
In your screen shot, the text in the button is "**I subscribe to list [list name]**".   It's normal behavior.

The problem is that it is "**You've been subscribed to list [list name]**".  Here is the actual screen shot

![image](https://user-images.githubusercontent.com/5743546/184300297-cc4fa9d1-d6ad-4978-9bf6-aaa226b73c95.png)

**Comment by racke** [comment]
OK you are right. But the original text and the form usage are still suboptimal. Will open a new ticket for that.

**Comment by rwiltfon** [comment]
Thanks @racke, I did open up a ticket with Tech Services, they are looking into the issue of it not working on a phone here at Illinois.  Although I would like to say again, the wording of the button is weird.  If the page is smart enough to know if the email address is already subscribed (like on a blur event or something) and it checked using Ajax or Javascript then I could see that wording being helpful.  But if that page isn't going to do all that work, can we rename the button to just Subscribe, or Subscribe to list [list name]? Or is there another ticket open for that?

**Comment by ikedas** [comment]
No.  Vanilla Sympa does not use dynamic feature like Ajax for that button, nor does it output the reported text "You'd ...".  The reported behavior is likely the result of customization by Tech Services at Illinois.

**Comment by tmclaren** [comment]
We are reviewing the changes we've made for accessibility to debug this issue.  I also submitted an enhancement request to improve accessibility, https://github.com/sympa-community/sympa/issues/1460.
