### ISSUE TITLE
Translation of two strings containing the string '%s help'

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1461]
I am taking care of the translations of sympa into Spanish and Galician and today @ikedas proposed a change in the translation of these two strings:

See '%s help' to know available commands
See '%s help %s'

@ikedas suggested keeping the text between quotation marks as they were ('%s help' and '%s help %s'), removing the translation of the word "help" into Spanish and Galician.  I am opening this question here in order to know if there it is OK to change these strings or they should be kept in their original form because they has a special meaning or usage within the user interface.

Best regards.

**Comment by ikedas** [comment]
Hi @qosobrin ,

Format of Sympa's command line interface is changing now (see also #1303).  The message in question is used to help users correct their errors, like:
```
$ sympa review --coffee
Unknown option: coffee
See 'sympa help review'
$ sympa help coffee
Unknown command 'coffee'
See 'sympa help' to know available commands
$ 
```

**Comment by qosobrin** [comment]
Thank you for your clarifications, @ikedas, I have just left them the way you said. I would appreciate it very much if you could delete the suggestions you made in the translation platform both for the Spanish and the Galician translations regarding these two strings.

You can close this issue whenever you want.

Regards.

**Comment by ikedas** [comment]
@qosobrin , I removed my suggestions.  Thanks for the good question!
