### ISSUE TITLE
Unable to use "First Login" link on lists.sympa.community

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#1464]
Sorry if this isn't the right place to report this. I was debating whether to just email listmaster@lists.sympa.community, or Soji directly.

If I attempt to create a new password on the new Sympa lists site using: https://lists.sympa.community/firstpasswd it sends me an email with a link. If I click on that link I am told:

>Sorry, this operation can't be performed
>A validation link was sent to you on 17 Aug 2022 at 05:48:58. (the validation link was requested from host 131.111.184.4)
>reason
>The validation link has already been validated from host 20.49.151.171. If you did not perform this validation, please report this confidentiality issue to your mail services administrator. 

20.49.151.171 appears to be Azure/Microsoft. The actual IP address changes each time that I create a new "firstpasswd" email, but it always seems to be associated with Azure/Microsoft.

**Comment by racke** [comment]
It works for me.

**Comment by dpc22** [comment]
Just had a lightbulb moment. This will be the ever so helpful "safelinks" feature of Exchange Online.

The link that I clicked on in Thunderbird looks something like:

https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Flists.sympa.community%2Fticket%2F...

I need to find the raw link before Exchange Online gets it grubby paws on it. Sorry about the noise.

**Comment by ikedas** [comment]
Once a one-time-ticket URL (the URL in the form $wwsympa_url/ticket/XXXXXXXX) is accessed from an IP address, it cannot be accessed from any other IP address.
(It does not matter if the IP address is different from the IP address that first accessed the "first login" link.)

You may have already accessed that URL.  Or, some mail readers try to "read ahead" the link in the text when the body of the message is displayed; Please try opening the notification message with another mailer.

---
N.B. The one-time ticket feature should be deprecated (see #156), but it is still used for the password (re)setting.
