### ISSUE TITLE
Send mail stuck in queue

### ISSUE THREAD

**Issue by IzxxY** [sympa-community/sympa#1468]
Hi,
So i recently upgraded my sympa server from 6.2.62 to 6.2.68.
After the upgrade, some email got stuck in the queue /appli/sympa/sympa_prod/sympa/spool/msg/

I figured out why i couldn't send email to a mailling list.

But some email are still stuck in queue.

Do you know any command that i could use to send those email stuck there ?

Thank you !

**Comment by ikedas** [comment]
Hi @IzxxY ,
This question is difficult to answer due to lack of information.

Please  try:
  1. Press the [New issue] button above,
  2. select [Get started] in the right of [Question],
  3. follow the instructions to fill out your question
  4. and submit it again.
