### ISSUE TITLE
Mail stuck in queue 

### ISSUE THREAD

**Issue by IzxxY** [sympa-community/sympa#1469]
Version
-------

6.2.68

Installation method
-------------------

Migration from 6.2.62 to 6.2.68

Expected behavior
-----------------

mails should not being stuck in queue

Actual behavior
---------------

Some mails while migration got stuck in the queue.

When i was upgrading my sympa server from 6.2.62 to 6.2.68, some mails got stuck in sympa's queue. It's been 2 days and they are still stuck in the folder /appli/sympa/sympa_6.2.68/sympa/spool/msg/.

How can i force sympa to send these email ? Is there any ways ?
![Capture d’écran de 2022-08-24 09-10-18](https://user-images.githubusercontent.com/20505814/186275197-fd831446-e98a-43d1-8d5e-aac44831e428.png)

----------------------

**Comment by ikedas** [comment]
Hi @IzxxY ,

1. Could you please show the configuration of Sympa, MTA and web server?
     - For Sympa: content of `sympa.conf` file (sensitive information like db password should be masked).
     - For MTA: All settings related to Sympa.
     - For web server: All settings related to Sympa.
2. How you saved these mails into `msg` directory? 
   Please let us know the actual steps to do so.

**Comment by IzxxY** [comment]
I forgot to specify that once sympa, postfix and apache well configured, everything worked.

But the problem is that before I can properly configure my server, I have some mails that have been blocked in the queue.

Sending mail to sympa lists works very well.

2. To answer this question, I didn't save them by myself. After analyzing their content, I realized that these are the emails that were sent before I completely finished my sympa configuration

**Comment by ikedas** [comment]
You should correct unsafe permission of files and directories including spools.

The easiest way is removing all of installation of Sympa and installing again (**Note** that you must backup config, list data, archives, spools in advance).

As a result, content of `msg` spool have to have permission as below:

``` bash
# ls -la /appli/sympa/sympa_6.2.68/sympa/spool/msg/
total NN
drwxr-x--- NN sympa sympa  NN MMM DD HH:MM .
drwxr-xr-x NN sympa sympa  NN MMM DD HH:MM ..
drwxr-x---  N sympa sympa  NN MMM DD HH:MM bad
-rw-------  1 sympa sympa  NN MMM DD HH:MM LISTNAME@DOMAIN.nnnnnnnnnn.nnnnn
> I forgot to specify that once sympa, postfix and apache well configured, everything worked.
> 
> But the problem is that before I can properly configure my server, I have some mails that have been blocked in the queue.
> 
> Sending mail to sympa lists works very well.
> 
> 2. To answer this question, I didn't save them by myself. After analyzing their content, I realized that these are the emails that were sent before I completely finished my sympa configuration

You should correct unsafe permission of files and directories including spools.

The easiest way is removing all of installation of Sympa and installing again (**Note** that you must backup config, list data, archives, spools in advance).

As a result, contents of `msg` spool have to have permission as below:

``` bash
# ls -la /appli/sympa/sympa_6.2.68/sympa/spool/msg/
total NN
drwxr-x--- NN sympa sympa  NN MMM DD HH:MM .
drwxr-xr-x NN sympa sympa  NN MMM DD HH:MM ..
drwxr-x---  N sympa sympa  NN MMM DD HH:MM bad
-rw-------  1 sympa sympa  NN MMM DD HH:MM LISTNAME@DOMAIN.nnnnnnnnnn.nnnnn
...
```

When you confirmed that permission is correct, start Sympa service and check the logs.

**Comment by IzxxY** [comment]
THANK YOU !!
It worked !!!
The queue has been flushed right after I fixed the permission :
chown sympa.sympa file
 
Thank you so much !

**Comment by ikedas** [comment]
I realized that `bad` directory is world-writable and would be better to be corrected, e.g.:
``` bash
# chown -R sympa:sympa /appli/sympa/sympa_6.2.68/sympa/spool/msg/
# chmod -R g-w,o-rwx /appli/sympa/sympa_6.2.68/sympa/spool/msg/
```

**Comment by IzxxY** [comment]
Alright i'll change my perm on it !

**Comment by ikedas** [comment]
The problem appears to have been resolved.  Close.
