### ISSUE TITLE
Template error parsing not detected

### ISSUE THREAD

**Issue by simonelbaz** [sympa-community/sympa#1474]
Hi,

I am trying to create automatic list using config.tt2 template as suggested in [documentation](https://www.sympa.community/manual/customize/automatic-lists.html).

An exception is throwed but no error is logged.

After digging into the code (https://github.com/sympa-community/sympa/blob/f71f5ce96fc386993b151bff41a83fe205f8e2e8/src/lib/Sympa/Request/Handler/create_automatic_list.pm#L99), the abort_on_error variable is never set. So even if the template throws an error, it will not be logged.

I didn't find the place where to set abort_on_error to true in order to be able to log template errors.

Thanks for you help

**Comment by ikedas** [comment]
Hi @simonelbaz ,

Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/598768b6b7edfa8e6a7f8cfd2ef44ad9f9e8a3ec.patch) and check if the error will be logged?

**Comment by simonelbaz** [comment]
Hi @ikedas,

Bug fixed after applying your patch:

```
sympa-web-21_1  | Sep 12 13:05:28 sympa-web-21 sympa_automatic[210]: err main::#164 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessAutomatic::_twist#262 > Sympa::S
pindle::spin#95 > Sympa::Request::Handler::create_automatic_list::_twist#99 Can't parse /etc/sympa/*****/families/****/config.tt2: auto
family error - SYNTAX ERROR: *****
```

Thanks a lot

**Comment by ikedas** [comment]
Merged.  @simonelbaz , thank you for reporting bug!
