### ISSUE TITLE
sending stagged mails 

### ISSUE THREAD

**Issue by ASLLR** [sympa-community/sympa#1479]
Version
-------
Sympa 6.2.60

Installation method
-------------------
repo

Question
----------------------
Hi everyone, i would like to know how i can sending mail stagged in time. Because, i must send several thousands mail and i would like to not blacklist my IP. 

It is possible to send 1000 mails every 12 hours ? or others values this is an example.

Thank you in advance,

**Comment by ikedas** [comment]
> It is possible to send 1000 mails every 12 hours ? or others values this is an example.

I don't see any problem at all with that amount of mail delivery. That is only an average flow rate of a little more than one mail per minute.

Could you be more specific about what you would like to do?

**Comment by ASLLR** [comment]
Hi @ikedas thank you for your answer.

Yes but i don't know if it's possible directly with sympa for not overlead the network. I've seen we can do what i want directly in postfix with this command :

`smtp_destination_rate_delay = 1s`

source : https://wiki.deimos.fr/Postfix:_limit_outgoing_mail_throttling.html 

thank you in advance,
