### ISSUE TITLE
$localstatedir/sympa/static_content/css directory not created at install time

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#148]
As in subject, the $localstatedir/sympa/static_content/css is not created at install time and gets created only at run time. Probably pure nitpicking...

**Comment by ikedas** [comment]
What you pointed out is right. Currently CSS are generated without operation by user (previously it was generated by explicit operation) and css/ directory must always exist.

**Comment by ikedas** [comment]
Now STATICDIR/css will be created during installation, and STATICDIR and STATICDIR/js are no longer owned by sympa user.

Closed.
