### ISSUE TITLE
Regeneration of moderation process 

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1480]
Version
-------
6.2.60

Installation method
-------------------
Debian Bullseye package

Expected behavior
-----------------
A message waiting for moderation should be available in the web interface

Actual behavior
---------------
A message wainting for moderation is not available in the web interface

Additional information
----------------------
Yesterday someone sent a message to a moderated list. The message triggered the moderation process and a mail message was sent to the list moderators. I can see the message waiting in the `moderation` and `viewmail/mod` spool folders for that list but it does not shows up in the "Moderate" section of the web interface.

I am not interested in knowing the cause of this error since my server is working fine and I understand that it can be related with a one-time error but I would like to know if there is a way for server admins to force this message to show up in the web interface for moderation.

**Comment by qosobrin** [comment]
I close this question since it did not generate any answer.

**Comment by ikedas** [comment]
You didn't show the actual steps to reproduce the problem, so we can't figure out what is the problem (Perhaps #1406 is the case?).
