### ISSUE TITLE
Conflict with Wordpress installation on same domain as Sympa

### ISSUE THREAD

**Issue by raid1** [sympa-community/sympa#1481]
I am using a multi domain setup of sympa on my servers.
Sympa works great (thanks to all devs!)
But if there is a wordpress installation for the same domain name, the https://.../wws URL doesn't work anymore because WP comes with an .htaccess file like this which "sucks" the /wws into the wordpress parser:
```<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
```
This could be solved by adding an extra RewriteCond to exclude `/wws`
however Wordpress overwrites the .htaccess file by itself from time to time when the WP makes changes.

Version
-------
Sympa 6.2.60~dfsg-4  (Debian 11 package)

Installation method
-------------------
apt install sympa

Expected behavior
-----------------
Wordpress' .htaccess file should not rewrite sympa URLs.
I am looking for a method to protect the /wws path from the WP's RewriteUrl

My intentions to find a solution:
-------------------
I tried adding things to the global apache configuration but .htaccess overrides them.
Turning off the override rights of .htaccess would break Wordpress.

Of course I could add the RewriteCond to .htaccess and then write protect the file.
But then the Wordpress admin cannot make any WP changes anymore which require additions/changes in .htaccess.

Finally I thought I had found a solution:
I added this line to `/etc/apache2/conf-enabled/sympa.conf`:
`Alias /wws /var/lib/sympa`
This makes https://..../wws work again BUT then the sympa login button is broken. _sigh_

Any other ideas? Researching the web did not reveal anything hints.
It seems that I'm the only one using Sympa **and** Wordpress on the same domain name which is very surprising to me. :-)

Thanks A LOT in advance!
Andy

**Comment by ikedas** [comment]
You may change [`AllowOverride`](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) line to ignore  `.htaccess`:
``` code
AllowOverride None
```
and copy the contents of `.htaccess` into main config file.

**Comment by raid1** [comment]
Thanks for the quick reply and suggestion but as mentioned this would annoy the WP admins because they could not make changes anymore.

When I was still using the wwsympa-wrapper I had an ScriptAlias like this:
`ScriptAlias /wws /usr/lib/cgi-bin/sympa/wwsympa-wrapper.fcgi`
Now I'm using the SetHandler method like so:
```
<Location /wws>
    SetHandler "proxy:unix:/run/sympa/wwsympa.socket|fcgi://"
    Require all granted
</Location>
```
But "Location" seems to have lower priority than the RewriteRule.
Could that be changed somehow?

Thanks!

**Comment by ikedas** [comment]
[Documentation of httpd](https://httpd.apache.org/docs/2.4/en/sections.html#file-and-web) suggests "to never use `<Location>` when trying to restrict access to objects in the filesystem."  So you may use only one of `<Directory>` or `<Location>` for both `SetHandler` and `RewriteRule`.

**Comment by raid1** [comment]
I see, thanks for pointing me there.
The [Sympa Docs](https://www.sympa.community/manual/install/configure-http-server-proxy.html) suggest "Location" however.
So how could I rewrite the Apache config using "Directory" instead?  It's meant only for real filesystem paths and "/wws" is just a virtual path.
Still a bit lost here...

**Comment by raid1** [comment]
> So if you use `<Directory>` for the path `/wws`, you have to create a directory `wws` under the DocumentRoot. Or the server will respond `404 Not found`.
Correct. That's why this is not a solution. :-(

I came up with a workaround now:
I'm creating a dummy file named "wws" in the top directory of the Wordpress instance. This fulfills the second RewriteCond ("...! -f) and therefore skips the RewriteRule.
Not really great but the least effort and no interference with the WP admin.

**Comment by ikedas** [comment]
It's a bit surprising solution...!

Alternatively (just a thought), you might add another `RewriteCond` line to exclude the `/wws` from the rules.

**Comment by raid1** [comment]
Uhm, you might have overlooked my comment in the very first post:

> This could be solved by adding an extra RewriteCond to exclude /wws
> however Wordpress overwrites the .htaccess file by itself from time to time when the WP admin makes changes

Or am I misunderstanding your suggestion?

**Comment by ikedas** [comment]
> Uhm, you might have overlooked my comment in the very first post:
> 
> > This could be solved by adding an extra RewriteCond to exclude /wws
> > however Wordpress overwrites the .htaccess file by itself from time to time when the WP admin makes changes
> 
> Or am I misunderstanding your suggestion?

I understand that now httpd ignores `.htaccess` and only content of its main config file which won't be overwritten by WordPress will be effective.

**Comment by raid1** [comment]
Sorry, I have no idea what you are trying to say with your last comment.
"now" = ?
Why should Apache ignore .htaccess?
WP's "main config file" doesn't play a role here at all imho.
...?

Summarizing:
- There is definitely a conflict between the way Apache is configured for Sympa and .htaccess files of Wordpress.
- This should be handled by Sympa's Apache config or Wordpress. But I'm afraid they won't care. :-(
- I found an ugly workaround which does not seem to have side effects.

**Comment by ikedas** [comment]
> You may change [`AllowOverride`](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) line to ignore `.htaccess`:
> 
> ```
> AllowOverride None
> ```
> 
> and copy the contents of `.htaccess` into main config file.

Have you done this? If you have, .htaccess would be ignored by httpd and you may freely edit “main config file” of *httpd* (I’ve never written about WordPress’s config).

**Comment by ikedas** [comment]
The problem asked seems have been solved.  Close.

**Comment by raid1** [comment]
> The problem asked seems have been solved. Close.

Great, this sounds promising.
Please add a pointer to the solution.

**Comment by ikedas** [comment]
Hi @raid1 ,

I have written how to solve the problem.
If you are not satisfied with our advice, then ask your questions elsewhere, such as [WordPress Support Forums](https://wordpress.org/support/forums/).

**Comment by raid1** [comment]
Hi ikedas,
unfortunately what you have written does *not* solve the problem.
The only way to make sympa and wordpress live together peacefully is my weird workaround.

I'm a bit surprised that this doesn't seem to bother the sympa devs.

**Comment by racke** [comment]
It is really an Apache issue rather than a Sympa problem. I'm using Nginx and php-fpm, so I can't help you here.

**Comment by ikedas** [comment]
racke, so your nginx is completely ignoring the contents of the .htaccess written by WordPress!

Well then, it seems that even the administrator of Apache httpd doesn't have to be horrified that the contents of the .htaccess that WordPress writes will someday be completely changed.
