### ISSUE TITLE
Deprecate "dkim" authentication method for scenarios

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#1483]
Expected Behavior
-----------------

"dkim" authentication method for scenarios should be replaced with more effective feature.

Current Behavior
----------------

  * Sympa's DKIM verification is very insufficient:
      - It succeeds if either of signature passes, regardless of the signer domain or identity (see #1340). This means that a third party can add a signature to deceive the sender.
      - Since it is intended to verify the legitimacy of the address in the `From:` field, it can partly be replaced by DMARC verification.
      - On the other hand, if DMARC verification is to be performed, ARC verification should also be performed (in case that incoming message has been forwarded and has ARC seal(s)).
  * Even though the scenario is shared between the mail interface and the web interface, the `dkim` method is available only with the formaer.
  *  It is complicated because there are many scenarios that differ only in whether the `dkim` method is valid or not.

Possible Solution
-----------------

* [x] Deprecate `dkim` method and make it an synonym of `smtp` method.
* [x] ~~Add a new global option parameter to reflect the results of DKIM/DMARC/ARC verification to the `smtp` method (equivalent to the `dkim` method) or not (same as the `smtp` method so far).~~
* [x] ~~Make DKIM verification more precise (consider signer domain or identity).~~

It would be possible for Sympa to take on DMARC/ARC verification, however the results of verification at MTA could be used as well as the current ARC support.

Context
-------

**Comment by salaun-urennes1** [comment]
I'm not a DKIM/DMARC expert, therefor I suggest you ask David Verdin's point of view. He both knows very well Sympa and these protocols.

@dverdin could you give Soji your point of view on these propositions?

**Comment by ikedas** [comment]
> Yes, but it is not a important. S/MIME is not available in a web context either.

**Comment by ikedas** [comment]
>> * Even though the scenario is shared between the mail interface and the web interface, the `dkim` method is available only with the formaer.

> Yes, but it is not a important. S/MIME is not available in a web context either.

Please read [the document](https://www.sympa.community/manual/customize/basics-scenarios.html#authentication-methods).

> ARC verification adds a level of complexity because it supposes you have a reference of mail servers whose ARC headers you trust. That could be a new Sympa configuration file.

Such configuration file (why the file instead of parameter, besides) seems not useful.  What I wrote is that the message that has been modified in forwarding could validate the ARC chain instead of validating the DKIM signature.

Anyways I want to know: In the end, You think that the dkim authentication method is not helpful after all. Is it right?

**Comment by dverdin** [comment]
> > > * Even though the scenario is shared between the mail interface and the web interface, the `dkim` method is available only with the formaer.
> 
> > Yes, but it is not a important. S/MIME is not available in a web context either.
> 
> Please read [the document](https://www.sympa.community/manual/customize/basics-scenarios.html#authentication-methods).

I wrote it.
I forgot about it.

> 
> > ARC verification adds a level of complexity because it supposes you have a reference of mail servers whose ARC headers you trust. That could be a new Sympa configuration file.
> 
> Such configuration file (why the file instead of parameter, besides) seems not useful. What I wrote is that the message that has been modified in forwarding could validate the ARC chain instead of validating the DKIM signature.
> 
> Anyways I want to know: In the end, You think that the dkim authentication method is not helpful after all. Is it right?

What is the point of writing an answer if you don't read them ? I said that removing the dkim authentication level was a good idea.
I tried to give pointer about going further, but I can see that I'm losing my time trying to give advice here.
Anyway, I did give a last try.

**Comment by ikedas** [comment]
> > > > * Even though the scenario is shared between the mail interface and the web interface, the `dkim` method is available only with the formaer.
> > 
> > 
> > > Yes, but it is not a important. S/MIME is not available in a web context either.
> > 
> > 
> > Please read [the document](https://www.sympa.community/manual/customize/basics-scenarios.html#authentication-methods).
> 
> I wrote it. I forgot about it.
> 
> > > ARC verification adds a level of complexity because it supposes you have a reference of mail servers whose ARC headers you trust. That could be a new Sympa configuration file.
> > 
> > 
> > Such configuration file (why the file instead of parameter, besides) seems not useful. What I wrote is that the message that has been modified in forwarding could validate the ARC chain instead of validating the DKIM signature.
> > Anyways I want to know: In the end, You think that the dkim authentication method is not helpful after all. Is it right?
> 
> What is the point of writing an answer if you don't read them ? I said that removing the dkim authentication level was a good idea. I tried to give pointer about going further, but I can see that I'm losing my time trying to give advice here. Anyway, I did give a last try.

OK. I confirmed that this is one of the features that was only planned but not working properly.

In these years, I have been working on fixing many of those things to make them really usable or removing them to cleanup code. I am happy to be able to remove this.  Thank you for answer.

**Comment by ikedas** [comment]
The interpretation of DKIM signature verification results is left to each ADMD, but on Sympa, it seems to have originally recognized this as a useless feature, we will no longer associate DKIM verification results with user credentials. Therefore, I withdraw the second and third of the three solutions I proposed in my first post.

**Comment by ikedas** [comment]
I submitted update in documentation: sympa-community/sympa-community.github.io#95
