### ISSUE TITLE
Can't access page of list object in webUI

### ISSUE THREAD

**Issue by FabriceRigoulot** [sympa-community/sympa#1484]
Logged as admin in the webUI, I can't access the page of administration of static list when I was subscribed. I got  the error message "Erreur interne du serveur

Sympa n'a pas pu renvoyer la page demandée pour la raison suivante :

Erreurs : undef error - escape_quote: filter not found".

Version
-------

6.2.68

Installation method
-------------------

Rpm availiable in EPEL repository.

Expected behavior
-----------------

I expect to get the page where I can configure the list or see the subcribers.

Actual behavior
---------------

In the left frame I got the error messge mentionned above and the right frame is empty.

Additional information
----------------------

The issue occurs when I was subcribed to the list. If I remove my email from subscriber via CLI (sympa del ...) or SQL command , then I get the expected page.

Extract of sympa log :
Sep 21 08:45:58 tique-vm wwsympa[8548]: info main::do_info() [robot robot.cc] [session 13209663735019] [client w.x.y.z] [user aaa@bbb.cc] [list ma.liste]
Sep 21 08:45:58 tique-vm wwsympa[8548]: err main::#1778 > main::send_html#2397 [robot robot.cc] [session 13209663735019] [client w.x.y.z] [user aaa@bbb.cc]] [list ma.liste] /info: error: undef error - escape_quote: filter not found

"sympa.pl  --reload_list_config" and "sympa.pl --dump_users" are successful.

Issue doesn't occur with dynamic list (DB or LDAP datasource).

**Comment by ikedas** [comment]
Hi @FabriceRigoulot ,

`escape_quote` template filter has been deprecated, but the templates customized on your server still includes it.

Please try this:
  1. Cancel all customization of the web templates which are placed in `$SYSCONFDIR/web_tt2` and/or `$SYSCONFDIR/mail_domain/web_tt2` (To know the location of $SYSCONFDIR check [here](https://www.sympa.community/manual/layout.html#sysconfdir)).
  2. Confirm that the error is sloved.
  3. Apply each customization included in the templates cancelled in 1. again.

**Comment by FabriceRigoulot** [comment]
Hi @ikedas 
Indeed by replacing the our customized web template by the standard, i doesn't get the error anymore.
Thanks
