### ISSUE TITLE
integrate Sympa with exchange 2016

### ISSUE THREAD

**Issue by Rami0612** [sympa-community/sympa#1493]
Dears Support , 

we have exchange 2016 , is there any option to integrated with Sympa .

if yes please provide the detailes how we can integrate 

Thanks
Regards,
Rami Chaar

**Comment by ikedas** [comment]
Hi,

I understood that you want to know how to install Sympa on the server where Microsoft Exchangfe Server 2016 is installed.

Please see "[Requirements](https://www.sympa.community/manual/requirements.html)" in the manual.  It states that "Sympa does not support Microsoft Windows".  Installing Sympa on the Microsoft Windows Server is imposssible.

Instead, you may prepare anoither server machine with Unix-like OS (such as Linux) which is supported by Sympa, and may make this server cooperate with the Microsoft Exchange Server 2016.
