### ISSUE TITLE
dmarc_protection.phrase "From" format INCORRECT

### ISSUE THREAD

**Issue by awongsfca** [sympa-community/sympa#1498]
Version
-------
6.2.64

Installation method
-------------------
RPM 

Expected behavior
-----------------
list_for_email - “List” (on behalf of e-mail)	and
list_for_name - “List” (on behalf of Name)
are ACTUALLY working in the opposite ways

Actual behavior
---------------
list_for_email  shows Mail List (on behalf of FirstName LastName)
list_for_name  shows Mail List (on behalf of Email Address)

Steps to reproduce
------------------
/etc/sympa/sympa.conf
use this line
dmarc_protection.phrase list_for_email 
then update to use next line
dmarc_protection.phrase list_for_name

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @awongsfca .

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1500.patch) and check if the problem will be solved?  Thank you.
