### ISSUE TITLE
How to update Owners and Moderators from source when instantiating lists from family

### ISSUE THREAD

**Issue by Kkspike** [sympa-community/sympa#1504]
Version
-------
[6.2.68](https://sympa-community.github.io/)

Installation method
-------------------
yum install sympa 
(CentOS Linux 7 (Core))

Expected behavior
-----------------
When I instantiate lists from families, Owners and Moderators should be updating from the source

Actual behavior
---------------
The Owners and Moderators lists are not getting updated

Additional information
----------------------
We've been using Sympa for many years but I've noted lately that something is not working right. We update our lists frequently because we are managing the lists for many of our schools and the employees are moving around quite frequently. I have noticed that the list of Owners and Moderators are not updating at all when we instantiate the lists from families. I checked the configuration (which we haven't changed in a while) and everything seems to be set up correctly. 

The thing is, if I go to a list in the web GUI and I go to Admin > Users > Moderators (for instance) and I use the Synchronize moderators with data source, the list gets updated according to the SQL query we have set up in the config.tt2 file of the family.

My questions are
1) Are moderators and owners supposed to get updated when I instantiate the family ? I'm pretty sure it used to be the case, no ? 
2) If not, how can I force the owners and moderators list to update with the data source on command line (we have thousands of lists, I can't go and update them all indivually from the GUI) ?

---------------------

Here is the process with screenshots

I instantiated the family trough the CLI
![image](https://user-images.githubusercontent.com/35116060/197590678-e1d335e6-c250-4c11-a8a7-51d9b73d045f.png)

It did not change the Moderators list from source.

This is the result of the query that the moderators are based on (I redacted the names)
![image](https://user-images.githubusercontent.com/35116060/197589887-08536d0e-f8cb-48b2-9891-1ca2f87100cc.png)

This is the actual list of moderators on the list before I update it trough the GUI (I redacted the names)
![image](https://user-images.githubusercontent.com/35116060/197590036-d278ee01-62a6-46a8-81a1-b7bb67a42a1e.png)

This is the list after I use the Synchronize with the data source on the GUI
![image](https://user-images.githubusercontent.com/35116060/197590389-6c86647c-0ff5-4023-b2ea-5dcc2d799cd2.png)

The update removed Myriam and added Linda in her place (as it should be).

**Comment by ikedas** [comment]
@Kkspike , could you please wait for a while and see if the inclusion would be synchronized?
