### ISSUE TITLE
Fail to restore list owners if list in error_config

### ISSUE THREAD

**Issue by salaun-urennes1** [sympa-community/sympa#1524]
I am transferring mailing lists from another Sympa server. Because these lists are in error_config (no owner defined), I can't run the restore_users command to load these owners and fix the list. It seems that the restore_users code should be adapted.

-------
6.2.48

Installation method
-------------------
from source

Expected behavior
-----------------
`Sympa.pl` should let me run restore_users even if the liste is in error_config

Actual behavior
---------------
`sympa.pl --restore_users` fails with error `List is not open`

Steps to reproduce
------------------
For each list, the other listmaster provided the list_data directory including config, editor.dump, member.dump and owner.dump.
I first installed the list directory into our server's list_data/ and then ran  `sympa.pl --reload_list_config`.
At that stage the list is in error_config status because no owner is defined.
I then tried running `sympa.pl --restore_users --role=member,editor,owner` for the list, but if failed with following logs:

```
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: notice main:: Sympa 6.2.48 Started
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: debug2 Sympa::List::new(xx@listes.univ-rennes1.fr, , )
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: debug2 Sympa::List::load(Sympa::List <>, xx, listes.univ-rennes1.fr, ...)
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: debug2 Sympa::List::sync_include_admin(Sympa::List <xx@listes.univ-rennes1.fr>)
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: debug2 Sympa::List::get_admins(Sympa::List <xx@listes.univ-rennes1.fr>, owner,  => )
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: err main::#372 > Sympa::List::new#418 The list "xx" has got no owner defined
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: debug2 Sympa::List::set_status_error_config(Sympa::List <xx@listes.univ-rennes1.fr>, no_owner_defined, ...)
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: err main::#372 > Sympa::List::new#420 > Sympa::List::set_status_error_config#462 The list Sympa::List <xx@listes.univ-rennes1.fr> is set in status error_config: no_owner_defined()
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: debug2 Sympa::send_notify_to_listmaster(Sympa::List <xx@listes.univ-rennes1.fr>, no_owner_defined, ARRAY)
			...
Nov 18 08:56:42 vmperl-psympa1 sympa[13372]: err main::#378 List is not open: Sympa::List <xx@listes.univ-rennes1.fr>

```
Additional information
----------------------
I checked the latest code from github and I suspect the behavior is still the same with latest code https://github.com/sympa-community/sympa/blob/75b5d99b6857a4dc27e3b4efdae1a4177179d358/src/lib/Sympa/CLI/restore.pm#L62-L64

I suggest removing this condition

**Comment by ikedas** [comment]
As of 6.2.58, the list without defined owner is no longer erroneous: See also #955.

**Comment by salaun-urennes1** [comment]
Thanks for the quick response, Soji.
I should have remembered that change, since I was involved, sorry.
Then with 6.2.58 it should be fine for me.
Would it still make sense to allow restore_users to be run if list is not open...I don't known?

**Comment by ikedas** [comment]
> Would it still make sense to allow restore_users to be run if list is not open...I don't known?

I can't say for sure. One possible reason might be that `owner.dump` etc are also used to save user information when the list is closed, so that users cannot be changed while the list is closed.

Please check the current behaviour and give your suggestion.

**Comment by salaun-urennes1** [comment]
I'd say that it is acceptable that we expect  a list to be reopened first before users get restored.
So I close the issue.

Thanks
