### ISSUE TITLE
Adding ARC support

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#153]
Current beta: Sympa 6.2.37b.2

### ToDo

- [x] Making changes on Sympa
- [x] Documentation
- [x] Beta testing

### Documentation (draft)

- Sympa Administration Manual: [DKIM and ARC features for Sympa](https://sympa-community.github.io/manual/customize/dkim-arc.html)

### References

Related posts:
  - [\[sympa-developpers\] Adding ARC supprt to Sympa](https://listes.renater.fr/sympa/arcsearch_id/sympa-developpers/2018-01/alpine.OSX.2.21.1801042045010.25310%40ary.qy)

Specification:
  - [Authenticated Received Chain Overview](https://dmarc.org/presentations/ARC-Overview-2016Q3-v01.pdf) by DMARC.org
  - [Authenticated Received Chain (ARC) Protocol](https://tools.ietf.org/html/draft-ietf-dmarc-arc-protocol-10), draft-ietf-dmarc-arc-protocol
  - [Recommended Usage of the Authenticated Received Chain (ARC)](https://tools.ietf.org/html/draft-ietf-dmarc-arc-usage), draft-ietf-dmarc-arc-usage

**Comment by jrlevine** [comment]
General flow:
* as message is received, see if there is an Authentication-Results header. If there is, do ARC validation on incoming message and edit arc=<whatever> result into the A-R header or arc=none if none
* as outgoing message is signed, look for that A-R header again, use the incoming ARC result in ARC signing which can happen at the same time as DKIM signing
* add ARC headers above DKIM header(s) on the way out
I can provide sample code if it'd be useful

**Comment by ikedas** [comment]
@jrlevine, thanks for guidance. Please do provide sample!

**Comment by jrlevine** [comment]
[prearc.txt](https://github.com/sympa-community/sympa/files/1629547/prearc.txt)
Here's the prepass I use to add the incoming arc-chain to the Authentication-Results header. I run it on deliver as:
|bin/prearc | bin/queue <listname>

**Comment by jrlevine** [comment]
Here's a simplified version of my post-pass ARC and DKIM signer. (I used to use mj2 and it was easier to keep using this than to integrate it into Sympa.) You can see how the ARC signature is added in parallel with DKIM signature(s).
[sympamail.txt](https://github.com/sympa-community/sympa/files/1629551/sympamail.txt)

**Comment by dverdin** [comment]
I strongly agree with this proposal. ARC's design is especially well suited for mziling lists. That would be a good hope for mailing lists to go through DMARc agressive policies.
However, I feel we will need some servers reputation listings to make it work. Is there something planned by some consortium somewhere?
@jrlevine : did you hear about such a reputation list? I think this could be useful.

**Comment by ikedas** [comment]
Draft documentation was merged: https://sympa-community.github.io/manual/customize/dkim-arc.html

I have a question: Doc says:
> ARC requires Mail::DKIM version 0.60 or later which includes ARC support.

But the last release on [metacpan](https://metacpan.org/release/Mail-DKIM) is 0.53, and 0.51 is identical to it except some test cases added.  Isn't 0.51 suffice?

**Comment by jrlevine** [comment]
On Sat, 6 Oct 2018, IKEDA Soji wrote:
> Draft documentation was merged: https://sympa-community.github.io/manual/customize/dkim-arc.html
>
> I have a question: Doc says:
>> ARC requires Mail::DKIM version 0.60 or later which includes ARC support.
>
> But the last release on [metacpan](https://metacpan.org/release/Mail-DKIM) is 0.53, and 0.51 is identical to it except some test cases added.  Isn't 0.51 suffice?

You're right.  I checked, anything since 0.50 is OK.

Regards,
John Levine, johnl@iecc.com, Primary Perpetrator of "The Internet for Dummies",
Please consider the environment before reading this e-mail. https://jl.ly

**Comment by ikedas** [comment]
> You're right. I checked, anything since 0.50 is OK.

Thanks for confirming.  Unfortunately current Sympa have to support Perl 5.8.1 at earliest while 0.50 uses `//` operator.  I'll adopt 0.51.

**Comment by ikedas** [comment]
If there are no more problems, this issue will be closed in the next week, i.e. beta test will be finished!
