### ISSUE TITLE
[6.2.72] Mail::AuthenticationResults::Header Missing in cpanfile

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa#1539]
Mail::AuthenticationResults::Header is currently absent from cpanfile, so Sympa crashes at startup.

**Comment by ikedas** [comment]
Mail-DKIM depends on it.  Close.
https://metacpan.org/dist/Mail-AuthenticationResults/requires

**Comment by dverdin** [comment]
Mail::DKIM is not currently a direct Sympa dependency in the cpanfile.
We have Mail::DKIM::Verifier and Mail::DKIM::ARC::Signer. None of these require Mail::DKIM.
I don't see any Sympa dependency requiring Mail::DKIM: https://metacpan.org/dist/Mail-DKIM/requires

I simply ran `cpanm --installdeps .` and the "Mail::AuthenticationResults::Header" was not installed. It is either a cpanfile or a documentation problem.

**Comment by ikedas** [comment]
When submitting a bug report, please fill in all fields of the template. Are you willing to cooperate with others?
