### ISSUE TITLE
Sympa 6.2.24 : Welcome message no more editable

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#155]
I have installed a fresh version of sympa 6.2.22 and created a list ti modify the messages templates.
In that version, the Welcome message may be modfiied (see first file attached)

![messages-templates-6 2 22](https://user-images.githubusercontent.com/32573089/34641274-c4ea554a-f301-11e7-92cc-5b146fb73eb1.png)

Next, I update to sympa 6.2.24 and the welcome message is no more editable (see second attachment).

![messages-templates-6 2 24](https://user-images.githubusercontent.com/32573089/34641281-da292c92-f301-11e7-8838-509fe0dd0cb2.png)

The installations have been made from sources : configure - make - make install

**Comment by ikedas** [comment]
On my side it is shown:
![edit_list_templates](https://user-images.githubusercontent.com/5743546/34645504-adbe3170-f392-11e7-89c0-6aa4ec0cf0e1.png)

Can you show us following information?
  - The source of "Edit list templates" page
  - `web_tt2/editfile.tt2` file, if you have customized it.

**Comment by pascalmaes** [comment]
As I said, I start from a fresh version : an empty folder /var/sympa and I don't make any tuning except for the file /etc/sympa/sympa.conf

# ls -lR /var/sympa/etc
/var/sympa/etc:
total 56
-r--r--r-- 1 root  root   355 Jan  6 16:24 README
-rw-r----- 1 sympa sympa   10 Jan  6 16:25 cookies.history
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 create_list_templates
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 custom_actions
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 custom_conditions
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 data_sources
-rw-r--r-- 1 sympa sympa  138 Jan 6 17:07 data_structure.version
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 families
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 global_task_models
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 list_task_models
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 mail_tt2
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 scenari
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 search_filters
drwxr-xr-x 2 sympa sympa 4096 Jan  6 16:24 web_tt2

/var/sympa/etc/create_list_templates:
total 0
/var/sympa/etc/custom_actions:
total 0
/var/sympa/etc/custom_conditions:
total 0
/var/sympa/etc/data_sources:
total 0
/var/sympa/etc/families:
total 0
/var/sympa/etc/global_task_models:
total 0
/var/sympa/etc/list_task_models:
total 0

What I have done this morning

# /etc/init.d/sympa stop
# /etc/init.d/apache2 stop
# cd Install/sympa-6.2.2.22
# make install
# /var/sympa/bin/sympa.pl --upgrade
notice main:: Sympa 6.2.22 Started
notice main:: Upgrade process...
notice main:: Upgrading from 6.2.24 to 6.2.22...
notice Sympa::Upgrade::upgrade() Installing  older version of Sympa ; no upgrade operation is required
notice main:: Upgrade process finished

# /etc/init.d/sympa start
# /etc/init.d/apache2 start

# cp /var/sympa/default/web_tt2/editfile.tt2 /tmp/editfile-6.2.22.tt2

After that, hte welcome message is editable and the welcome message is the following 
# ls -l /var/sympa/default/mail_tt2/welcome.tt2
-rw-r--r-- 1 root root 456 Jan  7 10:25 /var/sympa/default/mail_tt2/welcome.tt2

Next

# /etc/init.d/sympa stop
# /etc/init.d/apache2 stop
# cd Install/sympa-6.2.2.24
# make install
# /var/sympa/bin/sympa.pl --upgrade
notice main:: Sympa 6.2.24 Started
notice main:: Upgrade process...
notice main:: Upgrading from 6.2.22 to 6.2.24...
notice Sympa::Upgrade::upgrade() Rebuilding config.bin files for ALL lists...it may take a while...
notice Sympa::Upgrade::upgrade() Rebuilding the admin_table...
notice main:: Upgrade process finished

# /etc/init.d/sympa start
# /etc/init.d/apache2 start

The welcome message is the new one (seems the same content)
#  ls -l /var/sympa/default/mail_tt2/welcome.tt2
-rw-r--r-- 1 root root 456 Jan  7 10:32 /var/sympa/default/mail_tt2/welcome.tt2

but it is no more editable (doesn't appear)

# diff /var/sympa/default/web_tt2/editfile.tt2 /tmp/editfile-6.2.22.tt2 

[diff-editfile.txt](https://github.com/sympa-community/sympa/files/1609615/diff-editfile.txt)

# diff edit-templates-6.2.24.html edit-templates-6.2.22.html
[diff-edit-template-page.txt](https://github.com/sympa-community/sympa/files/1609618/diff-edit-template-page.txt)

Furthermore, I have the following error if I try to modify a template
![capture d ecran 2018-01-07 a 10 49 33](https://user-images.githubusercontent.com/32573089/34648346-a6a10ef2-f398-11e7-97fa-8874f35f7a22.png)

I don't have this problem with the 6.2.22 version

Thanks

**Comment by ikedas** [comment]
@pascalmaes, can you compare edit_list.conf between 6.2.22 and 6.2.24?

**Comment by pascalmaes** [comment]
% cd /var/sympa
% find . -name edit_list.conf
./default/edit_list.conf
%  more etc/data_structure.version 
# This file is automatically created by sympa.pl after installation
# Unless you know what you are doing, you should not modify it
6.2.22
% cp default/edit_list.conf /tmp/edit_list-6.2.22.conf
% cd Install/sympa-6.2.24/
% make install
% /var/sympa/bin/sympa.pl --upgrade
notice main:: Sympa 6.2.24 Started
notice main:: Upgrade process...
notice main:: Upgrading from 6.2.22 to 6.2.24...
notice Sympa::Upgrade::upgrade() Rebuilding config.bin files for ALL lists...it may take a while...
notice Sympa::Upgrade::upgrade() Rebuilding the admin_table...
notice main:: Upgrade process finished
% cd /var/sympa
% find . -name edit_list.conf
% diff ./default/edit_list.conf /tmp/edit_list-6.2.22.conf 
99,103d98
< owner_domain			owner				read
< owner_domain_min		owner				read
< owner_domain			privileged_owner		write
< owner_domain_min		privileged_owner		write

**Comment by ikedas** [comment]
sorry I forget to say: If files (editfile.tt2 & edit_list.conf) customized for 6.2.22 are there, please compare them with defaults of 6.2.24.

**Comment by pascalmaes** [comment]
There are no customization, only the defaults are used.

**Comment by ikedas** [comment]
I have no idea... @pascalmaes, could you show the entire HTML source (not the diff) of the page in question? You may send it to my e-mail if you prefer.

**Comment by pascalmaes** [comment]
Here is the source


[edit-templates-6.2.24.html.txt](https://github.com/sympa-community/sympa/files/1612286/edit-templates-6.2.24.html.txt)

**Comment by ikedas** [comment]
Thanks @pascalmaes, I confirmed Sympa omits welcome template (not by such as brower bug).

Seeing reject message, I guess there is problem of file permission. Could you check if:
- wwsympa.fcgi is running with privilege of `sympa` user (in case of Apache, invoked through wwsympa-wrapper.fcgi)?
- template files including `mail_tt2/welcome.tt2` are readable by wwsympa.fcgi (files are owned by `sympa` user).

**Comment by pascalmaes** [comment]
Hello,

wwwsympa.fcgi is running as sympa: 
sympa    14163  8319  0 Jan10 ?        00:00:00 /usr/sbin/apache2 -k start

% ls -l /var/sympa/bin/wwsympa*
-rwsr-sr-x 1 sympa sympa   9480 Jan  7 12:44 /var/sympa/bin/wwsympa-wrapper.fcgi
-rwxr-xr-x 1 root  root  588533 Jan  7 12:44 /var/sympa/bin/wwsympa.fcgi

By default the files are owned by root, I change the owner to sympa but no way

% ls -al /var/sympa/default/
total 348
drwxr-xr-x  8 root  root    4096 Jan  7 12:44 .
drwxr-xr-x 12 sympa sympa   4096 Jan 11 08:16 ..
-rw-r--r--  1 root  root    1113 Jan  7 12:44 auth.conf
-rw-r--r--  1 root  root  176038 Jan  7 10:53 ca-bundle.crt
-rw-r--r--  1 root  root     327 Jan  7 12:44 charset.conf
-rw-r--r--  1 root  root    3962 Jan  7 12:44 crawlers_detection.conf
-rw-r--r--  1 root  root     328 Jan  7 12:44 create_list.conf
drwxr-xr-x 10 root  root    4096 Jan  6 16:24 create_list_templates
-rw-r--r--  1 root  root    4196 Jan  7 10:53 edit_list.conf
drwxr-xr-x  2 root  root    4096 Jan  7 12:44 global_task_models
-rw-r--r--  1 root  root     436 Jan  7 12:44 ldap_alias_entry.tt2
-rw-r--r--  1 root  root    1360 Jan  7 12:44 list_aliases.tt2
drwxr-xr-x  2 root  root    4096 Jan  7 12:44 list_task_models
drwxr-xr-x  2 sympa sympa   4096 Jan  7 12:44 mail_tt2
-rw-r--r--  1 root  root   21696 Jan  7 12:44 mhonarc-ressources.tt2
-rw-r--r--  1 root  root   53009 Jan  7 12:44 mime.types
-rw-r--r--  1 root  root     515 Jan  7 12:44 nrcpt_by_domain.conf
drwxr-xr-x  2 sympa sympa   4096 Jan  7 12:44 scenari
-rw-r--r--  1 root  root   18376 Jan  7 12:44 sympa.wsdl
-rw-r--r--  1 root  root     801 Jan  7 12:44 topics.conf
drwxr-xr-x  6 sympa sympa   4096 Jan  7 12:44 web_tt2

% ls -al /var/sympa/default/mail_tt2/
...
-rw-r--r-- 1 sympa sympa   377 Jan  7 12:44 reject.tt2
-rw-r--r-- 1 sympa sympa   456 Jan  7 12:44 welcome.tt2

**Comment by ikedas** [comment]
@pascalmaes, thanks, and ---
  - How about the mode of `/var/sympa/etc/mail_tt2/*.tt2` ?
  - How about the output of following command?
    ``` csh
    ps -ef | grep wwsympa
    ```
    or
    ``` csh
    ps ax | grep wwsympa
    ```

**Comment by pascalmaes** [comment]
As I said, all I do is make ; make install and then create a list ; no customization.
It works fine with 6.2.22 (except the change of owners or editors which is no take into account) and the update to 6.2.24 breaks the edit templates.

% ls -al /var/sympa/etc/{mail_tt2,web_tt2,scenari}
/var/sympa/etc/mail_tt2:
total 8
drwxr-xr-x  2 sympa sympa 4096 Jan  6 16:24 .
drwxr-xr-x 13 sympa sympa 4096 Jan  6 16:25 ..

/var/sympa/etc/scenari:
total 8
drwxr-xr-x  2 sympa sympa 4096 Jan  6 16:24 .
drwxr-xr-x 13 sympa sympa 4096 Jan  6 16:25 ..

/var/sympa/etc/web_tt2:
total 8
drwxr-xr-x  2 sympa sympa 4096 Jan  6 16:24 .
drwxr-xr-x 13 sympa sympa 4096 Jan  6 16:25 ..

% ps -ef | grep wwsympa
root     27751 27629  0 07:43 pts/1    00:00:00 grep wwsympa
% ps -ax | grep wwsympa
27754 pts/1    S+     0:00 grep wwsympa

with a log_level = 3, the output of sympa.err:

Jan 12 07:49:04 sympa-test.sipr.ucl.ac.be wwsympa[27986]: err main::#1606 > main::do_editfile#8175 [robot listes] [session 78628056198469] [client 130.104.x.y] [user pascal.maes] [list test2] Not allowed

the output of sympa.log:

Jan 12 07:48:54 sympa-test.sipr.ucl.ac.be wwsympa[27979]: info main:: WWSympa started, process 27979
Jan 12 07:48:55 sympa-test.sipr.ucl.ac.be wwsympa[27979]: info main::do_admin() [robot listes] [session 78628056198469] [client 130.104.64.150] [user pascal.maes] [list test2] 
Jan 12 07:48:58 sympa-test.sipr.ucl.ac.be wwsympa[27984]: info main:: WWSympa started, process 27984
Jan 12 07:48:59 sympa-test.sipr.ucl.ac.be wwsympa[27984]: info main::do_editfile(message_templates) [robot listes] [session 78628056198469] [client 130.104.x.y] [user pascal.maes] [list test2] 
Jan 12 07:49:04 sympa-test.sipr.ucl.ac.be wwsympa[27986]: info main:: WWSympa started, process 27986
Jan 12 07:49:04 sympa-test.sipr.ucl.ac.be wwsympa[27986]: info main::do_editfile(reject.tt2) [robot listes.uclouvain.be] [session 78628056198469] [client 130.104.x.y] [user pascal.maes] [list test2]

**Comment by ikedas** [comment]
Are you using *BSD? Then please run:
``` csh
ps -axw | grep wwsympa
```
This will show the all wwsympa.fcgi processes.

**Comment by pascalmaes** [comment]
We are using debian 8.7 and all I see with ps are the apache2 processes

**Comment by ikedas** [comment]
> We are using debian 8.7 and all I see with ps are the apache2 processes

That's curious. How you run `wwsympa.fcgi` of Sympa 6.2.24? Is there difference from host running 6.2.22? For example: configuration of apache, option given to `./configure` script, ...

**Comment by pascalmaes** [comment]
Same option for 6.2.24 and 6.2.22 and no differences: it's the same host; all I do it to replace one version with the other by a "make install" and a "sympa.pl --upgrade"

./configure \
--prefix=/var/sympa \
--with-confdir=/etc/sympa \
--with-perl=/usr/bin/perl \
--with-user=sympa \
--with-group=sympa \
--with-postalias=/usr/sbin/postalias \
--with-postmap=/usr/sbin/postmap \

in /etc/apache2/envvars
export APACHE_RUN_USER=sympa
export APACHE_RUN_GROUP=sympa

in /etc/apache2/sites-enabled
 	<Location /sympa>
		Options +ExecCGI
		Options +FollowSymLinks
		AddHandler cgi-script   .fcgi
		Require all granted
	</Location>
        ScriptAlias /sympa "/var/sympa/bin/wwsympa-wrapper.fcgi"

I have also try
	<Location /wws>
		Options +ExecCGI
		Options +FollowSymLinks
		SetHandler fcgid-script
		Require all granted
	</Location>
        ScriptAlias /wws "/var/sympa/bin/wwsympa.fcgi"

but it doesn't working too

**Comment by ikedas** [comment]
@pascalmaes, I feel your configuration is a bit complicating. CGI and FastCGI are not the same thing. Both 6.2.22 and 6.2.24 might not work correctly.

Please try following:
- Confirm that mod_fcgid (`libapache2-mod-fcgid`) has been installed.
- Enable mod_fcgid.  A file `fcgid.conf` with [this content](https://salsa.debian.org/debian/libapache2-mod-fcgid/blob/master/debian/fcgid.conf) may be found.
- Add a configuration for Sympa referring to [this content](https://anonscm.debian.org/git/collab-maint/sympa.git/tree/debian/conf/apache2/sympa.conf).

(Sorry, I can't show working configuration because I'm in holiday and there are no Debian in my home).

**Comment by pascalmaes** [comment]
Hurray !

It works.
Thank you very much.

All I have to do is replace my sympa configuration for apache2 by yours.

**Comment by ikedas** [comment]
Well done! Thanks for answering to my questions patiently. If you don’t find problem with new configuration, please close this issue.

**Comment by pascalmaes** [comment]
Thanks again
