### ISSUE TITLE
The Sympa web interface shows the wrong subscription date. Instead the date on the db is correct

### ISSUE THREAD

**Issue by morenonardelliunitn** [sympa-community/sympa#1566]
We upgrade Sympa from 6.2.28 to 6.2.68 and then upgrade 6.2.68 to 6.2.70

Installation method
-------------------
We have reinstalled Sympa with rpm package on the Red Hat Enterprice Lnux 8 and export the db from the older version and import in the new version

Actual behavior
---------------
If we check the subscribe's date in the sympa web interfce we find almost all the values set to "01 Jan 1970	".
Instaed f we check the db we can find the correct date of sunscription of the users.

Additional information
----------------------
The issue affected both manually added users and those imported from external data sources.
It seems that the error refers to past actions, if you add a new user the registration date is correct
I attach same picture to describe the issue

![sympaissue-db](https://user-images.githubusercontent.com/29304925/210057326-3dab1d48-40d8-4f49-8a74-a09a9b773408.png)
![sympaissue-newadd](https://user-images.githubusercontent.com/29304925/210057330-3fd950a7-912e-4f1d-9775-0959d3e798d5.png)
![sympaissue-web](https://user-images.githubusercontent.com/29304925/210057332-68c04c09-9253-4ed7-a650-287b19d89b5f.png)

**Comment by ikedas** [comment]
Hi @MorenoUniTN ,

Since Sympa 6.2.28, `date_epoch_subscriber` column in `subscriber_table` was used and `date_subscriber` column has been obsoleted.  First, please check the value in the `date_epoch_subscriber`. If its contents are invalid, the upgrade procedure may not have been carried out properly.

**Comment by MorenoUniTN** [comment]
Hi @ikedas ,
I cheecked and the value of  date_epoch_subscriber column in the table subscriber_table result null for  almost all the values... 
Can you advise how I can fix ?  Can I do it with only SQL commands?

**Comment by ikedas** [comment]
I see you use MySQL.

If there is nothing else wrong with Sympa's behavior after the upgrade, I think you can fix the database content by doing the following:
``` sql
UPDATE subscriber_table
SET date_epoch_subscriber = UNIX_TIMESTAMP(date_subscriber)
WHERE date_epoch_subscriber IS NULL;
```
and also
``` sql
UPDATE subscriber_table
SET update_epoch_subscriber = UNIX_TIMESTAMP(update_subscriber)
WHERE update_epoch_subscriber IS NULL;
```
And, possiblly you may also have to repair `date_epoch_admin` and `update_epoch_admin` in `admin_table`:
``` sql
UPDATE admin_table
SET date_epoch_admin = UNIX_TIMESTAMP(date_admin)
WHERE date_epoch_admin IS NULL;
```
and
``` sql
UPDATE admin_table
SET update_epoch_admin = UNIX_TIMESTAMP(update_admin)
WHERE update_epoch_admin IS NULL;
```

**Comment by MorenoUniTN** [comment]
Thank you so much @ikedas for your support.
I will check the admin table and try to update the table columns over the next few weeks with these SQL commands.

Thank you!
