### ISSUE TITLE
sympa.pl - family instantiation - "--quiet" option has no effect on progress bar

### ISSUE THREAD

**Issue by jfaedi** [sympa-community/sympa#1567]
Version
-------
6.2.70

Installation method
-------------------
source package

Expected behavior
-----------------
./sympa.pl --instantiate_family=${family} --robot=${robot} --input_file=${xml_input_file} --close_unknown --quiet
<no output>

Actual behavior
---------------
./sympa.pl --instantiate_family=${family} --robot=${robot} --input_file=${xml_input_file} --close_unknown --quiet
List "xxxxx" (1/1) created/updated
Creating lists: 100% [===========================================================================================]D 0h00m01s

Steps to reproduce
------------------
Instantiate a famliy and use "--quiet" option

Additional information
----------------------
The problem is in "lib/Sympa/CLI/instantiate.pm" near line 134 where "silent" arg sholud be used when creating $progress object like that:
``` perl
        $progress = Term::ProgressBar->new(
            {   name   => 'Creating lists',
                count  => $total,
                ETA    => 'linear',
                silent => $options{quiet}
            }
        );
```

**Comment by ikedas** [comment]
Hi @jfaedi , thanks for reporting bug!

Though I've not confirmed yet, the PR above could fix the problem.  --- However it is the fix against 6.2.71b.1: Recently CLI of Sympa had been changed much.
