### ISSUE TITLE
Notify why new user entry wasn't accepted

### ISSUE THREAD

**Issue by Cwpute** [sympa-community/sympa#1569]
I was trying to add myself (proprietary) as a moderator, but as i tried, Sympa just told me "nothing was changed" and surely my mail adress wasn't added in the list.
Throughtrial and error i figured it was because the "Name" i gave myself was using a space character, which is seemingly not accepted as a correct entry. So i erased the space character and the user was at last accepted as a new moderator (going from `Mail Officiel` to `MailOfficiel`)

Sympa should warn you of incorrect entries like that, so as to give you a chance to correct it instead of thinking the software just doesn't work.
Better still, Sympa should allow for "names" with a space character in it, because if prompted with "name" i'm sure many of us are willing to insert name AND surname, thus using a space character.

I should add that i'm reporting this only for the Moderator page, but that it should be probably applied to other pages as well (Proprietaries, Subscribers etc.)

**Comment by ikedas** [comment]
Hi @Cwpute ,

Please describe the actual operation you performed so that we can reproduce the problem: "I visited the URL xxx, entered my address 'xxx@xxx.xxx' into xxx, entered my name 'xxx xxx' into xxx, clicked xxx button, ...".

**Comment by Cwpute** [comment]
1. Be anywhere on the administration pages for your newsletter; the landing page can do (https://mywebsite.com/sympa/admin/mynewsletter#)
2. In the Basic Operations drop-down menu, go to Users > Moderators
3. Create a new moderator
4. In the Name page, choosea new with a space character

Aaaand the space character names now work.
![whydoesitwork](https://user-images.githubusercontent.com/80604512/210731192-e6843784-4ab2-4f36-8f03-4e5f1e814b81.png)
I swear everytime i tried one yesterday it wouldn't accept it, but when i tried ones without it didn't…

Maybe it's irrelevant, but i sometimes have to reload the page, because neither the buttons or text fields appear, making me think it might be a server issue rather than a software issue. Could that be the case ?

I'm using Sympa 6.2.40 hosted at nebulae.co, an indie provider.

**Comment by ikedas** [comment]
All right. If there are no similar reports after waiting for a while, we will close this issue.

**Comment by Cwpute** [comment]
Could it be the case that this is a server-side issue ?

**Comment by ikedas** [comment]
Further information is needed to determine if this is a server-side issue.  If possible, please report the problem more (please refer to [this description](https://lists.sympa.community/msg/en/2022-06/Lt9Em85rIFZZah2GCgnu3g) as well).

**Comment by Cwpute** [comment]
Unfortunately i can't provide much more info without any guidance. I'll ask the people at nebulae.co if this problem appears again.
