### ISSUE TITLE
[scenario] How to limit the number of email address when responding to a list

### ISSUE THREAD

**Issue by PgAuffret** [sympa-community/sympa#1578]
Version:
---
6.2.40 _via_ Debian apt

Question
---

I have looked at the [documentation](https://www.sympa.community/gpldoc/man/sympa_scenario.5.html)  but did not find any answer. Some list members are using their email client to spread messages from one particular list to another. To do so they add some list email addresses to the 'To', 'Cc' or 'Bcc' fields, when answering to a list message. So, is there any way to prevent users to add more than n lists when responding to a list?
For instance :

> From: list1@lists
> To: list2@lists, list3@lists
> Cc: list4@lists
> Bcc: list5@lists, ...

**Comment by ikedas** [comment]
Hi @PgAuffret ,

I think it is impossible to limit the number of recipients by any funtion of Sympa, e.g. the scenarios.   Even if it was possible, that is inadequate because there is no way to know the BCC addresses.

**Comment by PgAuffret** [comment]
Hello @ikedas,
Thank you for your answer. I was hoping it would be possible to write something like `less_than([number_of_email_address_per_field],'1') smtp,smime,md5 -> do_it`.
However, as you said, 'To', 'CC' nor ' 'Bcc' variables seem to exist.
There is a reference to is_bcc variable. But obviously it is not meant to test the content of the field.
