### ISSUE TITLE
Clicking the button Accept to change to a new email adress doesn't change it at all

### ISSUE THREAD

**Issue by Umeaboy** [sympa-community/sympa#1586]
Version
-------
6.2.66 via Mageia

Expected behavior
-----------------
When logging in to SYMPA to change the email address to another one, it should be done after clicking the link in the AUTH mail followed by clicking the button to Accept the change that you receive in the other email Inbox.

Actual behavior
---------------
After clicking the button Accept and logging out and then trying to login using the new email address it fails to work, but the one that I used before still works.

Steps to reproduce
------------------
1. I open Firefox.
2. I type https://ml.mageia.org and hit Enter/Return button.
3. I click Login in the right upper corner.
4. I type my current email address and the password and then I click the Go button.
5. Now I click the upper right corner on my email address and click User preferences.
6. In the field for New email address: I type my new email address and click Change Email.
7. I get a notification message that I've got a new message waiting in my other Inbox.
8. I click to open that AUTH message and see the link so I click it.
9. Now I'm asked "Are you sure you want to change?" and I click Accept.
10. No error message displayed when I click the button.
11. I click in the upper right corner on my current email address and then click on Logout.
12. On the login screen I choose to enter my email address and keep my current password.
13. The login fails with a message stating " ERROR () - Provided password is incorrect " even though I haven't changed my password.

**Comment by Umeaboy** [comment]
I reported it downstream as well: https://bugs.mageia.org/show_bug.cgi?id=31501

**Comment by ikedas** [comment]
Hi @Umeaboy ,

Are you an administrator of [ml.mageia.org](https://ml.mageia.org/)? If you are _not_, at first you should contact these administrators.

FYI: I could not reproduce the problem you reported with Sympa 6.2.70 on my private server.

**Comment by Umeaboy** [comment]
> Hi @Umeaboy ,
> 
> Are you an administrator of [ml.mageia.org](https://ml.mageia.org/)? If you are _not_, at first you should contact these administrators.
> 
> FYI: I could not reproduce the problem you reported with Sympa 6.2.70 on my private server.

No, I'm not.
The standard way to perhaps get this issue fixed is to first report it upstream so that's what I did.
We'll see if any of the administrators comments this.

**Comment by ikedas** [comment]
> The standard way to perhaps get this issue fixed is to first report it upstream so that's what I did.
> We'll see if any of the administrators comments this.

Developers at upstream (and also you) cannot determine whether the reported problem is environment-dependent or caused by upstream code. The only one who can do that is the administrator of the respective installation.

Therefore, problems at a particular site should be reported to the administrator at first. If the administrator determines that the problem is dependent on their environment, they will solve the problem by their own.  Otherwise, they will submit a bug report with this issue tracker.

We appreciate your cooperation.

**Comment by ikedas** [comment]
Bug 31501 in Mageia seems to have been rejected.  This isssue is also closed.

**Comment by ikedas** [comment]
> No. You need an account for the bugzilla in order to view the status of it. When I'm logged in it still says NEW at the top.

I see  Anyways, as I wrote in the last week, please wait for the response from the administrator of Mageia.  Until then, we will not be able to help you.
