### ISSUE TITLE
Is it possible to manage owners and editors of lists or change lists configuration using SOAP?

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#1588]
Version
-------
6.2.60

Installation method
-------------------
Debian Package

Expected behavior
-----------------
I want to use SOAP to manage some of my lists including the following aspects: create/close lists, change the behaviour of already created lists, add/remove subscriptors, and add/remove owners/editors.

Actual behavior
---------------
I could only find information on how to create/close lists and how to add/remove subscriptors.

Additional information
----------------------
I have been reading about the use of SOAP to manage sympa lists and subscriptors. I know how to create/close lists and how to add/remove subscriptors, but I have not found any information on how to do any of the followindg actions, or even if it is possible to do them: changing the behaviour (configuration) of a already created list, and managing owners/editors of a list.

I would appreciate it very much if you could tell me if this is possible and, if so, how to do it, since I haven't  found any refference to them neither in the Sympa's SOAP API documentation ((https://www.sympa.community/manual/customize/soap-api.html) nor in Sympa's default WSDL document (https://github.com/sympa-community/sympa/blob/main/default/sympa.wsdl)

Thank you very much.
Best regards.

**Comment by ikedas** [comment]
See also #526 and #1251 / #1503 .

**Comment by qosobrin** [comment]
> See also #526 and #1251 / #1503 .

So, after reading all these three, I realize that this is a work in progress. In my opinion, we should have the same options for owner/editor management as we have for subscribers; I mean, we should be able to manage owner/editor in lists using SQL external sources, LDAP queries, SOAP calls, etc. I know some of them are more available than others right now but, for people like me that use a lot of dynamic subscriptions lists, it is a must.

Thank you very much for your prompt answer, @ikedas 

Best regards.

PS: I'm closing this question since I do not feel like I'm going to get a better answer than yours, @ikedas
