### ISSUE TITLE
Different values ​​between local configuration files and MySQL database

### ISSUE THREAD

**Issue by morenonardelliunitn** [sympa-community/sympa#1591]
Hi all,
we have found a different values between many values stored in a local file **config** (files stored in /var/lib/sympa/list_data/domain/namelist/ ) with the corresponding values in databaes's tables.
It's possibile or it's a bug?

Version
-------
6.2.70

Installation method
-------------------
via rpm package (on EPEL repository) in RHEL 8.6

Expected behavior
-----------------
What I expect is that the data between the database and the config files are in sync

Actual behavior
---------------
At the moment it is not like that

Additional information
----------------------
What I have noticed is the lack of synchronization of only some parameters such as the owner's profile mode (normal/provileged) or the owner/editor reception mode

There is a command that allows synchronization of data from the database to configuration files local to the list?

**Comment by ikedas** [comment]
As of 6.2.34, owners and moderators are no longer stored in list `config` file: They are stored only in database.  If you migrate from an earlier version, the values of `owner` and `editor` in the `config` file will no longer be used.

**Comment by MorenoUniTN** [comment]
Thanks @ikedas for the answer. 
If I understand correctly the values ​​of the owner and editor sections in the `config` files can they then be deleted? I only have one doubt, in the config files of the lists there are also references to the mode of inclusion of any owners or moderators, the sections are identified by `owner/editor_include`. Are these values also no longer used in the files?

**Comment by racke** [comment]
The include statements are still valid in the config. Only owner and editor are not in use.

**Comment by ikedas** [comment]
racke is right.  `owner` and/or `editor` paragraph(s) may be removed from the list `config` files (n.b. of course you could simply ignore them instead of doing so).  The others may not.

**Comment by MorenoUniTN** [comment]
Thanks everyone for the answsers.
In this regard I did some tests and I encountered another problem.
I have a `list` with` owner include config` , I tried changing an owner profile value from `normal` to `privileged` in Sympa web interface. After forcing the `Synchronized owners with data sources` I rechecked the `config` file of the list and the value has been correctly modified (`privileged`), but in the database the value remains the old one (`normal`).

If you think it's better I can open a new post with with more information or screen about it.

Thanks in advanced
Moreno

**Comment by ikedas** [comment]
Please write down what you actually did and the facts you actually observed. Please see also [here](https://lists.sympa.community/msg/en/2022-06/Lt9Em85rIFZZah2GCgnu3g).

**Comment by MorenoUniTN** [comment]
Sure @ikedas  and thanks....
we have found a unexpected behavior with the update operation with same profile information refered to `owner` o `editor` included from `data source`.

Version
-------
6.2.70

Installation method
-------------------
via rpm package (on EPEL repository) in RHEL 8.6

Actual behavior
-----------------
In some list we have configured included owner and editor from data source `Owners defined in an external data source (owner_include)(default)` . For this we have create a file `.incl` and stored in the path `/var/lib/sympa/list_data/domain/listname/data_sources` . The files contain LDAP query parameter configuration. 
This is ok and the owners and te parameters ewas defined in the web section was added correctly to the list and the vaues is the same in the databases on `admin.table`

![Sympa-ownDataSources-1](https://user-images.githubusercontent.com/29304925/218765151-59fb505b-2fe9-4531-8f0b-85ca46e0c13c.png)

![Sympa-ownDataSources-5](https://user-images.githubusercontent.com/29304925/218765032-b42cc2be-7362-4c11-973a-dbdcbd0c6cfd.png)

If I try to change a value in the Sympa Webb interface, for example from `profile` `normal` to `privlieged` and once I have forced the synchronization using the `Synchronize owners with data sources` button I keep seeing the wrong value (`normal`) both in the owners section of the Sympa web interface and the value stored in the database.
if I check the `config` file of the list instead I find the correct value (`privileged`) in the `owner_include` section:
`owner_include
reception mail
visibility noconceal
profile privileged
source psupsympa`


Additional information
----------------------
I hope I have detailed the error, if not please tell me what might help and if any further information or testing is needed, if I can be of any help please let me know, I will gladly do so

Thanks in advanced

Moreno

**Comment by ikedas** [comment]
@MorenoUniTN , thank you for detailed report.

The values of the `profile`, `reception`, and/or `visibility` parameters in `owner_`|`editor_include` are applied when a user is newly added, but not when the user is retained as a result of re-synchronization. I see it is a bug in the documentation that this is not clearly stated.

**Comment by ikedas** [comment]
Hi @MorenoUniTN ,
As of 6.2.72, a command line "[`sympa set`](https://www.sympa.community/gpldoc/man/sympa-set.1.html)" will be available.

**Comment by MorenoUniTN** [comment]
Thanks  very much @ikedas,
Sounds good!

**Comment by ikedas** [comment]
There seems no more questions. Close.
