### ISSUE TITLE
SMIME digital signatures in HTML formatted emails show tampering

### ISSUE THREAD

**Issue by iulistadmin** [sympa-community/sympa#16]
HTML-formatted emails distributed through Sympa may display an error stating that the message has been tampered with since it was signed. The original signing certificate is intact in the email, and viewing the certificate shows that the certificate matches the original sender, but the warning gives recipients pause. Plain text and rich text emails do not appear to be affected. The issue has been replicated in multiple clients. Our installation is Sympa 6.1.11 on RHEL 6 using Postfix MTA. We have asked the user community for assistance, but we received no response.

**Comment by ikedas** [comment]
Hi,

Possiblly Sympa 6.2.x may not break S/MIME messages.
  https://sourcesup.renater.fr/tracker/index.php?func=detail&aid=8416&group_id=23&atid=167

Please check it.

If you encounter the problem with recent version of Sympa, please show us some samples of messages.

**Comment by iulistadmin** [comment]
Thank you. We weren’t aware this was corrected in the newer release. We do want to upgrade, and this gives us even more reason to do so.

 

Tim Silvers

Campus Communications Infrastructure

Indiana University

**Comment by ikedas** [comment]
No more report.  This issue is closed by now.
