### ISSUE TITLE
Spaces in email subject are deleted when there is accents

### ISSUE THREAD

**Issue by thierrytiti** [sympa-community/sympa#162]
The subject of an email "Bonjour à tous" is tranformed in "[listname] Bonjourà tous"

**Comment by ikedas** [comment]
Hi @thierrytiti,

Could you please show us the raw header of message both before and after passing mailing list?
  - To get a message both before and after passing the list, send a message to the list CC'ing yourself.
  - To see raw header, use the function such as "View message source" on your mailer (for this issue, the header especially "Subject" field is needed: message body is not needed).

Regards,
-- Soji

**Comment by thierrytiti** [comment]
Hi,

I tryed with another email client: it's a client bug on partially encoded subjects.
It works correctly with thunderbird.

1/
Original Email has header
Subject: =?utf-8?Q?Bonjour_=C3=A0_tous?=

This is dispayed as "Bonjour à tous"

2/
The email received via Sympa has headers:
Thread-Topic: Bonjour =?utf-8?Q?=C3=A0_tous?=
Subject: [testlistes] Bonjour =?UTF-8?Q?=C3=A0?= tous

This is displayed as "[testlistes] Bonjouràtous"

Regards,
Thierry
