### ISSUE TITLE
automatic mail unsubscribtion on error on a list

### ISSUE THREAD

**Issue by PhilLAL** [sympa-community/sympa#163]
Hi, 
I would like to know if there is an option to automatically unsubscribe a mail address when it is on error. 
I have searched into the doc but did not find anything on this topic, but perhaps did I miss this part...
Thanks and happy new year.

edit: we currently have a 6.2 sympa, and we seem to loose some mail adress on some lists since we start up the server after importing from googlelist, so I wonder if there is an option which could explain this behaviour.

**Comment by ikedas** [comment]
Hi @PhilLAL,

On List Admin page, go to [Edit list config] - [Bounces] and see the help.

**Comment by PhilLAL** [comment]
thank you !
