### ISSUE TITLE
Message de désabonnement

### ISSUE THREAD

**Issue by Boutin-christian** [sympa-community/sympa#1643]
Bonjour

lors du désabonnement via l'interface Web

le message suivant est envoyé

Vous ([christian.boutin@lenord.fr](mailto:christian.boutin@lenord.fr)) êtes désabonné(e) de la liste [syndicat-123@liste.lenord.fr](mailto:syndicat-123@liste.lenord.fr)

Vous pouvez cependant vous réabonner en cliquant ici :
http://sympa-rec.intranet.cg59.fr/sympa/subscribe/syndicat-123

est-il possible de paramétrer ce message pour ne pas afficher la partie réabonnement ?

Seconde question

dans le paramétrage message type ajouté en en fin est -il possible de mettre un lien plutôt qu'une adresse en clair ?
exemple
Pour vous désabonner merci d'utiliser l'url suivant : https://sympa-rec.intranet.cg59.fr/sympa/signoff/syndicat-123/

D'avance merci

Cordialement

**Comment by ikedas** [comment]
Bonjour @Boutin-christian ,
S'il vous plaît pourriez-vous nous indiquer la version de Sympa ?

Hi @Boutin-christian ,
Could you please tell us the version of Sympa?

**Comment by ikedas** [comment]
フランス語はほとんど書けませんので英語で答えさせてください (読むのは問題ありません。機械翻訳を使えます)。

Permettez-moi de répondre en anglais, car j'ai du mal à écrire le français (Je n'ai aucun problème pour lire le français. Je peux utiliser la traduction automatique). 

> lors du désabonnement via l'interface Web
> 
> le message suivant est envoyé
> 
> Vous ([christian.boutin@lenord.fr](mailto:christian.boutin@lenord.fr)) êtes désabonné(e) de la liste [syndicat-123@liste.lenord.fr](mailto:syndicat-123@liste.lenord.fr)
> 
> Vous pouvez cependant vous réabonner en cliquant ici : http://sympa-rec.intranet.cg59.fr/sympa/subscribe/syndicat-123
> 
> est-il possible de paramétrer ce message pour ne pas afficher la partie réabonnement ?

You may customize the template file `mail_tt2/bye.tt2` in [$DEFAULTDIR](https://www.sympa.community/manual/layout.html#defaultdir).  _Note_ that you must not modify this file directly: files under $DEFAULTDIR will be overwritten at the time of upgrading.  Instead, you should copy it to appropriate place and edit it (See the [description](https://www.sympa.community/manual/customize/basics-templates.html#location) for more details).

Templates includes texts in english: They are translated the other languages at runtime.  You may replace them with french texts in the file you edits.

> dans le paramétrage message type ajouté en en fin est -il possible de mettre un lien plutôt qu'une adresse en clair ? exemple Pour vous désabonner merci d'utiliser l'url suivant : https://sympa-rec.intranet.cg59.fr/sympa/signoff/syndicat-123/

I don't understand what you mean by "le paramétrage message type ajouté en fin". Could you please you show me a specific example?
