### ISSUE TITLE
Switch Font Awesome from 4 to 6

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#1656]
Expected Behavior
-----------------

Font Awesome should be up-to-date, i.e. 6.4.x.

Current Behavior
----------------

Font Awesome bundled in Sympa is outdated, i.e. 4.3.0.

Possible Solution
-----------------

Upgrade Font Awesome: See also [the instruction](https://fontawesome.com/docs/web/setup/upgrade/).

**Comment by racke** [comment]
I looked up the status of the Debian package, which says:

 Please note that this package provides Font Awesome 4 (not Font Awesome 5 or Font Awesome 6 which are different fonts with different licensing).

What is the difference between these releases?

There is also the fork of Font Awesome, which was created because of the licensing situation (if I remember correctly).

**Comment by ikedas** [comment]
> I looked up the status of the Debian package, which says:
> 
> Please note that this package provides Font Awesome 4 (not Font Awesome 5 or Font Awesome 6 which are different fonts with different licensing).
> 
> What is the difference between these releases?

[Icon names changed](https://fontawesome.com/v5/docs/web/setup/upgrade-from-v4#icon-name-changes-between-version-4-and-5) after FA4.  So we have to modify templates.

Abolut the license, it seems for me that [FA4](https://fontawesome.com/v4/license/) and [FA6 Free](https://fontawesome.com/license/free) differ in some details but basically they keep the free/open source license.  Am I right?

> There is also the fork of Font Awesome, which was created because of the licensing situation (if I remember correctly).

I just learned about Fork Awesome. I don't see where the [ForkA](https://forkaweso.me/Fork-Awesome/license/) license improves things.

**Comment by ikedas** [comment]
These are all icons currently used by Sympa.

There appears to be a slight design change (Especially noticeable in 6, 22, 37, 38, etc.).

| Font Awesome 4.3.0 | Font Awesome 6.4.0 Free (red: name changed) |
| ---------------------- | --------------------------- |
| ![image](https://user-images.githubusercontent.com/5743546/231363179-70d96323-8831-4a36-b04e-84fbc214001e.png) | ![image](https://user-images.githubusercontent.com/5743546/231363281-73ebdb02-4ff5-4034-b931-d84bcafd0989.png) |

**Comment by ikedas** [comment]
Please check the PR above.  Thanks!

**Comment by ikedas** [comment]
PR above was applied to [lists.sympa.community](https://lists.sympa.community/).

**Comment by ikedas** [comment]
Ready.
