### ISSUE TITLE
Wrong French translation branch

### ISSUE THREAD

**Issue by SansPseudoFix** [sympa-community/sympa#1658]
Version
-------
 
6.2.68

Expected behavior
-----------------

Current version of sympa to be sync on correct French translation branch.

Actual behavior
---------------

`smimeorowner` and `owner` have same translations. 

![ksnip_20230419-111535](https://user-images.githubusercontent.com/6507951/233028836-a7fe6ecb-f556-4220-842d-a1ca9d4ba3a1.png)

But if you look at [tanslate.sympa](https://translate.sympa.community/fr/web_help/translate/fr.po#search=smimeorowner&sfields=source,target), `smimeorowner` has a different (and correct) translation. Translations seem to be stuck on the old main branch.

Additional information
----------------------
Tested on Framalistes.

**Comment by ikedas** [comment]
Hi @SansPseudoFix ,
Please create an account on the [translate.sympa.community](https://translate.sympa.community) server (if you haven't yet done so) and correct the translation. You seem to know more about French than most people here.

**Comment by ikedas** [comment]
Sorry @SansPseudoFix . I see that you have already fixed the translation on [translate.sympa.community](https://translate.sympa.community) .

Changes made on the translation server are automatically accumulated by the daily job into a pull request. This PR is finally merged only just before a new release.

To see the latest PR, look for the item titled "Update translation" in [Pull Requests](/sympa-community/sympa/pulls).

**Comment by ikedas** [comment]
It would be greatly appreciated if you could fix the other translation as well.  Thank you.

**Comment by SansPseudoFix** [comment]
It's ok! :)
Thank you for the hint. We have added the latest translations to Framalistes in the meantime.
