### ISSUE TITLE
Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: <message> 'setCustom' already defined

### ISSUE THREAD

**Issue by Nalisman385** [sympa-community/sympa#1676]
Version
-------
6.2.72

Installation method
-------------------
source package or rpm

Expected behavior
-----------------
no error

Actual behavior
---------------
error throw when $soapClient = new SoapClient($soapServer) is called after upgrade to .72
 
PHP Fatal error:  Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: <message> 'setCustom' already defined in /opt/sympa/etc/sympa/docs/subscribe/subscribe.php:155\nStack trace:\n#0 /opt/sympa/etc/sympa/docs/subscribe/subscribe.php(155): SoapClient->SoapClient()\n#1 {main}\n  thrown in /opt/sympa/etc/sympa/docs/subscribe/subscribe.php on line 155, referer: https://ev.ritmailtest.rit.edu/subscribe/sample.php

Steps to reproduce
------------------
$soapServer = "https://$site/sympa/wsdl";
$soapClient = new SoapClient($soapServer);
$soapClient->debug_flag=true;

Additional information
----------------------
The following lines in sympa.wsdl appear to be the issue:

<message name="setCustom">
        <part name="list" type="xsd:string"/>
        <part name="key" type="xsd:string"/>
        <part name="value" type="xsd:string" xsd:minOccurs="0"/>
</message>

<message name="setCustom">
        <part name="return" type="xsd:boolean"/>
</message>

Changing to the following resolves the issue:

<message name="setCustomRequest">
        <part name="list" type="xsd:string"/>
        <part name="key" type="xsd:string"/>
        <part name="value" type="xsd:string" xsd:minOccurs="0"/>
</message>

<message name="setCustomResponse">
        <part name="return" type="xsd:boolean"/>
</message>

**Comment by Nalisman385** [comment]
Addendum, the XML excerpts got removed from the bug report:

Lines 310, 316 both have message name="setCustom", where message name="setCustomRequest" and message name="setCustomResponse" should be present, respectively.

**Comment by ikedas** [comment]
Hi @Nalisman385 ,
Thank you for reporting bug.  Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/50e164e.patch) and confirm that it works?

**Comment by Nalisman385** [comment]
Confirmed, I have that in my test environment
