### ISSUE TITLE
Require click to send email on auto_signoff

### ISSUE THREAD

**Issue by zzottel** [sympa-community/sympa#168]
On a newly created list, one member was on a corporate outlook.com account.

It seems that at least with certain settings turned on, Microsoft visits every link present in emails sent to an email account (probably for protection against malicious links, and I guess they like building profiles about their users this way, too).

So, as in the message footer, there's a link to auto_signoff in my list, Microsoft visited that link. Then the confirmation email came in, and Microsoft visited that link, too, and the user was unsubscribed without any action on his part. (I could see in the logs that both visits came from Microsoft IP addresses.)

This could be mitigated by requiring the user to click a button for sending the confirmation email.

**Comment by ikedas** [comment]
Hi @zzottel,

Recent version of Sympa requests confirmation when the user visits auto_signoff link.  What version of Sympa are you using?

**Comment by zzottel** [comment]
Ah, that could be. Debian is currently on 6.2.16. Maybe I could switch to testing or unstable. Do you know in wich version that was changed?

**Comment by zzottel** [comment]
Found it, seem to have benn 6.2.19b.1. Thanks for the info! :-)
