### ISSUE TITLE
sympa dies on incoming mail: DIED: Can't locate object method "new" via package "Mail::AuthenticationResults::Header" at /usr/share/sympa/lib/Sympa/Message.pm line 717.

### ISSUE THREAD

**Issue by DF3MS** [sympa-community/sympa#1681]
Version
-------

6.2.72

Installation method
-------------------

yum via default repo on centos7

Expected behavior
-----------------

sympa delivers incoming mails as expected

Actual behavior
---------------

sympa crashes with `DIED: Can't locate object method "new" via package "Mail::AuthenticationResults::Header" at /usr/share/sympa/lib/Sympa/Message.pm line 717.`

Steps to reproduce
------------------

send a mail to our instance

Additional information
----------------------

systemd-journal:
```
Jun 12 10:29:39 ml01.**** sympa_msg[23035]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <testliste1@***********.1686558185.22098>; envelope_sender=*****@********; message_id=eeb71707-3ea9-0822-660b-b14657be3a7e@******; sender=*****@********
Jun 12 10:29:39 ml01.**** sympa_msg[23035]: err main::#242 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessIncoming::_twist#202 > Sympa::Message::aggregate_authentication_results#717 DIED: Can't locate object method "new" via package "Mail::AuthenticationResults::Header" at /usr/share/sympa/lib/Sympa/Message.pm line 717.
Jun 12 10:29:39 ml01.**** systemd[1]: sympa.service: main process exited, code=exited, status=255/n/a
Jun 12 10:29:39 ml01.**** systemd[1]: Unit sympa.service entered failed state.
Jun 12 10:29:39 ml01.**** systemd[1]: sympa.service failed.
```

After a downgrade to version 6.2.70 all works fine.

**Comment by ikedas** [comment]
Hi @DF3MS ,
Please run following commands:
``` base
$ rpm -q sympa
$ rpm -q perl-Mail-DKIM
$ rpm -q perl-Mail-AuthenticationResults
```
and show us the results.

**Comment by DF3MS** [comment]
```
[root@ml02 ~]# rpm -q sympa
sympa-6.2.72-2.el7.x86_64
[root@ml02 ~]# rpm -q perl-Mail-DKIM
perl-Mail-DKIM-0.39-8.el7.noarch
[root@ml02 ~]# rpm -q perl-Mail-AuthenticationResults
package perl-Mail-AuthenticationResults is not installed
[root@ml02 ~]#
```
ml02 is my testing system, it is basically the same as ml01. I suspect a missing dependency-package "perl-Mail-AuthenticationResults"

**Comment by DF3MS** [comment]
yup. after installing the missing package sympa is now working.

**Comment by ikedas** [comment]
Thanks for confirming workaround.  I'll contact maintainer of EPEL package.

**Comment by maxCSA** [comment]
I had the same problem, so I installed the missing package, but now I have this error 
`DIED: Can't locate object method "extended_headers" via package "Mail::DKIM::Signer" at /usr/share/sympa/lib/Sympa/Message.pm line 475.`
Any solution?

Perl DKIM module is installed
```
 rpm -q perl-Mail-DKIM
perl-Mail-DKIM-0.39-8.el7.noarch
```
Thanks for you help

**Comment by maxCSA** [comment]
I opened separated issue since it might not be related with this issue : https://github.com/sympa-community/sympa/issues/1685
