### ISSUE TITLE
No longer able to see email that triggered bounce

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#1683]
Version
-------

Sympa 6.2.72,

Installation method
-------------------

Installed via EPEL repo on RHEL 7.9

Expected behavior
-----------------

Actual behavior
---------------

When checking a user why a message bounced (GET /sympa/ajax/viewbounce/listname?email=email39%40addresss.com&previous_action=editsubscriber HTTP/1.1" 200 2460 "https://sympa.oururl.com/sympa/editsubscriber/listname?email=email39%40addresss.com&previous_action=reviewbouncing" [...] in the logs), I no longer see the body of the message, only
--- Begin Message ---
--- End Message ---

![2023-06-13_08-20](https://github.com/sympa-community/sympa/assets/1931981/6d1ccd66-eae5-4aac-9336-99316adc8a68)

Steps to reproduce
------------------

Click on an email address of the review bouncing section, then on "latest error".

Additional information
----------------------

First installation since the sympa-ja.org repo is no longer was working. I also had to copy some awesome-font files to another directory as it didn't find them in me static_content_path and giving me 404s, so it may be a larger issue rather than a bug?

Thanks for looking into it.

**Comment by ikedas** [comment]
Sympa-JA.org packages could be updated by EPEL packages seamlessly.  If you have already been using the version 6.2.46 or later, you had already moved to EPEL.

fontawesome-font seems not be related to the reported problem.  If the problem occurs only with a particular bounce, then the bounce message may just be corrupted.

**Comment by laerm** [comment]
Hi @ikedas 

Indeed, it seems not all messages are problematic. I'll keep an eye out if anything like this happens in the future. Sorry for the noise, I should have checked more cases!
