### ISSUE TITLE
DIED: Can't locate object method "extended_headers" via package "Mail::DKIM::Signer" 

### ISSUE THREAD

**Issue by maxCSA** [sympa-community/sympa#1685]
**Note by admin: This is a problem specific to RPM distribution in EPEL 7 repository only.**

---

Version
-------

6.2.72-2.el7 (EPEL)

Installation method
-------------------

EPEL on RHEL 7

Expected behavior
-----------------

Send email as usual

Actual behavior
---------------

Crash with the following error message: 
`Jun 13 11:13:25 mx bulk[3285]: err main::#160 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessOutgoing::_twist#412 > Sympa::Message::dkim_sign#475 DIED: Can't locate object method "extended_headers" via package "Mail::DKIM::Signer" at /usr/share/sympa/lib/Sympa/Message.pm line 475.`

Steps to reproduce
------------------

Send any message to any list

Additional information
----------------------

Once crashed, no message can be sent.
I had this error right after fixing this other bug : https://github.com/sympa-community/sympa/issues/1681

DKIM package is installed
```
rpm -q perl-Mail-DKIM
perl-Mail-DKIM-0.39-8.el7.noarch
```

**Comment by ikedas** [comment]
Hi @maxCSA , thank you for reporting the problem.

This is a problem specific to RPM distribution in EPEL 7 repository.

I prepare [a patch](https://github.com/sympa-community/sympa/commit/4102670.patch) for now.  Could you please apply it and check if the problem will be solved?

**Comment by ikedas** [comment]
Hi again,

The patch has been updated.  Please apply [this patch](https://github.com/sympa-community/sympa/commit/8e4d671.patch) and check if the problem will be solved.

**Comment by xavierba** [comment]
@maxCSA could you please give a try at this build ?
https://koji.fedoraproject.org/koji/taskinfo?taskID=102138575
It has both the Requires for perl-Mail-AuthenticationResults added and the patch from @ikedas.
I'll push it to EPEL 7 testing repo once I'll have your feedback

**Comment by maxCSA** [comment]
@xavierba I tested the packages and I had no problem.

I'm not that familiar with this kind of testing, so just to be sure, I downloaded and installed  sympa-6.2.72-3.el7.x86_64.rpm and sympa-nginx-6.2.72-3.el7.x86_64.rpm (downloaded from here : https://koji.fedoraproject.org/koji/buildinfo?buildID=2215304). It automatically installed the perl-Mail-AuthenticationResults depedency. Once done, I got a nice "Powered by Sympa 6.2.72" on the web interface and no more "DIED" error when sending message.

Thanks to @ikedas for the quick fix.

**Comment by xavierba** [comment]
@maxCSA you did it right, sorry for not giving more directions for testing.
I'll submit the package to EPEL 7 testing. Please make sure to let us know if you find more issues.
I believe the patch is just a stop gap workaround until a better integrated fix can be worked on by @ikedas.
That being said, I'm going to be out until next monday evening starting end of the afternoon, I'll probably not be able to do much until next Tuesday.

**Comment by xavierba** [comment]
Here's the tracking link for the update:
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2023-ea3f56bcc8
It will go to EPEL 7 stable repository in 7 days. The delay can be shorter if it receives enough positive karma.

**Comment by ikedas** [comment]
The problematic behavior has been fixed on the downstream.  This issue is closed.

**Comment by ikedas** [comment]
Thanks for reporting & fixing, @maxCSA & @xavierba !
