### ISSUE TITLE
Changing the description of the DSN used for list moderated notification emails

### ISSUE THREAD

**Issue by fusenuk** [sympa-community/sympa#1688]
Expected Behavior
-----------------
When sending an email to a list that is moderated, the sender should receive a easily understandable notice that the message has not been distributed due to awaiting moderator approval.

Current Behavior
----------------
The recent change via #1508 means that you no longer send out an easily understandable notice but instead respond with a SMTP status code of 4.3.0 but with the default description of "Other or undefined mail system status".

Possible Solution
-----------------
Change the description to be something like "Your email is awaiting approval from the owner of the mailing list"

Context
-------
Previously Sympa sent out the plain English email notifying of awaiting modification. Now it ends up with the sending mail server sending a random unexplained bounce message.

And example of this is from Office365 -

```
Delivery is delayed to these recipients or groups:

[sympa-settings-test@xx.ac.uk](mailto:sympa-settings-test@xx.ac.uk)

Subject: Mod email test

This message hasn't been delivered yet. Delivery will continue to be attempted.


Diagnostic information for administrators:

Generating server: xx.ac.uk

[sympa-settings-test@xx.ac.uk](mailto:sympa-settings-test@xx.ac.uk)
xx.ac.uk
Remote server returned '554 5.4.0 <xx.ac.uk #4.3.0 X-Sympa; Other or undefined mail system status>'

Original message headers:

```

I don't think that is very helpful for end users.

**Comment by ikedas** [comment]
The DSN Sympa itself returns is as below.  It includes human-readable description.
```
This is an automatic response sent by Sympa Mailing Lists Manager.
Your message to the list 'sandbox' has been forwarded to the moderator(s)

------------------------------------------------------------------------------

Reporting-MTA: dns; sympa.community
Arrival-Date: Thu, 22 Jun 2023 00:52:06 +0000

Final-Recipient: rfc822; sandbox@sympa.community
Action: delayed
Status: 4.3.0
Remote-MTA: dns; sympa.community
Diagnostic-Code: X-Sympa; Other or undefined mail system status
------------------------------------------------------------------------------
(Original message header follows)
```

Somehow, the M365 server seems to have seen this message returned by Sympa and reported that a "persistent error" (554 5.4.0) had occurred.

The Diagnostic-Code seems to be preserved, so I'll try to improve this.

**Comment by ikedas** [comment]
@fusenuk , please check the PR above..

**Comment by fusenuk** [comment]
Those new DSN descriptions look good thanks.

**Comment by agouaux** [comment]
Holy Crap this is causing unimaginable pain for us. How the hell is "X-Sympa; Other or undefined mail system status" human readable? Seriously. To an engineer, sure. To the average Sympa user, oh hell no. 

Beginning to really regret doing a point release update to Sympa right before the Fall semester. I'm using to point releases not being major pain points. However, this one sure hasn't proven to be so far based on the number of support calls we're getting.
