### ISSUE TITLE
Font-Awesome CSS files failing to load due to 404 file not found responses

### ISSUE THREAD

**Issue by fusenuk** [sympa-community/sympa#1691]
Version
-------
6.2.72

Installation method
-------------------
RHEL YUM package

Expected behavior
-----------------
The new font-awesome icons to show up in the browser.

Actual behavior
---------------
The new font-awesome CSS files are not loading. The URLs return 404 response codes, so none of the new icons are showing.

Steps to reproduce
------------------
Browse to the main index page and look at the three main links in the image below. None of them show whatever circle icon they are supposed to show.

Additional information
----------------------
Very strangely the license file does load successfully at https://lists.kent.ac.uk/static-sympa/fonts/font-awesome/LICENSE.txt

Also the font files load at https://lists.kent.ac.uk/static-sympa/fonts/font-awesome/webfonts/fa-brands-400.ttf

It seems to be a specific issue with just the CSS files.

I've included two screenshots below showing the 3 404 responses to trying to load the new CSS files yet when I search for the files on the server then they appear exactly where they should be. None of the Sympa config settings for static content have been changed from the default.

![image](https://github.com/sympa-community/sympa/assets/4472966/46297c40-4369-49c2-9920-6035ddf26f7e)

![image](https://github.com/sympa-community/sympa/assets/4472966/1ee3f57e-c935-4ffc-a91b-1d08be27ee7b)

**Comment by ikedas** [comment]
@fusenuk , please show exact version of RPM package.

**Comment by fusenuk** [comment]
Installed Packages
Name        : sympa
Arch        : x86_64
Version     : 6.2.72
Release     : 2.el7
Size        : 16 M
Repo        : installed
From repo   : university_of_kent_EPEL_epel7-x86_64
Summary     : Powerful multilingual List Manager
URL         : http://www.sympa.org
License     : GPL-2.0-or-later AND (OFL-1.1-RFN AND MIT) AND OFL-1.1-RFN AND MIT and (MIT OR GPL-2.0-only)
Description : Sympa is scalable and highly customizable mailing list manager. It
            : can cope with big lists (200,000 subscribers) and comes with a
            : complete (user and admin) Web interface. It is internationalized,
            : and supports the us, fr, de, es, it, fi, and chinese locales. A
            : scripting language allows you to extend the behavior of commands.
            : Sympa can be linked to an LDAP directory or an RDBMS to create
            : dynamic mailing lists. Sympa provides S/MIME-based authentication
            : and encryption.


We host a local repo that pulls packages from the EPOL repo (https://www.redhat.com/en/blog/whats-epel-and-how-do-i-use-it)

**Comment by ikedas** [comment]
Please run following command:
```
# rpm -V sympa sympa-httpd
```
(If you have installed `sympa-nginx` or `sympa-lighttpd`, replace `sympa-httpd` with it)
then show us the entire output.

**Comment by fusenuk** [comment]
Thanks ikedas that highlighted the root cause.

`/usr/share/sympa/static_content/fonts/font-awesome/css# rpm -V sympa sympa-httpd
SM5..U.T.  c /etc/sympa/auth.conf
S.5....T.  c /etc/sympa/create_list.conf
S.5..UGT.  c /etc/sympa/edit_list.conf
.....UG..    /etc/sympa/scenari
S.5..U.T.  c /etc/sympa/sympa.conf
S.5..UGT.  c /etc/sympa/topics.conf
.....UG..    /etc/sympa/web_tt2
S.5....T.    /usr/share/sympa/default/mail_tt2/moderate.tt2
S.5....T.    /usr/share/sympa/default/web_tt2/list_menu.tt2
.......T.    /usr/share/sympa/default/web_tt2/subscriber_table.tt2
missing   c /etc/httpd/conf.d/sympa.conf`

The missing httpd sympa.conf is being replaced by a custom .conf file with the following Aliases in

`  ## Vhost docroot
  DocumentRoot "/var/www/html"
  ## Alias declarations for resources outside the DocumentRoot
  Alias /export "/opt/sympa-local/export"
  Alias /static-sympa/fonts/font-awesome/css "/usr/share/font-awesome-web/css"
  Alias /static-sympa/fonts/font-awesome/fonts "/usr/share/fonts/fontawesome"
  Alias /static-sympa/css "/var/lib/sympa/css"
  Alias /static-sympa/pictures "/var/lib/sympa/pictures"
  Alias /static-sympa "/usr/share/sympa/static_content"
  ScriptAlias /sympa "/usr/libexec/sympa/wwsympa-wrapper.fcgi"
`
I've temporarily copied all of the missing CSS files to the aliased directory

`/usr/share/sympa/static_content/fonts/font-awesome/css# cp *.css /usr/share/font-awesome-web/css/`

and that has returned the 'proper' look to Sympa.

Are those Alias' normally created by the Sympa install or are users expecting to manually add them to the HTTPD config at install?

The above config was completed by a colleague who has now left.

**Comment by ikedas** [comment]
Remove (or comment out) these lines:
``` code
Alias /static-sympa/fonts/font-awesome/css "/usr/share/font-awesome-web/css"
Alias /static-sympa/fonts/font-awesome/fonts "/usr/share/fonts/fontawesome"
```
and restart httpd service.

----
Also note that it would be better to use the original `sympa.conf` for httpd and edit it to suit your site's needs. Otherwise, it will be re-installed each time you update the `sympa-httpd` package.
