### ISSUE TITLE
Failing to import lists from an older sympa

### ISSUE THREAD

**Issue by thc2cat** [sympa-community/sympa#1693]
Hi.

I'm  trying to upgrade an very old server, and i have issues to import lists.

Version
-------
Older versions :  Sympa 6.2.16, mysql  (Ver 14.12 Distrib 5.0.95)
dev-server :  CentOS8 / Sympa 6.2.72 / mysql  (Ver 8.0.26)

Installation method
-------------------

Sympa was installed from yum rpm on both hosts.

Expected behavior
-----------------

I was expecting that db upgrade would retrieve all lists.

Actual behavior
---------------

sympa.pl -upgrade doesn't seem to fail, but i got zero list at the end

Additional information
----------------------

How i do it : 
 OLD: mysqldump sympa -uoperator -p<PASS> > sympa.dump
 vi sympa.dump to replace instances of oldserver hostname to newserver hostname

 NEW SERVER: 
     mysql> drop database sympa ;
     mysql> CREATE DATABASE sympa CHARACTER SET utf8;
     mysql> drop  USER 'sympa'@'localhost'  ;
     mysql> CREATE USER 'sympa'@'localhost' IDENTIFIED BY '<SYMPASSWD>';
     mysql> GRANT ALL PRIVILEGES ON sympa.* to 'sympa'@'localhost';

 mysql -u sympa  -p  sympa < /tmp/sympa.dump

 vi  /etc/sympa/data_structure.version for replacing 6.2.16 version.
 sympa.pl --upgrade
  (Got no real errors from this, versions guessed right.
... sympa[43099]: notice Sympa::CLI::upgrade::_upgrade() Upgrading from 6.2.16 to 6.2.72...
...
...notice Sympa::CLI::upgrade::_upgrade() Upgrade process finished

But index list in wwsympa show zero lists

Any ideas ?
Thanks

**Comment by ikedas** [comment]
Hi @thc2cat ,

Please read [the manual](https://www.sympa.community/manual/upgrade/move.html) and follow the steps described there.
