### ISSUE TITLE
List inclusion in data_source no longer working as expected

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#1694]
A list owner contacted us saying that the inclusion of another list is not working as expected since the last update, and unable to say how long this has been happening.

List A has a number of members added manually, as well as members from list B, added via a data_source include_list (which is now include_sympa_list, correct?). Adding an inclusion no longer does a initial include of all of list B members, but only changes made to list B since inclusion.

Version
-------

 v6.2.72 on RHELv7.9

Installation method
-------------------
Via EPEL repo

Expected behavior
-----------------
When I include a list B into list A, I expect the members of list B to be added to list A.

Actual behavior
---------------

List A contains 100 members
List B contains 10 members

I include list B to add its members to list A -> nothing happens, no error in log. List A still contains only 100 users, even after inclusion time has run out, or I force data sync.
If I add 1 user to list B, this user is then included in list A, which then contains 101 users. The 10 initial members of list B are not included.

Additional information
----------------------
I've also noticed that on the member list page, for users added via the inclusion, in the sources column, I have some sort of hash (for example "05c07645"). This might have been the case before, but is not hugely helpful.

**Comment by ikedas** [comment]
Hi @laerm ,

As discussed [here](https://lists.sympa.community/msg/en/2023-06/-1YwCyHtWdW5z_6b3w6McQ), subscribers who have been explicitly added to the list will not be affected by the inclusion settings, i.e. they will no longer added again, nor will they be deleted even if they are deleted from the source list.

Also, subscribers who have been explicitly deleted from the list are registered in the exclusion table and will be excluded from inclusion unless they are removed from that table.  To view or clear content of the exclusion table, follow [Exclude] link in the list members page.

---
> I've also noticed that on the member list page, for users added via the inclusion, in the sources column, I have some sort of hash (for example "05c07645"). This might have been the case before, but is not hugely helpful.

Please submit a new issue on this.

**Comment by laerm** [comment]
Thanks for your reply @ikedas !

I'm afraid I don't understand "only synchronize the users that "inclusion_label_susbscriber" is not NULL". How do I change this label? How do I get the same behaviour as before? We have a few lists that rely on this mechanism. I don't see anything in the changelog v6.2.72 unless I'm mistaken?

**Comment by ikedas** [comment]
> I'm afraid I don't understand "only synchronize the users that "inclusion_label_susbscriber" is not NULL".

I have _never_ said anything like that.  The `inclusion_label_susbscriber` column has nothing to do with the discussion here.

I said that only users who are not explicitly subscribed and not carried in the exclusion table are eligible for inclusion.

**Comment by ikedas** [comment]
Oops, the description of the link is a bit odd; please forget about the `inclusion_label_susbscriber`.

**Comment by laerm** [comment]
Hello @ikedas ,

Okay, I did indeed find a bunch of users on the /show_exclude/listname page. I restored them and all seems to be okay.

So am I right in thinking that users removed from list B, will then still be removed from list A, is that correct? I'm not sure how those users ended up on the exclusion list, is there a git issue where this change is explained so I can understand it properly?

I've opened an issue for the weird display on the members page here https://github.com/sympa-community/sympa/issues/1695

**Comment by ikedas** [comment]
> So am I right in thinking that users removed from list B, will then still be removed from list A, is that correct?

That's right.  The subscribers only included from the list B into A will be removed from A, if they no longer the subscribers of B.

> I'm not sure how those users ended up on the exclusion list, is there a git issue where this change is explained so I can understand it properly?

The subscribers explicitly deleted from the list (e.g. with web interface) are registered in the exclusion table.

> I've opened an issue for the weird display on the members page here #1695

Thanks!

**Comment by laerm** [comment]
Hello @ikedas ,

Thanks for clearing that up. I will keep an eye out for any weirdness from now on with the affected lists.
