### ISSUE TITLE
WWSympa: Switch to Foundation 6

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#170]
Currently web interface uses [Foundation 5.5.3](https://foundation.zurb.com/sites/docs/v/5.5.3/).

Foundation 5 is slightly older and not expected further maintenance.  Foundation for Site 6 would be better.  So I propose replacing Foundation bundled in Sympa source with Foundation 6.
  - [Foundation 6.4.x](https://foundation.zurb.com/sites/docs/) would be used.

Replacement would be better to be done in separate branch, then after careful tests, it may be merged into master (and current sympa-6.2).

If no objection, I'll add branch and work with it.  Milestone may be 6.2.28 (by now the next of the next stable).

----
Notice
------
(update: 2018-01-31)
  * The [foundation6](https://github.com/sympa-community/sympa/tree/foundation6) branch was created. Please use this branch to work for this issue.
  * Feel free to submit PR.  However note that base branch of PR should be `foundation6` (neither `sympa-6.2` nor `master`).
  * Feel free to merge PR, if you are allowed to do.

**Comment by xavierba** [comment]
On the same subject, there is also the bundled modernizr. Bundled version is 2.6.2, latest from 2.x branch is 2.8.3. The 2.x branch is unmaintained upstream, which is currently at 3.5.0 (https://modernizr.com/news/modernizr-3-5-0). Let me know if you'd rather want this to be tracked in another issue.
Still on the JS subject, it would be nice to make sure jquery 3 deprecations are addressed and jquery-migrate removed. Again, let me know if you want a new issue for this one.

**Comment by ikedas** [comment]
@xavierba, I have no objection to deal with other JS stuff. Because Foundation more or less depends on them (e.g. removal of jquery-migrate would be done).

**Comment by racke** [comment]
Sounds good to me :-)

**Comment by ikedas** [comment]
Hi all,
New branch was created.
  * Please read the "Notice" added in the first comment.

Recently, only Foundation has been updated and rendering is broken.

**Comment by ikedas** [comment]
PR #187 will be merged in a few days, but `foundation6` branch will be kept unmerged during Sympa 6.2 beta.  Please check out and test code in `foundation6` branch.

**Comment by xavierba** [comment]
#290 removes some files that are now useless.

**Comment by xavierba** [comment]
www/Makefile.am fixes: #317

**Comment by ikedas** [comment]
Hi everybody,

foundation6 branch was successfully merged.  It will be available on the next beta, 6.2.33b.2.

Thanks so much for help!
