### ISSUE TITLE
Email went out unmoderated

### ISSUE THREAD

**Issue by Scoopdiggity** [sympa-community/sympa#1711]
Hi, we have Sympa installed as a web form.  I'm not using terminal command lines to operate it.
We're using 6.2.7.0. (i think)
We created a list, and sent out an email, but we expected the email to go to a moderator, as it has so many times before.
However, this time, it just delivered to all members of the list, rather than asking for moderation.
Is there a simple flag that I missed which says "force moderation" or something like that?
Thanks much.  This is my 3rd time using it - and I guess it shows..
Thanks for your help

**Comment by ikedas** [comment]
Hi @Scoopdiggity ,
Could you please show us the "Who can send messages (send)" setting of the list in question?

**Comment by ikedas** [comment]
Hi @SansPseudoFix ,

Could you please show us the "Who can send messages (send)" setting of the list in question?

**Comment by SansPseudoFix** [comment]
**Moderated, even for moderators** (aka `editorkeyonly`).

![ksnip_20230904-161238](https://github.com/sympa-community/sympa/assets/6507951/2a6f8e31-0c14-45f7-8c0a-53e4fec882f4)

**Comment by ikedas** [comment]
There seem any noticeable changes in the processing of the `send` parameter during 6.2.68 to 6.2.72.  @Scoopdiggity , if possible, could you check with 6.2.72 to see if the problem is resolved?
