### ISSUE TITLE
Location of static_content and css directories

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#172]
Hi,

My understanding is the static_content name comes from the fact that it is statically served by the http server, while the remaining is served by cgi.
Most of what is installed in static_content directory is indeed data that does not change (fonts, javascripts) and thus can be installed readonly and owned by root user. This seems to fit well to $datadir$.
The only exception is the css subdirectory, which holds content dynamically generated by sympa and thus needs to be writeable by sympa user. As this is a subdirectory of static_content, this gets installed into $datadir$, but would seems to better fit into $localstatedir$.
I would suggest to split location of the css directory from the location of the static_content directory. The css directory could then be installed into $localstatedir$ while the static_content directory is installed into $datadir. This would probably mean the http conf needs to be tweaked to acknowledge for this change.

Does that make sense ?

Regards,
Xavier

**Comment by ikedas** [comment]
Hi Xavier,
I feel it making sense.  Currently, default value of `css_path` parameter is derived from `static_content_path` parameter (it's STATICDIR by default). The former would have the default location of its own.

**Comment by xavierba** [comment]
There is likely a similar issue with the pictures directory, which is located within staticdir too (and is also not created, like the css dir that got fixed with 85a6217e2657bfffdb884179d0feaed78c8b53e6)

**Comment by ikedas** [comment]
Changes look done.  I'll close this issue.

**Comment by ikedas** [comment]
Reopened to fix bug described in PR above.

**Comment by ikedas** [comment]
Seems fixed. Close.
