### ISSUE TITLE
INFO command pulls different owners than Web UI Users>Owners displays

### ISSUE THREAD

**Issue by iulistadmin** [sympa-community/sympa#1732]
We performed an upgrade a few years ago, however there are still many lists with owners and moderators in the config file.  When we go to the Web UI and selecting Users>Owners displays the correct owners from the database. We have noticed that when we send the command INFO listname to list@list.ourdomain.edu it returns the owners from the config file.

Version
-------

We are using release 6.2.72

Installation method
-------------------

Installed from RPM

Expected behavior
-----------------

When we go to the Web UI and selecting Users>Owners displays the correct owners from the database. 

Actual behavior
---------------

We have noticed that when we send the command INFO listname to list@list.ourdomain.edu it returns the owners from the config file. 

Steps to reproduce
------------------

Look at the list config file, /var/lib/sympa/list_data/list.ourdomain.edu/test-list/config, and see an owner:

owner
email me@ourdomain.edu
profile privileged
reception mail
visibility noconceal
gecos Gim
 
This is still in the config file above the subject although list was upgraded years ago. We go the web UI, https://list.ourdomain.edu/sympa then search for the list. On the admin page we select Users>Owners and it displays the correct owners from the database. 

When we send an email to lsit@list.ourdomain.edu with the subject INFO test-list, it sends an email with the owners pulled from the config file.

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @iulistadmin , thank you for reporting bug!

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/1734.patch) to your Sympa, restart the services and check if the problem will be solved?
