### ISSUE TITLE
Missing check on "Digest frequency"

### ISSUE THREAD

**Issue by fchaumontet** [sympa-community/sympa#1742]
Users can defined digest frequency with minutes = 99.
It make sympa process crash.
Attached files :
- log extract corresponding to the crash in ProcessDigest.pm
- print screen of Digest frequency define in the list configuration

Version
-------
Sympa 6.2.68

Installation method
-------------------
source package

Expected behavior
-----------------
Integrate a value check in new release in the configuration screen
Add a value check in ProcessDigest.pm that log the list name

Steps to reproduce
------------------
Go to "Edit list Config" > "Sending/receiving setup"
Enter hour or/and minute out of range (27h99m for example) 
Start sympa.

![ListConfig-InvalidDigestFrequency](https://github.com/sympa-community/sympa/assets/152282993/7f427d1d-2efd-4fe1-aece-d51b10dff121)
[SympaLogExtract-hide.log](https://github.com/sympa-community/sympa/files/13488136/SympaLogExtract-hide.log)

**Comment by ikedas** [comment]
@fchaumontet , thank you for reporting bug!

Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/aa98920aa97a2c852921003401acad99baacce9e.diff) and check if the problem will be solved?

**Comment by fchaumontet** [comment]
Hi, 
We just try the patch.
It work for minutes but not for hours
![image](https://github.com/sympa-community/sympa/assets/152282993/275c0706-f780-4fe6-9079-c81e88c9c12b)

**Comment by ikedas** [comment]
Sorry.  Could you please apply [additional patch](https://github.com/sympa-community/sympa/commit/3c37ca0fb38e12f6578ae5b55fd203c19e9a54f4.diff) and check again?

**Comment by fchaumontet** [comment]
Hello, 
It looks good.
Thanks for the patch.
Regards
