### ISSUE TITLE
Moderation links need login

### ISSUE THREAD

**Issue by woodfighter** [sympa-community/sympa#1746]
Version
-------
Sympa 6.2.72

Installation method
-------------------
installed from FreeBSD ports

Expected behavior
-----------------
Clicking on the links in mails sent to moderators for approval/rejection by sympa in lists with a send-scenario like
```
title.gettext Moderated, even for moderators

true()                             smtp,md5,smime        -> editorkey
```
while not logged in don't need the user to login. Links look like
https://sympa.example.org/sympa/distribute/listname/d3b07384d113edec49eaa6238ad5ff00
https://sympa.example.org/sympa/reject/listname/d3b07384d113edec49eaa6238ad5ff00

Actual behavior
---------------
User is presented with an error message “ERROR (reject) - Authorization rejected. Maybe you forgot to log in?”

Steps to reproduce
------------------

1. Send mail to list with the above-mentioned send scenario, where you are a moderator.
2. Logout from the mailing lists website.
3. Click on the distribute or reject link in the mail sent to moderators.
4. Be presented with an error and a login page and the message is kept waiting in the moderation queue.

Additional information
----------------------
According to user information this behavior changed with the update from version 6.2.70.

**Comment by ikedas** [comment]
Authentication is also required for `send.editorkeyonly` scenario with previous version of Sympa.

I suppose that that user experienced session expiration.

**Comment by woodfighter** [comment]
My colleague seems to have found what the user was missing: 3341d035f01e654dfd8bf3b347535d2ebf25785d removed the mailto-links from the mail. We'll adjust our templates. Sorry for wasting time.
