### ISSUE TITLE
Editors defined from a SQL source missing people

### ISSUE THREAD

**Issue by Kkspike** [sympa-community/sympa#1759]
We have numerous lists configured by families. I have a problem with one of the lists. We are getting the list of editors with a SQL query in one of our systems. The query returns 8 emails, when we synchronize the editors, only 5 are getting added/modified. I've checked on the SQL server and the query is good, I've logged on to the SQL server as the user who is using the query to get the editors and it returns 8 emails also. But whenever I syncrhonize the editors on that list, only the same 5 out of 8 are getting added/modified. I can't seem to find this action in the logs (I wanted to check if there was an error or something). What could cause the omittance of those 3 editors in particular ? They have no special characters in their emails (apostophes or the like)

Version
-------
[6.2.72](https://www.sympa.community/)

Installation method
-------------------
yum install

Expected behavior
-----------------
From a SQL source, 8 editors should be added/modified in the editors list

Actual behavior
---------------
Only the same 5 are added as editors out of the 8 from the query.

Additional information
----------------------
Actual editors
![editors](https://github.com/sympa-community/sympa/assets/35116060/1e84783b-cdcf-4319-b3be-c9366f3460ec)

From the query
![query](https://github.com/sympa-community/sympa/assets/35116060/b4ab20c7-6900-4e4f-a4e9-fe9a86f38cf7)

**Comment by racke** [comment]
Please check Sympa's exclusion_table for the missing editors.

**Comment by Kkspike** [comment]
One user was present in the exclusion_table for another list (excluded from subscribers). I removed her exclusion but it had no effect on this exclusion on the editors on the list.

**Comment by Kkspike** [comment]
Is there a verbose log somewhere that keeps track of members, owners and editors modifications from external sources ?

**Comment by ikedas** [comment]
Some kind of log should be output (Log level may not be changed.
).  How about restarting `rsyslog.service`?

**Comment by Kkspike** [comment]
This is something I haven't thought about. However, no luck even after restarting the rsyslog service. I'm at lost, here...
