### ISSUE TITLE
Sympa Accessibility Issue - 2 - Text content must exceed Color Contrast Ratio (CCR) of 3.1

### ISSUE THREAD

**Issue by rm1-uiuc** [sympa-community/sympa#1760]
The University of Illinois at Urbana-Champaign, Technology Services Accessibility Testing team conducted an Accessibility Review of Sympa on September 25, 2023 and found 26 issues that need to be fixed to make the interface accessible for visual impaired users.

Version
-------
6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------
Text content must exceed Color Contrast Ratio (CCR) of 3.1 for large and/or bolded text and 4.5 for any other size or style of text.

Actual behavior
---------------
Text content does not exceed Color Contrast Ratio (CCR) of 3.1 for large and/or bolded text and 4.5 for any other size or style of text.

Steps to reproduce
------------------
Sympa Accessibility Issue - 1 was determined by an Automation Tool Evaluation using AInspector and Siteimprove Accessibility Checkers as automated accessibility evaluation tools.

After running these automation tools the following issue was identified:

Text content must exceed Color Contrast Ratio (CCR) of 3.1 for large and/or bolded text and 4.5 for any other size or style of text. The higher the color contrast of text the easier it is to read, especially for people with visual impairments.

[1.4.3 Contrast (Minimum) (Primary)](https://www.w3.org/TR/WCAG21/#contrast-minimum)

![image](https://github.com/sympa-community/sympa/assets/144282683/66225ef5-851d-4f6e-b388-4e6476e404fa)

Additional information
----------------------
Attached is the Accessibility Review conducted on Sept 25,2023
[Tech Services Review - Accessibility Evaluation Report for Sympa.pdf](https://github.com/sympa-community/sympa/files/13549153/Tech.Services.Review.-.Accessibility.Evaluation.Report.for.Sympa.pdf)

**Comment by ikedas** [comment]
Hi @rm1-uiuc , 

The image you presented seems not generated with the default settings of Sympa.

* The wording will never be as presented in templates by default.
* Sympa by default will never have the color scheme as presented.

Furthermore, I do not understand what the red rectangle drawn in the screenshot represents.  Could you please explain?

**Comment by ikedas** [comment]
Is there any further information? If there are no developments, this issue will be closed for the present.
