### ISSUE TITLE
Sympa Accessibility Issue - 4 - Radio buttons must have grouping label

### ISSUE THREAD

**Issue by rm1-uiuc** [sympa-community/sympa#1762]
The University of Illinois at Urbana-Champaign, Technology Services Accessibility Testing team conducted an Accessibility Review of Sympa on September 25, 2023 and found 26 issues that need to be fixed to make the interface accessible for visual impaired users.

Version
-------
6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------
Radio buttons must have grouping label. 

Actual behavior
---------------
See picture below.

Radio button currently do not have a grouping label for screen reader to read.

Steps to reproduce
------------------
Sympa Accessibility Issue - 4 - was determined by an Automation Tool Evaluation using AInspector and Siteimprove Accessibility Checkers as automated accessibility evaluation tools.

After running these automation tools the following issue was identified:

Radio buttons must have grouping label. A related group of radio buttons must have a grouping label. Screen readers treat grouping labels differently than standard labels, typically speaking the grouping label only once when focus is first moved to one the groups controls.

[WCAG 3.3.2 Labels or Instructions (Primary)](https://www.w3.org/TR/WCAG21/#labels-or-instructions)

![image](https://github.com/sympa-community/sympa/assets/144282683/aeb1e724-c862-4538-b767-dedc996d370c)

Fig 4 No grouping label on radio buttons.

Additional information
----------------------
Attached is the Accessibility Review conducted on Sept 25,2023
[Tech Services Review - Accessibility Evaluation Report for Sympa.pdf](https://github.com/sympa-community/sympa/files/13549366/Tech.Services.Review.-.Accessibility.Evaluation.Report.for.Sympa.pdf)

**Comment by ldidry** [comment]
For this one, as `Campus Only Mailing list` is not a list template shipped with Sympa, I think that your administrator customised the template and made a mistake.

I mean: the two other radio buttons are grouped, as I feel from your screenshot. Those two other radio buttons use list templates shipped with Sympa.

**Comment by ldidry** [comment]
Note: I may be wrong, of course.

**Comment by ikedas** [comment]
@rm1-uiuc , coud you please provide the create_list template files for "Campus Only Maiing List (Intranet)" that that user deployed on their site?

**Comment by rm1-uiuc** [comment]
Good Afternoon ikedas, I opened these Accessibility Issues as the Product Owner of the service so will need to follow up with our Sympa Admin to get this additional information you need.   

Once I speak with them and get an answer I will provide another update.

Thanks
