### ISSUE TITLE
Sympa Accessibility Issue - 5 - Each LABEL element using the FOR attribute must reference a form control on the page

### ISSUE THREAD

**Issue by rm1-uiuc** [sympa-community/sympa#1763]
The University of Illinois at Urbana-Champaign, Technology Services Accessibility Testing team conducted an Accessibility Review of Sympa on September 25, 2023 and found 26 issues that need to be fixed to make the interface accessible for visual impaired users.

Version
-------
6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------
Each LABEL element using the FOR attribute must reference a form control on the page. LABEL elements are useful for screen readers to read when they reference or encapsulate form controls.

Actual behavior
---------------
LABEL elements using the FOR attribute do not reference a form control on the page

Steps to reproduce
------------------
Sympa Accessibility Issue - 5 - was determined by an Automation Tool Evaluation using AInspector and Siteimprove Accessibility Checkers as automated accessibility evaluation tools.

After running these automation tools the following issue was identified:

Each LABEL element using the FOR attribute must reference a form control on the page. LABEL elements are useful for accessibility only when they reference or encapsulate form controls. Change the LABEL element with the FOR attribute value 'owner' to reference a form control. Also change the LABEL element with the FOR attribute value 'list_type' to reference a form control.

[WCAG Level A 3.3.2 Labels or Instructions (Primary)](https://www.w3.org/TR/WCAG21/#labels-or-instructions)

![image](https://github.com/sympa-community/sympa/assets/144282683/8a16e8cb-80ad-4586-bbce-0c95808ee65c)

Fig 5 Label attribute with no form control issue.

Additional information
----------------------
Attached is the Accessibility Review conducted on Sept 25,2023
[Tech Services Review - Accessibility Evaluation Report for Sympa.pdf](https://github.com/sympa-community/sympa/files/13549437/Tech.Services.Review.-.Accessibility.Evaluation.Report.for.Sympa.pdf)

**Comment by ikedas** [comment]
Hi @rm1-uiuc ,

The reported issue was reproduced by me, but the screenshot presented is not due to default settings: The template looks customized.

This is the appearance by default:
![image](https://github.com/sympa-community/sympa/assets/5743546/630885bd-f4a3-4207-a36a-72007bcc73f4)
