### ISSUE TITLE
Sympa Accessibility Issue - 6 - Headings must be properly nested

### ISSUE THREAD

**Issue by rm1-uiuc** [sympa-community/sympa#1764]
The University of Illinois at Urbana-Champaign, Technology Services Accessibility Testing team conducted an Accessibility Review of Sympa on September 25, 2023 and found 26 issues that need to be fixed to make the interface accessible for visual impaired users.

Version
-------
6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------
Headings must be properly nested. Headings must be properly nested within a landmark. 

Actual behavior
---------------
Headings are not properly listed within a landmark.

Steps to reproduce
------------------
Sympa Accessibility Issue - 6 - was determined by an Automation Tool Evaluation using AInspector and Siteimprove Accessibility Checkers as automated accessibility evaluation tools.

After running these automation tools the following issue was identified:

Headings must be properly nested. Headings must be properly nested within a landmark. Adjust the level of the H4 heading or other heading elements such that the headings are properly nested in the MAIN landmark

[WCAG Level A 1.3.1 Info and Relationships (Primary)](https://www.w3.org/TR/WCAG21/#info-and-relationships)

![image](https://github.com/sympa-community/sympa/assets/144282683/dce0c64f-400d-4923-b159-c3e2ee229ef5)

Fig 6 Inconsistent heading structure.

Additional information
----------------------
Attached is the Accessibility Review conducted on Sept 25,2023
[Tech Services Review - Accessibility Evaluation Report for Sympa.pdf](https://github.com/sympa-community/sympa/files/13549513/Tech.Services.Review.-.Accessibility.Evaluation.Report.for.Sympa.pdf)

**Comment by ikedas** [comment]
Hi @rm1-uiuc ,

I could not find the problem of improper nesting of headings (You seems telling about `<h`*n*`>` tag. Am I right?).  Could you please point out where the problem occurs in actual HTML source?

**Comment by ikedas** [comment]
Is there any further information? If there are no developments, this issue will be closed for the present.
