### ISSUE TITLE
Sympa Accessibility Issue - 7 - LABEL element does not allow the implicit role of the element to be changed

### ISSUE THREAD

**Issue by rm1-uiuc** [sympa-community/sympa#1765]
The University of Illinois at Urbana-Champaign, Technology Services Accessibility Testing team conducted an Accessibility Review of Sympa on September 25, 2023 and found 26 issues that need to be fixed to make the interface accessible for visual impaired users.

Version
-------
6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------
Role is not allowed. Some HTML elements are restricted in the role allowed based on the semantics of the element (e.g. LI elements can only have list related ARIA roles). 

Actual behavior
---------------
The LABEL element does not allow the implicit role of the element to be changed.  This role conflict causes the screen reader to receive confusing and/or conflicting information.  Removing the HEADING role from the element will provide more cleaner read by the screen reader.

Steps to reproduce
------------------
Sympa Accessibility Issue - 7 - was determined by an Automation Tool Evaluation using AInspector and Siteimprove Accessibility Checkers as automated accessibility evaluation tools.

After running these automation tools the following issue was identified:

Role is not allowed. Some HTML elements are restricted in the role allowed based on the semantics of the element (e.g. LI elements can only have list related ARIA roles). When a role conflicts with the implicit semantics of an HTML element the accessibility API provides confusing and/or conflicting information to screen readers.

In this case, the LABEL element does not allow the implicit role of the element to be changed. Remove the HEADING role from the element.

[WCAG Level A 4.1.2 Name, Role, Value (Primary)](https://www.w3.org/TR/WCAG21/#name-role-value)

![image](https://github.com/sympa-community/sympa/assets/144282683/77fd4d7d-0c80-47b9-b462-4c0965f95bbc)

Fig 7 Inconsistent heading structure.

Additional information
Attached is the Accessibility Review conducted on Sept 25,2023
[Tech Services Review - Accessibility Evaluation Report for Sympa.pdf](https://github.com/sympa-community/sympa/files/13549596/Tech.Services.Review.-.Accessibility.Evaluation.Report.for.Sympa.pdf)

**Comment by ikedas** [comment]
Hi @rm1-uiuc ,

>  Remove the HEADING role from the element.

What do you mean by this suggestion? Alter all, How do you think we have to change actual code?

**Comment by ikedas** [comment]
Is there any further information? If there are no developments, this issue will be closed for the present.
