### ISSUE TITLE
Sympa Accessibility Issue - 11 - Form controls must have labels

### ISSUE THREAD

**Issue by rm1-uiuc** [sympa-community/sympa#1769]
The University of Illinois at Urbana-Champaign, Technology Services Accessibility Testing team conducted an Accessibility Review of Sympa on September 25, 2023 and found 26 issues that need to be fixed to make the interface accessible for visual impaired users.

Version
-------
6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------
All Form controls must have an accessible labels on it (INPUT, SELECT, TEXTAREA, PROGRESS, METER and OUTPUT)  A label associated with a form control ensures that information about the form control is spoken by screen readers.

Actual behavior
---------------
No Accessible labels are on any of the form elements (INPUT, SELECT, TEXTAREA, PROGRESS, METER and OUTPUT ). 

Steps to reproduce
------------------
Sympa Accessibility Issue - 11 - was determined by an Automation Tool Evaluation using AInspector and Siteimprove Accessibility Checkers as automated accessibility evaluation tools.

After running these automation tools the following issue was identified:

Form controls must have labels. Each INPUT, SELECT, TEXTAREA, PROGRESS, METER and OUTPUT element must have an accessible label. A label associated with a form control ensures that information about the form control is spoken by screen readers when it receives focus. Tag Names: ul[role=tree], ul[role=treeitem].

[WCAG Level A 3.3.2 Labels or Instructions (Primary)](https://www.w3.org/TR/WCAG21/#labels-or-instructions)

![image](https://github.com/sympa-community/sympa/assets/144282683/6d40af99-d5ec-4500-a4ff-491514206616)
![image](https://github.com/sympa-community/sympa/assets/144282683/5fe36ae7-73a8-434a-9b1a-4d5284bb6c8e)

Fig 12 Forms control must have labels.

Additional information
----------------------
Attached is the Accessibility Review conducted on Sept 25,2023
[Tech Services Review - Accessibility Evaluation Report for Sympa.pdf](https://github.com/sympa-community/sympa/files/13552245/Tech.Services.Review.-.Accessibility.Evaluation.Report.for.Sympa.pdf)

**Comment by ikedas** [comment]
Hi @rm1-uiuc,

I couldn’t find form control (either of `input`, `select`, `textarea` and so on) in the rectangle you draw on the screenshot.  Could you please explain your suggestions?

**Comment by ikedas** [comment]
If there are no developments, this issue will be closed for the present.
