### ISSUE TITLE
Unable to import a large file of e-mails to a maillist using wwsympa

### ISSUE THREAD

**Issue by nzoueidi** [sympa-community/sympa#177]
Hello, I am trying to import a file contains a list of 150k emails using the web interface of Sympa. I had an error while doing that (Erreur interne - Impossible de construire les membres de la liste). I chekced the log there is many error entries all almost related to the task manager of sympa. I tried to pgrep the task manager process but it seems that there is one process.

Sympa version : 6.1.17
OS: Ubuntu 16.04

Naeîl ZOUEIDI
LINAGORA

**Comment by ikedas** [comment]
Hi Naeîl,

How did you import a file? Please tell us the detaild operation you took.

**Comment by nzoueidi** [comment]
Hello Ikedas,

I imported the file using the web interface. 
More precisely, by defining the path of the mail list to import using the web interface. 

However, I tried to import the mail list using the script sympa.pl. It works like charm.

PS: when the size of the file to import is lower than ~50k mails or lower it works also..

**Comment by ikedas** [comment]
Naeîl, how did you "imported the file by defining the path of the mail list to import using the web interface"? Please tell us the operation by each step (setting xxx to xxx, clicking xxx, ...).

**Comment by ikedas** [comment]
Stagnating issue. Closed for the present.
