### ISSUE TITLE
Issues with sending mails using special French characters

### ISSUE THREAD

**Issue by nzoueidi** [sympa-community/sympa#178]
Hello, I have encountered problems related to sending mails using wwsympa. 
I am using the FR UTF8 encoding. The problems are below:

  - When sending a mail that does not contain an FR special characters (e.g: é,è), the body of the mail will be gone.
  - When the body of the message contains only one image, the end and footer texts are not displayed. Besides, there is a difference of style fonts between the beginning of the text and the end footer

I checked the log, there are no suspicious entries due to those issues.

Sympa version : 6.1.17
OS: Ubuntu 16.04

Naeîl ZOUEIDI
LINAGORA

**Comment by racke** [comment]
On 02/01/2018 03:40 PM, Naeil ZOUEIDI wrote:
> Hello, I have encountered problems related to sending mails using wwsympa.
> I am using the FR UTF8 encoding. The problems are below:
> 
> |- When sending a mail that does not contain an FR special characters (e.g: é,è), the body of the mail will be gone. -
> When the body of the message contains only one image, the end and footer texts are not displayed. Besides, there is a
> difference of style fonts between the beginning of the text and the end footer |
> 
> I checked the log, there are no suspicious entries due to those issues.
> 
> Sympa version : 6.1.17
> OS: Ubuntu 16.04
> 
> Naeîl ZOUEIDI
> LINAGORA

Hello Naeîl,

please give us more details on your problem:

* where did you configure the "FR UTF8" encoding? is that a system setting?
* how did you send the email - from your email client or from the web interface?

Regards
          Racke

-- 
Ecommerce and Linux consulting + Perl and web application programming.
Debian and Sympa administration. Provisioning with Ansible.

**Comment by nzoueidi** [comment]
Hello Racke,

The FR UTF8 enconding is on the system setting. Also in the locale environment and I have a LANG variable refers to fr_FR.UTF-8. 

Thanks,
Naeîl

**Comment by ikedas** [comment]
Hi @nzoueidi,

Can you show us the messages of problem? We want to see raw messages (all of content and full header).

**Comment by ikedas** [comment]
Stagnating issue. Close for the present.
