### ISSUE TITLE
Unable to increase the incoming_max_count

### ISSUE THREAD

**Issue by Ne-34** [sympa-community/sympa#1780]
Unable to increase the incoming_max_count

Version
-------

Sympa Version 6.2.72

Installation method
-------------------

Source package

Expected behavior
-----------------

You should be able to increase the incoming_max_count via the sympa.conf to produce more sympa_msg.pl workers. 

Actual behavior
---------------

When you make the change to increase the incoming_max_count via the sympa.conf and restart sympa. All other services such as (wwsympa,task,bounce,archive,outgoing) will start-up as normal, except for the sympa service itself. In order for the sympa service to start you must first to remove the change from the sympa.conf, and the sympa service can be started as normal.  

Steps to reproduce
------------------

1. Stop the sympa services
2. Access the sympa.conf
3. Make a change inside the sympa.conf to incerase incoming_max_count
4. Attempt to start the sympa services.

All other service will start except the sympa itself. 

Additional information
----------------------

Thank you for any information that you can provide to help with the increasing of the incoming_max_count.

**Comment by ikedas** [comment]
What are the name and the version of Operating System where you installed Sympa?

How do you launch the services for Sympa? (manually, using init scripts, systemd units, launchd, ... or something else?)

Could you please actual content of `sympa.conf` before and after changes?

If possible, could you please show the log of Sympa _from when_ you started the services _to when_ you found that `sympa` has not started?

**Comment by Ne-34** [comment]
Thank you for your time. I am hoping this data will help in resolving this I really like to increase the incoming_max_count.

1.	What are the name and the version of Operating System where you installed Sympa?
NAME="Red Hat Enterprise Linux Server", VERSION="7.9 (Maipo)"
2.	 How do you launch the services for Sympa? (manually, using init scripts, systemd units, launchd, ... or something else?)
When applying a change I restart the services manually. In this order:
Systemctl restart sympa-outgoing
Systemctl restart sympa-archive
Systemctl restart sympa-bounce
Systemctl restart sympa-task
Systemctl restart sympa
Systemctl restart wwsympa
3.	Could you please actual content of sympa.conf before and after changes?
I have attached doc sympa.conf_before_change an sympa_conf_after_change the email.

[Sympa.conf_After_Change.docx](https://github.com/sympa-community/sympa/files/13693681/Sympa.conf_After_Change.docx)
[Sympa.conf_Before_Change.docx](https://github.com/sympa-community/sympa/files/13693682/Sympa.conf_Before_Change.docx)

4.	If possible, could you please show the log of Sympa from when you started the services to when you found that sympa has not started?
I have attached two files with that data.

[Sympa log.docx](https://github.com/sympa-community/sympa/files/13693713/Sympa.log.docx)
[Systemctl status detail.docx](https://github.com/sympa-community/sympa/files/13693714/Systemctl.status.detail.docx)

**Comment by ikedas** [comment]
For example, with my Sympa on CentOS 7, these processes are invoked:
```
$ ps aux|sed -ne '1p;/sympa/p'
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
sympa     1044  0.0  0.0  17332   192 ?        Ss    8月17   0:08 /usr/bin/multiwatch -f 5 -- /usr/libexec/sympa/wwsympa.fcgi
sympa     2510  1.2  1.7 410396 69992 ?        S    08:30   0:00 /usr/bin/perl /usr/sbin/sympa_msg.pl
sympa     2520  0.0  1.3 395200 54428 ?        S    08:30   0:00 /usr/bin/perl /usr/sbin/archived.pl
sympa     2521  0.0  1.3 289896 52676 ?        S    08:30   0:00 /usr/bin/perl /usr/sbin/bounced.pl
sympa     2522  0.0  1.2 202104 50700 ?        S    08:30   0:00 /usr/bin/perl /usr/sbin/bulk.pl
sympa     2523 88.0  2.6 444912 105988 ?       S    08:30   0:24 /usr/bin/perl /usr/sbin/task_manager.pl
adminus+  2551  0.0  0.0 117036   948 pts/0    R+   08:31   0:00 sed -ne 1p;/sympa/p
sympa    22181  0.0  2.7 492032 109816 ?       S    12月16   0:27 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
sympa    22187  0.0  1.9 443652 80704 ?        S    12月16   0:01 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
sympa    22195  0.0  1.8 443040 76112 ?        S    12月16   0:01 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
sympa    22199  0.0  1.8 443100 75384 ?        S    12月16   0:01 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
sympa    22209  0.0  2.0 445872 81848 ?        S    12月16   0:01 /usr/bin/perl /usr/libexec/sympa/wwsympa.fcgi
sympa    31254  0.0  0.0  17332    12 ?        Ss    6月27   0:08 /usr/bin/multiwatch -f 2 -- /usr/libexec/sympa/sympa_soap_server.fcgi
sympa    31255  0.0  0.0 454060     0 ?        S     6月27   0:24 /usr/bin/perl /usr/libexec/sympa/sympa_soap_server.fcgi
sympa    31256  0.0  0.0 453984     0 ?        S     6月27   0:24 /usr/bin/perl /usr/libexec/sympa/sympa_soap_server.fcgi
```
In this case with default setting, `incoming_max_count 1`, one `sympa_msg.pl` process is invoked and 410396 kiB of virtual memory is consumed.

You changed `incoming_max_count` from `4` to `8`.  This increases the number of `sympa_msg.pl` processes by 4 and, by analogy with my results above, increases the required virtual memory by about 1.6 GiB.  I believe that the system had run out of swap, the OOM killer killed the process that had just started, and systemd stopped the service.

The `incoming_max_count` needs not to be too large, or more memory needs to be added.

**Comment by Ne-34** [comment]
Thank for your response. 

The current system in which the sympa is running on has 32 GB of memory. 

The same issue (not starting) is experience when I set the incoming_max_count  to "2".  There was a error message that I seen via "systemctl status sympa" Failed to parse PID from file /run/sympa/sympa_msg.pid: Invalid argument". This is what I see every time I attempt to increase the incoming_max_count pass the default. 

When the incoming_max_count is set to 1 everything starts up as normal.

**Comment by ikedas** [comment]
Please try:

1. Stop all services of Sympa, and confirm that the all services are stopping.
2. ``rm /run/sympa/sympa_msg.pid``
3. Start all services of Sympa.

**Comment by Ne-34** [comment]
I found that if the automatic_list_feature is turned off it prevents you from increasing the incoming_max_count. Once the automatic_list_feature is turned on the sympa.service was able to start-up with the increase incoming_max_count edit made to the sympa.conf.

**Comment by ikedas** [comment]
> Question: You should be able to increase the incoming_max_count without enabling the automatic_list_feature?

Yes, `I could increase the `incoming_max_count` without setting the `automatic_list_feature` which is `off` by default.

Btw you couldn't increase `incoming_max_count` from 4 to 8, could you?  Conversely, you could increase it from 1 (default) to 4.  That is, your server's capacity is to start no less than 4 and no more than 8 `sympa_msg.pl` services.

**Comment by ikedas** [comment]
No update.  Close for now.
