### ISSUE TITLE
Adding Oneclick URL to the footer of the message

### ISSUE THREAD

**Issue by Ne-34** [sympa-community/sympa#1784]
Version
-------

Sympa Version 6.2.72

Installation method
-------------------

Source package

Expected behavior
-----------------

How to include the Oneclick Url in the message footer? I tried applying the header name in the format suggested by (https://www.sympa.community/manual/customize/message-personalization.html) in the message_footer file but was unsuccessful. I would like to allow users to click that link to unsubscribe from the footer.

Actual behavior
---------------

The appropriate headers are applied confirmed by the imaged provided below. 

Additional information
----------------------

<img width="350" alt="Sympa1" src="https://github.com/sympa-community/sympa/assets/105612222/cc1162df-c148-4e92-b234-2cb6c40145eb">

**Comment by ikedas** [comment]
The feature of [RFC 8058 One-Click Unsubscribe](https://datatracker.ietf.org/doc/html/rfc8058) has been introduced on Sympa 6.2.72.

The header fields for one-click are added to messages delivered through the list when the following conditions are met:
  * `wwsympa_url` parameter is set.
  * `rfc2369_header_fields` parameter contains `unsubscribe`.
  * message personalization is enabled.
  * DKIM signing is available (required by the RFC).

One-click link URL will be expired in 7 days to prevent abuse.

See PR #1538 for details.

**Comment by Ne-34** [comment]
Thanks, ikedas. The problem is not the one-click headers (list-unsubscribe, list-unsubscribe-post) those headers have been applied to the message successfully.

All the feature that's listed in your response are enabled. 

I have followed the RFC 8058 One-Click Unsubscribe before placing the question. 

The link that's provided in the "list-unsubscribe" (picture provided in the chat).  It there away to have that link placed in the message footer to allow user the ability to click it to unsubscribe. 

Similar to the "auto_signoff", but for "oneclick"

**Comment by ikedas** [comment]
> Similar to the "auto_signoff", but for "oneclick"

Sympa does not have such feature.

**Comment by Ne-34** [comment]
I think that would be a great enhancement. At this point we have the Oneclick link in the header. but it would be great to have that same link in the message footer to allow the user to click the link and actually use the one-click unsubscribe feature.

**Comment by ikedas** [comment]
I don't think we woild implement such a one-click feature.  Because it is very likely that the link prefetching feature of MUA makes unintentional unsubscription.

RFC 8058 does not provide normal "link": If a user followed that link in normal way, one-click unsubscription, will not occur.  It is also the case on prefetching feature of MUA.

**Comment by Ne-34** [comment]
Thanks, ikedas for all your time it really means a lot.

I have tested that link that was provided in the "list-unsubscribe header", and it took me to the page to unsubscribe from the list, I still had to confirm, after confirming it removed me right then and there. The prefetching feature of a MUA would not be able to confirm for the user to remove them from the list. 

I have also copied that link into an email and sent it through Office365, Onperm and my email gateway which is configured to conduct prefetching, and there was no accidental removal. 

The title of One-Click is very misleading. I have tested several mass messengers One-click feature in they follow the same path as the "oneclick" feature of sympa. One-click doesn't truly mean one-click, it means reducing the number of steps that user would need have to go through to unsubscribe.

Sympa One-click **Tested**
1. Use the link 
2. Confirmed that I want to be removed
3. Got an email stating that I have been removed. 

The older way of unsubscribing: **Tested**
1. Click the unsubscribe Link 
2. Confirm that you want to be removed.
3. You would get an email from Sympa asking if you really would like to be removed. 
4. One you click the confirmation link in that email, you will then be redirected to the unsubscribe page.
5. Confirm that you want to be removed again.
6. You will receive an email stating that you have been removed from the list.

I just think that providing the ability to place that link in the message footer ("like other unsubscribe methods") allows the feature to be used, instead of just using it for header data.

**Comment by ikedas** [comment]
Please read RFC 8058.  It does not provide the "link" to access (i.e. by GET method) one-click unsubscribe functionality but the URL to request (by POST method) that functionality.

In other words, this one-click feature needs support by MUA.  If an MUA does not support it, the URL may be treated as normal "link".

**Comment by ikedas** [comment]
Close for now.
