### ISSUE TITLE
No approve link provided in moderation email

### ISSUE THREAD

**Issue by gonzalo** [sympa-community/sympa#1788]
After upgrade, no approve link provided in moderation email

Version
-------
6.2.70 upgraded from a very old version

Installation method
-------------------
Debian 12 apt

Expected behavior
-----------------
Moderation email should provide an approve link like this

http://ourserver.com/sympa/ticket/0983475209384759208743

We recently updated to sympa 6.7.2 our very old installation and found that moderation email received by moderators no longer provide an "approve link" as use to be:

Actual behaviour
---------------
We receive a link to the generic moderation page of the list that forces the administrator to login. Links looks like this:

http://ourserver.com/sympa/modindex/list_name

Additional information
----------------------
I've taken a look at the moderation.tt2 template and https://www.sympa.community/manual/customize/message-personalization.html page but didn't see any useful information.

Is this feature deprecated? I'm missing something in my configuration?

This feature is extremely useful for us as allows some moderators to approve messages without login from internet (login is only allowed in the intranet)

**Comment by ikedas** [comment]
Please see also #156.  One-time ticket in moderation notification has been deprecated.

**Comment by ikedas** [comment]
If there is any discussion, please continue with the issue above. This issue is closed.
