### ISSUE TITLE
sympa review --status : the command does not give a good result

### ISSUE THREAD

**Issue by PatkmM** [sympa-community/sympa#1789]
Version
-------
6.2.70 on debian

Installation method
-------------------

Expected behavior
-----------------
The command "sympa review --status list@robot" must display the status of a list with the list of members and the list of suspended members

Actual behavior
---------------
On our installation, the command indicates that all members subscribed to the list are suspended, which is not the case as none of them are, and the list is working correctly.
 Is there a bug in the command or have I used it incorrectly?
Thanks in advance.
Patrick.

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @PatkmM ,
Could you please show the output of the command?  Actual email addresses may be masked.

**Comment by PatkmM** [comment]
Thank you for taking my request.
This is the result.
It's the same for all the robot's lists.

# sympa review --status <list>@<robot>
21 member(s) in list <list>@<robot>
member@robot
member2@robot
member3@robot
member4@robot
.../...

------------------
2 bounced member(s) in list <list>@<robot>.
<member>@<robot>
<member>@<robot>
21 suspended member(s) in list <list>@<robot>.
member@robot
member2@robot
member3@robot
member4@robot
.../...
# 
Patrick.

**Comment by ikedas** [comment]
Hi @PatkmM ,

Your results appear to show that 21 members are suspended.  Please check the actual status by selecting User from the Admin menu of web interface.

**Comment by PatkmM** [comment]
Hi,
On the Admin menu none of them are suspended. All are "normal (direct message reception)" and the list works perfectly.
I'm wondering about the output of the "sympa -request" command.
Thank you !
Patrick.

**Comment by ikedas** [comment]
Reception mode (normal and so on) is not the suspension status.  Please click each email in member list and check if each of them is suspended or not.

**Comment by PatkmM** [comment]
Sorry, I must have misunderstood, but that's exactly what I did and verified by clicking on each of the subscribers.
Patrick.
