### ISSUE TITLE
Is it possible to set custom vars on xml creation list templates?

### ISSUE THREAD

**Issue by gonzalo** [sympa-community/sympa#1793]
Version
-------
Sympa 6.2.70

Installation method
-------------------
deb package

Expected behavior
-----------------
I'm trying to add custom_vars into xml template files to standarize automatic creation of certain lists, but I don't know if is even possible. 

What I'm trying to achieve is something like this. 

```
<?xml version="1.0" ?> 
  <list> 
  	<listname>forpruebav2</listname> 
	<type>my_type</type>
    	<subject>XML generated list xxxxx</subject> 
    	<status>open</status> 
    	<topics>my_topic</topics> 
  	<language>es</language> 
  	<owner multiple="1"> 
  	   <email>my@mail.com</email> 
  	</owner> 
        <custom_subject>TEST LIST</custom_subject>
        <custom_vars>
           <var name=“my_custom_var_name" value="/xxx/xxx/xxxx/my_file.txt"/>
        </custom_vars>
  </list>
```
The template work (list is created), but obviously custom_vars section is just "ignored"

**Comment by ikedas** [comment]
XML element should be:
```xml
        <custom_vars multiple="1">
           <name>my_custom_var_name</name>
           <value>/xxx/xxx/xxxx/my_file.txt</value>
        </custom_vars>
```
And you may add the parameter to `config.tt2` of list creation template:
```
(Existing content of config.tt2...)

[% FOREACH v = custom_vars %]
custom_vars
  [% v.name %] [%v.value %]

[% END %]
```

**Comment by gonzalo** [comment]
Thank you I will test and let you know

regards

--
Gonzalo

**Comment by ikedas** [comment]
Possibly solved. Close.
