### ISSUE TITLE
File names in shared document storage are garbled.

### ISSUE THREAD

**Issue by lifestyle-design** [sympa-community/sympa#1802]
When I upload a Japanese file name to the shared document storage, the file name becomes garbled.

Version
-------
Sympa 6.2.72

Installation method
-------------------
CentOS7 yum

Expected behavior
-----------------
When I upload a Japanese file name to the shared document storage, the file name becomes garbled.

Actual behavior
---------------
When I upload a Japanese file name to the shared document storage, the file name becomes garbled.

Steps to reproduce
------------------
When I upload a Japanese file name to the shared document storage, the file name becomes garbled.

Additional information
----------------------
![Screenshot (19)](https://github.com/sympa-community/sympa/assets/28140559/e7c74944-4869-4639-b53e-a826ecb49c7f)

**Comment by lifestyle-design** [comment]
![Screenshot (17)](https://github.com/sympa-community/sympa/assets/28140559/a3859a5a-6fb0-4684-a2f2-30b0873a117f)

**Comment by ikedas** [comment]
Hi @lifestyle-design ,

バグ報告ありがとうございます。
スクリーンショットに写り込んでいるオーナーの名前とかが生々しいんですけど大丈夫ですかね。

Thank you for reporting bug!  I confirmed the behavior you reported.  I'm planning to submit a PR to resolve it in several days.

**Comment by lifestyle-design** [comment]
ご返信ありがとうございます。
スクショの指摘ありがとうございます。
該当部分伏せました。
よろしくお願いします。

**Comment by lifestyle-design** [comment]
@ikedas 
対応ありがとうございます。
こちらもう修正完了した感じでしょうか？
src/lib/Sympa/Tools/Text.pm
を上書きすれば良いですかね？

**Comment by ikedas** [comment]
Hi @lifestyle-design ,

Could you please apply the change on PR #1803 and check if the problem will be solved? Note that you should restart wwsympa service.

すみません。PRを提出したあと寝落ちしてしまってそのままになっていました。おっしゃるようにファイルを上書きすればいけると思います。なお変更適用後にwwsympaのサービスは再起動する必要があります。

**Comment by lifestyle-design** [comment]
@ikedas 
直りました！
ご対応ありがとうございましたm(_ _)m
