### ISSUE TITLE
SOAP Login

### ISSUE THREAD

**Issue by johnnychuang** [sympa-community/sympa#1804]
SOAP authorization failed.

Version 
-------
[6.2.70]

Installation method
-------------------
debian 12, deb

Expected behavior
-----------------
I want to access lists over SOAP.  it should show the complete list, 

Actual behavior
---------------
it shows [soap:Server] Authentication failed

Additional information
----------------------
After upgrading server from Debian 11 to Debian 12 , rerun our test program and it failed. In server log, In the Logs I can see this:
```
10:54:24.752080+01:00 dev-lisa-mail sympasoap[875]: err main::#85 > Sympa::WWW::SOAP::Transport::handle#118 > SOAP::Transport::HTTP::CGI::handle#616 > Sympa::WWW::SOAP::Transport::request#75 > Sympa::WWW::Session::new#74 Missing robot parameter, cannot create session object
10:54:24.757629+01:00 dev-lisa-mail sympasoap[875]: notice Sympa::WWW::SOAP::login(XXXXXX@XXXX.XXX)
10:54:24.759316+01:00 dev-lisa-mail sympasoap[875]: err main::#85 > Sympa::WWW::SOAP::Transport::handle#118 > SOAP::Transport::HTTP::CGI::handle#627 > SOAP::Transport::HTTP::Server::handle#459 > SOAP::Server::handle#2844 > (eval)#2878 > (eval)#2893 > Sympa::WWW::SOAP::login#183 > Sympa::WWW::Auth::check_auth#62 > Sympa::WWW::Auth::authentication#214 Incorrect password for user XXXXXX@XXXX.XXX
10:54:24.759472+01:00 dev-lisa-mail sympasoap[875]: notice Sympa::WWW::SOAP::login() Login authentication failed
```
But when I log in to the website, this account can work.

**Comment by ikedas** [comment]
Hi @johnnychuang ,
Could you please show us the steps to reproduce the problem you encountered?

**Comment by johnnychuang** [comment]
@ikedas 
I fixed this problem, After updating to the latest version, it drops my soap_url in the config file. So I rewrote it back to configure, and restart the sympasoap service. then it works again. sorry for this
