### ISSUE TITLE
personalization_feature on and unexpected behavior when sending

### ISSUE THREAD

**Issue by morenonardelliunitn** [sympa-community/sympa#1807]
We have implemented the "personalization feature" option on some of our lists that have a large number of recipients (more than 30,000 users).
Unlike other lists that have the same number of recipients but do not have this configuration, we note that the "personalization_feature" option causes emails to be processed differently from sendmail. Although the "maxsmtp" options with value 40 and nrcpt with value 25 have been configured in the /etc/sympa/sympa.conf file, the emails processed by these lists are sent individually.
Therefore one email for each sendmail call, while the lists that do not have the "" option configured follow the correct configurations by sending packets of 25 email addresses per sendmail call.
Is this an expected behavior of sympa or are there additional configurations that we have not implemented?

Processing a single email per sendmail call affects the performance of the server machine which has to manage a very high CPU load (the server is a virtual machine with 4 CPUs and 16 GB of RAM)

Version
-------
6.2.72

Installation method
-------------------
Sympa is installed with rpm package on RHEL 8.7

**Comment by gavyounger** [comment]
Surely this is expected behaviour. 

With message personalisation switched on for a list, each and every message will be different in some way, thereby requiring a distinct call to the MTA?

**Comment by morenonardelliunitn** [comment]
Thanks @gavyounger for the answer.
Regarding this, I would like to ask you something else. Is there a configuration other than enabling the "personalization feature" option to have Sympa add the "List-Unsubscribe-Post: List-Unsubscribe=One-Click" field to the header of outgoing emails?

Thanks in advanced

**Comment by morenonardelliunitn** [comment]
Hi @ikedas 
 
> If one-click unsubscribing feature have to be enabled, each and every message must have the List-Unsubscribe field with different value by each rec ipient. That's why one-click feature may be enabled if and only if the personalization feature is enabled.

Thanks for the reply and the explanation of the behavior of the system.

**Comment by ikedas** [comment]
There seem no more questions.  Close.
