### ISSUE TITLE
HTML signature with Unicode characters generates 'rejected_authorization' error

### ISSUE THREAD

**Issue by ntmlod** [sympa-community/sympa#181]
Hello Sympa devs,

I have coded a HTML signature for my moderator email address with some Unicode characters, it looks like this:

```
<p>
	<b>Name</b><br>
	<em>Role</em><br>
	&#128231; <a href='mailto:xxxxxxxx@www.xxxxxxxx.xxxx'>Email</a>
</p>
<table>
	<td>
		<img alt='Company logo from external link' style='height: 70px; width: auto;' src='http://www.xxxxxxxx.xxxx/xxxxx.png'>
	</td>
	<td style='padding: 0 10px 0 10px;'>
		<hr size='65'>
	</td>
	<td>
		<font size='2'>
			<b>Company</b> - <a href='http://www.xxxxxxxx.xxxx'>URL</a>
			<p>
				<font size='4'>&#128240;</font> <em><a href='http://www.xxxxxxxx.xxxx/xxxx/'>Link 1</a></em> &nbsp;~&nbsp;
				<font size='4'>&#127757;</font> <em><a href='http://www.xxxxxxxx.xxxx/xxxxxx/'>Link 2</a></em> &nbsp;~&nbsp;
				<font size='4'>&#128218;</font> <em><a href='http://www.xxxxxxxx.xxxx/xxxxxxxxxxxx/'>Link 3</a></em>
			</p>
			<font size='4'>&#128235;</font> Newsletter: <a href='http://listes.xxxx.xxx/sympa/info/xxxx-xxxxxxxx'>manage your subscription</a> / <a href="mailto:sympa@xxxxx.xx?subject=SIGNOFF xxxx-xxxxxxxx">unsubscribe</a>
		</font>
	</td>
</table>
```

I have checked it with different browsers and email clients, it seemed to be OK.
On my following attempt to send a message to the mailing list, I was rejected by Sympa. In the logs view (just the owner of the list, not a listmaster), I had a 'rejected_authorization' error.

Then, I enabled `Allow message personalization` for testing but with the same result. Finally, I got back to my previous plain signature and the message was distributed.

It is my first experience as Sympa list owner, did I miss something in the mailing list configuration ?

**Comment by ntmlod** [comment]
@ikedas I was probably not clear with my initial statement. Just want to say that I have the right permissions to post to the list. With my HTML signature, the message didn't pass contrary to the same message with a plain text signature.
> 02 Feb 2018 18:11:29 | xxxxx-xxxxxxxx | DoMessage | xxxxx-xxxxxxxx@xxxxxxx.xxx.1517591488.27280 |   | Other events | error | rejected_authorization | xxxxxxxx@xxxxxxxxx.xxx |   | sympa_msg

@racke Sympa 6.2.16

**Comment by ikedas** [comment]
@ntmlod, I understood you are using web interface to operate list.

Could you please tell us these information?
  1. What is the value of "send" parameter? To confirm this, see the setting of "Who can send messages" item in "Sending" page of "Edit List Config".
  2. Sender (e-mail in "From:" field of message) of message in question is whether ---
       - Listmaster,
       - Owner of the list in questioin,
       - Editor (moderqator) of the list in questioin,
       - Subscriber (member) of the list in questioin,
       - or, having any or all of roles above?
  3. Any messages which sender received from the Sympa system, if any.

**Comment by ntmlod** [comment]
>     What is the value of "send" parameter? To confirm this, see the setting of "Who can send messages" item in "Sending" page of "Edit List Config".
Newsletter, restricted to moderators (newsletter)
>     Sender (e-mail in "From:" field of message) of message in question is whether ---
>         Listmaster,
>         Owner of the list in questioin,
>         Editor (moderqator) of the list in questioin,
>         Subscriber (member) of the list in questioin,
>         or, having any or all of roles above?
Editor (moderator) of the list.
I'm also the owner of the list via another email but I use an email alias which is defined as moderator of the list
>     Any messages which sender received from the Sympa system, if any.
No, but I'm not sure if the configuration of the list is set to do so.

**Comment by ikedas** [comment]
> > What is the value of "send" parameter? To confirm this, see the setting of "Who can send messages" item in "Sending" page of "Edit List Config".
> 
> Newsletter, restricted to moderators (newsletter)

I see. This option will allow posts from moderators, while reject posts from others and will send back a message with content "Message distribution for this list is restricted to list moderators." to the sender.
Didn't you receive such message?

> > Sender (e-mail in "From:" field of message) of message in question is whether ---
> >   - Listmaster,
> >   - Owner of the list in questioin,
> >   - Editor (moderqator) of the list in questioin,
> >   - Subscriber (member) of the list in questioin,
> >   - or, having any or all of roles above?
> 
> Editor (moderator) of the list.
> I'm also the owner of the list via another email but I use an email alias which is defined as moderator of the list

Do you mean that "Moderators" section in "List definition" page of "Edit List Config" contains setting of that "email alias which is defined as moderator"?

> > Any messages which sender received from the Sympa system, if any.
> 
> No, but I'm not sure if the configuration of the list is set to do so.

As I wrote above, message sender will receive some message, if e-mail of the sender is not configured as a moderator.

**Comment by ntmlod** [comment]
>>>What is the value of "send" parameter? To confirm this, see the setting of "Who can send messages" item in "Sending" page of "Edit List Config".
>>>
>>Newsletter, restricted to moderators (newsletter)
>> 
> I see. This option will allow posts from moderators, while reject posts from others and will send back a message with content "Message distribution for this list is restricted to list moderators." to the sender.
> Didn't you receive such message?
>
No, absolutely no error message from the list.
>>>Sender (e-mail in "From:" field of message) of message in question is whether ---
>>> 
>>>Listmaster,
>>>Owner of the list in questioin,
>>>Editor (moderqator) of the list in questioin,
>>>Subscriber (member) of the list in questioin,
>>>or, having any or all of roles above?
>>> 
>>Editor (moderator) of the list.
>>I'm also the owner of the list via another email but I use an email alias which is defined as moderator of the list
>> 
> Do you mean that "Moderators" section in "List definition" page of "Edit List Config" contains setting of that "email alias which is defined as moderator"?
>
Yes, I connect to the web interface with my "listmaster" email to manage the list but I use an email alias when I want to post on the newsletter.

**Comment by ikedas** [comment]
> >>>Sender (e-mail in "From:" field of message) of message in question is whether ---
> >>> 
> >>>Listmaster,
> >>>Owner of the list in questioin,
> >>>Editor (moderqator) of the list in questioin,
> >>>Subscriber (member) of the list in questioin,
> >>>or, having any or all of roles above?
> >>> 
> >>Editor (moderator) of the list.
> >>I'm also the owner of the list via another email but I use an email alias which is defined as moderator of the list
> >> 
> > Do you mean that "Moderators" section in "List definition" page of "Edit List Config" contains setting of that "email alias which is defined as moderator"?
> >
> 
> Yes, I connect to the web interface with my "listmaster" email to manage the list but I use an email alias when I want to post on the newsletter.

And that "email alias" address is the same as the address shown in "User Email" column of [log above](#issuecomment-363081633), is it right?

**Comment by ntmlod** [comment]
>And that "email alias" address is the same as the address shown in "User Email" column of log above, is it right?
>
Exactly

**Comment by ikedas** [comment]
@ntmlod, please show us following information:
  - all parameters of Sympa you configured.
  - the content of message you sent (with full header).
  - Related system log (not only logs shown on web interface but also all log entries recorded in system log file).

**Comment by ntmlod** [comment]
Sorry for a delay, finally I figured out where the issue came from and Sympa has nothing to do with.

On my second try, I receive a non-distribution notification for policy reason from the relay at the entry of the network.
They suspect the spam filter detects my messages as a false positive.

So this ticket can be closed
