### ISSUE TITLE
"Request a list" missing from webpage

### ISSUE THREAD

**Issue by hl7webmaster** [sympa-community/sympa#1815]
The button to "request a list" is missing from the webpage. This is a brand new sympa installation.

Version
-------

6.2.66

Installation method
-------------------

sudo apt-get install -y sympa

Expected behavior
-----------------

Actual behavior
---------------
as shown in the attached screenshot, the Button is missing

Additional information
----------------------

<img width="955" alt="Sympa" src="https://github.com/sympa-community/sympa/assets/22037276/f88fb89e-930e-4f9a-83d1-a32e25e44fb8">

**Comment by ikedas** [comment]
What is the button to "request a list"? Could you please present a screenshot of it?

**Comment by hl7webmaster** [comment]
Sure, i got this off the Sympa website
<img width="799" alt="Sympa2" src="https://github.com/sympa-community/sympa/assets/22037276/6cf4a8ba-177c-4e87-82a8-08e8279838fc">

**Comment by ikedas** [comment]
Please check the [create_list](https://www.sympa.community/gpldoc/man/sympa_config.5.html#create_list) parameter.

**Comment by hl7webmaster** [comment]
Thank you.
