### ISSUE TITLE
RPM package for CentOS 8/9

### ISSUE THREAD

**Issue by Ne-34** [sympa-community/sympa#1820]
Version
-------
Sympa Version 6.2.72

Installation method
-------------------
Source Package

Expected behavior
-----------------

I want to update my Linux server's OS and I need to know if there is a source package for Sympa Version 6.2.72 that works with CentOS 8/9.

If there is, can you give me the link to that source package? I want to avoid a manual installation.

Actual behavior
---------------

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @Ne-34 ,

What is “source package”?  Why do you need t?

**Comment by Ne-34** [comment]
Is there a RPM packages for RHEL 9? If not, when will it be available?

**Comment by ikedas** [comment]
@Ne-34 , please read [the documentation](https://www.sympa.community/manual/).

**Comment by xavierba** [comment]
Sympa for all supported EL and clone releases is available from EPEL.
It is also available in regular Fedora repositories, built from the exact same RPM spec file.

**Comment by ikedas** [comment]
There seems no more questions.  Close.
