### ISSUE TITLE
Support Stalwart Mail Server 

### ISSUE THREAD

**Issue by yodatak** [sympa-community/sympa#1821]
Expected Behavior
-----------------

Its a good email rust server  Stalwart Mail Server 

Current Behavior
----------------
It lack in stalwart postmap or sendmail_aliases or postalias program

Possible Solution
-----------------
Try to make an upstream demand but it got refused because its a old format

https://github.com/stalwartlabs/mail-server/issues/115

**Comment by ikedas** [comment]
Stalwart looks supporting [LMTP delivery](https://stalw.art/docs/smtp/outbound/routing/#lmtp-delivery).  I wrote a program to allow sympa receive messages via LMTP port, [lmtpsympa](/ikedas/lmtpsympa) (this does not need aliases files).

**Comment by yodatak** [comment]
> Stalwart looks supporting [LMTP delivery](https://stalw.art/docs/smtp/outbound/routing/#lmtp-delivery). I wrote a program to allow sympa receive messages via LMTP port, [lmtpsympa](/ikedas/lmtpsympa) (this does not need aliases files).

Nice did you have some documentation how to use it? 🤓

**Comment by ikedas** [comment]
There seem no more questions. Close.
