### ISSUE TITLE
Amazon Linux 2023 Support for Sympa

### ISSUE THREAD

**Issue by UAProfessorProton** [sympa-community/sympa#1829]
Just need to check in if Amazon Linux 2023 will be supported in the future. Currently Sympa can be installed via EPEL in Amazon Linux 2. EPEL is not supported by Amazon Linux 2023

Reference:
[-] Extra Packages for Enterprise Linux (EPEL) - https://docs.aws.amazon.com/linux/al2023/ug/compare-with-al2.html#epel

Version
-------

Latest version of Sympa

Installation method
-------------------

N/A
Expected behavior
-----------------

N/A
Actual behavior
---------------

N/A
Additional information
----------------------

N/A

**Comment by ikedas** [comment]
Hi @UAProfessorProton ,

Amazon Linux 2023 is not supported by EPEL.  You can install Sympa from source distribution.  Please see the [documentation](https://www.sympa.community/manual/install/install-sympa-distribution.html).

**Comment by UAProfessorProton** [comment]
Thank you for the quick response. Will close this issue now.
