### ISSUE TITLE
Delete All Subscribers From List

### ISSUE THREAD

**Issue by bashbros** [sympa-community/sympa#1836]
It would be nice to be able to delete all subscribers at one time. We have some lists that are well over 8k subscribers and going page by page is tedious. There are so many changes in the list at any given time that going through it takes way more time than just blowing it away and importing a fresh list from our database. 

Expected Behavior
-----------------
Button to remove ALL subscribers from the list.

Current Behavior
----------------
Radio button to delete all subscribers on the current page. 

Possible Solution
-----------------
Expand the viewable subscribers to a larger number? 

Context
-------
We have several groups that refresh their lists once a month. As of right now, we have to manually close the list and do backend work to remove all subscribers at once. Then, reopen the list.

**Comment by ikedas** [comment]
There seems no more questions. Close.
