### ISSUE TITLE
How can I rebuild archives and get attachments with exact extensions?

### ISSUE THREAD

**Issue by msjang** [sympa-community/sympa#1838]
Version
-------
Sympa 6.2.66

Installation method
-------------------
Ubuntu 22.04 LTS
apt install -y sympa

Expected behavior
-----------------
I uploaded eml files on /var/lib/sympa/arc/mylist@mydomain/YYYY-MM/arctxt/
and I performed Rebuild archives for an individual list.
The archive would gives attachments with exact same extensions.

Actual behavior
---------------
The archive gives attachments with  'bin' extension only.
<img width="743" alt="sympa-reindex-extensions" src="https://github.com/sympa-community/sympa/assets/2688660/7d1aefe4-cd7f-43a4-858a-63147c4db37e">

**Comment by ikedas** [comment]
Hi @msjang ,
I found that, unfortunately, MHonArc has a bug.

Could you please try applying [this fix](/sympa-community/MHonArc/pull/22) and customizing [mhonarc_rc.tt2](https://www.sympa.community/manual/customize/basics-templates.html) as below?
```
<MIMEARGS>
...
(existing settings)
...
application/hwp+zip; subdir ext=hwpx type="Hanword Document"
application/x-hwp; subdir ext=hwp type="Hanword Document"
</MIMEARGS>
```
