### ISSUE TITLE
log_socket_type parameter should allow host, port, timeout options

### ISSUE THREAD

**Issue by simonelbaz** [sympa-community/sympa#1839]
Hello,

I need to pass \%option as mentionned in https://perldoc.perl.org/Sys::Syslog#setlogsock().

It would allow sending logs to remote host, port and timeout.

Expected Behavior
-----------------
"inet" value should allow host, port, timeout options.

Current Behavior
----------------
log_socket_type is checked against the following regex: [if ($self->{_socket_type} =~ /^(unix|inet)$/i) {](https://github.com/sympa-community/sympa/blob/09bd230e22076b3c1d5e1c737916ac8e6bae002f/src/lib/Sympa/Log.pm#L226).

It is not useful for "inet" socket used towards remote servers.

Possible Solution
-----------------
log_socket_type parameter should allow hash input.

Regards

**Comment by ikedas** [comment]
> It is not useful for "inet" socket used towards remote servers.

The `unix` did not work on some environments including Solaris and `inet` (i.e. TCP or UDP bound for local host) had to be specified.

BTW  making the full option available looks very meaningful.  Thank you for suggestion!
