### ISSUE TITLE
Setting invite sender as From: violates modern sender authentication

### ISSUE THREAD

**Issue by adam12b1** [sympa-community/sympa#1846]
Version
-------
Sympa 6.2.72

Installation method
-------------------
FreeBSD port

Expected behavior
-----------------
Invite emails should successfully reach their destination.

Actual behavior
---------------
These invites will be filtered or blocked in many cases, because they are sending **From:** the person doing the invitation. Assuming that person's email is not hosted on the same system as the Sympa lists, sender authentication will fail.

Additional information
----------------------
The fix (or one possible fix) is extremely simple: just remove the **From:** line from the <code>mail_tt2/invite.tt2</code> file. That way, the invite will go out with the default Sympa administrative sender address, <code>sympa@lists.domain.org</code> (or whatever domain the Sympa server lives in), which will pass sender authentication checks.
```
# diff -c invite.tt2~ invite.tt2
*** invite.tt2~ Sun Mar 31 20:18:16 2024
--- invite.tt2  Tue May 28 16:04:12 2024
***************
*** 1,5 ****
  [%# invite.tt2 ~%]
- From: [% requested_by %]
  Reply-To: [% conf.email %]@[% domain %]
  Subject: [%"Invitation to join list %1"|loc(list.name)|qencode%]

--- 1,4 ----
```

**Comment by ikedas** [comment]
Hi @adam12b1 , thank you for your contribution!
I'll review your changes and, if possible, will add something.  Please wait for a few weeks.
