### ISSUE TITLE
Feature request: A new action for send on moderated lists is needed to enforce authentication

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#185]
All available actions for send scenarios are related either to authentication or moderation, but there is no way to enforce authentication and moderation at the same time. I'll explain with an example.

Let's suppose I want a private moderated list where messages from subscribers have to be moderated. I would create something like this:

```
title.gettext Private moderated

is_listmaster([sender])             smtp,dkim -> request_auth
is_listmaster([sender])             smime,md5 -> do_it
is_owner([listname],[sender])       smtp,dkim -> request_auth
is_owner([listname],[sender])       smime,md5 -> do_it
is_editor([listname],[sender])      smtp,dkim -> request_auth
is_editor([listname],[sender])      smime,md5 -> do_it
is_subscriber([listname],[sender])  smtp,dkim -> request_auth
is_subscriber([listname],[sender])  smime,md5 -> editorkey
true()                              smtp,dkim,smime,md5 -> reject(reason='send_subscriber')
```

Let's see what happens with is_subscriber lines. When a message from a subscriber comes from an authenticated channel (smime, md5) it is sent to editors to be moderated. But when it comes from an unauthenticated source the sender is requested to authenticate. When he/she authenticates the message is distributed without moderation.

If I decided to forget about authentication I could change those lines to something like this:

```
is_subscriber([listname],[sender])  smtp,dkim,smime,md5 -> editorkey
```

In this case, since you are not enforcing authentication, anybody could spoof a subscribers email address and send a message to the list. An editor, who does not know anything about spoofing and believes the message comes originally from the sender, accepts the message. 

A new action, or a combination of both of them, would be desirable. Let's call it request_auth_editorkey and then my last two lines would be:

```
is_subscriber([listname],[sender])  smtp,dkim -> request_auth_editorkey
is_subscriber([listname],[sender])  smime,md5 -> editorkey
```

Another solution would be allowing editorkey to be a modifier of request_auth action. In this case my last two lines would be:

```
is_subscriber([listname],[sender])  smtp,dkim -> request_auth,editorkey
is_subscriber([listname],[sender])  smime,md5 -> editorkey
```

Thank you very much. Regards.

**Comment by ikedas** [comment]
Hi @qosobrin,

I read [documentation of authentication methods](https://github.com/sympa-community/sympa-community.github.io/blob/master/manual/customize/basics-scenarios.md#authentication-methods).
  - If a user has successfully logged in to web interface, they have been authenticated. Thus they have `md5` level.
  - If a user sends message by mail client, they have not been authenticated. Thus they have `smtp` level.

Difference is existence of preceding authentication.  I feel it is natural that the user in latter case needs additional authentication.

Conversely, if user in the former case would need additional authentication, how they could accomplish it? (It is meaningful only if additional authentication is stronger mechanism than preceding username/password authentication).

**Comment by qosobrin** [comment]
I don't your get your point. I understand authentication mechanisms, but sympa lacks a way to enforce authentication and moderate send from smtp at the same time. If you use:

```
is_subscriber([listname],[sender])  smtp,dkim,smime,md5 -> editorkey
```
and a subscriber sends an plain smtp email (without dkim or smime) to the list, a request is sent to the editor, who can approve or deny message delivery.  Any smtp message sent to this list, whether they come from a real subscriber or from a spoofed subscriber email address, will generate a request for publication to the editors. It's in the hands of the editors to distinguish between real or spoofed email messages sent using plain smtp. This is because you can enforce authentication through smtp and request moderation at the same time.

So, now suppose you identify the problem and change your scenario to something like this.

```
is_subscriber([listname],[sender])  smtp,dkim -> request_auth
is_subscriber([listname],[sender])  smime,md5 -> editorkey
```

With this solution you enforce authentication to messages sent using plain smtp. In this new situation, when a message is received  from a subscriber using plain smtp, an authentication message is sent to the subscriber. If the subscriber confirms this authentication, the message is distributed automatically without the editor consent.

As you can see, there is no way to enforce authentication and moderation at the same time for messages sent using plain smtp, and that's my point. Sympa needs a new action for these cases. And I'm not talking only about sending, but also about subscription and any other function where moderation can be used.

**Comment by ikedas** [comment]
> So, now suppose you identify the problem and change your scenario to something like this.
> 
> ```
> is_subscriber([listname],[sender])  smtp,dkim -> request_auth
> is_subscriber([listname],[sender])  smime,md5 -> editorkey
> ```
> 
> With this solution you enforce authentication to messages sent using plain smtp. In this new situation, when a message is received  from a subscriber using plain smtp, an authentication message is sent to the subscriber. If the subscriber confirms this authentication, the message is distributed automatically without the editor consent.

Is it right? Why I ask is that those two lines are the same as lines included in `send.privatekeyandeditorkeyonly` scenario file, a "moderated" scenario.

**Comment by qosobrin** [comment]
No, you are right. I have just tested the scenario and it worked as expected. Shame on me. 

```
is_subscriber([listname],[sender])  smtp,dkim -> request_auth
is_subscriber([listname],[sender])  smime,md5 -> editorkey
```

In this scenario when a subscriber sends a plain smtp message (no smime) to the list, an authentication message is sent back to him/her. Once he/she confirms the authenticity of the original post the editor receives it to be moderated.

Sorry for the inconvenience.

Regards.
