### ISSUE TITLE
alias addresses not being created for new lists since the Operating System was updated

### ISSUE THREAD

**Issue by SympaNovice** [sympa-community/sympa#1859]
Since the Operating System (OS) on the sympa list server was updated, the sympa aliases are no longer being automatically created for any new lists.
This means that when a user sends to a new sympa list, the email is not delivered as the list address in the maillog is seen as 'User unknown'

Version
-------

Sympa 6.2.68

Installation method
-------------------

Manual

Expected behavior
-----------------

Alias addresses used by sympa should be automatically created on the creation of a new list on the sympa listserver through the web ui

Actual behavior
---------------

Since the Operating System (OS) on the listserver was updated, the sympa aliases are no longer being automatically created for any new lists.
This means that when a user sends to a new sympa list, the email is not delivered as the list address in the maillog is seen as 'User unknown' (see excerpt from maillogs below).

Apr 29 12:41:36 listserver sendmail[4242]: 43TBfaji004242: [mynewlist@mydomain.com](mailto:mynewlist@mydomain.com)... User unknown

As the sender is not notified that delivery has failed, the sender is under the impression their message has been delivered to the group when it hasn't.

Steps to reproduce
------------------

Create a list, add the subscribers and then send an email to the list address.
The email is not delivered as the list address in the maillog is seen as 'User unknown' (see excerpt from maillogs below). As the alias addresses have not been created, it does not work.

Apr 29 12:41:36 listserver sendmail[4242]: 43TBfaji004242: [mynewlist@mydomain.com](mailto:mynewlist@mydomain.com)... User unknown

Additional information
----------------------

The automatic creation of aliases as part of new list creation is currently not working. When the sympa server was originally set up the automatic creation of alias addresses when new lists were created was working. They appeared to stop working when the Server Operating System (OS) was updated so I am thinking some file permissions must have been changed as a result of the OS update. I believe it might be as simple as changing user/owner/file permissions of alias process/files but I don't know what they should be.  Any help with this would be most appreciated. 

Please Note: My workaround for the moment is to manually create the aliases for each new list that is created...I do this by
manually running the command to add the sympa alias addresses to the new list 
e.g. **/home/sympa/bin/alias_manager.pl add mynewlist mydomain.com**
I logged this with the sympa-community as a question (#1834 opened on May 9 by [SympaNovice]) back in May but to-date I have got no responses.

OS Version: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Sympa Version: Sympa 6.2.68

Current permissions:
/home/sympa/default/
-rw-r--r-- 1 root root 436 Apr 7 2022 ldap_alias_entry.tt2
-rw-r--r-- 1 root root 646 Jul 13 2022 list_aliases.tt2

/etc/mail/
-rw-r--r-- 1 root root 0 Feb 29 15:15 aliasesdb-stamp
-rw-r--r-- 1 sympa sympa 2663489 May 8 14:37 sympa_aliases
-rw-r--r-- 1 sympa sympa 5218304 May 8 15:31 sympa_aliases.db

/home/sympa/bin/
-rwxr-xr-x 1 sympa sympa 5417 Apr 7 2022 alias_manager.pl
-rw-r--r-- 1 root root 734 May 8 12:02 $SENDMAIL_ALIASES
-rwxr-xr-x 1 sympa sympa 7278 Apr 7 2022 sympa_newaliases.pl
-rwxr-x--- 1 sympa sympa 10760 Apr 7 2022 sympa_newaliases-wrapper

**Comment by ikedas** [comment]
Since you have installed Sympa manually, upgrading the OS will not automatically upgrade Sympa or its dependent modules. So you have to upgrade (i.e., to re-install) Sympa's dependency modules manually. See [the documentation](https://www.sympa.community/manual/install/install-dependent-modules.html) to know how to (re-)install dependency modules.
Note that, if you are using optional features such as LDAP, you will need to upgrade (to re-install) the specific modules for those as well.

**Comment by SympaNovice** [comment]
@ikedas Thanks for that.

As mentioned Sympa version is 6.2.68.  So we ran the command to check the modules, see the output generated from that command below. From what I can see the required modules all appear to be OK. Do you think the optional modules should be updated?

[root@list ~]# /home/sympa/bin/sympa_wizard.pl --check
##############################################################################
# This process will help you install all Perl (CPAN) modules required by Sympa
# software.
# Sympa requires from 50 to 65 additional Perl modules to run properly.
# The whole installation process should take around 15 minutes.
# You'll first have to configure the CPAN shell itself and select your
# favourite CPAN server.
# Note that you might prefer to install the required Perl modules using your
# favourite DEB/RPM mechanism.
# Feel free to interrupt the process if needed ; you can restart it safely
# afterward.
##############################################################################
Press the Enter key to continue...

Checking for PERL version:

Your version of perl is OK (5.016003  >= 5.16.0)

Checking for REQUIRED modules:

perl module                     STATUS
-----------                     ------
Archive::Zip::SimpleUnzip       OK (0.040  >= 0.024)
Archive::Zip::SimpleZip         OK (0.040  >= 0.021)
CGI                             OK (4.54   >= 3.51)
CGI::Fast                       OK (2.16   >= 1.08)
Class::Singleton                OK (1.6    >= 1.03)
DBD::mysql                      OK (4.023  >= 4.008)
DBI                             OK (1.627  >= 1.48)
DateTime::Format::Mail          OK (0.403  >= 0.28)
DateTime::TimeZone              OK (2.52   >= 0.59)
Digest::MD5                     OK (2.52   >= 2.00)
Encode                          OK (2.51   >= 1.0)
FCGI                            OK (0.74   >= 0.67)
File::Copy::Recursive           OK (0.45   >= 0.36)
File::NFSLock                   OK (1.29   >= 1.0)
File::Path                      OK (2.09   >= 2.08)
Getopt::Long                    OK (2.4    >= 2.24)
HTML::FormatText                OK (2.16   >= 1.0)
HTML::StripScripts::Parser      OK (1.03   >= 1.03)
HTML::TreeBuilder               OK (5.07   >= 1.0)
IO::File                        OK (1.16   >= 1.10)
IO::Scalar                      OK (2.113  >= 1.0)
LWP::UserAgent                  OK (6.05   >= 1.0)
List::Util::XS                  OK (1.62   >= 1.20)
Locale::Messages                OK (1.32   >= 1.20)
MHonArc::UTF8                   OK (2.6.24 >= 2.6.24)
MIME::Base64                    OK (3.13   >= 3.03)
MIME::Charset                   OK (1.012.2 >= 1.011.3)
MIME::EncWords                  OK (1.014.3 >= 1.014)
MIME::Lite::HTML                OK (1.24   >= 1.23)
MIME::Tools                     OK (5.509  >= 5.423)
Mail::Address                   OK (2.12   >= 1.70)
Net::CIDR                       OK (0.21   >= 0.16)
Sys::Syslog                     OK (0.36   >= 0.03)
Template                        OK (3.010  >= 2.21)
Term::ProgressBar               OK (2.22   >= 2.09)
Text::LineFold                  OK (2018.012 >= 2018.012)
Time::HiRes                     OK (1.9725 >= 1.29)
URI::Escape                     OK (3.31   >= 3.28)
XML::LibXML                     OK (2.0207 >= 1.70)

Checking for OPTIONAL modules:

perl module                     STATUS
-----------                     ------
AuthCAS                         was not found on this system.
Setting FTP Passive mode
-> Usage of this module: CAS Single Sign-On client libraries. Required if you
   configure Sympa to delegate web authentication to a CAS server.
-> Install module AuthCAS ? [n]
Clone                           OK (0.45   >= 0.31)
Crypt::CipherSaber              was not found on this system.
-> Usage of this module: This module provides reversible encryption of user
   passwords in the database.  Useful when updating from old version with
   password reversible encryption, or if secure session cookies in non-SSL
   environments are required.
-> Install module Crypt::CipherSaber ? [n]
Crypt::Eksblowfish              OK (0.009  >= 0.009)
Crypt::OpenSSL::X509            was not found on this system.
-> Usage of this module: Required to sign, verify, encrypt and decrypt S/MIME
   messages.
-> Install module Crypt::OpenSSL::X509 ? [n]
Crypt::SMIME                    was not found on this system.
-> Usage of this module: Required to sign, verify, encrypt and decrypt S/MIME
   messages.
-> Install module Crypt::SMIME ? [n]
DBD::CSV                        was not found on this system.
-> Usage of this module: CSV database driver, required if you include list
   members, owners or moderators from CSV file.
-> Install module DBD::CSV ? [n]
DBD::ODBC                       was not found on this system.
-> Usage of this module: ODBC database driver, required if you connect to a
   database via ODBC.
-> Install module DBD::ODBC ? [n]
DBD::Oracle                     was not found on this system.
-> Usage of this module: Oracle database driver, required if you connect to a
   Oracle database.
-> Install module DBD::Oracle ? [n]
DBD::Pg                         was not found on this system.
-> Usage of this module: PostgreSQL database driver, required if you connect
   to a PostgreSQL database.
-> Install module DBD::Pg ? [n]
DBD::SQLite                     OK (1.39   >= 1.31)
Data::Password                  OK (1.12   >= 1.07)
Encode::Locale                  OK (1.03   >= 1.02)
IO::Socket::IP                  OK (0.41   >= 0.21)
IO::Socket::SSL                 OK (1.94   >= 0.90)
LWP::Protocol::https            was not found on this system.
-> Usage of this module: Required when including members of a remote list.
-> Install module LWP::Protocol::https ? [n]
Mail::DKIM::ARC::Signer         was not found on this system.
-> Usage of this module: Required in order to use ARC features to add ARC
   seals.
-> Install module Mail::DKIM::ARC::Signer ? [n]
Mail::DKIM::Verifier            OK (0.39   >= 0.37)
Net::DNS                        OK (0.72   >= 0.65)
Net::LDAP                       OK (0.68   >= 0.40)
Net::SMTP                       OK (2.31   >= 1.0)
SOAP::Lite                      was not found on this system.
-> Usage of this module: Required if you want to run the Sympa SOAP server
   that provides mailing list services via a "web service".
-> Install module SOAP::Lite ? [n]
Unicode::Normalize              OK (1.14   >= 1.03)
Unicode::UTF8                   OK (0.62   >= 0.58)
******* NOTE *******
You can retrieve all theses modules from any CPAN server
(for example ftp://ftp.pasteur.fr/pub/computing/CPAN/CPAN.html)

**Comment by SympaNovice** [comment]
Just letting you know it is now resolved....

When setting up the new sympa server, to get sympa to work with sendmail originally, we had to change the default permissions on two directories associated with sendmail from drwxr-xr-x   to   drwxrwxr-x

The directories were		==>	         /etc/mail
 				                ==>  	/var/spool/mqueue

When the OS was patched/updated, it changed the permissions back to the default permissions

To resolve, changed the permissions using the following commands...
        chmod 775 /etc/mail
	chmod 775 /var/spool/mqueue
