### ISSUE TITLE
Sympa arc sign is not enabled

### ISSUE THREAD

**Issue by kazimkoybasi** [sympa-community/sympa#1868]
sympa does not sign messages with arc even enabled
-------
6.2.72

Installation method
-------------------
RPM on Alma Linux 9

Expected behavior
-----------------
```
ARC-Authentication-Results: i=1; domain
    arc=pass;
    dkim=pass (2048-bit rsa key sha256) header.d=domain
```
```
debug2 Sympa::Message::arc_seal() ARC sealed:
debug2 Sympa::Message::arc_seal() ARC sealed:
```

Actual behavior
---------------
```
ARC-Authentication-Results: i=1; domain
    arc=none;
    dkim=pass (2048-bit rsa key sha256) header.d=domain
```
No logs for arc seal with loglevel 3

Steps to reproduce
------------------
Configured sympa with parameters below, with postfix smtp server and opendkim on same server. When I send email to lists adress via authenticated user. 
```
dkim_feature    on
dkim_add_signature_to   robot,list
dkim_parameters.signer_domain my_domain_with_dkim_key
dkim_parameters.private_key_path /usr/share/sympa/default/key/domain/key.private
dkim_signature_apply_on any
dkim_parameters.selector my_selector
arc_feature on
```
We have 6.2.64 version on current prod and it succesfully sign messages via arc . We plan to upgrade version 6.2.72 .

Additional information
----------------------
```
Jul 26 11:56:38 sympat sympa_msg[37233]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <listname@domain.1721984196.37397/shelved:arc_cv=none> for Sympa::List <listname@domain> with priority 5, <a6cbb5a0-5e8e-45ee-a6e4-471b98999119@domain>
Jul 26 11:56:39 sympat sympa_msg[37233]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message <listname@domain.1721984196.37397/shelved:arc_cv=none;decorate;dkim_sign> is stored into bulk spool as <5.5.1721984196.1721984199.001177.listname@domain_z,37233,2473>
Jul 26 11:56:39 sympat sympa_msg[37233]: info Sympa::Spindle::ToList::_twist() Message Sympa::Message <listname@domain.1721984196.37397/shelved:arc_cv=none;dkim_sign> for Sympa::List <listname@domain> from kazimtest@domain accepted (0.06 seconds, 1 sessions, 6 subscribers), message ID=a6cbb5a0-5e8e-45ee-a6e4-471b98999119@domain, size=1371
Jul 26 11:56:39 sympat bulk[37246]: notice Sympa::Mailer::store() Done sending message Sympa::Message <5.5.1721984196.1721984199.001177.listname@domain_z,37233,2473/z/shelved:arc_cv=none> for Sympa::List <listname@domain> (priority 5) in 3 seconds since scheduled expedition date
Jul 26 11:57:34 sympat sympa_msg[37233]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <listname@domain.1721984251.37411/shelved:arc_cv=none> for Sympa::List <listname@domain> with priority 5, <807801e3-ae87-4fc1-aab3-d4ea6359f4cc@domain>
Jul 26 11:57:34 sympat sympa_msg[37233]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message <listname@domain.1721984251.37411/shelved:arc_cv=none;decorate;dkim_sign> is stored into bulk spool as <5.5.1721984251.1721984254.148041.listname@domain_z,37233,7974>
Jul 26 11:57:34 sympat sympa_msg[37233]: info Sympa::Spindle::ToList::_twist() Message Sympa::Message <listname@domain.1721984251.37411/shelved:arc_cv=none;dkim_sign> for Sympa::List <listname@domain> from kazimtest@domain accepted (0.06 seconds, 1 sessions, 6 subscribers), message ID=807801e3-ae87-4fc1-aab3-d4ea6359f4cc@domain, size=1371
Jul 26 11:57:34 sympat bulk[37246]: notice Sympa::Mailer::store() Done sending message Sympa::Message <5.5.1721984251.1721984254.148041.listname@domain_z,37233,7974/z/shelved:arc_cv=none> for Sympa::List <listname@domain> (priority 5) in 3 seconds since scheduled expedition date
```

Thank you for supporting sympa.

**Comment by ikedas** [comment]
Hi @kazimkoybasi ,

The Actual Behavior you presented appears to be normal. That is, Sympa appends the first instance (`I=1`) of the ARC seal to the message.

**Comment by ikedas** [comment]
> If it is expected, how can I see ARC sealed: message in log ? Are there any configuration for this ?

Sympa is not designed to log "ARC sealed" when an ARC seal is added. That's why it can not.

> I just realized that it does not fail to deliver @gmail.com and @hotmail.com addresses incoming email from our domain but it fails to deliver emails which is sent from aol.com and yahoo.com and header is below for these emails .

AOL.com and Yahoo.com are known to not honor the ARC seals in messages they receive and to have a DMARC policy of entire rejection.   In other words, they uniformly reject messages originating from their own service email addresses if they are routed through an outside server, e.g. mailing list.

You might want to deal with such recipient sites using [DMARC protection](https://www.sympa.community/manual/customize/dmarc-protection.html) settings.

**Comment by kazimkoybasi** [comment]
Hi @ikedas,
Thank you for your answer.  Sorry for misunderstanding, our smtp server does not have any ARC implementation other than Sympa and Sympa does not log as "ARC sealed" even for emails sent from our smtp server, which has only dkim signing implementation.  Sympa log for one of the message which is sent from our smtp server is like below. Does my sympa configuration have issues? We have dmarc reject record for our main email domain and lists domain.

Jul 27 16:10:52 sympat sympa_msg[40899]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <test-list@sympat.univ.edu.1722085851.40932>; envelope_sender=user1@univ.edu; message_id=ccf6e237-7a14-40c0-99a2-43020b784c06@univ.edu; sender=user1@univ.edu
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::new(Sympa::Scenario, sympat.univ.edu, spam_status, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::_compile_scenario(sympat.univ.edu, spam_status, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::new(Sympa::Scenario, sympat.univ.edu, include, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::authz(Sympa::Scenario <spam_status.x-spam-status;/usr/share/sympa/default/scenari/spam_status.x-spam-status>, smtp, HASH, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::check_smime_signature(Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none>)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::smime_decrypt(Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none>)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::check_virus_infection(Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none>, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug Sympa::Message::check_virus_infection() Sympa not configured to scan virus in message
Jul 27 16:10:52 sympat sympa_msg[40899]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none> for Sympa::List <test-list@sympat.univ.edu> with priority 5, <ccf6e237-7a14-40c0-99a2-43020b784c06@univ.edu>
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::get_plain_body(Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none>)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::new(Sympa::Scenario, Sympa::List <test-list@sympat.univ.edu>, send, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::_compile_scenario(Sympa::List <test-list@sympat.univ.edu>, send, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::new(Sympa::Scenario, Sympa::List <test-list@sympat.univ.edu>, include, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::authz(Sympa::Scenario <send.editorkey;/usr/share/sympa/default/scenari/send.editorkey>, smtp, HASH, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Scenario::do_search(Sympa::List <test-list@sympat.univ.edu>, HASH, blocklist.txt)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::is_admin(Sympa::List <test-list@sympat.univ.edu>, actual_editor, user1@univ.edu, )
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_admins(Sympa::List <test-list@sympat.univ.edu>, actual_editor, filter => ARRAY)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Database::connect() Connected to Database Sympa::DatabaseDriver::MySQL <db_host=db.univ.edu;db_name=sympa;db_user=sympa>
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Spindle::ToModeration::_send_confirm_to_editor(Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none>, md5)
Jul 27 16:10:52 sympat sympa_msg[40899]: notice Sympa::Spool::store() Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none> is stored into Sympa::Spool::Moderation as <test-list@sympat.univ.edu_c493857740ec4b844008966ea7b20616>
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::_load_edit_list_conf(Sympa::List <test-list@sympat.univ.edu>)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_admins(Sympa::List <test-list@sympat.univ.edu>, receptive_editor,  => )
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::send_file(Sympa::List <test-list@sympat.univ.edu>, moderate, user@univ.edu, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::User::get_global_user(user@univ.edu)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_list_member(Sympa::List <test-list@sympat.univ.edu>, user@univ.edu)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_list_member() attrib = ()
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_admins(Sympa::List <test-list@sympat.univ.edu>, owner,  => )
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::Template::_new_from_template(Sympa::Message::Template, Sympa::List <test-list@sympat.univ.edu>, moderate.tt2, user@univ.edu, HASH)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::new(Sympa::Message::Template, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <test-list@sympat.univ.edu.1722085853.40899,4894/shelved:dkim_sign>; envelope_sender=test-list-owner@sympat.univ.edu; message_id=sympa.1722085852.340091.40899.231@sympat.univ.edu; recipients=user@univ.edu; sender=test-list-request@sympat.univ.edu; template=moderate;
Jul 27 16:10:52 sympat sympa_msg[40899]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message::Template <test-list@sympat.univ.edu.1722085853.40899,4894/shelved:dkim_sign> is stored into bulk spool as <5.5.1722085853.1722085852.486270.test-list@sympat.univ.edu_s,40899,2468>
Jul 27 16:10:52 sympat sympa_msg[40899]: info Sympa::Spindle::ToModeration::_twist() Key c493857740ec4b844008966ea7b20616 of message Sympa::Message <test-list@sympat.univ.edu.1722085851.40932/shelved:arc_cv=none> for list Sympa::List <test-list@sympat.univ.edu> from user1@univ.edu sent to editors (0.43 seconds)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::User::get_global_user(user1@univ.edu)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_list_member(Sympa::List <test-list@sympat.univ.edu>, user1@univ.edu)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_list_member() attrib = ()
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::List::get_admins(Sympa::List <test-list@sympat.univ.edu>, owner,  => )
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::Template::_new_from_template(Sympa::Message::Template, Sympa::List <test-list@sympat.univ.edu>, delivery_status_notification.tt2, user1@univ.edu, HASH)
Jul 27 16:10:52 sympat sympa_msg[40899]: debug2 Sympa::Message::new(Sympa::Message::Template, ...)
Jul 27 16:10:52 sympat sympa_msg[40899]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <test-list@sympat.univ.edu.1722085852.40899,6928/shelved:dkim_sign>; envelope_sender=<>; message_id=sympa.1722085852.508257.40899.79@sympat.univ.edu; recipients=user1@univ.edu; sender=sympa-request@sympat.univ.edu; template=delivery_status_notification; action=delayed; status=4.3.0
Jul 27 16:10:52 sympat sympa_msg[40899]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message::Template <test-list@sympat.univ.edu.1722085852.40899,6928/shelved:dkim_sign> is stored into bulk spool as <5.5.1722085852.1722085852.518472.test-list@sympat.univ.edu_s,40899,4425>
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::new(Sympa::Message, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <sympa@sympat.univ.edu.1722085865.2369,5396>; envelope_sender=sympa-request@sympat.univ.edu; message_id=<sympa.1722085865.403018.2369.997@sympat.univ.edu>; sender=user@univ.edu
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Scenario::new(Sympa::Scenario, sympat.univ.edu, spam_status, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Scenario::authz(Sympa::Scenario <spam_status.x-spam-status;/usr/share/sympa/default/scenari/spam_status.x-spam-status>, smtp, HASH, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::check_smime_signature(Sympa::Message <sympa@sympat.univ.edu.1722085865.2369,5396/shelved:arc_cv=none>)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::smime_decrypt(Sympa::Message <sympa@sympat.univ.edu.1722085865.2369,5396/shelved:arc_cv=none>)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::check_virus_infection(Sympa::Message <sympa@sympat.univ.edu.1722085865.2369,5396/shelved:arc_cv=none>, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug Sympa::Message::check_virus_infection() Sympa not configured to scan virus in message
Jul 27 16:11:07 sympat sympa_msg[40899]: debug Sympa::Spindle::DoCommand::_twist() Processing command with priority 1, <sympa.1722085865.403018.2369.997@sympat.univ.edu>
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::get_plain_body(Sympa::Message <sympa@sympat.univ.edu.1722085865.2369,5396/shelved:arc_cv=none>)
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Request::Message::__parse() Parsing: QUIET DISTRIBUTE test-list c493857740ec4b844008966ea7b20616
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::_load_edit_list_conf(Sympa::List <test-list@sympat.univ.edu>)
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Spindle::ProcessMessage::_twist() Processing Sympa::Request <action=distribute;context=test-list@sympat.univ.edu>
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::_load_edit_list_conf(Sympa::List <test-list@sympat.univ.edu>)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::new(Sympa::Message, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::smime_decrypt(Sympa::Message <test-list@sympat.univ.edu_c493857740ec4b844008966ea7b20616.distribute/shelved:arc_cv=none>)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::update_stats(Sympa::List <test-list@sympat.univ.edu>, 1, , , )
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::_increment_msg_count(Sympa::List <test-list@sympat.univ.edu>)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Robot::load_topics(sympat.univ.edu)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::sync_include(Sympa::List <test-list@sympat.univ.edu>, member)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_total_bouncing()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::send_notify_to_owner(Sympa::List <test-list@sympat.univ.edu>, bounce_rate, HASH)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_admins(Sympa::List <test-list@sympat.univ.edu>, receptive_owner,  => )
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::send_file(Sympa::List <test-list@sympat.univ.edu>, listowner_notification, ARRAY, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_admins(Sympa::List <test-list@sympat.univ.edu>, owner,  => )
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::Template::_new_from_template(Sympa::Message::Template, Sympa::List <test-list@sympat.univ.edu>, listowner_notification.tt2, ARRAY, HASH)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Message::new(Sympa::Message::Template, ...)
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <test-list@sympat.univ.edu.1722085867.40899,3227/shelved:dkim_sign>; envelope_sender=test-list-owner@sympat.univ.edu; message_id=sympa.1722085867.634987.40899.739@sympat.univ.edu; recipients=ARRAY; sender=sympa@sympat.univ.edu; template=listowner_notification; type=bounce_rate
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: univ.edu; rcpt by dom: 1; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message::Template <test-list@sympat.univ.edu.1722085867.40899,3227/shelved:dkim_sign> is stored into bulk spool as <5.5.1722085867.1722085867.640671.test-list@sympat.univ.edu_s,40899,571>
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_first_list_member(Sympa::List <test-list@sympat.univ.edu>, email, )
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_next_list_member()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_next_list_member()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_next_list_member()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_next_list_member()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_next_list_member()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::get_next_list_member()
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spindle::ToList::_mail_message(Sympa::Message <test-list@sympat.univ.edu_c493857740ec4b844008966ea7b20616.distribute/shelved:arc_cv=none;decorate;dkim_sign>, ARRAY, tag => z)
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: aol.com; rcpt by dom: 1; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: gmail.com; rcpt by dom: 1; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: hotmail.com; rcpt by dom: 1; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: univ.edu; rcpt by dom: 1; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: univ.edu; rcpt by dom: 2; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::Spool::Outgoing::_get_recipient_tabs_by_domain() Domain: yahoo.com; rcpt by dom: 1; limit for this domain:
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Spool::Outgoing::store() Message Sympa::Message <test-list@sympat.univ.edu_c493857740ec4b844008966ea7b20616.distribute/shelved:arc_cv=none;decorate;dkim_sign> is stored into bulk spool as <5.5.1722085867.1722085867.645129.test-list@sympat.univ.edu_z,40899,5107>
Jul 27 16:11:07 sympat sympa_msg[40899]: debug2 Sympa::List::update_stats(Sympa::List <test-list@sympat.univ.edu>, 0, 6, 2749, 16494)
Jul 27 16:11:07 sympat sympa_msg[40899]: notice Sympa::Spindle::ToList::_send_msg() No VERP subscribers left to distribute message to list Sympa::List <test-list@sympat.univ.edu>
Jul 27 16:11:07 sympat sympa_msg[40899]: info Sympa::Spindle::ToList::_twist() Message Sympa::Message <test-list@sympat.univ.edu_c493857740ec4b844008966ea7b20616.distribute/shelved:arc_cv=none;dkim_sign> for Sympa::List <test-list@sympat.univ.edu> from user@univ.edu accepted (0.07 seconds, 1 sessions, 6 subscribers), message ID=ccf6e237-7a14-40c0-99a2-43020b784c06@univ.edu, size=1568
Jul 27 16:11:07 sympat sympa_msg[40899]: info Sympa::Request::Handler::distribute::_twist() DISTRIBUTE test-list c493857740ec4b844008966ea7b20616 from user@univ.edu accepted (0.07 seconds)


Best Regards.

**Comment by ikedas** [comment]
I do not understand what you are expecting.

I searched Sympa source code for the string "``ARC sealed``" and found no hits.  That is, Sympa *should not* output the string "ARC sealed" in any case.

In the first place, the ``ARC-Authentication-Results`` field (AAR) containing ``arc=none`` is a valid term to be included in the first instance (``i=1``) of the ARC seal (See [RFC8617](https://datatracker.ietf.org/doc/html/rfc8617#section-5.2)).  Thus, it is clear that your Sympa has successfully ARC-sealed the message.

If what you expect is different from what I wrote above, please explain it in other words.

**Comment by kazimkoybasi** [comment]
Hi @ikedas,

I got the point now. Sympa version 6.2.64 is logging as **debug2 Sympa::Message::arc_seal() ARC sealed:** and this part is changed in Sympa 6.2.72, so new version does not write this log for ARC Sign.  Thank you for information and your time.

Best Regards.
