### ISSUE TITLE
sympa_msg crashes with signal 10 on FreeBSD

### ISSUE THREAD

**Issue by kokarl** [sympa-community/sympa#1887]
Version
-------
Version : sympa 6.2.72

Installation method
-------------------
Running on FreeBSD 13.3 with perl 5.40. Installed from ports. 

Expected behavior
-----------------
Process sympa_msg.pl should not die...

Actual behavior
---------------
Previous process sympa_msg.pl crashed with the following errors : 
Use of uninitialized value $_ in split at /usr/local/libexec/sympa/Sympa/Spool/Outgoing.pm line 335.
Use of uninitialized value $dom in hash element at /usr/local/libexec/sympa/Sympa/Spool/Outgoing.pm line 355.

**Comment by ikedas** [comment]
Hi @kokarl ,
Could you please provide more information, such as all of the logs related to the message that caused the crash in question?

**Comment by kokarl** [comment]
Hello @ikedas 

Nothing in my sympa.log as I'm in log_level =0 in my sympa.conf. I just switched to log_level=4 and waiting sympa_msg.pl crash again...

**Comment by ikedas** [comment]
`log_level` doesn't matter.  Please show the log _from when_ the message in question was picked from `msg` spool _to when_ the crashing occurred: Show all logs for this period, rather than just taking out several lines that you think make sense (sensitive information may be masked).

**Comment by kokarl** [comment]
Here are the logs I got before sympa_msg.pl crashes : 

Sep  6 10:07:19 serveur sympa_msg[98237]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <sympa@myrobot.fr.1725610038.90355,7455>; envelope_sender=sympa-request@myrobot.fr; message_id=<sympa.1725610038.635891.90355.175@myrobot.fr>; sender=sender@sender.fr
Sep  6 10:08:05 serveur wwsympa[90355]: notice Sympa::Spool::store() Sympa::Message <<sympa.1725610085.304704.90355.263@myrobot.fr>> is stored into Sympa::Spool::Incoming as <sympa@myrobot.fr.1725610085.90355,1288>
Sep  6 10:10:21 serveur sympa_msg[98237]: notice Sympa::Request::Message::__parse() Parsing: QUIET DISTRIBUTE maliste cf49f2d7f7b5315bfdbaf9e08b7eaae0
Sep  6 10:10:21 serveur sympa_msg[98237]: notice Sympa::Spindle::ProcessMessage::_twist() Processing Sympa::Request <action=distribute;context=maliste@myrobot.fr>
Sep  6 10:10:21 serveur kernel: pid 98237 (perl), jid 0, uid 200: exited on signal 10

**Comment by ikedas** [comment]
Hi @kokarl ,
The signal 10 ([Bus Error](https://en.wikipedia.org/wiki/Bus_error) on FreeBSD) is scaresely considered that it is caused by Sympa itself.
This error is most likely caused by any bugs in external Perl module(s) used by Sympa and other software. Another relatively rare cause could be a hardware failure.

You'd be bette to monitor if the similar problems continue to occur. If so, you should consider updating the OS and all modules and/or replacing the hardware.

**Comment by kokarl** [comment]
Hi @ikedas 

Thanks for your feedback. First, I will try to update all the perl module installed on my FreeBSD Server, and monitor what's goind on. And If the issue still occurs, I will update all the packages installed on my system.
