### ISSUE TITLE
Modified web template file lists.tt2 in sysconfigdir isn't being used by Sympa

### ISSUE THREAD

**Issue by fusenuk** [sympa-community/sympa#1895]
Version
-------
Sympa 6.2.72
Red Hat Enterprise Linux Server 7.9 (Maipo) AND Red Hat Enterprise Linux 9.4 (Plow)

Installation method
-------------------
Installed via YUM package manager from official RHEL repo

Expected behavior
-----------------
A new file named **lists.tt2** was added into **/etc/sympa/web_tt2** and I expected this copy of the templated file to be served in the browser by Sympa

Actual behavior
---------------
We use multiple modified web_tt2 files -

```
root@sympa-dev:/etc/sympa/web_tt2# ls -hal
total 40K
drwxr-xr-x.  2 root  root   134 Sep 19 10:17 .
drwxr-xr-x. 12 sympa sympa 4.0K Sep 19 10:25 ..
-rw-r--r--.  1 root  root  6.2K Sep 19 10:14 create_list_request.tt2
-rw-r--r--.  1 root  root   408 Jun 15  2018 footer.tt2
-rw-r--r--.  1 root  root  1.4K Oct 29  2020 help.tt2
-rw-r--r--.  1 root  root  4.5K Oct 29  2020 home.tt2
-rw-r--r--.  1 root  root  3.7K Sep 19 10:15 lists.tt2
-rw-r--r--.  1 root  root  4.0K Jun 15  2018 my.tt2
-rw-r--r--.  1 root  root  2.9K Oct 11  2018 pref.tt2
```

When restarting Sympa/httpd, the lists.tt2 file is not being used from this location **/etc/sympa/web_tt2** instead the copy of the file being served to the browser is in the normal distribution directory of **/usr/share/sympa/default/web_tt2**

The other recently modified file of **create_list_request.tt2** is successfully being served from **/etc/sympa/web_tt2**

Additional information
----------------------
The fact the modified create_list_request.tt2 is being successfully used in the /etc/sympa/ folder would suggest the default values for the web_tt2 sysconfigdir and defaultdir are normal. I've looked in the documentation and my local config and I can't find anywhere where I would need to tell Sympa specifically to use the new lists.tt2 file, it sounds like the file simply existing in /etc/sympa/web_tt2 should be enough to tell it to use this modified version.

I'm seeing this behaviour across two different RHEL servers but both using the Sympa version mentioned above.

**Comment by fusenuk** [comment]
With a little bit of nudging from ChatGPT I managed to fix the issue. It suggested this -

```
However, if there are issues with your new template, Sympa might fallback to the default template in /usr/share/sympa/default/web_tt2/. To ensure your new template is being used:

    Temporarily rename or remove the fallback default template in /usr/share/sympa/default/web_tt2/, forcing Sympa to use your custom template.
```

so I renamed 'lists.tt2' in /usr/share/sympa/default/web_tt2/ and then tried to search for a list and it gave an error that the file **search_list.tt2** was missing.

I then noticed this symlink _lrwxrwxrwx. 1 root root    9 Aug 22 16:01 search_list.tt2 -> lists.tt2_

so my fix is to simply rename **lists.tt2** to **search_list.tt2** in the **/etc/sympa/web_tt2/** directory and now the custom template is being used instead.

**Comment by fusenuk** [comment]
With a little bit of nudging from ChatGPT I managed to fix the issue. It suggested this -

```
However, if there are issues with your new template, Sympa might fallback to the default template in /usr/share/sympa/default/web_tt2/. To ensure your new template is being used:

    Temporarily rename or remove the fallback default template in /usr/share/sympa/default/web_tt2/, forcing Sympa to use your custom template.
```

so I renamed 'lists.tt2' in /usr/share/sympa/default/web_tt2/ and then tried to search for a list and it gave an error that the file **search_list.tt2** was missing.

I then noticed this symlink _lrwxrwxrwx. 1 root root    9 Aug 22 16:01 search_list.tt2 -> lists.tt2_

so my fix is to simply rename **lists.tt2** to **search_list.tt2** in the **/etc/sympa/web_tt2/** directory and now the custom template is being used instead.

**Comment by ikedas** [comment]
Hi @fusenuk ,
Please read [the documentation of Sympa]() also.

About configuration files it [says](https://www.sympa.community/manual/customize/basics-configuration.html):

> ### Changing configuration files
> When you customize configuration files, don't edit files under [$DEFAULTDIR](https://www.sympa.community/manual/layout.html#defaultdir) directly. Changes on the files under this directory will be overwritten by new version during upgrade process.
> 
> Instead, you should copy files under $DEFAULTDIR directory into the directory of appropriate scope (see previous section), then edit these copies.

In other words, you should have changed the files under `/etc/sympa`, instead of those under `/usr/share/sympa/default`.

**Comment by fusenuk** [comment]
That's what I did, as mentioned in the original post. The edited new template files were under **/etc/sympa/web_tt2**

As part of the investigation into what was causing the problem, the file in **/usr/share/sympa/default** was temporarily renamed and that showed that the actual template filename needed within **/etc/sympa/web_tt2** was **search_list.tt2** not **/etc/sympa/web_tt2**

The fix was renaming the file that existed in **/etc/sympa/web_tt2** to **search_list.tt2**
