### ISSUE TITLE
Change bundled Raleway font from TTF to OTF

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#190]
Hi,

While looking at unbundling the Raleway font from Sympa for Fedora/EPEL package, I noticed the bundled version is TTF, while the Fedora provided version is OTF. I filed a bug at Fedora [1] to get the TTF version packaged, but it turned out OTF fonts are preferred over TTF [2] and thus the request was denied. Upstream for Raleway also has dropped support for TTF in later (not yet stable) releases of the font [3]. 
Also, it's seems the font was not updated since it was imported in Sympa 3 years ago [4] while upstream has updated it [5]. The font would need to be refreshed from [6].

Thanks,
Xavier

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1525401
[2] https://fedoraproject.org/wiki/Choosing_the_right_font_format_to_package
[3] https://github.com/impallari/Raleway/tree/master/fonts/v4020
[4] https://github.com/sympa-community/sympa/commit/08de4d7cb287541d7c1e69e77535cd09f73b1975
[5] https://github.com/impallari/Raleway/commits/master/fonts/v3.000%20Fontlab
[6] https://github.com/impallari/Raleway/tree/master/fonts/v3.000%20Fontlab/OTF

**Comment by racke** [comment]
I suppose the browsers are just fine with OTF?

**Comment by xavierba** [comment]
It works fine for me in Firefox, and my understanding is otf is similar enough to ttf to not induce any issue, but you have a valid point, I'll check with Chromium and try to find others to test with (but won't be able to test on anything IE, Edge or whatever the poor^W windows/mac users are suffering from^W^W^Wusing).

**Comment by ikedas** [comment]
I think: As browsers supporting only TTF may provide poor support for web fonts, they should be omitted. In short, OTF is sufficient.

**Comment by qosobrin** [comment]
I would volunteer to do a brief test on Mac OS, iOS and Windows browsers as long somebody could provide me with a testing installation of Sympa using OpenType fonts.

**Comment by ikedas** [comment]
The fix by xavierba will be iconluded in the next beta, 6.2.25b.1.

**Comment by ikedas** [comment]
@qosobrin and all, thanks for testing!  Is there any problem? If it looks nothing, I’ll close this issue.
