### ISSUE TITLE
Nasima Akthar Lipi

### ISSUE THREAD

**Issue by nasima0081-t5** [sympa-community/sympa#1900]
issue is the best working yet
In above example httpd or network are System V scripts written in bash or sh shell. Here is a sample shell script:
Version

#!/bin/bash
#
# chkconfig: 35 90 12
# description: Foo server
#

# Get function from functions library
. /etc/init.d/functions

# Start the service FOO
start() {
Installation method
-------------------

Expected behavior
-----------------

Actual behavior
---------------

Additional information
----------------------

**Comment by racke** [comment]
Don't see any relevance for Sympa in this ticket.
