### ISSUE TITLE
Question: How can I alert you about English strings errors or typos?

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#192]
I am privately translating sympa (I will send it to the community later) and I have discovered some errors, typos and mistakes in the original English strings. I understand that opening a new issue for every one of them would be somewhat cumbersome, both for me and the community, but I have no problem doing so.

I could also do it myself (fork the original branch, edit and request the pull) but that would break the translations in every language since the original string changed.

How do you prefer for me to proceed? I would be open to any other solutions.

Thank you. Regards.

**Comment by ikedas** [comment]
@qosobrin, see #115.

**Comment by qosobrin** [comment]
All right, thank you.
