### ISSUE TITLE
Rejection message returned when suscribing to a list restricted info access

### ISSUE THREAD

**Issue by mdurandGH** [sympa-community/sympa#193]
Hello,
And first of all my excuses for my poor English, it's such a long time I haven't spoken !
Here is my situation and request : I have created several lists with Framalistes.org using Sympa, all in "author" or "private" mode, which means anyone can subscribe but with my authorization. 
I have encountered an issue found when someone is trying to subscribe to one of this list : in fact, he receive a kind of purple banner (from Framalistes I guess ?) written : "Access denied : you are not allowed to do this action.", so that people think it didn't work and try again and again...
I would prefer them to read something like "your demand has been registered but requires a manual validation ; you'll be soon noticed when it will be done".
But I don't find a way to change this message : it seams easy to create or change message for people who've already subscribed and are on the list, but I find nothing to create or change the message to someone who hasn't subscribed yet and has no rights.
Thanks a lot for help and have a good day all !
mdurandGH

**Comment by ikedas** [comment]
Hi @mdurandGH,

What are "author" and "private" modes? Please show us the screen shot of web page where you saw these modes.

**Comment by mdurandGH** [comment]
Hi ikedas,
Thanks for interest and sorry cause I made a mistake : it was "auth" and "owner", which are privileges settings (I though they were due to sympa, but maybe only set by framalistes ?), to decide who is allowed to subscribe or not :
"auth" = subscription request confirmed
"owner" = needs owner approval
NB : "private" is a confidentiality setting (who can access to list information, or who is able to invite new subscribers, etc.)
Here is a screen shot : 
![image](https://user-images.githubusercontent.com/36455785/36309509-34b4d45c-1325-11e8-9e9d-34fb9fe8bf09.png)

**Comment by ikedas** [comment]
@mdurandGH,
When "someone is trying to subscribe to one of this list", what operation did that person perform? (For example: she/he sent a message to the address xxx@xxxx; she/he opened the URL xxx then clicked xxx button...) Please describe us the details.

**Comment by mdurandGH** [comment]
@ikedas 
Thanks for your return.

At first the problem occured with the second method : after opening the URL : https://framalistes.org/sympa/subscribe/[name of the list], adding his/her email and clicking "OK", people see this message : 
![image](https://user-images.githubusercontent.com/36455785/36374266-0243cd64-156b-11e8-9020-59fb40419457.png)
(means "ACCES DENIED (information) : you are not allowed to do this action")
That's where I would prefer a message like "your demand has been registered but requires a manual validation ; you'll be soon notified when it will be done" whithout finding how to set this.

After your message I also tried to add someone by writing a mail from his adress to sympa@framalistes.org, with "subscribe [nameofthelist]" in subject, and this time it is ok, cause the subscriber receive back a mail telling : "La commande a été exécutée : subscribe [nameofthelist] sent_to_owner Votre demande d'abonnement (ou de désabonnement) a été envoyée aux
propriétaires de la liste pour examen. Vous recevrez une notification lorsque ceux-ci vous auront abonné (ou désabonné) à la liste."
Which means : "The command has been executed : subscribe [nameofthelist] sent_to_owner ; Your subscribing (or unscubscribing) demand has been sent to list owners for validation. You will be notified when they will accept your subscription (or unsubscription)."

That is exactly the kind of message I would expect with the graphic method, the one that is used by most people who don't understand anything to this lists things and just would like to receive messages ;-)

Thanks again, have a good day !

**Comment by ikedas** [comment]
@mdurandGH, I got it.

After a user successfully subscribed to a list using web, she/he will be redirected to list information page `https://framalistes.org/sympa/info/[name of the list]`.  However, your list has a setting "Who can view list information" to "restricted to subscribers (private)".  If the user has not logged in, Sympa cannot know who is the user, and decides that this user is _not_ a subscriber. That's why the message "ACCES REFUSE" is shown.

One workaround is setting "Who can view list information" to "for anyone (open)".

However, someone obviously won't prefer to exposing their list to the public.  I think it is a bug to be fixed.

**Comment by racke** [comment]
Sounds like a bug to me too - at least user should be asked to login before viewing the list information.

**Comment by ikedas** [comment]
Please [a patch](https://github.com/sympa-community/sympa/compare/sympa-6.2...ikedas:issue-193.patch) to fix problem.

**Comment by mdurandGH** [comment]
Thanks @ikedas and @racke for your returns and patch !
The Framalistes team has been informed and will integrate the patch with the next service update (unknown date by now).

**Comment by ikedas** [comment]
@mdurandGH, thanks for information.  Closed.
