### ISSUE TITLE
Move smtpc to independent repository

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#201]
Currrently smtpc (sympa_smtpc) is bundled in source distribution.

It may be required for some environment as an alternative to sendmail utility not supporting some extended feature<sup>[1]</sup>, but such situation is rare.  So I propose moving smtpc to sympa-contribs repo.

[1]  sendmail utility provided by OpenSMTPD is known not supporting envelope ID feature which is required to provide tracking feature of Sympa.

**Comment by xavierba** [comment]
My understanding is this piece of code might have an usage outside of sympa. Maybe having it as a project on its own would give it more exposure and potential contributors ?

**Comment by ikedas** [comment]
> My understanding is this piece of code might have an usage outside of sympa. Maybe having it as a project on its own would give it more exposure and potential contributors ?

It makes sense. 

Do you mean it would be better to be moved outside of sympa-community? (I can use my personal space or my company's space).

**Comment by xavierba** [comment]
Yes, outside of sympa-community. I trust you to find a location where smtpc could live on its own.

**Comment by ikedas** [comment]
Okey, I did it: https://github.com/ikedas/smtpc

If no objection, src/smtpc in sympa repo will be removed on the next release (6.2.25b.2).

**Comment by ikedas** [comment]
It was removed.
