### ISSUE TITLE
Notification not sent to the owner when a list is confirmed by a listmaster

### ISSUE THREAD

**Issue by ydelattre** [sympa-community/sympa#212]
Hi,

with sympa version 6.2.24, the notification is not sent to the owner when a list is confirmed by a listmaster.
Only the notification to the listmaster is sent.

We did some debug.
It appears the value of the "notify owner" checkbox is not passed to the confirm_action.tt2

From confirm action page :

```html
<form action="/wwsympa/" method="POST">
<input name="mode" value="install" type="hidden">
--><input name="notify" value="" type="hidden"><--
  <input name="action" value="open_list" type="hidden">
  <input name="list" value="test-issue" type="hidden">
  <input name="previous_action" value="set_pending_list_request" type="hidden">
  <div>
    <input class="MainMenuLinks" id="response_action_confirm" name="response_action_confirm" value="Confirmer" type="submit">
    <input class="MainMenuLinks" id="response_action_cancel" name="response_action_cancel" value="Retour" type="submit">
  </div>
</form>
```

The value is correct in the page's post parameters :

```
action : open_list
list : test-issue
mode : install
notify : on
previous_action : set_pending_list_request
serial : 1
```

Thanks for your help.

**Comment by ikedas** [comment]
Hi @ydelattre,

Can you apply [this patch](https://github.com/ikedas/sympa/commit/f22b139.patch) and check if problem you reported will be solved? Thanks.

**Comment by ydelattre** [comment]
Hi @ikedas,

this patch solve the issue :)
Thanks a lot for your reactivity !

**Comment by ikedas** [comment]
Thanks for confirmation.

The patch was applied. This issue is closed.
