### ISSUE TITLE
Unify scenario names

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#216]
I understand that this is just a matter of aesthetics here and my request is not very important, but there are some scenarios named:
```
access_web_archive.closed
access_web_archive.intranet
access_web_archive.listmaster
access_web_archive.owner
access_web_archive.private
access_web_archive.public
```
while others are named using a different pattern:
```
archive_mail_access.closed
archive_mail_access.default
archive_mail_access.owner
archive_mail_access.private
archive_mail_access.public
```
Only one pattern would be desirable, either archive_mail_access.* and archive_web_access.* , or access_web_archive.* and access_mail_archive.*

Thank you very much.
Regards.

**Comment by ikedas** [comment]
@qosobrin, I agree to consistent naming. Please go on.

**Comment by ikedas** [comment]
@qosobrin, your PR was merged. Thanks for good change!

**Comment by qosobrin** [comment]
Sorry for the delay. I was out for a while. Thank you for the merge.
