### ISSUE TITLE
Cannot set Japanese charactors in list subject

### ISSUE THREAD

**Issue by frisky-gh** [sympa-community/sympa#218]
At setting page "/wws/edit_list_request/LIST-ID/description", I cannot set Japanese characters in list subject.
If I set subject including characters such as "あ", those characters store as invalid, such as "ÃÂ".
I use sympa-6.2.16 (debian stable).

It is caused by character encoding. Perhaps, it will be fixed following patch:

```
--- /usr/share/sympa/lib/Sympa/List.pm.orig     2018-03-02 20:50:29.223568943 +0900
+++ /usr/share/sympa/lib/Sympa/List.pm  2018-03-02 20:50:49.984497769 +0900
@@ -8614,7 +8614,7 @@
                 $p->{'hour'}, $p->{'minute'};
             $fd->print(sprintf "%s %s\n\n", $key, $value);
         } else {
-            $fd->print(sprintf "%s %s\n\n", $key, $p);
+          $fd->print(sprintf "%s %s\n\n", $key, Encode::decode_utf8($p));
         }
     }

```

**Comment by ikedas** [comment]
Hi @frisky-gh,

確証はないですが、この件はSympa 6.2.24で直っているかもしれません (#134)。busterで試していただくことは可能でしょうか。

I’m not sure but the bug possibly fixed by Smpa 6.2.24 (see issue #134).  Could you please check the buster?

**Comment by frisky-gh** [comment]
ありがとうございます。
Sympa 6.2.24 (buster) で修正されていることを確認できました。

**Comment by ikedas** [comment]
Duplicate of #134.
