### ISSUE TITLE
Message-ID increment failing

### ISSUE THREAD

**Issue by jonccrice** [sympa-community/sympa#226]
We have a number of e-lists where the Message-ID of does not increment.
Some of them increment intermittently.
These all appear to be in the same list family.
Sample list config attached.
[announcements-all.config.txt](https://github.com/sympa-community/sympa/files/1794650/announcements-all.config.txt)

**Comment by ikedas** [comment]
Hi @jonccrice,

  - What version of Sympa are you using?
  - I understand "Message-ID" is sequence number prepended to message subject. Am I right?

**Comment by jonccrice** [comment]
Hi!

We running Sympa version 6.1.15.
The message-id I referring to is in the message header.
For example, in the e-list announcements-all@elist.tufts.edu<mailto:announcements-all@elist.tufts.edu> the message header field (Message-ID:)
The sample message header below show the value of the Message-ID field to be <announcements-all.115@anonymous> .
The 115 number is not incrementing reliably.

Received: from smtpin-prod-11.uit.tufts.edu (10.246.136.17) by
tabvmexcashub01.tufts.ad.tufts.edu (10.246.136.81) with Microsoft SMTP Server
(TLS) id 14.3.352.0; Tue, 3 Oct 2017 16:13:02 -0400
Received: from tssdc-lb-float-eipubwebapp.net.tufts.edu ([10.250.108.11]:51482
helo=ppagent-prod-08.uit.tufts.edu)       by smtpin-prod-11.uit.tufts.edu with
esmtp (Exim 4.89)        (envelope-from <announcements-all-owner@elist.tufts.edu>)
         id 1dzTYp-0001Dv-mC; Tue, 03 Oct 2017 16:12:59 -0400
Received: from pps.filterd (ppagent-prod-08.uit.tufts.edu [127.0.0.1])       by
ppagent-prod-08.uit.tufts.edu (8.16.0.21/8.16.0.21) with SMTP id
v93KADpm014385; Tue, 3 Oct 2017 13:12:59 -0700
Received: from smtpout-prod-03.uit.tufts.edu
(smtpout-prod-03-relay.uit.tufts.edu [130.64.19.53])       by
ppagent-prod-08.uit.tufts.edu with ESMTP id 2da987cv3e-1   (version=TLSv1
cipher=AES256-SHA bits=256 verify=NOT);   Tue, 03 Oct 2017 13:12:59 -0700
Received: from elist-prod-01.uit.tufts.edu ([10.250.166.22]:40203)   by
smtpout-prod-03.uit.tufts.edu with esmtps (TLSv1:AES256-SHA:256)    (Exim 4.76)
         (envelope-from <announcements-all-owner@elist.tufts.edu>)   id
1dzTYl-0002Ei-Kd; Tue, 03 Oct 2017 16:12:55 -0400
Received: from sympa by elist-prod-01.uit.tufts.edu with local (Exim 4.76)
         (envelope-from <announcements-all-owner@elist.tufts.edu>)   id
1dzTYk-0002cl-5e; Tue, 03 Oct 2017 16:12:55 -0400
X-Sympa-To: announcements-all
To: "announcements-all@elist.tufts.edu" <announcements-all@elist.tufts.edu>
Subject: In Response to the Events in Las Vegas
Thread-Topic: In Response to the Events in Las Vegas
Thread-Index: AQHTPIOh0+Cd5nRD50uiFyPlvrj9dg==
Date: Tue, 3 Oct 2017 20:10:17 +0000
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
user-agent: Microsoft-MacOutlook/f.1f.0.170216
x-originating-ip: [10.250.136.18]
Content-Type: multipart/alternative;
         boundary="_000_6C5C7B30CA144626B35D5067BF5CBAE2tuftsedu_"
MIME-Version: 1.0
X-Tufts-Proofpoint-Spam-Reason: elist
X-Validation-by: kaitlin.provencher@tufts.edu
From: <announcements@tufts.edu>
Message-ID: <announcements-all.115@anonymous>
Reply-To: <announcements@tufts.edu>
X-Loop: announcements-all@elist.tufts.edu
X-Sequence: 115
Errors-to: announcements-all-owner@elist.tufts.edu
Precedence: bulk
Sender: <announcements-all-request@elist.tufts.edu>
X-no-archive: yes
List-Id: <announcements-all.elist.tufts.edu>
X-Tufts-Proofpoint-Spam-Reason: elist
Return-Path: announcements-all-owner@elist.tufts.edu
X-MS-Exchange-Organization-AuthSource: tabvmexcashub01.tufts.ad.tufts.edu
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Exchange-Organization-AVStamp-Mailbox: SMEXw]nP;1369500;0;This mail has
been scanned by Trend Micro ScanMail for Microsoft Exchange;
X-MS-Exchange-Organization-SCL: 0


Best Regards,

Jon

Tufts Technology Services (TTS)
169 Holland Street
Somerville, MA 02144
Phone: (617) 627-8855

**Comment by ikedas** [comment]
I got it.  This bug seems fixed on recent version, Sympa 6.2.24 (#105).
Unfortunately, there is no plan to fix it on Sympa 6.1.x.
Could you please consider upgrading Sympa?

**Comment by jonccrice** [comment]
Thank you for the update. This helps clarify the issue we are seeing which is seems to be with large e-lists that are LDAP-based.
In the meantime, is there any reason we can’t manually update the message ID (1st entry in the stats file) so that we can ensure that the message ID is updated?

Best Regards,

Jon

Tufts Technology Services (TTS)
169 Holland Street
Somerville, MA 02144
Phone: (617) 627-8855

**Comment by ikedas** [comment]
@jcdelepine,

> In the meantime, is there any reason we can’t manually update the message ID (1st entry in the stats file) so that we can ensure that the message ID is updated?

Yes, the 1st entry represents the most recent message ID.  You can edit `stats` file to change this entry to be expected number for the last message.

**Comment by ikedas** [comment]
Seems no more discussion. Close.
