### ISSUE TITLE
Conf edition through web interface is broken

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#231]
Hi,

After having a hard time finding how to enable sympa.conf edition through the web interface (copy and edit default/web_tt2/edit_config.tt2), I found out that the table layout is completely broken.
Thus my request has 2 parts:
- Fix table layout when WUI edition is enabled.
- Toggle the feature with a real conf parameter in sympa.conf.

Regards,
Xavier

**Comment by xavierba** [comment]
Another question, I noticed the ```cookie``` is not obfuscated.  Is that expected ?

**Comment by ikedas** [comment]
> Another question, I noticed the `cookie` parameter is not obfuscated. Is that expected ?

This bug was fixed on 6.2.33b.1. cf. https://github.com/sympa-community/sympa/commit/c7d32c71e504aec045217460612a98884cfd7951

**Comment by ikedas** [comment]
edit_config feature was removed once on 6.2.71b.1.  cf. 7bba859

**Comment by ikedas** [comment]
@xavierba , if you think edit_config feature useful, please submit another issue for [Feature Request](https://github.com/sympa-community/sympa/issues/new?assignees=&labels=enhancement&template=feature-request.md).
