### ISSUE TITLE
Feature request: add support for the subscribers.db.dump format in sympa.pl --import

### ISSUE THREAD

**Issue by sivertkh** [sympa-community/sympa#232]
> 09:07:36 <__denis__> hi, there is a simple way to import members from subscribers.db.dump to a list? And preserve name ?

sympa.pl --import does only support data on the form \<address\> \<name\>. It would be nice to be able to import subscribers.db.dump files as well. The code to support this should already exist as sympa imports these files when a list i reactivated.

**Comment by ikedas** [comment]
Hi @sivertkh,

PR above introduces `--suck` option to restore list users from files created by `--dump`.  Do you think it satisfies reported need?

**Comment by sivertkh** [comment]
@ikedas Yes perfect. Thank you!

**Comment by ikedas** [comment]
FIx was merged. Closing.
