### ISSUE TITLE
Reference to missing font

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#242]
6.2.30 on RHEL7 installed via RPM.

I've just updated and getting now getting 404s on GETs to https://**hostname**/static-sympa/external/font-awesome/fonts/fontawesome-webfont.woff?v=4.1.0

The only files in /usr/share/fonts/fontawesome/ are FontAwesome.otf & fontawesome-webfont.ttf

My attempts at finding a reference to the .woff file in the code failed dismally.

Thanks!

**Comment by xavierba** [comment]
where does the rpm comes from ?

**Comment by xavierba** [comment]
Could you please check if the httpd conf is correct ? Check if there are relevant differences between /etc/httpd/conf.d/sympa.conf and /etc/httpd/conf.d/sympa.conf.rpmnew if it does exist.

**Comment by laerm** [comment]
Hello Xavier,

Thanks for your answer. I modified /etc/httpd/conf.d/sympa.conf after the upgrade to add the new aliases:

Alias /static-sympa/external/font-awesome/css /usr/share/font-awesome-web/css
Alias /static-sympa/external/font-awesome/fonts /usr/share/fonts/fontawesome
Alias /static-sympa/css /var/lib/sympa/css
Alias /static-sympa/pictures /var/lib/sympa/pictures

But the error was still present. I cannot be sure the error wasn't showing up on the previous version I was on (6.2.24). Prior to that, we upgraded from an old 5.4.7. Maybe that's when the problem occurred. In any case, if I'm the only one experiencing this issue, I think we can safely assume it's not a widespread problem and it stemmed from earlier.

Sorry for the noise!

**Comment by xavierba** [comment]
Just to make sure, you restarted httpd after upgrading sympa and modifying the httpd conf, right ?

**Comment by laerm** [comment]
I did indeed, no dice. No sign of the fontawesome-webfont.woff file at all on my system. Copying it from the RPM file manually did the trick.

**Comment by xavierba** [comment]
Corrupted fontawesome rpms ? rpm -V fontawesome-fonts fontawesome-fonts-web ?

**Comment by laerm** [comment]
No luck there either, both were installed on my system (prod + test) a while ago. Just the .woff file missing, the FontAwesome.otf and fontawesome-webfont.ttf were in the /usr/share/fonts/fontawesome/

**Comment by xavierba** [comment]
ok, so this is my fault. The fontawesome packages on both EL6 (4.4.0 from EPEL) and EL7 (4.1.0 from RHEL/CentOS) don't include the woff flavor.

**Comment by xavierba** [comment]
Or maybe not. This might be a packaging bug in the fontawesome package from RHEL/CentOS. It doesn't ship the woff flavor, but do reference it in the css.
