### ISSUE TITLE
Kind of inheritance of md5 challenge for a list composed of N sub-lists

### ISSUE THREAD

**Issue by flaf** [sympa-community/sympa#249]
Hi,

I'm using Sympa 6.2.X here and I have a list L which is composed of N sub-lists (list1, list2, ..., listN). **On each sub-list**, a user can send a mail but a challenge by e-mail is required before (with the md5 in the e-mail object):

```
equal([sender],'user@dom.tld')      smtp           -> request_auth
equal([sender],'user@dom.tld')      md5            -> do_it
```

When the user sends an e-mail on the list L, he receives N challenges by e-mail (1 challenge by sub-list) and it's not very handy.

1. First, currently it is not possible to have only one challenge for the all N sub-lists, is it correct? (or did i miss anything in the doc?)
2. If 1. is correct, it could be an interesting feature.

And I have the same porblem with moderation (instead of the md5 challenge) where I would like to avoid the moderation of the same message for each sub-list (ie N moderations for the same message).

Regards.

**Comment by ikedas** [comment]
Hi,
> First, currently it is not possible to have only one challenge for the all N sub-lists, is it correct? (or did i miss anything in the doc?)

You might want to use [data source](https://sympa-community.github.io/manual/customize/data-sources.html) to include one or more lists into a list.

For example, a list name `parent-list` with config including lines
```
include_sympa_list
listname child-list-a
name Child A

include_sympa_list
listname child-list-b
name Child B

include_sympa_list
listname child-list-c
name Child C

```
`parent-list` will automatically include all subscribers of `child-list-a`, `child-list-b` and `child-list-c` as its subscribers.  Then, when a user posts a message to `parent-list`, only the scenario of `parent-list` will be applied, and the message will be sent to all subscribers directly, not going though any child lists.

If you are configuring the lists with web interface, please go to [Edit List Config] - [Data sources setup], and set up [List inclusion] entry.

**Comment by ikedas** [comment]
No more questions seen.  This issue is closed.
