### ISSUE TITLE
Missing Function "action_change_email" on serveradmin.tt2

### ISSUE THREAD

**Issue by CorneliusC** [sympa-community/sympa#25]
Hi,
I’m Cornelius from „Fraunhofer Gesellschaft“ in germany. 
We use sympa 6.2.16 for our +60 institutes with nearly 30.000 employees.

I just tried your newest version and there is also one function in the
serveradmin.tt2 template missing.

We had the old version 6.1.17 running until 2016, there you could
Change „old_email“ to „new_email“.

I added the part manuelly to the file serveradmin.tt2 (Line 70 to 81):
[serveradmin.tt2.txt](https://github.com/sympa-community/sympa/files/1108775/serveradmin.tt2.txt)

This is very important to us, because we have several name-changes through
the year. Also we use strict access by smartcard. So after the rename of one
user it would only be possible to change the e-mail-adresse by hand in the
mysql-database. But the best way is to change it with the template function.

**Comment by agouaux** [comment]
You can still do this on the command line:

`SYMPA_HOME/bin/sympa.pl --change_user_email --current_email=OLD --new_email=NEW
`

But, yes, we too miss the convenience of doing it via the web admin UI.

**Comment by ikedas** [comment]
6.2.19b.1 restores change_email function as "move_user".  Please check it in serveradmin and pref pages, then report if it works sanely.  Thanks.

**Comment by MargoM** [comment]
Version: 6.2.19b.1

In serveradmin.tt2 changing email works.

But not in user preferences. In user preferences there is no "Change email" button.

After changing the code (pref.tt2) I can see the button, I think there is a typo:
value="[% user.email %]
should be
value="[% user.email %]"
no closing bracket (line: 46 https://github.com/sympa-community/sympa/blob/6.2.19b.1/default/web_tt2/pref.tt2).

Changing user's email, Do you really want this action to be taken
I click "Confirm", new error message pops up:

```
Internal Server Error
Sympa encountered an internal error.
Please contact the listmaster.

Error: Missing incoming parameter at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN15> line 1.
Traceback

DIED: Missing incoming parameter at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN15> line 1.
 at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN15> line 1.
	Sympa::Request::Handler::move_user::_twist(Sympa::Spindle::ProcessAuth=HASH(0x6154c70), Sympa::Request <action=move_user;context=mydomain;email=myemail>) called at /home/sympa/bin/Sympa/Spindle.pm line 92
	Sympa::Spindle::spin(Sympa::Spindle::ProcessAuth=HASH(0x6154c70)) called at /home/sympa/bin/Sympa/Request/Handler/auth.pm line 69
	Sympa::Request::Handler::auth::_twist(Sympa::Spindle::ProcessRequest=HASH(0x61d0178), Sympa::Request <action=auth;context=mydomain>) called at /home/sympa/bin/Sympa/Spindle.pm line 92
	Sympa::Spindle::spin(Sympa::Spindle::ProcessRequest=HASH(0x61d0178)) called at /home/sympa/bin/wwsympa.fcgi line 17285
	main::do_auth() called at /home/sympa/bin/wwsympa.fcgi line 1638
```

**Comment by MargoM** [comment]
Version: 6.2.19b.1

In serveradmin.tt2 changing email works.

But not in user preferences. In user preferences there is no "Change email" button.

After changing the code (pref.tt2) I can see the button, I think there is a typo:
value="[% user.email %]
should be
value="[% user.email %]"
no closing bracket (line: 46 https://github.com/sympa-community/sympa/blob/6.2.19b.1/default/web_tt2/pref.tt2).

Changing user's email, Do you really want this action to be taken
I click "Confirm", new error message pops up:

```
Internal Server Error
Sympa encountered an internal error.
Please contact the listmaster.

Error: Missing incoming parameter at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN15> line 1.
Traceback

DIED: Missing incoming parameter at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN15> line 1.
 at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN15> line 1.
	Sympa::Request::Handler::move_user::_twist(Sympa::Spindle::ProcessAuth=HASH(0x6154c70), Sympa::Request <action=move_user;context=mydomain;email=myemail>) called at /home/sympa/bin/Sympa/Spindle.pm line 92
	Sympa::Spindle::spin(Sympa::Spindle::ProcessAuth=HASH(0x6154c70)) called at /home/sympa/bin/Sympa/Request/Handler/auth.pm line 69
	Sympa::Request::Handler::auth::_twist(Sympa::Spindle::ProcessRequest=HASH(0x61d0178), Sympa::Request <action=auth;context=mydomain>) called at /home/sympa/bin/Sympa/Spindle.pm line 92
	Sympa::Spindle::spin(Sympa::Spindle::ProcessRequest=HASH(0x61d0178)) called at /home/sympa/bin/wwsympa.fcgi line 17285
	main::do_auth() called at /home/sympa/bin/wwsympa.fcgi line 1638
```

**Comment by ikedas** [comment]
@MargoM , could you please retry renaming from the beginning, with corrected `pref.tt2`?

**Comment by MargoM** [comment]
My modification in default/web_tt2/pref.tt2

```
- <input type="hidden" name="current_email" value="[% user.email %] />
+ <input type="hidden" name="current_email" value="[% user.email %]" />
```
Diffchecker: https://i.imgur.com/U11nfva.png

**Comment by ikedas** [comment]
Okey then, with modified pref.tt2, could you please retry procedure of operation renaming email?

**Comment by MargoM** [comment]
1. Inserting new email address (My preferences) > Change email
2. Changing user's email > Confirm
3. After clicking validation link, that i received by email (You requested an action 'move_user'.)
4. Changing user's email > Confirm
5. Internal Server Error

```
Internal Server Error
Sympa encountered an internal error.
Please contact the listmaster.

Error: Missing incoming parameter at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN41> line 1.
Traceback

DIED: Missing incoming parameter at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN41> line 1.
 at /home/sympa/bin/Sympa/Request/Handler/move_user.pm line 54, <GEN41> line 1.
	Sympa::Request::Handler::move_user::_twist(Sympa::Spindle::ProcessAuth=HASH(0x6769228), Sympa::Request <action=move_user;context=mydomain.ee;email=myemail@ee>) called at /home/sympa/bin/Sympa/Spindle.pm line 92
	Sympa::Spindle::spin(Sympa::Spindle::ProcessAuth=HASH(0x6769228)) called at /home/sympa/bin/Sympa/Request/Handler/auth.pm line 69
	Sympa::Request::Handler::auth::_twist(Sympa::Spindle::ProcessRequest=HASH(0x65c9d20), Sympa::Request <action=auth;context=mydomain.ee>) called at /home/sympa/bin/Sympa/Spindle.pm line 92
	Sympa::Spindle::spin(Sympa::Spindle::ProcessRequest=HASH(0x65c9d20)) called at /home/sympa/bin/wwsympa.fcgi line 17285
	main::do_auth() called at /home/sympa/bin/wwsympa.fcgi line 1638
```

**Comment by MargoM** [comment]
Now in Sympa 6.2.19b.2 this works fine! Thanks!

**Comment by ikedas** [comment]
@MargoM, Thanks much for confirming. This issue is closed.
