### ISSUE TITLE
Erroneous typing in templates

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#266]
This issue is a collection of following PRs:
  - ~~#254 Use font-awesome icons instead of stock images  (@ikedas)~~ closed
  - ~~#262 Double \<hr\> shown under some conditions (@qosobrin)~~ closed
  - ~~#265 Removed extra periods at the end of these sentences (@qosobrin)~~ closed

**\***: Needs updating translation catalog.

See also: ~~#257~~ closed.

**Comment by qosobrin** [comment]
I added some more changes to pull #265. They include:

- Variable requested but not used
- Added missing spaces between checkboxes and labels
- Added a couple of <br /> to improve readability
- Properties of shared files and folders not showing element name

All of them are minor changes that affect only element display, not software logic, so I considered that they could be grouped in the same pull request. I keep it opened while necessary. @ikedas, please, close it yourself before 6.2.32 release.

Regards.
