### ISSUE TITLE
regression from 6.1: missing admin function to bulk unsubscribe

### ISSUE THREAD

**Issue by agouaux** [sympa-community/sympa#27]
This is related to #25 .  In 6.1, under the Admin tab of the web UI, when you searched for a user it would not only show all the lists that user was on, but on the far right there were buttons to edit or delete the subscription.  This made it really handy to delete all that user's subscriptions after they left the enterprise.  Now, that interface just shows all the lists that user is on, forcing you to visit each list separately and remove that user with much more steps.

There also doesn't appear to be a sympa.pl command option to delete a user from all lists, so unlike with #25, there is no other option to do a mass deletion of a user other than to manually visit each list.

**Comment by mikekuriger** [comment]
Has there been any movement on this issue?

**Comment by ikedas** [comment]
@mikekuriger, as you see, none has contributed anything yet, such as a patch.

**Comment by ldidry** [comment]
I take that one.
