### ISSUE TITLE
Protocol for reporting security related bugs

### ISSUE THREAD

**Issue by mpkut** [sympa-community/sympa#270]
Is there a recommended method for reporting security sensitive items to the development team? I did not see a specifically private method in the contributor information.

**Comment by ikedas** [comment]
Hi @mpkut,

[sympa-security](https://listes.renater.fr/sympa/info/sympa-security) mailing list was launced for security contact about Sympa.  People in change subscribe to it and its archive is private.  Please inform us though this list.

**Comment by mpkut** [comment]
Thank you @ikedas, that mechanism should work fine. Much appreciated!
