### ISSUE TITLE
Cannot subscribe via web to sympa-announce

### ISSUE THREAD

**Issue by hmpf** [sympa-community/sympa#271]
The recent security advisory reminded me that announcement of new versions (and security advisories) needs to be sent to all involved with sympa in my organization, to prevent spof. I attempted to subscribe an alias that sends to all the relevant people, but the web interface at renater replies with AUTHORIZATION REJECT (info). Is this intentional? If so, what is the correct way to subscribe to the announcements?

Which reminds me, the new website needs a page with info about mailing lists and other contact points, I'll open a ticket there also.

**Comment by ikedas** [comment]
There seem no other questions and this issue is closed.
