### ISSUE TITLE
Possible typo in official doc on unsubscribe links

### ISSUE THREAD

**Issue by jjogeva** [sympa-community/sympa#273]
Hi!

Hope this is the correct tracker for current documentation errors. I have spent some time today trying to get an unsubscribe link working on a fresh list on Sympa 6.2.22.

**Current state**
The documentation (https://www.sympa.org/manual/message-handling) states that the following line needs to be added:
To unsubscribe from this list, clink here: [% 'auto_signoff' | url_abs([listname],{email=>user.email}) %]

**The problem**
This ends up creating a url without the list name and user get's:
"ERROR (auto_signoff) - ..."

**The fix**
The correct line should have a "." in "listname"
To unsubscribe from this list, click here: [% 'auto_signoff' | url_abs([list.name],{email=>user.email}) %]

Hope that someone can fix this in the documentation

Edit: Found another typo

**Comment by ikedas** [comment]
Hi @jjogeva ,
I feel `listname` is correct.

**Comment by jjogeva** [comment]
I have to admit that after 2,5 years passed from the initial debug process for the issue it is a bit hard for me to remember the details.
I also do not understand the answer/question/statement. Do you mean that semantically username is more correct? Or has there maybe been an update that fixed this issue?
I was talking about how the system was not working as documented. I am not opposed if this is changed but the documentation should reflect this.

**Comment by ikedas** [comment]
@jjogeva , please show us details, such as file full path name and full content of footer file.

**Comment by ikedas** [comment]
Referred page does no longer exist.  This issue is closed.
