### ISSUE TITLE
Missing path after installation

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#274]
I have just installed sympa 6.2.32 from source code in Debian 9. My configure options were:
```
./configure --enable-fhs --with-confdir=/etc/sympa --with-initdir=/etc/init.d
```
After installation I ran:
```
/home/sympa/sbin/sympa_wizard.pl
/home/sympa/sbin/sympa.pl --health_check
```
When I started sympa service I got the following error:
```
touch: cannot touch '/home/sympa/var/lock/subsys/sympa': No such file or directory
```
I restarted the service several times, but the error always comes up. Then I created the full path:
```
mkdir -p /home/sympa/var/lock/subsys/sympa
```
and the error disappeared after sympa service restart.

This path creation should have happened during installation, or, even better, there should be some logic before sending the touch command that checks and creates (in case it is missing) the path at runtime.

Regards.

**Comment by ikedas** [comment]
Hi @qosobrin,

Currently init script by default assumes CentOS/RHEL.  You may specify `configure` options to setup startup scripts suitable for your environment.  As far as I know, for example:

  - Debian/Ubuntu:
      - Using Systemd:
        `--without-initdir --with-unitsdir=/lib/systemd/system`
      - Using [initscript provided by Debian project](https://salsa.debian.org/sympa-team/sympa/blob/master/debian/sympa.init):
        `--without-initdir`
        and copy initscript above as a file `sympa` into `/etc/init.d` manuallly.

  - FreeBSD:
      - Using [rc script provided by FreeBSD project](https://svnweb.freebsd.org/ports/head/mail/sympa/files/sympa.in):
        `--without-initdir `
        and copy rc script above as a file `sympa` into `/usr/local/etc/rc.d` manuallly.

  - CentOS/RHEL 6 or earlier:
      - Using initscript bundled in Sympa:
        `--with-initdir=/etc/rc.d/init.d --with-lockdir=/var/lock/subsys`
         The directory `/var/lock/subsys` is prepared by system.

  - CentOS/RHEL 7 or later:
      - Using Systemd:
        `--without-initdir --with-unitsdir=/lib/systemd/system`
      - Using initscript bundled in Sympa:
        `--with-initdir=/etc/rc.d/init.d --with-lockdir=/var/lock/subsys`
         The directory `/var/lock/subsys` is prepared by system.

  - Fedora:
      - Using Systemd:
        `--without-initdir --with-unitsdir=/lib/systemd/system`

**Comment by qosobrin** [comment]
Previous versions were working fine with my configure options, so I guess this must be a bug or a problem of any kind.  Even though I did not specify `--with-lockdir=/var/lock/subsys` option, the path for the default value of this configure variable should be created during installation or at runtime to prevent any problems. Don't you agree?

**Comment by racke** [comment]
I agree to that.

**Comment by ikedas** [comment]
@qosobrin,

> Previous versions were working fine with my configure options,

Could you please show evidence?

**Comment by qosobrin** [comment]
@ikedas , for what do you need an evidence? And what kind of evidence?

**Comment by ikedas** [comment]
@qosobrin, please show the versions of Sympa and configure options you used previously and recently.

**Comment by ikedas** [comment]
- `--with-lockdir` was introduced on 4.0b.3, with default as `/var/lock/subsys`:
    sympa-community/historic-sympa@43e7092
  - `--enable-fhs` was introduced on 6.0.6, then the default of `--with-lockdir` with `--enable-fhs` was `${prefix}/var/lock/subsys` (if `--localstatedir` was not specified):
    sympa-community/historic-sympa@bea8423
  - Any versions of Sympa have not created "lockdir" directory during source installation, but this path has been embedded in `sympa` init script bundled in source.

I guess @qosobrin have not specified `--enable-fhs` with previous versions, and specified it at this time.

### Proposal: Let the default of `--with-lockdir` be `/var/lock/subsys` always

This directory was originally prepared for [upstart](http://upstart.ubuntu.com/) which has been adopted by Fedora/RHEL, Debian/Ubuntu etc. (On Systemd, this directory is included in `tmpfiles.d/legacy.conf` for compatibility with legacy systems).

Thus, the default value of this option should not depend on `--prefix` option of each application.

**Comment by qosobrin** [comment]
@ikedas I have been using the same configure options in my test environment for a while. I will install both 6.2.32 and 6.2.30 and will send you logs for configure, make and first run. This will take me a while so, please, do not close the issue.

**Comment by ikedas** [comment]
@qosobrin, thanks. This issue will not be closed before your problem will be solved.

**Comment by ikedas** [comment]
Hi @qosobrin, how is it going about your trial?

**Comment by ikedas** [comment]
Stagnating issue.  Closed.
