### ISSUE TITLE
Please wait.... infinite spinner

### ISSUE THREAD

**Issue by micah** [sympa-community/sympa#279]
We attempted to upgrade to 6.2.32, and put aside our web_tt2 template customization to see if we could use the newly updated templates and modify them to our needs.

Everything was migrated fine and then I logged into the web interface. I got a spinner with the text "Please wait..." -- it never ended. I tried to debug what it was waiting for, but I could not determine it. 

The spinner seems to come when class='heavyWork' in the tt2 files occurs, but I could not tell what was not completing the task.

**Comment by ikedas** [comment]
Hi @micah,
What page was supposed to be displayed when you logged in? (Initially it is `home` page. It may be changed by `default_home` parameter)

**Comment by micah** [comment]
IKEDA Soji <notifications@github.com> writes:

> Hi @micah,
> What page was supposed to be displayed when you logged in? (Initially it is `home` page. It may be changed by `default_home` parameter)

It was the `home` page, but this was happening on other pages as well.

**Comment by ikedas** [comment]
@micah, i want to confirm:
  - Did you show home page and then perform log in?
  - Didn't you click "Back" button of web browser?

**Comment by micah** [comment]
IKEDA Soji <notifications@github.com> writes:

>   - Did you show home page and then perform log in?


I think it was after logged in, as it seemed like it was some fetching
of some user data (list action, latest topics, or something).

>   - Didn't you click "Back" button of web browser?

no, also this was happening on every page.

What I want is some way to debug it... its possible it was something
with our setup or templates. But I couldn't figure out where it was
coming from, and I didn't see anything in the logs that was pointing to
it.

**Comment by ikedas** [comment]
@micah, I can't figure out what is shown on your display, but I may give some suggestions.
  1. Please read [Upgrading notes](https://sympa-community.github.io/manual/upgrade/notes.html), if you have not.
  2. Cancel all modifications (except those made by `sympa.pl --upgrade`) and see if your Sympa works correctly.
  3. Then, modify configurations gradually, and  by each modification, check if Sympa works correctly.
  4. If Sympa got not working, please show us:
      - The change you made
      - Configuration of Sympa (`sympa.conf` and files related to your change)
      - What you see: For example screen shot
      - What system records: System log.

**Comment by ikedas** [comment]
Stagnating issue. Closed at present.

**Comment by crpeck** [comment]
I just did a clean install of 6.2.42 with no changes to any of the tt2 files and I am seeing the same thing, on every page.

**Comment by racke** [comment]
Can you tell us which browser you use and which version? Please also check it with other browsers.

**Comment by crpeck** [comment]
This is happening on the following browsers & OS's:
Linux Ubuntu 19.04
Google Chrome 73.0.3683.86
Mozilla Firefox 66.0.1

Mac OSX
Google Chrome 73.0.3683.86 -firefox
Mozilla Firefox 66.0.2
Safari 12.0.3

**Comment by lolaslade** [comment]
Seeing the same issue

**Comment by derOtto** [comment]
Having the same issue.
The div with id _loading_ is always shown but will never be hidden.

So I added a simple function to sympa.js, hiding the div when all resources were loaded:

```diff
diff --git a/ORIG_STATICDIR/js/sympa.js b/UPDATED_STATICDIR/js/sympa.js
index eb2d179..68bd9c4 100644
--- a/ORIG_STATICDIR/js/sympa.js
+++ b/UPDATED_STATICDIR/js/sympa.js
@@ -208,6 +208,11 @@ $(function() {
                $('#loading').show();
        });
 });
+// and hide when all resources (with external) are loaded
+$(window).load(function() {
+       $('#loading').hide();
+});
+

 // fade effect for notification boxes
 $(function() {
``` (git diff between [sympa.js](https://github.com/sympa-community/sympa/blob/6.2.40/www/js/sympa.js) and updated version)

Although I didn't tested this on multiple Browsers or OSs (only Chromium on Linux) it may help others or is something fixing this bug.
You still have to check whether this is a possible solution and if this is the right thing to wait for. _I just get this from [here](https://stackoverflow.com/a/32867110)._

**Comment by racke** [comment]
@derOtto Can you please add your browser version?

**Comment by derOtto** [comment]
@racke I updated my answer providing the requested information.
https://github.com/sympa-community/sympa/issues/279#issuecomment-650825780

**Comment by ikedas** [comment]
@derOtto, does this work?
``` diff
diff --git a/www/js/sympa.js b/www/js/sympa.js
index 3ff5557..c285220 100644
--- a/www/js/sympa.js
+++ b/www/js/sympa.js
@@ -208,6 +208,9 @@ $(function() {
        $('.heavyWork').on('click', function(){
                $('#loading').show();
        });
+
+       // and hide it.
+       $('#loading').hide();
 });

 // fade effect for notification boxes
```
I'm not sure because I couldn't reproduce reported behavior.

**Comment by derOtto** [comment]
@ikedas: it also disappears, but as with the original file, some sites are not probably loaded (for example lists) with the original or the suggestion from you.
With hiding it, when page is fully loaded (my sulution), all content shows up.

I temporary deployed two endpoints, serving all the suggestions. They are all the same only differing in nginx serving the different sympa.js':
- http://old.lists.jc-otto.de/ (original, non modified sympa.js)
- http://652125440.lists.jc-otto.de (@ikedas suggestion)
- https://lists.jc-otto.de (my modification)

**Comment by ikedas** [comment]
@derOtto , your Sympa is not configured properly:

![](https://user-images.githubusercontent.com/5743546/86258935-5a539f00-bbf6-11ea-8a38-a53274ffc721.png)

With your configuration, style sheet added by Sympa is completely omitted.  If it is properly configured, it will be shown as [this page](https://listes.renater.fr/sympa/) and proposed fixes may not be needed:

![](https://user-images.githubusercontent.com/5743546/86259525-157c3800-bbf7-11ea-95f8-378277ffa640.png)

Please check your configuration.  If you want help about configuration, please submit another issue.

**Comment by derOtto** [comment]
> With your configuration, style sheet added by Sympa is completely omitted. If it is properly configured, it will be shown as [this page](https://listes.renater.fr/sympa/) and proposed fixes may not be needed

That was the right clue, leading me to [this thread](https://listes.renater.fr/sympa/arc/sympa-users/2018-04/msg00002.html).
After that I could find the right directories in the apache conf (/etc/apache2/conf-available/sympa.conf) and only there. There is no conf or snippet in in the nginx directory and no hint in the [gpldoc](https://github.com/sympa-community/gpldoc).

- So the /css-sympa is in the old /var/lib/sympa/css where the old static_content (/var/lib/sympa/static_content) was( before upgrade).
- /static-sympa moved to /usr/share/sympa/static_content
- /pictures-sympa is only in /var/lib/sympa/pictures but dir is empty (only empty index.html file, like old static_content).

It was quite confusing that there was no error or warning, css was missing.

So for me this issue is fixed, but I don't know about @micah.

Unfortunately in the [repo](https://github.com/sympa-community/gpldoc) issues are deactivated but maybe you (the sympa authors) could make a todo about adding this information to the http-server and directory layout parts. --thx

**Comment by ikedas** [comment]
@derOttto, when you upgrade earlier version of Sympa, you'd be better to read [Upgrading note](https://sympa-community.github.io/manual/upgrade/notes.html) in documentation.

There are several changes on paths for CSS and so on, as of [version 6.2.28](https://sympa-community.github.io/manual/upgrade/notes.html#from-versions-prior-to-6228).

**Comment by ikedas** [comment]
This issue is closed at present.
Though what @micah reported might not be the same as what @derOtto wrote.

**Comment by ikedas** [comment]
@michaellaunay , sympa_wizard will never generate style.css.
About problems on Debian packages, please ask the Debian team.
