### ISSUE TITLE
Internal server error in WebUI when email has removed from list

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#28]
`/editsubscriber/test-newsletter/foo.bar%40example.com/review`

This link shows "Internal server error" and also spams the listmaster with an email instead of saying "User not found" or something like that.

Sympa version: 6.2.16

**Comment by ikedas** [comment]
@racke, I hope reported bug has been fixed.

**Comment by racke** [comment]
Excellent, thanks @ikedas.

**Comment by racke** [comment]
Done.
