### ISSUE TITLE
Upgrading 6.2.16 -> 6.2.32 error about pictures_dir not found

### ISSUE THREAD

**Issue by ErikDOlson** [sympa-community/sympa#280]
[root@pulcher bin]# ./sympa.pl --upgrade
    notice main:: Sympa 6.2.32 Started
    Use of uninitialized value $pictures_dir in -d at /home/sympa/bin/Conf.pm line 857.
    Use of uninitialized value $pictures_dir in mkdir at /home/sympa/bin/Conf.pm line 858.
    err main::#277 > Conf::checkfiles#859 Unable to create directory
    Missing files.

Racke says: "The default should work as well, please file a bug at Github. At least --upgrade should tell you that the setting is missing."

**Comment by racke** [comment]
Yeah, but shouldn't we have a sane default?

**Comment by ikedas** [comment]
As I don’t know what occurred, asked for confirm notes at first.

**Comment by ErikDOlson** [comment]
I think Racke is correct.  The upgrade notes say "you MIGHT want to 
specify..." on both pictures_path and pictures_url.  I did not get an 
error for not specifying pictures_url, but I *did* get an error for not 
specifying pictures_path.  So yes, one has a "sane default", while the 
other does not.

-- 
Erik D. Olson
erik@thekrib.com

**Comment by ikedas** [comment]
@ErikDOlson, could you show us:
  - content of sympa.conf, and corresponding robot.conf if any
  - content of $MOD

**Comment by ErikDOlson** [comment]
sympa.conf enclosed includes the pictures_path line that I added to make it work.

[Constants.zip](https://github.com/sympa-community/sympa/files/1944972/Constants.zip)

**Comment by ikedas** [comment]
@ErikDOlson,

I see you have used default value for `static_content_path` on your installation.

If possible, could you try followng operation and check if error will disappear?
  1. Remove `pictures_path` line you added.
  2. Remove a file `sympa.conf.bin` which is placed in the same directory as `sympa.conf`.
  3. Restart web interface (See "Forced reloading" in [Reloading WWSympa](https://sympa-community.github.io/manual/admin/services.html#reloading-wwsympa)).

**Comment by ikedas** [comment]
Perhaps [this patch](https://github.com/ikedas/sympa/commit/7495a21.patch) may fix problem.  It is the least subset of PR#284 above.

**Comment by ikedas** [comment]
Related fix was merged. This issue is closed.
Thanks for valuable report!
