### ISSUE TITLE
error list for all the mailing list

### ISSUE THREAD

**Issue by PhilLAL** [sympa-community/sympa#281]
Hello,
after importing a whole mailing list system from google to sympa, we got a lot of errors in our mailing lists since a lot of mails are in error.
We would like to identify theses mail and correct these errors for all the mailing lists. Is there a way to do this? 
The errors seems to be visible in each mailing list but I did not suceed to list errors in one list for all the sympa mailing list. :(
Thank you

**Comment by ikedas** [comment]
Unfortunately, none seems having particular answers.  This issue is closed at present.

**Comment by PhilLAL** [comment]
Hello,
to be clear, my question was a request to get a way to display the errors for all the list of a sympa server (for use by global administrator), instead of force administrator to get into each list to display errors.
It would be much more convenient when a server manage several dozens of lists.
