### ISSUE TITLE
crawlers_detection.conf update?

### ISSUE THREAD

**Issue by taggart** [sympa-community/sympa#286]
Where does default/crawlers_detection.conf comes from? It looks like maybe it hasn't been updated in a while. I ran into a crawler today that it didn't know about, but maybe it's already included in wherever this file comes from?

**Comment by ikedas** [comment]
As we can see at the firlst line of this file, it was taken from useragentstring.com in 2007, and have not been updated. I think, if we have to update it, we may have to find another well-maintained source.

**Comment by ikedas** [comment]
Possible alternative to useragentstring.com:

  * [WhatIsMyBrowser.com > User Agents > Explore > Software Type > Crawler](https://developers.whatismybrowser.com/useragents/explore/software_type_specific/crawler/)
    ([Legal](https://developers.whatismybrowser.com/api/about/legal/))

**Comment by ikedas** [comment]
* [Browser Capabilities Project](http://browscap.org/) ([MIT LIcense](https://github.com/browscap/browscap/blob/6.0.x/LICENSE))

**Comment by taggart** [comment]
I came upon this old issue today, is this still relevant? The header on the file in 6.2.66 still says 2007.
This only helps with "well behaved" crawlers, but I think that's still good.

**Comment by ikedas** [comment]
> is this still relevant? 
Yes.  We are waiting for any improvements to be contributed.

**Comment by taggart** [comment]
* The whatismybrowser.com legal document listed above says:

> You may use this database of user agents and parse results however you want - EXCEPT for making it publicly available on the internet, either as a downloadable/sharable file or through a user agent listing.

so I think that rules out including that one.

* The udger.com [license](https://udger.com/legal/data_licence) seems to exclude using that one.

* The browscap one seems good. The produced browscap.ini file has records like the following:

```
[360Spider]
Parent=DefaultProperties
Comment=360Spider
Browser=360Spider
Browser_Maker=Qihoo 360 Technology Co. Ltd.
Platform=Win32
Crawler=true
Device_Type=Desktop
Device_Pointing_Method=mouse
```
So looking for the `Crawler=true` one is a start, but also there are records like this:

```
[GrapeshotCrawler]
Parent=DefaultProperties
Comment=GrapeshotCrawler
Browser=GrapeshotCrawler
Browser_Maker=Grapeshot Limited
Crawler=true

[Mozilla/5.0 (compatible; GrapeshotCrawler/2.0; +http://www.grapeshot.co.uk/crawler.php)]
Parent=GrapeshotCrawler
Version=2.0
MajorVer=2
```

where you'd need to go to the parent to figure it out.

I think a couple things are probably possible.

1.  Have a script that takes browscap.ini as input and outputs crawlers_detection.conf. This could be done at sympa build time, periodically and the result checked into git, and/or on the installed system if you wanted to update.
2.  Use the browscap git repo to produce crawlers_detection.conf directly. Might be easier, but would require you had it checked out somewhere.

**Comment by ikedas** [comment]
See also:
- [HTTP::Browscap](https://metacpan.org/release/GWYN/HTTP-Browscap-0.06/view/Browscap.pm) - Module using browscap.ini (with caching feature)

- [HTTP::BrowserDetect](https://metacpan.org/dist/HTTP-BrowserDetect) - Module using hardcoded rules to detect "robots"

**Comment by ikedas** [comment]
Additional works found on GitHub:
- [monperrus/crawler-user-agents](/monperrus/crawler-user-agents)
- [JayBizzle/Crawler-Detect](/JayBizzle/Crawler-Detect)
- [mimmi20/BrowserDetector](/mimmi20/BrowserDetector)

They look not having Perl interfaces.
