### ISSUE TITLE
First time listmaster tries to edit template: AUTHORIZATION REJECT

### ISSUE THREAD

**Issue by GeoffMaciolek** [sympa-community/sympa#288]
I've tried this a few times on the same system, creating new lists (on a virtual host), and having the same issue every time.

## Steps To Reproduce

* Create a fresh server with virtual hosts (not certain if either of these are required!)
* Create listmaster account & log in
* Create a new list
* Attempt to edit template
> At this point you'll receive: "AUTHORIZATION REJECT (editfile) Rights to this action are 'hidden' for a 'user'."
> 
> with this log entry in `sympa.log`:
> ```
> May  8 21:23:06 mlist1 wwsympa[3975]: info main::do_editfile(message_templates) [robot list.domainREDACTED.org] [session 02xxxxxxxxxx24] [client RED.ACT.ED.143] [user myEMAILaddr@gmail.com] [list testpublic]
> May  8 21:23:06 mlist1 wwsympa[3975]: info main::do_editfile(message_templates) [robot list.domainREDACTED.org] [session 02xxxxxxxxxx24] [client RED.ACT.ED.143] [user myEMAILaddr@gmail.com] [list testpublic]
> May  8 21:23:08 mlist1 wwsympa[3972]: info main::do_editfile(message.footer) [robot list.domainREDACTED.org] [session 02xxxxxxxxxx24] [client RED.ACT.ED.143] [user myEMAILaddr@gmail.com] [list testpublic]
> May  8 21:23:08 mlist1 wwsympa[3972]: info main::do_editfile(message.footer) [robot list.domainREDACTED.org] [session 02xxxxxxxxxx24] [client RED.ACT.ED.143] [user myEMAILaddr@gmail.com] [list testpublic]
> May  8 21:23:08 mlist1 wwsympa[3972]: err main::#1573 > main::do_editfile#8095 [robot list.domainREDACTED.org] [session 02xxxxxxxxxx24] [client RED.ACT.ED.143] [user myEMAILaddr@gmail.com] [list testpublic] Not allowed
> May  8 21:23:08 mlist1 wwsympa[3972]: err main::#1573 > main::do_editfile#8095 [robot list.domainREDACTED.org] [session 02xxxxxxxxxx24] [client RED.ACT.ED.143] [user myEMAILaddr@gmail.com] [list testpublic] Not allowed
>  ```
* Return to edit any template file, and it will will work as expected.

## Software / Environment

* Version: Sympa 6.2.32
* OS: CentOS 7 (Current updates as of 2018-05-08)
* Installation source: `Sympa-JA.org` repository
* Web Server: nginx 1.2.12-2.el7
* DB Server: mariadb 5.5.56-2.el7
* Web Client: Chromium

**Comment by GeoffMaciolek** [comment]
@ikedas It's not an "actual" permissions error, though, because after the first attempt to edit the file (causing an error), I can edit the file normally.  So, while this may be "consistent" behavior, it's certainly **unexpected** behavior. Trying to edit a file and getting a permission error doesn't automatically lead to "I should try it again."  It's a usable workaround, but it seems something is broken.

Maybe this has to do with the old admin caching issue, #7? (I don't know much about Sympa internals, unfortunately).

**Comment by ikedas** [comment]
@GeoffMaciolek,

I see. Sympa shows file content at first, and then denies saving changes if it is not allowed by configuration (`edit_list.conf`).  Such behavior is inconsistent and it should be fixed.

**Comment by ikedas** [comment]
No additional infomration. Cloase at present.
