### ISSUE TITLE
DMARC protection - From address broken syntax

### ISSUE THREAD

**Issue by mirceab-simmons** [sympa-community/sympa#289]
Sympa 6.2.16 bundled with Debian 9, although the current source 

Setting DKIM protection (dmarc_reject,dmarc_quarantine) and dmarc_protection_phrase to 'name_and_email' generates a new From address something like:
"First Last" (original@example.com) <list@domain.tld>

This From address somehow gets changed by the MTAs to drop the original@example.com part. The resulting From address looks like:
"First Last" <list@domain.tld>

My solution would to fix the addrencode function in lib/Sympa/Tools/Text.pm so that the double quotes are put not just around '$phrase' but around '$phrase ($comment)'.

Besides the call from lib/Sympa/Message.pm (DKIM protection related), it looks like the addrencode function is only used in three other places, twice in lib/Sympa/Message/Template.pm and once in cgi/wwsympa.fcgi, but these calls never have the 4th argument ("comment"), so this bug is specific to DKIM protection.

**Comment by ikedas** [comment]
Let’s continue on #623. Close.
