### ISSUE TITLE
search and admin table

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#294]
When I start a search of a list, sympa seems to reconstruct the admin table : I see a lot of request in sympa.log related to the owners (owner_include) for all the lists.

As we have a lot of lists, it take a lot of time and the server send an error message:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

When I try again, I have the same behaviour.

**Comment by ikedas** [comment]
Hi @pascalmaes,
- What version of Sympa do you using?
- If you upgraded Sympa recently, have you done upgrade process succsessfully, e.g. running `sympa.pl --upgrade`? (See also [manual](https://sympa-community.github.io/manual/upgrade.html))
- What is shown in sympa log?
- How about configuration (`sympa.conf`/`robot.conf` and sample of list `config`)?

**Comment by pascalmaes** [comment]
I encoutered the problem with version 6.2.32 and I have upgraded to 6.2.33b1 as I read that the admin was now in the DB but there is no change.

For each upgrade I run the sympa.pl --upgrade

Extract of sympa.log:

`May 15 00:20:08 sympa-1.sipr.ucl.ac.be task_manager[27470]: info Sympa::List::_include_users_remote_file() 0 included users from remote file ...
May 15 00:20:08 sympa-1.sipr.ucl.ac.be task_manager[27470]: info Sympa::List::_include_users_remote_file() 2 included users from remote file ...
May 15 00:20:08 sympa-1.sipr.ucl.ac.be task_manager[27470]: info Sympa::List::_include_users_remote_file() 1 included users from remote file ...`


We have 3857 lists and there are 3 request/list to get all the owners.


No changes in the configuration files between the different versions of sympa

To reproduce the behaviour, goto https://sympa-1.sipr.ucl.ac.be/institution and make a search for a list on "personnel" for example (no need to be identified).

**Comment by ikedas** [comment]
I reproduced behavior.  Approximately 400 seconds after I hit "Search lists", "Internal server error" occurred.

@pascalmaes, can you check behavior of Sympa as below?
1. Get modification timestamps of files `.last_sync.admin` in all list directories:
   ``` bash
   ls -l EXPLDIR/*/.last_sync.admin EXPLDIR/*/*/.last_sync.admin
   ```
2. Do search lists.

3. check modification timestamps of files `.sync_include.admin` in all list directories:
   ``` bash
   ls -l EXPLDIR/*/.last_sync.admin EXPLDIR/*/*/.last_sync.admin
   ```
Note that replace `EXPLDIR` with the [path suitable for your environment](https://sympa-community.github.io/manual/layout.html#expldir).

Then compare result of 1 and 3:
- Are there newly created `.sync_include.admin` files?
- Are there `.sync_include.admin` files updated timestamp? and files _not_ updated timestamp?

**Comment by pascalmaes** [comment]
During my ls -l, I find directories with lock files like include_admin_user.lock

I have deleted all theses files and now its working fine.

The timestamp of the .last_sync.admin and .last_chane.admin are changed when I launch sympa.
Since I have deleted the lock files, the process of updating admin is not started at each search lists.

**Comment by ikedas** [comment]
I don't know why `include_admin_user,lock` was kept (usually it is created and removed automatically when each syncronization is started and finished).

Could you please watch your Sympa a few days, and report if you encountered block of search again? (If the problem will not occur again, I will close this issue for the time.)

**Comment by ikedas** [comment]
There seems no problem anymore.  This issue is closed.  Thanks for reporting your experience!
