### ISSUE TITLE
Prevent the use of the list address as owner or moderator

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#297]
We got the case where the list was moderated for everyone and the owner was the list address, causing a mail loop.

I think this should not happen.

Seen on 6.2.16.

**Comment by ikedas** [comment]
cf. #345.  This seems fixed on 6.2.17.

**Comment by sivertkh** [comment]
Looks like this is still a problem on 6.2.32.

Moderated list. One of the administrators used the "Changing your email address" feature to changed there email to a list address.
When an email was delivered to the list, a moderation email was sent back to the list starting a moderatron loop.

**Comment by ikedas** [comment]
@sivertkh, I understand. #345 doesn't deal with list address.

Are there any use cases to add list address as a moderator (or owner, if moderators are not defined)?

**Comment by ikedas** [comment]
Hi folks,

Ok, there seem no use cases to add list address as a moderator/owner.

Please check PR above.

**Comment by ldidry** [comment]
Seems good to me.

**Comment by ikedas** [comment]
Merged.  Thanks for reporting bug!
Closing.

**Comment by ldidry** [comment]
Patched and tested, works well :+1: 

Thank you.
