### ISSUE TITLE
Prevent being privileged AND unprivileged owner of a list

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#298]
On 6.2.16, you can put the same address as privileged and unprivileged owner. This result to being unprivileged owner, and if you're the only privileged owner, you're screwed unless you ask the listmaster to modify your settings.

I think it should not happen, you should not be able to put the same address for privileged and unprivileged owner, or a least, you should be considered as privileged owner.

Seen on 6.2.16.

**Comment by ikedas** [comment]
Hi @ldidry,

Duplicate emails might not be set as owners/editors (See PR #13 for details of change).  Consequently, both privileged and normal owners with the same email could not coexist.
This fix was incorporated in 6.2.17b.1.

**Comment by ldidry** [comment]
Ok, so it's already solved.

Thanks :+1:
