### ISSUE TITLE
Feature request: archive mails without attachments ability

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#303]
On 6.2.16, attachments are stored in the archives.

Our archives are fastly and constantly growing. We would beneficiate from an option that makes archives not storing the attachments.

As I saw, the archives contains the original mail, containing the attachments in base64, and the extracted attachments. That make the attachments weight a lot on the disk.

**Comment by ikedas** [comment]
See following post not to extract "attachments":
- "[Re: Disabling attachments](https://www.mhonarc.org/archive/html/mhonarc-users/2005-06/msg00003.html)" by Earl Hood, in mhonarc-users list. 2005-06-02.

**Comment by ldidry** [comment]
Ok, I think I figured it out.

I need to override `default/mhonarc-ressources.tt2` and set [`MIMEINCS`](https://www.mhonarc.org/MHonArc/doc/resources/mimeincs.html) or [`MIMEEXCS`](https://www.mhonarc.org/MHonArc/doc/resources/mimeexcs.html) in it.

Is that it?

**Comment by ldidry** [comment]
If yes, I'll close this issue and create one in https://github.com/sympa-community/sympa-community.github.io

**Comment by ldidry** [comment]
Issue opened: https://github.com/sympa-community/sympa-community.github.io/issues/19

Closing.
