### ISSUE TITLE
fail to send notification of Too large message because envelope_sender is empty

### ISSUE THREAD

**Issue by diegogmanzanares** [sympa-community/sympa#311]
Hi,
I testing sympa to migrate our actual mailling system. When I check the notification for Too large message send to one list, I dont receive the notification. The envelope_sender is empty and the postfix server reject the mail with empty from attribute.
I modify the configuration of postfix to send this message with empty from, but I think that sympa server have send this message with the envelope_sender compelete with a email address.

Thanks.

I attach the logs.

**sympa.log**
May 18 13:46:39 sympa-server sympa_msg[1524]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <pruebas@listas.pruebas.ccoo.es.1526643999.1524,8185>; **envelope_sender=<>**; message_id=sympa.1526643999.1524.205@listas.pruebas.ccoo.es; recipients=dgomez@ccoo.es; sender=gestor_listas-request@listas.pruebas.ccoo.es; template=delivery_status_notification; action=failed; status=5.2.3

**maillog**
**May 18 13:46:40 sympa-server postfix/pickup[1439]: F3C82C0321: uid=996 from=<>**
May 18 13:46:40 sympa-server postfix/cleanup[1585]: F3C82C0321: message-id=<sympa.1526643999.1524.205@listas.pruebas.ccoo.es>
May 18 13:46:40 sympa-server postfix/qmgr[1440]: F3C82C0321: from=<>, size=6554, nrcpt=1 (queue active)
**May 18 13:46:40 sympa-server postfix/smtp[1629]: F3C82C0321: to=<dgomez@ccoo.es>, relay=xxxxxx.ccoo.es[ip_relay_smtp]:25, delay=0.33, delays=0.27/0.02/0.01/0.03, dsn=5.7.1, status=bounced (host xxxxxx..ccoo.es[ip_relay_smtp] said: 554 5.7.1 <>: Sender address rejected: Access denied (in reply to RCPT TO command))**
May 18 13:46:40 sympa-server postfix/qmgr[1440]: F3C82C0321: removed

**Comment by ikedas** [comment]
Hi @diegogmanzanares,

That message is Delivery Status Notification (DSN) which is sent with null envelope_sender ([RFC5321, 4.5.5](https://tools.ietf.org/html/rfc5321#section-4.5.5)).

Log indicates that Postfix on your server (sympa-server) handled DSN correctly and tried to relay it to the other server (xxxxxx.ccoo.es), however destination server denied.  If it matters, please contact administrator of destination server.

**Comment by ikedas** [comment]
There seem no more answers. Close.
