### ISSUE TITLE
Don't show Autocrypt headers in web archive

### ISSUE THREAD

**Issue by KwadroNaut** [sympa-community/sympa#316]
I noticed while reading a mailing list archive online that autocrypt headers were displayed alongside from/to/date/… [1]. I find it confusing, a typical MUA displays date, from, to, subject and that´s about it. Would it be possible to not display those headers (example):
```
Openpgp: preference=signencrypt
Autocrypt: addr=a@example.net; keydata= xsFNBFLqOAABEADYvRtw4FU3xbQbZ+PzyxY8aMTO90baFHjFtm6hknSvWhh6hRHKYzE6tLRC lMG/ba/cIu0oumYfNnlS9QHnX5qCT9Tsq2qs….
```
More information about this project and headers can be read here: https://autocrypt.org/

[1] example: https://lists.riseup.net/www/arc/linguine/2018-05/msg00004.html

**Comment by ikedas** [comment]
Hi @KwadroNaut,

Settings of archives are defined in `mhonarc-ressources.tt2` file.  This file is extracted and used as MHonArc resource file.

To hide additional header fields, you can define a recoource variable [EXCS](https://www.mhonarc.org/MHonArc/doc/resources/excs.html) in the file above.

**Comment by ikedas** [comment]
Please check PR above.
