### ISSUE TITLE
Feature: add a "report abuse" button on lists info page

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#323]
- [x] create a template that will be included into lists info page
- [x] the template will simply be a mailto link to listmaster with subject "Sympa abuse report: list_name" (something like that)

**Comment by ikedas** [comment]
Hi @ldidry,

Could you please describe motivation?

**Comment by ldidry** [comment]
Some people have been subscribed without consent to some mailing lists.

I could have enforced the consent mail for subscribing, but it can be annoying when you migrate a list from google groups/yahoo ML to our server, in which case subscribing people without their consent is quite OK, to not bother them with the "please click here/send email to confirm", since they already say they're ok when they subscribed to the previous ML.

But sometimes, you may be subscribed to some new list, and you don't know why. As an example: I may have send a mail to a company/association to ask for details about a product/whatever. Then someone decides to create a ML, and subscribes all people that showed some interest once. In that case, it's kind of an abuse. As a listmaster, I want people to be able to warn me about that, so I know I should watch the owner's list behavior and tell him/her that he/she is doing something wrong (and ban him/her if he/she continues).

**Comment by ikedas** [comment]
@ldidry,

I understand.  You need a mailto link to report unsolicited addition without opt-in consent.

Following markup may insert such link (sorry, I haven't confirmed carefully).
``` code
[% | mailto("${conf.listmaster_email}@${domain}",{subject=>"Sympa abuse report: ${list.name}"}) %]Report abuse[%END%]
```

Do you think it should be included in the template shipped in source distribution? (I personally think it may be descibed in documentation, in a chapter such as "Tips on template customizaton").

**Comment by ldidry** [comment]
Well, I operated a few services (image or file hosting per ex.) without those kind of buttons, and people ask for the button.

Providing such buttons heavily helps fighting harassment or simply bad behavior.

I think it should be shipped it in Sympa and as an option in sympa.conf, disabled by default: it would be easier for the admins to switch on the button than to read the doc and customize Sympa. They may not even think of using the customization for that.
Fun fact: @dverdin talk earlier on sympa-fr about the old grey interface. It was kind of ugly, and it stays like it 5 years because coders thought that admins would customize the interface, but most of them did not customize things. That says a lot about how much admins have time to customize Sympa.

I suggest to disable the option by default because there is situations where it shouldn't be used, like in universities' Sympa installations (where unsollicited and unneeded subscriptions should not happen, and where universities should have a way to report such things anyway).

I suggest a separate template (ie not code the button directly into list info template) to include in list info template to allow easier modification (I consider that big templates are a plague to read).

Per customization example, at Framasoft, we will change the mailto link to a link to our contact page, but a default mailto button will be a good default for a lot of people.

**Comment by ikedas** [comment]
> Fun fact: @dverdin talk earlier on sympa-fr about the old grey interface. It was kind of ugly, and it stays like it 5 years because coders thought that admins would customize the interface, but most of them did not customize things. That says a lot about how much admins have time to customize Sympa.

Makes sense.  Recently it is pain for administrators to take over customizaton on templates.
When anyone submits a PR, I'll merge it.
