### ISSUE TITLE
DSGVO compliant approval Documentation

### ISSUE THREAD

**Issue by HS10** [sympa-community/sympa#329]
Hello, after DSGVO got active on 25.05, I want to ask how the approvals by double opt in are documented inside sympa Database, how distinction is done between manually added adresses and if the Documentation is compliant to DSGVO Documentation Requirements.
Thank you

**Comment by HS10** [comment]
Hello. Can anyone help me with this Question?
I have found now the table "one_time_ticket_table" inside My Database.
Are there all one_time_tickets with Status saved? Are These entries deleted somewhen?
Does a IP-Address inside Stauts mean thhat it is apporved?

**Comment by ikedas** [comment]
No response.  This issue will be closed for the present.  Please feel free to re-open it if you prefer.
