### ISSUE TITLE
sympa.js bundles part of MochiKit

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#334]
sympa.js is bundling part of MochiKit.
See https://github.com/sympa-community/sympa/blob/4c2a7527bd8d44caacbfe4cab0ef908df789d09c/www/js/sympa.js#L264 and below.
I think this should at least be separated to its own file or possibly be removed and the current version of MochiKit, in whole or in part, be used instead. I have not researched which version sympa.js is bundling, but here's a link to the file containing the 2 functions in the latest MochiKit stable version: https://github.com/mochi/mochikit/blob/MochiKit-1.4.2/MochiKit/Color.js

**Comment by ikedas** [comment]
We probably may replace the code with external color picker plugins. Some examples:
- [Spectrum](https://github.com/bgrins/spectrum)
    - highly customizable
    - `input[type=color]` polyfill
    - i18n'ed
- [tinyColorPicker](https://github.com/PitPik/tinyColorPicker)
    - small
- [Bootstrap Colorpicker](https://github.com/farbelous/bootstrap-colorpicker)
    - customizable

**Comment by xavierba** [comment]
Replacing the 2 functions from MochiKit with something else is probably a good idea, but in the meanwhile, would extracting this to its own file be feasible ? Or possibly import Color.js from the link above ? This may help with the later code replacement.

**Comment by xavierba** [comment]
Just a note, the following files are used by the color picker and could be removed if it is replaced by something else:
www/icons/crosshairs.png
www/icons/h.png
www/icons/position.png
www/icons/sv.png

**Comment by ikedas** [comment]
I mean at least [this range of lines](https://github.com/sympa-community/sympa/blob/4c2a7527bd8d44caacbfe4cab0ef908df789d09c/www/js/sympa.js#L100-L508) can be replaced by an external plugin. Besides,

- It is possible to move two functions into a separate file. However, I feel a bit uncomfortable  to put it together with other external js components.
- btw, Color.js depends on a few other js files included in MochiKit, and importing it also requires them.

**Comment by ikedas** [comment]
In PR above I chose jQuery MiniColors, because some major distributions (Debian and derivativbes) provide package.

**Comment by ikedas** [comment]
PR was merged. Closing.
