### ISSUE TITLE
Images and Merge_Feature

### ISSUE THREAD

**Issue by KWMSources** [sympa-community/sympa#337]
Hi,

I have an error by sending mails with sympa with the merge_feature on. If the mail contains an image (no matter if the image is attached or linked by html) the sender gets a mail back with "Cannot personalize message" (...) "Your message cannot be personalized.  Please check template syntax.".

I would really like to send a personalized newsletter with images in it, so it would be nice to fix it or get a workaround...

Thanks!

**Comment by dverdin** [comment]
Hi,

Do you have any logs from Sympa when the merge fails? That would be very helpful.
Also : does it fail whichever image you use?

Thanks!

**Comment by KWMSources** [comment]
Hi,

every image triggers the error.

Log:

`Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <test-mitglieder@listen.gruene-bonn.de.1528706413.7963>; envelope_sender=kay-wilhelm.maehler@gruene-bonn.de; message_id=d946ad53-64ac-8d99-1506-891fcdc9381a@gruene-bonn.de; sender=kay-wilhelm.maehler@gruene-bonn.de
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <test-mitglieder@listen.gruene-bonn.de.1528706413.7963> for Sympa::List <test-mitglieder@listen.gruene-bonn.de> with priority 5, <d946ad53-64ac-8d99-1506-891fcdc9381a@gruene-bonn.de>
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#177 > Sympa::Spindle::AuthorizeMessage::_test_personalize#344 > Sympa::Message::personalize#1240 > Sympa::Message::_merge_msg#1267 > Sympa::Message::_merge_msg#1331 Error merging message
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#177 > Sympa::Spindle::AuthorizeMessage::_test_personalize#344 > Sympa::Message::personalize#1240 > Sympa::Message::_merge_msg#1268 Failed to personalize message part
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#178 Failed to personalize. Message Sympa::Message <test-mitglieder@listen.gruene-bonn.de.1528706413.7963> for list Sympa::List <test-mitglieder@listen.gruene-bonn.de> was rejected
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <test-mitglieder@listen.gruene-bonn.de.1528706417.7831,8234>; envelope_sender=<>; message_id=sympa.1528706417.7831.758@listen.gruene-bonn.de; recipients=kay-wilhelm.maehler@gruene-bonn.de; sender=sympa-request@listen.gruene-bonn.de; template=delivery_status_notification; action=failed; status=5.6.5
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: notice Sympa::Bulk::store() Message Sympa::Message::Template <test-mitglieder@listen.gruene-bonn.de.1528706417.7831,8234> is stored into bulk spool as <5.5.1528706417.1528706417.845341.test-mitglieder@listen.gruene-bonn.de_s,7831,4443>
Jun 11 10:40:18 v22017014195343255 bulk[7836]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <5.5.1528706417.1528706417.845341.test-mitglieder@listen.gruene-bonn.de_s,7831,4443/s> to Sympa::List <test-mitglieder@listen.gruene-bonn.de> (priority 5) (starting 1 seconds after scheduled expedition date)
Jun 11 10:40:18 v22017014195343255 bulk[7836]: notice Sympa::Mailer::store() Done sending message Sympa::Message <5.5.1528706417.1528706417.845341.test-mitglieder@listen.gruene-bonn.de_s,7831,4443/s> for Sympa::List <test-mitglieder@listen.gruene-bonn.de> (priority 5) in 1 seconds since scheduled expedition date
`

Thanks in advance!

**Comment by KWMSources** [comment]
Hi,

every image triggers the error.

Log:

`Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <test@listen.foo.de.1528706413.7963>; envelope_sender=...@foo.de; message_id=d946ad53-64ac-8d99-1506-891fcdc9381a@foo.de; sender=...@foo.de
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <test@listen.foo.de.1528706413.7963> for Sympa::List <test@listen.foo.de> with priority 5, <d946ad53-64ac-8d99-1506-891fcdc9381a@foo.de>
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#177 > Sympa::Spindle::AuthorizeMessage::_test_personalize#344 > Sympa::Message::personalize#1240 > Sympa::Message::_merge_msg#1267 > Sympa::Message::_merge_msg#1331 Error merging message
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#177 > Sympa::Spindle::AuthorizeMessage::_test_personalize#344 > Sympa::Message::personalize#1240 > Sympa::Message::_merge_msg#1268 Failed to personalize message part
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#178 Failed to personalize. Message Sympa::Message <test@listen.foo.de.1528706413.7963> for list Sympa::List <test@listen.foo.de> was rejected
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <test@listen.foo.de.1528706417.7831,8234>; envelope_sender=<>; message_id=sympa.1528706417.7831.758@listen.foo.de; recipients=...@foo.de; sender=sympa-request@listen.foo.de; template=delivery_status_notification; action=failed; status=5.6.5
Jun 11 10:40:17 v22017014195343255 sympa_msg[7831]: notice Sympa::Bulk::store() Message Sympa::Message::Template <test@listen.foo.de.1528706417.7831,8234> is stored into bulk spool as <5.5.1528706417.1528706417.845341.test@listen.foo.de_s,7831,4443>
Jun 11 10:40:18 v22017014195343255 bulk[7836]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <5.5.1528706417.1528706417.845341.test@listen.foo.de_s,7831,4443/s> to Sympa::List <test@listen.foo.de> (priority 5) (starting 1 seconds after scheduled expedition date)
Jun 11 10:40:18 v22017014195343255 bulk[7836]: notice Sympa::Mailer::store() Done sending message Sympa::Message <5.5.1528706417.1528706417.845341.test@listen.foo.de_s,7831,4443/s> for Sympa::List <test@listen.foo.de> (priority 5) in 1 seconds since scheduled expedition date
`

Thanks in advance!

**Comment by dverdin** [comment]
And your images were included in a multipart/related message? Weird. Sympa should not have any interaction with an attachment/* part.
Do you have an example of such a message that failed to be parsed?

Cheers,

David

**Comment by KWMSources** [comment]
I can forward an example. Personally, I tried 2 ways:

1: By HTML-Link
`--------------3E98A6A5F548E6AD572508AA
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <div class="moz-cite-prefix">Am 10.06.2018 um 22:30 schrieb Kay:<br>
    </div>
    <blockquote type="cite"
      cite="mid:93b24424-fcff-801a-8229-e77d6095e47a@foo.de">
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <div class="moz-cite-prefix">Am 10.06.2018 um 20:49 schrieb Kay:<br>
      </div>
      <blockquote type="cite"
        cite="mid:ec941488-a570-79ce-8599-44e6f944fbfd@foo.de">
        <meta http-equiv="Content-Type" content="text/html;
          charset=utf-8">
        <img moz-do-not-send="true"
src="path_to_image"
          alt="" height="384" width="768"> </blockquote>
      <p><br>
      </p>
    </blockquote>
    <p><br>
    </p>
  </body>
</html>

--------------3E98A6A5F548E6AD572508AA--
`

2: As Attachment

`--------------A1DDCC2D9322D02F3ABFB61E
Content-Type: multipart/related;
 boundary="------------F1F9BEB858FE56371974924D"


--------------F1F9BEB858FE56371974924D
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit

<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <div class="moz-cite-prefix"><img
        src="cid:part1.B599C731.9D9FBFB3@foo.de" alt=""><br>
      Am 09.06.2018 um 22:38 schrieb Kay  :<br>
    </div>
    <blockquote type="cite"
      cite="mid:dce140e1-abb4-5575-fcbb-21211e25995a@foo.de">
      <pre wrap="">Test!

</pre>
    </blockquote>
    <p><br>
    </p>
  </body>
</html>

--------------F1F9BEB858FE56371974924D
Content-Type: image/jpeg;
 name="bohplhibpcmcjohp.jpg"
Content-Transfer-Encoding: base64
Content-ID: <part1.B599C731.9D9FBFB3@foo.de>
Content-Disposition: inline;
 filename="bohplhibpcmcjohp.jpg"

{ATTACHMENT-CODE}`**

**Comment by ikedas** [comment]
Hi @KWMSources,

Messages you shew were incomplete.  I added necessary headers and tested with them using Sympa 6.2.32, but could not reproduce reported behavior.

Could you please show a complete message you can reproduce?

**Comment by KWMSources** [comment]
`To: test-list@mylistserver.de
From: =?UTF-8?Q?Kay?= <kay@myadress.de>
Subject: Test
Message-ID: <787f55f6-42ea-7701-59e0-d501a5f4f981@myadress.de>
Date: Sun, 10 Jun 2018 00:33:00 +0200
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.8.0
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <p>Test</p>
    <p><br>
    </p>
    <img src="path_to_image" moz-do-not-send="true" alt="" height="384" width="768">
  </body>
</html>`

By the way, I'm using Thunderbird, but tried it also at Webmail Roundcube.

**Comment by KWMSources** [comment]
Here the full message of the "Cannot personalize"-Response of Sympa:

```
Return-Path: <MAILER-DAEMON>
X-Original-To: kay@myadress.de
Delivered-To: kay@myadress.de
Received: from mylistserver.de (mylistserver.de [185.170.114.251])
	by srv31.myprovider.info (Postfix) with ESMTP id C682CC190C
	for <kay@myadress.de>; Wed, 20 Jun 2018 14:30:18 +0200 (CEST)
Received: by mylistserver.de (Postfix, from userid 1000)
	id D32295F252; Wed, 20 Jun 2018 14:30:15 +0200 (CEST)
Message-Id: <sympa.1529497815.17326.696@mylistserver.de>
Date: Wed, 20 Jun 2018 14:30:15 +0200
To: kay@myadress.de
From: "SYMPA" <sympa-request@mylistserver.de>
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
Auto-Submitted: auto-replied
Content-Type: multipart/report; report-type=delivery-status;
	boundary="----------=_<sympa.1529497815.17326.196@mylistserver.de>"
Subject: Cannot personalize message
X-Loop: sympa@mylistserver.de
X-Mailer: Sympa 6.2.32

This is a MIME-encapsulated message.

------------=_<sympa.1529497815.17326.196@mylistserver.de>
Content-Disposition: inline
Content-Description: Notification
Content-Type: TEXT/PLAIN; charset="US-ASCII"
Content-Transfer-Encoding: 7BIT
MIME-Version: 1.0
Content-length: 250

This is an automatic response sent by Sympa Mailing Lists Manager.
Impossible to distribute your message for list 'test-mitglieder@listen.gruene-
bonn.de' for the following reason:

Your message cannot be personalized.  Please check template syntax.

------------=_<sympa.1529497815.17326.196@mylistserver.de>
Content-Type: message/delivery-status

Reporting-MTA: dns; mylistserver.de
Arrival-Date: Wed, 20 Jun 2018 14:30:15 +0200

Final-Recipient: rfc822; test-mitglieder@mylistserver.de
Action: failed
Status: 5.6.5
Remote-MTA: dns; mylistserver.de
Diagnostic-Code: X-Sympa; Conversion Failed

------------=_<sympa.1529497815.17326.196@mylistserver.de>
Content-Type: message/rfc822
Content-Disposition: inline

Received: from srv31.myprovider.info (srv31.myprovider.info [128.127.71.241])
	by mylistserver.de (Postfix) with ESMTPS id 7186F5F249
	for <test-mitglieder@mylistserver.de>; Wed, 20 Jun 2018 14:30:10 +0200 (CEST)
Received: from [10.20.103.44] (gw-2s00.infcs.de [194.95.66.1])
	by srv31.myprovider.info (Postfix) with ESMTPSA id 47C7BC1904
	for <test-mitglieder@mylistserver.de>; Wed, 20 Jun 2018 14:30:12 +0200 (CEST)
To: test-mitglieder@mylistserver.de
From: =?UTF-8?Q?Kay_Wilhelm_M=c3=a4hler?= <kay@myadress.de>
Subject: test
Message-ID: <5d11ee51-df2d-6171-d14f-40887b4bab1b@myadress.de>
Date: Wed, 20 Jun 2018 14:30:10 +0200
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.8.0
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="------------97986B9CBB2EA98D66A83660"
X-PPP-Message-ID: <20180620123012.22778.8724@srv31.myprovider.info>
X-PPP-Vhost: myadress.de

This is a multi-part message in MIME format.
--------------97986B9CBB2EA98D66A83660
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit


--------------97986B9CBB2EA98D66A83660
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 7bit

<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=utf-8">
  </head>
  <body text="#000000" bgcolor="#FFFFFF">
    <p><img src="path_to_image" alt="" height="384" width="768"></p>
  </body>
</html>

--------------97986B9CBB2EA98D66A83660--

------------=_<sympa.1529497815.17326.196@mylistserver.de>--
```

**Comment by albig** [comment]
I have the same problem and it is reproducable, that the sympa merge_feature does not work with HTML-only mails.

I'm using sympa 6.2.36.

An example, I sent via the webmailer of the German hoster GMX.de:

**failed email in HTML-format**
<pre>
From test@example.com Tue Oct 23 20:37:20 2018
Return-Path: <text@example.com>
Delivered-To: me@example.com
Received: (qmail 25810 invoked from network); 23 Oct 2018 22:37:20 +0200
MIME-Version: 1.0
Message-ID: <trinity-64285c63-d91e-4252-89c3-09eb10018d53-1540327037555@3c-app-gmx-bs42>
From: test@example.com
To: sympa-list@example.com, me@example.com
Subject: sympa test html-format
Content-Type: text/html; charset=UTF-8
Date: Tue, 23 Oct 2018 22:37:17 +0200
Importance: normal
Sensitivity: Normal

<html><head></head><body><div style="font-family: Verdana;font-size: 12.0px;"><div>body text</div></div></body></html>
</pre>

**working email in text-format**
<pre>
From  test@example.com Tue Oct 23 20:37:48 2018
Return-Path: <test@example.com>
Delivered-To: me@example.com
MIME-Version: 1.0
Message-ID: <trinity-f8839880-a67e-472b-9793-78e8fd29a833-1540327065166@3c-app-gmx-bs42>
From: test@example.com
To: sympa-list@example.com, me@example.com
Subject: sympa test text-format
Content-Type: text/plain; charset=UTF-8
Date: Tue, 23 Oct 2018 22:37:45 +0200
Importance: normal
Sensitivity: Normal

body text
</pre>

The logging shows the following in case of failed HTML-mail:
<pre>
Oct 23 22:47:42 mail sympa_msg[28356]: notice Sympa::Spindle::ProcessIncoming::_twist() Processing Sympa::Message <sympa-list@example.com.1540327658.27071>; envelope_sender=test@example.com; message_id=trinity-e7fa35cf-a276-4739-80a0-ce71234ece68-1540327644977@3c-app-gmx-bs42; sender=test@example.com
Oct 23 22:47:42 mail sympa_msg[28356]: info Sympa::Spindle::DoMessage::_twist() Processing message Sympa::Message <sympa-list@example.com.1540327658.27071> for Sympa::List <sympa-list@example.com> with priority 5, <trinity-e7fa35cf-a276-4739-80a0-ce71234ece68-1540327644977@3c-app-gmx-bs42>
Oct 23 22:47:42 mail sympa_msg[28356]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#177 > Sympa::Spindle::AuthorizeMessage::_test_personalize#344 > Sympa::Message::personalize#1240 > Sympa::Message::_merge_msg#1339 Error merging message
Oct 23 22:47:42 mail sympa_msg[28356]: err main::#243 > Sympa::Spindle::spin#95 > Sympa::Spindle::AuthorizeMessage::_twist#178 Failed to personalize. Message Sympa::Message <sympa-list@example.com.1540327658.27071> for list Sympa::List <sympa-list@example.com> was rejected
</pre>

**Comment by ldidry** [comment]
@albig @KWMSources Did you upgraded your Sympa to more recent versions and do you still have the problem? I can't reproduce it (I'm testing it on sympa-6.2 branch and on 6.40).

**Comment by ikedas** [comment]
Stagnating issue.  Close for now.
