### ISSUE TITLE
ERROR (search) - Missing argument filter

### ISSUE THREAD

**Issue by emauger** [sympa-community/sympa#341]
Hi,
I use version 6.2.32 on linux (CentOS 7).
I always have the message 'ERROR (search) - Missing argument filter' on all my lists when:
  - I go to the 'View the list of subscribers' panel;
  - I then search a specific user using 'Search for a user'
  - I click on the user to modify his reception mode (from Standard to None for example).
When I click on Update, I always have the error message.
If I don't search and browse the list of subscribers and then click directly on the user, I don't have the message.

In the logs, I have:
info main::check_action_parameters() [robot igf.cnrs.fr] [session 39436082885231] [client 10.7.8.6] [user administrator@igf.cnrs.fr] [list info] Missing parameter "filter"

err main::#1558 [robot igf.cnrs.fr] [session 39436082885231] [client 10.7.8.6] [user administrator@igf.cnrs.fr] Missing required parameters for action "search"

Any idea ?

**Comment by ikedas** [comment]
Hi @emauger,

If possible, could you please apply [this path](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/343.patch) to check if problem will be solved?

Thanks.

**Comment by emauger** [comment]
Hi Soji,
    
    It works perfectly.
    Thanks a lot.
    
    Le 15/06/2018 à 03:58, IKEDA Soji a
      écrit :
    
    
      Hi @emauger,
      If possible, could you please apply this path to check
        if problem will be solved?
      Thanks.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/sympa-community/sympa/issues/341#issuecomment-397490926","url":"https://github.com/sympa-community/sympa/issues/341#issuecomment-397490926","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/sympa-community/sympa","title":"sympa-community/sympa","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/sympa-community/sympa"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ikedas in #341: Hi @emauger,\r\n\r\nIf possible, could you please apply [this path](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/343.patch) to check if problem will be solved?\r\n\r\nThanks.\r\n"}],"action":{"name":"View Issue","url":"https://github.com/sympa-community/sympa/issues/341#issuecomment-397490926"}}}
      {
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [sympa-community/sympa] ERROR (search) - Missing argument filter (#341)",
"sections": [
{
"text": "",
"activityTitle": "**IKEDA Soji**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ikedas",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"sympa-community/sympa\",\n\"issueId\": 341,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"sympa-community/sympa\",\n\"issueId\": 341\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/sympa-community/sympa/issues/341#issuecomment-397490926"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 345456601\n}"
}
],
"themeColor": "26292E"
}
    
    
    -- 
         Eric Mauger              |  IGF UMR5203
Administrateur systeme et reseau  |  141, rue de la Cardonille
       04 34 35 92 37             |  34094 Montpellier cedex 5
