### ISSUE TITLE
Introducing cpanfile [meta issue]

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#355]
Introducing [`cpanfile`](https://metacpan.org/pod/distribution/Module-CPANfile/lib/cpanfile.pod) to manage dependency information about external Perl modules.

Workplace: [create-cpanfile](https://github.com/sympa-community/sympa/tree/create-cpanfile) branch.

Preceding discussions (possibly incomplete):

  - https://listes.renater.fr/sympa/arc/sympa-developpers/2018-05/msg00026.html
  - https://listes.renater.fr/sympa/arc/sympa-developpers/2018-05/msg00050.html
  - https://listes.renater.fr/sympa/arc/sympa-developpers/2018-05/msg00044.html

**Comment by ikedas** [comment]
@ldidry,

If you are ok, I'll merge `create-cpanfile` branch to `sympa-6.2` (including #351).

**Comment by ldidry** [comment]
Go for it!

**Comment by ikedas** [comment]
@ldidry,
I realized `cpanfile` does not contain Perl as dependency.  Isn't it problematic not to check version of Perl? If it is, how we would do it?

**Comment by ldidry** [comment]
Good point.

As said on https://metacpan.org/pod/Carton: "You can also specify the minimum perl required in cpanfile:"
```
requires 'perl', '5.16.3';
```

**Comment by ikedas** [comment]
I added a requirement perl as suggested.

@ldidry, if you feel ok, please merge pr above.  It will be the last thing added to 6.2.34!

**Comment by ikedas** [comment]
Thanks!
