### ISSUE TITLE
Sympa Ver. 6.2.32: Shibboleth user_attributes changed

### ISSUE THREAD

**Issue by pveith** [sympa-community/sympa#361]
I upgraded from 6.2.16 to 6.2.32 and anything seems to work just fine. But instead of having an XML-fragment with the addional Shibboleth attributes, i just get a hash-value in my database. I use the attributes to prefill the gecos-attribute, which now doesn't work now. Is this broken, or have i missed something?

**Comment by ikedas** [comment]
Hi @pveith,

Could you please show us configuration of each software?
  - Sympa --- `auth.conf` (Please omit sensitive information like password)
  - Shibboleth SP -- Attribute settings (what you added/changed, if you modified config files such as `attribute-resolver.xml`, `attribute-filter.xml`).

**Comment by pveith** [comment]
Yes, sure. I did not anticipate a shibboleth problem, as is worked very well wit the 6.2.16 Version from the debian stretch repro. I might as well mention that, i try to used apt build-dep sympa in stretch to build a 6.2.32 package for stretch, which worked out really well. We are using the debian-stretch-packaged version of of shibboleth, which is 2.6.0. This might just be the problem, as `attribute-resolver.xml` and `attribute-filter.xml` seem to be part of version 3 of shibboleth.

Syma auth:
```
generic_sso
        service_name                    Anmelden
        service_id                      federation_renater 
        http_header_list                eppn,cn
        email_http_header               eppn
        logout_url                      https://shibboleth-test****/idp/profile/Logout
```

**Comment by ikedas** [comment]
Looks you gets only standard attributes.

So what is "hash-value"? Can you show us with such as screen shot?

**Comment by pveith** [comment]
It was somthin like `eppn__PAIRS_SEP__XXX@uni-bonn.de__ATT_SEP__cn__PAIRS_SEP__FIRST LASTNAME` now i just get something like `HASH(AxFFFFFF)`.

**Comment by ikedas** [comment]
Hi @pveith,

If possible, can you apply [this patch](https://github.com/sympa-community/sympa/commit/dc6156b.patch) and check if problem will be solved?

**Comment by pveith** [comment]
Hi @ikedas,
As i said  before. My problem seems to have come from a defunctional shibboleth service provider installation and is already solved. As i received the Info that 6.2.34 is released, i already build packages for that and installed them. They work just fine. We test everything on our testserver before upgrading our main server, which will be done soon.
Hopefully we can directly go to 6.2.34. This means the patch is probably not necessary, i suspect. But i install test the patch, if it helps the project.

**Comment by ikedas** [comment]
@pveith, I missed your post.  OK, I'll withdraw my patch once, and close this issue.
Thanks for reporting!
