### ISSUE TITLE
sceneri subscribe.{auth,authdkim,auth_notify,auth_notifydkim}

### ISSUE THREAD

**Issue by taggart** [sympa-community/sympa#364]
I have questions about these sceneri
They are all similar to this:
```
is_subscriber([listname],[sender]) smtp,dkim,smime     -> do_it
true()                             smtp,dkim           -> request_auth
true()                             md5,smime           -> do_it
```

I guess the first line is checking to see if the sender is already subscribed? Why does it "do_it"? Is there any potential to change subscription settings in this way? Because it's got smtp in the line and isn't authenticated.
For the second line it's then doing request_auth no matter what, what's the point of listing dkim if it allows smtp as well too?
For line 3 I guess if they weren't a subscriber (line 1) and they already authenticated (line 2) and they have a proper md5 or smime, then they get subscribed?

Version
-------

Installation method
-------------------

Expected behavior
-----------------

Actual behavior
---------------

Additional information
----------------------

**Comment by ikedas** [comment]
On the 1st line, I think do_it is intensional: Even if a user wrote a bad scenario accepting subscription requests by subscribers themselves, Sympa once accept it and at last [finish it with _erroneous_ status](https://github.com/sympa-community/sympa/blob/sympa-6.2/src/lib/Sympa/Request/Handler/subscribe.pm#L75-L88) successfully.

**Comment by ikedas** [comment]
On the 2nd line, I think “dkim” is unnecessary: It looks added for completeness.

In addition, IMO “smtp” is also unnecessary: 1. As all other authentication levels supersede smtp level, if a list of authentication levels contains “smtp”, other levels may be omitted. And 2. As “smtp” is the default authentication level, list of levels itself may be omitted.

**Comment by taggart** [comment]
OK, that explanation makes sense, closing this issue. Thanks

**Comment by ikedas** [comment]
@taggart,
If you are interested, would you please check `unsubscribe.*` scenarios? Difference from `subscribe.*` scenario is that it takes `[email]` as e-mail to be unsubscribed separately from `[sender]`. In other words, users are possiblly able to unsubscribe others.
