### ISSUE TITLE
Unable to delete a pending list

### ISSUE THREAD

**Issue by finkyseb** [sympa-community/sympa#366]
Version
-------
6.2.32

Installation method
-------------------
source package

Expected behavior
-----------------
We should be able to activate or delete a pending list.

Actual behavior
---------------
Actually, we can only activate the list and then delete it.
It's impossible to delete directly a pending list :

```
Erreurs : Undefined subroutine &Sympa::Aliases::ERR_CONFIG called at /usr/share/sympa/lib/Sympa/Aliases/External.pm line 99.
           Pile d'appel           
DIED: Undefined subroutine &Sympa::Aliases::ERR_CONFIG called at /usr/share/sympa/lib/Sympa/Aliases/External.pm line 99.
 at /usr/share/sympa/lib/Sympa/Aliases/External.pm line 96.
        Sympa::Aliases::External::_error(15, '') called at /usr/share/sympa/lib/Sympa/Aliases/External.pm line 73
        Sympa::Aliases::External::del(Sympa::Aliases::External=HASH(0x8308af0), Sympa::List <test-creation-non-listmaster@unistra.fr>) called at /usr/share/sympa/lib/Sympa/Request/Handler/close_list.pm line 155
        Sympa::Request::Handler::close_list::_close(Sympa::Spindle::ProcessRequest=HASH(0x867e578), Sympa::Request <action=close_list;context=unistra.fr;current_list=test-creation-non-listmaster@unistra.fr;mode=install>) called at /usr/share/sympa/lib/Sympa/Request/Handler/close_list.pm line 107
        Sympa::Request::Handler::close_list::_twist(Sympa::Spindle::ProcessRequest=HASH(0x867e578), Sympa::Request <action=close_list;context=unistra.fr;current_list=test-creation-non-listmaster@unistra.fr;mode=install>) called at /usr/share/sympa/lib/Sympa/Spindle.pm line 95
        Sympa::Spindle::spin(Sympa::Spindle::ProcessRequest=HASH(0x867e578)) called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 11103
        main::do_close_list() called at /usr/lib/cgi-bin/sympa/wwsympa.fcgi line 1573
```

**Comment by finkyseb** [comment]
@eiro : Aurais-tu des pistes ou déjà rencontré un problème similaire ?

**Comment by ikedas** [comment]
Hi @finkyseb,
Could you please show us configuration of Sympa (`sympa.conf` and/or `robot.conf`), especially these parameters:
  - `aliases_program`
  - `aliases_db_type`
  - `sendmail_aliases`
  - `alias_manager`

**Comment by eiro** [comment]
hello @finkyseb,

On Tue, Jul 03, 2018 at 02:00:41AM -0700, Sébastien FINKBEINER wrote:
> @eiro : Aurais-tu des pistes ou déjà rencontré un problème similaire ?

* please don't use french on the issue system. if you want a frendly
  french support, please use the sympa-fr mailing list (or even send
  me an email and i'll reply if i can).

regards,
marc

**Comment by ikedas** [comment]
Don’t worry. In fact, there have been issues written with non-English.

If you feel you cannot describe what you want to say well with English, you may not hesitate to use your familiar language.

In short, there are no rules to use English in the Sympa community, and I think such rule is not nebessary.

**Comment by eiro** [comment]
hello,


On Tue, Jul 03, 2018 at 05:08:38AM -0700, IKEDA Soji wrote:
> If you feel you cannot describe what you want to say well with English, you may not hesitate to use your familiar language.
> In short, there are no rules to use English in the Sympa community, and I think such rule is not nebessary.

good to know.  thank you! however, i know @finkyseb has no problem at
all with english :)

regards
marc

**Comment by ikedas** [comment]
Hi @finkyseb,
Is the program alias_manager.pl the thing installed with Sympa?
  - If it is, remove sendmail_aliases and alias_manager lines in config file(s), and try to follow [installation instruction](https://sympa-community.github.io/manual/install.html) again.
  - If it is not, i.e. you created it, check if it is running sanely, for example execution bits in file mode is on.

**Comment by finkyseb** [comment]
Hi @ikedas,

I think our alias_manager.pl is a modified version of a past sympa alias_manager.pl
Our aliases are stored/written in an OpenLDAP backend.
I think also that I have to adapt the new aliases process.

**Comment by finkyseb** [comment]
Hi @ikedas,

We need to store aliases in our OpenLDAP.
Have you an example of configuration (template) to do that ?
Thanks.

**Comment by ikedas** [comment]
Hi @finkyseb,

An alias manager supporting LDAP is bundled in Sympa.  Though I have not tried it, following description may not be incorrect.

  - Please replace `$DEFAULTDIR`, `$LIBEXECDIR` and `$SYSCONFDIR` in below with real values (See content of `Sympa/Constants.pm` to know real values on your environment).

`$SYSCONFDIR/ldap_alias_manager.conf`:
  - Create it with following content.
    ```
    ldap_host               <LDAP host>
    ldap_base_dn            <base DN>
    ldap_bind_dn            <bind DN>                               # optional
    ldap_bind_pwd           <password>                              # optional
    ldap_mail_attribute     <attribute names>
    ldap_ssl                <0 or 1>
    ldap_ssl_version        <tlsv1, tlsv1_2 etc.>                   # optional
    ldap_cachain            <file including trusted certificates>   # optional
    queue_transport         $LIBEXECDIR/queue
    bouncequeue_transport   $LIBEXECDIR/bouncequeue
    ```

`$SYSCONFDIR/list_aliases.tt2`:
  - Copy `$DEFAULTDIR/list_aliases.tt2` to this place.

`$SYSCONFDIR/ldap_alias_entry.tt2`:
  - Copy `$DEFAULTDIR/ldap_alias_entry.tt2` to this place, and edit the copy as you prefer.

`sympa.conf`:
  - Add following setting:
    ```
    alias_manager $LIBEXECDIR/ldap_alias_manager.pl
    ```

Note:
  - Currently, LDAP (ldap) and LDAP over TLS/SSL (ldaps) are supported.  LDAP with StartTLS has not been supported yet.

**Comment by ikedas** [comment]
Yes, that fix was included in Sympa 6.2.34 released just now.

However I'm not sure your alias_manager.pl will work as expected.  If possible, can you check new release or apply that commit to current version?

**Comment by finkyseb** [comment]
Hi @ikedas,

This fix corrects our problem.
But we detects another one. Perhaps should I open another issue ?
The process to rename a list takes an incredible time.
In the web interface we receives an HTTP 500 error and via the shell (sympa.pl --rename_list) it works but takes lots of time.
We make a strace on the process and it seems to parse all the robots and list before to rename effectively the list.

**Comment by ikedas** [comment]
Hi @finkyseb, thanks for confirming!
Well, we'd be better to close this issue and move to new one.

**Comment by finkyseb** [comment]
Issue resolved by commit https://github.com/sympa-community/sympa/commit/fe66a41f47d83ef701d50776a7358d34219b7ef7
