### ISSUE TITLE
Rename a list takes incredible time

### ISSUE THREAD

**Issue by finkyseb** [sympa-community/sympa#368]
Version
-------
[Sympa 6.2.32](https://github.com/sympa-community/sympa/commit/55a07dd8688f616e180915022a8423f9bee5e554)

Installation method
-------------------
Source Package

Expected behavior
-----------------
Rename a list via Web Interface or via the shell with sympa.pl

Actual behavior
---------------
The process to rename a list takes an incredible time.
In the web interface we receives an HTTP 500 error and via the shell (sympa.pl --rename_list) it works but takes lots of time.
We make a strace on the process and it seems to parse all the robots and list before to rename effectively the list.

Unistra team
---------------
@acexiis @finkyseb @jean1

Additional information
----------------------

**Comment by ikedas** [comment]
In [Sympa::Request::Handler::move_list::_move()](https://github.com/sympa-community/sympa/blob/6.2.32/src/lib/Sympa/Request/Handler/move_list.pm#L209), all spools are scanned and their contents are renamed.  During this process, each of directory entries is read and confirmed which list it belongs to (with `$spool->next`).

**Comment by finkyseb** [comment]
Ok I understand the problematic, but in our case, our users loose the capability of rename a list.
All actions done with the graphical interface ended with an internal error.
Do you think, you will be able to fix this bug soon ?

Thanks.

**Comment by ikedas** [comment]
Hi @finkyseb,

Can your team give us any solutions or hints to improve scanning directory?

**Comment by ikedas** [comment]
Hi @finkyseb and all,

Is [this patch](https://github.com/sympa-community/sympa/compare/1fb5a1a...ikedas:265ebbc.patch) improve? (**Note**: this patch was poorly tested.  Don't apply it to production system).

**Comment by ikedas** [comment]
[The patch was updated](https://github.com/sympa-community/sympa/compare/1fb5a1a...ikedas:4e38c71.patch).

**Comment by ikedas** [comment]
Hi @finkyseb and all,

My fix will be released with the next stable, 6.2.36. If it will not improve satisfactorily, please re-open this issue.

Thanks for inputs!
