### ISSUE TITLE
Perl dies when changing priveleged list owners via web interface

### ISSUE THREAD

**Issue by aejm-unikent** [sympa-community/sympa#37]
Using Sympa 6.2.18. When trying to change privileged owners for a mailing list using the web interface, the following error message appears and the change fails:

`DIED: missing parameter "user" at /usr/share/sympa/lib/Sympa.pm line 519. Sympa::send_notify_to_user(Sympa::List <mailing-list@kent.ac.uk>, 'added_as_listadmin', '', HASH(0xde4a230)) called at /usr/libexec/sympa/wwsympa.fcgi line 11847 main::_notify_added_admin(Sympa::List::Config <mailing-list@kent.ac.uk>) called at /usr/libexec/sympa/wwsympa.fcgi line 11609 main::do_edit_list() called at /usr/libexec/sympa/wwsympa.fcgi line 1680`

**Comment by ikedas** [comment]
@aejm-unikent,

Could you please check if [this patch](https://github.com/sympa-community/sympa/commit/36a01f96d6f3475448fb67b04f484582ec675064.patch) solve the problem?
