### ISSUE TITLE
Schedule for remote inclusion of users

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#370]
I have several lists in my server that include users from a remote SQL Database. For maintenance reasons our SQL Database server is out of service for a couple of minutes everyday so, during this period, Sympa generates a bunch of e-mail messages warning us of the problem. 

Is there a way to prevent Sympa to try to include users during scheduled hours? Or, in other words, is there a way to schedule user inclusions?

**Comment by ikedas** [comment]
Hi @qosobrin,

Probably you can set "Time ranges when inclusion is not allowed" (períodos de tiempo en los que la inclusión no está permitida) in Data sources setup page.

**Comment by ikedas** [comment]
There seem no additional questions.  Close.
