### ISSUE TITLE
Change of case in original strings in the translation site does not result in warnings for translated languages

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#374]
Sorry for posting this issue here as it is not related to Sympa but to the translation site https://translate.sympa.org but I have found no other place where to post it.

When you update a string in English changing just the case for one or more words the status of the translated string in the other languages should change to `Suggested` instead of `Translated`. If this is not possible the string should be shown as a new string.

For example, the string `used to encrypt passwords with the Bcrypt hash algorithm` recently changed to `Used to encrypt passwords with the Bcrypt hash algorithm.` but in Spanish and Galician the string was marked as `Translated`. As there is no way to know which string changed case, I can not correct them in the translations. I was aware of this change reading the commits in the git, but I think that should not be the way to proceed.

Side note: a good place to post this request would be the list for translators that I requested in #333 but that would require the list to be created open to subscribers to post instead of read-only as @ikedas stated in https://github.com/sympa-community/sympa-community.github.io/issues/17

**Comment by ikedas** [comment]
Hi @qosobrin,

Not alike some languages frequently updated, with several languages, there are slight chances to catch up minute changes on translated strings.  To keep strings translated as much as possible,  changes on translated strings to fix typos or formatting issues may be ignored (changes discussed on this issue is by #355, capitalizing sentences describing dependent modules).

I'd like to ask active translators for being patient.

**Comment by qosobrin** [comment]
Thank you for your answer, @ikedas . I see your point that some changes commited to the translation site need not to be translated, but unfortunatelly I think a change of case may have a visual impact on the final design/aspect.

The other point in my question/request is a central point of information for translators. Any advance on this? Today I was looking a way to communicate you that your translation server (http://translate.sympa.org) is behaving wierdly (I translated several strings into Galician but the system is still telling me that there are some untranslated strings) but I could not finf a way.

Thank you very much.
Regards,

**Comment by ikedas** [comment]
> Thank you for your answer, @ikedas . I see your point that some changes commited to the translation site need not to be translated, but unfortunatelly I think a change of case may have a visual impact on the final design/aspect.

> The other point in my question/request is a central point of information for translators. Any advance on this? Today I was looking a way to communicate you that your translation server (http://translate.sympa.org) is behaving wierdly (I translated several strings into Galician but the system is still telling me that there are some untranslated strings) but I could not finf a way.
> 
> Thank you very much.
> Regards,

**Comment by ikedas** [comment]
Hi @qosobrin,

> Thank you for your answer, @ikedas . I see your point that some changes commited to the translation site need not to be translated, but unfortunatelly I think a change of case may have a visual impact on the final design/aspect.

I’m very sorry that I could not help translators about changes occurred with a source code. Though I have known impact by case changes on your language (that’s comparable to mistake on distinction between two phonogram sets my language has: These two should be used separately), I chose easy way.  I’ll consider to notice translators in advance, if such cases will be expected in the future.

> The other point in my question/request is a central point of information for translators. Any advance on this? Today I was looking a way to communicate you that your translation server (http://translate.sympa.org) is behaving wierdly (I translated several strings into Galician but the system is still telling me that there are some untranslated strings) but I could not finf a way.

Update of statistical information of translation seems more or less behind translations themselves.  I’l try investigating how to fasten update.

Thanks for suggestions!

> Thank you very much.
> Regards,

**Comment by qosobrin** [comment]
Thanks you, @ikedas Since everything seem answered I'm closing the issue. Regards.
