### ISSUE TITLE
Sympa sysv init script not LSB compiliant

### ISSUE THREAD

**Issue by LAKostis** [sympa-community/sympa#376]
Version:
-------
sympa-6.2.24-1.20171222.RHEL6.x86_64

Installation method
-------------------
rpm

Expected behavior
-----------------
According LSB specification init script should return different exit codes for every status:
(http://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/iniscrptact.html)
~~~
0 | program is running or service is OK
-- | --
1 | program is dead and /var/run pid file exists
2 | program is dead and /var/lock lock file exists
3 | program is not running
4 | program or service status is unknown
5-99 | reserved for future LSB use
100-149 | reserved for distribution use
150-199 | reserved for application use
200-254 | reserved
~~~

Actual behavior
---------------
~~~
# service sympa status; echo "$?"
Status of Sympa subsystem: 
Status file for subsystem NOT found.
sympa_msg.pl is stopped
bulk.pl is stopped
archived.pl is stopped
bounced.pl is stopped
task_manager.pl is stopped
0
~~~

Additional information
----------------------
~~~
# rpm -qf /etc/init.d/sympa 
sympa-6.2.24-1.20171222.RHEL6.x86_64
~~~

I think this bug also exists in 6.2.34, but haven't checked yet.

**Comment by LAKostis** [comment]
[Simple fix for this](https://gist.github.com/LAKostis/05ced8ebbb6ddf73e1c90e6bb9f37a5a)

**Comment by ikedas** [comment]
Hi @LAKostis,
Could you please you submit your fix as pull request?

**Comment by ikedas** [comment]
Fix was merged. Thank you for improving Sympa!
