### ISSUE TITLE
Close and reopen long list will render them defunctional

### ISSUE THREAD

**Issue by pveith** [sympa-community/sympa#382]
I am not sure if this is a bug, or just an issue with a bottleneck in our vmware-stores. We have two bigger lists which we want to close, if they are not needed. These list have 8k and 30k subscribers imported from a separate local database, which will cause our server to timeout when opening or closing the list with the webfrontend. 
I can successfully close the lists with CLI-Interface, but opening them fails using the webinterface. (There seems to be no open-command with sympa.pl, is this right?)

**Version**
6.2.34; Compile from source build into a deb-package using the debian sympa-package as a template.

**Expected behavior**
opening and closing lists successfully.

**Actual behavior**
Timeout while importing subscriber (We get an Apache internal Server Error). From what i looked up configuration is done. The the process fails importing the subscribers. This means Owner and Moderator are not imported all! And the Aliases for Postfix are not installed.
From my point of view, it would be better to try an import owner & editor and install the aliases prior to importing all subscribers. The users are much easier to recover than owner, editor and aliases. At least IMHO they are more obvious to check.

**Additional Information**
Right now we will switch to just setting the send-option to "closed" thus disabling any sending to this list until we change that option.

**Comment by ikedas** [comment]
Hi @pveith,

I guess it a problem due to database load (speed).

Can you apply [this patch](https://github.com/sympa-community/sympa/pull/383.patch) in PR #383?  This adds `--open_list` option to CLI.

**Comment by pveith** [comment]
Hi @ikedas,
i installed the patch and it works like a charm. Even our smaller testserver can now handle these lists correctly. Thanks a lot.

**Comment by ikedas** [comment]
Hi @pveith,
Good. If you don't find problem with this patch, please close this issue.
Thanks for the input!

**Comment by pveith** [comment]
Okay, forgot to do it. Sorry.
