### ISSUE TITLE
Lost owners on list copy

### ISSUE THREAD

**Issue by UniversitaPerugiaSysAdm** [sympa-community/sympa#384]
Version
-------

6.2.34

Installation method:
-------------------

from RedHat packages

Expected behavior:
-----------------

creating a new list copying a template or an existing list, we expect to have a new working list

Actual behavior:
---------------

creating a new list copying a template or an existing list is created a new list without owners marked as "Erroneous configuration"

Additional information
----------------------

[sympa_log.txt](https://github.com/sympa-community/sympa/files/2223826/sympa_log.txt)

**Comment by ikedas** [comment]
Hi @UniversitaPerugiaSysAdm,

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/385.patch) and check if copying list works sanely?

Note: Before retrying renaming, "errorneous" list would be removed manually, i.e. removing a directory with _new_ list name under `/var/lib/sympa/list_data` or its subdirectory.

**Comment by UniversitaPerugiaSysAdm** [comment]
For now we solve the problem :  
  -  adding owners and editors 
  -  closing the list 
  -  then (as ListMaster) restoring the closed list.   
In this way List is recreated without errors.   
In the near future we will test the patch.
Thanks to all of you.

**Comment by ikedas** [comment]
@UniversitaPerugiaSysAdm, thanks for precise checking! The patch will be include in the next release in this year.
