### ISSUE TITLE
Notify user that he already subscribed to a list

### ISSUE THREAD

**Issue by SansPseudoFix** [sympa-community/sympa#386]
Version
-------

6.2.24

Expected behavior
-----------------

User should be notify that he already has a subscription when he tries to subscribe to a list.

Actual behavior
---------------

When a user tries to subscribe to a list he already subscribed, he does not receive a subscription email (seems ok) but he is not informed that he already has a subscription neither.

**Comment by ikedas** [comment]
HI @SansPseudoFix,

I think as following:

If you have not logged in, you have to enter your e-mail address to request for subscribing to the list.  Because, Sympa does not know _who are you_.  In fact, _everyone_ can enter your e-mail address instead of their own. Therefore, Sympa would be better not to tell everyone whether you have subscribed or not.

**Comment by SansPseudoFix** [comment]
Thank you @ikedas, I see. Seems legit with web interface but maybe, at least, send a mail: "You already are a subscriber of this list"?

**Comment by ikedas** [comment]
@SansPseudoFix, if Sympa sends a mail, I think content of the mail may be such as:

> Someone (probably you) requested for subscribing to xxxx list, but you have already subscribed to this list. There is nothing to do on your side.

Is this appropriate? (And is my english sane?)

**Comment by SansPseudoFix** [comment]
Yes, I think it's perfect! Thanks again.

> (And is my english sane?)

Well, from my french point of view, it seems flawless :P

**Comment by ikedas** [comment]
Thanks for confirming!  I'll try to implement it.  Please wait for a while (for some weeks).

**Comment by ikedas** [comment]
Hi @SansPseudoFix,
If possible, could you please check [this patch](https://github.com/sympa-community/sympa/compare/sympa-6.2...a51f2c8.patch) by the PR above?  (Unfortunately, this may be applicable to recent vrsion, not 6.2.24.)

**Comment by ldidry** [comment]
@ikedas I'll update our sympa next tuesday (14/08) and will try your patch. (@SansPseudoFix is one of my coworker)

**Comment by ikedas** [comment]
Thanks! I'll look forward your response.

**Comment by ldidry** [comment]
It works! Thank you :slightly_smiling_face:

**Comment by ikedas** [comment]
Merged. Thanks for confirming!

@SansPseudoFix, if you feel good, please close this issue.

**Comment by SansPseudoFix** [comment]
Yes, perfect, thank you!
