### ISSUE TITLE
sympa.pl --change_user_email no longer working with 6.2.34

### ISSUE THREAD

**Issue by agouaux** [sympa-community/sympa#389]
6.2.34
-------

Source
-------------------

`sympa.pl --change_user_email --current_email=OLD@domain.x --new_email=NEW@domain.x`

should change all occurrences in Sympa of OLD@domain.x to NEW@domain.x.
-----------------

When I use the command above, and OLD@domain.x is either an owner or editor, their address as either owner or editor is not updated.  The command returns successfully, but continually checking the owner/editor fields, and only the old address shows up.  I did a:

`sympa.pl --dump_users --list=LIST --role='owner,editor,member'`

and still the OLD@domain.x address was listed for the owner.
---------------

**Comment by agouaux** [comment]
I've confirmed that doing --dump_users and editing the dump file for the new email address, then doing a --restore_users works.  So, that'll be my workaround for now for owners/editors.

**Comment by ikedas** [comment]
Hi @agouaux,

  - Could you please show us Sympa logs during execution of `--change_user_email`?
  - Weren't the owner and editor addresses included from data sources?
  - Were subscriber addresses succsessfully changed?

**Comment by ikedas** [comment]
Hi @agouaux,
If possible, could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/395.patch) by PR above and check if the problem will solved?

**Comment by agouaux** [comment]
Sorry for lack of response!  I'll try to answer your questions this
afternoon.  Thanks!

**Comment by agouaux** [comment]
So, for the first set of questions, the log only showed that the command executed.

The owner was indeed manually subscribed and not from a data source.

Subscribers successfully changed.  In fact I used the same address for an owner and subscriber, did the command, it returned success, but only subscriber changed.

I'll now apply patch and try everything again.

**Comment by ikedas** [comment]
@agouaux, Thanks for confirming. This fix will be included in the next release of Sympa.
