### ISSUE TITLE
"Delivery delayed" mail incorrectly triggers bounce handler

### ISSUE THREAD

**Issue by jornane** [sympa-community/sympa#397]
Version
-------
sympa-6.2.16~dfsg-3
postfix-3.1.8-0+deb9u1

Installation method
-------------------
Debian package

Expected behavior
-----------------
When Sympa receives a mail on the Enveloppe-From address («listname»-owner@«domain»), it should not immediately mark all users as «in error». When users are «in error» for a short time (few days), Sympa should still attempt to send mail to them, even if 100% of users are «in error». Sympa should also send out error mails to the admin to indicate that there is a problem.

Actual behavior
---------------
When Sympa receives a mail from the Enveloppe-From address («listname»-owner@«domain»), it marks all users listed in that mail as «in error». When all users are «in error», Sympa starts sending out error mails to the admin to indicate that there is a problem, but stops forwarding mails to users. This happens even when the mail it received was not a bounce mail but simply a delayed delivery notice.

Additional information
----------------------
According to our logs, the only mail that was received on the bounce address («listname»-owner@«domain») had the following subject: `Delivery delayed:[«listname»] «subject of mail»`. Thus, no mail has been bounced, but a mail was sent to the Enveloppe-From address.

It would be great to have a configuration setting to continue delivering mails even if 100% of the users are «in error».

**Comment by ikedas** [comment]
Hi @jornane,

I read the code at a glance, and found that, if "Bounces management"/"warn rate" parameter in list config is set to be greater than `100` (such as `110`), error mails seem not to be sent to admins (cf. [correspondng code](https://github.com/sympa-community/historic-sympa/blob/tags/sympa-6.2.16/src/lib/Sympa/Spindle/ToList.pm#L203-L213)).  I'm not sure that forwarding to all users will be stopped in this case.  Can you check "warn rate" parameter?

**Comment by jornane** [comment]
```
## expire_bounce_task
## Task name for expiration of old bounces
expire_bounce_task      daily

## bounce_warn_rate
## Bouncing email rate for warn list owner
bounce_warn_rate        30

## bounce_halt_rate
## Bouncing email rate for halt the list (not implemented)
## Not yet used in current version, Default is 50
bounce_halt_rate        50
```

I've set up a test list, but it seems that Sympa *will not send out mail* to addresses it thinks are bouncing. So then I guess I'm looking for a way to not mark addresses as bouncing based on just one returned mail (since that returned mail can be a delay notification instead of an actual bounce). I see that I can expire bounces earlier, but that would also affect addresses that are actually bouncing.

**Comment by ikedas** [comment]
Hi @jornane,

`expire_bounce` task always clears bounce information older than 10 days.  Probably bounce scores of subscribers have been high enough, and forwarding won't be resumed in several days.

What you can do to resume forwarding immediatly is resetting bounce scores of each subscriber: Go to "Review" (list of subscribers) page, click e-mail address of user who has bounce score, and click "Reset errors".

----
To suppress increase of bounce scores, you'd be better to increase `minimum_bouncing_count` and/or `minimum_bouncing_period` parameters in `sympa.conf`. They decide to increase bounce scores when how many bounces are returned in how long period (see [description](https://sympa-community.github.io/manual/man/sympa.conf.5.html#minimum_bouncing_count)).

**Comment by ikedas** [comment]
Stagnating issue. I'll close it at present.
