### ISSUE TITLE
sympa_msg: uninitialized value

### ISSUE THREAD

**Issue by moritz25** [sympa-community/sympa#40]
Hey,
I get in  /var/spool/sympa/tmp/PID.stderr the following message:
Use of uninitialized value in numeric le (<=) at /usr/share/sympa/lib/Sympa/List.pm line 1391.
The PID from sympa_msg.pl
I'm using debian 9 (Stretch), with sympa 6.2.16~dfsg-3 and perl v5.24.1

**Comment by ikedas** [comment]
Hi,

Can you check if [this patch](https://github.com/sympa-community/sympa/commit/31269c058f1c7bdd565b1bfc0d372550f9ba5980.patch) solve the problem you reported?

**Comment by moritz25** [comment]
Hey, 
yes this patch solve this problem. Thank you.

**Comment by ikedas** [comment]
Merged.  Thank you for reporting bug!
