### ISSUE TITLE
Internal Server Error: Can't locate object method "_marshal_format" in Spool.pm (71)

### ISSUE THREAD

**Issue by promasu** [sympa-community/sympa#401]
Version
-------

Name        : sympa
Version     : 6.2.35b.1
Release     : 1.20180826.RHEL7
Architecture: x86_64

Name        : postfix
Epoch       : 2
Version     : 2.10.1
Release     : 6.el7
Architecture: x86_64

Installation method
-------------------

rpm

Expected behavior
-----------------

Access over wwsympa with nginx (config from documentation)
I have only one account listed as listmaster at robot.conf of that specified domain.
I want to make a list request at (create_list_request).

Actual behavior
---------------

When submitting the form the error below occures.

Additional information
[Stacktrace_Sympa_marshal_format.txt](https://github.com/sympa-community/sympa/files/2325262/Stacktrace_Sympa_marshal_format.txt)

----------------------

**Comment by WhiteGryphonFIT** [comment]
I'm running into the same issue on CentOS 6.9 after the 6.2.35b.1 update.

**Comment by ikedas** [comment]
It's failure in code due to poor reviewing/testing.

Please apply [This patch](https://github.com/sympa-community/sympa/commit/9e45263336f2de97a86f86c2511991af06188b50.patch) and check if the problem will be solved.

**Comment by promasu** [comment]
It worked. Thanks a lot!
