### ISSUE TITLE
Error in the name of a function in wwsympa.fcgi

### ISSUE THREAD

**Issue by bmarchal54** [sympa-community/sympa#404]
An mistake is present in the script wwsympa.fgci at line 6463

Version
-------
6.2.32

Installation method
-------------------
rpm

Expected behavior
-----------------
Copy a tt2 in the local directory of a list.

Actual behavior
---------------
DIED: Undefined subroutine &Sympa::Language::caonic_lang called at /usr/libexec/sympa/wwsympa.fcgi line 6463.
 at /usr/libexec/sympa/wwsympa.fcgi line 6461.
	main::do_copy_template() called at /usr/libexec/sympa/wwsympa.fcgi line 1573

Additional information
----------------------
A patch to correct the mistake 

```
[root@esbareich sympa]# diff wwsympa.fcgi wwsympa.fcgi-6.2.32-avantPatchLang 
6463c6463
<         $param->{'tpl_lang_lang'} = Sympa::Language::canonic_lang($tpl_lang);
---
>         $param->{'tpl_lang_lang'} = Sympa::Language::caonic_lang($tpl_lang);
```

**Comment by ikedas** [comment]
Fixed: https://github.com/sympa-community/sympa/commit/928beff06b68380d31d9dc75cbe25c1c31df53cd Thanks for reporting bug!
