### ISSUE TITLE
DKIM per-list options not saved

### ISSUE THREAD

**Issue by jrlevine** [sympa-community/sympa#412]
Version
-------

6.2.34

Installation method
-------------------

source package

Expected behavior
-----------------

Update DKIM parameters like selector or private key file, should be saved in list config file

Actual behavior
---------------

not saved in list config file

Additional information
----------------------

dkim_feature and dkim_signature_apply_on are saved, but stuff in the dkim_parameters section are not

**Comment by jrlevine** [comment]
Note: if you hand-edit the parameters into the config file, it'll read it properly, but if you save it
from the CGI, nothing gets saved, not even the old values.

**Comment by ikedas** [comment]
Hi @jrlevine,

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/413.patch) and check if the problem will be solved? Thanks!

**Comment by jrlevine** [comment]
I applied the patch and it didn't fix the problem. As an experiment I commented out the obsolete header_list sub-parameter in ListDef.pm and it *still* didn't save the paragraph.

**Comment by ikedas** [comment]
Just in case, did you [force reloading web service](https://sympa-community.github.io/manual/admin/services.html#reloading-wwsympa)?

**Comment by jrlevine** [comment]
On Wed, 12 Sep 2018, IKEDA Soji wrote:
> Just in case, did you [force reloading web service](https://sympa-community.github.io/manual/admin/services.html#reloading-wwsympa)?

It's in a test setup with plain CGI, the web service starts up for every 
www request.

Regards,
John Levine, johnl@iecc.com, Primary Perpetrator of "The Internet for Dummies",
Please consider the environment before reading this e-mail. https://jl.ly

**Comment by ikedas** [comment]
> It's in a test setup with plain CGI, the web service starts up for every
www request.

CGI mode was deprecated on 6.2.24 (see #69).  I think you may have to restart web service, wwwsympa.fcgi process and HTTPd.

**Comment by jrlevine** [comment]
On Wed, 12 Sep 2018, IKEDA Soji wrote:
>> It's in a test setup with plain CGI, the web service starts up for every
> www request.
>
> CGI mode was deprecated on 6.2.24 (see #69).  I think you may have to restart web service, wwwsympa.fcgi process and HTTPd.

I took a look.  The CGI::Fast module will also work as regular CGI, and 
everything else works fine.  I'm pretty sure that's not it.

Regards,
John Levine, johnl@iecc.com, Primary Perpetrator of "The Internet for Dummies",
Please consider the environment before reading this e-mail. https://jl.ly

**Comment by ikedas** [comment]
I don't know whether wwsympa will work sanely as plain CGI or not.  Anyways, on my environments with FastCGI, either:
- Apache 2.2 + mod_fcgid + wwsympa-wrapper.fcgi + wwsympa.fcgi 6.2.35b.1
- nginx + spawn_fcgi + wwsympa.fcgi 6.2.35b.1

the problem was reproduced, and was solved by applying the patch.

**Comment by jrlevine** [comment]
I'm now running Apache 2.4 + mod_proxy + mod_proxy_fcgi + spawn_fcgi + wwsympa-wrapper.fcgi + 6.2.35b.1 and it doesn't work. Who knows, will try again after I finish the ARC patches.
