### ISSUE TITLE
list created by a perl script - problem of no_owner_defined()

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#420]
With Sympa version 6.2.32, I was able to create a list with a perl script which create a folder named as the list, an in this folder an info file and a config file.

After that, I ran sympa.pl with the options --reload_list_config and --sync_list_db

As I have a lot of lists to create each year, this method is very fast but now whith sympa 6.2.36, I get the error : Sympa::List::set_status_error_config#464 The list Sympa::List is set in status error_config: no_owner_defined().

Even if there is a directive "owner_include" in the config file.

What should I do to be able to continue to create my lists with that method ?

Thanks,

**Comment by pascalmaes** [comment]
It doesn't
The option --open_list seems to work only with cloded lists, not with the pending one
I will try with the line status closed next time I have to create a new list.

OK for the other command 

/var/sympa/bin/sympa.pl --restore_users --list=listname\@robot --role=owner

**Comment by ikedas** [comment]
Sorry, then, in step 1., how about replacing “status ...” line with “status closed”?

**Comment by pascalmaes** [comment]
It works
Thank you

**Comment by ikedas** [comment]
Thanks for confirming.  I’ll add this  procedure to Administration Manual.
