### ISSUE TITLE
Error escaping apostrophe on stats page

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#428]
Version
-------
6.2.36 (but I believe it's been present for quite a few versions)

Installation method
-------------------
sympa-ja.org.rhel.repo

Expected behavior
-----------------
Stat plots should display

Actual behavior
---------------
Stat plots with apostrophes in the title don't display

Additional information
----------------------
Sympa version is in french. So for example title of plot **chartdivdel** is "Utilisateur supprimé par l'administrateur". The apostrophe throws a javascript error and the plot is completely blank. Same for plot 
 **chartdivadd_or_subscribe**, the French title is "Ajout d'abonnements".

**Comment by ikedas** [comment]
Hi @laerm,

Can you apply [this patch](https://github.com/ikedas/sympa/commit/f5f2f9e.patch) to `stats.tt2` and check if the problem will be solved?  Thanks.

**Comment by ikedas** [comment]
@laerm, thanks for reporting and confirming! I found more similar bugs in the other places and fixed them together.
