### ISSUE TITLE
List parameter "host" should be abolished

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#43]
Lists can have `host` parameter overriding host part of list addresses derived from virtual host the list belongs to.

- Cons:

  It breaks alias management: When a list is removed, alias manager cannot find aliases to be removed; If users (owners) change this parameter, aliases won't be renamed.  At least current implementaion cannot handle those situations properly.

- Pros:

  Users (listmasters) can categorize lists with multiple domains under one virtual host. It may be useful for some service providors hosting list services to users by each virtual domain.

IMO this feature would be better to be removed for simplicity of implementation.

**Comment by dverdin** [comment]
- Another con: In addition, when a virtual host domain changes, these list-specific host parameters are not changed. Thus leading to confusion and errors.
- Another pro: when hosting lists behind another frontend than Sympa (I did it with zimbra), you can have a virtual lists domain (lists.example.com) that's only used in enveloppes and a visible list domain (example.com) that's the same as the frontend domain, making all addresses (lists and people) appear in the same domain. In that case, the list host parameter is example.com when the virtual host parameter is lists.example.com.

So indeed, implementation is harder with this parameter but it has its use cases. Before removing this parameter, we should think about whether replacements exist for the current instances using it.

**Comment by ikedas** [comment]
PR above will add notice on deprecation during upgrading process.
Milestone is set to 6.2.28 (on June).
