### ISSUE TITLE
Primary `auth.conf` won't be used by robots

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#432]
Version
-------
At least 6.2.32 or later, and maybe also earlier versions. 

Installation method
-------------------
RPM, however other methods will apply.

Expected behavior
-----------------
When these files exist (note: `dom.ain` below is not primary domain):
  - `$SYSCONFDIR/auth.conf`
  - `$SYSCONFDIR/dom.ain/robot.conf`

and this file does _not_ exist:
  - `$SYSCONFDIR/dom.ain/auth.conf`

during login process on web interface of `dom.ain`, setting in the first file `$SYSCONFDIR/auth.conf` is applied.

Actual behavior
---------------
Setting in `$SYSCONFDIR/auth.conf` is not used but default behavior (only password login with `user_table` is enabled) is performed.

Additional information
----------------------
Honestly I'm not sure current behavior is buggy.  But it looks making sense that `$SYSCONFDIR/auth.conf` is used by default.

**Comment by xavierba** [comment]
It makes sense to have auth.conf behave like other conf/template files, that is, parse conf from narrower (in this case, mail domain) to wider (in this case, site) configuration, as described here : https://sympa-community.github.io/manual/customize/basics-configuration.html
I just spent a bit of time helping someone on IRC. There was no way to get LDAP auth working until an auth.conf file was dropped into /etc/sympa/mail_domain, although /etc/sympa/auth.conf was properly configured, but silently ignored.

**Comment by Saphar** [comment]
This bug also affects 6.2.24. I agree with xavierba, the behavior is unexpected and caused me quite some time to figure out.

**Comment by ikedas** [comment]
Hi, could anyone please check if [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/513.patch) will solve the problem?
