### ISSUE TITLE
Not able to insert into logs_table

### ISSUE THREAD

**Issue by bertaviader** [sympa-community/sympa#433]
Version
-------
Ubuntu 16.04
Sympa 6.2.16
MariaDB 10.2.15
Sendmail 8.15.2
Apache 2.4.18

Installation method
-------------------
Adding the apt-source and installing it by apt-install

Expected behavior
-----------------
When something happens in the application it's expected to save the logs into de table logs_table

Actual behavior
---------------
When the user is going to a list, the logs in the application are not displaying. Also, there is an error in the logs.

Additional information
----------------------
Errors in the logs:

err main::#1662 > main::do_setpref#5657 > main::web_db_log#2067 > Sympa::Log::db_log#317 > Sympa::Database::do_prepared_query#379 Unable to execute SQL statement "INSERT INTO logs_table (date_logs, usec_logs, robot_logs, list_logs, action_logs, parameters_logs, target_email_logs, msg_id_logs, status_logs, error_type_logs, user_email_logs, client_logs, daemon_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)": (HY000) Field 'id_logs' doesn't have a default value

**Comment by ikedas** [comment]
Hi @bertaviader,
It seems that you imported database from earlier version of Sympa (maybe on the other machine). If it is the case, could you please tell us the previous version?

**Comment by bertaviader** [comment]
Well, we tried to install another version of sympa the version 6.1.24. But then we installed the 6.2.16. 
Maybe the process corrupted the database. The sympa it's not yet in production, do you know a way to resolve this?

Thank you!

**Comment by bertaviader** [comment]
Thank you so much!!!! It worked like a charm!!!
