### ISSUE TITLE
oracle data source setup with service_name parameter

### ISSUE THREAD

**Issue by bv-unibs** [sympa-community/sympa#446]
Hi,

I've an old sympa mailing list server ( ver. 6.1.17) with several lists configured for fetching data from oracle database query sources.

Soon I have to change the oracle database server which sympa is using for its queries, and after doing some tests I've encountered a problem with the oracle data source setup.
	
From sympa web interface when I configure the query data source using the new connection parameters, I can't establish the db connection for fetch data from the query.

I understand the problem lies in database name parameter, that for sympa is the oracle SID of the db instance.

With the previous database server configuration the oracle sid worked perfectly, but with the new configuration the db server uses a service_name for remote db connection purposes.
	
I tried to issue a command line connection via DBI Perl libraries, and I see i can establish a db connection with the service name parameter to the new database server, but when I refresh a query with  Sympa from web interface it's like sympa issues a connection call to DBI perl with the oracle SID parameter, that's is not accepted from the new remote database.

From sympa log when i try a new query from the web interface i see this error:

**wwsympa: err SQLSource::connect() Can't connect to Database DBI:Oracle:host=hostname;sid=service_name;port=port_number as username**

From what I see the problem is Sympa tries to issue a DBI connection passing the service name parameter for the remote instance as sid parameter, but when I try a direct connection from DBI using command line, and passing service name parameter as it is I can establish the connection.

I suppose the problem is I can't specify from web interface that db name parameter isn't the Oracle SID but the service_name parameter,  and sympa passes the wrong command to the perl function. 

Can I ask you if there's something wrong with what I'm doing, how can I workaround this problem or if  it's possible to connect to an oracle database via service name?
	
thanks

**Comment by ikedas** [comment]
Hi @bv-unins,

Please see PR #431.
