### ISSUE TITLE
Sympa 6.2.36: Crash of web interface when editing list moderators

### ISSUE THREAD

**Issue by sk-unikent** [sympa-community/sympa#456]
Version
-------
Sympa 6.2.36

Installation method
-------------------
RPM

Expected behavior
-----------------
When adding a list moderator to a list, the list moderator should be added, and no error should be displayed. This is done under the path /sympa/review/LISTNAME/editor, a form "Add moderators" is filled out and then "Update" is pressed, which currently results in the failure.

Actual behavior
---------------
Internal Server Error
Sympa encountered an internal error.

Please contact the listmaster.

Error: Can't use an undefined value as an ARRAY reference at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.

Traceback
DIED: Can't use an undefined value as an ARRAY reference at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.
 at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.
	Sympa::List::Users::__ANON__(Sympa::List::Users <notputtingthisongithub@kent.ac.uk>, HASH(0xe23d748)) called at /usr/share/sympa/lib/Sympa/Config.pm line 672
	Sympa::Config::_validate_changes(Sympa::List::Users <notputtingthisongithub@kent.ac.uk>, HASH(0xe23d748), ARRAY(0xea16580)) called at /usr/share/sympa/lib/Sympa/Config.pm line 285
	Sympa::Config::submit(Sympa::List::Users <notputtingthisongithub@kent.ac.uk>, HASH(0xe224c48), 'notputtingthisongithub2@kent.ac.uk', ARRAY(0xea16580)) called at /usr/libexec/sympa/wwsympa.fcgi line 4834
	main::_review_user('editor') called at /usr/libexec/sympa/wwsympa.fcgi line 4791
	main::do_review() called at /usr/libexec/sympa/wwsympa.fcgi line 1572

**Comment by sk-unikent** [comment]
From maillog:
err main::#1572 > main::do_review#4791 > main::_review_user#4834 > Sympa::Config::submit#285 > Sympa::Config::_validate_changes#672 > Sympa::List::Users::__ANON__#75 DIED: Can't use an undefined value as an ARRAY reference at /usr/share/sympa/lib/Sympa/List/Users.pm line 75.

**Comment by sk-unikent** [comment]
Hi @ikedas, thanks for the fast response!
I can confirm it resolves that particular issue but then I get:
>  ERROR (review) - Unable to reduce the number of list owners in required domains to 0. Domains that count toward the minimum requirement of 1: kent.ac.uk 

I can confirm there are two owners under the Kent domain (I tried re-adding them) on this list... I'm trying to work out why 'owners' is null in the first place, but it seems like everything in the list config is in order.

**Comment by sk-unikent** [comment]
Yes that works as a workaround, thank you!
I can confirm from a test box the issue is also present in 6.2.37b

**Comment by ikedas** [comment]
Thanks @sk-unikent for confirming! This fix will be included in 6.2.37b.2 in the next month.
