### ISSUE TITLE
message.footer in digest/summary message

### ISSUE THREAD

**Issue by acasadoual** [sympa-community/sympa#458]
Expected Behavior
-----------------
message.footer in digest/summary message. It is necessary to notify the subscriber of Personal Data Protection Clause

Current Behavior
----------------

Nothing to show

Possible Solution
-----------------

Include the same file "message.footer" or other file "message.footer.digest"

Context
-------

The actual version is 6.2.37b1

**Comment by acasadoual** [comment]
Hi ikedas,
I'm @acasadoual. Is it ok?

[% TRY %]
[% INSERT "message.footer" %]
[% CATCH %]
[% END %]

Thanks you.

**Comment by ikedas** [comment]
No, you may have to include notices directly in the templates.

**Comment by acasadoual** [comment]
If i want to include only in the foo list, i have to put the template in "list_data/foo/mail_tt2/summary.tt2 ?

**Comment by ikedas** [comment]
Yes, I think you are right.

**Comment by acasadoual** [comment]
No, all are ok.

**Comment by ikedas** [comment]
Ok, this issue is closed. Thanks for sharing your experience.
