### ISSUE TITLE
Owners et editors dont get imported from config files while upgrading to 6.2.36

### ISSUE THREAD

**Issue by salaun-urennes1** [sympa-community/sympa#459]
Version
-------
Moving from Sympa 6.2.16 to  6.2.36

Installation method
-------------------
Installation from sources

Expected behavior
-----------------
As stated in the changelog : Owners and moderators are no longer stored in list config file: They are stored only in database #49. However I would expect that the upgrade process to 6.2.36 would take a last look at list config files to import owners/editors in database.

Actual behavior
---------------
While running `sympa.pl --upgrade` I noticed a couple of these errors : 
```
err main::#842 > Sympa::Upgrade::upgrade#137 > Sympa::List::get_lists#7932 > Sympa::List::new#420 The list "m36895_1819" has got no owner defined
err main::#842 > Sympa::Upgrade::upgrade#137 > Sympa::List::get_lists#7932 > Sympa::List::new#422 > Sympa::List::set_status_error_config#464 The list Sympa::List <m36895_1819@listes.etudiant.univ-rennes1.fr> is set in status error_config: no_owner_defined()
```

I checked and found out that:
- owners are defined for this list in the config file
- owners are not in the DB admin_table 

I don't know why owners definition were not in sync between config file and database. It might be related to #11020.

The problem is that I don't have any easy way to force the update of admin_table, now that Sympa::List::_load_list_admin_from_config() subroutine has been removed.

I ended up writing this script to fix things:
```
#!/bin/bash
for config in `find /data/sympa/list_data -name config`
do 
  dir=$(dirname "$config")
  cd $dir 
  IFS=/ 
  path=($PWD)
  list=$(printf "%s@%s" ${path[-1]} ${path[-2]})
  echo "processing $list..."
  cat config| perl -n000e 'while (<STDIN>) {print if /^owner$/mg}' > owner.dump
  cat config| perl -n000e 'while (<STDIN>) {print if /^editor$/mg}' > editor.dump
  /usr/local/sympa/bin/sympa.pl --restore_users --list=$list --role=owner,editor  
done
```
It would make sense that the upgrade process does reload owners+editors from config files a last time; don't you think so?

**Comment by ikedas** [comment]
At lease looking the source, owner/editor in config files are migrated (since 6.2.33b.1):
https://github.com/sympa-community/sympa/blob/4e01624022c0532dba96c96455936d455ec19c10/src/lib/Sympa/Upgrade.pm#L1794-L1810

**Comment by salaun-urennes1** [comment]
The code you mention does not help much because 
1. it is run for closed lists only
2. it creates a dump of owners/editors, based on the config file, but does not import them in the admin_table

I suggest changing the upgrade code to 
1. create owner.dump and editor.dump for all lists
2. import these admins in admin_table

**Comment by ikedas** [comment]
Your suggestion looks right.  However, I wonder why some lists won’t sync owners/editors with db despite they were open.  I’ll investigate for a while.

**Comment by salaun-urennes1** [comment]
I did a quick test: it seems to do the job.
Thank you Soji
