### ISSUE TITLE
Language change won't affect, 6.2.18

### ISSUE THREAD

**Issue by MargoM** [sympa-community/sympa#46]
Hello!

Sympa version: 6.2.18

```
# grep "lang" /etc/sympa/sympa.conf | grep -v '#'
supported_lang	et,fi,it,fr,pl,en-US
lang    et
```

I would like to set et to default language, but still en-US is default language. Only how I can change default language is to remove the en-US from the supported_lang parameter. I would like to keep en-US also, so users can choose it from Sympa GUI.

I'dont have any robot.conf, which overrides it.

Is it bug or am I missing something?

thanks
Margo

**Comment by ikedas** [comment]
@MargoM, have you restart sympa and HTTPd?

**Comment by MargoM** [comment]
Yes, restared: spawn-fcgi, nginx, mariadb, sympa and rebooted machine, still same. Also, checking sympa site with incognito-private modes, no caching. I can see the change if I remove the en-US value.

And in incongnito mode, my user language (my preferences language tab) is overridden, there is English (US), but in database I have et.

**Comment by ikedas** [comment]
I guess your browser may prefer to en-US than et. Could you please check if Estonian precedes English in language preferece of the browser.

**Comment by MargoM** [comment]
Yes, thanks! Browser default language was English, after changing it to Estonian, now it works.

Is there anyway to ignore browser language and always use Estonian? I miss the language selection button (for example in header).

**Comment by ikedas** [comment]
Users can set language of their own by logging in and setting their preference.  When the user logged in again, their language will be applied.

When the user did not login, accessing this URL may set language to `et` temporarily:
``http://<host name>/sympa/set_lang/et``

Although this feature is not documented.

**Comment by MargoM** [comment]
Well thanks, appreciate your work. I think we can close this issue.

**Comment by MargoM** [comment]
Hello!

I am still facing with this problem. My previous solution was: 
```
# grep "lang" /etc/sympa/sympa.conf | grep -v '#'
supported_lang	et,de,es,fi,fr,it,pl,ru,sv
lang	et
```

I removed the English language from supported_lang, so even if the browser uses English language the Sympa website is still in Estonian.
Now I have a problem, that users can't select en (or en-US) language from the GUI (Language of the list). Any ideas or hacks to solve this problem, @ikedas ?

**Comment by MargoM** [comment]
Okey, but if I would like to force use always specific language? Field lang in sympa.conf works only if browser language is the same.

**Comment by ikedas** [comment]
I looked the code at glance and guessed: Sympa trys to use the language supported by browser _and_ included in `lang` or `supported_lang` parameter as much as possible.  And when any languages did not suit, uses `lang` parameter.  So, if you want to stick to single language, you may have to include only that language in `supported_lang` (and `lang`).

(My guess above is about users who have not logged-in: Once user has logged in, the language specified by their user preference page will be used. In this case they can only choose one of languages in `supported_lang`.)
