### ISSUE TITLE
Unable to sent email from external  email clients to Sympa list

### ISSUE THREAD

**Issue by ptashraf** [sympa-community/sympa#462]
We have installed and configured  Sympa 6.2.16 in Debian machine.
We can send email  from the web interface to the lists and it is ok but when we  sent a mail from another client like outlook it get failed below error
Remote Server returned '``<lists-1.test.TLD #5.1.1 smtp;550 5.1.1 <ashraf-test@lists-1.test.TLD>: Recipient address rejected: User unknown in local recipient table``
Request kind help and support.
Thanks
Ashraf

**Comment by racke** [comment]
You need to configure the mail server on your Debian machine to pass on the emails to sympa.
Please check our documentation, e.g. for Postfix: https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html

**Comment by ikedas** [comment]
Stagnating issue. Close it.
