### ISSUE TITLE
Issue with the message sent to owners to allow unsubscribing

### ISSUE THREAD

**Issue by bmarchal54** [sympa-community/sympa#469]
In the message sent to list owners to allow unsubscription, in the url, it is the owner's address that is visible and not the address of the requester.
This is disturbing because the owner thinks, wrongly, that he subscribes.
If the 'mailto' link is sent, the correct address is visible.

Version
-------
6.2.32

Installation method
-------------------
Sympa was installed with rpm 

Expected behavior
-----------------
It should be the address of the subscriber that appears.

Actual behavior
---------------

Additional information
----------------------
The template 'listowner_notification.tt2' produces the message on line 81.

**Comment by bmarchal54** [comment]
I propose the following modification of the file 'listowner_notification.tt2'.
It makes it possible to reach the list of subscriptions / unsubscribers waiting, and thus to make visible the addresses to be validated.


diff /usr/share/sympa/default/mail_tt2/listowner_notification.tt2 /etc/sympa/mail_tt2/listowner_notification.tt2
59c59
<   [% 'auth' | url_abs([keyauth,'add',list.name],{email=>user.email}) %]
---
>   [% 'subindex' | url_abs([list.name]) %]
77d76
< 
81c80
<   [% 'auth' | url_abs([keyauth,'del',list.name],{email=>user.email}) %]
---
>   [% 'sigindex' | url_abs([list.name]) %]

Cordially

**Comment by ikedas** [comment]
Email in the link is address of approver, not subscriber nor requester.  It's required by the feature.
And this link follows a confirmation page that has the link to sigindex/subindex page.

To clarify requester, you may add `[% who %]` in `listowner_notification.tt2`.

**Comment by bmarchal54** [comment]
With your solution, we can see in the message received the address of the person to subscribe / unsubscribe. 
But at the moment of validation, this one is not displayed any more. It is just said "Unsubscribe the selected addresses", without seeing on which one gives the authorization. 
In my opinion, it's quite disturbing. 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
I see. `web_tt2/confirm_action.tt2` also should display target address.

**Comment by ikedas** [comment]
Hi @bmarchal54, if possible, could you please check if [this patch](https://github.com/sympa-community/sympa/compare/6.2.40...b531c07.patch) will solve the problem?
  - This changes texts in templates, and translation would be updated later.

**Comment by bmarchal54** [comment]
Hello, 

I just tried your patch on our test server. 
When composing the sent URL, it is put an email address of one of the owners. But it is not necessarily this one who will do the action. Is this normal? 

cordially 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
> Hello, I just tried your patch on our test server. When composing the sent URL, it is put an email address of one of the owners. But it is not necessarily this one who will do the action. Is this normal? cordially

I think it's normal.  Who have done the action will be known by the other owner(s) if any.

**Comment by ikedas** [comment]
The PR has been included in 6.2.41b.1.  Thanks for reporting bug and checking fix!
