### ISSUE TITLE
Changing list owner/editor parameter, internal server error

### ISSUE THREAD

**Issue by MargoM** [sympa-community/sympa#47]
Hello!

Sympa version: 6.2.18

If changing list owner/editor parameters (profile, reception, visibility), internal server error occurs. For example changing list owner (already set) profile "privileged owner" to "normal owner". And I am able to crash fcgi (needs restart).

I can change owner/editor parameter, if changing "user" email.

```
Internal Server Error
Sympa encountered an internal error.
Please contact the listmaster.

Error: missing parameter "user" at /home/sympa/bin/Sympa.pm line 519.
Traceback

DIED: missing parameter "user" at /home/sympa/bin/Sympa.pm line 519.
 at /home/sympa/bin/Sympa.pm line 519.
	Sympa::send_notify_to_user(Sympa::List <listname@domain>, 'added_as_listadmin', '', HASH(0x65c3c70)) called at /home/sympa/bin/wwsympa.fcgi line 11847
	main::_notify_added_admin(Sympa::List::Config <listname@domain>) called at /home/sympa/bin/wwsympa.fcgi line 11609
	main::do_edit_list() called at /home/sympa/bin/wwsympa.fcgi line 1680
```

I tried it in https://demo.sympa.org/sympa, here it works fine.

Thanks

**Comment by ikedas** [comment]
This issue is duplicate of #37.

**Comment by MargoM** [comment]
Ohh well, I tried to check if this problem is already here... Thank you again ikedas!
