### ISSUE TITLE
Bounce errors of subscriber can't be reset after e-mail address change

### ISSUE THREAD

**Issue by dboehmer** [sympa-community/sympa#472]
Version
-------
Sympa 6.2.24

Installation method
-------------------
Sorry, I don't know because this is someone else's system.

What I have done
------------------

* received e-mail about subscriber bouncing too often
* asked new e-mail address from this person and changed the subscriber's e-mail address as list admin
* then tried to reset the bounce error counter for this subscriber

Expected behavior
-----------------
Any of these in decreasing order of preference:

1. number of bounces is automatically zero after setting new e-mail address
1. button for resetting acts on old e-mail address
1. on the reviewbouncing page the bounces for the old address are listed separately and can be explicitly reset 

Actual behavior
---------------
* *Reset errors* button doesn't work neither on subscriber page nor on list's reviewbouncing page
* error message:

> ERROR (resetbounce) - E-mail address <new address> was not found in list <list name>. 

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @dboehmer,

> ## Expected behavior
> Any of these in decreasing order of preference:
> 
> 1. number of bounces is automatically zero after setting new e-mail address
> 2. button for resetting acts on old e-mail address
> 3. on the reviewbouncing page the bounces for the old address are listed separately and can be explicitly reset

What benefits by resetting bounce informaton of older address (in case of 2. or 3. above)?  They are no longer  a subscriber of the list.

With current behavior, I think bounce information is (maybe) took over by new address, and anyways owner can reset information of this new address.

**Comment by ikedas** [comment]
I understood.  I can't figure out why you got an error message containing the old address, too.
Anyway, I'll close this issue at present.  If you encounter the same behavior of Sympa, please reopen it.
Thanks for information!
