### ISSUE TITLE
Bug in logic. Password is in md5 format, not rehashing

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#489]
Log messages when adding a new subscriber to a mailing list through WWSympa:

Dec  2 17:06:49 localhost wwsympa[13577]: err main::#1576 > main::do_add#7203 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::add::_twist#137 > Sympa::User::save#203 > Sympa::User::add_global_user#741 Bug in logic. Password is in md5 format, not rehashing
Dec  2 17:06:49 localhost wwsympa[13577]: err main::#1576 > main::do_add#7203 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::add::_twist#137 > Sympa::User::save#203 > Sympa::User::update_global_user#648 Bug in logic: Password is in md5 format, not rehashing

(Line numbers might be a bit off due to some logging changes in the module).

Version
-------

 6.2.37b.2

Installation method
-------------------

Ansible

**Comment by ikedas** [comment]
This is introduced on PR #398. I guess this may be related to issue #167 (not surely).
I wish it would be kept before release of 6.2.38.

**Comment by ikedas** [comment]
Tentative change has been reverted. Close.
