### ISSUE TITLE
smtpc build warnings

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#50]
Hi,

gcc is reporting warnings while building smtpc:

make[2]: Entering directory '/builddir/build/BUILD/sympa-6.2.19b.1/src/smtpc'
  CC       smtpc.o
  CC       sockstr.o
smtpc.c: In function 'parse_options':
smtpc.c:229:28: warning: comparison between pointer and zero character constant [-Wpointer-compare]
       if (*p == ':' && ++p != '\0')
                            ^~
smtpc.c:229:24: note: did you mean to dereference the pointer?
       if (*p == ':' && ++p != '\0')
                        ^~
smtpc.c:272:28: warning: comparison between pointer and zero character constant [-Wpointer-compare]
       if (*p == ':' && ++p != '\0')
                            ^~
smtpc.c:272:24: note: did you mean to dereference the pointer?
       if (*p == ':' && ++p != '\0')
                        ^~
This is with sympa 6.2.19 beta1 but the warnings were already in 6.2.18.

Also, in 6.2.19 beta 1, smtpc is not installed anymore to libexecdir but to bindir. Is that expected ?

Regards,
Xavier

**Comment by ikedas** [comment]
@xavierba , I was astonished to see my gcc had been missing these malicious typos. It should be fixed:

- https://github.com/sympa-community/sympa/compare/sympa-6.2...ikedas:sympa-6.2

> Also, in 6.2.19 beta 1, smtpc is not installed anymore to libexecdir but to bindir. Is that expected ?

It is intended: https://github.com/sympa-community/sympa/commit/a220ee7f2dadadea1dab7ca8a5d3981d286d984a . To keep compatibility to earlier version, `--bindir=(libexec directory)` have to be added to configure option.

**Comment by xavierba** [comment]
I can confirm the smtpc build warnings are now gone, thanks.
Also, thanks for the hint about smtpc in bindir rather than libexecdir.

**Comment by ikedas** [comment]
Merged. Thanks for reviewing & confirming. This issue is closed.
