### ISSUE TITLE
Long request email in message_report

### ISSUE THREAD

**Issue by mathieuroquefort** [sympa-community/sympa#502]
In the file message_report.tt2, there are some occurences of the message 
`[%|loc(list.name,list.host)%]For further information, please contact %1-request@%2[%END%]`

But if we have a quite long list name and a quite long list host, the request email ends up being quite long itself (40 chars easily), and the line has more than 76 chars. As the address contains an hyphen, it is cut in the middle of the email, and users cannot click it. Even copying and pasting the email becomes complicated for "normal" users.

A solution would be to introduce a line break before the address.

Version
-------
Sympa 6.1.17 / CentOS 6.10

Installation method
-------------------
?

Expected behavior
-----------------
Pour plus de détails, contactez
test-discussion-request@listes.secourspopulaire.fr

Actual behavior
---------------
Pour plus de détails, contactez test-discussion-
request@listes.secourspopulaire.fr

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @mathieuroquefort,

I guess (but didn't confirm) `<test-discussion-request@listes.secourspopulaire.fr>` may prevent line folding.

**Comment by mathieuroquefort** [comment]
You mean adding < and > before and after the email ?
But if I do this in the code, translation won't work anymore.

**Comment by ikedas** [comment]
Yes, changes on templates will break translations for a while.  But at once the changes were included in the codebase, appropriate fixups will be made on translation catalog.

**Comment by mathieuroquefort** [comment]
So, I shouldn't make any change in my installed version, but wait until it is changed in a new version ?

**Comment by ikedas** [comment]
To avoid breakage of running site, you can download source of catalog, modify it and install it for your site.  We are sorry that we have not update [documentation about translationwork](https://translate.sympa.org/pages/help)

**Comment by ikedas** [comment]
@mathieuroquefort, could you please apply [this patch](https://github.com/sympa-community/sympa/commit/e20865f.patch) to check if the problem will be solved?

**Comment by mathieuroquefort** [comment]
I did not test yet...

**Comment by ikedas** [comment]
@mathieuroquefort, I was too hasty. Please check the patch on your server.
The patch will be included in the next release planned in this Friday.

**Comment by racke** [comment]
You can strip off parts of the path inside the patch file with the -p parameter. So if you want just to strip off "src", it would be `patch -p1`.
