### ISSUE TITLE
Add a global quiet_subscription setting which enforce the "quiet add" policy

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#503]
Related to https://github.com/sympa-community/sympa/pull/500

Expected Behavior
-----------------
Have a setting in `sympa.conf` allowing to enforce the "quiet add" policy, either for forcing quiet subscriptions (in enterprise for ex.) or disabling quiet subscriptions (public Sympa server, have to respect GDPR).

Default behavior will be no enforcing, so quiet add is list's owner's choice.

Current Behavior
----------------
There is no global policy, it's always list's owner's choice.

Possible Solution
-----------------
Have this setting in `sympa.conf`:
`quiet_subscription off|on|optional`

`optional` being the default

Context
-------
See "Expected behavior".

**Comment by ikedas** [comment]
I looked PR#509 and it is nice.  If there are no more ideas, it would be merged.  This issue is tagged milestone 6.2.40.
