### ISSUE TITLE
Deprecate sympa_wizard.pl

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#508]
Expected Behavior
-------------------
`sympa_wizard.pl` will be deprecated, and reasonable alternative(s) will be suggested or provided.

Current Behavior
-----------------
`sympa_wizard.pl` is provided to install dependent modules, edit `sympa.conf` and so on.

Possible Solution
-----------------
Currently, `sympa_wizard.pl` provides following functions.  We have to find or implement their alternatives.

  - [x] `sympa_wizard.pl`
    Function: Edit current Sympa configuration.

    ⇒  Users may edit sympa.conf manually, or may use the other functions to modify configuration.

  - [x] `sympa_wizard.pl` `--batch` _key_=_value_ ...
    Function: Edit in batch mode.  Arguments would include pairs of parameter name and value.

    ⇒  Implement new function such as:

    ~`sympa.pl` `--conf` `key=value` ...~

    `sympa` `config` _key_=_value_ ...

  - [x] `sympa_wizard.pl` `--check`
    Function: Check CPAN modules needed for running Sympa.

    ⇒  Currently `cpanfile` is available (See [details](https://sympa-community.github.io/manual/install/install-dependent-modules.html#using-cpanminus-cpanm)).  Or, users may use package systems they prefer.

  - [x] `sympa_wizard.pl` `--create` [ `--target` _file_ ]
    Function: Creates a new sympa.conf configuration file.

    ⇒  Users may compose sympa.conf manually, or may use the other functions to create and modify configuration.
    ⇒ With consensus made on #601, implement new function such as:

    `sympa` `config` `create` [ `--config` _file_ ]

  - [x] `sympa_wizard.pl` `--display`
    Function: Outputs all configuration parameters.

    ⇒  Implement new function such as:

    ~`sympa.pl` `--conf`~

    `sympa` `config` `show`

Context
--------
What `sympa_wizard` aimed were providing easy way to install dependent modules and creating initial configuration relying only upon Perl core.  However, nowaday `sympa_wizard.pl` is not so flexible as users need.

---
EDIT: 2021-12-11 Changed command line of new functions.

**Comment by racke** [comment]
I agree with the deprecation, but we need to keep in mind that it is used in the postinst script from the Debian package.

**Comment by ikedas** [comment]
I consider it. I think of preparing a [minimal `sympa.conf`](https://github.com/sympa-community/sympa/compare/sympa-6.2...ikedas:minimal_sympa.conf#diff-aa78bdb5f36a8bd9f3220479f6d41711) and installing it.

**Comment by dverdin** [comment]
I agree with the deprecation too. People installing Sympa for the first time tend to validate default value in batch. Plus the wizard was somewhat creating a confusion with configure.
