### ISSUE TITLE
"subject_list" field in "list_table" table is NULL

### ISSUE THREAD

**Issue by vincent-lucas** [sympa-community/sympa#51]
Hello,

Since an update from 2.1.16 to 6.2.16 version, the "subject_list" field in "list_table" table is set to "NULL" for new created lists and is no more updated when changing the subject for an existing list.

Is this a normal new behavior ? Is the list subject only stored into the list config file ?

Best regards,
Vincent

**Comment by ikedas** [comment]
Hi,
> Is this a normal new behavior ? Is the list subject only stored into the list config file ?

I think it is normal. On 6.2.x, original subject is stored only into `config` file, and `searchkey_list` field in list_table holds a key for case-insensitive matching.

Regards,
-- Soji

**Comment by vincent-lucas** [comment]
Hello Soji,

Thank you for the response. I did not see this change in the release notes.

Regards,
Vincent
