### ISSUE TITLE
connexion web interface

### ISSUE THREAD

**Issue by larok972** [sympa-community/sympa#518]
Hi,
I've met a problem when i try to login in web interface.  I Click on "Email adress" and the window disappear every time, no way to write in the field. I don't understand the origin of this problem. is it a wrong apache setting, a bug? 

Thanks in advance for your help

**Comment by ikedas** [comment]
Hi @larok972,
What is the version of Sympa you are using?

**Comment by larok972** [comment]
Good morning, 
I migrated settings and datas from a 6.2.12 version to a new server 6.2.22.
Kindest

**Comment by ikedas** [comment]
You would be better to upgrade to more recent version.

You mean that dorpdown menu containing login form is hidden:
![login-6 2 24](https://user-images.githubusercontent.com/5743546/50875676-cba10000-140c-11e9-9a39-c8e6bc01ed6d.png)

Recent version (6.2.34 and later) gave up login form in dropdown menu and put a button in the menu to open login page:
![login-6 2 38](https://user-images.githubusercontent.com/5743546/50875761-26d2f280-140d-11e9-85a1-4ed695e8d63f.png)

**Comment by larok972** [comment]
Good morning,

Exactly i clic on "connexion", the form appears but when i try to write the form disappear.

kindest

**Comment by ikedas** [comment]
Good evening.
Okey, can you try recent version (6.2.38 is the best at present)?

**Comment by larok972** [comment]
Hi Ikeda,

I found a solution for my problem. I copied static-content from my old server to the new and it works.

Kindest

**Comment by ikedas** [comment]
Hi @larok972,

It's nice!  Thanks for sharing your experiences.

If you don't have problem anymore on your server, please close this issue.
