### ISSUE TITLE
Owner and editors edition through the command line

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa#524]
Expected Behavior
-----------------
A lot of administrators have built scripts to mass edit config files, especially for owners provisioning.

Current Behavior
----------------
These scripts are broken as of Sympa 6.2.34 due to the fact that editors and owners are now located in the database only. These are the only list parameters having such an exception.

Possible Solution
-----------------
I plan to add options to sympa.pl to manage list adminsitrators. That way, these scripts will keep on working, simply by replacing the sed or whatever command the admins were using by the relevant sympa.pl command.

These options would make usage of the new Sympa code and use the new primitives to add / replace / delete adminstrators.

Actually, this would even be an improvement to previous Sympa versions because such options would have been very usefull before, for example when somebody leaves an institution and her replacement needs to take over the leaver's list.

Here is the intended interface I want to provide:

sympa.pl --add-admin --list=<listname> --vhost=<domain> --email=<an@email> --role=<owner|editor> --visibility=<value> --profile=<privileged|normal> --reception_mode=<reception_mode> --gecos<gecos>

sympa.pl --delete-admin --list=<listname> --vhost=<domain> --email=<an@email> --role=<owner|editor>

sympa.pl --replace-admin --list=<listname> --vhost=<domain> --previous_admin=<an@email> --new_admin=<an.other@email>

In each case, the "last modified by" list parameter would contain "listmaster@domain.tld" email.

What do you think? I could do this easily and quickly using the current codebase.

Context
-------
I'm in contact with a lot of listmasters through the lists and a lot complained about the lost functionnality, while agreeing the vanishing of the cache problem was very cool.

**Comment by racke** [comment]
Wouldn't it be better to include the owners from SQL/LDAP/... like we do for subscribers?

**Comment by ikedas** [comment]
Providing Sympa::Request handler at first seems better.  It may be useful for the other components than command line (e.g. SOAP: See #526).

**Comment by racke** [comment]
Yes, definitely. That's the way to go.

**Comment by ikedas** [comment]
Hi @dverdin,

### Alternative solution

If you seek a quick solution, you'd be better to consider using dump files.

Previously administrators edited config file to change owners/moderators directly.  Instead, with current version, they may do
```
sympa.pl --dump_users --list LISTNAME --role owner,editor
(Edit owner.dump and/or editor.dump)
sympa.pl --restore_users --list LISTNAME --role owner,editor
```
Contents of `owner.dump` and `editor.dump` are the same as `owner` and `editor` paragraphs in `config` with earlier versions.  Editing them can be easier for administrators than learning new command line tools.

**Comment by dverdin** [comment]
Hi @ikedas ,
That's a perfectly valid solution indeed! And I'll propose it to the French mailing list where the question arose first.
I had not spotted this option before. sorry. Otherwise, I wouldn't have bothered you.

That questions the pertinence of my proposal. If the primary problem has a solution, it might be pointless to develop it. Then again, there is the correlated issue with SOAP/REST API. And for it, we need the Request Handler, that could be reused for the command line.

So I'll think I'll still do it, following your proposal of a Request Handler. But it's good to knwo there is short term solution - that could perfectly remain the long term solution.

Thanks, Soji!

**Comment by dverdin** [comment]
Dear all,
I just committed a request handler for adding list admins.
Do you agree with how I did it?
Any comment would be appreciated.
Thanks!

**Comment by dverdin** [comment]
Aaaaaaand I forgot to put a link towards the commit...
Here it is: https://github.com/dverdin/sympa/commit/db273b5bdc5b050cb971c0ee9a63fded173628c6

**Comment by ikedas** [comment]
I think `add` and `del` are sufficient. `replace` may no required.

BTW, you'd be better to work on cleaner branch on your fork.
https://github.com/sympa-community/sympa/compare/sympa-6.2...dverdin:add_list_admin_request_handler
Due to (no-ff) merge, your branches on your fork is separated from master repo.
https://github.com/sympa-community/sympa/network

**Comment by dverdin** [comment]
That's certainly a possibility.
However, as these data are in database, it feels easier to run an "update" query than a bunch of call to add and del. And also, replacing is different from adding or deleting from an end user point of view. That's why I wanted to implement this function explicitely.
But this can be seen later.

**Comment by dverdin** [comment]
Dear all,
I fixes my branch. that looks better, doesn't it? https://github.com/sympa-community/sympa/network
Here is the new commit: https://github.com/dverdin/sympa/commit/e80f799bcf0775a72699276891f2170cce9ecb28

I'll keep working on this basis.
Regards,
