### ISSUE TITLE
"Authorization rejected" when unsubscribe from a list 

### ISSUE THREAD

**Issue by UniversitaPerugiaSysAdm** [sympa-community/sympa#531]
When I try ti unsubscribe from a list (configured with open_notify parameter) I obtain the following error in 
the browser:
ERROR(confirm_action) - Authorization rejected. Maybe you forgot to log in?

From sympa.log I can see:
....CSRF token mismatch: in="" session="27d19461800de3cd6f9eb3269402d68b"
.....Missing required parameters for action "confirm_action"

Version
-------

6.2.38-1.20181221.RHEL6.x86_64

Installation method
-------------------

rpm from sympa-ja.org repository

Expected behavior
-----------------

I should unsubscribe from the ML.

Actual behavior
---------------

ERROR(confirm_action) - Authorization rejected. Maybe you forgot to log in?

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @UniversitaPerugiaSysAdm,

Please update to 6.2.40 released Saturday.  For details please see #527.
