### ISSUE TITLE
Ownoreditor restriction

### ISSUE THREAD

**Issue by psvillanueva2015** [sympa-community/sympa#545]
Hi,

We are currently using Sympa 6.2.22 version. I just observe that when adding new owner and we set the restriction to "ownderoreditor" and try to send an email to the lists we got delivery failure"Delivery not authorized, message refused" but after adding the on the lists owner and restarted the sympa service mail got delivered without any issue. 

Thank you,
Pete

**Comment by ikedas** [comment]
Hi @psvillanueva2015,

Can you show us the source of "owneroreditor" scenario?

**Comment by psvillanueva2015** [comment]
Hi Ikeda,

see below lists config

visibility noconceal

reply_to_header
apply forced
value sender

serial 10

subject all-einfochips is an Automatic List of users located at EIC.

subscribe owner

clean_delay_queuemod 15

editor
email corporatecommunications@sample.com
reception nomail
visibility noconceal

editor
email corporatecommunications@sample.com
reception nomail
visibility noconceal

unsubscribe open_notify

process_archive on

topics Locations

creation
email sympa.message@sample.com
date 19 Dec 2011 at 11:28:13
date_epoch 1324312093

update
email sympa.message@sample.com
date_epoch 1548989419

review private

default_user_options
reception mail
visibility noconceal

*send owneroreditor*

status open

remind listmaster

available_user_options
reception mail,nomail,txt,urlize

rfc2369_header_fields archive,help,owner,post,subscribe,unsubscribe


owner
email help.desk@sample.com
profile privileged
reception mail
visibility noconceal

owner
email matthew.saints@sample.com
profile privileged
reception mail
visibility noconceal
gecos MATTHEW SAINTS

owner
email ROLANDO@sample.com
profile privileged
reception mail
visibility noconceal
gecos ROLANDO

owner
profile privileged
reception mail
email help_desk@sample.com
visibility noconceal

include_sql_query
db_name prodmdm
name Prodmdm
db_port 1521
host larrie.sample.com
passwd 12345677
db_type Oracle
user SYMPA
sql_query select DISTINCT EMAIL_ADDRESS from MDM.MDM_SYMPA_VIEW WHERE
UPPER(TRIM(LOCATION_NAME)) = 'EINFOCHIPS, AHMEDABAD'  AND ACTIVE_FLAG='Y'
and NOT EMAIL_ADDRESS IS NULL

Thank you,
Pete

**Comment by psvillanueva2015** [comment]
here is the content of the send.owneroreditor scenari

title.getext restricted to approved senders

is_editor([listname],[sender])    smtp,smime,md5 -> do_it
is_owner([listname],[sender])     smtp,smime,md5  -> do_it
true()                            smtp,smime,md5  -> reject(reason='send_editor')

**Comment by ikedas** [comment]
@psvillanueva2015, thanks for presenting content of `send.owneroreditor`.  Content of `config` you posted may be deleted.

Can you check recent version of Sympa (6.2.40 or later is better)? I looks like the problem on cache fixed on 6.2.36 and later.

**Comment by psvillanueva2015** [comment]
Thank you
