### ISSUE TITLE
The translation server shows a wrong number of incomplete strings

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#554]
Two weeks ago I completed the translation of all the strings into Spanish and Galician but the translation server is still showing that there are a number of strings incomplete and several others with errors (in both languages). When I click on these numbers it tells that there are no results available. 

Furthermore, I wonder if there is a way to delete the suggestion on unit #11300: https://translate.sympa.org/es/web_help/translate/#filter=suggestions

Is there a way to correct this?

Thank you very much.
Best regards,
Luis A.

**Comment by ikedas** [comment]
@qosobrin, I have realized what you reported: Pootle (a server software to manage translation) fails to update counting of strings to be corrected.

This looks not affecting content of translation.  It will be corrected at the time of the next synchronization between translation site and Sympa sources.  Thanks for your patience.

**Comment by qosobrin** [comment]
The problem seem to be recurring. I close this request.
