### ISSUE TITLE
Vacation message to Message templates

### ISSUE THREAD

**Issue by MargoM** [sympa-community/sympa#56]
Hello!

I would like to add Vacation message to Message templates, so users can change it easily.
Could someone give some more detailed info, http://www.sympa.org/contribs/vacation. My test experiment was unsuccessful :(

Or this feature is planned to be in Message templates in near future?

Thanks

**Comment by ikedas** [comment]
As far as I know, anyone don't have plan to add that feature to Sympa.

If no further information will not be givin in this month, I'd like to close this issue.

**Comment by ikedas** [comment]
Stagnated issue. Closed for now.
