### ISSUE TITLE
import.tt2: non-working line break in toolip

### ISSUE THREAD

**Issue by 1resu** [sympa-community/sympa#562]
[import.tty](https://github.com/sympa-community/sympa/blob/220c12b2ff1a3d05bd172b4c3904205c9e46f181/default/web_tt2/import.tt2#L8) defines a line break within a tooltip by the `<br/>` html tag. This doesn't work.

Using `&#013;` instead of `<br/>` should do the trick. Or you can insert a real line break - but this results in changing all language files.

**Comment by ikedas** [comment]
My browsers (Firefox 57, Chrome 72 and IE 11) ignored `&#13;`.  `&#13;&#10;` looks better.  Could you please check [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/563.patch)?

> ... - but this results in changing all language files.

No problem.  translation catalog will be adjusted at the time of the next release.

**Comment by 1resu** [comment]
The patch works with my setup (Sympa 6.2.40, Firefox 60.5, Chromium 72) except for the second line break. But this also happens with my initial comment's "solution" (`&#013;`).

I'm not sure why this happens.

**Comment by ikedas** [comment]
I mislead.  The lines looked broken just by word wrapping (CR was ignored and LF was replaced with space by browsers).

Could you please apply this [additional patch](https://github.com/sympa-community/sympa/commit/9f2b36cf6d5e37e111d429d1b652ec59a0fc34e8.diff)?

**Comment by 1resu** [comment]
The patch works like expected. Thanks for your support!

**Comment by ikedas** [comment]
@1resu, thanks for confirming! I'll merge the patches. This issue will be closed.
