### ISSUE TITLE
Data format for nosync_time_ranges

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#564]
Any one can provide more information on the format to be used in the nosync_time_ranges variable? The information provided in https://sympa-community.github.io/manual/man/list_config.5.html does not seem very clear to me.

Format: /$time_ranges/

Thank you very much.
Best regards,
Luis A.

**Comment by ikedas** [comment]
Hi @qosobrin,

`$time_ranges` is defined in source as following:

https://github.com/sympa-community/sympa/blob/9d31cceb2e6301d551cfa83995b43e5dca0f79dc/src/lib/Sympa/Regexps.pm#L64-L66

It means:

| symbol | regexp | example(s) |
| --- | --- | --- |
| $time | /\[012\]?\[0-9\](?:\:\[0-5\]\[0-9\])?/ | "`4`", "`12`", "`00:00`", "`23:45`" |
| $time_range | /$time-$time/ | "`4-8`", "`12-13`", "`14:56-23:45`" |
| $time_ranges | /$time_range(?:\s+$time_range)*/ | "`4-8 12-13 14:56-23:45`" |

**Comment by qosobrin** [comment]
Thank you for the precise answer.

Regards.
