### ISSUE TITLE
Problems with syncronization of ldap members

### ISSUE THREAD

**Issue by bertaviader** [sympa-community/sympa#568]
Hello,

We installed the version 6.2.16. Everything was fine until the users began to add members to the list. There is a problem with the ldap configuration when the result returns more than 1000 members. The problem is this one: 
Sympa::List::_include_users_ldap#5391 LDAP search (single level) failed: (4) Sizelimit exceeded
For this Sympa sends every hour a mail error to the list administration, I have the default_ttl to 86400 seconds. But it seems that is not working.

Can you help me? What I'm doing wrong?
Thank you,
Berta

**Comment by racke** [comment]
That is most likely an error message from the LDAP server. Maybe it is possible to increase the size limit there.

**Comment by qosobrin** [comment]
Is this problem related to #57?

**Comment by racke** [comment]
Paging should be helpful in this situation, yes.

**Comment by bertaviader** [comment]
Sorry I didn't explain myself correctly, the main problem was the sending every hour of the error. I check the solution of another thread and didn't correct the problem immediately, after two restarts it seems now it's working. Thank you anyway. I will close now the question.

Thanks you!
Berta
