### ISSUE TITLE
List owners and Listmaster can't moderate messages

### ISSUE THREAD

**Issue by tsarevpp** [sympa-community/sympa#569]
Hi there, I recently installed sympa 6.2.40 and this was an upgrade from 6.2.16. It was a fresh install and I transferred all of the data from the old install.
However, after importing the database it seems like the listmster (me) and some list owners can't moderate their posts in the lists. For example - there is a moderated list in which only the moderator can approve messages for the digest and I can see that using the impersonate option. But I can't for some reason. Can you give any ideas what could have caused that and how it can be solved?

By the way, when importing the DB (MySQL) I did a regex for datetime and replaced all ocurrances of my datetimes with UNIX_TIMESTAMP($0) to fulfill the epoch change.

**Comment by dverdin** [comment]
What is the scenario used for this list? And is it the same as the one you had before?
cheers!
David

**Comment by ikedas** [comment]
Stagnating issue. Close for now.

**Comment by tricovictor** [comment]
> Hi there, I recently installed sympa 6.2.40 and this was an upgrade from 6.2.16. It was a fresh install and I transferred all of the data from the old install.
> However, after importing the database it seems like the listmster (me) and some list owners can't moderate their posts in the lists. For example - there is a moderated list in which only the moderator can approve messages for the digest and I can see that using the impersonate option. But I can't for some reason. Can you give any ideas what could have caused that and how it can be solved?
> 
> By the way, when importing the DB (MySQL) I did a regex for datetime and replaced all ocurrances of my datetimes with UNIX_TIMESTAMP($0) to fulfill the epoch change.

Were you able to solve the problem? I have the same situation but with Postgres.

**Comment by racke** [comment]
@tricovictor Did you try to update to a more recent version of Sympa?

**Comment by colorninja** [comment]
@tricovictor I wasn't able to get it solved, but it got resolved in some of the updates.

**Comment by tricovictor** [comment]
@racke No, it is the one that comes in Debian Buster by default.

**Comment by ikedas** [comment]
@colorninja , please read "[Upgrading Sympa in place](https://sympa-community.github.io/manual/upgrade/in-place.html)".
