### ISSUE TITLE
After login, the last content (image), not always the last page, is shown

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#580]
Version
-------

At least
- 6.2.13
- 6.2.40

Installation method
-------------------

- 6.2.13: Source tar.gz
- 6.2.40: RPM (Sympa-JA.org)

Expected behavior
-----------------

1. Visit a page of public archive on which an image is embedded, e.g. [this page](https://listes.renater.fr/sympa/arc/sympa-announce/2019-03/msg00001.html).
2. Perform login.
3. The page you have visited at step 1 will be shown.

![スクリーンショット 2019-04-01 5 15 37](https://user-images.githubusercontent.com/5743546/55294472-5c501080-543d-11e9-88bc-72e952885deb.png)

Actual behavior
---------------

The embeded image is shown, i.e. [this](https://listes.renater.fr/sympa/arc/sympa-announce/2019-03/pngukcdlPq1E1.png).
![スクリーンショット 2019-04-01 5 16 08](https://user-images.githubusercontent.com/5743546/55294479-75f15800-543d-11e9-8ee2-fbdfc8d6c2d9.png)

Additional information
----------------------

When login is performed, user will be redirected to the last page they visited before login. In this situation, Sympa looks confusing between embedded images and base page.

EDIT (by @dverdin): I added the installation method of the 6.2.13 you tested. It's RENATER's, installed from sources.

**Comment by dverdin** [comment]
Just an intuition: the image was probably originally loaded _after_ the archive page. If Sympa redirects to the _last_ content it delivered, it may automatically redirect to the image.
This should be checked, of course.
