### ISSUE TITLE
Extra space at the end of line in topics.conf

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#581]
Version
-------

6.2.40

Installation method
-------------------

RPM (Sympa-JA.org)

Actual behavior
---------------

If `topics.conf` has this content:
``` code
other
visibility conceal␣
```
(``␣`` is a space)

Each time the users access to web interface, this error message is shown in the log:
``` code
Unable to find scenario file "topics_visibility.conceal "
```

**Comment by dverdin** [comment]
To fix this, we might change Conf.pm to ignore trailing spaces.

**Comment by racke** [comment]
Yeah good idea. As a rule, always strip surrounding spaces.

**Comment by dverdin** [comment]
Damn. We seem to be doing it already. It was too easy...
https://github.com/sympa-community/sympa/blob/2766e0ef8a536e9726757865cfc8e9050738edcf/src/lib/Conf.pm#L1737
