### ISSUE TITLE
Message-Id broken with anonymous sender

### ISSUE THREAD

**Issue by adam12b1** [sympa-community/sympa#587]
If the anonymous_sender setting is used, the Message-Id that Sympa constructs is extremely basic ("<listname.N@anonymous>") and actually creates problems, because the "N" increment will repeat itself each month - it will not be unique over time. As a result, various email clients (including Apple Mail, but others too) will incorrectly display a previous month's message when a new one is received, thinking they are identical. And that is fair enough, as this is a violation of **RFC 2822**:

> The message identifier (msg-id) itself MUST be a globally unique
> identifier for a message.  The generator of the message identifier
> MUST guarantee that the msg-id is unique.

The fix is very simple: Instead of creating a poorly formed Message-Id, Sympa should simply *remove* that header, which will result in the MTA creating a new true unique one.

The diff on src/lib/Sympa/Spindle/TransformIncoming.pm would be:
```
85,87c85
<         my $new_id =
<             $list->{'name'} . '.' . $message->{xsequence} . '@anonymous';
<         $message->replace_header('Message-Id', "<$new_id>");
---
>         $message->delete_header('Message-Id');
```

**Comment by ikedas** [comment]
Hi @adam12b1,

> ... because the "N" increment will repeat itself each month ...

I feel it curious.  "N" is taken from [`stats` file](https://sympa-community.github.io/manual/customize/basics-list-config.html#other-files) by each list.  "N" is always incremented but not rewound.   Could you please check if something overwrites this file?

**Comment by adam12b1** [comment]
Ah geez - thanks Soji, you got it! It turns out we are resetting the stats file to zeroes every month for billing purposes, so that's why the counter resets and repeats. Not Sympa's fault at all. My apologies for the noise!

Closing this issue.
