### ISSUE TITLE
MHonArc depedency not detected

### ISSUE THREAD

**Issue by wouldsmina** [sympa-community/sympa#59]
OS : DEBIAN 9
SYMPA 6.2.16 from debian package repository
MHonArc v2.6.19+ from debian package repository

sympa_wizard --check don't detect MHonArc : MHonArc::UTF8 n'a pas été trouvé sur le sytème. 

wwsympa work like a charm, archives are generated with MHonArc v2.6.19+.

**Comment by racke** [comment]
Maybe because it is installed in `/usr/share/mhonarc` which is not in `@INC` usually?

**Comment by ikedas** [comment]
I suppose it may be dealt with by packagers. FYI, RPM solved it by applying [a patch](https://github.com/ikedas/sympa-rpm/blob/master/SOURCES/sympa-6.2a.40-r11708-wizard-mhonarc.patch).

**Comment by racke** [comment]
@ikedas thanks for the pointer, we can do that on the Debian end too.

**Comment by wouldsmina** [comment]
the patch work (without uppercase).

**Comment by racke** [comment]
Submitted as Debian bug (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876272), thus closing here.
Thanks @wouldsmina for the report.
