### ISSUE TITLE
Q: Why is the Debian package so out of date?

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#591]
In the institution where I work we use the Debian package for Sympa. At this moment Debian is providing version 6.2.16 of Sympa. Over the time, as Sympa released new versions, I saw some of them going into Sid and Buster versions, but they never went to the Stretch (current stable) version. Anyone can provide any information on the reason for this behaviour?

Thank you very much.
Best regards,
Luis A.

**Comment by racke** [comment]
This is normal behaviour for Debian stable releases - they usually don't get new versions of packages.

**Comment by qosobrin** [comment]
Thank @racke for your answer. I have recently finished the translation of Sympa debian package into Galician (it was incomplete). Do you know if there is a way to push that translation into the debian package or they only allow error correction?

**Comment by mamair** [comment]
For some packages newer versions are available as backports, but not for sympa :-( https://backports.debian.org/

**Comment by sumpfralle** [comment]
> Do you know if there is a way to push that translation into the debian package or they only allow error correction?

Between major release (every two years) there are [Point Releases](https://wiki.debian.org/DebianReleases/PointReleases) published every two months. They contain security fixes and corrections of grave bugs. Translation updates are probably not within that scope.

As @mamair suggested: a backports package could be useful for administrators that want to upgrade sympa within a stable release of Debian. Contributions to the [Debian Sympa Team](https://salsa.debian.org/sympa-team) are surely welcome and would increase the probability of regularly updated backports packages (if there is an actual demand).

But I guess, this is out of scope for this issue tracker. Thus I would recommend to close this ticket.

**Comment by qosobrin** [comment]
OK, thank you everybody for you answers. I'm closing the ticket.
