### ISSUE TITLE
ldap ssl connexion no error message

### ISSUE THREAD

**Issue by goudal-emmk** [sympa-community/sympa#596]
Version
-------

Sympa 6.2.41b.2

Installation method
-------------------

from source

Expected behavior
-----------------

I had some errors in the ldaps configuration (fbad ssl version, and some problem with certificate chain. 
The only error message is that the connexion failed.

Actual behavior
---------------

Errors are generated either by Net::LDAP module or IO::Socket::SSL but none of these errors are treated by sympa who just put a generic message error "connexion failed" and not the precise message from the preceding modules.
What I would expect is to have these message repported by sympa

Additional information
----------------------

**Comment by goudal-emmk** [comment]
Question ? 
It's just a bug concerning error messages not beeing caught and displayed !

**Comment by racke** [comment]
I concur about this issue being a bug. The actually LDAP error should bubble up to the Sympa logs.

**Comment by ikedas** [comment]
@goudal-emmk.  Could you please show us detailed information?  For example logs when error occurred (we at least have to know when does it occur).

**Comment by racke** [comment]
#1045 might be helpful here.
