### ISSUE TITLE
Conf::Conf{'host'} used in List.pm but domain used in sympa.conf

### ISSUE THREAD

**Issue by goudal-emmk** [sympa-community/sympa#598]
Version
-------

 Sympa 6.2.41b.2

Installation method
-------------------

Source

Expected behavior
-----------------

Either an error message : host not configured in sympa.conf
or no error at all... explanation below

Actual behavior
---------------

When calling the code for conditional_condition, there is a call to List::new which calls search_list_among_robots which use the 'host' parameter 
 if (-d $Conf::Conf{'home'}.'/'.$listname) {
        return $Conf::Conf{'host'};
    }
The problem is that in the sympa.conf the default robot domain is in the domain attribute, not the host one (and the host parameter is not listed in the sympa.conf given in the distribution).

What would be nice is
- either to use domain to return the robot domain
- either test the value of the $Conf::Conf{'host‘} and rise an error if the value is not defined..

Additional information
----------------------

**Comment by ikedas** [comment]
`host` is the thing like synonim of `domain` for compatibility to earlier version of Sympa.  Anyway `host` should be deprecated.  I'll check the code and clean tis old thing away.

**Comment by ikedas** [comment]
I couldn't confirm there are lines reported by this issue.  I'll close it by now.  Please feel free to reopen it if necessary.
