### ISSUE TITLE
Missing columns in sympa's admin_table

### ISSUE THREAD

**Issue by A3TH3RIUS** [sympa-community/sympa#600]
**Version**
From Sympa 6.0b.2 to Sympa 6.2.41b.2

**Installation method**
From Source

**Expected behavior**
It seems that when the database was updated by the `sympa.pl --upgrade` command, a column in the admin_table table was deleted, the **date_admin** column.

**Actual behavior**

After updating the database using `sympa.pl --upgrade` when I wanted to modify a list on the web interface, I received this error in the logs:

```
 wwsympa[9393]: List::get_first_admin_user() Unable to execute SQL statement "SELECT user_admin AS email, comment_admin AS gecos, reception_admin AS reception, visibility_admin AS visibility, UNIX_TIMESTAMP(date_admin) AS date, UNIX_TIMESTAMP(update_admin) AS update_date, info_admin AS info, profile_admin AS profile, subscribed_admin AS subscribed, included_admin AS included, include_sources_admin AS id, REVERSE(SUBSTRING(user_admin FROM position('@' IN user_admin) FOR 50)) AS dom FROM admin_table WHERE (list_admin = 'listes' AND robot_admin = 'listes.example.fr' AND role_admin = 'owner' ) ORDER BY dom" : Unknown column 'date_admin' in 'field list'
```

To correct this problem, I had to manually alter the admin_table table and add the date_admin column to it.

**Comment by ikedas** [comment]
Hi @A3TH3RIUS,
It looks weird for me, because Sympa 6.2.26 or later will never use `UNIX_TIMESTAMP` function in SQL statements.  Could you please check if recent version of Sympa has been installed in correct location?

**Comment by A3TH3RIUS** [comment]
Hi @ikedas ,
I checked that my version of Sympa is at the right place using the documentation:
[](https://sympa-community.github.io/manual/layout.html)
The only solution I have found is to manually modify the table to correct this error.

**Comment by ikedas** [comment]
Could you please check the full path of running wwsympa.fcgi program (or wwsympa-wrapper.fcgi)?

**Comment by A3TH3RIUS** [comment]
the full path of running wwsympa.fcgi program (or wwsympa-wrapper.fcgi) is /home/sympa/bin/wwsympa.fgci and /home/sympa/bin/wwsympa-wrapper.fcgi.

**Comment by ikedas** [comment]
Thanks. Could you check the years in copyright notices at the beginning of running `/home/sympa/bin/wwsympa.fcgi` script? Sympa 6.0b.2 was published in 2009 and 6.2.41b.2 was out in 2019.

**Comment by ikedas** [comment]
I forgot to write.  Could you please show the `configure` options you specified?

**Comment by A3TH3RIUS** [comment]
![wwsympa fcgi](https://user-images.githubusercontent.com/32356014/56733500-a092b000-6760-11e9-9bc2-0eaf0c97d81a.png)
And for the `configure` options i specified, the only option I specified is `--with-unitsdir=/lib/systemd/system`

**Comment by ikedas** [comment]
However, error log you showed is obviously generated by Sympa prior to 6.2 (at 6.2, List module has been renamed to Sympa::List).  I can’t figure out what is happening...

Are you accessing correct server? Web UI has been drastically changed during 6.0 to 6.2, and you will see completely different look & feel.

**Comment by A3TH3RIUS** [comment]
Yes, I am sure to access the right server. I have the old server with Sympa 6.0 and the new server with version 6.2 of Sympa. The interface of version 6.0 has a pale blue color and that of version 6.2 is with a darker blue.

**Comment by ikedas** [comment]
It's a view with recent veriosn (in Japenese language).
<img width="1141" alt="スクリーンショット 2019-04-25 23 32 01" src="https://user-images.githubusercontent.com/5743546/56744199-03ad3280-67b3-11e9-9ae5-2f386940eed9.png">

**Comment by A3TH3RIUS** [comment]
Yes, I have the same version on my new server.
![Capture du 2019-04-26 14-23-38](https://user-images.githubusercontent.com/32356014/56807277-a951b780-682e-11e9-8d75-e51bee9546ce.png)

**Comment by ikedas** [comment]
@A3TH3RIUS, could you please show some lines in the log file before and after the reported error message?

**Comment by A3TH3RIUS** [comment]
![Capture du 2019-04-29 10-09-03](https://user-images.githubusercontent.com/32356014/56883338-a93bfc80-6a66-11e9-96c1-73ac771da179.png)

Here the lines before and after the reported error.

**Comment by ikedas** [comment]
It’s hardly believable, but some modules look old. Can you please try these things?
1. Remove everything under /home/sympa/bin.
2. Install Sympa again.

**Comment by A3TH3RIUS** [comment]
Unfortunately I can not do these tests on this server because it is working normally now and will be used soon.
However, I will try to do these tests on a server clone and come back to you after that.

**Comment by ikedas** [comment]
> However, I will try to do these tests on a server clone and come back to you after that.

Thanks!

**Comment by A3TH3RIUS** [comment]
I was able to do the tests that you had asked me and I also tried the update by the sympa.pl --upgrade script. The logs returned the following errors:
![Capture du 2019-05-07 15-05-25](https://user-images.githubusercontent.com/32356014/57301633-bfd2fb00-70d9-11e9-99a8-1ee5a4b6419a.png)
Apparently when running the update, there is a series of sql queries that drop columns.

**Comment by ikedas** [comment]
Hi @A3TH3RIUS,
I think this message itself does not matter. I'll fix confusing error message on the future release.

**Comment by bv-unibs** [comment]
Hi, I've the same issue occurring during the sympa fake upgrade from 6.1.17 to 6.2.40:

notice Sympa::Upgrade::upgrade() Upgrading admin_table
err main::#890 > Sympa::Upgrade::upgrade#1835 > Sympa::DatabaseDriver::MySQL::delete_field#288 > Sympa::Database::do_query#280 Unable to execute SQL statement "ALTER TABLE admin_table DROP COLUMN date_admin": (42000) Can't DROP COLUMN date_admin; check that it exists
err main::#890 > Sympa::Upgrade::upgrade#1835 > Sympa::DatabaseDriver::MySQL::delete_field#296 Could not delete field date_admin from table admin_table in database sympa
notice Sympa::Upgrade::upgrade() Upgrading subscriber_table
err main::#890 > Sympa::Upgrade::upgrade#1838 > Sympa::DatabaseDriver::MySQL::delete_field#288 > Sympa::Database::do_query#280 Unable to execute SQL statement "ALTER TABLE subscriber_table DROP COLUMN date_subscriber": (42000) Can't DROP COLUMN date_subscriber; check that it exists
err main::#890 > Sympa::Upgrade::upgrade#1838 > Sympa::DatabaseDriver::MySQL::delete_field#296 Could not delete field date_subscriber from table subscriber_table in database sympa

Someone came up with a solution for these issues with database tables?

thanks

**Comment by bv-unibs** [comment]
Hi, can you please me let me know if there's some workaround for getting rid of this issue?

thanks

**Comment by ikedas** [comment]
This error message is spurious.  It is not the error.

**Comment by bv-unibs** [comment]
So, do you think I can ignore it, and proceed with my setup? I suppose that if fake upgrade script tried to remove these columns, these aren't needed anymore for the normal server operativity..

Is it correct?

thanks

**Comment by ikedas** [comment]
What is the version and installation method of your Sympa (both of older and newer)?
How did you performed upgrading process?

**Comment by bv-unibs** [comment]
My older version was sympa 6.1.17 installed from source on redhat 6 server
My newer version is sympa 6.2.40 installed from debian 10 repository 

I used the sympa.pl fake upgrade with the following clause:

./sympa.pl --upgrade --from=6.1.17 --to=6.2.40

I used this same method (without the db error message above) few months ago on a testing server with the only difference that the upgrade was from 6.1.17 to 6.2.38 as you can see in the following issue:

https://github.com/sympa-community/sympa/issues/530

thanks

**Comment by bv-unibs** [comment]
I missing to tell that the sympa server seems working fine now, and I don't receive any errors in the logs, but I want to be certain that the configuration process worked flawlessly 

thanks

**Comment by ikedas** [comment]
> My older version was sympa 6.1.17 installed from source on redhat 6 server
> My newer version is sympa 6.2.40 installed from debian 10 repository
> 
> I used the sympa.pl fake upgrade with the following clause:
> 
> ./sympa.pl --upgrade --from=6.1.17 --to=6.2.40

To upgrade from older version installed using source to newer version using some package sytem, see #646.

**Comment by bv-unibs** [comment]
ok thanks..

**Comment by ikedas** [comment]
No additinal reports.  This ticket will be closed by now.
