### ISSUE TITLE
Add a configure option for sympa.conf-dist location

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#601]
Related to #595, see https://github.com/sympa-community/sympa/pull/595#discussion_r277600734

**Comment by ikedas** [comment]
@ldidry , how about add a function in `sympa.pl` to create `sympa.conf`?  This way, users who need sample config can create it by themselves, and we don't need thinking about the location of it.

**Comment by ldidry** [comment]
Seems a good option to me :slightly_smiling_face:

**Comment by racke** [comment]
Yes :+1: . Also it would be more flexible - we could offer basic, standard and exhaustive sympa.conf file.

**Comment by ikedas** [comment]
We'd be better to move discussion to #508.  This issue is closed.
