### ISSUE TITLE
broken line in moderate.tt2

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#607]
Sometimes the mailto line is broken 

Version
-------
6.2.42

Installation method
-------------------
From source package

Expected behavior
-----------------
The line should not be broken

Actual behavior
---------------
In the source of the message, we have 👎 
<mailto:sympa@listes.xxx.yy?subject=3DDISTRIBUTE%20test-mp-
srv2%20c562384571d18fb47c0a09bc057d764e>

Additional information
----------------------
The following text is correct

ou envoyez un e-mail =E0 sympa@listes.xxx.yy avec comme sujet :
DISTRIBUTE test-mp-srv2 c562384571d18fb47c0a09bc057d764e

**Comment by ikedas** [comment]
Hi @pascalmaes,
I couldn't reproduce the problem on long `mailto:` link with Sympa 6.2.42.
Could you please show entire body of message source?

**Comment by ikedas** [comment]
Can you log-in the Sympa server and send a message including that long `mailto:` line to you? If the line would broken, relay server (maybe Office365) broke the line. Otherwise, Sympa broke the line.

**Comment by pascalmaes** [comment]
When I send the email from sympa, the result is good

`<mailto:sympa2@listes.uclouvain.be?subject=3DDISTRIBUTE%20test-mp-srv2%20f0=
3413866de6fd8d4413c9f9cafbea95>
`

Surprisingly, in that case the mail receive to moderate was good also.


I added two editors and they receive the mail (one on gmail.com, one on live.be) these two editors receive the mail correctly 

`<mailto:sympa2@listes.uclouvain.be?subject=3DDISTRIBUTE%20test-mp-srv2%20f0=
3413866de6fd8d4413c9f9cafbea95>
`

while the mail receive on my mailbox is not

`<mailto:sympa2@listes.uclouvain.be?subject=3DDISTRIBUTE%20test-mp-
srv2%20f03413866de6fd8d4413c9f9cafbea95>
`

Very strange as the servers are the same for my work mailbox and live.be

**Comment by ikedas** [comment]
@pascalmaes, are they use the same e-mail client software?

**Comment by pascalmaes** [comment]
Yes

We wonder if the problem does not come from the "quoted-printable"
With that encoding a "=" should be put at the carriage return

`Content-Disposition: inline
Content-Transfer-Encoding: QUOTED-PRINTABLE
Content-Type: text/plain; charset="ISO-8859-1"
Content-length: 1004

Un nouveau message pour la liste test-mp-srv2 est arriv=E9 de
pascal.maes@uclouvain.be.

Il y a 10 messages en attente de mod=E9ration.
Pour consulter la liste des messages en attente, veuillez cliquer sur le li=
en
suivant : <http://sympa-2.sipr.ucl.xxx.yy/sympa/ticket/10657718437932>

Pour diffuser le message ci-joint dans la liste test-mp-srv2 :

<mailto:sympa2@listes.xxx.yy?subject=3DDISTRIBUTE%20test-mp-
srv2%20e79549f914c828c9553d5871289cac29>

ou envoyez un e-mail =E0 sympa2@listes.xxx.yy avec comme sujet :
DISTRIBUTE test-mp-srv2 e79549f914c828c9553d5871289cac29
`

Why use the quoted-printable ?
Why not a Content-Transfer-Encoding: 8bit ?

**Comment by ikedas** [comment]
> Why use the quoted-printable ?
> Why not a Content-Transfer-Encoding: 8bit ?

Because it's recommendation by the standard.

However, I found QP encoding by `MIME::QuotedPrint` module looks behaving wrong: A line longer than 74 octets should be split by insterting `=CRLF`.  I'll investigate further.

**Comment by ikedas** [comment]
@pascalmaes, can you run this script on your Sympa server?

qptest.pl:
```
use strict;
use warnings;
use MIME::Parser;

my $entity = MIME::Parser->new->parse_data('');
$entity->head->mime_attr('Content-Type', 'text/plain');
$entity->head->mime_attr('Content-Type.Charset', 'iso-8859-1');
$entity->head->mime_attr('Content-Transfer-Encoding', 'quoted-printable');

my $ioh    = $entity->bodyhandle->open('w');
$ioh->print(<<'EOF');
123456789 123456789 123456789 123456789 123456789 123456789 123456789 1234567
EOF
$ioh->close;

printf "MIME::Parser %s\n", $MIME::Parser::VERSION;
printf "MIME::QuotedPrint %s\n", $MIME::QuotedPrint::VERSION;
print "---\n";
print $entity->as_string;
print "---\n";
__END__
```

This should show following result:
```
MIME::Parser 5.xxx
MIME::QuotedPrint x.xx
---
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

123456789 123456789 123456789 123456789 123456789 123456789 123456789 12345=
67
---
```

**Comment by pascalmaes** [comment]
Here is the result

'sympa-2:/root# ./qptest.pl
MIME::Parser 5.505
MIME::QuotedPrint 3.13
---
Content-Type: text/plain; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

123456789 123456789 123456789 123456789 123456789 123456789 123456789 12345=
67
---'

**Comment by ikedas** [comment]
Thanks, your environment looks up-to-date enough.

Your Sympa encoded long line correctly as
```
<mailto:sympa2@listes.uclouvain.be?subject=3DDISTRIBUTE%20test-mp-srv2%20f0=
3413866de6fd8d4413c9f9cafbea95>
```
However, something in the middle decoded it as
```
<mailto:sympa2@listes.uclouvain.be?subject=3DDISTRIBUTE%20test-mp-srv2%20f03413866de6fd8d4413c9f9cafbea95>
```
and folded it: Things like virus scanner, spam filter, `procmail` filter etc.

**Comment by ikedas** [comment]
@pascalmaes, have your problem been solved?

**Comment by ikedas** [comment]
This issue is closed for now.
