### ISSUE TITLE
failed_to_create_web_session

### ISSUE THREAD

**Issue by CorneliusC** [sympa-community/sympa#612]
Sympa 6.2.42 (Firefox 65.0.2 / Chrome Version 73.0.3683.75)
-------
We have a problem when using the sympa webinterface. Our system contains sympa vhosts for different maildomains. We have an base domain "example.de" and then different subdomains for the vhost-Webinterface for example "server01.example.de" and then "listname.list.example.de". 

Sometimes, I don't have figured out when and why yet, I get several listmaster notification when using the webinterface with the subject "Listmaster / failed_to_create_web_session". The problems I got, when this notification comes up is, I can't add subscriber to lists and I can't create new lists for example.

In the Logs I can see this:

> May 13 08:00:45 server01 wwsympa[104004]: debug2 Sympa::List::get_robots()
May 13 08:00:45 server01 wwsympa[104004]: debug main::_split_params() PATH_INFO: /home
May 13 08:00:45 server01 wwsympa[104004]: debug2 main::_split_params() Debug level 0
May 13 08:00:45 server01 wwsympa[104004]: debug Sympa::WWW::Session::new(abc.example.de, af0c382f188151084eeb5677ed2e3d82dd, home)
May 13 08:00:45 server01 wwsympa[104004]: debug2 Sympa::WWW::Session::load(Sympa::WWW::Session, af0c382f188151084eeb5677ed2e3d82dd)
May 13 08:00:45 server01 wwsympa[104004]: info Sympa::WWW::Session::load() Undefined session ID in cookie "af0c382f188151084eeb5677ed2e3d82dd"
May 13 08:00:45 server01 wwsympa[104004]: debug2 Sympa::send_notify_to_listmaster(abc.example.de, failed_to_create_web_session, HASH)
May 13 08:00:45 server01 wwsympa[104004]: debug2 Sympa::Tools::SMIME::find_keys(abc.example.de, sign)
May 13 08:00:45 server01 wwsympa[104004]: debug2 Sympa::Message::Template::_new_from_template(Sympa::Message::Template, abc.example.de, listmaster_notification.tt2, ARRAY, HASH)
May 13 08:00:45 server01 wwsympa[104004]: debug2 Sympa::Message::new(Sympa::Message::Template, ...)
May 13 08:00:45 server01 wwsympa[104004]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <sympa@abc.example.de.1557727245.104004,7649>; envelope_sender=sympa-request@abc.example.de; message_id4004.32@abc.example.de; recipients=ARRAY; sender=sympa@abc.example.de; template=listmaster_notification; type=failed_to_create_web_session

So I checked the cookies in the browser an there is something strange. I have one cookie with an Size 47 which is has this "af0c382f188151084eeb5677ed2e3d82dd" ID. And one other with an size of 27. When I manually remove the first cookie from the browser, everything works again until some point in the future when another of this problem-cookie occurs.

![sympa chrome cookie_2](https://user-images.githubusercontent.com/6986670/57602188-be348780-755e-11e9-8222-96d8376316fa.jpg)

I already tried to check the files like Session.pm, but I can't figure out where this other cookie comes from and what could be the problem. Do you have any hint?

We use ldap authentification (SSL_CLIENT_S_DN) to access the interface.

**Comment by CorneliusC** [comment]
This was the first log entry:

> May 13 07:48:48 server01 wwsympa[102845]: debug main::_split_params() [robot example.de] [client 153.96.12.26] Incoming parameter: subaction=
May 13 07:48:48 server01 wwsympa[102845]: debug Sympa::WWW::Session::new(example.de, af0c382f188151084eeb5677ed2e3d82dd, serveradmin)
May 13 07:48:48 server01 wwsympa[102845]: debug2 Sympa::WWW::Session::load(Sympa::WWW::Session, af0c382f188151084eeb5677ed2e3d82dd)
May 13 07:48:48 server01 wwsympa[102845]: info Sympa::WWW::Session::load() Undefined session ID in cookie "af0c382f188151084eeb5677ed2e3d82dd"

**Comment by racke** [comment]
Cookies for .example.de are valid for subdomains. So if there is also an cookie issued for the subdomain, both are present and causing trouble.

**Comment by CorneliusC** [comment]
Ok, than it is more an webserver issue? (Apache)

**Comment by CorneliusC** [comment]
Or this? https://sympa-community.github.io/gpldoc/man/sympa.conf.5.html#cookie_domain

**Comment by racke** [comment]
Did you change the cookie domain for the separate Sympa robots / virtual servers?

**Comment by CorneliusC** [comment]
No.
Thats my /etc/sympa/sympa.conf:

```
 ## HTTP cookies validity domain
cookie_domain   localhost
## HTTP cookies lifetime
cookie_expire   0
cookie_refresh  60
```

And that was my robot.conf:

`## cookie_domain;`

So I assume it must be something like:
`cookie_domain .example.de`
