### ISSUE TITLE
Spurious MHonArc Search warnings for undefined search parameters

### ISSUE THREAD

**Issue by pkissman** [sympa-community/sympa#613]
Version
-------
Version 6.2.42

Installation method
-------------------
Installed from Source on a Debian 9 System

Expected behavior
-----------------
No warnings when MHonArc archives are searched.

Actual behavior
---------------
Many warnings populate error log when archives are searched for undefined parameters: $subj, $date, $from, $id.

When someone does archive searching, our log files fill up with warnings such as:

```
[Tue May 14 09:19:44.283239 2019] [fcgid:warn] [pid 23730] [client <ipaddress>:4878] mod_fcgid: stderr: [Tue May 14 09:19:44 2019] wwsympa.fcgi: Use of uninitialized value $subj in substitution (s///) at /usr/local/sympa/bin/Sympa/WWW/Marc/Search.pm line 307., referer: <website>/sympa
```

Additional information
----------------------

I made some changes to <home>/sympa/bin/Sympa/WWW/Marc/Search.pm that seems to solve the issue, but was not confident to submit a patch.

```
--- Search.pm   2019-05-14 10:36:27.205977640 -0400
+++ Search.pm_dist      2019-05-14 09:12:25.280414786 -0400
@@ -304,20 +304,18 @@
                 last if (/-->/);
             }
         }
+        $subj =~ s/ *-->$//;
 
-        if($subj) { $subj =~ s/ *-->$//; }
-
-               ($from = (<$fh> // '') ) =~ s/^<!--X-From-R13: (.*) -->/$1/;
-
+        ($from = <$fh>) =~ s/^<!--X-From-R13: (.*) -->/$1/;
 
         ## No more need to decode header fields
         #$from = &MIME::Words::decode_mimewords($from);
 
         $from =~ tr/N-Z[@A-Mn-za-m/@A-Z[a-z/;
 
-               ($date = ( <$fh> // '') ) =~ s/^<!--X-Date: (.*) -->/$1/;
+        ($date = <$fh>) =~ s/^<!--X-Date: (.*) -->/$1/;
 
-               ($id = (<$fh> // '') ) =~ s/^<!--X-Message-Id: (.*) -->/$1/;
+        ($id = <$fh>) =~ s/^<!--X-Message-Id: (.*) -->/$1/;
 
         if ($body) {
             my $lines = '';
```

**Comment by ldidry** [comment]
I created a PR with a more simple solution: https://github.com/sympa-community/sympa/pull/618

**Comment by ldidry** [comment]
@pkissman, can you try this patch please? https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/618.patch

**Comment by pkissman** [comment]
@ldidry ,  Yes. this patch appears to work.  I've never actually bothered to look at a MHonarc message file before.  So I learned something new.  Thank you for cleaning up and simplifying a solution.
