### ISSUE TITLE
restore_list command line option

### ISSUE THREAD

**Issue by taggart** [sympa-community/sympa#62]
To close large lists we use the command line method:

  sympa.pl --close_list=list@robot

since the process takes long enough that the web method times out.

Today we ran into a situation where were needed to _restore_ a large
list, but there doesn't seem to be a --restore_list option.

I took a look at what wwsympa is doing and for closing lists (in
do_close_list) and it's calling the generic $list->close from List.pm,
but for restoring lists (in do_restore_list) it's doing a bunch of
the work itself (change status, save config, restore subscriber dump,
insert users in db, savestats, setup aliases, etc).

Could it be refactored and moved into a $list->restore
in List.pm and we could also get a --restore_list option?

Thanks

**Comment by taggart** [comment]
I had a need to be able to do this again today and remembered this issue. Any progress?
Thanks

**Comment by ikedas** [comment]
@taggart, can you please check the PR above?

**Comment by ikedas** [comment]
PR merged. close.
