### ISSUE TITLE
Drop support for Perl 5.8.x

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#620]
Expected Behavior
-----------------
Sympa will support Perl 5.10.1 or later.

Current Behavior
----------------
Sympa has to support Perl 5.8.1 or later.

**Comment by racke** [comment]
Facts: Even Perl 5.10 is more than 11 years old. CentOS 6 comes with Perl 5.10. So there is really no need to support anything older.

**Comment by ikedas** [comment]
Precisely, Perl 5.10.0 was a version a bit messed. We'd be better to abandon it (RHEL/CentOS have done).

**Comment by racke** [comment]
I don't really care for old Perl versions, what would be your suggestion for the minimum Perl version? And if we decide on one, I suggest that we inform the community beforehand the next release.

**Comment by ikedas** [comment]
As I wrote at first, 5.10.1 is my suggestion.

**Comment by ldidry** [comment]
I agree. One of the strength of Sympa is that it supports old Perl but dropping 5.8 is kind of needed if we want to be able to use some modern (11 years old though, but it’s better than 5.8 which is 17 years old) Perl syntax, but there is no rush to jump on cutting-edge Perl versions. 5.10.1 is enough for now.

**Comment by ikedas** [comment]
A patch merged.  This issue will be closed when the next beta (maybe 6.2.45b.1) builds sanely.
