### ISSUE TITLE
Disable archive

### ISSUE THREAD

**Issue by rafaelmr2** [sympa-community/sympa#625]
Hi,

How can I disable archive messages?

Thanks.

**Comment by ldidry** [comment]
Hello,

Go to https://your-server.org/sympa/edit_list_request/YOUR_LIST/archives (Admin > Configure the list > The archives) and put the first setting (`process_archive`) to disabled (`off`).

**Comment by rafaelmr2** [comment]
Thanks.

It's possible to disable by default in all server? I install the server now, there's no list yet (only test), but would like to do this by default.

**Comment by ldidry** [comment]
Put `process_archive off` in `sympa.conf` and it will be disabled by default. Note that `off` is the default value, so if there is no `process_archive on` in `sympa.conf`, it’s already how you want it to be.

**Comment by rafaelmr2** [comment]
Thanks ;)
