### ISSUE TITLE
include_ldap_query and include_ldap_2level_query behaving differently

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#63]
While playing with include_ldap_query, I found what I think is an undocumented behaviour.
If filling attrs with, say,  "mail,cn", both the email and name appear when reviewing the list members.
The fact that you can use 2 attributes in the attrs field, first for email and second for name, is not documented.

However, the same behaviour cannot be reproduced with include_ldap_2level_query.
Using attrs2="mail" works, the dynamic list is properly populated with the emails.
Using attrs2="mail,cn" just gives an empty subscribers list.

This is with sympa 6.2.19 beta2.

**Comment by ikedas** [comment]
Merged. Thanks for reporting & fixing bug!
