### ISSUE TITLE
INTERNAL SERVER ERROR (edit_list) - Failed to include members 

### ISSUE THREAD

**Issue by psvillanueva2015** [sympa-community/sympa#631]
Hi,

Our sympa environment just recently upgraded to 6.2.40, when working with data source we frequently encounter this error " INTERNAL SERVER ERROR (edit_list) - Failed to include members "  but after removing the file inclusion option it fix the problem and it reappear when we try to modify again the data source setup. Any Idea?

Below is the list config file

visibility noconceal

reply_to_header
apply forced
value sender

web_archive
access private

subject testing new sympa

subscribe open

serial 7

unsubscribe open_notify

creation
email sympa.message@example.com
date obsoleted
date_epoch 1558941545

update
email sympa.message@example.com
date_epoch 1558943003

review private

default_user_options
reception mail
visibility noconceal

send owneroreditor

status open

remind listmaster

available_user_options
reception urlize,mail,txt,nomail

include_file sympa.message@teradyne.com

include_sql_query
passwd Teradyne1
db_name app-dwh-vip.corp.example.com:2600/mdmAPP.corp.example.com
db_type Oracle
user SYMPA
name Prodmdm1
sql_query select DISTINCT EMAIL_ADDRESS from MDM.MDM_SYMPA_VIEW WHERE UPPER(TRIM(LOCATION_NAME)) = 'CEBU'  AND ACTIVE_FLAG='Y' AND DEPARTMENT_NUM = '072970' and NOT EMAIL_ADDRESS IS NULL

Thanks,
Pete

**Comment by ikedas** [comment]
Hi @psvillanueva2015,

Could you please show us syslog entries when you encountered the internal server error? Thanks.

**Comment by psvillanueva2015** [comment]
here is the syslog message 

May 27 04:13:10 lists-dev1 wwsympa[21580]: info main::do_home() [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com]
May 27 04:13:15 lists-dev1 wwsympa[21580]: info main::do_search_list_request() [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com]
May 27 04:13:20 lists-dev1 wwsympa[21580]: info main::do_search_list(all-cebu) [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com]
May 27 04:13:26 lists-dev1 wwsympa[21580]: info main::do_info() [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com] [list bpit-infra-all-cebu-testing]
May 27 04:13:28 lists-dev1 wwsympa[21580]: info main::do_admin() [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com] [list bpit-infra-all-cebu-testing]
May 27 04:13:33 lists-dev1 wwsympa[21580]: info main::do_edit_list_request(data_source) [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com] [list bpit-infra-all-cebu-testing]
May 27 04:13:47 lists-dev1 wwsympa[21580]: info main::do_edit_list() [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com] [list bpit-infra-all-cebu-testing]
May 27 04:13:48 lists-dev1 wwsympa[21580]: notice Sympa::List::on_the_fly_sync_include() Synchronizing list members...
May 27 04:13:48 lists-dev1 wwsympa[21580]: err main::#1571 > main::do_edit_list#10665 > Sympa::List::on_the_fly_sync_include#7031 > Sympa::List::sync_include#6683 > Sympa::List::_load_list_members_from_include#5995 > Sympa::List::_include_users_file#4869 Unable to open file "sympa.message@example.com"
May 27 04:13:48 lists-dev1 wwsympa[21580]: err main::#1571 > main::do_edit_list#10665 > Sympa::List::on_the_fly_sync_include#7031 > Sympa::List::sync_include#6683 > Sympa::List::_load_list_members_from_include#6012 Inclusion include_file failed in list Sympa::List <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com>
May 27 04:13:48 lists-dev1 wwsympa[21580]: info Sympa::List::_include_users_sql() 101 included users from SQL query
May 27 04:13:48 lists-dev1 wwsympa[21580]: err main::#1571 > main::do_edit_list#10665 > Sympa::List::on_the_fly_sync_include#7031 > Sympa::List::sync_include#6695 Errors occurred while synchronizing datasources for list Sympa::List <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com>
May 27 04:13:48 lists-dev1 wwsympa[21580]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com.1558944828.21580,1848>; envelope_sender=bpit-infra-all-cebu-testing-owner@lists-dev1.corp.example.com; message_id=sympa.1558944828.21580.735@lists-dev1.corp.example.com; recipients=ARRAY; sender=sympa@lists-dev1.corp.example.com; template=listmaster_notification; type=sync_include_failed
May 27 04:13:48 lists-dev1 wwsympa[21580]: notice Sympa::Bulk::store() Message Sympa::Message::Template <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com.1558944828.21580,1848> is stored into bulk spool as <1.5.1558944828.1558944828.477841.bpit-infra-all-cebu-testing@lists-dev1.corp.example.com_s,21580,9445>
May 27 04:13:48 lists-dev1 wwsympa[21580]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com.1558944828.21580,6259>; envelope_sender=bpit-infra-all-cebu-testing-owner@lists-dev1.corp.example.com; message_id=sympa.1558944828.21580.605@lists-dev1.corp.example.com; recipients=ARRAY; sender=sympa@lists-dev1.corp.example.com; template=listmaster_notification; type=web_intern_error; action=Command process
May 27 04:13:48 lists-dev1 wwsympa[21580]: notice Sympa::Bulk::store() Message Sympa::Message::Template <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com.1558944828.21580,6259> is stored into bulk spool as <1.5.1558944828.1558944828.600624.bpit-infra-all-cebu-testing@lists-dev1.corp.example.com_s,21580,1964>
May 27 04:13:48 lists-dev1 wwsympa[21580]: info main::do_edit_list_request(data_source) [robot lists-dev1.corp.example.com] [session 39666361393906] [client 132.223.40.132] [user sympa.message@example.com] [list bpit-infra-all-cebu-testing]
May 27 04:13:49 lists-dev1 bulk[21908]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <1.5.1558944828.1558944828.477841.bpit-infra-all-cebu-testing@lists-dev1.corp.example.com_s,21580,9445/s> to Sympa::List <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com> (priority 1) (starting 1 seconds after scheduled expedition date)
May 27 04:13:49 lists-dev1 bulk[21908]: notice Sympa::Mailer::store() Done sending message Sympa::Message <1.5.1558944828.1558944828.477841.bpit-infra-all-cebu-testing@lists-dev1.corp.example.com_s,21580,9445/s> for Sympa::List <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com> (priority 1) in 1 seconds since scheduled expedition date
May 27 04:13:49 lists-dev1 bulk[21908]: notice Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message <1.5.1558944828.1558944828.600624.bpit-infra-all-cebu-testing@lists-dev1.corp.example.com_s,21580,1964/s> to Sympa::List <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com> (priority 1) (starting 1 seconds after scheduled expedition date)
May 27 04:13:49 lists-dev1 bulk[21908]: notice Sympa::Mailer::store() Done sending message Sympa::Message <1.5.1558944828.1558944828.600624.bpit-infra-all-cebu-testing@lists-dev1.corp.example.com_s,21580,1964/s> for Sympa::List <bpit-infra-all-cebu-testing@lists-dev1.corp.example.com> (priority 1) in 1 seconds since scheduled expedition date

**Comment by racke** [comment]
So it looks like that Sympa can't find the file `sympa.message@example.com`. Where is this file located? Which installation method did you use? What was your Sympa version before the upgrade?

**Comment by psvillanueva2015** [comment]
When we take over managing sympa it was at version 6.0.3 then we upgraded to 6.2.22 then the latest one 6.2.40 - Sympa was originally installed from tar file and upgraded also via source or tar file.  sympa.message@example.com no where to be found. During creation of autolist by default  file inclusion is automatically populated with sympa.message@example.com but deleting that before saving error will not appear but when we modify again we need to delete again to eliminate the error., therefore it will not totally deleted and it keeps coming back when we try to modified. 

![image](https://user-images.githubusercontent.com/13635380/58605228-a16fb200-82c9-11e9-9bfd-331bb0deec77.png)

For now what I have done is to create a file /home/sympa/expl/include_admin/admin and put that file when creating a new auto list. Is there a way we can make this as default?

**Comment by ikedas** [comment]
The problem described in the title looks solved. Please submit new issue for question about particular setting.
