### ISSUE TITLE
Is it possible to moderate list creation and after say "That user is legit and can bypass moderation"?

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#633]
[Framalistes](https://framalistes) is a public Sympa instance. Anyone can create lists on it.

Spammers used it the last two weeks to create a lot of lists and send spam.

We now use the `create_list.public_listmaster` scenario to avoid that. It solves the spam issue but slows down the "create list and use it" process for legit users.

Is there a way to put new users in quarantine and make their list creation moderated while having a flag on manually verified users that make them able to create lists without being moderated?

If there is no way to do that, I’ll make this issue a feature request and work on it.

**Comment by ikedas** [comment]
I think defining specific privileges may be realised by using [named filters](https://sympa-community.github.io/manual/customize/basics-scenarios.html#named-filters) in scenario.

**Comment by ldidry** [comment]
Closing. My custom scenario condition is waiting for merge on https://github.com/sympa-community/sympa-contribs/pull/10
