### ISSUE TITLE
Prevent lists creation with the same name and different cases when list creation is moderated

### ISSUE THREAD

**Issue by ldidry** [sympa-community/sympa#635]
Same 

Version
-------
6.40.0

Installation method
-------------------
source

Expected behavior
-----------------
Lists with the same name but a different case (like "test" and "Test") should not be able to be created when lists are pending for listmaster validation.

Actual behavior
---------------
I got a user that created two lists (let’s say "test" and "Test").

In the pending lists page, the name of lists are lowercased. I have been able to validate "test" but after that, "test" still showed up in the pending lists page. After some DB digging, there was "Test" that was still pending. I couldn’t validate or reject "Test" since lists names are lowercased on the pending list page: all I got was the "test" validation page (which was already validated, of course)

Additional information
----------------------
If there is no moderation on list creation, `list_data/test` is already created when you want to create a list with same name and different case: the list name is already taken, so the problem doesn’t appear.

**Comment by racke** [comment]
I would be actually good if a list name would be always lower case, but that's probably not realistic.

**Comment by ldidry** [comment]
Mmh… strange: I can’t ask to create two lists with different cases but some of our users succeed.

I can’t reproduce the bug, either on my dev VM nor on production.

I close this issue but will reopen it if I succeed to reproduce.

**Comment by ldidry** [comment]
I suspect something with list renaming, but I’m not sure. I’ll investigate when the bug will come back.
