### ISSUE TITLE
Moving from 6.1.1 to 6.2.24 on a new server

### ISSUE THREAD

**Issue by nmatt** [sympa-community/sympa#646]
I need to move from Sympa 6.1.1 (source distribution) to 6.2.24 (Ubuntu 18.04.2 LTS package) on a new server, with minimum outage time. The [Moving to another server](https://sympa-community.github.io/manual/upgrade/move.html) page doesn't address upgrading from Sympa 6.1.x, and the [Upgrading Notes](https://sympa-community.github.io/manual/upgrade/notes.html) assume an in-place upgrade. What is the recommended/least error-prone procedure here? How do the steps marked as "[Source distribution only]" apply when moving from source distribution to binary distribution (Ubuntu package)?

One approach that maybe might make sense is to first migrate the 6.1.1 installation to 6.**1**.24 (Ubuntu 16.04 LTS package), then upgrade that in-place to 6.2.24, and then move the result to the new server. Is there an easier way?

**Comment by ikedas** [comment]
Hi @nmatt,

Firstly, in-place upgrade needs [directory layout](https://sympa-community.github.io/manual/layout.html) being the same between earlier and newer versions.

If directory layout is differ among earlier and newer versions. IMO recommended procedure is migrating new layout with earlier version at first, and then upgrading to newer version:
1. Perform in-place upgrade from 6.**1**.1 to 6.**1**.24 with the same layout using source distribution.
2. Install 6.**1**.24 package distributed by Ubuntu, and copy database, list config, global config used by source installation above to where Ubuntu package recognizes.
3. Upgrade Ubuntu package from 6.**1**.24 to 6.**2**.24.

After each step above, you have to confirm that Sympa is running properly.

**Comment by nmatt** [comment]
Thanks @ikedas for the info. I'll close the issue for now.
