### ISSUE TITLE
FR: Publisher role needed

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#647]
In a moderated discussion list I need to define a special user with publisher permissions: every post this user send to the list is published without moderation but the user does moderate the messages other users send.

Is there any way to get this behaviour? If not, would you consider it to be a possible future feature?

Best regards.

**Comment by racke** [comment]
Is this similar to the "trusted user" approach (#644), but for one or several lists only?

**Comment by qosobrin** [comment]
Yes, that's the idea. The ideal would be that list owners could define these "trusted" or "publisher" users the same way they define moderators using the web GUI (that's the reason why I think this could be a new feature).

I imagine that, at this moment, this can be accomplished by modifying the list send scenario, but that would require some kind of advanced knowledge that regular list admins lack of.

**Comment by ikedas** [comment]
As I commented on #633, I think defining specific privileges may be realised by using [named filters](https://sympa-community.github.io/manual/customize/basics-scenarios.html#named-filters) in scenario.

**Comment by qosobrin** [comment]
My feature request #669 could be a good solution to this problem. Thank you for any one who responded to this issue.

Regards.
