### ISSUE TITLE
Branches and tags from version < 6.2 missing in GitHub

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#650]
The Sympa 6.1 tags are missing in GitHub.

**Comment by ikedas** [comment]
Hi,

You can see [historic-sympa](https://github.com/sympa-community/historic-sympa) repository.

**Comment by paulmenzel** [comment]
Is Sympa 6.2 a complete rewrite, so that there is no common history?

**Comment by ikedas** [comment]
I think so.

sympa-community/historic-sympa@04026826cc153c601adb6a6e78e973a99a5bc9e9 in historic-sympa repo is the same as sympa-community/sympa@3a644d49dabce1c28477a4f908e68550b045763f in sympa repo: Both of them point release 6.2.16.
