### ISSUE TITLE
 Cannot create /var/spool/sympa/digest/X: File exists at /usr/share/sympa/lib/Sympa/Spool.pm line 74.

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#651]
Running the upgrade script after updating from 6.1.23\~dfsg-2+deb8u3 to Sympa 6.2.16\~dfsg-3+deb9u2 (Debian 9 (Stretch)), it aborts because the spool file already exists.

    $ sudo /usr/lib/sympa/bin/sympa.pl --upgrade
    […]
    notice Sympa::Upgrade::upgrade() Upgrading digest spool.
    Cannot create /var/spool/sympa/digest/vorstand@example.net: File exists at /usr/share/sympa/lib/Sympa/Spool.pm line 74.
    $ ls -ld /var/spool/sympa/digest/vorstand@example.net
    -rw-r-----. 1 sympa sympa 222172 Jun 10 17:09 /var/spool/sympa/digest/vorstand@example.net

**Comment by ikedas** [comment]
Hi @paulmenzel,

Have stopped services of Sympa (sympa.pl and so on) before you run `sympa.pl --upgrade`?

**Comment by ikedas** [comment]
No response.  Closed for the present.
