### ISSUE TITLE
Improve handling of missing `sympa/web_tt2` during upgrade

### ISSUE THREAD

**Issue by paulmenzel** [sympa-community/sympa#652]
Upgrading from 6.1.23 to 6.2.16 with `/usr/lib/sympa/bin/sympa.pl --upgrade` shows the error below.

    notice Sympa::Upgrade::fix_colors() /etc/sympa/sympa/sympa.conf file saved as /etc/sympa/sympa/sympa.conf.upgrade12.Jun.2019-14.00.23
    err main::#797 > Sympa::Upgrade::upgrade#1345 > Sympa::Upgrade::save_web_tt2#2020 /etc/sympa/web_tt2 directory is not writable: No such file or directory. Unable to rename it. Web interface might look buggy after upgrade

If the directory `/etc/sympa/web_tt2` does not exist, no error should be shown (maybe a notice). It seems totally fine, that it is missing, if no customizations were made.

Additionally, no empty backup directory `/etc/sympa/web_tt2.upgrade12.Jun.2019-13.25.58/` should be created.

Version
-------

6.2.16~dfsg-3+deb9u2

Installation method
-------------------
Debian 9

**Comment by ikedas** [comment]
Hi @paulmenzel,
Could you please check the PR above? Thank you.
