### ISSUE TITLE
Sympa footer outlook

### ISSUE THREAD

**Issue by bertaviader** [sympa-community/sympa#658]
Hey!

I have a question regarding outlook, we have a server with version of sympa 6.2.16. I want to add a footer with a link to unsubscribe from the list. I added a message.footer.mime in the web_tt2, with the link. But when I send a message from a list, the footer is added as a attachment htm and not appended in the same message. Do you know how I can fix this? Did not change the file_type. 

We have the same configuration in another server, but with a minor version of sympa, and with gmail the footer is attached correctly, appended in the message as we want.

Thank you,
Berta

**Comment by ikedas** [comment]
Hi @bertaviader,

You have to use message.footer in stead of message.footer.mime, and have to set footer_type parameter to “append”.

**Comment by bertaviader** [comment]
Okay, so I cannot have mime in outlook? It needs to be text?
Can I have links in message.footer?

Thanks!

**Comment by ikedas** [comment]
Hi,
You may have links in message.footer.  Please try it.

**Comment by bertaviader** [comment]
Thanks!!!! I've tried and it work. 
Do you know how to have a link to unsubscribe directly? Without the need to go to the web page?

Thank you,
Berta

**Comment by ikedas** [comment]
Please look in `[$EXPLDIR](https://sympa-community.github.io/manual/layout.html#expldir)/list path/` directory.  There are `config` and `message.footer` files.  You may edit or create these in directory of any lists.  See [documentation](https://sympa-community.github.io/manual/customize/basics-list-config.html) for more details.

**Comment by bertaviader** [comment]
Okay, thanks I will close the issue.

**Comment by Shelagh-Lewins** [comment]
I cannot find how to set the footer_type parameter. Can anybody explain this please? The docs say what it does but not how to edit the value. Thanks!
