### ISSUE TITLE
Problème de récupération du domaine dans les appels de Custom_conditions

### ISSUE THREAD

**Issue by bmarchal54** [sympa-community/sympa#660]
Hello,

When calling the CustomsCondition (line 1451 of the Scenario.pm module), the name of the list, passed as a parameter, does not always contain the domain.

This may be of concern if two lists of two different domains have the same name.

I use the recovered name to make a call to a Sympa :: List object in the 'verify' function. I always have two parameters: the name of the list and the e-mail address to test.

To remedy this, I always pass a patch that adds the robot last parameter.
        eval "CustomCondition::${condition}::verify(\@{\$args_ref},\$robot)";

Would it be possible to change that?

cordially

Version
-------
Sympa 6.2.42 installed with yum

**Comment by ikedas** [comment]
Hi @bmarchal54,

Change seems possible,  I'll investigate it further.  Please wait for a while (perhaps some weeks).

Thanks for your suggestion!

**Comment by ikedas** [comment]
Hi @bmarchal54,

Can you modify scenario file as below?
``` code
...
CustomCondition::condition( ...values..., [domain])  smtp,smime,skim,md5 -> reject()
...
```
`[domain]` may be used with Sympa 6.2.32 or later. With earlier versions. `[conf->host]` may be used instead.

**Comment by bmarchal54** [comment]
Hello, 
I will do the test.
It's cleaner than always changing the source code of the module. 
By displaying the name of the list in parameter, sometimes there is the name of the domain, sometimes no. 
thanks a lot for your help 
cordially 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
No more problems.  Close.
