### ISSUE TITLE
Can not access shared documents anymore

### ISSUE THREAD

**Issue by pveith** [sympa-community/sympa#661]
Upgrade from 6.2.40 to 6.2.42 and now shared documents are not working.

Log file Entry: 
Jun 18 11:17:58 SERVERNAME wwsympa[9825]: info main:: [robotSERVERNAME.DOMAIN] [session 28120700933350] [client 000.000.000.000] [user pveith@uni-bonn.de] [list test3] Unknown action d_read

Link to produce the error (https://SERVERNAME.DOMAIN/wws/d_read/test3/) is gernerated via list_menu.tt2. Which previously worked fine with 6.2.40. Did i miss anything while upgrading?

**Comment by ldidry** [comment]
Do you have added `shared_feature on` in `/etc/sympa/sympa.conf` after the upgrade? (it seems to be missing in the release notes, you couldn’t know)

Documentation: https://www.sympa.org/gpldoc/man/sympa.conf.5.md#shared_feature

**Comment by pveith** [comment]
Thanks a lot. Was not notified, so realised very late, that my problem is solved.
