### ISSUE TITLE
New Sympa Logo

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#665]
Expected Logo
-----------------

New Sympa logo is proposed.

[<img src="https://www.sympa.org/_media/logos/actual/regular/sympa_blue.png" />](https://www.sympa.org/logos/)
(Click the image above to see the other variants.)

Current Logo
----------------

This is Sympa logo currently used.

<img src="https://www.sympa.org/_media/logos/old/sympa_multi_150x121.png" />

Possible Solution
-----------------

Replacing Sympa logo and icon in the source distribution with new ones.

Context
-------

**Comment by qosobrin** [comment]
What font was used to produce the logo? Is the kerning for the letters correctly applied? I feel more space between S, Y and M letters than I feel between M and P or between P and A. Otherwise, cool logo.

**Comment by ldidry** [comment]
I flagged this Issue as `newcomers` as it doesn’t seem a hard work to me.

**Comment by ldidry** [comment]
The font is [Smoothy Sans](https://creativemarket.com/ianbarnard/166172-Smoothy-Cursive-Script-Sans). I don’t know if the kerning has been modified.

**Comment by qosobrin** [comment]
Thank you, @ldidry

**Comment by Poukram35** [comment]
Hi,
sorry I hadn't seen posts about logo...
As Luc said, the SMOOTHY font was used, and I modified it with cut-outs in the letters.
That said, it's been more than a year since I made the logo, following the survey on the Sympa logo, and I don't remember where I took this font, because I see now that it's not free.

Indeed there is a little more space between the letters S, Y and M than M and P or between P and A. 
Honestly, I don't remember why.... But I corrected it in the logo attached and you can see the result. I can apply on all logos if necessary.

![logo_sympa](https://user-images.githubusercontent.com/5887670/60724699-72d39f80-9f37-11e9-98eb-170006a7bd8b.png)
...

**Comment by ldidry** [comment]
Once the new kerning is accepted, @Poukram35, would you mind updating the [logos page](https://www.sympa.org/logos/) (or ask someone to do it if you don’t have the rights, poke @dverdin)?

I’m on holidays tonight for 2 weeks but I will be able to update the logos in my PR (or you can do a PR on https://github.com/ldidry/sympa/tree/fix-665).

**Comment by ikedas** [comment]
Where is master repository for the logos? The [logo page](https://www.sympa.org/logos/logos) seems not listing all of them (On favicon, only purple variant is listed).

I think we'd be better to create the repo to maintain logos (It may also be used as CDN to deliver them).

**Comment by racke** [comment]
Separate repository sounds good to me, we can also other assets (like JS bundles or other stuff) there if needed.

**Comment by racke** [comment]
I prefer sympa-assets.

**Comment by ikedas** [comment]
I prefer `assets`, like [gpldoc](https://github.com/sympa-community/gpldoc) that may be accesssed as [`https://site/gpldoc/`](https://sympa-community.github.io/gpldoc/)

**Comment by mjourdan** [comment]
Some feelings:
- the colored trunks between the discs are unnecessary
- on the text, the white oblique bars on the text lack of parallelism

**Comment by ikedas** [comment]
> I prefer `assets`, like [gpldoc](https://github.com/sympa-community/gpldoc) that may be accesssed as [`https://site/gpldoc/`](https://sympa-community.github.io/gpldoc/)

If no ibjection, I'll create `assets` repo:  Thanks to GirHub Pages functionality, it may be accessed as `https://sympa-community.github.io/assets/`

**Comment by ikedas** [comment]
As I told elsewhere, this proposal is being scrapped. The PR that @ldidry had submitted will also be closed,
So please resubmit it at another time in the future.

I think there are a few issues that need to be addressed in order to make a new proposal.
1. Are the author of the logo still willing to give permission to use it for Sympa?
3. How would be the license of the logo? Some kind of open license (e.g. CC-BY-SA), public domain or else?
4. Should there be a user interface that allows administrators to choose the colors of the logo?
5. anything else?
