### ISSUE TITLE
Q: Message moderator in custom header

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#666]
Sympa allows adding custom headers to messages sent to distribution lists. Is there any way to add a header that indicates the address of the editor who moderated (released) the message? Do these custom headers allow using Sympa variables? If so, what variable should I use?

Thank you very much.
Best regards.

**Comment by ikedas** [comment]
Such header field is added to any messages (held once and) approved by moderator: `X-Validation-by:`.  Please check the header of distributed messages.

**Comment by qosobrin** [comment]
Thank you very much. That information was in front of my eyes and I couldn't see it.

Best regards.
