### ISSUE TITLE
Digests should include reply-to address in DMARC protection mode

### ISSUE THREAD

**Issue by yardenac** [sympa-community/sympa#670]
When a message is shown in templates such as [digest.tt2](https://github.com/sympa-community/sympa/blob/sympa-6.2/default/mail_tt2/digest.tt2) and [digestplain.tt2](https://github.com/sympa-community/sympa/blob/sympa-6.2/default/mail_tt2/digestplain.tt2), it shows the sender as `From: [% m.from %]`.

But when DMARC protection mode is enabled, the From header is not useful - it will only contain the list address. Is there a way for digest templates to include the reply-to address as well?

I'm a moderator at [sfchalkboard](https://lists.riseup.net/www/info/sfchalkboard) and this is a regular complaint we get from users in digest mode. When the sender has a DMARC reject policy (most common domains like gmail & yahoo do), digest readers are unable to send a private reply. Often people will send replies to the list, and then we have to reject their message and tell them the correct email address. Now we have to tell everybody to repeat their email addresses in the body of their message!

If you could tell us the right code to put in the template file, the riseup folks are open to patching it locally. But to me, this is a bug which should be fixed for everybody.

**Comment by ikedas** [comment]
Hi @yardenac,

Could you please show us an actual example of the digest message in question?

**Comment by yardenac** [comment]
@ikedas I'm not going to post an actual full message, but here's an example of a digest message from a DMARC-rejecting sender:

```
---------- Forwarded message ----------
From: Jane Doe <sfchalkboard@lists.riseup.net>
To: sfchalkboard@lists.riseup.net
Cc: 
Bcc: 
Date: Sat, 22 Jun 2019 11:56:35 -0400
Subject: [sfchalkboard] Jane Doe's Random Subject Line
```

**Comment by yardenac** [comment]
Turns out this isn't just a digest problem. It's a problem when viewing archives as well, such as in this screenshot:

![sfchalkboard-dmarc-bug](https://user-images.githubusercontent.com/687943/60140998-78c3c680-9768-11e9-9048-050e6811687f.png)

DMARC mode should only replace the From header in actual smtp message, not in all these other ways.

**Comment by ikedas** [comment]
Hi @yardenac,

Please contact with riseup’s support at first.  We cannot know how they are managing and/or customizing Sympa of their own.

**Comment by yardenac** [comment]
@ikedas I did. Their digest templates are unmodified, and none of us knows how to modify it to do this.

**Comment by ikedas** [comment]
At least on recent version of Sympa, messages to be archived or be compiled to digest will _not_ be modified by way of DMARC protection.  I think templates don’t matter from the beginning.

One reason I can imagine is that a list contains another list as a subscriber.  If a message is posted to the former list, protection will be applied, and it will be forwarded to subscribers of the latter list.

Anyway, riseup support will help you better.  If they think the problem you reported is due to a bug or a bad feature of Sympa, they will report it to us.

**Comment by ikedas** [comment]
@taggart , do you have any news?

**Comment by yardenac** [comment]
The problem has not been fixed and support.riseup.net appears to be eating the tickets I submit.

**Comment by ikedas** [comment]
@yardenac , please contact with riseup's support.  This seems not the problem of (at least recent version of) Sympa itself.

This issur is closed.
