### ISSUE TITLE
Death of the task_manager process

### ISSUE THREAD

**Issue by bmarchal54** [sympa-community/sympa#681]
Since switching to version 6.2.42, I have regularly stopped the task_manager process.
When I look at which list that might correspond, I suspect that it corresponds to a list that has been deleted between the definition of the task and the launch of it.

Version
-------
6.2.42

Installation method
-------------------
yum package

Error message in sympa.log
------------------------------------
```
Jul  3 06:42:02 esbareich task_manager[46073]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1562128919;label=INIT;model=sync_include;context=*>
**Jul  3 06:42:02 esbareich task_manager[46073]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1334 DIED: Can't call method "sync_include" without a package or object reference at /usr/share/sympa/lib/Sympa/Spindle/ProcessTask.pm line 1334, <GEN9042068> line 1.**
```
List of task to execute
```
# ll /var/spool/sympa/task/*1562128919*
-rw-r----- 1 sympa sympa 112  3 juil. 06:41 1**562128919.INIT.sync_include.all-lettres-l-3-ncy-et-culturelles-fi-1920@etu.univ-lorraine.fr**
-rw-r----- 1 sympa sympa 112  3 juil. 06:41 1562128919.INIT.sync_include.all-mz-l2-ulpla-1920@etu.univ-lorraine.fr
```
But in the directory /var/lib/sympa/list_data/etu.univ-lorraine.fr :
```
# ll -d all-lettres-l-3-ncy-et-culturelles-fi-* 
drwxr-xr-x 2 sympa sympa 4096  3 juil. 05:32 all-lettres-l-3-ncy-et-culturelles-fi-1819
```
The list all-lettres-l-3-ncy-et-culturelles-fi-1920 t does not exist anymore

Thanks in advance

**Comment by racke** [comment]
Looks like the task manager should check if the list still exists and discard the task if the list is gone.

**Comment by bmarchal54** [comment]
Hello, 

That's what I did. But there should be no stopping of the task_manager process in this context. Do not treat a task for a list that no longer exists, in my opinion, directly in the code. 

Cordially 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
Hi @bmarchal54,
Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/245428aa3fcc5588361f27370e1df6917e7f3f63.patch) and check if the problem will be solved?  Thanks.

**Comment by bmarchal54** [comment]
Hello, 

Thank you for the patch proposal. I just put it in place. I will follow in the day if the problem comes back and I'll let you know. 

Have a good day 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by bmarchal54** [comment]
Hello, 

Since the passage of the patch proposed last Sunday, I did not stop the task_manager process. 

Thank you so much. 

cordially 

--- 
Benoît MARCHAL 
Sous direction Infrastructure & Services 
Direction du Numérique 
Université de Lorraine 
Tél : 03.72.74.11.39 
mél : Benoit.Marchal@univ-lorraine.fr

**Comment by ikedas** [comment]
I merged fix, and it will be included in the next release.
@bmarchal54, thanks for reporting bug and improving Sympa!
