### ISSUE TITLE
Q: Path to files in sympa code

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#682]
I'm in the process of creating a custom scenario condition that needs to read a configuration file as described in https://sympa-community.github.io/manual/customize/custom-scenario-conditions.html

I have been searching but could not find a way to refer to sympa's paths from within the code. I wonder if I `home`, `etc`, `css_path` and so on as defined in the sympa.conf file are valid within the custom scenario condition code file. Is it there any documentation on best practices to access files within sympa code?

Thank you very much.
Best regards,

**Comment by ikedas** [comment]
At first, see `sympa.conf(5)`.  For example `etc` is descibed as
> #### `etc`
> 
> Directory for configuration files
> 
> - Default:
> 
>     `$SYSCONFDIR`
> 
> - Overrides:
> 
>     None.
> 
> Base directory of global configuration (except "sympa.conf").

`lang` is described as:
> #### `lang`
> 
> Default language
> 
> - Default:
> 
>     `en-US`
> 
> - Overrides:
> 
>     Virtual domain
> 
>     List
> 
> This is the default language used by Sympa. One of supported languages should be chosen.

Currently, getting configuration looks slightly messing:

- Global configuration, i.e. defined in `sympa.conf`, may be given by `%Conf::Conf` hash.  Some parameters (e.g. `etc`) may have only global config and cannot be overridden by each domain.
- Overrides by each domain, i.e. defined in `robot.conf`, may be given by `Conf::get_robot_conf()` function.  Some parameters (e.g. `title`) may have global default and/or domain config and cannot be overridden by each list.
- Overrides by each list, e.g. defined in `config` file, may be given by `$list->{'admin'}` hash.

Examples:

``` perl
use Conf;
...
$etc = $Conf::Conf{'etc'};                                # sympa.conf
$title = Conf::get_robot_conf($domain, 'title');          # robot.conf
$lang = $list->{'admin'}{'lang'};                         # list config
```

**Comment by qosobrin** [comment]
Thank you, @ikedas for the complete information; I will try one of these days. After my little project is complete, is there any place where I can contribute with the code for other users to benefit from? Maybe a new folder under https://github.com/sympa-community/sympa-contribs ?

**Comment by ikedas** [comment]
Of course you can contribute your work to [sympa-contribs](https://github.com/sympa-community/sympa-contribs). Thanks!

**Comment by qosobrin** [comment]
@ikedas , I finally got some spare time to create a custom scenario condition and contributed it to sympa-contribs. I requester to pull it to a fork/pull request by @dverdin because he had already organized the folders on that project and had already created a folder to store custom scenario conditions. I hope the person in charge of sympa-contribs will find some time to evaluate our changes and accept them.

I'm closing this issue now since my question is answered. Thank you very much to everyone.

Best regards.
