### ISSUE TITLE
Commit messages from github.com can cause mhonarc to spin

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#685]
[test.pl.txt](https://github.com/sympa-community/sympa/files/3372532/test.pl.txt)

Version
-------

Sympa 6.2.44
MHonARC 2.6.19

Installation method
-------------------
rpm from https://copr.fedorainfracloud.org/coprs/xavierb/sympa/

Expected behavior
-----------------

archived.pl / mhonarc should successfully archive input message.

Actual behavior
---------------

mhonarc spins at 100% CPU indefinitely because of a broken regexp .

Additional information
----------------------

One of our users is sending commit messages from their github repositories to  a mailing list that we archive. They then decided to fork Chrome and other huge open source projects. This generates very large messages with a specific structure.

I appreciate that this might be a case of "well, don't do that then", but I thought that I ought to at least report this as a potential issue.

Strictly speaking this is an issue with MHonARC rather than Sympa, but it looks like it is triggered by the following option that Sympa uses in  mhonarc-ressources.tt2 :

```
<MIMEARGS>
text/plain; quote
</MIMEARGS>
```

I will attach a small Perl script which generates anonymised  sample input. I believe that the problem is down to two sets of  ```<email address>``` separated by 100,000 lines of text. If I reduce that to 30,000 lines of text then mhonarc completes after 53 seconds on a test system.

**Comment by ikedas** [comment]
Hi @dpc22,
What is the version of your Perl? (what is shown with `rpm -q perl`?)

**Comment by dpc22** [comment]
On 2019-07-12 04:11, IKEDA Soji wrote:
> Hi @dpc22 [1],
>  What is the version of your Perl? (what is shown with rpm -q perl?)

perl-5.16.3-294.el7_6.x86_64

(We are running RHEL 7.6, and there are no pending updates).

-- 
David Carter                             Email: dpc22@cam.ac.uk
University of Cambridge,                 Phone: (01223) 748408
Information Services,                    Fax:   (01223) 334679
7 J J Thomson Avenue,
Cambridge UK.  CB3 0RB

**Comment by ikedas** [comment]
I reprodiced using test message with 50,000 lines and this `mhonarc-ressources.tt2`
``` code
<MIMEARGS>
text/plain; nonfixed htmlcheck maxwidth=78
</MIMEARGS>
```

**Comment by ikedas** [comment]
@dpc22, thouogh this is a fix to MHonArc, attached patch may solve the problem.

[issue-689-001.patch.txt](https://github.com/sympa-community/sympa/files/3395156/issue-689-001.patch.txt)

Note that this patch has not been tested carefully.

**Comment by ikedas** [comment]
This is not a bug of Sympa.  Close.
