### ISSUE TITLE
Get 404 for mailing list for users

### ISSUE THREAD

**Issue by gzcwnk** [sympa-community/sympa#687]
Hi,

I am trying to join the mailing list to get help with setting up sendmail and I am getting a 404 on your website can someone fix this please?

**Comment by ikedas** [comment]
Hi @gzcwnk,
  - Could you please show the URL you tried?
  - Have you seen [description in Administration Manual](https://sympa-community.github.io/manual/install.html)?

**Comment by gzcwnk** [comment]
This,

https://www.sympa.org/community/lists.md

leads to,

https://github.com/listes.renater.fr%60](https://listes.renater.fr/sympa/info/sympa-users)

**Comment by gzcwnk** [comment]
Tying to follow 2. for sendmail and I have no working aliases part, seems to be down to a sendmail config being lacking.

**Comment by ikedas** [comment]
Very sorry.  The menu has been linked to trial pieces.

Please see original documentation: https://sympa-community.github.io/community/lists.html

**Comment by gzcwnk** [comment]
Hi,

Is there a mailing list at all?

What is causing this?

Not Found

The requested URL /firstpasswd was not found on this server.

**Comment by ikedas** [comment]
@gzcwnk, could you please tell us how you operated?

If you want to join to a mailing list, go to info page of the list and click “Subscribe” link.

**Comment by gzcwnk** [comment]
"could you please tell us how you operated?"   I have no idea what you mean, maybe type it in french? and I'll get google to translate it.

**Comment by gzcwnk** [comment]
I sent subscribe email to the list and that seemed to have worked, but its gone to a moderator.

**Comment by gzcwnk** [comment]
Trying to login as listmatser to,

http://lists.victoria.ac.nz/firstpasswd

**Comment by ikedas** [comment]
I'm not a francophone. I mean, please describe what you did step-by-step. For example: "I opened a page (URL), clicked (label) button, ..., then a messsage (text) was shown."

**Comment by gzcwnk** [comment]
Hi, sorry.  I opened the sympa page for the first time, put in my email address as the listmaster and clicked on "first login?",

https://pasteboard.co/InpKC87.jpg

**Comment by ikedas** [comment]
I suppose "First login?" should be linked to <http://lists.victoria.ac.nz/sympa/firstpasswd>.

Could you please show setting in main config file (`/etc/sympa/sympa.conf`, or `/etc/sympa/sympa/sympa.conf` if any), especially in "wwsympa_url" line?

**Comment by gzcwnk** [comment]
#ssj start
#wwsympa_url         (You must define this parameter to enable web interface)
wwsympa_url        http://lists.victoria.ac.nz
#ssj fini

**Comment by ikedas** [comment]
> ```
> wwsympa_url http://lists.victoria.ac.nz
> ```

In your case, perhaps [`wwsympa_url`](https://sympa-community.github.io/gpldoc/man/sympa.conf.5.html#wwsympa_url) has to be:
```
wwsympa_url http://lists.victoria.ac.nz/sympa
```

**Comment by gzcwnk** [comment]
Ok that is fixed, thanks.
