### ISSUE TITLE
info.tt2 generates some noise in Apache error log

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#688]
Version
-------

6.2.44

Installation method
-------------------

rpm from https://copr.fedorainfracloud.org/coprs/xavierb/sympa/

RHEL 7.6

Expected behavior
-----------------

The list  "info" page should not generate entries in the Apache error log

Actual behavior
---------------

Each page view generates an error:

```
[Fri Jul 12 10:41:21.156711 2019] [proxy_fcgi:error] [pid 13008] [client 131.111.56.48:45994] AH01071: Got error 'Argument "" isn't numeric in numeric gt (>) at /usr/share/sympa/default/web_tt2/info.tt2 line 32.\n'
```

Additional information
----------------------

Appears to be down to the following in ```web_tt2/info.tt2```:

```
            [% IF mod_message > 0 %]
           ...
            [% IF mod_total_shared > 0 %]
```

If I replace that with:

``` 
           [% IF mod_message && (mod_message > 0) %]
          ...
           [% IF mod_total_shared && (mod_total_shared > 0) %]
```

The errors disappear.

**Comment by ikedas** [comment]
@dpc22, thanks for reporting bug! Your suggestion will be included in the next beta released in this weelend.  Thanks!
