### ISSUE TITLE
WWSympa: Make FastCGI support mandatory

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#69]
Currently (as of 6.2.22), WWSympa (wwsympa.fcgi) may use either FastCGI or CGI.  Latter is *un*useful in practical use.  CGI support would be given up and FastCGI would be made mandatory.

N.B.: SOAP server (sympa_soap_server.fcgi) requires FastCGI support.

**Comment by racke** [comment]
I second that. CGI should *die* ... ask @sawyerx.

**Comment by ikedas** [comment]
Merged, then this issue is closed.
