### ISSUE TITLE
Data too long for column 'include_sources_subscriber'

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#692]
Version
-------
6.2.22

Installation method
-------------------
RPM package sympa-6.2.22-1.20171002.RHEL7.x86_64

Expected behavior
-----------------
One list based on a sql query can get subscribers.

Actual behavior
---------------
The list cannot get its subscribers. The error in the log is :
Jul 16 16:26:06 tcgesympa2 wwsympa[44060]: err main::#1639 > main::do_edit_list#10765 > Sympa::List::on_the_fly_sync_include#7238 > Sympa::List::sync_include#7134 > Sympa::List::add_list_member#3955 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subsc       riber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, includ       e_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES (?, ?, ?,        ?, FROM_UNIXTIME(1563287166), FROM_UNIXTIME(1563287166), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)": (22001) Data too long for column 'include_sources_subscriber' at row 1

Jul 16 16:26:06 tcgesympa2 wwsympa[44060]: err main::#1639 > main::do_edit_list#10765 > Sympa::List::on_the_fly_sync_include#7238 > Sympa::List::sync_include#7134 > Sympa::List::add_list_member#3994 Unable to add subscriber jean.thomas@ext.dsi.cnrs.fr to table subscriber_table for list proriorecette@listes-rec.dsi.cnrs.fr

Additional information
----------------------
NONE

**Comment by ikedas** [comment]
This problem may be solved by #693.

As a workaround, you may extend the size of `include_sources_subscriber` field, such as:
```sql
ALTER TABLE subscriber_table CHANGE COLUMN
include_sources_subscriber include_sources_subscriber varchar(62);
```
(You look using MySQL/MariaDB)

**Comment by jth56000** [comment]
Hello Ikeda,

We have modified subscriber_table structure to set include_source_subscriber to varchar(100).
Bu we still have an error in sympa log :

Jul 17 14:50:56 tcgesympa2 wwsympa[46724]: err main::#1639 > main::do_edit_list#10765 > Sympa::List::on_the_fly_sync_include#7238 > Sympa::List::sync_include#7134 > Sympa::List::add_list_member#3955 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "INSERT INTO   (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES (?, ?, ?, ?, FROM_UNIXTIME(1563367856), FROM_UNIXTIME(1563367856), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)": (22001) Data too long for column 'include_sources_subscriber' at row 1

And in mariadb log : 

INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES ('listmaster-rec@dsi.cnrs.fr', NULL, 'proriorecette', 'listes-rec.dsi.cnrs.fr', FROM_UNIXTIME(1563368107), FROM_UNIXTIME(1563368107), 'mail', NULL, 'noconceal', '0', '1', '0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26,0e8f8b26', NULL, NULL, NULL, NULL, 0)

Thank you for your help.
Jean

**Comment by jth56000** [comment]
I can add this is critical for us, we have alsohave this error when migrating from
RedHat 5.8, sympa 6.2.22 code source install, mysql-server-5.5.25a-1.el5.remi
To
RedHat 7.6, sympa 6.2.22 RPM packages, rh-mariadb102-mariadb-server-10.2.22-1.el7.x86_64

Regards,
Jean

**Comment by ikedas** [comment]
Though I don't know why, inclusion from data source doesn't work properly.  A way to fix quickly is as following:
1. Remove all subscribers who are included from data source(s).
2. Remove all entries of the subscribers above in "exclusion" table of the list (that is shown by "Exclusion" button).
3. Synchronize the list with data source(s) again (by waiting for an hour, or synchronize immediately by clicking "Synchronize members with data sources" button).

**Comment by jth56000** [comment]
Hello Ikeda, for your information thi issue is our priority since we cannot migrate our production server.

**Comment by ikedas** [comment]
Hi @jth56000,
Could you please show sql log too?

**Comment by jth56000** [comment]
Here is mariadb log when synchronizing :


190722  9:00:31    16 Query     SELECT id_session AS id_session, prev_id_session AS prev_id, date_session AS "date", remote_addr_session AS remote_addr, email_session AS email, data_session AS data, hit_session AS hit, start_date_session AS start_date, refresh_date_session AS refresh_date FROM session_table WHERE id_session = '32172024478724' AND prev_id_session IS NOT NULL OR prev_id_session = '32172024478724'
                   16 Query     SELECT COUNT(*) FROM user_table WHERE email_user = 'listmaster-rec@dsi.cnrs.fr'
                   16 Query     SELECT email_user AS email, gecos_user AS gecos, password_user AS password, cookie_delay_user AS cookie_delay, lang_user AS lang, attributes_user AS attributes, data_user AS data, last_login_date_user AS last_login_date, wrong_login_count_user AS wrong_login_count, last_login_host_user AS last_login_host FROM user_table WHERE email_user = 'listmaster-rec@dsi.cnrs.fr'
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr'
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr' AND user_subscriber = 'listmaster-rec@dsi.cnrs.fr'
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr' AND bounce_subscriber IS NOT NULL
                   16 Query     SELECT bounce_subscriber AS "bounce", bounce_address_subscriber AS "bounce_address", bounce_score_subscriber AS "bounce_score", custom_attribute_subscriber AS "custom_attribute", UNIX_TIMESTAMP(date_subscriber) AS "date", user_subscriber AS "email", suspend_end_date_subscriber AS "enddate", comment_subscriber AS "gecos", include_sources_subscriber AS "id", included_subscriber AS "included", number_messages_subscriber AS "number_messages", reception_subscriber AS "reception", suspend_start_date_subscriber AS "startdate", subscribed_subscriber AS "subscribed", suspend_subscriber AS "suspend", topics_subscriber AS "topics", UNIX_TIMESTAMP(update_subscriber) AS "update_date", visibility_subscriber AS "visibility"
          FROM subscriber_table
          WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr'  ORDER BY email
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr'
                   17 Connect   sympadbusr@localhost as anonymous on sympadb
                   17 Query     SET NAMES 'utf8mb4'
                   17 Query     SELECT user_admin FROM admin_table WHERE robot_admin = 'listes-rec.dsi.cnrs.fr' and role_admin = 'owner'
                   16 Query     DELETE FROM inclusion_table WHERE target_inclusion = 'propriorecette@listes-rec.dsi.cnrs.fr' AND role_inclusion = 'member' AND update_epoch_inclusion < '1563778831'
                   16 Query     SELECT user_exclusion AS email, date_exclusion AS "date" FROM exclusion_table WHERE list_exclusion = 'propriorecette' AND robot_exclusion = 'listes-rec.dsi.cnrs.fr'
                   17 Quit
                   16 Query     SELECT user_exclusion AS email, date_exclusion AS "date" FROM exclusion_table WHERE list_exclusion = 'propriorecette' AND robot_exclusion = 'listes-rec.dsi.cnrs.fr'
                   16 Query     INSERT INTO stat_table (date_stat, email_stat, operation_stat, list_stat, daemon_stat, user_ip_stat, robot_stat, parameter_stat, read_stat) VALUES ('1563778831', 'catherine.mendiboure@dsi.cnrs.fr', 'add_or_subscribe', 'propriorecette', 'wwsympa', NULL, 'listes-rec.dsi.cnrs.fr', '', '0')
                   16 Query     INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES ('catherine.mendiboure@dsi.cnrs.fr', NULL, 'propriorecette', 'listes-rec.dsi.cnrs.fr', FROM_UNIXTIME(1563778831), FROM_UNIXTIME(1563778831), 'mail', NULL, 'noconceal', '0', '1', '093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c', NULL, NULL, NULL, NULL, 0)
                   16 Query     SET NAMES 'utf8mb4'
                   16 Query     INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES ('catherine.mendiboure@dsi.cnrs.fr', NULL, 'propriorecette', 'listes-rec.dsi.cnrs.fr', FROM_UNIXTIME(1563778831), FROM_UNIXTIME(1563778831), 'mail', NULL, 'noconceal', '0', '1', '093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c', NULL, NULL, NULL, NULL, 0)
                   16 Query     SELECT user_exclusion AS email, date_exclusion AS "date" FROM exclusion_table WHERE list_exclusion = 'propriorecette' AND robot_exclusion = 'listes-rec.dsi.cnrs.fr'
                   16 Query     INSERT INTO stat_table (date_stat, email_stat, operation_stat, list_stat, daemon_stat, user_ip_stat, robot_stat, parameter_stat, read_stat) VALUES ('1563778831', 'listmaster-rec@dsi.cnrs.fr', 'add_or_subscribe', 'propriorecette', 'wwsympa', NULL, 'listes-rec.dsi.cnrs.fr', '', '0')
                  16 Query     INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES ('listmaster-rec@dsi.cnrs.fr', NULL, 'propriorecette', 'listes-rec.dsi.cnrs.fr', FROM_UNIXTIME(1563778831), FROM_UNIXTIME(1563778831), 'mail', NULL, 'noconceal', '0', '1', '093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c', NULL, NULL, NULL, NULL, 0)
                   16 Query     SET NAMES 'utf8mb4'
                   16 Query     INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES ('listmaster-rec@dsi.cnrs.fr', NULL, 'propriorecette', 'listes-rec.dsi.cnrs.fr', FROM_UNIXTIME(1563778831), FROM_UNIXTIME(1563778831), 'mail', NULL, 'noconceal', '0', '1', '093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c', NULL, NULL, NULL, NULL, 0)
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr'
                   16 Query     SELECT bounce_subscriber AS "bounce", bounce_address_subscriber AS "bounce_address", bounce_score_subscriber AS "bounce_score", custom_attribute_subscriber AS "custom_attribute", UNIX_TIMESTAMP(date_subscriber) AS "date", user_subscriber AS "email", suspend_end_date_subscriber AS "enddate", comment_subscriber AS "gecos", include_sources_subscriber AS "id", included_subscriber AS "included", number_messages_subscriber AS "number_messages", reception_subscriber AS "reception", suspend_start_date_subscriber AS "startdate", subscribed_subscriber AS "subscribed", suspend_subscriber AS "suspend", topics_subscriber AS "topics", UNIX_TIMESTAMP(update_subscriber) AS "update_date", visibility_subscriber AS "visibility"
          FROM subscriber_table
          WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr'  ORDER BY email
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr'
                   16 Query     SELECT bounce_subscriber AS "bounce", bounce_address_subscriber AS "bounce_address", bounce_score_subscriber AS "bounce_score", custom_attribute_subscriber AS "custom_attribute", UNIX_TIMESTAMP(date_subscriber) AS "date", user_subscriber AS "email", suspend_end_date_subscriber AS "enddate", comment_subscriber AS "gecos", include_sources_subscriber AS "id", included_subscriber AS "included", number_messages_subscriber AS "number_messages", reception_subscriber AS "reception", suspend_start_date_subscriber AS "startdate", subscribed_subscriber AS "subscribed", suspend_subscriber AS "suspend", topics_subscriber AS "topics", UNIX_TIMESTAMP(update_subscriber) AS "update_date", visibility_subscriber AS "visibility" FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr' ORDER BY email
                   16 Query     INSERT INTO logs_table (date_logs, usec_logs, robot_logs, list_logs, action_logs, parameters_logs, target_email_logs, msg_id_logs, status_logs, error_type_logs, user_email_logs, client_logs, daemon_logs) VALUES ('1563778831', '469323', 'listes-rec.dsi.cnrs.fr', 'propriorecette', 'review', '', 'listmaster-rec@dsi.cnrs.fr', NULL, 'success', NULL, 'listmaster-rec@dsi.cnrs.fr', '10.238.10.3', 'wwsympa')
                   16 Query     SELECT count(*) FROM subscriber_table WHERE list_subscriber = 'propriorecette' AND robot_subscriber = 'listes-rec.dsi.cnrs.fr' AND user_subscriber = 'listmaster-rec@dsi.cnrs.fr'
                   16 Query     SELECT COUNT(*) FROM inclusion_table WHERE source_inclusion = 'propriorecette@listes-rec.dsi.cnrs.fr'
                   16 Query     SELECT id_session FROM session_table WHERE prev_id_session = '32172024478724'
                   16 Query     UPDATE session_table SET date_session = '1563778831', remote_addr_session = '10.238.10.3', robot_session = 'listes-rec.dsi.cnrs.fr', email_session = 'listmaster-rec@dsi.cnrs.fr', start_date_session = '1563774716', hit_session = '8', data_session = ';auth=\"classic\";is_family_owner=\"HASH(0x5cefa00)\";unauthenticated_email=\"\";lang=\"fr\";redirect_url=\"https://10.245.201.80/wws/review/propriorecette\";data=\"\"' WHERE id_session = '32172024478724' AND prev_id_session IS NOT NULL OR prev_id_session = '32172024478724'

**Comment by ikedas** [comment]
It's not releated to sympa log.  Please delete it.

**Comment by jth56000** [comment]
In the sympa log from this morning synchronisation I have again :
#grep -i "data too long" /var/log/sympa
Jul 22 09:00:31 tcgesympa2 wwsympa[1880]: err main::#1638 > main::do_review#4862 > Sympa::List::on_the_fly_sync_include#7238 > Sympa::List::sync_include#7134 > Sympa::List::add_list_member#3955 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES (?, ?, ?, ?, FROM_UNIXTIME(1563778831), FROM_UNIXTIME(1563778831), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)": (22001) Data too long for column 'include_sources_subscriber' at row 1
Jul 22 09:00:31 tcgesympa2 wwsympa[1880]: err main::#1638 > main::do_review#4862 > Sympa::List::on_the_fly_sync_include#7238 > Sympa::List::sync_include#7134 > Sympa::List::add_list_member#3955 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "INSERT INTO subscriber_table (user_subscriber, comment_subscriber, list_subscriber, robot_subscriber, date_subscriber, update_subscriber, reception_subscriber, topics_subscriber, visibility_subscriber, subscribed_subscriber, included_subscriber, include_sources_subscriber, custom_attribute_subscriber, suspend_subscriber, suspend_start_date_subscriber, suspend_end_date_subscriber, number_messages_subscriber) VALUES (?, ?, ?, ?, FROM_UNIXTIME(1563778831), FROM_UNIXTIME(1563778831), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)": (22001) Data too long for column 'include_sources_subscriber' at row 1

**Comment by ikedas** [comment]
As a workaround, you can add the user by doing:

1. Remove the subscriber, if they have been included in the list.
2. Add the subscriber manually, using "Add" button on "Manage list members" page.
2. Check if the entry of the subscriber above _is included_ in "exclusion" table, or add the entry (the table is shown by "Exclusion" button).
4. Synchronize the list with data source(s) again (by waiting for an hour, or synchronize immediately by clicking "Synchronize members with data sources" button).
5. Repeat 1. to 4. by each subscriber that causes error.

**Comment by jth56000** [comment]
I can’t do that on the production server.
Many lists and uses are impacted by this issue.

**Comment by racke** [comment]
> This sql log is not releated to sympa log. Please delete it.

It could be relevant as the actual value of include_sources_subscriber is shown here, e.g.:

'093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c'

That might be the problem ... why Sympa does insert the same value multiple times?

**Comment by ikedas** [comment]
> I can’t do that on the production server. Many lists and uses are impacted by this issue.

First, have you tried the [procedure](#issuecomment-512710819) I wrote at 18th June?

If you have done that procedure and error about "Data too long" occurred again, there may be some problem (such as loop on inclusion).  So I suggested a workaround.

Second, why can't you try the [workaround](issuecomment-513675207) I wrote on just above?

**Comment by jth56000** [comment]
I did the procedure on 18th June but still have the error.

**Comment by jth56000** [comment]
On my example the list is simple the inclusion is an sql query in sympa database to include all list owners :
SELECT user_admin FROM admin_table WHERE robot_admin = 'services.cnrs.fr' and role_admin = 'owner'

There is no loop on inclusion in the list.

De : IKEDA Soji <notifications@github.com>
Envoyé : lundi 22 juillet 2019 10:07
À : sympa-community/sympa <sympa@noreply.github.com>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)


I can’t do that on the production server. Many lists and uses are impacted by this issue.

First, have you tried the procedure I wrote at 18th June?

If you have done that procedure and error about "Data too long" occurred again, there may be some problem (such as loop on inclusion). So I suggested a workaround.

Second, why can't you try the workaround<issuecomment-513675207> I wrote on just above?

**Comment by ikedas** [comment]
> I did the procedure on 18th June but still have the error.

If you have done that procedure and error about "Data too long" occurred again, there may be some problem (such as loop on inclusion).  I think that, to investigate the reason of this problem drastically, you once will have to remove all setting about inclusion.  It is not realistic idea.

So I suggested a [workaround](issuecomment-513675207).

**Comment by racke** [comment]
Ok but why does Sympa write these duplicated values?

**Comment by jth56000** [comment]
The work around you suggested was to set include_sources_subscriber varchar(62).
I set it to varchar(100) and still have the issue?

**Comment by racke** [comment]
You can safely set it to varchar(255).

**Comment by ikedas** [comment]
> The work around you suggested was to set include_sources_subscriber varchar(62). I set it to varchar(100) and still have the issue?

The workaround I suggested is:

> As a workaround, you can add the user by doing:
> 
> 1. Remove the subscriber, if they have been included in the list.
> 2. Add the subscriber manually, using "Add" button on "Manage list members" page.
> 3. Check if the entry of the subscriber above _is included_ in "exclusion" table, or add the entry (the table is shown by "Exclusion" button).
> 4. Synchronize the list with data source(s) again (by waiting for an hour, or synchronize immediately by clicking "Synchronize members with data sources" button).
> 5. Repeat 1. to 4. by each subscriber that causes error.

What is the reason you cannot do it? (it is pure question, not rhetorical.)

**Comment by jth56000** [comment]
It works on the Integration server, I manage to synchronize my list.
But I still have the error on the new production server.

De : Stefan Hornburg (Racke) <notifications@github.com>
Envoyé : lundi 22 juillet 2019 10:19
À : sympa-community/sympa <sympa@noreply.github.com>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)


You can safely set it to varchar(255).

**Comment by jth56000** [comment]
On July 16een when we see se cannot migrate because of this error we came back on the old server.
I have not the interface on the new server, it points on the old server.
I cannot add users on the new server by the interface.

De : IKEDA Soji <notifications@github.com>
Envoyé : lundi 22 juillet 2019 10:22
À : sympa-community/sympa <sympa@noreply.github.com>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)


The work around you suggested was to set include_sources_subscriber varchar(62). I set it to varchar(100) and still have the issue?

The workaround I suggested is:

As a workaround, you can add the user by doing:

  1.  Remove the subscriber, if they have been included in the list.
  2.  Add the subscriber manually, using "Add" button on "Manage list members" page.
  3.  Check if the entry of the subscriber above is included in "exclusion" table, or add the entry (the table is shown by "Exclusion" button).
  4.  Synchronize the list with data source(s) again (by waiting for an hour, or synchronize immediately by clicking "Synchronize members with data sources" button).
  5.  Repeat 1. to 4. by each subscriber that causes error.

What is the reason you cannot do it? (it is pure question, not rhetorical.)

**Comment by ikedas** [comment]
I see.  Now you are working on old server. Is it true?

If it is true, could you please tell us:
- Is the error occur on the old server?
- Version and installation method of the "old" server.

**Comment by jth56000** [comment]
Yes we are working back on the old server where we do not have the error.
The old server is running 6.2.22 code source install.

**Comment by ikedas** [comment]
It means that there are some differences between old and new servers (and environment like network).  Please check them at first.

You would be better to try migrating one or a few lists at first, and to see if they will be migrated successful.

**Comment by jth56000** [comment]
Ø  It means that there are some differences between old and new servers (and environment like network). Please check them at first.

Ø  You would be better to try migrating one or a few lists at first, and to see if they will be migrated successful.
Environment differences are mainly as followed :
Old server : redhat 5.8 / mysql 5.5.25a (mysql-server-5.5.25a-1.el5.remi)
New server : Redhat 7.6 / mariadb 10.2.22 (rh-mariadb102-mariadb-server-10.2.22-1.el7.x86_64)

How to migrate list one by one since we keep the same robot name and we have 4378 lists with 2883926 subscribers ?

**Comment by jth56000** [comment]
No answers for this ?

De : Stefan Hornburg (Racke) <notifications@github.com>
Envoyé : lundi 22 juillet 2019 10:02
À : sympa-community/sympa <sympa@noreply.github.com>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)


This sql log is not releated to sympa log. Please delete it.

It could be relevant as the actual value of include_sources_subscriber is shown here, e.g.:

'093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c'

That might be the problem ... why Sympa does insert the same value multiple times?

**Comment by ikedas** [comment]
It’s obvious that there are any difference, because one failed and another didn’t fail.

You may create a test list on the old server and copy it’s configuration to the new server.  These lists may not affect existing lists and subscribers.

——
Sorry but I’m living in Japan and will go asleep soon.

**Comment by jth56000** [comment]
Ø  You may create a test list on the old server and copy it’s configuration to the new server. These lists may not affect existing lists and subscribers.

We could reproduce the issue on the integration server which is the same configuration to the production server by creating a similar list to production list.

Have a good night.

**Comment by jth56000** [comment]
I mean similar to the new production server.

De : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>
Envoyé : lundi 22 juillet 2019 15:45
À : sympa-community/sympa <reply@reply.github.com>; sympa-community/sympa <sympa@noreply.github.com>
Cc : Mention <mention@noreply.github.com>; DSI Gestionnaire de Listes <listmaster@dsi.cnrs.fr>
Objet : RE: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)


Ø  You may create a test list on the old server and copy it’s configuration to the new server. These lists may not affect existing lists and subscribers.

We could reproduce the issue on the integration server which is the same configuration to the production server by creating a similar list to production list.

Have a good night.

**Comment by jth56000** [comment]
Ikeda,

Still no answers for this ?
What does this value means ?

Jean

De : THOMAS Jean
Envoyé : lundi 22 juillet 2019 15:19
À : 'sympa-community/sympa' <reply@reply.github.com>; sympa-community/sympa <sympa@noreply.github.com>
Cc : Mention <mention@noreply.github.com>; DSI Gestionnaire de Listes <listmaster@dsi.cnrs.fr>
Objet : RE: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)

No answers for this ?

De : Stefan Hornburg (Racke) <notifications@github.com<mailto:notifications@github.com>>
Envoyé : lundi 22 juillet 2019 10:02
À : sympa-community/sympa <sympa@noreply.github.com<mailto:sympa@noreply.github.com>>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr<mailto:jean.thomas@ext.dsi.cnrs.fr>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Objet : Re: [sympa-community/sympa] Data too long for column 'include_sources_subscriber' (#692)


This sql log is not releated to sympa log. Please delete it.

It could be relevant as the actual value of include_sources_subscriber is shown here, e.g.:

'093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c,093cb65c'

That might be the problem ... why Sympa does insert the same value multiple times?

**Comment by ikedas** [comment]
This problem may be solved by #693.  If you can wait for the next release, you may check if the problem will be solved with current beta, 6.2.45b.2.

**Comment by ikedas** [comment]
@jth56000, could you check if the problem was solved?

**Comment by jth56000** [comment]
@jth56000<https://github.com/jth56000>, could you check if the problem was solved?

I do not have the issue since I set include_source_subscriber to varchar(255).

**Comment by ikedas** [comment]
6.2.45b.2 will no longer use `include_sources_subscriber` field.  Did you check this version?

**Comment by jth56000** [comment]
Ø  6.2.45b.2 will no longer use include_sources_subscriber field. Did you check this version?

No I did not check this version.

I still have include_source_subscriber column in subscriber_table.

What do you mean by “will no longer use” ?

**Comment by ikedas** [comment]
I undertand. You don't use 6.2.45b.2. If you have no more questions, I'll close this issue.
