### ISSUE TITLE
Improving data sources

### ISSUE THREAD

**Issue by ikedas** [sympa-community/sympa#693]
(Part of) Expected changes
----------------------------
* Data sources won't overwrite display name (gecos) of existing subscriber: It is assigned only when a new user is added (included) from data source, or if it is added (subscribed) by users.
* Name of only one data source that was actually included will be shown in subscriber table of web interface.
* Size of `include_sources_subscriber` database field will no longer limit the number of datasources.

See details in the PR #516.

Context
-------
These changes will be included in the next beta (6.2.45b.1).  For more details about changes see the PR page below.

**Comment by racke** [comment]
Why would we limit the size of include_sources_subscriber to varchar(62)? There is no difference in storage for larger field sizes and this field isn't indexed.

**Comment by ikedas** [comment]
> Why would we limit the size of include_sources_subscriber to varchar(62)? There is no difference in storage for larger field sizes and this field isn't indexed.

You says about issue#692.  Currently (until 6.2.44) `include_sources_subscriber` is defined as `varchar(50)` by default.  Indeed the size itself need not limited, but I considered compatibility.

**Comment by racke** [comment]
Compatibility with what?

**Comment by ikedas** [comment]
If the field type was changed to `text`, `sympa.pl --health_check` will complain that database structure is broken.

**Comment by racke** [comment]
varchar(255) wouldn't be text and still a lot larger.

**Comment by ikedas** [comment]
Anyways it isn't big deal with PR#516.
