### ISSUE TITLE
sympa will not boot on RHEL7 with remote mysql8.0 database on reboot

### ISSUE THREAD

**Issue by gzcwnk** [sympa-community/sympa#694]
[root@vuwunicolistst1 ~]# rpm -q sympa
sympa-6.2.44-1.el7.x86_64
[root@vuwunicolistst1 ~]# more /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.6 (Maipo)
[root@vuwunicolistst1 ~]#

-------

Installation method
-------------------

rpm, via repo

Expected behavior
-----------------

sympa starts on reboot

Actual behavior
---------------

sympa fails to start on boot but can be manually start later.

Tried setting 90second delay in systemd but of no use (fail).
Tried setting IP address of db server instead of FQDN no difference (fail).

[root@vuwunicolistst1 ~]# systemctl status sympa
● sympa.service - Sympa mailing list manager
   Loaded: loaded (/usr/lib/systemd/system/sympa.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/sympa.service.d
           └─dependencies.conf
   Active: failed (Result: exit-code) since Wed 2019-07-17 15:38:47 NZST; 1min 1s ago
  Process: 5247 ExecStartPre=/usr/sbin/sympa.pl --health_check (code=exited, status=255)
  Process: 5241 ExecStartPre=/bin/chown sympa:sympa /run/sympa (code=exited, status=0/SUCCESS)
  Process: 5159 ExecStartPre=/bin/mkdir -p /run/sympa (code=exited, status=0/SUCCESS)

Jul 17 15:38:44 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: Starting Sympa mailing list manager...
Jul 17 15:38:46 vuwunicolistst1.ods.vuw.ac.nz sympa/health_check[5247]: info main:: Configuration file read, default log level 0
Jul 17 15:38:46 vuwunicolistst1.ods.vuw.ac.nz sympa/health_check[5247]: err main::#230 > Sympa::DatabaseManager::probe_db#94 > Sympa::DatabaseManager::instance#54 > Sympa::DatabaseDriver:...
Jul 17 15:38:46 vuwunicolistst1.ods.vuw.ac.nz sympa/health_check[5247]: err main::#230 > Sympa::DatabaseManager::probe_db#96 Could not check the database structure.  Make sure th...available
Jul 17 15:38:46 vuwunicolistst1.ods.vuw.ac.nz sympa.pl[5247]: Database sympa defined in sympa.conf has not the right structure or is unreachable. Verify db_xxx parameters in sympa.conf
Jul 17 15:38:47 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: sympa.service: control process exited, code=exited status=255
Jul 17 15:38:47 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: Failed to start Sympa mailing list manager.
Jul 17 15:38:47 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: Unit sympa.service entered failed state.
Jul 17 15:38:47 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: sympa.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@vuwunicolistst1 ~]# systemctl restart sympa
[root@vuwunicolistst1 ~]# systemctl status sympa
● sympa.service - Sympa mailing list manager
   Loaded: loaded (/usr/lib/systemd/system/sympa.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/sympa.service.d
           └─dependencies.conf
   Active: active (running) since Wed 2019-07-17 15:39:57 NZST; 2s ago
  Process: 6535 ExecStart=/usr/sbin/sympa_msg.pl (code=exited, status=0/SUCCESS)
  Process: 6532 ExecStartPre=/usr/sbin/sympa.pl --health_check (code=exited, status=0/SUCCESS)
  Process: 6530 ExecStartPre=/bin/chown sympa:sympa /run/sympa (code=exited, status=0/SUCCESS)
  Process: 6528 ExecStartPre=/bin/mkdir -p /run/sympa (code=exited, status=0/SUCCESS)
 Main PID: 6538 (sympa_msg.pl)
   CGroup: /system.slice/sympa.service
           └─6538 /usr/bin/perl /usr/sbin/sympa_msg.pl

Jul 17 15:39:56 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: Starting Sympa mailing list manager...
Jul 17 15:39:56 vuwunicolistst1.ods.vuw.ac.nz sympa/health_check[6532]: info main:: Configuration file read, default log level 0
Jul 17 15:39:57 vuwunicolistst1.ods.vuw.ac.nz sympa_msg[6535]: info main::_load() Configuration file read, default log level 0
Jul 17 15:39:57 vuwunicolistst1.ods.vuw.ac.nz sympa_msg[6535]: notice Sympa::Process::daemonize() Starting sympa/msg daemon, PID 6538
Jul 17 15:39:57 vuwunicolistst1.ods.vuw.ac.nz systemd[1]: Started Sympa mailing list manager.
Jul 17 15:39:57 vuwunicolistst1.ods.vuw.ac.nz sympa_msg[6538]: notice main:: Sympa/msg 6.2.44 Started
[root@vuwunicolistst1 ~]# 

Additional information

----------------------

**Comment by gzcwnk** [comment]
from /var/log/sympa.log

========
Jul 17 15:38:46 vuwunicolistst1 sympa/health_check[5247]: info main:: Configuration file read, default log level 0
Jul 17 15:38:46 vuwunicolistst1 sympa/health_check[5247]: err main::#230 > Sympa::DatabaseManager::probe_db#94 > Sympa::DatabaseManager::instance#54 > Sympa::DatabaseDriver::MySQL::connect#58 > Sympa::Database::connect#157 Can't connect to Database Sympa::DatabaseDriver::MySQL <db_host=vuwunicomysqlt3.ods.vuw.ac.nz;db_name=sympa;db_user=svc_sympa>: Can't connect to MySQL server on 'vuwunicomysqlt3.ods.vuw.ac.nz' (101)
Jul 17 15:38:46 vuwunicolistst1 sympa/health_check[5247]: err main::#230 > Sympa::DatabaseManager::probe_db#96 Could not check the database structure.  Make sure that database connection is available
Jul 17 15:38:50 vuwunicolistst1 wwsympa[5446]: info main:: WWSympa started, process 5446
Jul 17 15:38:50 vuwunicolistst1 wwsympa[5447]: info main:: WWSympa started, process 5447
Jul 17 15:38:50 vuwunicolistst1 wwsympa[5449]: info main:: WWSympa started, process 5449
Jul 17 15:38:50 vuwunicolistst1 wwsympa[5448]: info main:: WWSympa started, process 5448
Jul 17 15:38:50 vuwunicolistst1 wwsympa[5450]: info main:: WWSympa started, process 5450
Jul 17 15:39:56 vuwunicolistst1 sympa/health_check[6532]: info main:: Configuration file read, default log level 0
Jul 17 15:39:57 vuwunicolistst1 sympa_msg[6535]: info main::_load() Configuration file read, default log level 0
Jul 17 15:39:57 vuwunicolistst1 sympa_msg[6535]: notice Sympa::Process::daemonize() Starting sympa/msg daemon, PID 6538
Jul 17 15:39:57 vuwunicolistst1 sympa_msg[6538]: notice main:: Sympa/msg 6.2.44 Started
Jul 17 15:39:59 vuwunicolistst1 bulk[6539]: info main:: Configuration file read, default log level 0
Jul 17 15:39:59 vuwunicolistst1 bulk[6539]: notice Sympa::Process::daemonize() Starting bulk daemon, PID 6544
Jul 17 15:39:59 vuwunicolistst1 task_manager[6542]: info main:: Configuration file read, default log level 0
Jul 17 15:39:59 vuwunicolistst1 task_manager[6542]: notice Sympa::Process::daemonize() Starting task_manager daemon, PID 6545
Jul 17 15:39:59 vuwunicolistst1 bulk[6544]: notice main:: Bulk 6.2.44 Started
Jul 17 15:39:59 vuwunicolistst1 task_manager[6542]: notice main:: Task_Manager 6.2.44 Started
Jul 17 15:39:59 vuwunicolistst1 archived[6547]: notice main:: Archived 6.2.44 Started
Jul 17 15:39:59 vuwunicolistst1 bounced[6548]: notice main:: Bounced 6.2.44 Started
[root@vuwunicolistst1 log]# 

=========

**Comment by ikedas** [comment]
Hi @gzcwnk,

Havn't you edited `/etc/systemd/system/sympa.service.d/dependencies.conf`?  If you have uncommented lines for `mariadb.service`, you need not doing it: These lines are needed for *locally* managed db server.

Instead, with *remote* db server. you would be better to add these lines to that file:
```
[Unit]

After=network-online.target
Wants=network-online.target
```
to make Sympa services wait for network being up.  See [here](https://unix.stackexchange.com/questions/126009/) or [here](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/) for details.

**Comment by gzcwnk** [comment]
fixed thanks
