### ISSUE TITLE
Owner/Moderator can't send mail to list

### ISSUE THREAD

**Issue by Sympa-test** [sympa-community/sympa#695]
Expected behavior
-----------------
The owner and moderator of a list should send a mail to that list.

Actual behavior
---------------
When the owner/moderator of that list send a mail to it, an error occurs : ""Votre message pour la liste...a été rejeté.
La diffusion de message est réservée aux modérateurs.".

Additional information
----------------------
The authorization scenario is "send.newsletterkeyonly". I tried to switch to "send.newsletter" but the issue is stil the same.

In logs, we can see : "rejected() because sender not allowed" and "template=delivery_status_notification; action=failed; reason=send_editor; status=5.7.1".

Can someone help me ? 

Regards,

**Comment by ikedas** [comment]
Hi @Sympa-test,
One possible reason is that address of message sender (`From:` header field) is not address of list moderator.  Could you check the message acutually sent to the list?

**Comment by Sympa-test** [comment]
According to the logs the "sender" parameter is the list's moderator address.
But i can ask for the original of the mail.

**Comment by ikedas** [comment]
Close for the present.
