### ISSUE TITLE
sympa_aliases not updated because of lock

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#697]
Sympa 6.2.44 installed via sympa-ja.org.rhel.repo
Postfix
RHEL 7.6

Expected behavior
-------------------

What should happen:

Upon creation/closure of a liste, /var/lib/symp/sympa_aliases file is updated (worked in version 6.2.42!)

Actual behavior
-----------------

What actually happens:
sympa_aliases file *not* updated, and following is logged:

[...]
> Jul 18 05:08:32 prdsympa sympa[3276]: err main::#849 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_automatic_list::_twist#245 > Sympa::Aliases::Template::add#106 Can't lock /var/lib/sympa/sympa_aliases
[...]
> Jul 18 08:35:12 prdsympa sympa[22013]: err main::#604 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::close_list::_twist#122 > Sympa::Request::Handler::close_list::_close#155 > Sympa::Aliases::Template::del#173 Can't lock /var/lib/sympa/sympa_aliases
[...]

Additional information
---------------

This was broken upon upgrade from v.6.2.42 -> v.6.2.44. v6.2.43b.1 changelog mentions:
> Sympa::Aliases::Template creates exclusive lock on local storage #593, #602 (ikedas)
which I assume is the reason I'm seeing the above.

Thanks for looking into this!

Chris

----------------------

**Comment by ikedas** [comment]
Hi @laerm,

Could you please check if `/var/lib/sympa/` (directory) and `/var/lib/sympa/sympa_aliases` (file) are writable by sympa user? What is the result of `ls -la /var/lib/sympa/`?

**Comment by laerm** [comment]
Hello @ikedas ,

Thank you for your reply. The /var/lib/sympa/sympa_aliases (file) is writeable by the sympa user. The /var/lib/sympa/ (directory) was not. Have made it writeable by the sympa group and will report back to see if the issue is still present early next week.

**Comment by laerm** [comment]
I can confirm it was simply a permissions issue. However, a 755 on /var/lib/sympa and chgrp sympa was not sufficient. I ended up giving 777 for now, to be sure it was a permissions issue. Aliases are now added/removed correctly.

**Comment by ikedas** [comment]
777 is __dangerous__. Please do

chmod 755 /var/lib/sympa
chown sympa /var/lib/sympa

And, if you enabled SELinux, please disable it.

**Comment by laerm** [comment]
Hi @ikedas 

Sorry, my message wasn't clear. I added 777 just to make sur it was a permissions issue. 755 + chown sympa works as intended.

Cheers
