### ISSUE TITLE
6.2.44 Cannot delete a moderator/owner

### ISSUE THREAD

**Issue by bohwaz** [sympa-community/sympa#698]
Version
-------
6.2.44

Installation method
-------------------
RPM

Expected behavior
-----------------
When checking the box and the clicking the delete icon, it should delete the moderator or owner.

Actual behavior
---------------
Nothing happens. Dev console tells me there is no event listener on the icon.

**Comment by ikedas** [comment]
Hi @bohwaz,

After you checked checkboxes, did you click "_Update_" button below?

**Comment by ikedas** [comment]
This is an example:

![issue-698](https://user-images.githubusercontent.com/5743546/61862322-abe4ab80-af08-11e9-977a-d3802f5e8955.png)

**Comment by bohwaz** [comment]
No I clicked the "delete" icon above the checkbox, which changes the cursor to indicate that it is a clickable action ;)

If the "update" button means "delete the checked editors" it probably needs to be renamed :)

**Comment by ikedas** [comment]
“Delete” icon makes checkboxes of all users checked. “Update” button makes deletion (and the other modifications) happen in reality. How may we rename them?

**Comment by ldidry** [comment]
"Apply modifications", maybe?

**Comment by ikedas** [comment]
I agree to @ldidry.

**Comment by bohwaz** [comment]
Thanks that's an improvement, but IMHO the button should also be below the owners list, as it's not straightforward that the button applies to the whole page and not only the "add owner" form.
