### ISSUE TITLE
Log list not sorted for date

### ISSUE THREAD

**Issue by MorenoUniTN** [sympa-community/sympa#70]
Hi to all,
today i find a issue for log list in the sympa 6.2.20. Infact log is not order by date, even if sorting is set by date.
![sympaerr_edit](https://user-images.githubusercontent.com/29304925/31070562-196953e2-a761-11e7-94e7-f94ebc4ebe8c.png)

**Comment by ikedas** [comment]
Merged bug fix will be available on the next beta in November.  Thanks for lucid bug report!
