### ISSUE TITLE
stats page generates entries in Apache error_log

### ISSUE THREAD

**Issue by dpc22** [sympa-community/sympa#700]
Version
-------

Sympa 6.2.44

Installation method
-------------------

rpm from https://copr.fedorainfracloud.org/coprs/xavierb/sympa/

Expected behavior
-----------------

Should be able to view lists "Statistics" page:

```
/sympa/stats/test-dpc99
```

 without noise in Apache error log.

Actual behavior
---------------

I see the following error:

```
closedir() attempted on invalid dirhandle DIR at /usr/share/sympa/lib/Sympa/Tools/File.pm line 214.\n
```

**Comment by ikedas** [comment]
Hi @dpc22,

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/702.patch) and check if the problem will be solved?

**Comment by dpc22** [comment]
That seems to have done the trick. Thank you.

**Comment by ikedas** [comment]
@dpc22, thanks for confirming! The fix will be included in the next beta release in Saturday.
