### ISSUE TITLE
How do I change the listmaster email address and then change the password?

### ISSUE THREAD

**Issue by gzcwnk** [sympa-community/sympa#701]
I need to change the listmaster's email address and set a new password, can this be done?

**Comment by ikedas** [comment]
Listmasdters' emails may be changed by editing `listmaster` parameter in (as global setting) `sympa.conf` or (as the listmasters specific to a domain) `robot.conf`.

There are no special ways to set new password for listmasgters: Their password may be set in the same way as the other users.

**Comment by ikedas** [comment]
There seems no more questions.  Close.
