### ISSUE TITLE
Sympa Mailing lists with Exchange 2016 Server 

### ISSUE THREAD

**Issue by Azzmoh** [sympa-community/sympa#712]
Hi 

We are currently using Sympa as a mailing list server and everything from Sympa is passed on to Exim MTA's.
We are introducing Exchange 2016 servers and would like to know how to configure SYMPA to use Exchange 2016 server for mail routing?

Many Thanks

**Comment by qosobrin** [comment]
Exchange 2016 server for mail routing? What do you mean with that?  Suppose you are working for domain.com organization/corporation/university then you need a separate mail subdomain for your list server, for example lists.domain.com

In your DNS you need an MX register for domain.com pointing to your Exchange server and an MX register for lists.domain.com pointing to your Exim/Sympa server. I assume that both your Exim/Sympa and Exchange servers have public IPs and direct access to internet (with the proper firewalls, of course).

Is this what you were wondering? Sorry if I went for a too basic level but thats what I figured out you were questioning.
Regards.

**Comment by Azzmoh** [comment]
Hi 
Thanks for your reply much appreciated. 
Currently we have sympa with sub domain lists.domain.com which is pointing to Exim server and exim servers are internet facing but not sympa  list server. 

We are introducing exchange 2016 server in hybrid mode i.e. on-prem exchange 2016 server with hybrid exchange online/o365. 

with introduction of on-prem exchange 2016 server - we are going to change DNS/MX records to point to o365 directly instead of current entries pointing to EXIM servers. 

current setup 
internal applcations & sympa sends requests to > Exim > outbound to internet and O365. 

proposed setup : internal applications & sympa to send requests to exchange 2016 server > 2016 exchange server configured in hybrid mode to route emails to o365 > from 0365 to internet.

my question is : how can we redirect requests from sympa lists server to send and recieve requests from Exchange server 2016 ? 

we donot want to keep sympa lists server internet facing but behind Exchange 2016 server. 

Hope i made it clear if not then please donot hesitate for more clarification. 

Many Thanks

**Comment by qosobrin** [comment]
Send and Receive connectors and Accepted Domains in Exchange. That's where you cut the chase for your needs. First you'll have to configure the Accepted Domains to let Exchange know which mail domains it has to handle, and then you'll define the connectors to let it know how to handle the messages for each domain.

**Comment by Azzmoh** [comment]
Thanks for the informative and very precise to the point answer. so i will be creating a receive connector for sympa IP .Hopefully that should suffice the requirements for sympa. 

Many Thanks

**Comment by qosobrin** [comment]
Feel free to close this issue whet you best consider it. 

Regards.
