### ISSUE TITLE
list creation on web interface doesn't create list alias (6.2.40)

### ISSUE THREAD

**Issue by bv-unibs** [sympa-community/sympa#718]
Hi,
I'm using sympa version 6.2.40 from debian 10 repo with postfix version 3.4.5.
I have a problem regarding the sympa vs postfix configuration.

I've imported old aliases from a previous sympa system, and the mailing lists associated to these alias seems to be working.

But when I create a new list on web interface in sympa, it seems like the expected alias for postfix is not created, so when I try to send a message to a new list I receive the message:

recipient address rejected: user unknown in local recipient table

This is occurring for the new mailing lists created from the web interface. The alias is not created but I don't see any error in the sympa.log regarding this problem.

In the previous production version we had (6.1.17), the alias creation was automatic. How can I implement this functionality on this new system?

For postfix sympa integration I followed this documentation:
https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html
(Single Domain Setting)

Thanks

**Comment by bv-unibs** [comment]
In our previous version 6.1.17 we had a program named alias_manager.pl, that took care of the alias creation for sympa, but I understand this is now deprecated.

There's a similar function or a new procedure for this purpose? 

thanks

**Comment by racke** [comment]
There is a template for the aliases with the filename `list_aliases.tt2`. Check if you can find that in your installation.

**Comment by bv-unibs** [comment]
Yes, I found it already and put it in sysconfig directory of sympa: /etc/sympa, but I don't know how to integrate this in the system, and I didnt' found any documentation about this..

can you help me understand how to use this template?

thanks

**Comment by bv-unibs** [comment]
Hi, I've managed to solve the problem regarding the alias manager.. Now everything it's working..

You can close this issue 

Thank you

**Comment by racke** [comment]
Please explain what solved the problem so we can help others with a similar one.

**Comment by bv-unibs** [comment]
My sympa.conf file was missing of these 2 parameters:

alias_manager
sendmail_aliases

I mapped the first one the sympa installation alias manager.pl
and the second to my alias file..

I tried to create a new list and now the aliases are correctly created into the alias file..

The solution was simplest than I thought, but I think the documentation lacks of these informations.

By the way, thank you for the patience

**Comment by EduardoOsquel** [comment]
> 
> 
> My sympa.conf file was missing of these 2 parameters:
> 
> alias_manager
> sendmail_aliases
> 
> I mapped the first one the sympa installation alias manager.pl
> and the second to my alias file..
> 
> I tried to create a new list and now the aliases are correctly created into the alias file..
> 
> The solution was simplest than I thought, but I think the documentation lacks of these informations.
> 
> By the way, thank you for the patience

Im facing the same situation
How do you map this two? Im using debian buster 10 and the last sympa version

**Comment by EduardoOsquel** [comment]
I found my own solution adding the following to main.cf in postfix

alias_maps = hash:/etc/sympa/aliases.sympa.postfix, hash:/etc/mail/sympa/aliases
alias_database = hash:/etc/sympa/aliases.sympa.postfix, hash:/etc/mail/sympa/aliases

systemctl restart postfix

If someone find another one, please share!!!
