### ISSUE TITLE
sympa init script on Debian [: =: unary operator expected

### ISSUE THREAD

**Issue by pkissman** [sympa-community/sympa#72]
When you install a new version of sympa 6.20 or 6.22,  the initscript generated has the following warning on a Debian system (wheezy):
  **/etc/init.d/sympa: line 262: [: =: unary operator expected**

Adding quotes around the NETWORK reference in if [ ${NETWORKING} = "no" ]  in sympa-6.2.22/src/etc/script/sympa.in

if [ **"**${NETWORKING}**"** = "no" ]

seems to do the trick

**Comment by racke** [comment]
Thanks for the report @pkissman. But I think we should stop supporting init scripts as modern distributions are using systemd. Not that I really in love with that ... 

Given the small size of the current Sympa dev team, I don't see a point to support Debian wheezy etc.

**Comment by pkissman** [comment]
That's fine.  I can fix it myself at each upgrade install, which I do from source, not from  Debian packages.  We hope to hop up to a current OS distribution soon any.

Thanks for considering.

pjk



________________________________
