### ISSUE TITLE
Request date for renamed lists

### ISSUE THREAD

**Issue by Salo15** [sympa-community/sympa#720]
After a mailing list has been renamed, the pending lists web page displays the creation date of the original list as the request date.
The date when the list was renamed should be displayed here. For us, this has caused confusion with the list masters if this date is far in the past.

Version
-------
Sympa 6.2.16

Installation method
-------------------
Debian Package

Expected behavior
-----------------
In the case of renamed lists, the date of the renaming should appear on the website with the pending lists.

Actual behavior
---------------
After a mailing list has been renamed, the pending lists web page displays the creation date of the original list as the request date. This date sometimes lies far in the past and irritates the listmasters who are to release the list.

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @Salo15,

I think this bug will be fixed on the next release. Unfortunately the fix may bot be backported to earlier releases.

Thanks for reporting bug!
