### ISSUE TITLE
Error No user updated

### ISSUE THREAD

**Issue by bertaviader** [sympa-community/sympa#723]
Hey!

We migrated our sympa version 6.1.7 to a new server with the version 6.2.24. Everything seems fine, but I checked the logs, this morning and one of the lists is not performing as is has to.

The error in the log is this one:

Aug  7 08:31:42 server bulk[35427]: err main::#164 > (eval)#164 > Sympa::Process::_child_handler#158 > Sympa::Process::_reap_child#173 Child process 54611 for <5.5.1565159502.1565159502.157660.list@listdomain_s,35423,2964/s> exited with status 67
Aug  7 08:31:43 server bounced[35471]: err main::#160 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessBounce::_twist#576 > Sympa::Tracking::store#275 No user mail@listdomain to be updated in list Sympa::List <list@listdomain>

Do you know what means the error?

Thank you!
Berta

**Comment by ikedas** [comment]
Your sendmail immediately rejects message bound for unknown local user.

`sendmail` command should accept any messages sent from local machine, and if neccessary (i.e. the recipient is unknown), it may send the delivery status (bounce) back.

**Comment by bertaviader** [comment]
And how can I fix it? In the sendmail configuration?

**Comment by ikedas** [comment]
I think you may have to do the same things as 6.1 with:
- Setting of the mail server that actually delivers outbound messages.
- Setting of Sendmail where Sympa service is running, i.e. `sendmail` command will run.
- Setting of Sympa, especially `sendmail` and `sendmail_args` parameters in `sympa.conf`.

**Comment by ikedas** [comment]
Stagnating issue. Close.
