### ISSUE TITLE
Error main::#297 in sympa 6.2.20

### ISSUE THREAD

**Issue by MorenoUniTN** [sympa-community/sympa#726]
Hi, I have much of error in my sympa.log as:
Aug 12 13:14:31 list task_manager[1630]: err main::#297 > Sympa::List::get_lists#8255 > Sympa::List::new#386 > Sympa::List::load#812 Could not create new lock
Aug 12 13:14:31 list task_manager[1630]: err main::#297 > Sympa::List::get_lists#8255 > Sympa::List::new#386 > Sympa::List::load#812 Could not create new lock
Aug 12 13:14:31 list task_manager[1630]: err main::#297 > Sympa::List::get_lists#8255 > Sympa::List::new#386 > Sympa::List::load#812 Could not create new lock
Aug 12 13:14:31 list task_manager[1630]: err main::#297 > Sympa::List::get_lists#8255 > Sympa::List::new#386 > Sympa::List::load#812 Could not create new lock
Aug 12 13:14:31 list task_manager[1630]: err main::#297 > Sympa::List::get_lists#8255 > Sympa::List::new#386 > Sympa::List::load#812 Could not create new lock

This error not indicate wich list is in error and i can't resolv it? 
Any ideas ?

Thanks in advance

**Comment by racke** [comment]
Unfortunately the error message doesn't provide any details (shortcoming of Sympa code). The underlying problem is most likely insufficient permissions for the directory where Sympa tries to create the lock file.

**Comment by MorenoUniTN** [comment]
Ok thanks for the answer, i will check the permission of the folder.

**Comment by ikedas** [comment]
No update.  Close for the present.
