### ISSUE TITLE
List owner receives mail

### ISSUE THREAD

**Issue by Sympa-test** [sympa-community/sympa#728]
Expected behavior
-----------------
When someone sends a mail to a list, the owner doesn't want to receive a mail.

Actual behavior
---------------
When someone sends a mail to a list, the owner recevie a mail.

Additional information
----------------------
The visibility is "secret".
In "default_user_option", the "reception" field is (mail).
In "Reply_to_header", "value" field is "other_email", "other_email" is a no-reply address.

Regards,

**Comment by ikedas** [comment]
Hi @Sympa-test,
Could you please show us these?
- the message (with full header) the owner received
- Sympa's log during message delivery
Thanks.

**Comment by ikedas** [comment]
No update. Close for the present.
