### ISSUE TITLE
Problème de date

### ISSUE THREAD

**Issue by JCEYMER** [sympa-community/sympa#731]
Bonjour
avec Subject: [% FILTER qencode %][%|loc(list.name,date)%]%1 Digest %2[%END%] j'obtiens : 
Compilation du ven., **16 ao?t** 2019, liste membres écrit 16ao?t
Comment corriger l'accent ?
Plus loin j'ai : 
<p></b><a name="N[% m.id %]">[% m.id %] -</a> Date: **[% m.date %]** transmis par  
et cela me donne :  Date: Thu, 15 Aug 2019 08:46:04 +0200 transmis écris Au g c'est à dire anglais 

J'aurais aimé en français ...
Comment faire ?
Merci

**Comment by ikedas** [comment]
Hi @JCEYMER,
What is the version of Sympa you are using?

**Comment by JCEYMER** [comment]
Version 6.1.23

**Comment by ikedas** [comment]
Hi @JCEYMER. 

This seems a bug fixed on Sympa 6._2_.24 (_not_ 6.1.24).  See #134 for more details.

Unfortunately, the fixes on 6.2.x will not be backported to 6.1.x anymore.  Upgrading to recent version is recommended solution.
