### ISSUE TITLE
LWP::Protocol::https missing but needed by GUI

### ISSUE THREAD

**Issue by igoltz** [sympa-community/sympa#733]
Trying to send an html mail by providing an https URL in the GUI fails with
FEHLER (send_mail) - Die Seite konnte nicht richtig verarbeitet werden. Bitte überprüfen Sie den Inhalt der von Ihnen eingereichten Webseite oder Datei. Can't fetch https://FQDN/PATH.html (Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)) 

Version
-------
Sympa 6.2.44 (older version too) on CentOS 7

Installation method
-------------------
rpm based
yum install sympa sympa-httpd via Soji's RPM (http://sympa-ja.org/download/rhel/sympa-ja.org.rhel.repo)

and from source inside perlbrew env. with cpanm based package install
cpanm --installdeps --with-recommends --with-all-features --without-feature cas --without-feature migrate-from-very-old-version --without-feature csv --without-feature odbc --without-feature oracle --without-feature pg --without-feature sqlite --without-feature sybase --without-feature soap .

Expected behavior
-----------------
Providing an https URL in "Post" (/sympa/compose_mail/LIST/html_news_letter)
-> Sending an HTML page to the list
-> Select the source of your HTML newsletter / Send the page from the following URL:
should fetch and send the content of this URL as it does with http URLs

 
Actual behavior
---------------
Error Message:
Can't fetch https://FQDN/PATH.html (Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)) 

Additional information
----------------------
For rpm installation, yum install perl-LWP-Protocol-https.noarch fixed this.
And cpanm LWP::Protocol::https for installation from source.

LWP::Protocol::https as dependency is not covered by "sympa_wizard.pl --check" and the provided cpanfile
(Thus) rpm packe does not list perl-LWP-Protocol-https as dependency.

**Comment by ikedas** [comment]
Hi @igoltz,

- As of 6.2.45b.1, `LWP::Protocol::https` may be installed by using cpanm (see #516 for more details of changes).
- On RPM, we have noticed this bug (see ikedas/sympa-rpm#58).  It may be fixed on the next release.

Thanks for reporting bugs and reminding us about them!

**Comment by ikedas** [comment]
It will be included in the next Fedora/EPEL: cf. [commit](https://src.fedoraproject.org/rpms/sympa/c/db21cc7).
