### ISSUE TITLE
Large Subscriberlist and size of messages

### ISSUE THREAD

**Issue by pveith** [sympa-community/sympa#735]
This is not really a bug nor a an actual issue. We have a list, which has 40.000 User. This list is unique within our setup and is feed by editors only (newsletter). We have the problem, that sometimes attached documents will fill up our queues. We split the filesystem, as our first contact with this was, that the var partition filled up and not enough was logged to reconstruct the failed sends.
So now we ran out of postfix queues space and sympa did not crash. We could reconstruct which messages were missing and resend them.

**So my question is:** Is there a way to throttle this? I think about checking the membersize and the max queue size to calculate a max. message size. But i have probably overlooked some other technical features in sympa or postfix, which should be utilised.

**Comment by racke** [comment]
Sympa is sending out emails fast by default. There are few settings for Sympa to control that, but I didn't used these yet.

**Comment by racke** [comment]
As far as I can see, these are the available parameters for controlling the emails sent out by Sympa:
```

    {   'name'       => 'maxsmtp',
        'default'    => '40',
        'sample'     => '500',
        'gettext_id' => 'Maximum number of sendmail processes',
        'file'       => 'sympa.conf',
        'gettext_comment' =>
            "Maximum number of simultaneous child processes spawned by Sympa. This is the main load control parameter. \nProposed value is quite low, but you can rise it up to 100, 200 or even 300 with powerful systems.",
    },
    {   'name'       => 'nrcpt',
        'default'    => '25',
        'gettext_id' => 'Maximum number of recipients per call to sendmail',
        'gettext_comment' =>
            'This grouping factor makes it possible for the sendmail processes to optimize the number of SMTP sessions for message distribution. If needed, you can limit the number of recipients for a particular domain. Check the "nrcpt_by_domain.conf" configuration file.',
        'file' => 'sympa.conf',
    },
    {   'name'    => 'avg',
        'default' => '10',
        'gettext_id' =>
            'Maximum number of different mail domains per call to sendmail',
        'file' => 'sympa.conf',
    },

```

**Comment by pveith** [comment]
Thanks a lot. I will have a look at them and how they could help me with my problem. Probably nrcpt seems a good candidate. 
Right now i am try to evaluate if developing a plugin, which rejects too log message based on size of the message, list-member-count and max. queue-space for postfix, is worth the trouble. Our setup includes a dedicated smtp, which adds DKIM-signatures and only has throttled access to our main mailservice, which is the cause postfix builds up larger queues.

**Comment by racke** [comment]
Another idea would be to stop bulk daemon for a while whenever Postfix reaches it limits. Or just upgrade the server for more resources :nerd_face:

**Comment by pveith** [comment]
Yep, more resources. Should have thought about that earlier. Obviously i was to eager to teach those  large-PDF-sending users a lesson, that i overlooked that one. (My colleague mentioned that also.) O.o
