### ISSUE TITLE
Creating mailing list without list-masters approvals 

### ISSUE THREAD

**Issue by Zohman** [sympa-community/sympa#737]
Sympa version: 6.2.40

Hi,

It seem that currently new requests been sent directly to the admins for approvals..
is it possible to allow authenticated users to create lists without listmaster admin?
**create_list** only have `public_listmaster` and `intranet` (as far as i know)
probably combined with those whom listed in **owner_domain**.

Alternatively, telling which Perl module is in charge of this will be appreciated as well. :)

**Comment by ikedas** [comment]
Hi @Zohman,

You can create a new `create_list` scenario, say, `scenari/create_list.public` with the content:
``` code
title.gettext anybody

is_listmaster([sender])   md5,smime -> do_it
true()                    smtp,md5,smime -> do_it
```
And add a line to `sympa.conf` or `robot.conf`:
``` code
create_list public
```

Hope this helps.

**Comment by ldidry** [comment]
@ikedas I think we should include such scenario in the default scenari, don’t you think?

**Comment by ikedas** [comment]
> @ikedas I think we should include such scenario in the default scenari, don’t you think?

IMO it may benefit squatters: If anyone can create their account on the list server, they can create and manage the lists as much as possible.

**Comment by ikedas** [comment]
Closed for now.
