### ISSUE TITLE
Pending lists not clearly shown as "pending" in the web GUI

### ISSUE THREAD

**Issue by salaun-urennes1** [sympa-community/sympa#738]
When list creation is moderated, such lists should be clearly tagged as "pending" in the web GUI

Version
-------
6.2.36

Installation method
-------------------
sources

Expected behavior
-----------------
When a user creates a list and it remains pending, the web GUI should show that list as "pending" both in the "my" page and in the list's "info" page.

Actual behavior
---------------
In 6.2.36 the "my" page does not indicate that a list has a pending status. It can lead to confusion, because list aliases are not installed for pending lists.

The info page includes "List not activated yet" (see attached screenshot), but it should be highlighted. It used to be highlighted via the `bg_color_error` style, but this style definition has been removed in revision dab09c33c249c18f8aef53311ddd24bf3143d58e. I did not find a suitable style to use as a replacement.

![image](https://user-images.githubusercontent.com/4091149/63936688-b989d580-ca60-11e9-8fa6-dd86c6d30650.png)

**Comment by ikedas** [comment]
Hi @salaun-urennes1,
How does the "pending" lists are shown in "my" page? Could you show the screen shots?

**Comment by salaun-urennes1** [comment]
Here is how the **my** page shows a pending list :
![image](https://user-images.githubusercontent.com/4091149/63999759-7ed97900-cb04-11e9-9532-ea45f8da6b37.png)

**Comment by ikedas** [comment]
Hi @salaun-urennes1, could you pelase check PR above?
