### ISSUE TITLE
Shared Documents can't add file

### ISSUE THREAD

**Issue by A3TH3RIUS** [sympa-community/sympa#743]
**Version**
Sympa 6.2.41b.2

**Installation method**
From Source

**Problem**
One of the users of the Sympa mailing list service that I set up told me that he can not add files to the shared documents in his list. When trying to add, it receives the following error:

![image001](https://user-images.githubusercontent.com/32356014/64348770-0daf2f80-cff6-11e9-9e85-098bec00b973.png)

I did different tests and it seems that this is due to the size allowed for the added files which is insufficient.

If anyone knows how to increase the maximum size allowed for adding files in shared documents, please let me know.

**Comment by racke** [comment]
Is there anything in the log files which gives more information about the Internal Server Error?

**Comment by A3TH3RIUS** [comment]
no unfortunately the only error message I got is the one above. That's why I had to go trying different cases.
At the time of the error, the only logs I get are:
`Sep  5 15:36:16 listes wwsympa[24518]: notice Sympa::Scenario::_verify_custom() Using previous custom condition cache editor*ct*user.user@domaine.fr`

`Sep  5 15:36:16 listes wwsympa[24518]: debug Sympa::WWW::Session::store()`

`Sep  5 15:36:16 listes wwsympa[24518]: debug Sympa::WWW::Session::renew(id_session=91947338962688)`

`Sep  5 15:36:16 listes wwsympa[24518]: debug Sympa::WWW::Session::set_cookie(Sympa::WWW::Session, localhost, 0, )`

`Sep  5 15:36:18 listes wwsympa[24518]: debug main::_split_params() PATH_INFO: /d_read/ct/2019/`

`Sep  5 15:36:18 listes wwsympa[24518]: debug main::_split_params() [robot nom.domaine.fr] [client xxx.xxx.xxx.xxx] Incoming parameter: list=ct`

`Sep  5 15:36:18 listes wwsympa[24518]: debug Sympa::WWW::Session::new(nom.domaine.fr, 91947338962688, d_read)`

`Sep  5 15:36:18 listes wwsympa[24518]: notice Sympa::Scenario::_verify_custom() Using previous custom condition cache editor*ct*user.user@domaine.fr`

`Sep  5 15:36:18 listes wwsympa[24518]: info main::do_d_read(2019/) [robot nom.domaine.fr] [session 91947338962688] [client xxx.xxx.xxx.xxx] [user user.user@nom.domaine.fr] [list ct]`

and there is no mention of error before or after that.

**Comment by ikedas** [comment]
How about error logs of HTTP server?

**Comment by A3TH3RIUS** [comment]
Nothing related to Sympa in the http server error logs.

**Comment by racke** [comment]
You should be able to find the 500 error in these logs though, if you match the times.

**Comment by A3TH3RIUS** [comment]
Yes I know but even this error does not appear in the logs. Yet, I even made "on purpose" to cause this error in my tests but nothing appears.

**Comment by A3TH3RIUS** [comment]
So, if there is a variable (or other modification) to change the maximum size of files on shared directories, please let me know.

**Comment by racke** [comment]
You can set the "quota" for the shared documents in Edit List Config / Privileges on the bottom of the page.
Please note that the unit is in **Kilobytes**.

**Comment by racke** [comment]
Found no clue about the default though.

**Comment by racke** [comment]
If will take a closer look when I get the chance. Would you mind to share the config file for this list?

**Comment by A3TH3RIUS** [comment]
This is the configuration of the shared documents.

[conf.txt](https://github.com/sympa-community/sympa/files/3620577/conf.txt)

Sorry it took me a while to recover all the configuration files in one file and anonymize the users' email addresses.
I preferred to pass you a file rather than copy everything into text (more than 1000 lines).

**Comment by A3TH3RIUS** [comment]
I made a strace command to know exactly what was happening when Internal server error occurs on shared documents.

`
sudo strace -f $(for i in $(pgrep -f apache2); do echo -n "-p $i "; done)

strace: Process 1249 attached
strace: Process 1250 attached
strace: Process 1251 attached
strace: Process 1252 attached
strace: Process 1253 attached
strace: Process 1254 attached
strace: Process 1430 attached
strace: Process 2314 attached
strace: Process 2315 attached
strace: Process 16218 attached
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=0, tv_usec=133470} <unfinished ...>
[pid  2315] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  2314] epoll_wait(15,  <unfinished ...>
[pid  1430] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  1254] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  1253] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  1252] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  1251] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  1250] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid  1249] restart_syscall(<... resuming interrupted poll ...> <unfinished ...>
[pid 16218] <... select resumed> )      = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0} <unfinished ...>
[pid  1249] <... restart_syscall resumed> ) = 0
[pid  1249] poll([{fd=10, events=POLLIN}], 1, 3000 <unfinished ...>
[pid 16218] <... select resumed> )      = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0} <unfinished ...>
[pid  1249] <... poll resumed> )        = 0 (Timeout)
[pid  1249] semop(8486919, [{0, -1, SEM_UNDO}], 1) = 0
[pid  1249] semop(8486919, [{0, 1, SEM_UNDO}], 1) = 0
[pid  1249] wait4(1753, 0x7ffd4f9a7f6c, WNOHANG|WSTOPPED, NULL) = 0
[pid  1249] semop(8486919, [{0, -1, SEM_UNDO}], 1) = 0
[pid  1249] semop(8486919, [{0, 1, SEM_UNDO}], 1) = 0
[pid  1249] semop(8486919, [{0, -1, SEM_UNDO}], 1) = 0
[pid  1249] semop(8486919, [{0, 1, SEM_UNDO}], 1) = 0
[pid  1249] semop(8486919, [{0, -1, SEM_UNDO}], 1) = 0
[pid  1249] semop(8486919, [{0, 1, SEM_UNDO}], 1) = 0
[pid  1249] poll([{fd=10, events=POLLIN}], 1, 3000 <unfinished ...>
[pid  2314] <... epoll_wait resumed> [{EPOLLIN, {u32=338727520, u64=139762869506656}}], 2, 10000) = 1
[pid  2314] accept4(3, {sa_family=AF_INET, sin_port=htons(34386), sin_addr=inet_addr("192.168.35.9")}, [128->16], SOCK_CLOEXEC) = 16
[pid  2314] semop(8454149, [{0, 1, SEM_UNDO}], 1) = 0
[pid  2315] <... semop resumed> )       = 0
[pid  2315] epoll_wait(15,  <unfinished ...>
[pid  2314] getsockname(16, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("10.210.18.9")}, [128->16]) = 0
[pid  2314] fcntl(16, F_GETFL)          = 0x2 (flags O_RDWR)
[pid  2314] fcntl(16, F_SETFL, O_RDWR|O_NONBLOCK) = 0
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d14303000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d14301000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142ff000
[pid  2314] read(16, "POST /sympa HTTP/1.1\r\nHost: list"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142fd000
[pid  2314] stat("/home/sympa/bin/wwsympa-wrapper.fcgi", {st_mode=S_IFREG|S_ISUID|S_ISGID|0755, st_size=10976, ...}) = 0
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142fb000
[pid  2314] read(16, "Y\213\262\216_J\231\3147\351\362\2050\344W\260\270\234y\347\204'-MXQ\347\251\v,:\324"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142f9000
[pid  2314] read(16, "*q/\313\2525\324;+\324\306]n\20\330\322x\343\343\3\305\374\27<\301K\254\354\226J\366E"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142f7000
[pid  2314] read(16, "\201^\251\341\275m<C\241[\352+\31\211\234bH\317\360\260\352+\302\274y}>\233\6\235-\252"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142f5000
[pid  2314] read(16, "\34\375\24W/\250\302\317\344\262n\334\217\333\371\325\335>g\272\321\265\262\243\33\255\321\366\203\320+\257"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142f3000
[pid  2314] read(16, "\376\302\324\257\343\22\253[]M\26\"\325\3y\220\357\376\24n\330\377\0\32\247q\342\311\256n\242\265"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142f1000
[pid  2314] read(16, "\317v\361xv\344i6\3225\275\234D\275\303.\20\22B\360{\267\314:\377\0J\231\256h\362\303"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142ef000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142ed000
[pid  2314] read(16, "\333mkd\226\362\6\216\342('Ky\t!\344\22a\202\201\356;t\254\3737\2365O!\246@"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142eb000
[pid  2314] read(16, "2\265\246Pd\214\34w\357V\32N)\2420\245I\0\355\30\3155\270p1\234\236\264\304\312\361\254"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142e9000
[pid  2314] read(16, "\244H$\266\4y\247\253\332!A\0\347\340\340\340\340\334\0=}\276\\\315\317'g\253\354\331\263\247"..., 8000) = 8000
[pid  2314] getpid()                    = 2314
[pid  2314] open("/tmp/apr-tmp.LXWu2y", O_RDWR|O_CREAT|O_EXCL, 0600) = 17
[pid  2314] fcntl(17, F_GETFD)          = 0
[pid  2314] fcntl(17, F_SETFD, FD_CLOEXEC) = 0
[pid  2314] write(17, "!", 1)           = 1
[pid  2314] close(17)                   = 0
[pid  2314] unlink("/tmp/apr-tmp.LXWu2y") = 0
[pid  2314] getpid()                    = 2314
[pid  2314] open("/tmp/fcgid.tmp.p9aFtH", O_RDWR|O_CREAT|O_EXCL, 0600) = 17
[pid  2314] fcntl(17, F_GETFD)          = 0
[pid  2314] fcntl(17, F_SETFD, FD_CLOEXEC) = 0
[pid  2314] write(17, "\275\312\214\343\337ml\335k\20\370sHQi\26.\257\24\305e\30\34/L\263\21\214u\34\367&"..., 5779) = 5779
[pid  2314] write(17, "\244H$\266\4y\247\253\332!A\0\347\340\340\340\340\334\0=}\276\\\315\317'g\253\354\331\263\247"..., 2413) = 2413
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142e7000
[pid  2314] read(16, "t 700/XHeight 250/Leading 21/Ste"..., 8000) = 8000
[pid  2314] write(17, "\224<\"\331\304\210Cz@+\30\215\304\10H\262\337\326\243`}\317!4-}\336\201\323\20J&"..., 5587) = 5587
[pid  2314] write(17, "t 700/XHeight 250/Leading 21/Ste"..., 2605) = 2605
[pid  2314] read(16, "\224\0\0\301\351N\244##\35)\245\255\300p\2\220\340v\353T\321n\355\355\3264\375\373\16w\273"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142e5000
[pid  2314] write(17, "U'\21\260\214\221\306?\336\6\266\275\326\203\212\324\303\3235\371/5\306\271\272\362\314W\212L\240s"..., 5395) = 5395
[pid  2314] write(17, "\224\0\0\301\351N\244##\35)\245\255\300p\2\220\340v\353T\321n\355\355\3264\375\373\16w\273"..., 2797) = 2797
[pid  2314] read(16, "u\214\t\242\267\22\24\34t$\341s\353\355Z\227\0235\275\263J\261K)\37\301\20\313\32\314\325-"..., 8000) = 8000
[pid  2314] write(17, "}\341\313i\343\223\310\375\333\310p\331\31R;\214\177_\\V#xn\362\322Dh\334;\31I\\"..., 5203) = 5203
[pid  2314] write(17, "u\214\t\242\267\22\24\34t$\341s\353\355Z\227\0235\275\263J\261K)\37\301\20\313\32\314\325-"..., 2989) = 2989
[pid  2314] read(16, "?\341!\234\334=\357\332%E_5\35\376T\215\224\20\352;q\214\375*\305\362]YL\220\334\334"..., 8000) = 8000
[pid  2314] write(17, "\342h\276\314\312G\220 \21)#\250\351ZZ\275\355\305\275\334\32M\272<\301\341\6;[0B\217"..., 5011) = 5011
[pid  2314] write(17, "?\341!\234\334=\357\332%E_5\35\376T\215\224\20\352;q\214\375*\305\362]YL\220\334\334"..., 3181) = 3181
[pid  2314] read(16, "[\307%\305\351\207s\261b\354\6{\366\353[\265Z\342\312\336\346X$\2212\360\277\230\204q\203\214"..., 8000) = 8000
[pid  2314] write(17, "\260\371\224{\23\223\212\227&\366\31\347X\361\34\276(\276\262\215g\220\312\f\226\3531>Z\247\373'"..., 4819) = 4819
[pid  2314] write(17, "[\307%\305\351\207s\261b\354\6{\366\353[\265Z\342\312\336\346X$\2212\360\277\230\204q\203\214"..., 3373) = 3373
[pid  2314] read(16, "\340\277\262\232\326\3464\222\31\220\243\253.A\4zW!\360\343Q\226\343\300\321}\251\212\265\224\222\333"..., 8000) = 8000
[pid  2314] write(17, "slP7\37S\357X\372\325\325\37476\266\266P\271\363\234\357\227nUTu\31\354\307<}\r"..., 4627) = 4627
[pid  2314] write(17, "\340\277\262\232\326\3464\222\31\220\243\253.A\4zW!\360\343Q\226\343\300\321}\251\212\265\224\222\333"..., 3565) = 3565
[pid  2314] read(16, ".\277L\367\247\325;\273\10\246\33\304A\245\4:\344\221\226\0352GjoBK\231\315r\36,\361"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142e3000
[pid  2314] write(17, "\346\31\230\20\20\375\3403\375\322\277\250\25\313\210\222\261qL\302\276X\365\313O\263[\315\"\303j["..., 4435) = 4435
[pid  2314] write(17, ".\277L\367\247\325;\273\10\246\33\304A\245\4:\344\221\226\0352GjoBK\231\315r\36,\361"..., 3757) = 3757
[pid  2314] read(16, "\0\0\300\30\24QE0\fUK\335>\336\366\26\212X\307\316A,\243\7\203\221\315Z?Z\6\17"..., 8000) = 8000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142e1000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142df000
[pid  2314] mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1d142dd000
[pid  2314] writev(16, [{iov_base="HTTP/1.1 500 Internal Server Err"..., iov_len=192}, {iov_base="<!DOCTYPE HTML PUBLIC \"-//IETF//"..., iov_len=608}], 2) = 800
[pid  2314] write(9, "192.168.35.9 - - [20/Sep/2019:08"..., 286) = 286
[pid  2314] times({tms_utime=0, tms_stime=0, tms_cutime=0, tms_cstime=0}) = 2291867360
[pid  2314] shutdown(16, SHUT_WR)       = 0
[pid  2314] poll([{fd=16, events=POLLIN}], 1, 2000) = 1 ([{fd=16, revents=POLLIN}])
[pid  2314] read(16, "\2456qbf\347;\305\35v\217\341}\27B\226Yt\335:\10$\224\374\316\253\363w\343=\207'"..., 512) = 512
[pid  2314] read(16, "3\245^E\366\33[\206\37\332\322.\5\272\221\226E^\231S\236\234\n\326Hu/\34\374.\276\262"..., 512) = 512
[pid  2314] read(16, ")\356\271'\30\366\256\341zR\275\3048u\247S\7ZuZ\1h\244\245\252\21\317x\323X}\27"..., 512) = 512
[pid  2314] read(16, "1\305t\37\17\314Q^k\332}\254\22Ge\4\350c.\345\271(29\377\0<\326\17\201\264m"..., 512) = 512
[pid  2314] read(16, "t\265\261\350\340\32\234]:\232\33\32\307\216\354\274m\340\253_\16Y\351k\375\245)T\235Y6\307"..., 512) = 512
[pid  2314] read(16, "V\316\332\16\276:\235\33\246\314\353\355B{\313\317\354\3559\301q\217:pN#\36\307\271\377\0\n"..., 512) = 512
[pid  2314] read(16, "T\0100\3\251\343a%\277*\345\301\306\356\347\241\233T\345\212\211\332Kg2i\20\275\304\220\333K"..., 512) = 512
[pid  2314] read(16, "\210\371\252\276\241}o\246\330Myw\"\305\4(]\331\2160\5Y5\344\277\21u\357\355\255A\274"..., 512) = 512
[pid  2314] read(16, "_W\272\376\322\325\201,\262\260\v\34$\365\10\243\247\326\273\201\326\256\21\260\233]\0055\304|E\361"..., 512) = 512
[pid  2314] read(16, "\226\25y\2329\312\341\217<\n\363!AW\\\310\367j\342\336\25\362\275O.d\203i>` \364"..., 512) = 512
[pid  2314] read(16, "SX\306\337d\222\6\0\233\22\336s\311\234\2Q\276b:\363\232\356\364\313\30\254\255\300O\232FQ"..., 512) = 512
[pid  2314] read(16, "\313A\363\20z\f\343\371\3259\244{\366\273\262\335\345\334B\313$EI\345{\37\346+>\313E|"..., 512) = 512
[pid  2314] read(16, "\246\207\251Ia\345\331\335\273\265\221\\Aq#r\270\376\7'\333\241\252v\205\274\303\33\2561\305h"..., 512) = 512
[pid  2314] read(16, "\326\332\376fG\270\334#eR\374\2562\16;\343\35i\247\334\37\221\265\4q\305\22\307\22*\242\200"..., 512) = 512
[pid  2314] read(16, "\6\234\356\270\262\270@\326\323\237\366\227\261\353\310\365\257N\206`\333\344\236\207,\360\375bC\341\215K"..., 512) = 512
[pid  2314] read(16, "r\2\366\3271^\26\320\355\300\315\302\201\367\243e\34\204$t=+\242\236g\361\7\205\355\357'\267"..., 512) = 512
[pid  2314] read(16, "\310\257B\307\351PZY\333X\333\254\26\260\244Q \302\252\214`T\344\361Wk!\16\242\274\353]"..., 512) = 512
[pid  2314] read(16, "X\272\265]i/d\272umM\"pLM\375\335\207\357/\0340\344`\372\322\317%\344\332\314\211"..., 512) = 512
[pid  2314] read(16, "\232\327\205\254\333\342f\221i\251\357\216\307R'\177\226\337\361\360\343\240 z\347\255lh\236\0\223^"..., 512) = 512
[....
.....
.....
....]
[pid  2314] read(16, "\247\3760\367o\217\275v\360\275K\r\3332&<\352\357z\253\341eG\305\243\263\253\3778\263\374\375"..., 512) = 512
[pid  2314] read(16, "www.w3.org/1999/02/22-rdf-syntax"..., 512) = 512
[pid  2314] read(16, ":description></rdf:Description>\n"..., 512) = 512
[pid  2314] read(16, "/xmpMM:InstanceID></rdf:Descript"..., 512) = 512
[pid  2314] read(16, "                             \n  "..., 512) = 512
[pid  2314] read(16, "                      \n         "..., 512) = 512
[pid  2314] read(16, "               \n                "..., 512) = 512
[pid  2314] read(16, "        \n</rdf:RDF></x:xmpmeta><"..., 512) = 512
[pid  2314] read(16, "\177\212\261:1>l\340\21\322&J\243\340\265({*z<\305\211>q\357\216x\3570\260\34\251"..., 512) = 512
[pid  2314] read(16, "000000640 00000 n\r\n0000009226 00"..., 512) = 512
[pid  2314] read(16, "000 n\r\n0000078380 00000 n\r\n00000"..., 512) = 512
[pid  2314] read(16, "60139 00000 n\r\n0000560535 00000 "..., 512) = 512
[pid  2314] read(16, "n\r\n0000628512 00000 n\r\n000062862"..., 512) = 512
[pid  2314] read(16, "7 65535 f\r\n0000000108 65535 f\r\n0"..., 512) = 512
[pid  2314] read(16, "000000133 65535 f\r\n0000000134 65"..., 512) = 512
[pid  2314] read(16, "535 f\r\n0000000159 65535 f\r\n00000"..., 512) = 512
[pid  2314] read(16, "00184 65535 f\r\n0000000185 65535 "..., 512) = 512
[pid  2314] read(16, "f\r\n0000630924 00000 n\r\n000063141"..., 512) = 512
[pid  2314] read(16, "4 00000 n\r\n0001452303 00000 n\r\n0"..., 512) = 512
[pid  2314] read(16, "rm-data; name=\"action_d_create_c"..., 512) = 379
[pid  2314] poll([{fd=16, events=POLLIN}], 1, 2000) = 1 ([{fd=16, revents=POLLIN|POLLHUP}])
[pid  2314] read(16, "", 512)           = 0
[pid  2314] close(16)                   = 0
[pid  2314] read(5, 0x7ffd4f9ab82f, 1)  = -1 EAGAIN (Resource temporarily unavailable)
[pid  2314] close(17)                   = 0
[pid  2314] unlink("/tmp/fcgid.tmp.p9aFtH") = 0
[pid  2314] semop(8454149, [{0, -1, SEM_UNDO}], 1 <unfinished ...>
[pid 16218] <... select resumed> )      = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0} <unfinished ...>
[pid  1249] <... poll resumed> )        = 0 (Timeout)
[pid  1249] poll([{fd=10, events=POLLIN}], 1, 3000 <unfinished ...>
[pid 16218] <... select resumed> )      = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}) = 0 (Timeout)
[pid 16218] wait4(-1, 0x7ffd4f9ab8cc, WNOHANG|WSTOPPED, NULL) = 0
[pid 16218] select(0, NULL, NULL, NULL, {tv_sec=1, tv_usec=0}
^C
strace: Process 1249 detached
strace: Process 1250 detached
strace: Process 1251 detached
strace: Process 1252 detached
strace: Process 1253 detached
strace: Process 1254 detached
strace: Process 1430 detached
strace: Process 2314 detached
strace: Process 2315 detached
strace: Process 16218 detached
 <detached ...>

`




Apparently when adding a document, it performs a series of reads then it creates several temporary files in which it writes then there is an Internal Server Error
And I still do not understand what can cause this error.

**Comment by A3TH3RIUS** [comment]
Little update on this topic, one of my colleagues found the solution to this problem of size in the shared folders.
This was due to FCGI's `FcgidMaxRequestLen` variable.
Once added to the Apache files, this solved the problem.
