### ISSUE TITLE
Robot verification for --make_alias_file command line option

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#746]
```
sympa@local-sympa:~$ /usr/local/sympa/bin/sympa.pl --make_alias_file --robot nevairbe.example.com
Sympa aliases file /var/spool/sympa/tmp/sympa_aliases.1519 was made.  You probably need to install it in your SMTP engine.
sympa@local-sympa:~$ cat /var/spool/sympa/tmp/sympa_aliases.1519 
#
#	Aliases for all Sympa lists open on nevairbe.example.com
#
```
Sympa produces alias file for bogus robot and doesn't give any error message back to the user.

**Comment by racke** [comment]
@ikedas How can I check whether [`$robot`](/var/spool/sympa/tmp/sympa_aliases.1340) contains a valid robot?

**Comment by ikedas** [comment]
I can't get it.  Have you created configuration of a new robot? How did you set up `list_aliases.tt2` (this can be prepared by each robot)? What does the aliases file contain?

**Comment by racke** [comment]
`nevairbe.example.com` is a fake robot and in my setup I have an alias file for each robot. The point is that the value from `--robot` is **not validated** and Sympa generates an **empty file**.

Therefore I would like to check whether the value is $robot actually **is**  a robot. Please let me know which code can be used for that so I can provide a pull request for this problem.

**Comment by ikedas** [comment]
Oh I see.
Currently we may use `Conf::valid_robot()` to check if a domain is vaild mail domain.
