### ISSUE TITLE
Error message "Use of uninitialized value $2" while instancing family lists

### ISSUE THREAD

**Issue by jhb2** [sympa-community/sympa#749]
When instancing many lists (students lists) using families from an XML file, each instantiation return an error message like this one : 
Creating lists:  71% [==]0m50s Left
Use of uninitialized value $2 in int at /home/sympa/bin/Sympa/Datasource.pm line 109.
Use of uninitialized value $4 in int at /home/sympa/bin/Sympa/Datasource.pm line 110.
Use of uninitialized value $2 in int at /home/sympa/bin/Sympa/Datasource.pm line 109.
Use of uninitialized value $4 in int at /home/sympa/bin/Sympa/Datasource.pm line 110.
List "etuqesi1e" (339/471) created/updated

Version
-------
6.2.40

Installation method
-------------------
Source package

Expected behavior
-----------------
Error message should disapear

Actual behavior
---------------
Error message are shown, don't know whats incorrect in list creation

Additional information
----------------------
Here is an example of xml use to instanciate one list

<list>
        <listname>etuQESI1E</listname>
        <subject>1ere annee Ing agroalim E (ESIAB Quimper)</subject>
        <description>Liste des etudiants de : 1ere annee Ing agroalim E</description>
        <custom_subject>1ere annee Ing agroalim E</custom_subject>
          <ldap>
          <filter>(cn=2019QESI1E)</filter>
          </ldap>
      </list>

**Comment by ikedas** [comment]
@jhb2, coukd you please check [this patch](https://github.com/sympa-community/sympa/commit/fcc912d61b6a08a956138f29a89b1b17d9f18a25.patch)?

(Note that, on recent beta, Datasource.pm was renamed to DataSource.pm, but this change may be applicable to earlier releases.)

**Comment by jhb2** [comment]
@ikedas 

Fixed! perfect, thank you...

List "uestc2op" (1255/1366) created/updated
List "uestc2uo" (1256/1366) created/updated
List "uestc2uoc" (1257/1366) created/updated
Creating lists: 100% [======================

**Comment by ikedas** [comment]
Thanks for confirming fix! Fixes will be incluxded in the next stable, 6.2.46.
