### ISSUE TITLE
sympa dead at riseup.net

### ISSUE THREAD

**Issue by RainerBielefeld** [sympa-community/sympa#751]
Hi all,

today I experienced that 2 postings of me to https://lists.riseup.net/www/info/wandervoegel-bs have become lost. It seems more probable that that is a reseup.net problem, but it's a little difficult to contact someone there.

Do you know a riseup.net contact for that problem? That project seems to be dead more or less?

Best regards

Rainer Bielefeld

**Comment by racke** [comment]
I never used riseup.net and don't know anything useful about them. Please ask on the mailing list where you can reach more people which might have an answer.
