### ISSUE TITLE
Unknown list

### ISSUE THREAD

**Issue by Isma399** [sympa-community/sympa#759]
Sympa Version: 6.2.40

Hello,
we've got some list unreachable since 3 days. I don't know what has changed on their parameters.
The fact is in the log:
Sep 24 11:44:41 listes wwsympa[19353]: info main:: [robot .................] [session 96057974241080] [client .............] [user ...................] Unknown list "syndicat-snptes-tous"

In the DB, this lists appear correctly and in list_data it's also OK.

Any hints?

**Comment by racke** [comment]
Do you use multiple robots (domains) or just one?

**Comment by racke** [comment]
That looks like wrong directory permissions which prevent the creation of the lockfile by the sympa user.

**Comment by Isma399** [comment]
No, that's not this case. Each directory under list_data is given to sympa:sympa with 0644 rights.
Thx for your answer

**Comment by racke** [comment]
You are sure the directory permissions are 0644? That should be 0755.

**Comment by Isma399** [comment]
Excuse me, the directory permission is 0755, the underlying files are 0644

**Comment by Isma399** [comment]
Ok, config owner was root...
Thanks for your help.
