### ISSUE TITLE
No members included with include_remote_file

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#761]
I'm using the include_remote_file to get the subscribers but none are added 
 

> info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=com-aca-ibst@listes.uclouvain.be;id=ca1fcf6e;role=member;name=comm-aca>: 0 included, 0 deleted, 0 updated, 0 kept

I have the same problem with the "owner_include"

Version
-------
6.2.46

Installation method
-------------------
from source package

Expected behavior
-----------------
No subscriber added 

Actual behavior
---------------

31 subscribers when i try the same command with a browser

**Comment by racke** [comment]
I think you the "Actual behavior" is the "Expected behavior". What do you mean with "try the same command with a browser"?

**Comment by pascalmaes** [comment]
You're right: I'm expecting 31 subscribers but I don't get any.

The include_remote_file is a http request. I can verify with a browser that the request is working fine.

**Comment by racke** [comment]
How does the http response looks like?

**Comment by pascalmaes** [comment]
curl "https://user:password@wso2ei.xxxx.be:yyyy/employees/v1/lists/emails?group_id=1&acronym=IBST&accept=plain"
andre.moens@uclouvain.be
benjamin.elias@uclouvain.be
benoit.desguin@uclouvain.be
bernard.hallet@uclouvain.be
bernard.knoops@uclouvain.be
cathy.debier@uclouvain.be
charles.hachez@uclouvain.be
christine.dupont@uclouvain.be
corentin.claeys@uclouvain.be
david.alsteens@uclouvain.be
elif.aktas@uclouvain.be
francois.chaumont@uclouvain.be
francoise.gofflot@uclouvain.be
henri.batoko@uclouvain.be
isabelle.donnay@uclouvain.be
jacques.mahillon@uclouvain.be
jf.rees@uclouvain.be
marc.boutry@uclouvain.be
marc.francaux@uclouvain.be
melissa.page@uclouvain.be
michel.ghislain@uclouvain.be
pascal.hols@uclouvain.be
patrice.soumillion@uclouvain.be
patrick.dumont@uclouvain.be
pierre.bertin@uclouvain.be
pierre.morsomme@uclouvain.be
rene.rezsohazy@uclouvain.be
xavier.draye@uclouvain.be
yvan.larondelle@uclouvain.be
yves-jacques.schneider@uclouvain.be
yves.dufrene@uclouvain.be

**Comment by pascalmaes** [comment]
I don't know if it's important but I have add a field to the database:

db_additional_subscriber_fields	server_subscriber

**Comment by racke** [comment]
For what reason did you need to add this field?

**Comment by pascalmaes** [comment]
because I'm using the same database server for 3 sympa servers.
We have a lot of lists and the load is spread on the 3 servers.

The field was used to know on which server is the subscriber but I think that we can delete it if needed.

**Comment by ikedas** [comment]
Hi @pascalmaes,

Could you please show entire log of Sympa from beginning to ending of “include” action?

**Comment by pascalmaes** [comment]
Sep 25 14:43:05 sympa-test.sipr.ucl.ac.be wwsympa[8059]: info main::do_sync_include(com-aca-ibst) [robot listes.uclouvain.be] [session 83573756214667] [client 130.104.64.150] [user pascal.maes@live.be] [list com-aca-ibst]
Sep 25 14:43:05 sympa-test.sipr.ucl.ac.be wwsympa[8059]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=com-aca-ibst@listes.uclouvain.be;role=member>
Sep 25 14:43:05 sympa-test.sipr.ucl.ac.be wwsympa[8059]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=com-aca-ibst@listes.uclouvain.be;id=ca1fcf6e;role=member;name=comm-aca>: 0 included, 0 deleted, 0 updated, 0 kept
Sep 25 14:43:05 sympa-test.sipr.ucl.ac.be wwsympa[8059]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=com-aca-ibst@listes.uclouvain.be;role=member>: 0 included, 0 deleted, 0 updated
Sep 25 14:43:06 sympa-test.sipr.ucl.ac.be wwsympa[8059]: info main::do_review() [robot listes.uclouvain.be] [session 83573756214667] [client 130.104.64.150] [user pascal.maes@live.be] [list com-aca-ibst]
Sep 25 14:43:06 sympa-test.sipr.ucl.ac.be wwsympa[8059]: info main::_review_member() [robot listes.uclouvain.be] [session 83573756214667] [client 130.104.64.150] [user pascal.maes@live.be] [list com-aca-ibst] No subscriber

**Comment by ikedas** [comment]
And, could you please show the content of data source file (•.incl) and corresponding setting in list config?

**Comment by pascalmaes** [comment]
file owners.incl:

include_remote_file
user sympa
passwd password
url https://wso2ei.xxxx:yyyy/mandates/v1/gestionnaires/emails?acronym=[% param.0 %]&accept=plain

config file:

owner_include
visibility noconceal
source owners
profile privileged
reception mail

include_remote_file
ssl_ciphers ALL
name comm-aca
timeout 1800
user sympa
ssl_version ssl_any
passwd password
ca_verify none
url https://wso2ei.sgsi.ucl.ac.be:8243/employees/v1/lists/emails?group_id=1&acronym=IBST&accept=plain

**Comment by ikedas** [comment]
Hi @pascalmaes,

What is shown by doing this from Sympa server?
``` bash
$ openssl s_client -connect wso2ei.xxx:yyyy
```

**Comment by pascalmaes** [comment]
Dear Ikeda,

`# openssl s_client -connect wso2ei.sgsi.ucl.ac.be:8243
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Assured ID Root CA
verify return:1
depth=1 C = NL, ST = Noord-Holland, L = Amsterdam, O = TERENA, CN = TERENA SSL CA 3
verify return:1
depth=0 C = BE, L = Ottignies-Louvain-la-Neuve, O = Universit\C3\A9 catholique de Louvain, CN = esb.sgsi.ucl.ac.be
verify return:1
---
Certificate chain
 0 s:/C=BE/L=Ottignies-Louvain-la-Neuve/O=Universit\xC3\xA9 catholique de Louvain/CN=esb.sgsi.ucl.ac.be
   i:/C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA SSL CA 3
 1 s:/C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA SSL CA 3
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA
 2 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Assured ID Root CA
---

The the server certificate
The subject
The issuer
---
No client certificate CA names sent
---
SSL handshake has read 4580 bytes and written 495 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 5D8C4EEF7E358BC180E9A264AE4B8C5C9C4199F684427539ED59F4D62061AA5F
    Session-ID-ctx:
    Master-Key: 5B3E9E32B7F5E79FABAB8ACF10B9213078902C6BB6C95B46F8E84AB771EF65101984556A1B9CBBAC95D71EC8EED63A65
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1569476335
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
read:errno=0
`

**Comment by ikedas** [comment]
Hi @pascalmaes,

Could you apply this patch and show us what logged?
(NOTE that a line `Authorization: Basic XXXXXXXX` in request contains user name & password and _must not_ be shown!)

``` patch
diff --git a/src/lib/Sympa/DataSource/RemoteFile.pm b/src/lib/Sympa/DataSource/R
index f97cce0..5125b3c 100644
--- a/src/lib/Sympa/DataSource/RemoteFile.pm
+++ b/src/lib/Sympa/DataSource/RemoteFile.pm
@@ -97,6 +97,8 @@ sub _open {
         $Conf::Conf{'tmpdir'},
         $list->get_id, $PID, (int rand 9999);
     my $res = $ua->request($req, $self->{_tmpfile});
+    $log->syslog('info', 'REQUEST: %s', $req->as_string);
+    $log->syslog('info', 'RESPONSE:%s', $res->as_string);
     unless ($res->is_success) {
         $log->syslog('err', 'Unable to fetch data source %s: %s',
             $self, $res->message);
```

**Comment by ikedas** [comment]
Related to #693.

**Comment by pascalmaes** [comment]
Hi @ikedas,

Here are the results:

Sep 27 08:07:08 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info main::do_sync_include(com-aca-ibst) [robot listes.uclouvain.be] [session 35262695295404] [client 130.104.40.228] [user pascal.maes@live.be] [list com-aca-ibst]
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=com-aca-ibst@listes.uclouvain.be;role=member>
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info Sympa::DataSource::RemoteFile::_open() REQUEST: GET https://esb.sgsi.ucl.ac.be:8243/employees/v1/lists/emails?group_id=1&acronym=IBST&accept=plain
Authorization: Basic xxxxx
User-Agent: Sympa/6.2.46
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info Sympa::DataSource::RemoteFile::_open() RESPONSE:HTTP/1.1 200 OK
Connection: TE, close
Date: Fri, 27 Sep 2019 06:07:09 GMT
Content-Type: text/plain; charset=utf-8
Client-Date: Fri, 27 Sep 2019 06:07:09 GMT
Client-Peer: 130.104.6.182:8243
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=NL/ST=Noord-Holland/L=Amsterdam/O=TERENA/CN=TERENA SSL CA 3
Client-SSL-Cert-Subject: /C=BE/L=Ottignies-Louvain-la-Neuve/O=Universit\xC3\xA9 catholique de Louvain/CN=esb.sgsi.ucl.ac.be
Client-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Client-SSL-Socket-Class: IO::Socket::SSL
Client-Transfer-Encoding: chunked
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=com-aca-ibst@listes.uclouvain.be;id=d3a3b862;role=member;name=comm-aca>: 0 included, 0 deleted, 0 updated, 0 kept
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=com-aca-ibst@listes.uclouvain.be;role=member>: 0 included, 0 deleted, 0 updated
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info main::do_review() [robot listes.uclouvain.be] [session 35262695295404] [client 130.104.40.228] [user pascal.maes@live.be] [list com-aca-ibst]
Sep 27 08:07:09 sympa-test.sipr.ucl.ac.be wwsympa[27417]: info main::_review_member() [robot listes.uclouvain.be] [session 35262695295404] [client 130.104.40.228] [user pascal.maes@live.be] [list com-aca-ibst] No subscriber

**Comment by pascalmaes** [comment]
I add another log line

    while (my $line = <$fh>) {
    $log->syslog('info', 'RESPONSE:%s', $line);
        last if $line =~ /\A\r?\n\z/;
    }

And I get all the email addresses

Sep 27 08:24:38 sympa-test.sipr.ucl.ac.be wwsympa[27665]: info Sympa::DataSource::RemoteFile::_open() RESPONSE:andre.moens@uclouvain.be
Sep 27 08:24:38 sympa-test.sipr.ucl.ac.be wwsympa[27665]: info Sympa::DataSource::RemoteFile::_open() RESPONSE:benjamin.elias@uclouvain.be

**Comment by ikedas** [comment]
You are right. The code you quoted discards all addresses.  This code may be removed:
``` patch
diff --git a/src/lib/Sympa/DataSource/RemoteFile.pm b/src/lib/Sympa/DataSource/RemoteFile.pm
index f97cce0..0e76e0c 100644
--- a/src/lib/Sympa/DataSource/RemoteFile.pm
+++ b/src/lib/Sympa/DataSource/RemoteFile.pm
@@ -108,9 +108,6 @@ sub _open {
         $log->syslog('err', 'Cannot open file %s: %m', $self->{_tmpfile});
         return undef;
     }
-    while (my $line = <$fh>) {
-        last if $line =~ /\A\r?\n\z/;
-    }
     return $fh;
 }
```

**Comment by pascalmaes** [comment]
Yes!!!

Sep 27 08:33:35 sympa-test.sipr.ucl.ac.be wwsympa[27864]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=com-aca-ibst@listes.uclouvain.be;id=d3a3b862;role=member;name=comm-aca>: 31 included, 0 deleted, 0 updated, 0 kept

And it's also good for the owner_include

Sep 27 08:34:33 sympa-test.sipr.ucl.ac.be wwsympa[27872]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=com-aca-ibst@listes.uclouvain.be;id=ec8b159d;role=owner;name=>: 0 included, 0 deleted, 0 updated, 1 kept

**Comment by pascalmaes** [comment]
I have still a problem with the owners and editors included by data_sources

In the config file, I have:

owner_include
source_parameters SC
reception mail
visibility noconceal
source owner_fac
profile privileged

The file owner_fac.incl is:

include_sql_query
db_type mysql
host sympa-tools.sipr.ucl.ac.be
user sylist
passwd XXXX
db_name dafs
sql_query SELECT DISTINCT email FROM owners WHERE fac='[% param.0 %]' AND sigle is null

Result 👍 
mysql> SELECT DISTINCT email FROM owners WHERE fac='SC' AND sigle is null;
+-----------------------------+
| email                       |
+-----------------------------+
| chantal.poncin@uclouvain.be |
+-----------------------------+
1 row in set (0.00 sec)


With debug level  3, I see that there is a connection to the database:

Sep 27 16:05:13 sympa-3.sipr.ucl.ac.be wwsympa[25048]: debug3 Sympa::Database::connect(Sympa::DatabaseDriver::MySQL <db_host=sympa-tools.sipr.ucl.ac.be;db_name=dafs;db_user=sylist>)
Sep 27 16:05:13 sympa-3.sipr.ucl.ac.be wwsympa[25048]: debug2 Sympa::Database::connect() Connected to Database Sympa::DatabaseDriver::MySQL <db_host=sympa-tools.sipr.ucl.ac.be;db_name=dafs;db_user=sylist>
Sep 27 16:05:13 sympa-3.sipr.ucl.ac.be wwsympa[25048]: debug2 Sympa::List::get_admins(Sympa::List <bsta2ms-g-b1@listes-student.uclouvain.be>, owner,  => )
Sep 27 16:05:13 sympa-3.sipr.ucl.ac.be wwsympa[25048]: debug3 Sympa::Database::do_prepared_query() Will perform query "SELECT date_epoch_admin AS "date", user_admin AS "email", comment_admin AS "gecos", inclusion_admin AS "inclusion", inclusion_ext_admin AS "inclusion_ext", inclusion_label_admin AS "inclusion_label", info_admin AS "info", profile_admin AS "profile", reception_admin AS "reception", subscribed_admin AS "subscribed", update_epoch_admin AS "update_date", visibility_admin AS "visibility", role_admin AS "role" FROM admin_table WHERE list_admin = ? AND robot_admin = ? ORDER BY user_admin"
Sep 27 16:05:13 sympa-3.sipr.ucl.ac.be wwsympa[25048]: debug3 Sympa::Database::do_prepared_query() Will perform query "INSERT INTO logs_table (date_logs, usec_logs, robot_logs, list_logs, action_logs, parameters_logs, target_email_logs, msg_id_logs, status_logs, error_type_logs, user_email_logs, client_logs, daemon_logs) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"

But no owners are added

Sep 27 17:39:12 sympa-3.sipr.ucl.ac.be wwsympa[13305]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=bsta2ms-g-b1-2019@listes-student.uclouvain.be;role=owner>
Sep 27 17:39:12 sympa-3.sipr.ucl.ac.be wwsympa[13305]: info Sympa::Request::Handler::include::_get_data_sources(Sympa::List <bsta2ms-g-b1-2019@listes-student.uclouvain.be>, owner)
Sep 27 17:39:12 sympa-3.sipr.ucl.ac.be wwsympa[13305]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=bsta2ms-g-b1-2019@listes-student.uclouvain.be;role=owner>: 0 included, 0 deleted, 0 updated


Same behavior with the editors and the members

**Comment by ikedas** [comment]
@pascalmars,
Please see #762.

**Comment by pascalmaes** [comment]
Thanks a lot

**Comment by iulistadmin** [comment]
Is this an issue with 6.2.60? From our logs:

Sympa::DataSource::File::_next#61 Too much errors in file . Source file probably corrupted. Cancelling

**Comment by racke** [comment]
@iulistadmin Please open up a new issue with more information, especially about "URL not being a direct link". The logs probably provide more lines related to your problem than the single one you posted.
