### ISSUE TITLE
after 6.2.44 to 6.2.46 upgrade, oracle data source no longer do anything?

### ISSUE THREAD

**Issue by skunktoy** [sympa-community/sympa#762]
Upgraded sympa from 6.2.44 to 6.2.46 on a SLES 12 linux box.
Working list, which uses an oracle data source no longer updates.
I can change the sql query to include more or fewer people but the list membership
no longer changes.  There are no errors that I can find the logs.

Confirmed that queries I'm trying still work with perl seperately.

Version
-------
6.2.46

Installation method
-------------------
Installed from source package.

Expected behavior
-----------------
Membership should be updated to match oracle sql query.

Actual behavior
---------------
No updated ocuring. 

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @skunktoy,

Could you please explain _how_ no update occurred:
- Tell us what you have done step by step.
- Show is the log from the beginning to ending of inclusion process.
- let us know how many members have been included before inclusion and how the members Weete changed (added, deleted, kept included).
- Show the configuration related to this issue — e.g. *.incl file and/or sections of list config file corresponding to inclusion.

**Comment by skunktoy** [comment]
If I change the sql_query select to include no users, I would expect all users to be unsubscribed, this does no happen.  If I change it so that it should include 500+ users instead of the 136 currently on the list, there is no change.

Inclusion section of config file,
include_sql_query
db_user user
sql_query select EMAIL from appworx_emu.PZV_EMU_EMPLOYEE_ADDR where ( ECLS = 'XX' ) 
name BERP
db_type Oracle
db_name cloudedhost.oraclecloudatcustomer.com:1521/PROD.emich.edu
db_env ORACLE_HOME=/usr/local/oracle/instantclient_12_1
db_passwd password

This current config should include no one as there is no such XX in use.

I will generate the logs and include them.

**Comment by skunktoy** [comment]
Here is a debug level 4 of me forcing an membership update through the web interface.
It deleted 0 updated 0 added 0, and it should have removed 136.

[sympa.log](https://github.com/sympa-community/sympa/files/3653095/sympa.log)

**Comment by ikedas** [comment]
> If I change the sql_query select to include no users, I would expect all users to be unsubscribed, this does no happen.
> If I change it so that it should include 500+ users instead of the 136 currently on the list, there is no change.

By each time, you may do either:
  - Select [User]-[Subscribers] and click [Synchronize members with data sources].
  - Wait for some time, mostly one hour is enough.
And show us the log.

**Comment by ikedas** [comment]
Hi @skunktoy,

Could you please apply [this patch](https://github.com/sympa-community/sympa/pull/764/commits/ead4a28) and check if the problem will be solved?

**Comment by skunktoy** [comment]
Yes, this patch appears to fix the issue.

Thanks! :)

**Comment by ikedas** [comment]
Related to #693.
