### ISSUE TITLE
Odd error message after upgrade from 6.2.44 to 6.2.46 

### ISSUE THREAD

**Issue by skunktoy** [sympa-community/sympa#763]
When changing some list options through the web interface, I get an odd error message.
For example if I change the list "Subject of the List" I get the following error, 

 INTERNAL SERVER ERROR (edit_list) - Failed to include list admins

This does no occur for options, just some of them.

Version
-------
6.2.46

Installation method
-------------------
From source code

Expected behavior
-----------------
Expect list to update with no errors

Actual behavior
---------------
List updates, give gives spurious error?

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @skunktoy,

Could you please show us these things?
- Sympa’s log when the error is shown.
- Sympa’s configuration related to inclusion: *.incl file and/or sections of lis config file corresponding to inclusion.

**Comment by skunktoy** [comment]
There is no error in the sympa.log file, I can turn on high debugging and generate the error and see if there is any information in the log, if that will help.

I get this on all lists, even ones with no inclusio *.incl file or such sections in the config file.

**Comment by skunktoy** [comment]
I forced this error again, and including the logs set at debug level 4, but I don't see an error reported here.  The error I'm seeing is reported to the browser add selecting to save my list changes.

[sympa.log](https://github.com/sympa-community/sympa/files/3653120/sympa.log)

**Comment by ikedas** [comment]
Could you please show us entire config file of any list?

**Comment by skunktoy** [comment]
owner
visibility noconceal
profile privileged
reception mail
email mgoebel@emich.edu

subject Description of what this list is woot woot 

visibility conceal

send authorconfirmantionformatt-test

digest 4 6:56

reply_to_header
value sender
apply respect

custom_subject reboots

reject_mail_from_automates_feature on

info private

subscribe closed

add auth

unsubscribe closed

del auth

invite closed

remind listmaster

review ownereditor

shared_doc
d_edit private
d_read private

process_archive on

archive
mail_access owner
web_access private

clean_delay_queuemod 15

pictures_feature on

creation
email mgoebel@emich.edu
date 13 Apr 16 at 09:48:48
date_epoch 1555610695

update
date_epoch 1569421725
email mgoebel@emich.edu

status open

serial 7

**Comment by ikedas** [comment]
Hi @skunktoy,
Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/764.patch) and check if problem will be solved?

**Comment by skunktoy** [comment]
Yes, that patch would appear to fix that issue.

**Comment by ikedas** [comment]
Related to #693.
