### ISSUE TITLE
Sync'ing from a file is failing in 6.2.46:  "Skip badly formed line"

### ISSUE THREAD

**Issue by pkissman** [sympa-community/sympa#766]
I just upgraded from 6.2.44 to 6.2.46 from source on a Debian host.
I have two flat files of email addresses that are included into some lists.
Sync'ing those files now completely fails with "Skip badly formed line" until the process aborts.

I am now seeing this in my sympa log file:

Sep 26 08:58:46 mblc-web01 wwsympa[31083]: err main::#1544 > main::do_sync_include#16517 > Sympa::List::sync_include#4825 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#292 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#75 Skip badly formed line: "myemail@myhostname.org#015"

Eventually I see the error:
Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#292 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#65 Too much errors in file /etc/sympa/pubdir-announce. Source file probably corrupted. Cancelling

There have been no changes other than the upgrade.  The included source file is exactly the same.

myemail@myhostname.org
youremail@anotherhostname.org

with unix linefeeds.

Any help would be appreciated.

Version
-------

Installation method
-------------------

Expected behavior
-----------------

Actual behavior
---------------

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @pkissman,

I guess the error message tells that the file contains lines with Microsoft newlines (CR+LF).

**Comment by racke** [comment]
@ikedas we should deal with that instead of throwing an error.

**Comment by pkissman** [comment]
I thought I had tried to convert the included file back and forth between a dos format and a unix format, since that was the first thing I had thought of.

But then I went to the script that generates the included file and it is definitely putting in a \r\n, so I guess I was wrong about my own file format.
Sorry about that.

But this is definitely a change in behavior between 6.2.44 and 6.2.46.

I have rolled everything to 6.2.44 since these mailing lists were needed.
But I will reinstall 6.2.46 on our development server and try again
I’ll report back whether the newline change solves the problem for me.

Thanks for your help.

**Comment by pkissman** [comment]
@ikedas and @racke ,

I reinstalled 6.2.46 and regenerated the included file I was having trouble with, but with Unix line breaks, and it did indeed solve the problem.   Thank you.  

I was also suffering from issues #763 every time I added and removed data sources.  #764 solved that problem.

However, I don't remember that email addresses which have been included from a file remained subscribed once the data source is removed.  I thought you still had the ability to sync the subscribers so that the included emails were automatically removed.  Is this new behavior, or am I misremembering?

**Comment by ikedas** [comment]
Current code looks supporting both LF and CR+LF:

https://github.com/sympa-community/sympa/blob/c4087f3cc26b1b466e2cc5a26eaa443f0ca668e8/src/lib/Sympa/DataSource/File.pm#L58-L79

It’s curious... By any chance you have been using CR+CR+LF? It was allowed by previous versions.

Anyways it’s incompatible change.  I’ll submit fixes later.

**Comment by ikedas** [comment]
Hi @pkissman,

Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/d21684511ae3e81bd37b2ab2efe6c31eb19f0087.diff) and check if the problem will be solved?

**Comment by ikedas** [comment]
Related to #693.

**Comment by pkissman** [comment]
Hi @ikedas,

Yes. This patch did fix the problem.  Files with CRLFs now get included properly.
