### ISSUE TITLE
list owner not defined

### ISSUE THREAD

**Issue by A3TH3RIUS** [sympa-community/sympa#767]
**Version**
-----------------
Sympa 6.2.41b.2

**Installation method**
-----------------
From Source

Expected behavior
-----------------
no error mail of the custom conditions.

Actual behavior
---------------
When one of the users of my list server goes on the web interface and places itself on a list, to which it subscribes or even owns in some cases, an error_performing_condition appears.

The logs also note that the list has no owners while there are:
``` code
Sep 30 08:53:22 listes wwsympa[8563]: List::new() The list "personnels.enspima" has got no owner defined
Sep 30 08:53:22 listes wwsympa[8563]: List::set_status_error_config() The list "personnels.enspima" is set in status error_config
Sep 30 08:53:22 listes wwsympa[8563]: List::get_user_db() Sympa not setup to use DBI
Sep 30 08:53:22 listes wwsympa[8563]: err main::#1517 > main::check_param_in#2609 > Sympa::Scenario::authz#419 > Sympa::Scenario::_verify#1126 > Sympa::Scenario::_verify_custom#1454 Error evaluating verifipb: Operation 'OPEN' not supported on FCGI::Stream handle at /home/sympa/bin/mail.pm line 766.#012 ()
```
There is also some lists on a series of "Bad entry" logs while the list works perfectly.
And there are  some lists where the owners suddenly disappear.
Unfortunately, as these errors occur randomly, I do not know how to reproduce them.

**Comment by ikedas** [comment]
Hi @A3TH3RIUS,

Sympa 6.2.41b.2 does never have a module "List" but has "Sympa::List".  I see you mixed modules of earlier version (maybe 6.1.x) and 6.2.41b.2 of Sympa.

It's surprising that your server looks working somewhat properly. However, none can know whether your server is running surely properly.

Please retry installing Sympa, i.e.: Remove _everything_ in your server, and cleanly install Sympa again.

**Comment by ikedas** [comment]
Relating to #600.

**Comment by ikedas** [comment]
Close by now.
