### ISSUE TITLE
Huge growth in msyql-bin.XXXXXX logs with 6.2.46 or 6.2.48

### ISSUE THREAD

**Issue by skunktoy** [sympa-community/sympa#769]
So something with member inclusion seems to have driven the growth of the mysql binary logs up hugely with the newer versions.  I'm including 48603 users from an ldap source on one list and have a couple of other lists including a couple of hundred people each from an oracle source.  I did not notice this growth earlier until it triggered a monitor that the disk in question was filling up.  I have had to change log expiration from 60 days down to 4 in mysql to keep the disk reasonable usable.

Not a show stopper, but a surprising change .

-------
6.2.46 and 6.2.48

Installation method
-------------------

Expected behavior
-----------------
Rapid growth of mysql change logging, there must be a lot more database changes going on with membership inclusion than there were before.

Actual behavior
---------------
Rapid growth of mysql binary change logs.

Additional information
----------------------
We have not changed anything with mariadb during or after the sympa upgrades other than the expiration time for the logs.

**Comment by ikedas** [comment]
Hi @skunktoy,

[Upgrading notes(...) says:

> Inclusion feature of members, owners or moderators has been reconstructed. Slightly long time can be spent to refresh inclusion of users entirely at the first time just after upgrade.

Users would be refreshed entirely at the first time. I guess that’s (at least one of) why the logs grew rapidly.

**Comment by racke** [comment]
@skunktoy, can you check whether any tables in your database are very large?

Example SQL query:

```
SELECT  table_schema as `Database`,  table_name AS `Table`,  round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB`  FROM information_schema.TABLES  where table_schema = 'sympa' ORDER BY (data_length + index_length) DESC;`
```

If your Sympa database has a different name than `sympa`, please adjust the query.

**Comment by skunktoy** [comment]
MariaDB [sympa]> SELECT  table_schema as `Database`,  table_name AS `Table`,  round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB`  FROM information_schema.TABLES  where table_schema = 'sympa' ORDER BY (data_length + index_length) DESC;
+----------+-----------------------+------------+
| Database | Table                 | Size in MB |
+----------+-----------------------+------------+
| sympa    | stat_table            |      65.16 |
| sympa    | subscriber_table      |      33.64 |
| sympa    | mail_aliases          |       0.19 |
| sympa    | session_table         |       0.09 |
| sympa    | logs_table            |       0.08 |
| sympa    | stat_counter_table    |       0.06 |
| sympa    | admin_table           |       0.03 |
| sympa    | one_time_ticket_table |       0.02 |
| sympa    | notification_table    |       0.02 |
| sympa    | netidmap_table        |       0.02 |
| sympa    | list_table            |       0.02 |
| sympa    | inclusion_table       |       0.02 |
| sympa    | exclusion_table       |       0.02 |
| sympa    | conf_table            |       0.02 |
| sympa    | bulkspool_table       |       0.02 |
| sympa    | bulkmailer_table      |       0.02 |
| sympa    | user_table            |       0.02 |
+----------+-----------------------+------------+
17 rows in set (0.01 sec)

**Comment by skunktoy** [comment]
Looking through one the binary log files it like every time sympa runs the user include for each list it is updating each subscriber entry.  Would this be the expected behavior?

UPDATE subscriber_table SET inclusion_subscriber = '1570463041', inclusion_ext_subscriber = '1570463041' WHERE user_subscriber = 'XXX@emich.edu' AND list_subscriber = 'matt-employees' AND robot_subscriber = 'YYY.emich.edu' AND inclusion_subscriber IS NOT NULL AND '1570463039' <= inclusion_subscriber

Matt

**Comment by ikedas** [comment]
It's expected behavior.  Previously (with 6.2.44 or earlier), large number of (possiblly hundreds of thousands of) users were loaded into the memory at first, then Sympa added and deleted users in database.  With such behavior, Sympa needed big memory to handle _all_ users at once, despite it used external database.

**Comment by skunktoy** [comment]
Okay, that makes sense, I will adjust our logging accordingly.

Thanks!
