### ISSUE TITLE
extending CSRF support

### ISSUE THREAD

**Issue by fpoulain** [sympa-community/sympa#780]
Hi,

It would be great if sympa extends CSRF support. Currently, we have some lists opened to subscription with auth (email loop). Those subscribe forms are spamed by bots (thousand per day). We don't have any real solution avoiding this at hosting level.

Several techniques could limit spam, starting with a CSRF token.

I saw that since 2c0e8109c3 and b30815ce91 there is csrf protection. Could it be possible please to (maybe optionally) extends this protection for all public forms?

**Comment by ikedas** [comment]
Hi @fpoulain, could you please tell us what version of Sympa you are using?

**Comment by ikedas** [comment]
Hi @fpoulain,

Feature of CSRF tolerance is available on Sympa 6.2.40 or later.  On Debian, Sympa with this feature is provided by buster or bullseye.  Unfortunately buster does not provide it.

**Comment by fpoulain** [comment]
> Feature of CSRF tolerance is available on Sympa 6.2.40 or later.

Nice. Is it generalized to all forms posts ?

**Comment by ikedas** [comment]
I think it is generalized to all forms which are provided by WWSympa.

**Comment by ikedas** [comment]
Close by now.
