### ISSUE TITLE
Database membership updates now fail silently if there is an error

### ISSUE THREAD

**Issue by skunktoy** [sympa-community/sympa#781]
sympa-6.2.48 on SLES 12.4 

I have noticed that if you write a bad query and try to manually force a membership update through the web interface it now fails silently instead of putting up and error like it used to. Curious if this this new expected behavior?

Thanks!

**Comment by skunktoy** [comment]
An example error from the sympa.log file : 

2019-11-05T09:34:21.826152-05:00 boxname wwsympa[4249]: err main::#1544 > main::do_sync_include#16517 > Sympa::List::sync_include#4828 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#289 > Sympa::DataSource::open#134 > Sympa::DataSource::SQL::_open#99 > Sympa::Process::eval_in_time#472 > (eval)#479 > (eval)#479 > Sympa::DataSource::SQL::__ANON__#53 Unable to connect to SQL data source Sympa::DataSource::SQL <context=atm@boxname.emich.edu;id=cbb530e4;role=member;name=INSTANCE>

I had forgotten a single ' in the query and when I put that in the list successfully updated.

**Comment by ikedas** [comment]
OK. Thanks for sharing your experiences!  Close.

**Comment by cgx** [comment]
I'm surprise this issue has been closed so quickly. I think the behaviour must be improved. An error message should be displayed when a user defines an invalid SQL query. Would reconsider the issue @ikedas?

**Comment by ikedas** [comment]
Error message is displayed in the log (and I guess that more detailed logs describing SQL syntax error might also be shown).  I don't think it "silent".

**Comment by racke** [comment]
Well but not sufficient either, it should contain at least the SQL error.

**Comment by ikedas** [comment]
> Well but not sufficient either, it should contain at least the SQL error.

Could you please reproduce “no SQL error”?

**Comment by racke** [comment]
Not at the moment, but will setup a test case. I refer to a SQL error like 

```
MariaDB [sympa]> select noway from  subscriber_table;
ERROR 1054 (42S22): Unknown column 'noway' in 'field list'
```

**Comment by racke** [comment]
Ok, the SQL error is displayed in the log. @skunktoy please provide more information about your specific case.

**Comment by skunktoy** [comment]
Hey,

  Before 6.2.48 the web interface would display an error status of some kind, sorry I don't recall what it said if a bad query was attempted through the web interface - aka attempt to resync the membership list.  Now if the query is bad it fails silently on the web interface side, so you have notice that the membership was not updated to look in the logs and see that there is an error.
  Usually not an issue bit one fat fingering on entering something through web interface and the users get to scratch their heads on confusion.

Thanks!

**Comment by racke** [comment]
Yes that might be the case. I just opened an issue on a related problem:  #907

**Comment by skunktoy** [comment]
That sounds very similar, and just as confusing.
