### ISSUE TITLE
Can't access to family of list creation menu after upgrade from 6.2.22 to 6.2.48

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#788]
-------

6.2.48 RPM installation from repository

Installation method
yum upgrade from 6.2.22 
-------------------

RPM installation from repository on redhat 7.6

Expected behavior
-----------------

I should access to the menu of family list creation.

Actual behavior
---------------

I have the following error 
ERREUR (create_automatic_list_request) - La liste '' est inconnue. 

In the log 
Nov  8 10:15:24 tcgisympa2 wwsympa[8766]: info main:: [robot listes-int.dsi.cnrs.fr] [session 54325746428645] [client 10.238.10.3] [user listmaster-int@dsi.cnrs.fr] Unknown list "jean-test"

Additional information
----------------------

**Comment by ikedas** [comment]
Hi @jth56000,
Could you please tell us how you accessed to the "family of list creation menu" step-by-step? Thanks for patience.

**Comment by jth56000** [comment]
Hi @jth56000<https://github.com/jth56000>,
Could you please tell us how you accessed to the "family of list creation menu" step-by-step? Thanks for patience.

On my web interface I have a direct access to my families on the left menu here in Red :

[cid:image001.png@01D5963B.EABF2550]

I have the error when I click on one of this family of lists.

Jean

**Comment by ikedas** [comment]
Sorry, attachments in e-mail are removed.  Can you log in to GitHub and upload screen shots?

**Comment by jth56000** [comment]
Here is the screen shot 

![image](https://user-images.githubusercontent.com/52824032/68648936-dbeca480-0521-11ea-861c-59f635fa2c16.jpg)

**Comment by jth56000** [comment]
NB : it was working on 6.2.45.b2

**Comment by ikedas** [comment]
@jth56000, please tell us ---
- The URLs labels like "Listes de diffusion DRH" link to.
- All of the log entries just after you clicked the link and just before the screen was refreshed.
- Settings about families (such as `automatic_list_creation`, `automatic_list_families`) in `sympa.conf` and/or `robot.conf`

**Comment by jth56000** [comment]
@jth56000<https://github.com/jth56000>, please tell us ---

  *   The URLs labels like "Listes de diffusion DRH" link to.
https://listes-int.dsi.cnrs.fr/wws/automatic_lists_request/drh

  *   All of the log entries just after you clicked the link and just before the screen was refreshed.
In log levl 2 :
Nov 12 09:10:20 tcgisympa2 task_manager[34245]: info Sympa::List::_load_list_config_file() Missing key "date_epoch" in param "creation" in /datasan/sympa/list_data/listes-int.dsi.cnrs.fr/sgen-cfdt+all-01-all-all/config
Nov 12 09:10:20 tcgisympa2 task_manager[34245]: info Sympa::List::_load_list_config_file() Missing key "email" in param "creation" in /datasan/sympa/list_data/listes-int.dsi.cnrs.fr/snptes+all-06-all-all/config
Nov 12 09:10:20 tcgisympa2 task_manager[34245]: info Sympa::List::_load_list_config_file() Missing key "date_epoch" in param "creation" in /datasan/sympa/list_data/listes-int.dsi.cnrs.fr/snptes+all-06-all-all/config
Nov 12 09:10:22 tcgisympa2 wwsympa[34124]: info main:: [robot listes-int.dsi.cnrs.fr] [session 65017074295761] [client 10.238.30.3] [user listmaster-int@dsi.cnrs.fr] Unknown list "drh"
Nov 12 09:10:29 tcgisympa2 sympa_msg[34238]: debug2 Sympa::List::new(listetest2, listes-int.dsi.cnrs.fr, just_try)
Nov 12 09:10:29 tcgisympa2 sympa_msg[34238]: debug2 Sympa::List::load(Sympa::List <>, listetest2, listes-int.dsi.cnrs.fr, ...)
Nov 12 09:10:29 tcgisympa2 sympa_msg[34238]: debug2 Sympa::List::new(listetest1, listes-int.dsi.cnrs.fr, just_try)
Nov 12 09:10:29 tcgisympa2 sympa_msg[34238]: debug2 Sympa::List::load(Sympa::List <>, listetest1, listes-int.dsi.cnrs.fr, ...)
Nov 12 09:10:29 tcgisympa2 sympa_msg[34238]: debug2 Sympa::List::new(liste_test_jean_thomas_9, listes-int.dsi.cnrs.fr, just_try)
Nov 12 09:10:29 tcgisympa2 sympa_msg[34238]: debug2 Sympa::List::load(Sympa::List <>, liste_test_jean_thomas_9, listes-int.dsi.cnrs.fr, ...)


  *   Settings about families (such as automatic_list_creation, automatic_list_families) in sympa.conf and/or robot.conf
In sympa . conf :
automatic_list_feature on
automatic_list_creation family_owner
automatic_list_removal if_empty

In robot.conf :
automatic_list_removal    if_empty
automatic_list_families name=sgen-cfdt:prefix=sgen-cfdt:display=Listes syndicales sgen-cfdt:prefix_separator=+:classes_separator=-:family_owners_list=SGEN-CFDT@syndicats.cnrs.fr;name=sncs-fsu:prefix=sncs-fsu:display=Listes syndicales sncs-fsu:prefix_separator=+:classes_separator=-:family_owners_list=sncs@cnrs.fr;name=snirs-cgc:prefix=snirs-cgc:display=Listes syndicales snirs-cgc:prefix_separator=+:classes_separator=-:family_owners_list=Snirs-cfecgc@syndicats.cnrs.fr;name=snprees-fo:prefix=snprees-fo:display=Listes syndicales snprees-fo:prefix_separator=+:classes_separator=-:family_owners_list=SNPREES-FO@syndicats.cnrs.fr;name=snptes:prefix=snptes:display=Listes syndicales snptes:prefix_separator=+:classes_separator=-:family_owners_list=SNPTES@syndicats.cnrs.fr;name=sntrs-cgt:prefix=sntrs-cgt:display=Listes syndicales sntrs-cgt:prefix_separator=+:classes_separator=-:family_owners_list=SNTRS-CGT@syndicats.cnrs.fr;name=sud-recherche-epst:prefix=sud-recherche-epst:display=Listes syndicales sud-recherche-epst:prefix_separator=+:classes_separator=-:family_owners_list=SUD-RECHERCHE-EPST@syndicats.cnrs.fr;name=drh:prefix=drh:display=Listes de diffusion DRH:prefix_separator=+:classes_separator=-:family_owners_list=drh.communication@cnrs.fr;name=jean-test:prefix=jean-test:display=Listes Test Jean:prefix_separator=+:classes_separator=-:family_owners_list=jean.thomas@ext.dsi.cnrs.fr

**Comment by ikedas** [comment]
If you have customized `web_tt2/sympa_menu.tt2`, please take back it, i.e. remove customized template file.

**Comment by jth56000** [comment]
If you have customized web_tt2/sympa_menu.tt2, please take back it, i.e. remove customized template file.

Yes it works better.
