### ISSUE TITLE
No date header in messages posted directly from the sympa web site

### ISSUE THREAD

**Issue by scheff** [sympa-community/sympa#791]
Version
-------

Sympa 6.2.44
Debian GNU/Linux 9.11 (stretch)

Installation method
-------------------

source package

Expected behavior
-----------------

Messages shown in the archive of an list 
    URL: .../sympa/arc/LISTNAME/YYYY_MM/
should be included in the output when queriing the latest messages of a list 
    URL: .../sympa/latest_arc/LISTNAME?count=10

Actual behavior
---------------
Messages send after upgrading to Sympa 6.2.44 are not included in the output of latest_arc.

Additional information
----------------------

After editing a message and inserting a the header manually, e.g.

    Date: Fri, 25 Oct 2019 11:11:11 +0000

and rebuilding the archive ther message is shown in the output of latest_arc.

**Comment by ikedas** [comment]
Hi @scheff,

Could you please apply [this patch](https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/793.patch) and check if Date field will be inserted properly?

And for my information: What are the name and version of MTA software you are using with Sympa?

**Comment by racke** [comment]
@ikedas I actually thought about asking the MTA question. But independent of that we *should* add the date, otherwise we get an "unknown" date in the moderation overview. Thanks for your patch!

**Comment by ikedas** [comment]
@racke you are right. My Postfix has been overprotectively adding missing Date field and I have never realized it was missing!

**Comment by racke** [comment]
Emails originating from the "compose email" are processed before submitted to a MTA, that's why we got the problem. I suppose that all established MTAs are adding standard fields like Message-ID and Date if they are missing.

**Comment by scheff** [comment]
Am 08.11.19 um 15:44 schrieb IKEDA Soji:
>
> Hi @scheff <https://github.com/scheff>,
>
> Could you please apply this patch
> <https://patch-diff.githubusercontent.com/raw/sympa-community/sympa/pull/793.patch>
> and check if Date field will be inserted properly?
>
> And for my information: What are the name and version of MTA software
> you are using with Sympa?
>
>
Hi Soji, hi Stefan,

the patch solved the issue. :-)

Messages posted from the Sympa web site after applying the patch contain
a date header and are listed with latest_arc.

While testing the patch I noticed a small difference in the URL of mails
send by a mail client and from the Sympa web site in the output of
latest_arc:

    *Send by a mail client:*

    https://lists.uni-mainz.de/sympa/arcsearch_id/000-testliste-1/2019-11/55f39782-a0bd-5806-7539-970d5ef9fdf1%40uni-mainz.de

    *Send from the Sympa web site:*

    https://lists.uni-mainz.de/sympa/arcsearch_id/000-testliste-1/2019-11/*sympa.*1573463004.25894.778%40lists.uni-mainz.de

Both URL are valid. This difference is not caused by the patch. It was
probably introduced with Sympa 6.2.44, too.

Thank you and best regards

Thomas

PS: The MTA is sendmail (8.15.2-8).


-- 
--------------------------------------------------------------------------
Mail  thomas.scheffczyk@uni-mainz.de  Johannes Gutenberg-Universität Mainz
Tel.  +49 6131 39 26399               Zentrum für Datenverarbeitung
GnuPG B84D 8BE9 6F5C A832 60A2        Anselm-Franz-von-Bentzel-Weg 12
      41C0 C483 76EB AA49 FA72        55128 Mainz

**Comment by ikedas** [comment]
@scheff, thanks so much for confirming fix! The fix will be included in the next stable release, maybe 6.2.50.
