### ISSUE TITLE
Bounced crash - missing Encode::HanExtra

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#8]
```
Apr 15 09:49:16 post bounced[1513]: notice main:: Bounced 6.2.16 Started
Apr 15 09:49:17 post bounced[1513]: err main::#157 > Sympa::Spindle::spin#75 > Sympa::Spool::next#135 > Sympa::Message::new#180 > MIME::Charset::new#432 > MIME::Charset::_find_encoder#467 > (eval)#1 > (eval)#1 > MIME::Charset::BEGIN#1 DIED: Can't locate Encode/HanExtra.pm in @INC (you may need to install the Encode::HanExtra module) (@INC contains: /usr/share/sympa/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at (eval 204) line 1.
```
This happened with a Debian install.

So

1. First we need to make sure that this module is installed.
2. Bounced should discard the message and not trying it at every run.

**Comment by ikedas** [comment]
@racke, would you please try updating MIME-Charset to latest version?

**Comment by racke** [comment]
First of all it is a really serious problem, because that stops the bounce processing altogether. So I ended up with more 3K unprocessed emails in the machine on question.

**Comment by racke** [comment]
Current version of MIME::Charset is 1.011.1-1+deb8u2 (Debian Jessie).

**Comment by ikedas** [comment]
At least 1.011.3 on CPAN seems requred (Changelog of [MIME-Charset](http://cpansearch.perl.org/src/NEZUMI/MIME-Charset-1.012.2/Changes) and [Sympa-6.2](https://github.com/sympa-community/sympa/commit/56466f713154ab9dbba9348b55a25933d7377f11)).

Note that MIME-Charset-1.011.3 on GitHub is broken.  1.012 would be used.

**Comment by ikedas** [comment]
Hi,

I could reproduce this issue and solution with 6.2.18.

If MIME-Charset 1.011.1 was installed and Encode-HanExtra was _not_ installed,
- sympa_msg.pl crashed, message was kept in msg spool:
```
Jul 14 16:16:43 XXXXX sympa_msg[28868]: err main::#240 > Sympa::Spindle::spin#75 > Sympa::Spool::next#139 > Sympa::Message::new#165 > Sympa::Message::_get_sender_email#273 > MIME::EncWords::decode_mimewords#452 > MIME::EncWords::_convert#476 > MIME::Charset::new#428 > MIME::Charset::_find_encoder#463 > (eval)#1 > (eval)#1 > MIME::Charset::BEGIN#1 DIED: Can't locate Encode/HanExtra.pm in @INC (@INC contains: /usr/share/sympa/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at (eval 278) line 1.
```

If MIME-Charset 1.011.1 was installed and Encode-HanExtra was installed,
- Message was delivered.

If MIME-Charset 1.011.3 was installed and Encode-HanExtra was _not_ installed,
- Message was delivered.

IF MIME-Charset 1.011.3 was installed and Encode-HanExtra was installed,
- Message was delivered.

**Comment by racke** [comment]
Done.
