### ISSUE TITLE
Fix ridiculous English spelling for spam protection button

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#80]
`This button trys to protect the mailing lists archives against address harvesting by a Spammer.`

3rd person of try is "tries" - and spammer should be lowercase. In addition this message is quite pathetic in general. I will *try* to come up with a better one.

**Comment by ikedas** [comment]
Errors in translation (including English) would be corrected on translation site: https://translate.sympa.org/
Would you please check it?

**Comment by racke** [comment]
OK, done that.

**Comment by ikedas** [comment]
Closd at present.
