### ISSUE TITLE
Search for list does not work after upgrade from 6.2.22 to 6.2.48

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#801]
Version
-------
SYMPA 6.2.48 on RedHat 7.6

Installation method
-------------------
RPM installation from repository

Expected behavior
-----------------
Searching for a list should work

Actual behavior
---------------
The search timeout with the message :
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at assistance@dsi.cnrs.fr to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additional information
----------------------
No specific message in sympa log file

**Comment by jth56000** [comment]
Hi @jth56000<https://github.com/jth56000>,
Please show us these things:

  *   How you "search" the message?
For example: "opened a page '...', enter a keyword '...' in '...' text box, then clicked '...' button, and ...".
  *   Log of Sympa during the operation above.
Hello Ikeda,
The problem is not when I search for a message but when I search for a list in the main page of the interface.
It hangs.
Jean

**Comment by jth56000** [comment]
Hi @jth56000<https://github.com/jth56000>,
Please show us these things:

  *   How you "search" the message?
For example: "opened a page '...', enter a keyword '...' in '...' text box, then clicked '...' button, and ...".
  *   Log of Sympa during the operation above.

In the log I have :
Nov 15 10:52:48 tcgisympa2 wwsympa[126083]: info main::do_search_list(liste_test_jean_thomas) [robot listes-int.dsi.cnrs.fr] [session 65017074295761] [client 10.238.30.3] [user listmaster-int@dsi.cnrs.fr]
Nov 15 10:52:55 tcgisympa2 task_manager[88254]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=snprees-fo+all-all-1-all@listes-int.dsi.cnrs.fr;id=1e8469fa;role=member;name=>: 6 included, 0 deleted, 33750 updated, 32 kept
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=snprees-fo+all-all-1-all@listes-int.dsi.cnrs.fr;role=member>: 6 included, 6 deleted, 33750 updated
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::do_next() line 5 of sync_include: next(1573897977, INIT)
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: notice Sympa::Spool::store() Sympa::Task <date=1573897977;label=INIT;model=sync_include;context=snprees-fo+all-all-1-all@listes-int.dsi.cnrs.fr> is stored into Sympa::Spool::Task as <1573897977.INIT.sync_include.snprees-fo+all-all-1-all@listes-int.dsi.cnrs.fr>
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::do_next() --> new task Sympa::Task <date=1573897977;label=INIT;model=sync_include;context=snprees-fo+all-all-1-all@listes-int.dsi.cnrs.fr>
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1573811278;label=INIT;model=sync_include;context=snprees-fo+all-all-1-all@listes-int.dsi.cnrs.fr> is now useless. Removing it
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1573811281;label=INIT;model=sync_include;context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr>
Nov 15 10:52:57 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr;role=member>
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::RemoteFile <context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr;id=ab8b1090;role=member;name=>: 0 included, 0 deleted, 2560 updated, 0 kept
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr;role=member>: 0 included, 0 deleted, 2560 updated
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::do_next() line 5 of sync_include: next(1573897982, INIT)
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: notice Sympa::Spool::store() Sympa::Task <date=1573897982;label=INIT;model=sync_include;context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr> is stored into Sympa::Spool::Task as <1573897982.INIT.sync_include.snptes+all-all-all-a@listes-int.dsi.cnrs.fr>
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::do_next() --> new task Sympa::Task <date=1573897982;label=INIT;model=sync_include;context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr>
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1573811281;label=INIT;model=sync_include;context=snptes+all-all-all-a@listes-int.dsi.cnrs.fr> is now useless. Removing it
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1573811286;label=INIT;model=sync_include;context=elections2019cneser_chercheurs@listes-int.dsi.cnrs.fr>
Nov 15 10:53:02 tcgisympa2 task_manager[88254]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=elections2019cneser_chercheurs@listes-int.dsi.cnrs.fr;role=member>
Nov 15 10:53:04 tcgisympa2 task_manager[88254]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 > Sympa::List::sync_include#4825 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#292 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#75 Skip badly formed line: "Bereng▒re.abou@univ-paris-diderot.fr"
Nov 15 10:53:04 tcgisympa2 task_manager[88254]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 > Sympa::List::sync_include#4825 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#292 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#75 Skip badly formed line: "Bereng▒re.dubrulle@cea.fr"
Nov 15 10:53:04 tcgisympa2 task_manager[88254]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 > Sympa::List::sync_include#4825 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#292 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#75 Skip badly formed line: "Bereng▒re.fromy@ibcp.fr"
Nov 15 10:53:04 tcgisympa2 task_manager[88254]: err main::#148 > Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessTask::_twist#74 > Sympa::Spindle::ProcessTask::_execute#140 > Sympa::Spindle::ProcessTask::_cmd_process#174 > Sympa::Spindle::ProcessTask::do_sync_include#1349 > Sympa::List::sync_include#4825 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#181 > Sympa::Request::Handler::include::_update_users#292 > Sympa::DataSource::next#149 > Sympa::DataSource::File::_next#75 Skip badly formed line: "Bereng▒re.perello@mom.fr"

**Comment by jth56000** [comment]
Hi @jth56000<https://github.com/jth56000>,
Please show us these things:

  *   How you "search" the message?
For example: "opened a page '...', enter a keyword '...' in '...' text box, then clicked '...' button, and ...".
  *   Log of Sympa during the operation above.
In Httpd error log file I have :
[Fri Nov 15 10:53:28.592832 2019] [fcgid:warn] [pid 126095] [client 10.238.30.3:59594] mod_fcgid: read data timeout in 40 seconds, referer: https://listes-int.dsi.cnrs.fr/wws/search_list_request
[Fri Nov 15 10:53:28.595994 2019] [core:error] [pid 126095] [client 10.238.30.3:59594] End of script output before headers: wwsympa.fcgi, referer: https://listes-int.dsi.cnrs.fr/wws/search_list_request

**Comment by racke** [comment]
How many mailing lists do you have on your Sympa instance? Does the error go away if you increase the mod_fcgid timeout?

**Comment by jth56000** [comment]
How many mailing lists do you have on your Sympa instance? Does the error go away if you increase the mod_fcgid timeout?

We have more than 3600 lists on our instance.

How do we increase mod_fcgid timeout I did not find the parameter in the config file.

**Comment by racke** [comment]
So the problem might be that 6.2.48 is less efficient than 6.2.22 when it comes to dealing with a large number of lists. For increasing mod_fcgid please consult the corresponding Apache documentation.

**Comment by jth56000** [comment]
So the problem might be that 6.2.48 is less efficient than 6.2.22 when it comes to dealing with a large number of lists. For increasing mod_fcgid please consult the corresponding Apache documentation.



Ok I found how to modify fcgid timeout and now it works fine, Thanks a lot.



Jean
