### ISSUE TITLE
Subscribers marked as "delivery failed" after attempted spam delivery

### ISSUE THREAD

**Issue by sumpfralle** [sympa-community/sympa#809]
I noticed an issue with a mailing list configured as `public`:
1. incoming spam email targeted at the mailing list
2. mailing list mail server accepts the mail (maybe it barely escaped the spam detection)
3. sympa receives the mail
4. sympa tries to deliver the mail to its subscribers
5. all subscribers reject the incoming mail due to its spam appearance
6. all subscribers are marked as *failed delivery*
7. further mails to the mailing list are rejected (*all subscribers are marked as failed delivery*)

I think, sympa should not treat spam-based rejections as individual delivery problems for specific recipients. Instead it should ignore content-based rejections.

The following log message (anonymized IP address) appeared in my mailing list server (postfix) when its delivery was rejected (by a local milter process - rspamd):
```
milter-reject: END-OF-MESSAGE from baz.example.com[10.0.0.0]: 5.7.1 Spam message rejected; from=<foo-owner@lists.example.org> to=<foo@example.org> proto=ESMTP helo=<mail.example.org>
```

Probably I will need to enable moderation for incoming emails from non-subscribers. But I would like to avoid this friction.

Do you have other suggestions?

**Comment by ikedas** [comment]
Hi @sumpfralle,

Why don't you filter incoming emails by spam checker?

Outgoing messages may be rejected by various reasons, and it is difficult for Sympa to know whether a message delivery was rejected due to its spam appearance or due to another reason.

**Comment by sumpfralle** [comment]
> Why don't you filter incoming emails by spam checker?

I do. But the spam filtering on my mail server differs (inevitably) from the spam filtering setup of the subscribers' mail servers.

When my mail server tried to deliver a mail that the local spam filtering considered to be barely not-spammy-enough to be discarded, this mail was rejected by all receiving mail servers.

At the moment we enable moderation for mails above a specific spam probability level.

Maybe this is the best approach for this problem of asymmetric spam filtering rules. I cannot tell.

Feel free to close this issue, if you think, that the handling of spam-related rejections should not or cannot be separated from usual rejection handling.

**Comment by ikedas** [comment]
Closed for now.  Thank you for sharing your experiences!
