### ISSUE TITLE
Error processing scenario

### ISSUE THREAD

**Issue by BrunoMalaval** [sympa-community/sympa#813]
Version
-------
6.2.49b.1

Installation method
-------------------
Source package

Expected behavior
-----------------
Fix parsing scenario

Actual behavior
---------------
In a create scenario (create_list.uha) , I use 2 ldap search filters to control creation list

Scenario is

```
is_listmaster([sender])     md5,smime -> do_it
equal([sender],'dnum.listmaster@uha.fr')        md5,smime -> do_it
search(membres_di.ldap)     md5,smime -> do_it
search(personnel_uha.ldap)  smtp,md5,smime -> listmaster,notify
true()                      smtp,md5,smime -> reject(reason='create_list_local_user')
```
On the home page, I get this error

```
DIED: /usr/local/sympa/etc/scenari/create_list.uha: Bareword "membres_di" not allowed while "strict subs" in use at (eval 177) line 17. Bareword "ldap" not allowed while "strict subs" in use at (eval 177) line 17. Bareword "personnel_uha" not allowed while "strict subs" in use at (eval 177) line 20. Bareword "ldap" not allowed while "strict subs" in use at (eval 177) line 20. 
 at /usr/local/sympa/bin/Sympa/Scenario.pm line 249.
Sympa::Scenario::compile('lists-diff.uha.fr', 'title.gettext Demande de creation de liste UHA\x{a}\x{a}is_listmaster...', 'function', 'create_list', 'file_path', '/usr/local/sympa/etc/scenari/create_list.uha') called at /usr/local/sympa/bin/Sympa/Scenario.pm line 218
Sympa::Scenario::new('Sympa::Scenario', 'lists-diff.uha.fr', 'create_list') called at /usr/local/sympa/bin/wwsympa.fcgi line 2697
main::check_param_in() called at /usr/local/sympa/bin/wwsympa.fcgi line 1503
```
I test to remove the first ``search()`` , and get the same error for the second

Additional information
----------------------

Thanks a lot
Bruno

**Comment by racke** [comment]
I suppose this works in earlier versions of Sympa?

**Comment by BrunoMalaval** [comment]
Yes,
It works fine on my production server (6.2.16)
And tested on a 6.2.44 with no error.

It looks like an error in parsing scenario, not when process it

**Comment by racke** [comment]
The module has been recently rewritten (#782), so it looks like a regression. Thanks for testing the beta version and reporting the problem!

**Comment by ikedas** [comment]
Hi @BrunoMalaval ,

Could you please apply [this patch](https://github.com/ikedas/sympa/commit/c436b4f.patch) and check if the problem will be solved? Thanks.

**Comment by BrunoMalaval** [comment]
Hi @ikedas 

It fix the error, so I can connect and will continue my tests

Thanks a lot, great job
