### ISSUE TITLE
No moderation on signed message on 6.2.22

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#819]
Version
-------
6.2.22 : sympa-6.2.22-1.20171002.RHEL7.x86_64
Installation method
-------------------
RPM Installation on RdeHat 7.6

Expected behavior
-----------------
signed message should be moderate with the following scenario 👍 

#cat /usr/share/sympa/default/scenari/send.newsletterkeyonly
title.gettext Newsletter, restricted to moderators after confirmation

is_editor([listname],[sender])                 smime           -> do_it
is_editor([listname],[sender])                 smtp,dkim,md5,smime  -> editorkey
true()

Actual behavior
---------------
Only unsigned message are sent to moderation.
Signed message are directly distributed

Additional information
----------------------
We reproduce the same issue in 6.2.48 RPM installation on RedHat 7.6.
It was working correctly on our old server running 6.2.22 tar.gz installation on RedHat 5.8
We tried with 2 different certificates.

**Comment by racke** [comment]
So the message is signed with S/MIME, but the sender is not an editor?

**Comment by jth56000** [comment]
So the message is signed with S/MIME, but the sender is not an editor?
The sender is the same on signed or unsigned message, he is an editor but only unsigned message are sent to moderation.

**Comment by racke** [comment]
Your bug report is a bit confusing, as you state 6.2.22 in subject but in the description it does work with 6.2.22 on your old server.

Also, I think it does exactly what you specified:

`is_editor([listname],[sender]) smime -> do_it`

Which translates into bypass the moderation (second instruction in the scenario) when sender is an editor and the message is signed with S/MIME.

**Comment by jth56000** [comment]
Your bug report is a bit confusing, as you state 6.2.22 in subject but in the description it does work with 6.2.22 on your old server.

Also, I think it does exactly what you specified:

is_editor([listname],[sender]) smime -> do_it

Which translates into bypass the moderation (second instruction in the scenario) when sender is an editor and the message is signed with S/MIME.

Yes I know it’s confusing but I confirm it was working with the same scenario on 6.2.22 tar.gz installation on RedHat 5.8.

The scenario is the default scenario for newsletterkeyonly delivered with sympa.

**Comment by jth56000** [comment]
I suppressed this line and it works correctly but I do not understand why it was working with this line before.



Thanks.



De : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>
Envoyé : lundi 9 décembre 2019 10:59
À : sympa-community/sympa <reply@reply.github.com>; sympa-community/sympa <sympa@noreply.github.com>
Cc : Author <author@noreply.github.com>; DSI Gestionnaire de Listes <listmaster@dsi.cnrs.fr>
Objet : RE: [sympa-community/sympa] No moderation on signed message on 6.2.22 (#819)





Your bug report is a bit confusing, as you state 6.2.22 in subject but in the description it does work with 6.2.22 on your old server.

Also, I think it does exactly what you specified:

is_editor([listname],[sender]) smime -> do_it

Which translates into bypass the moderation (second instruction in the scenario) when sender is an editor and the message is signed with S/MIME.

Yes I know it’s confusing but I confirm it was working with the same scenario on 6.2.22 tar.gz installation on RedHat 5.8.

The scenario is the default scenario for newsletterkeyonly delivered with sympa.

**Comment by racke** [comment]
It looks like the bug was actually in version 6.2.22.
