### ISSUE TITLE
Sympa and Docker

### ISSUE THREAD

**Issue by joergklein** [sympa-community/sympa#824]
I will run sympa with Docker. During the compile process I got the following errors.
Here is the GitLab Repo: https://gitlab.com/joklein/sympa

Please look for this lines

> make[2]: Entering directory '/usr/src/sympa-6.2.49b.2/src/lib'
>   GEN      Sympa/Internals.pod
> Sympa::DataSource::file is deffer from Sympa::DataSource::File

rm -f ar.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ar.gmo ar.po
ar.po:6: warning: header field 'Project-Id-Version' still has the initial default value
ar.po: 369 translated messages, 708 fuzzy translations, 1751 untranslated messages.
rm -f br.gmo && /usr/bin/msgfmt -c --statistics --verbose -o br.gmo br.po
br.po:6: warning: header field 'Project-Id-Version' still has the initial default value
br.po: 11 translated messages, 152 fuzzy translations, 2665 untranslated messages.
rm -f bg.gmo && /usr/bin/msgfmt -c --statistics --verbose -o bg.gmo bg.po
bg.po: 16 translated messages, 280 fuzzy translations, 2532 untranslated messages.
rm -f ca.gmo && /usr/bin/msgfmt -c --statistics --verbose -o ca.gmo ca.po
ca.po: 2294 translated messages, 316 fuzzy translations, 218 untranslated messages.
rm -f cs.gmo && /usr/bin/msgfmt -c --statistics --verbose -o cs.gmo cs.po
cs.po: 554 translated messages, 1237 fuzzy translations, 1037 untranslated messages.
rm -f de.gmo && /usr/bin/msgfmt -c --statistics --verbose -o de.gmo de.po
de.po: 2828 translated messages.
rm -f el.gmo && /usr/bin/msgfmt -c --statistics --verbose -o el.gmo el.po
el.po: 1655 translated messages, 717 fuzzy translations, 456 untranslated messages.
rm -f en_US.gmo && /usr/bin/msgfmt -c --statistics --verbose -o en_US.gmo en_US.po
en_US.po:7: warning: header field 'Project-Id-Version' still has the initial default value
en_US.po: 1708 translated messages, 634 fuzzy translations, 486 untranslated messages.

and many lines more

> ! Installing the dependencies failed: Module 'MHonArc::UTF8' is not installed
> ! Bailing out the installation for ..
> 105 distributions installed
> The command '/bin/sh -c cpanm -L /home/sympa/ --installdeps --notest .' returned a non-zero code: 1

Please try to run this Dockerfile to see all this errors.

Here my Dockerfile

```
FROM centos:latest

LABEL maintainer="" \
      description="Docker base image for Sympa, a mailing list server"

RUN dnf update -y  \
    && dnf group install -y "Development Tools" \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Set locale
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# Download the source file
ENV SYMPA_VERSION 6.2.49b.2
ENV SYMPA_BINARY ${SYMPA_VERSION}.tar.gz

RUN curl -LJO https://github.com/sympa-community/sympa/archive/${SYMPA_BINARY} \
    && tar xzf sympa-${SYMPA_BINARY} -C /usr/src/ \
    && rm sympa-${SYMPA_BINARY}

RUN groupadd sympa \
    && useradd -g sympa -c 'Sympa' -s /sbin/nologin sympa

WORKDIR /usr/src/sympa-${SYMPA_VERSION}

# Compile Sympa
RUN autoreconf -i \
    && automake --add-missing \
    && ./configure --enable-fhs --without-initdir --with-unitsdir=/etc/systemd/system \
    # && ./configure --enable-fhs --without-initdir --with-unitsdir=/etc/systemd/system --prefix=/usr/local --with-confdir=/etc/sympa \
    && make \
    && make install \
    && make clean

# Install Perl modules
RUN dnf install -y epel-release \
    && dnf install -y cpanminus mhonarc \
    && dnf clean all \
    && rm -rf /var/cache/dnf

# Install Sympa
RUN cpanm -L /home/sympa/ --installdeps --notest .


CMD ["/bin/bash"]
```

**Comment by ikedas** [comment]
Hi @joergklein , though I haven't confirmed, this may solve the problem:

``` code
RUN cpanm -L /home/sympa --notest --configure-args='PREFIX=/home/sympa' MHonArc::UTF8
RUN cpanm -L /home/sympa/ --installdeps --notest .
```

**Comment by joergklein** [comment]
I put this lines into the Dockerfile, but the error is the same.

```
# Install Sympa
RUN cpanm -L /home/sympa --notest --configure-args='PREFIX=/home/sympa' MHonArc::UTF8
RUN cpanm -L /home/sympa/ --installdeps --notest .
```
Here the error message again.

```
! Installing the dependencies failed: Module 'MHonArc::UTF8' is not installed
! Bailing out the installation for ..

```

**Comment by racke** [comment]
Doesn't work for me either. This module doesn't have a version, that might be causing the problem.

**Comment by ikedas** [comment]
@joergklein, could you please show all messages related to error, instead of an excerpt at the end?

**Comment by racke** [comment]
@ikedas, basically it is installing a lot of modules and at the end complains about the missing module.
```

Building Test-Compile-v2.3.1 ... OK
Successfully installed Test-Compile-v2.3.1
! Installing the dependencies failed: Module 'MHonArc::UTF8' is not installed
! Bailing out the installation for ..
105 distributions installed

```

**Comment by ikedas** [comment]
Before that it says such as
``` code
! Installing MHonArc::UTF8 failed. See /home/myname/.cpanm/work/1576572780.28730/build.log for details. Retry with --force to force install it.
```
I asked for the content of `build.log`.

**Comment by ikedas** [comment]
Does this work?
``` code
RUN cpanm -L /home/sympa --notest --configure-args='PREFIX=/home/sympa LIB=/home/sympa/lib/perl5' MHonArc::UTF8
RUN cpanm -L /home/sympa/ --installdeps --notest .
```

**Comment by joergklein** [comment]
It works. Thank you for the hlep.
