### ISSUE TITLE
new owners or moderators not taken inot account by the scenario

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#83]
When a list is configured to accept mail from owners or editors, adding new owners or new editors needs a restart of Sympa for the mail to be accepted when sending by these new ones.

Somebody says that's normal because the scenari are in a cache but we can't restart Sympa at each mdofication of the owners or editors

**Comment by racke** [comment]
What is your Sympa version?

**Comment by pascalmaes** [comment]
The last one : 6.2.22

**Comment by racke** [comment]
Which scenario do you use? Just need sufficient information to reproduce your problem.

**Comment by pascalmaes** [comment]
/var/sympa/etc/scenari/send.owneroreditorkey

title.us Owners and editors only
title.fr limité aux propriétaires et modérateurs

is_owner([listname],[sender])      smtp,smime,md5    -> do_it
is_editor([listname],[sender])     smtp,smime,md5    -> do_it
is_subscriber([listname],[sender]) smtp,smime,md5    -> reject
match([sender],/\.ucl\.ac\.be/)    smtp,smime,md5    -> reject
true()                             smtp,smime,md5    -> reject,quiet

**Comment by pascalmaes** [comment]
Hereafter a description of the problem posted on sympa-fr@listes.renater.fr

Bonjour,


Je coince toujours sur ce problème : lorsque nous ajoutons des propriétaires ou des modérateurs, ceux-ci ne sont pas pris en compte à moins d'un redémarrage des processus sympa.


J'ai ajouté une impression dans les journaux de bord.


la liste test-mp-srv2 n'accepte la diffusion des messages que des proprio et modérateurs


1) l'envoi est refusé à juste titre car pascal.maes@gmail.com n'est pas dans les owners

Oct  6 14:28:32 sympa-2.sipr.ucl.ac.be sympa_msg[27496]: notice Sympa::Spindle::AuthorizeMessage::_twist() SENDER = pascal.maes@gmail.com , action = reject,quiet , auth_method = smtp

Oct  6 14:28:32 sympa-2.sipr.ucl.ac.be sympa_msg[27496]: notice Sympa::Spindle::AuthorizeMessage::_twist() Message Sympa::Message <test-mp-srv2@listes.uclouvain.be.1507292908.27682> for Sympa::List <test-mp-srv2@listes.uclouvain.be> from pascal.maes@gmail.com rejected() because sender not allowed


2) pascal.maes@gmail.com est ajouté comme propriétaire de la liste

Oct  6 14:29:12 sympa-2.sipr.ucl.ac.be wwsympa[27737]: notice Sympa::Spindle::ProcessTemplate::_twist() Processing Sympa::Message::Template <test-mp-srv2@listes.uclouvain.be.1507292952.27737,4885>; envelope_sender=test-mp-srv2-owner@listes.uclouvain.be; message_id=sympa.1507292952.27737.992@listes.uclouvain.be; recipients=pascal.maes@gmail.com; sender=sympa2@listes.uclouvain.be; template=user_notification; type=added_as_listadmin


3) Ses messages sont toujours refusés


Oct  6 14:30:24 sympa-2.sipr.ucl.ac.be sympa_msg[27496]: notice Sympa::Spindle::AuthorizeMessage::_twist() SENDER = pascal.maes@gmail.com , action = reject,quiet , auth_method = smtp

Oct  6 14:30:24 sympa-2.sipr.ucl.ac.be sympa_msg[27496]: notice Sympa::Spindle::AuthorizeMessage::_twist() Message Sympa::Message <test-mp-srv2@listes.uclouvain.be.1507293020.27923> for Sympa::List <test-mp-srv2@listes.uclouvain.be> from pascal.maes@gmail.com rejected() because sender not allowed

**Comment by ikedas** [comment]
I think this bug is a duplicate of issue #11.

**Comment by racke** [comment]
So in #11 we include the owners from another list ... which is only synced periodically and not when the members of the included list changes. Is that the case here as well, @pascalmaes? BTW thanks for providing us with a detailed report.

**Comment by pascalmaes** [comment]
No, it's not the case.
The new owner has been added with the web interface (at 14:29:12) without any error and the admin_table has been well updated 

`list_admin               user_admin                            robot_admin                    role_admin date_admin..`
`test-mp-srv2 	pascal.maes@gmail.com 	listes.uclouvain.be 	owner 	2017-10-06 14:29:12`

**Comment by ikedas** [comment]
Ok, remove `duplicate` label and investigate further.

**Comment by ikedas** [comment]
I misunderstood. It seems a duplicate of #7.

**Comment by pascalmaes** [comment]
Yes, it is is.
Could we apply the patches ?

Why theses patches have not been applied in the following versions ?

**Comment by ikedas** [comment]
The last patch seems not able to solve the problem.

Anyway, we would be better to continue on #7.

**Comment by pascalmaes** [comment]
Same as #7
