### ISSUE TITLE
scenario : error-performing-condition

### ISSUE THREAD

**Issue by pascalmaes** [sympa-community/sympa#831]
Whithin the web interface, when I go to a list, I get the following message:

Dec 22 15:21:23 sympa-test.sipr.ucl.ac.be wwsympa[19759]: info Sympa::Scenario::authz() Error in scenario Sympa::Scenario <send.editorkeyonly;/var/sympa/default/scenari/send.editorkeyonly>, context Sympa::List <etd-uclouvain-2019@listes.uclouvain.be>: (error-performing-condition)

In sympa.err, I have:

Dec 22 15:19:40 sympa-test.sipr.ucl.ac.be wwsympa[19406]: err main::#1503 > main::check_param_in#2591 > Sympa::Scenario::authz#433 Error in scenario Sympa::Scenario <send.editorkeyonly;/var/sympa/default/scenari/send.editorkeyonly>, context Sympa::List <etd-uclouvain-2019@listes.ucl
ouvain.be>: (unknown)

Version
-------
Sympa 6.2.50

Installation method
-------------------

source package

Expected behavior
-----------------
I don't have the error with the previous version of Sympa (6.2.48)

**Comment by ikedas** [comment]
Hi @pascalmaes, could you please show these things? ---
- entire log during Sympa processed the message;
- content of `/var/sympa/default/scenari/send.editorkeyonly`;
- content of list `config` file.

**Comment by pascalmaes** [comment]
Hello,

You will find 

- the extract of the log file when I change from editorkey to editorkeyonly
- the files send.editorkey and send.editorkeyonly
- the config file (I remove the paragraph about the remote file instructions)
[Change-Send.txt](https://github.com/sympa-community/sympa/files/3995623/Change-Send.txt)
[send.editorkey.txt](https://github.com/sympa-community/sympa/files/3995624/send.editorkey.txt)
[send.editorkeyonly.txt](https://github.com/sympa-community/sympa/files/3995625/send.editorkeyonly.txt)
[config.txt](https://github.com/sympa-community/sympa/files/3995626/config.txt)

**Comment by ikedas** [comment]
@pascalmaes,

Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/cc5abe7feaaf004e5ee0d03eaa7f7faeaf9dd576.patch) and check if the problem will be solved?

**Comment by ikedas** [comment]
My overlooking.   Also please apply [this patch](https://github.com/sympa-community/sympa/commit/4fb71934009b49b28d1a9a99e008e24226a6e553.patch).

**Comment by pascalmaes** [comment]
I have still the following error (see in attachment)
[logfile.txt](https://github.com/sympa-community/sympa/files/3998009/logfile.txt)
[errfile.txt](https://github.com/sympa-community/sympa/files/3998010/errfile.txt)

**Comment by ikedas** [comment]
> I have still the following error (see in attachment)

Did you applied [additional patch](https://github.com/sympa-community/sympa/commit/4fb71934009b49b28d1a9a99e008e24226a6e553.patch)?

**Comment by pascalmaes** [comment]
Yes of course

**Comment by pascalmaes** [comment]
I have also a lot of the same kind of messages (error-performing-condition) with the topics_visibility.
To avoid these messages, I have to suppress all the "is_" condition (is_owner, is_subscriber, is_editor).

Dec 24 18:16:42 sympa-test.sipr.ucl.ac.be wwsympa[5690]: info Sympa::Spool::Listmaster::store() Stacking message about "error_performing_condition" for responsable-listes@uclouvain.be, pascal.maes@live.be (listes.uclouvain.be)
Dec 24 18:16:42 sympa-test.sipr.ucl.ac.be wwsympa[5690]: info Sympa::Scenario::authz() Error in scenario Sympa::Scenario <topics_visibility.intranet;/var/sympa/etc/scenari/topics_visibility.intranet>, context listes.uclouvain.be: (error-performing-condition)

**Comment by ikedas** [comment]
Have you restarted web service? (see also "[Reloading WWSympa](https://sympa-community.github.io/manual/admin/services.html#reloading-wwsympa)").

**Comment by ikedas** [comment]
And, please show us the content of `topics_visibility.intranet`.

**Comment by ikedas** [comment]
@pascalmaes ,

The `topics_visibility` scenario is always executed under "domain" context, i.e. not corresponding to any lists.  Thus that scenario cannot contain `is_subscriber()`, `is_owner()` nor `is_editor()` which take `[listname]` argument (IMHO this scenario may contain `is_listmaster()`).

**Comment by pascalmaes** [comment]
Hello

Sympa and apache have been both restarted.
I have changed the topics_visibility scenario and I have no more error about that.

You will find the log with some more information
[logfile.txt](https://github.com/sympa-community/sympa/files/3999896/logfile.txt)

**Comment by pascalmaes** [comment]
It seems that the error occurs only with the send scenario.
I have no error with info, review, unsubscribe, etc.
but with the send (I have changed to send.private):

Dec 25 20:22:43 sympa-test.sipr.ucl.ac.be wwsympa[15280]: info Sympa::Scenario::authz(Sympa::Scenario <send.private;/var/sympa/default/scenari/send.private>, md5, HASH, ...)
Dec 25 20:22:43 sympa-test.sipr.ucl.ac.be wwsympa[15280]: info Sympa::Scenario::authz() Error in scenario Sympa::Scenario <send.private;/var/sympa/default/scenari/send.private>, context Sympa::List <etd-uclouvain-2019@listes.uclouvain.be>: (error-performing-condition)

**Comment by ikedas** [comment]
@pascalmaes , thanks for cheking the other scenarios!

I think the expressions including "`[message]`" caused the problem.  We will release a patch release of Sympa (6.2.52) in a few days.

Thanks again for reporting and investigating bugs!
