### ISSUE TITLE
SSO Connexion configuration on sympa 6.2.48

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#834]
Hello,

I'm trying to configure a new server running sympa 6.2.48.

On this server I would like to configure SSO connexion on Renater federation but I don't know how it works.

I got 2 buttons for login "connexion" and "local connexion".
The "local connexion" works.

On the otherone I have the following message 👍 
 ERREUR INTERNE (sso_login) - Votre serveur d'authentification ne nous a pas transmis votre adresse email. 

In the Log I have 👍 

Dec 23 14:32:36 tcgisympa2 wwsympa[105932]: err main::#1544 > main::do_sso_login#3622 [robot listes-int.dsi.cnrs.fr] [session 03304764907617] [client 10.238.30.3] User could not be identified, no HTTP_MAIL HTTP header set

Could anabody help me to configure SSO connexion on renater federation please ?

Thank you.
Jean

**Comment by jth56000** [comment]
Any Idia ?
In my auth.conf I have 

## Here is the default auth.conf
## It defines the authentication backends used by Sympa

generic_sso
        service_name       Connexionaaaaaa
        service_id         federation_renater
        http_header_list   mail
        email_http_header  HTTP_MAIL
        logout_url         https://listes-int.dsi.cnrs.fr/wws/sso_login/federation_renater/Shibboleth.sso/Logout?return=https%3A%2F%2Flistes-int.dsi.cnrs.fr/


user_table
        regexp                 .*

I know I have to define the following var 
var wayf_URL = "https://discovery.renater.fr/renater/WAYF";
var wayf_sp_entityID = "https://listes-int.dsi.cnrs.fr/sp";
var wayf_sp_handlerURL = "https://listes-int.dsi.cnrs.fr/wws/sso_login/federation_renater/Shibboleth.sso";
var wayf_return_url = "https://listes-int.dsi.cnrs.fr/wws/sso_login/federation_renater";
var wayf_width  = 230;
var wayf_font_size = 9;

But where ?

Jean

**Comment by racke** [comment]
@dverdin Do you mind to help out here?

**Comment by ikedas** [comment]
Hi @jth56000 ,
  - For configuration of Sympa, please see [the instruction](https://sympa-community.github.io/manual/customize/shibboleth.html) in the manual.
      - You may use any names for `service_name` and `server_id`.
      - Please contact administrator of SP about appropriate values of ` http_header_list` and `email_http_header`.
      - `logout_url` may or may not be supported by the federation.  Please ask administrator of SP and fedrration.

  - For configuration of SP, please contact with help desk of federation. URLs and entity ID of WAYF will be used in configuratiuon of the SP.

**Comment by ikedas** [comment]
There seem no more questions.  Close
