### ISSUE TITLE
How to disable VERP?

### ISSUE THREAD

**Issue by laerm** [sympa-community/sympa#837]
Hello everyone,

I'm looking to disable VERP in Sympa 6.2.48, which rewrites the return address as follows:

Return-Path: <bounce+user==a==userdomain==listname@listdomain>

We are experiencing issues with our antispam gateway as it does not recognise the rewritten address, rejecting it. The gateway uses it's own bounce tagging.

I've tried setting the following in sympa.conf:

```
verp_rate 0%
tracking_delivery_status_notification off
tracking_message_disposition_notification off
```
but continue to see rewritten addresses. How should I go about turning VERP off completely?

Thank you for your input!

Sympa v. 6.2.48 installed via sympa-ja.org repo
RHEL 7.7

Best regards,

 Chris

**Comment by racke** [comment]
Which Sympa version are you using?

**Comment by laerm** [comment]
> Which Sympa version are you using?

Sorry, just edited my question. I'm on 6.2.48

**Comment by dverdin** [comment]
VERP is not bounce tagging. It is a mean to recognize the original receipient in the case of forwarded addresses.
Can't you declare the "bounce" local address in you antispam gateway? Anything after the "+" is supposed to be ignored for concerns of addresses resolution.

As for Sympa, it will automatically use VERP on adresses that have produced errors already. Is it the case for you?

Regards,

David

**Comment by laerm** [comment]
Hello David,

Thanks for your reply.

Yes, sorry, I confused the two mechanisms, not the same thing.

Still getting to grips with the new gateway. Able to now reroute all "bounce+" style emails to Sympa though I'm seeing loops from time to time. Will investigate further and come back in case I need more info.

It seems quite random. Possibly addresses that at some point were in error but aren't any more.

**Comment by dverdin** [comment]
Very good for the "bounce+" addresses! That will certainly clear a lot of things.

If you have more loops troubles, it might be an alias problem somewhere.
Have a look at your alias / maps files. Anything bounce-related is supposed to be piped into the bouncequeue Sympa program. Check the mail server configuration settings here: https://sympa-community.github.io/manual/install/configure-mail-server.html

Cheers!

David

**Comment by ikedas** [comment]
No updates.  Close by now.
