### ISSUE TITLE
Subscribers included from ldap 2 level query datasource dropped when refreshed from task manager

### ISSUE THREAD

**Issue by xavierba** [sympa-community/sympa#839]
Version
-------
6.2.48

Installation method
-------------------
rpm

Expected behavior
-----------------
Subscribers included from an LDAP 2 level query datasource are properly kept in the members lists. 

Actual behavior
---------------
Subscribers included from an LDAP 2 level query datasource are dropped from the members list when the refresh happens from the task manager.
They are added back when manually synchronizing with the datasource (either through Web UI or command line).

Additional information
----------------------
This is happening only witth include_ldap_2level_query.
include_ldap_query behaves properly.

**Comment by ikedas** [comment]
Hi @xavierba ,

Please show us:
- Configuration of the list (config, *.inc, ...)
- Steps to reproduce the ptoblem you occurred
- Entire log during the operation above.

**Comment by xavierba** [comment]
Hi @ikedas,

There are no particular steps to reproduce. Just setup a list with either a one level or 2 level LDAP include and wait for it to be wiped from LDAP datasource users.

According to the timestamp in member.include, the include refresh seems to be triggered by the task_manager. Manually running the include from the web UI or cli puts back the members in the list.
 
member.include content:
```
eb047bf6 1578639438
```

Here are some slightly tweaked logs to hide private details:
 - task_manager run:
```
Jan 10 06:57:18 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1578639435;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 10 06:57:18 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 10 06:57:18 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 0 included, 0 deleted, 0 updated, 0 kept 
Jan 10 06:57:18 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 0 included, 0 deleted, 0 updated
Jan 10 06:57:18 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::do_next() line 5 of sync_include: next(1578643038, INIT)
Jan 10 06:57:18 sympa-srv task_manager[1440]: notice Sympa::Spool::store() Sympa::Task <date=1578643038;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is stored into Sympa::Spool::Task as <1578643038.INIT.sync_include.some_list@lists.domain.tld>
Jan 10 06:57:18 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::do_next() --> new task Sympa::Task <date=1578643038;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 10 06:57:18 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1578639435;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is now useless. Removing it
```
- web UI refresh:
```
Jan 10 07:36:55 sympa-srv wwsympa[16600]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 10 07:36:55 sympa-srv wwsympa[16600]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 19 included, 0 deleted, 0 updated, 0 kept 
Jan 10 07:36:55 sympa-srv wwsympa[16600]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 19 included, 0 deleted, 0 updated
```

- cli refresh:
```
Jan 10 07:40:24 sympa-srv sympa[23176]: info main::_load() Configuration file read, default log level 0
Jan 10 07:40:25 sympa-srv sympa[23176]: notice main:: Sympa 6.2.48 Started
Jan 10 07:40:25 sympa-srv sympa[23176]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 10 07:40:25 sympa-srv sympa[23176]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 0 included, 0 deleted, 19 updated, 0 kept 
Jan 10 07:40:25 sympa-srv sympa[23176]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 0 included, 0 deleted, 19 updated
```

This seems to suggest the sync_include for include_ldap_2level_query is not doing the right thing when triggered from the task_manager. A test list using  include_ldap_query is affected as well. 

Also, I have other lists using include_sympa_list, which are working properly. No other type of include in use here (remote sympa, sql, ...).  

To narrow the bug hunt, I guess this is a regression introduced between 6.2.44, which was running properly afaik, and 6.2.48, which is what I am running currently.

Regards,
Xavier

**Comment by ikedas** [comment]
Thanks for presenting the steps to reproduce and logs.  Could you please show the configuration? Sensitive information may be masked.

**Comment by xavierba** [comment]
here's the include conf for 2 level:
```
include_ldap_2level_query
select2 all
scope2 sub
suffix2 ou=people,dc=domain,dc=tld
suffix1 ou=group,dc=domain,dc=tld
attrs1 memberUid
select1 all
filter2 uid=[attrs1]
timeout1 30
ca_verify required
ssl_ciphers ALL
attrs2 mail,cn
name ldap
scope1 sub
host ldap.domain.tld
filter1 cn=some_filter
ssl_version tlsv1
timeout2 30
use_tls starttls
```
Here's the include conf for 1 level:
```
include_ldap_query
attrs mail
ca_verify required
ssl_ciphers ALL
filter some_filter
name ldap
host ldap.domain.tld
timeout 30
suffix ou=people,dc=domain,dc=tld
ssl_version tlsv1
use_tls starttls
select first
scope sub
```

**Comment by xavierba** [comment]
Btw, I've tried to tweak the ```ttl``` parameter from the default 3600 to 60 in order to trigger the task_manager refresh more frequently to ease debug, but it doesn't seems to do anything. Actually, it doesn't even seem to be triggered every hour.

**Comment by xavierba** [comment]
And also, ```include_ldap_2level_query```, which is faulty in 6.2.48, has been patched (#785 and #792).
I may update to 6.2.52, but I don't think there is anything relevant to this bug in either 6.2.50 and 6.2.52, and I'd rather no update on friday.

**Comment by xavierba** [comment]
ok, scratch the part about ```ttl``` not working (but not fully, see below) and also about ```include_ldap_query```.

The 1 level ldap query list was actually closed, so no refresh was happening. I've restored the list and the refresh seems to do the right thing now.
However with a ttl value of 60, the refresh occurs every 120 seconds, so maybe there is something to look at here.

However, the 2 level query list is consistently wiped by the task_manager (also every 2 minutes with a ttl of 60):
```
Jan 10 10:17:29 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1578651389;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 10 10:17:29 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 10 10:17:29 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 0 included, 0 deleted, 0 updated, 0 kept
Jan 10 10:17:29 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 0 included, 19 deleted, 0 updated
Jan 10 10:17:29 sympa-srv task_manager[1440]: notice Sympa::Spool::store() Sympa::Task <date=1578651509;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is stored into Sympa::Spool::Task as <1578651509.INIT.sync_include.some_list@lists.domain.tld>
Jan 10 10:17:29 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::do_next() --> new task Sympa::Task <date=1578651509;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 10 10:17:29 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1578651389;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is now useless. Removing it
```

**Comment by xavierba** [comment]
Minimum ```ttl``` parameter value is capped by ```distribution_ttl``` value, so the 120 seconds sync with a ttl value of 60 is probably correct (although my understanding is the default for ```distribution_ttl`` is 300), but let's forget about that too.

**Comment by ikedas** [comment]
@xavierba,

What is the content of `member.include` just before and just after these operations?
- sync_include task
- web UI refresh
- CLI refresh
- and sync_include task again

And also log entries?

**Comment by xavierba** [comment]
hi @ikedas,

I have provided the corresponding logs after every sync operation here:
https://github.com/sympa-community/sympa/issues/839#issuecomment-572940278
And here another log where the task manager wipes the list from its previous subscribers:
https://github.com/sympa-community/sympa/issues/839#issuecomment-572977332

The content of ```member.include``` doesn't change much. The first field stay the same, only the second is changed.  This 2nd field does change on every sync, whatever the sync method is (task, webUI, cli).

I believe I have provided what you are asking for, unless I'm missing something ?

My understanding of the ```member.include``` content, without diving into the code, is:
- Each line represents a datasource and has 2 fields.
- The 1st field seems to be a list id
  - 2 lists using the same ```include_sympa_list``` will have the same content as first field.
  - In case of an ldap2 datasource (and probably other datasources too), the id is computed from the datasource config.
- The 2nd field is the unix epoch of the start time of the sync.

Regards,
Xavier

**Comment by ikedas** [comment]
The first field is unique ID of a data source. The second is the last time of successful inclusion in Unix time.

I want to know how the field was changing. Please show us the content of member.include before and after each of these operations:
- sync_include task
- web UI refresh
- CLI refresh
- and sync_include task again

And logs during operations above.

**Comment by xavierba** [comment]
--> task manager. At this point, the list doesn't contain the members that should have been included by the LDAP2 query.
```
Jan 17 10:49:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1579258081;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 17 10:49:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 17 10:49:02 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 0 included, 0 deleted, 0 updated, 0 kept
Jan 17 10:49:02 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 0 included, 0 deleted, 0 updated
Jan 17 10:49:02 sympa-srv task_manager[1440]: notice Sympa::Spool::store() Sympa::Task <date=1579258442;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is stored into Sympa::Spool::Task as <1579258442.INIT.sync_include.some_list@lists.domain.tld>
Jan 17 10:49:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::do_next() --> new task Sympa::Task <date=1579258442;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 17 10:49:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1579258081;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is now useless. Removing it
```
```member.include``` : ```eb047bf6  1579258142```

--> Refresh from WUI. Now the list does contain the LDAP2 query members.
```
Jan 17 10:49:56 sympa-srv wwsympa[14434]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 17 10:49:56 sympa-srv wwsympa[14434]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 19 included, 0 deleted, 0 updated, 0 kept
Jan 17 10:49:56 sympa-srv wwsympa[14434]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 19 included, 0 deleted, 0 updated
```
```member.include``` : ```eb047bf6  1579258196```

--> cli refresh. The list still contains the proper members.
```
Jan 17 10:50:48 sympa-srv sympa[19948]: debug2 Sympa::List::new(some_list@lists.domain.tld, , )
Jan 17 10:50:48 sympa-srv sympa[19948]: debug2 Sympa::List::load(Sympa::List <>, some_list, lists.domain.tld, ...)
Jan 17 10:50:48 sympa-srv sympa[19948]: debug2 Sympa::List::sync_include_admin(Sympa::List <some_list@lists.domain.tld>) 
Jan 17 10:50:48 sympa-srv sympa[19948]: debug2 Sympa::List::get_admins(Sympa::List <some_list@lists.domain.tld>, owner,  => )
Jan 17 10:50:48 sympa-srv sympa[19948]: debug2 Sympa::List::sync_include(Sympa::List <some_list@lists.domain.tld>, )
Jan 17 10:50:48 sympa-srv sympa[19948]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 17 10:50:49 sympa-srv sympa[19948]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 0 included, 0 deleted, 19 updated, 0 kept
Jan 17 10:50:49 sympa-srv sympa[19948]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 0 included, 0 deleted, 19 updated
```
```member.include``` : ```eb047bf6  1579258248```


--> task manager. The list is cleared from the LDAP2 query members.
```
Jan 17 10:55:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() Running task Sympa::Task <date=1579258442;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 17 10:55:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>
Jan 17 10:55:02 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::DataSource::LDAP2 <context=some_list@lists.domain.tld;id=eb047bf6;role=member;name=ldap>: 0 included, 0 deleted, 0 updated, 0 kept 
Jan 17 10:55:02 sympa-srv task_manager[1440]: info Sympa::Request::Handler::include::_twist() Sympa::Request <action=include;context=some_list@lists.domain.tld;role=member>: 0 included, 19 deleted, 0 updated
Jan 17 10:55:02 sympa-srv task_manager[1440]: notice Sympa::Spool::store() Sympa::Task <date=1579258802;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is stored into Sympa::Spool::Task as <1579258802.INIT.sync_include.some_list@lists.domain.tld>
Jan 17 10:55:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::do_next() --> new task Sympa::Task <date=1579258802;label=INIT;model=sync_include;context=some_list@lists.domain.tld>
Jan 17 10:55:02 sympa-srv task_manager[1440]: notice Sympa::Spindle::ProcessTask::_execute() The task Sympa::Task <date=1579258442;label=INIT;model=sync_include;context=some_list@lists.domain.tld> is now useless. Removing it
```
```member.include``` : ```eb047bf6  1579258502```

**Comment by xavierba** [comment]
@ikedas, I have updated the title and first comment.
Is there anything else I shall provide to help debug this issue ?
Have you been able to reproduce ?

**Comment by ikedas** [comment]
@xavierba, please set `log_level 2` in `sympa.conf`, restart services and perform [the procedure](https://github.com/sympa-community/sympa/issues/839#issuecomment-574439383) again.

**Comment by xavierba** [comment]
Hi @ikedas,

I have updated from sympa-6.2.48-2.el6.x86_64 to 6.2.52-1.el6_10.x86_64 on last thursday and it seems to no longer be happening.
I have updated from sympa-6.2.52-1.el6_10.x86_64 to 6.2.52-2.el6.x86_64 this morning to make sure all known bugfixes are applied (#842 and #847).
I'll keep watching the log to make sure everything is okay in the next few days and report back.

Regards,
Xavier

**Comment by xavierba** [comment]
I may have an idea on the difference in behavior between task_manager and cli/wui.

The 6.2.48-2 install was hot-patched with e262c7c015eefb89fc5100241698126dd2a8e36c (LDAP 2 level query fix), but sympa service was not restarted. The daemon was thus possibly still running the unpatched LDAP 2 level query code, while the datasource sync from the wui or cli was running the patched code. Udating to 6.2.52-1.el6-10 restarted the daemon and fixed the issue. Does that sound like a possible explanation ?
And yeah, I know, if the answer is yes, you can call me stupid, it would be much deserved...

**Comment by ikedas** [comment]
@xavierba , I feel it in sense. Sympa is so dull that it can’t know when it has been updated by itself. :-/

**Comment by xavierba** [comment]
In this case, sympa wouldn't know it had been patched, because I manually applied the patch directly on the server on top of the code deployed by the rpm while testing this very fix.
If I had properly deployed the patch with an updated rpm including it, sympa would have been restarted and I wouldn't have suffered from this self inflicted pain. In short, it's all my own fault and I'm sorry for the time you spent on this...

**Comment by ikedas** [comment]
I couldn't get confirmation on reported behavior.  This issue is closed.

If anyone reproduced the same problem, please submit the new issue.
