### ISSUE TITLE
Does not have remove option in moderator

### ISSUE THREAD

**Issue by psvillanueva2015** [sympa-community/sympa#843]
Does not have a check box in removing for some of the moderator.

Version

 6.2.40
-------

Installation method
-------------------

Installation from source

Expected behavior
-----------------

Should have check box option to remove moderator or editor - I just notice that only editor.dump has that option 

Actual behavior
---------------

Can not remove editor or moderator does not have a check box

Additional information
----------------------

![image](https://user-images.githubusercontent.com/13635380/72782242-3ad74400-3c5e-11ea-9464-eca40a6f2ee1.png)

**Comment by ikedas** [comment]
Hi @psvillanueva2015 ,
By any chance, are any moderators included from the data source? Such moderators cannot be removed with web UI.

**Comment by psvillanueva2015** [comment]
Hi ikedas,

No, They are not part of the data source.

Regards,
Pete

**Comment by ikedas** [comment]
@psvillanueva2015 , could you show us the content of `editor dump`? (private information may be masked).

**Comment by psvillanueva2015** [comment]
Here it is 

[root@lists std-engineering]# more editor.dump
editor
reception mail
email corporatecommunications@example.com
visibility noconceal

editor
reception mail
email richard.burns@example.com
visibility noconceal
gecos Rick Burns

editor
reception mail
email john.griesing@example.com
visibility noconceal

editor
email help_desk@example.com
reception mail
visibility noconceal
gecos help_desk

editor
reception mail
email help.desk@example.com
visibility noconceal
gecos Help Desk

[root@lists std-engineering]#

**Comment by ikedas** [comment]
Sorry I had to ask more clearly. Could you run
``` bash
sympa.pl --dump_users --role=editor --list=std-engineering@dom.ain
```
and then check the content of `editor.dump` of `std-engineering` list?

**Comment by psvillanueva2015** [comment]
I'll try this and let you know.

**Comment by psvillanueva2015** [comment]
After this command sympa.pl --dump_users --role=editor --list=std-engineering@dom.ain

entries in the editors were added in editor.dump but still checkbox is not visible.

**Comment by ikedas** [comment]
How does the content of `editor.dump` changed? Could you please show us?

**Comment by psvillanueva2015** [comment]
Here is the old entry of editor.dump.old

[root@lists std-engineering]# more editor.dump.old
editor
reception mail
email corporatecommunications@example.com
visibility noconceal

editor
reception mail
email richard.burns@example.com
visibility noconceal
gecos Rick Burns

editor
reception mail
email john.griesing@example.com
visibility noconceal

editor
email help_desk@example.com
reception mail
visibility noconceal
gecos help_desk

editor
reception mail
email help.desk@example.com
visibility noconceal
gecos Help Desk


Here is the new entry 

[root@lists std-engineering]# more editor.dump
date 1544322897
email ajay-kumar.yadav@example.com
id e4ce2e02
included 1
reception nomail
subscribed 0
update_date 1580090045
visibility noconceal

date 1544322897
email corporatecommunications@example.com
included 0
profile normal
reception mail
subscribed 1
update_date 1580090045
visibility noconceal

date 1544322897
email david.chapple@example.com
id e4ce2e02
included 1
reception nomail
subscribed 0
update_date 1580090045
visibility noconceal

date 1544322897
email help.desk@example.com
gecos Help Desk
id e4ce2e02
included 1
profile normal
reception mail
subscribed 1
update_date 1580090045
visibility noconceal

date 1545422066
email help_desk@example.com
gecos help_desk
included 0
profile normal
reception mail
subscribed 1
update_date 1580090045
visibility noconceal

date 1544322897
email john.griesing@example.com
included 0
profile normal
reception mail
subscribed 1
update_date 1580090045
visibility noconceal

date 1578923044
email marina.gutin@example.com
gecos Marina Gutin
included 0
profile normal
reception nomail
subscribed 1
update_date 1580090045
visibility noconceal

date 1544322897
email richard.burns@example.com
gecos Rick Burns
included 0
profile normal
reception mail
subscribed 1
update_date 1580090045
visibility noconceal

**Comment by ikedas** [comment]
Users with attribute "included 1" seem included from the data source (e.g. ``help.desk@example.com``) and they may not have checkboxes to delete. Others don't included and they may have checkboxes (e.g. ``help_desk@example.com``).

**Comment by psvillanueva2015** [comment]
Yes, you are correct. This was notice after the upgrade to 6.2.40 - It can only be remove from db level. Since we have a lot of lists already, I let our helpdesk recreate the list and delete the old one. I'm planning to update to latest stable version, do you think this problem still exist in the latest stable release?

**Comment by psvillanueva2015** [comment]
I checked the data_source file for specific lists std-engineering there is a file std-engineering.incl

[root@lists data_sources]# cat std-engineering.incl
include_file /home/sympa/expl/std-engineering/editors

[root@lists data_sources]# cat /home/sympa/expl/std-engineering/editors
david.chapple@example.com
ajay-kumar.yadav@example.com
help.desk@example.com

**Comment by psvillanueva2015** [comment]
So this is the way we remove those moderator that does not have checkbox :)

![image](https://user-images.githubusercontent.com/13635380/73152644-a3656b80-410b-11ea-99f5-f6f454a8bb31.png)

**Comment by psvillanueva2015** [comment]
I tested in our test box its was remove

**Comment by ikedas** [comment]
Please change data sources not to include unnecessary users.  Or, if you deleted unnecessary users from database table, they will be filled from data sources again.

**Comment by psvillanueva2015** [comment]
Thank you ikedas
