### ISSUE TITLE
The translation server is down (nginx problem)

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa#855]
It seems that the nginx frontend of the translation server is having some kind of problem right now:

> nginx error!
> The page you are looking for is temporarily unavailable. Please try again later.
> Website Administrator
> Something has triggered an error on your website. This is the default error page for nginx that is distributed with EPEL. It is located /usr/share/nginx/html/50x.html
> 
> You should customize this error page for your own site or edit the error_page directive in the nginx configuration file /etc/nginx/nginx.conf.

Regards.

**Comment by ikedas** [comment]
Server has been restarted.  Sorry for inconvenience.

**Comment by qosobrin** [comment]
Thank you for your prompt answer, @ikedas. Could you (or anyone) also provide some help with a couple of issues in the Spanish translation site [https://translate.sympa.org/es/](https://translate.sympa.org/es/)? 

- There are two suggestions that I am unable to remove/accept/get rid of.
- There are 45 words pending translation (button with a 45 in blue background) that lead to a empty string in the original language. I have already reported this problem from the translation server twice in the last couple of months.

Thank you very much in advance.
Regards.
