### ISSUE TITLE
Cannot remove owners/editors when their external data source as removed

### ISSUE THREAD

**Issue by aepli** [sympa-community/sympa#858]
Version
-------
Sympa 6.2.48

Installation method
-------------------
From source

Expected behavior
-----------------
When removing an owners/editors external data source, owners/editors from that source should be deleted from the owners/editors of the distribution list. The synchronization task should be deleted from the task folder.

Actual behavior
---------------
After removing an owners/editors external data source, they remain present as the owners/editors of the distribution list and cannot be deleted from the web interface (no checkbox). Currently, they must be removed from 'admin_table' in the database.

Additional information
----------------------
OS: Debian GNU/Linux 9.11 (stretch)
Perl: 5.24.1-3+deb9u5 amd64

**Comment by ikedas** [comment]
Hi @aepli ,

Could you please apply [this patch](https://github.com/ikedas/sympa/commit/5d19b9b.patch) and check if the problem will be solved?  Thanks.

**Comment by aepli** [comment]
Hi @ikedas,

I tested the fix in the issue #857 .  
You will find my comments there.

Regards.
