### ISSUE TITLE
How to use user Gecos in welcome message template

### ISSUE THREAD

**Issue by eurecomphil** [sympa-community/sympa#859]
Dear all,

I would like to add the "gecos" value (The full name of my user) inside my welcome message template.

What I did :  
- I created a new mailing list. 
- I enabled **Allow message personnalization (merge_feature)** in the _sending/receiving setup_ via the web interface.
- In _customizing_ I edited the welcome message and tried these :  
```
[%|loc(user.email)%]Your contact email address is %1[%END%]
[%|loc(user.gecos)%]Your team name is %1[%END%]
[% |loc(user.gecos)%] %1 [%END%]
[%|loc(user.name)%]  %1 [%END%]
[% |loc(user.friendly_date) %] %1 [%END%]
[%|loc(custom_vars.gecos)%] %1 [%END%]
```
When a new user is added, he receives the welcome email where all the variables in the template of these values are empty except the user.email... 
By the way, I of course do have text data in the "Name" column" of my users in "Review members" section.

Any idea guys ?
My SYMPA **version is 6.1.24**

**Comment by racke** [comment]
It works for me in 6.2.52 without merge_feature enabled and the following string in welcome template:

`[%|loc(user.gecos)%]More info: %1[%END%]`

**Comment by ikedas** [comment]
No updates. Close for now.
