### ISSUE TITLE
[editorkey] Quiet for moderator mails

### ISSUE THREAD

**Issue by derOtto** [sympa-community/sympa#861]
Expected Behavior
-----------------

It should be possible to also quiet the moderation mails (editorkey) send to moderators.

Current Behavior
----------------

editorkey,quiet only quiets the mails, send to the sender (which I guess should be the default behavior), but not the mails for informing the moderators.

Possible Solution
-----------------

Either it would be possible to add another "flag" like quiet (quiet2, quietmod, …?), which suppress these mails or seperation to two actions in each scenari (but could cause compatibility problems).

Context
-------

I was trying to implement the following spam handling:
- Mark Mails to no spam, maybe spam and defenetly spam.
- Depending on that, send the mails, store them for moderation without informing anyone (sender and moderators) or reject them.

**Comment by ikedas** [comment]
Notifications for moderators are always sent at least any of list admins in this way:
  1. Moderators who are set "reception" to "mail" (receive notification email).
  2. If none found, all users delegated to moderator.
  3. If none found, all users delegated to owner.

So if some of moderators want to ignore notifications, they may set "reception" option of their (as moderator) to "nomail".

**Comment by derOtto** [comment]
Ok, that solves the issue a little bit. But there's no option to ignore notification based on scenario actions like quiet for the sender at the moment. So reception is either all mails or no mails.
I would say an implementation of this would make sympa more configurationable, as it already is;)

**Comment by ikedas** [comment]
I think there are no ways to make moreration notifications ignored by all list administrators (moderator & owners).

If some of moderation notifications can be ignored by everyone, in the first place, messages should not be moderated.  There are some ways using `send` scenarios, such as:
  a. Restrict posting to subscribers only.  Messages from the others will be rejected.
  b. Request the users confirmation to post messages.

For exapmle,`send.privatekeyandeditorkeyonly` scenario does b., then only messsages that has been confirmed will be held for moderation (and notification will be sent to moderator).

**Comment by ikedas** [comment]
No updates,  Close for now.
