### ISSUE TITLE
unable to active list after 6.2.52

### ISSUE THREAD

**Issue by regis** [sympa-community/sympa#863]
**update 6.2.42 -> 6.2.52**

unable to activate list
no list in https://listes.XXX.fr/sympa/get_pending_lists

sympa.pl --show_pending_lists=XXX.fr
No pending list for robot XXX.fr

**error log :**

Feb  6 14:35:11 listes wwsympa[20821]: err main::#1544 > main::do_create_list#9772 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_list::_twist#272 > Sympa::List::save_config#844 > Sympa::List::_update_list_db#6964 > Sympa::Database::do_prepared_query#382 Unable to execute SQL statement "INSERT INTO list_table (status_list, name_list, robot_list, family_list, creation_epoch_list, creation_email_list, update_epoch_list, update_email_list, searchkey_list, web_archive_list, topics_list) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)": (HY000) Field 'editors_list' doesn't have a default value

Feb  6 14:35:11 listes wwsympa[20821]: err main::#1544 > main::do_create_list#9772 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_list::_twist#272 > Sympa::List::save_config#844 Unable to update list_table

**workaround :**
 
ALTER TABLE list_table ALTER COLUMN editors_list  SET DEFAULT '';
ALTER TABLE list_table ALTER COLUMN owners_list  SET DEFAULT '';
ALTER TABLE list_table ALTER COLUMN path_list  SET DEFAULT '';
ALTER TABLE list_table ALTER COLUMN subject_list  SET DEFAULT '';

**Comment by racke** [comment]
Did you run the sympa --upgrade command after the upgrade?

**Comment by ikedas** [comment]
By any chance did you upgrade MySQL? What are the versions of it before and after upgrade?

**Comment by ikedas** [comment]
No response.  I guess the reported problem is related to sql_mode of MySQL: See also #1028.

No more response.  This issue is closed.
