### ISSUE TITLE
Family list signoff does not work on 6.2.52

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#864]
Version
-------
6.2.52 (sympa-6.2.52-2.el7.x86_64)

Installation method
-------------------
RPM installation method

Expected behavior
-----------------
I have family of lists with datasource.
In my list I have a message footer to unsubscribe family of list such as 👍 
#cat message.footer
Pour ne plus recevoir les messages des Listes Test Jean, cliquez sur ce lien : [% wwsympa_url %]/family_signoff_request/jean-test/[% user.escaped_email %]
When I send a message to the list the users should be able to unsubscribe by clicking on the link.

Actual behavior
---------------
The unsubscription does not work.
When the user click on the link he receive a confirmation mail from sympa with a link to click to confirm unsubscription.
The unsusbscription complete with no errors.
An entry is created in exclusion table but the user still receive mail from the list.

Additional information
----------------------
It was working correctly in 6.2.48.

**Comment by ikedas** [comment]
Hi @jth56000 ,

Is the user included from any data source(s)? family_signoff feature affects only the subscribers included from data sources.

**Comment by jth56000** [comment]
Hi Soji, yes he is included from a data source.

**Comment by ikedas** [comment]
Please try these things —-

  - After successful confirmation of in subscription, wait for a while, say, one or two hours.  During this time  `task_manager.pl` daemon will run `sync_include` task to update subscribers.  Can you confirm this behavior by log file?

  - To confirm that user is included, run
    ```bash
    # sympa.pl --dump_users --role=member --list=listname@dom.ain.tld
    ```
    to dump subscribers information into `member.dump` file in list directory, and show us the paragraph of that user in this file (email and gecos may be masked).

**Comment by jth56000** [comment]
Soji, You were right.

I wait for task_manager to do the sync_include on the list and now users who have signed off do not receive anymore messages from the list.

Thank you for your great help.

 

Jean

 

De : IKEDA Soji <notifications@github.com> 
Envoyé : mardi 11 février 2020 11:22
À : sympa-community/sympa <sympa@noreply.github.com>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sympa-community/sympa] Family list signoff does not work on 6.2.52 (#864)

 

Please try these things —-

*         After successful confirmation of in subscription, wait for a while, say, one or two hours. During this time task_manager.pl daemon will run sync_include task to update subscribers. Can you confirm this behavior by log file?

*         To confirm that user is included, run

# sympa.pl --dump_users --role=member --list=listname@dom.ain.tld <mailto:--list=listname@dom.ain.tld> 

to dump subscribers information into member.dump file in list directory, and show us the paragraph of that user in this file (email and gecos may be masked).

**Comment by ikedas** [comment]
@jth56000, thanks for sharing your experiences! This issue is closed.
