### ISSUE TITLE
additional query when releasing an e-mail for the moderators

### ISSUE THREAD

**Issue by Salo15** [sympa-community/sympa#865]
It would be good if, when releasing an email for a list, the moderators would be asked again whether the email should actually be released.
Alternatively, the buttons for distributing and rejecting an email should be better separated on the website, so that it cannot happen that an email is accidentally released.

Version
-------
6.2.16

Installation method
-------------------
Debian Package

Expected behavior
-----------------
The moderators of mailing lists should not run the risk of accidentally releasing an email.

Actual behavior
---------------
The icon for releasing an email and the icon for rejecting an email are very close to each other.
After clicking on "Reject", a window is opened again with the question whether and which rejection message should be sent.
After clicking on "Distribute" the e-mail is distributed directly to the list.

At our institution, this has already led to e-mails being sent inadvertently to many thousands of students, which should actually be rejected.
Especially for such a large list, an additional query as to whether the e-mail should actually be distributed would be useful.

Additional information
----------------------

**Comment by Salo15** [comment]
Is there a possibility that we ourselves build such a query into our Sympa instance?

Best regards,
Sabine

**Comment by ikedas** [comment]
One idea is customizing web template. For example, add following text at the end of `web_tt2/modindex.tt2`:
``` code
<script>
$(function(){
    $('input[name="action_distribute"]').on('click', function(){
        return window.confirm('Do you really distribute selected messages?');
    });

    $('input[name="action_reject"]').on('click', function(){
        return window.confirm('Do you really reject selected messages?');
    });
});
</script>
```
And clicking the buttons will need confirmation.

(Note that `modindex.tt2` bundled in Sympa should not be edited directly.  See also [the documentation](https://sympa-community.github.io/manual/customize/basics-templates.html#location) to know how to customize templates.)

**Comment by Salo15** [comment]
Thank you very much for this information.
I first helped myself by changing the two templates modform.tt2 and modindex.tt2 so that the icons are now displayed larger and also in a different order, so that the button for releasing a mail and the button for deleting a mail are no longer next to each other.

Your suggestion is great and it's optimal that we can activate the additional query window also in lists.

From my side the window can be closed. I hope that you can follow the hint to the somewhat too small icons for the design of the website in future versions.

Best regards,
Sabine

**Comment by ikedas** [comment]
Closed.  Thanks for inputs!
