### ISSUE TITLE
unable to sort column in subscriber list

### ISSUE THREAD

**Issue by regis** [sympa-community/sympa#866]
after update 6.2.42 -> 6.2.52

in subscribers list 
<img width="787" alt="Screen Shot 2020-02-11 at 12 10 30" src="https://user-images.githubusercontent.com/14838/74231724-857d3680-4cc7-11ea-8f97-80beed82dc15.png">

after clicking on the sources column, the list of subscribers is empty

<img width="1003" alt="Screen Shot 2020-02-11 at 12 11 54" src="https://user-images.githubusercontent.com/14838/74231798-b52c3e80-4cc7-11ea-8aef-1453a0962a94.png">

**Comment by ikedas** [comment]
Hi @regis,

Could you please apply [this patch](https://github.com/sympa-community/sympa/commit/3d3c3cbbc1edbcd48cd6d80af48d8bd919e385f1.patch) and check if the problem will be solved?

**Comment by ikedas** [comment]
The patch was merged.  @regis , thanks for reporting bug!
