### ISSUE TITLE
Password encryption: Dropping Crypt::CipherSaber

### ISSUE THREAD

**Issue by racke** [sympa-community/sympa#87]
The old documentation says:

> Authentication is based on passwords stored in the database table user_table; if the appropriate Crypt::CipherSaber is installed, passwords are encrypted in the database using reversible encryption based on RC4. Otherwise, they are stored in clear text. In both cases, reminding of passwords is possible. 

But when I'm looking at my databases, I see only MD5 encryption. Note: I'm using Debian packages, but they
have a dependency on Crypt::CipherSaber.

**Comment by ikedas** [comment]
According to OChangelog, MD5 password hash was introduced on Sympa 6.0 (https://github.com/sympa-community/sympa/commit/311cae8c3de32c04515d3c16dffa408dae048e33), and RC4 password encription was deprecated on Sympa 6.2 (https://github.com/sympa-community/sympa/commit/a16fd3e5c65e7b01259284c6225e762a34701df4).

Currently, RC4 is used only for encryption/decription of HTTP session cookie.

**Comment by ikedas** [comment]
- After all, Crypt::CipherSaber is no longer used to encrypt passwords.
- And I doubt if encryption of cookie values will make HTTP session more secure: Each randomized value can be reusable in the period of ``cookie_refresh``.

So I suppose Crypt::CipherSaber would be better to be removed. If there is no objection, I'll submit a PR.

**Comment by ikedas** [comment]
6.2.26 introduced bcrypt password hash, then MD5 hash may be obsoleted: See also PR #225, #238.

On the other hand, password encrypted by RC4 is still supported.  Thus I propose:

  1. Deprecation of RC4:
       - Password storage encrypted by RC4 would be deprecated.
       - These may be decrypted and hashed during upgrading process.
  2. As well, encryption of session ID in HTTP cookie: It hardly enhances security.
  3. Finally, dropping a dependency module Crypt::Ciphersaber.

**Comment by ikedas** [comment]
PR above will drop Crypt::CipherSaber.
