### ISSUE TITLE
Death of the wwsympa process bug

### ISSUE THREAD

**Issue by bruncsak** [sympa-community/sympa#876]
Version
-------
sympa-6.2.52-2.el7.x86_64

Installation method
-------------------
via yum on CentOS 7 from the epel repository

I got regularly the following error message:
````
wwsympa[1234]: err main::#1544 > main::do_help#3868 > Sympa::get_url#756 DIED: Can't locate object method "host_port" via package "URI::_generic" at /usr/share/sympa/lib/Sympa.pm line 756.
````
I have in the apache error log the following in addition too:
````
[<date>] [fcgid:warn] [pid num1] [client 1.2.3.4:5678] mod_fcgid: stderr: Use of uninitialized value in string eq at /usr/share/sympa/lib/Sympa.pm line 753.
[<date>] [fcgid:warn] [pid num2] mod_fcgid: cleanup zombie process 1234
````

**Comment by ikedas** [comment]
Hi @bruncsak ,
- Could you please apply [this patch](https://github.com/sympa-community/sympa/pull/878.patch) and check if the problem will be solved?
- What is the value of `wwsympa_url` parameter in your `sympa.conf` (or `robot.conf`)?

**Comment by bruncsak** [comment]
I applied the patch, we will see is the problem still there, or not any more, thanks.

Concerning wwsympa_url:
There is no such entry in /etc/sympa/sympa.conf, I am using exclusively robot.
In the robot.conf the format of the wwsympa_url entry is simmilar to:
`wwsympa_url http://www.example.com/aa/bb`
The `www.example.com` hostname in the URL is not the hostname where the sympa itself is running, there is a reverse-proxy in front of the sympa host.

I am using non-standard configuration relative to the rpm package from the EPEL repo, due to the double components of the wwsympa_url local path. I use mod_fcgid instead of mod_proxy_fcgi. For additional detail please visit:
https://bugzilla.redhat.com/show_bug.cgi?id=1770783

**Comment by bruncsak** [comment]
There is one more information. I just realized that the configuration is incorrect on our side. The reverse proxy actually unloads the SSL tunnel, so the correct value for wwsympa_url should have been:
`wwsympa_url https://www.example.com/aa/bb`
instead of `http` schema.
Is it correct to write:
`wwsympa_url //www.example.com/aa/bb`, with other term not specifying the URL schema?

**Comment by ikedas** [comment]
@bruncsak , please submit new report for another issue. As I submitted #879, please post additional comment if any.

**Comment by ikedas** [comment]
> I applied the patch, we will see is the problem still there, or not any more, thanks.

Thanks!

> Concerning wwsympa_url:
> There is no such entry in /etc/sympa/sympa.conf, I am using exclusively robot.
> In the robot.conf the format of the wwsympa_url entry is simmilar to:
> `wwsympa_url http://www.example.com/aa/bb`

If possible, please show us the access log of httpd, including path and host name of accessed URI, from when the browser accessed help page to when wwsympa crashes.

> The `www.example.com` hostname in the URL is not the hostname where the sympa itself is running, there is a reverse-proxy in front of the sympa host.

With such situation you may have to add the "real" URL to Sympa configuration.
``` code
               +-------------+        +--------------+
browser ------ |reverse proxy| ------ | Sympa server |
               +-------------+        +--------------+
           ^                       ^
           |                       |
https://www.example.com/aa/bb     http://internal.host/sympa
```
In this figure, user recognizes Sympa service as `https://www.example.com/aa/bb`, while httpd of Sympa server recognizes itself as `http://internal.host/sympa`.   In this situation the latter URL and its host have to be added as below:
``` code
wwsympa_url https://www.example.com/aa/bb
http_host http://internal.host/sympa
cookie_domain internal.host
```

**Comment by bruncsak** [comment]
> If possible, please show us the access log of httpd, including path and host name of accessed URI, from when the browser accessed help page to when wwsympa crashes.

Unfortunately the combined apache log is not enabled (that is the default on CentOS). What I have in the access log is the following: `"GET /aa/bb/help HTTP/1.1"` at the precise moment wwsympa fails.
But I know from my colleague who is responsible for the enterprise reverse proxy configuration, that there is no URL rewriting for this reverse proxy rule. So the `Host:` HTTP header field must have been `www.example.com` and not the hostname of the sympa backend.

**Comment by ikedas** [comment]
I understand.  Then, are you sure that the reverse proxy passes `Host:` request header field to the Sympa server? If it doesn't, and `sympa.conf` doesn't contain proper `wwsympa_url` parameter, Sympa won't work correctly.

**Comment by bruncsak** [comment]
Our sympa installation in general works correctly with the outside URL, no big issue just some small ones like this.
I just did `tcpdump -n -s0 -X port 80` it is faster than anything else. I can confirm that the `Host:` header field is `www.example.com` and not the hostname of the sympa backend.

Concerning your recommended configuration:
`http_host http://internal.host/sympa`
According to https://sympa-community.github.io/manual/install/configure-http-server.html 
> On recent releases, this parameter is not necessary. http_host parameter may be obsoleted in the future.

So I avoid using the `http_host` variable. Which way should I go? By your recommendation or by the official documentation, they are slightly contradicting.

**Comment by ikedas** [comment]
Then, could you please check if the reverse proxy _always_ passes `Host:` field to the Sympa server?

**Comment by bruncsak** [comment]
That is really tricky to answer. At least all access I see has `HTTP/1.1` and no `HTTP/1.0` (except: `::1 - - [<date>] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 (internal dummy connection)"`)
I believe that our reverse proxy does no break the HTTP 1.1 protocol, so there must always `Host:` HTTP header field present.

**Comment by ikedas** [comment]
Anyways could you please add `wwsympa_url https://www.example.com/aa/bb` to `sympa.conf`?  If the reverse proxy doesn't pass `Host:` field, or if it passes unexpected host name,  and if `sympa.conf` doesn't contain proper `wwsympa_url` parameter, Sympa won't work correctly.

**Comment by bruncsak** [comment]
In fact, I have two robots, with different wwsympa_url parameters. I will put a third version of `wwsympa_url https://www.example.com/sympa` into the main, not in use sympa.conf file.

**Comment by ikedas** [comment]
OK.  Please let us know the result.

----
BTW, If you run two or more domains, it would be better to choose one as the default and to include its mail domain and URL in `sympa.conf`.  Such as:

`sympa.conf`:
```code
domain mail1.example.com
wwsympa_url https://web1.example.com/xxx
...
```
`mail1.example.com/robot.conf`:
```code
wwsympa_url https://web1.example.com/xxx
...
```
`mail2.example.com/robot.conf`:
```code
wwsympa_url https://web2.example.com/yyy
...
```

**Comment by bruncsak** [comment]
Could web1 equal to web2, or is it invalidating your proposed configuration?

**Comment by ikedas** [comment]
mail1 (web1) and mail2 (web2) are different each other.  sympa.conf and _one of_ robot settings share mail1 web1).

**Comment by ikedas** [comment]
@bruncsak , does the bug reproduce? If it does, please show us following things:
  - Configuration of Sympa: The `sympa.conf` and all `robot.conf`. For the time being `domain`, `wwsympa_url`, `http_host` and `cookie_domain` parameters are needed.
  - Configuration of HTTP server.
  - Log of HTTP server and Sympa, from when you sent the initial request to when wwsympa.fcgi dies.

Thanks.

**Comment by bruncsak** [comment]
Yes, I am able to reproduce the problem. I already set-up a test installation, but its configuration is still complex much out of a vanilla baseline. For example, it still has a reverse-proxy in front (I started the work out from the production).
What I can already tell is the following:

- No `http_host`, neither `cookie_domain` configured in `/etc/sympa/sympa.conf` or in any of the robot.conf files, all are defaulting.
- There is no `wwsympa_url` in the main `/etc/sympa/sympa.conf`file. If I add the parameter (even with any arbitrary value) the problem goes away. The lack of this parameter seemingly is a must to reproduce the problem.
- I am using mod_fcgid and not mod_proxy_fcgi. I do not know is there any significance of this.

**Comment by ikedas** [comment]
Could you please show us also these things?
  - Configuration of HTTP server.
  - Log of HTTP server and Sympa, from when you sent the initial request to when wwsympa.fcgi dies.

**Comment by bruncsak** [comment]
On each program output, configuration file, log file I made the following transformations:
- removing comments
- removing empty lines
- regular replacement of strings for privacy
````
curl --silent --show-error 'https://www.example.com/aa/cc/help'
<!DOCTYPE html>
<html class="no-js" lang="en-US" xml:lang="en-US">
    <!-- crash.tt2 -->
    <head>
        <meta charset="UTF-8" />
        <meta name="generator" content="Sympa 6.2.52" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Mailing lists service - crash </title>
        <!-- head_ui.tt2 -->
<link rel="stylesheet" href="/aa/static_content/js/jquery-ui/jquery-ui.css?v1.12.1" />
<link rel="stylesheet" href="/aa/static_content/js/jqplot/jquery.jqplot.css?v1.0.8" />
<link rel="stylesheet" href="/aa/static_content/js/jquery-minicolors/jquery.minicolors.css?v2.3.1">
<link rel="stylesheet" href="/aa/static_content/fonts/font-awesome/css/font-awesome.css?v4.3.0" />
<link rel="stylesheet" href="/aa/static_content/fonts/foundation-icons/foundation-icons.css?v3.0" />
<link rel="stylesheet" href="/aa/static_content/js/foundation/css/foundation-float.css?v6.4.2" />
<style>
  select[multiple], select[size] { height: auto; background-image: none; }
</style>
<link rel="stylesheet" href="/aa/static_content/css/web2.example.com/style.css?h=657ce934fd5bbd1c84ac720f50f4d8ef" title="Sympa CSS" />
<link rel="shortcut icon" href="/aa/static_content/icons/favicon_sympa.png" />
<!-- end head_ui.tt2 -->
        <!-- head_javascript.tt2 -->
<script>
<!--
var sympa = {
    backText:           'Back',
    calendarButtonText: 'Calendar',
    calendarFirstDay:   0,
    closeText:          'Close',
    dayNames:           'Sunday:Monday:Tuesday:Wednesday:Thursday:Friday:Saturday'.split(":"),
    dayNamesMin:        'Su:Mo:Tu:We:Th:Fr:Sa'.split(":"),
    home_url:           '/aa/cc/',
    icons_url:          '/aa/static_content/icons',
    lang:               'en-US',
    loadingText:        'Please Wait...',
    monthNamesShort:    'Jan:Feb:Mar:Apr:May:Jun:Jul:Aug:Sep:Oct:Nov:Dec'.split(":"),
    openInNewWinText:   'Open in a new window',
    resetText:          'Reset'
};
var lang = 'en-US';
//-->
</script>
<script src="/aa/static_content/js/jquery.js?v3.2.1"></script>
<script src="/aa/static_content/js/jquery-migrate.js?v1.4.1"></script>
<script src="/aa/static_content/js/jquery-ui/jquery-ui.js?v1.12.1"></script>
<script src="/aa/static_content/js/jqplot/jquery.jqplot.min.js?v1.0.8"></script>
<script src="/aa/static_content/js/jqplot/jqplot.categoryAxisRenderer.min.js?v1.0.8"></script>
<script src="/aa/static_content/js/jqplot/jqplot.barRenderer.min.js?v1.0.8"></script>
<script src="/aa/static_content/js/jqplot/jqplot.canvasAxisTickRenderer.min.js?v1.0.8"></script>
<script src="/aa/static_content/js/jqplot/jqplot.canvasTextRenderer.min.js?v1.0.8"></script>
<script src="/aa/static_content/js/jquery-minicolors/jquery.minicolors.min.js?v2.3.1"></script>
<script src="/aa/static_content/js/sympa.js?v6.2.52"></script>
<!--[if lt IE 9]>
    <script type="text/javascript" src="/aa/static_content/js/html5shiv/html5shiv.js?v3.7.2"></script>
<![endif]-->
<script type="text/javascript" src="/aa/static_content/js/respondjs/respond.min.js?v1.4.2"></script>
<script src="/aa/static_content/js/foundation/js/vendor/what-input.js?v4.2.0"></script>
<script src="/aa/static_content/js/foundation/js/foundation.min.js?v6.4.2"></script>
<!-- end head_javascript.tt2 -->
    </head>
    <body>
        <div id="top">
            <a class="displayNone" name="top" href="#content-inner">Skip to Content.</a>
        </div>
            <!-- header.tt2 -->
<header>
    <div class="title-bar"
         data-responsive-toggle="sympa-top-bar" data-hide-for="medium">
        <span class="menu-text" aria-hidden="true">
            <a href="http://www.example.com/aa/cc" title="http://www.example.com/aa/cc">
                    <img src="/aa/static_content/icons/logo_sympa.png" alt="SYMPA logo" />
                </a>
        </span>
        <div class="title-bar-right">
            <div class="title-bar-title">
                <span>Sympa Menu</span>
            </div>
            <a class="menu-icon" href="#" data-toggle="sympa-top-bar"></a>
        </div>
    </div>
    <nav class="top-bar" id="sympa-top-bar" role="navigation">
        <ul class="top-bar-left medium-2 columns show-for-medium">
            <li class="name">
                <span class="menu-text">
                    <a href="http://www.example.com/aa/cc" title="http://www.example.com/aa/cc">
                            <img src="/aa/static_content/icons/logo_sympa.png" alt="SYMPA logo" />
                        </a>
                </span>
            </li>
        </ul>
        <menu class="top-bar-right">
            <ul class="vertical medium-horizontal menu" data-responsive-menu="drilldown medium-dropdown">
                <!-- sympa_menu.tt2 -->
    <li class="">
        <a href="/aa/cc/home">
            <i class="fi-home"></i>  Home
        </a>
    </li>
    <li class="">
        <a href="#">
            <i class="fa fa-search-plus"></i> Search for List(s)
        </a>
        <ul class="vertical menu">
            <li class="">
                <a href="/aa/cc/search_list_request">
                    <i class="fa fa-search"></i> Search form
                </a>
            </li>
            <li class="">
                <a class="heavyWork" href="/aa/cc/lists">
                    <i class="fa fa-list"></i> Index of Lists
                </a>
            </li>
            <li class=""><a href="/aa/cc/lists_categories" target=""><i class="fa fa-sitemap"></i> Browse lists by categories</a>
        </ul>
    </li>
    <li class="">
        <a href="#">
            <i class="fa fa-life-ring"></i> Support
        </a>
        <ul class="vertical menu">
            <li class="">
                <a href="/aa/cc/help" title="Documentation">
                    <i class="fa fa-book"></i> Documentation
                </a>
            </li>
            <li class="">
                <a href="/aa/cc/help/faq.html" title="Frequently asked questions">
                    <i class="fa fa-question"></i> FAQ
                </a>
            </li>
        </ul>
    </li>
<!-- end sympa_menu.tt2 -->
                <!-- login_menu.tt2 -->
<li class="">
        <form action="/aa/cc" method="POST">
            <fieldset><input type="hidden" name="csrftoken" value="32f8e49d438c8271aacb3d18513d2af0" />
                <input type="hidden" name="previous_action" value="crash" />
                <input type="hidden" name="previous_list"   value="" />
                <span>
                    <button type="submit" name="action_login" value="Login">
                        <i class="fa fa-user"></i>
                        Login
                    </button>
                </span>
            </fieldset>
        </form>
    </li>
<!-- end login_menu.tt2 -->
            </ul>
        </menu>
    </nav>
    <h1 class="row">Mailing lists service</h1>
</header>
<!-- end header.tt2 -->
        <div id="loading"></div>
        <!-- aside_menu.tt2 -->
<aside class="medium-3 columns">
    </aside>
<!-- end aside_menu.tt2 -->
        <main id="content-inner" class="row"><a name="content-inner"></a>
                <!-- nav.tt2 -->
<!-- end nav.tt2 -->
                <h2>Internal Server Error</h2>
                <p>Sympa encountered an internal error.</p>
                <p>Please contact the listmaster.</p>
                   <p>Error: Can't locate object method &quot;host_port&quot; via package &quot;URI::_generic&quot; at /usr/share/sympa/lib/Sympa.pm line 756.
</p>
                   <h2>Traceback</h2>
                   <pre>DIED: Can't locate object method &quot;host_port&quot; via package &quot;URI::_generic&quot; at /usr/share/sympa/lib/Sympa.pm line 756.
 at /usr/share/sympa/lib/Sympa.pm line 756.
	Sympa::get_url(undef, 'help', 'nomenu', undef, 'paths', ARRAY(0x53c3460), 'authority', 'local') called at /usr/libexec/sympa/wwsympa.fcgi line 3868
	main::do_help() called at /usr/libexec/sympa/wwsympa.fcgi line 1544
</pre>
        </main><!-- End content-inner -->
        <div class="displayNone"><a href="#top">Top of Page</a></div>
        <div class="scroll-top-wrapper "></div>
        <!-- footer.tt2 -->
<footer role="contentinfo">
    <img src="/aa/static_content/icons/favicon_sympa.png" alt="SYMPA logo" width="20" height="20"/>
    <a href="https://www.sympa.org">Powered by Sympa 6.2.52</a>
</footer>
<!-- end footer.tt2 -->
    </body>
    <!-- end crash.tt2 -->
</html>

/etc/sympa/sympa.conf:
domain              web1.example.com
listmaster          listmaster@example.com
db_type             mysql
db_name             sympa
db_host             localhost
db_user             sympa
log_level           0
cookie               
css_url             /aa/static_content/css
pictures_url        /aa/static_content/pictures

/etc/sympa/web1.example.com/robot.conf:
wwsympa_url    http://www.example.com/aa/bb
soap_url       http://www.example.com/aa/bb/sympasoap
default_home   lists_categories
static_content_url      /aa/static_content

/etc/sympa/web2.example.com/robot.conf:
wwsympa_url    http://www.example.com/aa/cc
soap_url       http://www.example.com/aa/cc/sympasoap
default_home   lists_categories
static_content_url      /aa/static_content

/etc/httpd/conf.d/sympa.conf:
<IfModule mod_proxy_fcgi.c>
</IfModule>
<IfModule mod_fcgid.c>
    <Location /aa/bb/sympasoap>
        SetHandler fcgid-script
        Require all granted
    </Location>
    ScriptAlias /aa/bb/sympasoap /usr/libexec/sympa/sympa_soap_server-wrapper.fcgi
    <Location /aa/bb>
        SetHandler fcgid-script
        Require all granted
    </Location>
    ScriptAlias /aa/bb /usr/libexec/sympa/wwsympa-wrapper.fcgi
    <Location /aa/cc/sympasoap>
        SetHandler fcgid-script
        Require all granted
    </Location>
    ScriptAlias /aa/cc/sympasoap /usr/libexec/sympa/sympa_soap_server-wrapper.fcgi
    <Location /aa/cc>
        SetHandler fcgid-script
        Require all granted
    </Location>
    ScriptAlias /aa/cc /usr/libexec/sympa/wwsympa-wrapper.fcgi
</IfModule>
<Location /aa/static_content>
    Require all granted
</Location>
Alias /aa/static_content/css /var/lib/sympa/css
Alias /aa/static_content/pictures /var/lib/sympa/pictures
Alias /aa/static_content /usr/share/sympa/static_content

/var/log/httpd/access_log:
1.2.3.4 - - [21/Feb/2020:12:21:15 +0100] "GET /aa/cc/help HTTP/1.1" 503 9110 "-" "curl/7.29.0"

/var/log/httpd/error_log:
[Fri Feb 21 12:21:16.901409 2020] [fcgid:warn] [pid 135146] [client 1.2.3.4:36804] mod_fcgid: stderr: Use of uninitialized value in string eq at /usr/share/sympa/lib/Sympa.pm line 753.
[Fri Feb 21 12:21:21.981977 2020] [fcgid:warn] [pid 135145] mod_fcgid: cleanup zombie process 138470
````
Hoping that it is helpful.

**Comment by ikedas** [comment]
Sorry for repeating the same requests.  Could you please show us log of HTTP server and Sympa, **from when you sent the initial request to when wwsympa.fcgi dies.**

Additionally, please describe how you reproduced step-by-step (e.g. Launch browser, open the address xxxx://...., click xxxx, ...).

**Comment by bruncsak** [comment]
I am sorry. I forgot about the log of Sympa, here it comes.

And sorry, I thought it is better to reproduce with the program curl. One simple HTTP connection with the program curl, and the perl process dies. One access_log entry only. So here it is the same with an internet explorer browser:
````
I started my browser. Into the address bar I pasted the following URL and hit enter: https://www.example.com/aa/cc/
Then, in the "Support" pull down menu I select "Documentation".
I got:
Internal Server Error

Sympa encountered an internal error.

Please contact the listmaster.

Error: Can't locate object method "host_port" via package "URI::_generic" at /usr/share/sympa/lib/Sympa.pm line 756. 

Traceback
DIED: Can't locate object method "host_port" via package "URI::_generic" at /usr/share/sympa/lib/Sympa.pm line 756.
 at /usr/share/sympa/lib/Sympa.pm line 756.
	Sympa::get_url(undef, 'help', 'nomenu', undef, 'paths', ARRAY(0x5d74558), 'authority', 'local') called at /usr/libexec/sympa/wwsympa.fcgi line 3868
	main::do_help() called at /usr/libexec/sympa/wwsympa.fcgi line 1544



/var/log/sympa.log:
Feb 21 13:38:03 web1 wwsympa[143072]: info main:: WWSympa started, process 143072
Feb 21 13:38:03 web1 wwsympa[143072]: info main::do_lists_categories() [robot web2.example.com] [session 89731882581310] [client 1.2.3.4]
Feb 21 13:38:07 web1 wwsympa[143072]: info main::do_help() [robot web2.example.com] [session 89731882581310] [client 1.2.3.4]
Feb 21 13:38:07 web1 wwsympa[143072]: err main::#1544 > main::do_help#3868 > Sympa::get_url#756 DIED: Can't locate object method "host_port" via package "URI::_generic" at /usr/share/sympa/lib/Sympa.pm line 756.

/var/log/httpd/access_log:
1.2.3.4 - - [21/Feb/2020:13:38:02 +0100] "GET /aa/cc/ HTTP/1.1" 200 11198 "-" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"
1.2.3.4 - - [21/Feb/2020:13:38:07 +0100] "GET /aa/cc/help HTTP/1.1" 503 9110 "https://www.example.com/aa/cc/" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko"

````

**Comment by bruncsak** [comment]
No need for reverse proxy in front, I managed to reproduce the bug with direct http connection.

**Comment by ikedas** [comment]
1. I realized there is a bug. Could you please make a change below, restart httpd and check if the problem will be solved?
     ``` patch
     --- a/src/cgi/wwsympa.fcgi.in
     +++ b/src/cgi/wwsympa.fcgi.in
     @@ -3866,7 +3866,7 @@ sub do_help {
          # Given partial top URI, redirect to base.
          unless ($in{'help_topic'} or $ENV{REQUEST_URI} =~ /\/\z/) {
              $param->{'redirect_to'} = Sympa::get_url(
     -            $list, 'help',
     +            $robot, 'help',
                  nomenu    => $param->{'nomenu'},
                  paths     => [''],                 # Ends with '/'.
                  authority => 'local'
     ```
  2. I couldn't decide if SERVER_NAME (`ServerName` directive) in httpd configuration matches Sympa's URL.  If it does not, Sympa possiblly may not work correctly.

**Comment by bruncsak** [comment]
The problem disappeared with this patch. Thanks!

**Comment by ikedas** [comment]
@bruncsak , thanks for patience.  At last we can fix the bug.
Issue about `ServerName` was one of possible causes, but it turned out that it was not the case.

BTW I haven't answered one question:
> Is it correct to write:
> `wwsympa_url //www.example.com/aa/bb`, with other term not specifying the URL schema?

No.  Sympa cannot determine protocol used between client and server, and relative references including "network-path reference" (URL omitting scheme) cannot be used in its configuration.
