### ISSUE TITLE
How to create a test list at https://demo.sympa.org/?

### ISSUE THREAD

**Issue by jsbien** [sympa-community/sympa#880]
I've created an account but got a message that I'm not authorized to create a list. When I tried to request the creation, I got a message that the list already exists, but it is absent on the list of lists (the name is "kip").

On the other hand, I was unable to locate any description of how the demo can be used :-(

**Comment by racke** [comment]
The demo site isn't under control of the current Sympa community, so we are not be able to answer your question. It is quite outdated as well.

**Comment by jsbien** [comment]
Thanks for quick answer.
