### ISSUE TITLE
Is there a way to display the number of subscribers on the list home page?

### ISSUE THREAD

**Issue by jsbien** [sympa-community/sympa#881]
Any other way of allowing a subscriber to check the number of subscribers would be also OK.

**Comment by racke** [comment]
Do you want to show the number of subscribers for unauthenticated users? Which list type are you using?

**Comment by jsbien** [comment]
I just subscribed to a list run by Sympa 6.2.44 and it seems to me its configuration can be improved. I would like the number to be available to subscribed and/or logged users.

**Comment by racke** [comment]
Whether a subscriber sees the number of subscribers depends on the review scenario configured for the list in question. E.g. `review private` would show this number but also allows access to the subscriber information:
![test   Test   review](https://user-images.githubusercontent.com/143678/74926952-0975a380-53d7-11ea-90ff-c23f85824298.png)

**Comment by jsbien** [comment]
The owner of the list in question believes (it is an independent question whether he is right) that allowing access to the subscriber's information is prohibited by General Data Protection Regulation.
So my question is whether it is possible to show only the number of subscribers. If so, it is easy to create such a scenario?

**Comment by racke** [comment]
I can see the point, but it would require a new scenario and support in the web interface code.

**Comment by jsbien** [comment]
Thanks!
