### ISSUE TITLE
General Data Protection Regulation 

### ISSUE THREAD

**Issue by jsbien** [sympa-community/sympa#882]
Is it true that allowing subscribers to review the subscribers list is prohibited by GDPR? Years ago a German owner of a list claimed it is/was prohibited by German law... Google shows a lot of hits for GDPR and maling lists, but they don't seem relevant to the very problem.
I think that to be on the safe side one can request an explicit permision from the people wanting to subscribe.
Do you have some knowledge and/or experience on this topic?

**Comment by ikedas** [comment]
There seem no useful answers/comments.  This issue is closed by now.  Anyone may reopen it if they think it useful.
