### ISSUE TITLE
ldap_2level_query "select2 all" is returning only one result

### ISSUE THREAD

**Issue by caclement** [sympa-community/sympa#893]
In a dynamic data source, a ldap_2level_query seems to return only one result when "select2 all" is used. 

I have a list with a "include_ldap_2level_query" statement in the config file. I am only getting partial results on the second select. 

Example : I have 20 students, I want to get the parents for every student. I should have 40 parents but the result only returns 20 parents. It seems there is no difference between "select2 first" and "select2 all" in 6.2.52

I am on RHEL7 and the LDAP source is Microsoft Active Directory.

The bug is the same if I connect with LDAP with STARTTLS.

I have 6.0.1 in a lab and its working fine, I have the full results with the same config fille.

Version
-------
6.2.52

Installation method
-------------------
rpm

Expected behavior
-----------------
"select2 all" should return all results from a filter

Actual behavior
---------------
"select2 all" return only the first result

Additional information
----------------------
include_ldap_2level_query
select2 all
scope2 sub
suffix2 OU=PARENTS,OU=PEOPLE,dc=[redacted]
suffix1 OU=STUDENTS,OU=PEOPLE,dc=[redacted]
attrs1 cn
select1 all
filter2 (kids=[attrs1])
timeout1 60
name parent023706
attrs2 mail
bind_dn CN=[redacted]
scope1 sub
port 389
host [redacted]
bind_password [redacted]
filter1 (&(departmentNumber=023)(businessCategory=706))
timeout2 60

**Comment by ikedas** [comment]
Hi @caclement ,
Could you please present some samples of directory tree?

**Comment by caclement** [comment]
Hi @ikedas 

Do you have a prefered format ?

**Comment by ikedas** [comment]
Nothing in particular. Please choose a format you prefer.

**Comment by caclement** [comment]
Hello @ikedas 

I hope its clear enough !?

info.domain.com
				Computers
							ADM
								Building{1..n}
							PED
								Building{1..n}
							VDI
								Building{1..n}
				People
							Others
							Students
									All students are in this OU
							Employes
									All employes are in this OU
							Exams
							Kiosk
							Parents	
									All parents are in this OU
							Partners
									All partners are in this OU


More info :

All the students are in a flat container in info.domain.com/People/Students. There is no sub ou after that. Same for the parents.
									
The rest of the logic is in the user attributes and security groups (since its Active Directory)

**Comment by ikedas** [comment]
Sorry for not explaining enough. Could you please present a set of entries that can reproduce the behavior you reported?

**Comment by caclement** [comment]
Hello 

Here is 3 ldif file :

[children.txt](https://github.com/sympa-community/sympa/files/4307402/children.txt)
[parent1.txt](https://github.com/sympa-community/sympa/files/4307403/parent1.txt)
[parent2.txt](https://github.com/sympa-community/sympa/files/4307404/parent2.txt)

The children is filtered by the level1 query

filter1 (&(departmentNumber=023)(businessCategory=706))

The 2 parents are supposed to get filtered

filter2 (kids=[attrs1])

**Comment by ikedas** [comment]
Hi @caclement ,

Could you please apply a change below and check if the problem will be solved? Thanks.
``` patch
--- a/src/lib/Sympa/DataSource/LDAP.pm
+++ b/src/lib/Sympa/DataSource/LDAP.pm
@@ -149,8 +149,6 @@ sub _load_next {
 
             last if $ldap_select eq 'first';
         }
-
-        last if @retrieved;
     }
 
     return [@retrieved];
```

**Comment by ikedas** [comment]
The patch was applied for now.  Thanks for information!

**Comment by caclement** [comment]
@ikedas Sorry for the delay, but I can confirm that the bug is fixed ! Thank you for your good work !
