### ISSUE TITLE
Topic names in topics.conf with uppercase are ignored

### ISSUE THREAD

**Issue by wouldsmina** [sympa-community/sympa#91]
Hello,

No list is shown when selecting a topic with uppercase.

part of topics.conf : 
```
...
ADM
title administration
title.fr administration

RECH
title research
title.fr recherche
...
```
Debug : 
`
Oct 12 09:39:35 sympa wwsympa[9087]: debug3 Sympa::List::get_lists() filter (scalar(grep { $_ eq "adm" or index($_, "adm/") == 0 } @{$list->{"admin"}{"topics"} || []})); (topics_list LIKE '%,adm,%' OR topics_list LIKE '%,adm/%')
`

OS : DEBIAN 9
Sympa : 6.2.16

**Comment by MargoM** [comment]
I tried to reproduce, same debug:
```
Oct 12 16:33:35 sympa wwsympa[32645]: debug3 Sympa::List::get_lists() filter (scalar(grep { $_ eq "testtopic" or index($_, "testtopic/") == 0 } @{$list->{"admin"}{"topics"} || []})); (topics_list LIKE '%,testtopic,%' OR topics_list LIKE '%,testtopic/%')
```
OS: CentOS 7.4
Sympa: 6.2.20

I think there should be grep -i (ignore case).

**Comment by racke** [comment]
Which database do you use @wouldsmina, @MargoM

**Comment by wouldsmina** [comment]
hi @racke 
I use MySQL, but topics are stored in config file...

@MargoM I would rather `grep { lc($_),...` but I don't find where `get_lists()` execute this command. If any body help me to find where can i change this line, I can test and make a PR...

**Comment by racke** [comment]
This should be the grep you are searching for:

https://github.com/sympa-community/sympa/blob/master/src/lib/Sympa/List.pm#L8066

**Comment by racke** [comment]
I think you also need to lc($_) in index(...).

**Comment by wouldsmina** [comment]
not working too

**Comment by racke** [comment]
I'm wondering why you don't just lowercase "ADM" in topics.conf. I suppose it doesn't show in the UI anyway.

**Comment by MargoM** [comment]
I'm using MySQL. Like racke said, i think you should use uppercases in title/title.fr. This "ADM" is only stored in configuration file and in list_table table.

**Comment by wouldsmina** [comment]
> Like racke said, i think you should use uppercases in title/title.fr.

that's what I did. I just wanted to inform about this unexpected behavior

**Comment by ikedas** [comment]
I suppose only lowercase topic names are expected. The behavior accepting uppercase topic names seems bug.

**Comment by wouldsmina** [comment]
ok. So I close this ticket.
thanks

**Comment by ikedas** [comment]
Reopened.

If `db_list_chache` is `on` and database is MySQL, `topics_list` field will be matched using case-insensitive collation (`utf8_general_ci` etc.): Uppercase topic identifiers will be treated the same as lowercase.  This is not the case with the other database and no database (`db_list_chache` is `off`).

One solution is to normalize topic identifiers to lowercase.

**Comment by ikedas** [comment]
Merged.  This issue is closed.
