### ISSUE TITLE
Unsubscribed user lost when renaming a list

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#919]
When renaiming a list with data source, unsubscribed user who are listed in exclusion table are not excluded from the new name list.

Expected Behavior
-----------------
In exclusion table the list renamed should also be renamed in this table.

Current Behavior
----------------
The list is not renamed in exclusion_table.

Possible Solution
-----------------

Context
-------
We have this issue on redhat 7.6 running SYMPA 6.2.22 RPM package installation

**Comment by racke** [comment]
I tested renaming a list with file inclusion on the current code base and the records in the exclusion_table were changed to the new list.

**Comment by jth56000** [comment]
Ø  I tested renaming a list with file inclusion on the current code base and the records in the exclusion_table were changed to the new list.

You are right, I tested on a 6.2.52 release and it works.

**Comment by ikedas** [comment]
This looks fixed as part of #81, at commit 5ed9c56.
