### ISSUE TITLE
(Re)allow lists to only have owners from data sources

### ISSUE THREAD

**Issue by sivertkh** [sympa-community/sympa#92]
This might be more of a feature request then a bug rapport. 
In version 5 it was possible to have lists that only had owners from a data source. There was no need to set one manually a well.

If you try to remove the last owner in 6.2.16 you get the following error message.

`ERROR (edit_list) - Parameter 'owner' is mandatory. Ignoring deletion. 
ERROR (edit_list) - No parameter was edited `

**Comment by racke** [comment]
Yeah that makes sense. So I think it is a bug, as it defeats the purpose to have owners included from a database.
