### ISSUE TITLE
Typo in German Help "Introduction"

### ISSUE THREAD

**Issue by RainerBielefeld** [sympa-community/sympa#926]
Bug
-----
I found a typo on <https://demo.sympa.org/sympa/help/introduction>

"duzende"    should be
dutzende

Version
-------
6.2.32

Request
--------
Please move this one to a more appropriate place if necessary

**Comment by ikedas** [comment]
Hi @RainerBielefeld ,
Please correct [the text on translation site](https://translate.sympa.org/de/web_help/translate/de.po#unit=7900).  Note that you have to sign-in to edit translations.

**Comment by RainerBielefeld** [comment]
So I did.

**Comment by ikedas** [comment]
@RainerBielefeld , thanks much for correction!
