### ISSUE TITLE
command GET list file

### ISSUE THREAD

**Issue by larok972** [sympa-community/sympa#932]
Hi,
sympa_version: 6.2.22
Question:
When i try to get an archive with GET command in mail subject, the result is a failure. I think the problem is from a bad syntax of the file name, it's like (2020-04 80.9 ko jeu., 23 avril 2020 08:47:08) after INDEX list command. 
Anyone has an example?

Thanks in advance for your help

**Comment by ikedas** [comment]
Hi @larok972 ,

Please try:

```code
GET 2020-04
```

**Comment by ikedas** [comment]
Hi @larok972 ,

Please try:

```code
GET listname 2020-04
```

**Comment by larok972** [comment]
Hi ikedas,

'GET listname 2020-04' works well and i noted that if your smtp service is configured with a limited message size, you can't get taller archives.

Thank you

**Comment by ikedas** [comment]
Thanks for confirming.

> ... and i noted that if your smtp service is configured with a limited message size, you can't get taller archives.

It makes sense.  If you feel this behavior is a bug, please submit a new issue.
