### ISSUE TITLE
"Message not available" appears sometime in thread archive

### ISSUE THREAD

**Issue by PhilLAL** [sympa-community/sympa#935]
Version
-------
6.2.40 and 6.2.32 for listes.renater

Installation method
-------------------
deb package for 6.2.40, unknown for the 6.2.32

Expected behavior
-----------------
The thead archive should not display unavailable messages.

Actual behavior
---------------
**Examples:**
1. in https://listes.renater.fr/sympa/arc/sympa-users/2020-04/ we see a message `Re: [sympa-users] scenarii for request list possible?` sent on 15/04/2020 and an answer sent on 16/02/2020 (https://listes.renater.fr/sympa/arc/sympa-users/2020-04/msg00032.html), and between them a `Message not available`
2. in https://listes.renater.fr/sympa/arc/sympa-users/2020-03/ we see a message `[sympa-users] LDAP DATA Source` sent on 30/03/2020 and an answer sent on 31/03/2020 (https://listes.renater.fr/sympa/arc/sympa-users/2020-03/msg00046.html), and between them a `Message not available`. The 2d readable message cite a message which has not been sent on the list
3. in https://listes.renater.fr/sympa/arc/sympa-fr/2019-10/ we see a message `[sympa-fr] rediriger un mail de contact sur une liste privée` sent on 01/10/2019 and an answer sent on 01/10/2019 (https://listes.renater.fr/sympa/arc/sympa-fr/2019-10/msg00006.html), and between them a `Message not available`. The 2d readable message cite a message which has not been sent on the list
4. in https://listes.renater.fr/sympa/arc/sympa-fr/2019-07/ we see a message `[sympa-fr] sympa_aliases qui ne se met pas à jour` sent on 18/07/2019 and an answer sent on 18/07/2019 (https://listes.renater.fr/sympa/arc/sympa-fr/2019-07/msg00032.html), and between them a `Message not available`. The 2d readable message cite a message which has not been sent on the list

Additional information
----------------------
In the first case, the message source from https://listes.renater.fr/sympa/arc/sympa-users/2020-04/msg00031.html should be read to check if a filed `In-Reply-To:`correspond to the `Message-Id` from the one in source of https://listes.renater.fr/sympa/arc/sympa-users/2020-04/msg00031.html

In this case, my hypothesis is that when SYMPA displays thread archive, it creates an empty virtual message if it finds a missing Message-Id in the thread.

**Comment by ikedas** [comment]
> In this case, my hypothesis is that when SYMPA displays thread archive, it creates an empty virtual message if it finds a missing Message-Id in the thread.

You are right.  If a message is considered existing in the thread according to reference headers but doesn't really exist, an "unavailable" entry is shown.

**Comment by ikedas** [comment]
Markup for "Message not available" is defined by [TLINONE](https://www.mhonarc.org/MHonArc/doc/resources/tlinone.html) and [TLINONEEND](https://www.mhonarc.org/MHonArc/doc/resources/tlinoneend.html).  To change it on Sympa, modify `mhonarc_ressources.tt2` from:
``` code
<TLINONE>
        <li>
            ($tag$%|loc%$tag$)<em>Message not available</em>($tag$%END%$tag$)
</TLINONE>
```
to such as:
``` code
<TLINONE>
  <li>
</TLINONE>
```
Notes:
- Don't edit `mhonarc_ressources.tt2` in `default` directory. Instead copy it to SYSCONFDIR (such as `/etc/sympa`) and edit that copy.
- Changes on `mhonarc_ressources.tt2` won't change the archives in the past.

**Comment by ikedas** [comment]
There seem no more questions. Close.
