### ISSUE TITLE
sympa LDAP crash on RHEL7.8 Perl / ldap issue

### ISSUE THREAD

**Issue by gzcwnk** [sympa-community/sympa#945]
LDAP crash. This seems simialr to reported crash on < 0.65  but I am on perl:ldap 0.66

https://github.com/ikedas/sympa-rpm/issues/52

Version
-------

[root@vuwunicomailmnd2 ~]# rpm -q perl
perl-5.16.3-295.el7.x86_64
[root@vuwunicomailmnd2 ~]# rpm -q sympa
sympa-6.2.54-1.el7.x86_64
[root@vuwunicomailmnd2 ~]#

Installation method
-------------------

EPEL  + CPAN modules

[root@vuwunicomailmnd2 ~]# cpan -l |grep -i socket
IO::Socket::SSL 2.068
IO::Socket::INET6       2.72

[root@vuwunicomailmnd2 ~]# cpan -l |grep -i NET | grep -i LDAP
Bundle::Net::LDAP       0.03
Net::LDAP       0.66
8><--

Expected behavior
-----------------

web ui should not crash

Actual behavior
---------------

crashes as below,

Additional information
----------------------

DIED: Can't locate IO/Socket/INET6.pm in @INC (@INC contains: /usr/share/sympa/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /usr/share/perl5/vendor_perl/Net/LDAP.pm line 31.
 at /usr/share/perl5/vendor_perl/Net/LDAP.pm line 31.
	eval {...} called at /usr/share/perl5/vendor_perl/Net/LDAP.pm line 31
	Net::LDAP::BEGIN() called at /usr/share/perl5/vendor_perl/Net/LDAP.pm line 31
	eval {...} called at /usr/share/perl5/vendor_perl/Net/LDAP.pm line 31
	require Net/LDAP.pm called at (eval 305) line 2
	eval 'require Net::LDAP
;' called at /usr/share/sympa/lib/Sympa/Database.pm line 123
	Sympa::Database::connect(Sympa::DatabaseDriver::LDAP <host=ldap://10.180.48.95:392;use_tls=none>) called at /usr/libexec/sympa/wwsympa.fcgi line 3798
	main::is_ldap_user(undef) called at /usr/libexec/sympa/wwsympa.fcgi line 3071
	main::do_login() called at /usr/libexec/sympa/wwsympa.fcgi line 1541

**Comment by gzcwnk** [comment]
OK so it looks like a missing package and cpan put INET6 in /root/ which was un-expected. So the messy fix is,

cp /root/perl5/lib/perl5/IO/Socket/INET6.pm /usr/lib64/perl5/IO/Socket/

systemctl restart wwsympa.service

:(

**Comment by ikedas** [comment]
See [thread on sympa-users](https://listes.renater.fr/sympa/arcsearch_id/sympa-users/2020-05/SYCPR01MB47818F7ADC49EC399BC06A27D4B20%40SYCPR01MB4781.ausprd01.prod.outlook.com).

Abandoned issue. Closed.
