### ISSUE TITLE
sympa.conf not applies when I change and reboot

### ISSUE THREAD

**Issue by rafaelmr2** [sympa-community/sympa#951]
Hi,

I'm using **Sympa 6.2.54** (CentOS 7 Repository) with single domain. When I change some option in `/etc/sympa/sympa.conf` and restart (`systemctl restart sympa`), it does not apply de modifications.

What more else I have to do?

Thanks.

**Comment by ikedas** [comment]
Hi @rafaelmr2 ,
- How did you make modification on `sympa.conf`?
- What changes did you expect?

**Comment by ikedas** [comment]
Please make sure that services are really restarted, i.e.:
``` bash
# systemctl status sympa
(check if the service is running)
# systemctl restart sympa
# systemctl status sympa
(check if the service has been restarted)
```
And, please show us what is output during the steps above.

**Comment by rafaelmr2** [comment]
I also tried to reboot and nothing.

**Comment by rafaelmr2** [comment]
I don't know why, but I reboot again and I think it's working now 🤔
