### ISSUE TITLE
Issue with message.footer in 6.2.54

### ISSUE THREAD

**Issue by jth56000** [sympa-community/sympa#952]
I upgrade my SYMPA serever from 6.2.52 to 6.2.54.
I noticed that message.footer link change.

Version
-------
6.2.54 on redhat 7.6 rpm package

Installation method
-------------------
RPM

Expected behavior
-----------------

Actual behavior
---------------
I set the new message.footer.tt2 link for my family of list as described in https://sympa-community.github.io/manual/customize/basics-families.html#family-unsubscription

But when I create a new list the message.footer is empty.

Additional information
----------------------

**Comment by ikedas** [comment]
@jth56000 ,

Please show us the content of `message.footer.tt2` you created.

**Comment by jth56000** [comment]
Hello Soji,

 

Ø  Please show us the content of message.footer.tt2 you created.

Here is the message.footer.tt2 I created as described in the doc : 

[% TAGS <+ +> -%]

To stop receiving messages from <+ family_config.display +>, click on this link: [% 'family_signoff' | url_abs(['<+ family_config.name +>'],{email=user.email}) %]

<+ TAGS [% %] -+>

**Comment by ikedas** [comment]
Could you please show us the log `from when` you start the operation to create a new list `to when` the list is created?

**Comment by jth56000** [comment]
Could you please show us the log from when you start the operation to create a 
new list to when the list is created?

It looks like i got some errors :

Jun  5 14:22:35 tcgisympa2 bulk[48811]: notice 
Sympa::Spindle::ProcessOutgoing::_twist() Start sending message Sympa::Message 
<1.5.1591359754.1591359754.760002.sympa@listes-int.dsi.cnrs.fr_s,48698,8125/s> 
to listes-int.dsi.cnrs.fr (priority 1) (starting 1 seconds after scheduled 
expedition date)

Jun  5 14:22:35 tcgisympa2 wwsympa[84427]: notice 
main::do_create_automatic_list(jean-test) [robot listes-int.dsi.cnrs.fr] 
[session 16986523868627] [client 10.238.30.3] [user 
listmaster-int@dsi.cnrs.fr]

Jun  5 14:22:35 tcgisympa2 wwsympa[84427]: notice 
Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request 
<action=create_automatic_list;context=jean-test@listes-int.dsi.cnrs.fr>

Jun  5 14:22:35 tcgisympa2 wwsympa[84427]: err main::#1541 > 
main::do_create_automatic_list#16985 > Sympa::Spindle::spin#95 > 
Sympa::Request::Handler::create_automatic_list::_twist#207 Template error. 
List jean-test+ie-14-all-all from family Sympa::Family 
<jean-test@listes-int.dsi.cnrs.fr>, file message_footer : file error - 
message_footer.tt2: not found

Jun  5 14:22:35 tcgisympa2 wwsympa[84427]: err main::#1541 > 
main::do_create_automatic_list#16985 > Sympa::Spindle::spin#95 > 
Sympa::Request::Handler::create_automatic_list::_twist#207 Template error. 
List jean-test+ie-14-all-all from family Sympa::Family 
<jean-test@listes-int.dsi.cnrs.fr>, file message_footer.mime : file error - 
message_footer.mime.tt2: not found

Jun  5 14:22:35 tcgisympa2 wwsympa[84427]: info 
Sympa::List::_load_list_config_file() Missing key "email" in param "creation" 
in 
/datasan/sympa/list_data/listes-int.dsi.cnrs.fr/jean-test+ie-14-all-all/config

Jun  5 14:22:35 tcgisympa2 wwsympa[84427]: info 
Sympa::List::_load_list_config_file() Missing key "date_epoch" in param 
"creation" in 
/datasan/sympa/list_data/listes-int.dsi.cnrs.fr/jean-test+ie-14-all-all/config



But in my family directory I got the message.footer.tt2 file :

root@tcgisympa2:/etc/sympa/listes-int.dsi.cnrs.fr/families/jean-test 
[2020/06/05-14:25:51]

#ls -l

total 32

-rw-r--r-- 1 sympa sympa 2865  7 nov.   2019 automatic_lists_description.conf

-rw-r--r-- 1 sympa sympa 2869 27 mai    2019 
automatic_lists_description.conf.save

-rw-r----- 1 sympa sympa 2865  7 nov.   2019 
automatic_lists_description.conf.txt

-rwxr-xr-x 1 sympa sympa 1668 30 juil.  2019 config.tt2

-rwxr-xr-x 1 sympa sympa 1662  5 juin   2019 config.tt2.20190605

-rwxr-xr-x 1 sympa sympa 1636 27 mai    2019 config.tt2.bak

-rw-r--r-- 1 sympa sympa  199  5 juin  10:09 message.footer.tt2

-rw-r--r-- 1 sympa sympa  199 27 mai    2019 message.footer.tt2.save

-rwxr-xr-x 1 sympa sympa    0 27 mai    2019 param_constraint.conf

**Comment by ikedas** [comment]
As of 6.2.42, `message.footer` has been renamed to `message_footer` (See also #507).  This change was noted in documentation (I'll correct it later).

@jth56000 , Could you rename `message.footer.tt2` to `message_footer.tt2` and then try again?

**Comment by jth56000** [comment]
Thank you Soji, that was it.

We did not realize this modification when we migrate from 6.2.22 to 6.2.52 in april.

 

The issue can be closed.

 

De : IKEDA Soji <notifications@github.com> 
Envoyé : vendredi 5 juin 2020 14:43
À : sympa-community/sympa <sympa@noreply.github.com>
Cc : THOMAS Jean <jean.thomas@ext.dsi.cnrs.fr>; Mention <mention@noreply.github.com>
Objet : Re: [sympa-community/sympa] Issue with message.footer in 6.2.54 (#952)

 

As of 6.2.42, message.footer has been renamed to message_footer (See also #507 <https://github.com/sympa-community/sympa/issues/507> ). This change was noted in documentation (I'll correct it later).

@jth56000 <https://github.com/jth56000>  , Could you rename message.footer.tt2 to message_footer.tt2 and then try again?

**Comment by ikedas** [comment]
I modified documentation (sympa-community/sympa-community.github.io@2fffb83).

Thanks for reporting the problem!
