### ISSUE TITLE
"false" values in XML file prevent list creation

### ISSUE THREAD

**Issue by seblgr** [sympa-community/sympa#953]
Version
-------
6.2.56

Installation method
-------------------
source package

Expected behavior
-----------------
The list should be created 

Actual behavior
---------------
The list is not created

Additional information
----------------------
When a XML file used for list creation contains a "false" value (any value that evaluate as false in boolean context), the list is not created.
In the logs, we see the following error :
```sympa[15053]: err main::#764 > main::instantiate#1325 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_automatic_list::_twist#68 Error in representation data with these xml data```

In our family XML file, some lists contains the following line (the tag doesn't matter actually) : 
```<tag>0</tag>```
In Config_XML.pm, line 171
```perl
return undef unless $values;
```
in this case $values contains "0", which is false, thus the parsing ends prematurely and the list is not created. 
The others lists in the family are OK.

**Comment by ikedas** [comment]
Hi @seblgr ,
Could you please attach a sample of XML file by which we can reproduce the buggy behavior you reported?

**Comment by seblgr** [comment]
Hi @ikedas 
Here it is :
[create_family.zip](https://github.com/sympa-community/sympa/files/4736623/create_family.zip)

I forgot to mention that we don't have that problem in our current production system which is installed with version 6.2.42.

**Comment by ikedas** [comment]
Fixed. Thank you for reporting bug!
