### ISSUE TITLE
About "custom_subject"

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#958]
Hello.

There are two questions about "custom_subject".

## 1. About changing "custom_subject" in the list family

I want to unify "custom_subject" in the list, and added the following description to "param_constraint.conf".

`custom_subject [% list.name %]:[% list.sequence %]`

However, after adding the above setting and executing "--modify_list", the setting of the list was marked as an error.
Is it possible to change the "custom_subject" in the list family?

## 2. About "[% list.sequence %]"
Is it possible to align numbers to a specific number of digits with "[% list.sequence %]" of "custom_subject"?
For example, I want to display "1" as "001". Is this possible?

-----

The environment is Ubuntu 20.04, Sympa 6.2.56.

Best regards.

**Comment by ikedas** [comment]
日本語の質問には、可能なら英語のサマリをつけていただけるとありがたいです (全文翻訳でなくてもいいです)。コミュニティメンバの中にも「英語で書かないとみんなが読めないじゃないか!」と言う人もいますので。

Riku, could you add English summary?

**Comment by riku22** [comment]
@ikedas 
I'm sorry.
I edited it.

**Comment by ikedas** [comment]
Thanks!

個人的には、フランス語でも日本語でも今どきは機械翻訳で簡単に読めるので、むしろ英語にこだわらず自分の言語の投稿が増えてほしいです。

**Comment by ikedas** [comment]
Hi 陸,

Please check description about [custom subject](https://sympa-community.github.io/manual/customize/basics-templates.html#custom-tag-delimiters) in the manual.

**Comment by riku22** [comment]
@ikedas 
Thank you.
I deleted "param_constraint.conf" and added the following contents to "/etc/sympa/list.example.com/families/my_family/config.tt2" as a trial.

```
[% TAGS <+ +> %]
custom_subject [% list.name %]:[% list.sequence %]
<+ TAGS [% %] +>
```

Then, in the hope of updating the settings in the existing list, run the following command:

`sympa.pl --modify_list my_family --robot list.example.com --input_file list.xml`

However, the following contents are output to the log and the update fails.

```
Jun 16 23:00:30 riku22 sympa[66825]: notice main:: Sympa 6.2.56 Started
Jun 16 23:00:30 riku22 sympa[66825]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=update_automatic_list;context=mailinglist@ml.riku22.xyz>
Jun 16 23:00:30 riku22 sympa[66825]: err main::#940 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::update_automatic_list::_twist#61 > Sympa::Config_XML::new#72 The root element must be called "list"
Jun 16 23:00:30 riku22 sympa[66825]: err main::#940 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::update_automatic_list::_twist#63 Error in representation data with these xml data
```

The contents of the XML file are as follows.

```
<?xml version="1.0" ?>
<list>
<listname>test</listname>
<subject>test</subject>
<description/>
<status>open</status>
<language>ja</language>
<visibility>conceal</visibility>
<subscribe>auth</subscribe>
<archive>private</archive>
<user_visibility>conceal</user_visibility>
<reply_to>list</reply_to>
<strip_reply_to>respect</strip_reply_to>
<send>privateoreditorkey</send>
<topics>no</topics>
<owner multiple="1">
<email>contact@example.com</email>
<gecos>Riku</gecos>
</owner>
</list>
```

How can I update the settings in the list?

Best regards.

**Comment by riku22** [comment]
Hello.

The problem that XML cannot be updated due to an error has been solved.

After changing 

`<description/>`

to 

`<description>test list</description>`

, I was able to update the settings.

Then, the method of aligning "[% list.sequence %]" with a specific number of digits worked fine, as shown below.

- Save the following plugin with an appropriate file name.
```
#!/usr/bin/perl

package Sympa::Template::Plugin::sprintfPlugin;

use base qw( Template::Plugin );
use Template::Plugin;

sub load {
    my ($class, $context) = @_;
    return $class;
}

sub sprintf {
    my ($self, $number, $digit) = @_;
     $digit = 3 if !defined $digit;
     return sprintf("%0".$digit."d", $number);
}

1;
```
- Change "custom_subject" as follows.
```
[% TAGS <+ +> %]
custom_subject [% USE p = sprintfPlugin %][% list.name %]:[% p.sprintf(list.sequence, 3) %]
<+ TAGS [% %] +>
```

There may be a better way, but for now I'm able to insert something like "[test:005]" in the subject line using the above method.

Best regards.
