### ISSUE TITLE
About tags that can be used in "message_footer.tt2"

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#959]
Hello.

I'm trying to create a family and customize the message footer with "message_footer.tt2".
So, I have one question, is there a list of tags that can be used in the above file?
For example, is there a tag that gets the domains in the list?
I tried using "listdomain" and "[% list.domain %]", but it doesn't seem to work.

```
[% TAGS <+ +> -%]

----------
<+ subject +>

Contact the administrator:
<+ listname +>-request@<+ domain +>

<+- TAGS [% %] +>
```

I would appreciate any advice.
The environment is Ubuntu 20.04, Sympa 6.2.56.

Best regards.

**Comment by ikedas** [comment]
Hi, @riku22 ,

Firstly, you have to set `merge_feature` parameter to `on`.

Then these template variables in the messages will be interpolated (Note: these have not been documented and some of them may be deprecated or changed in the future):
  - `listname`
  - `domain`
  - `wwsympa_url`
  - `user.email`
  - `user.reception`
  - `user.suspend`
  - `user.startdate`
  - `user.enddate`
  - `user.bounce`
  - `user.bounce_score`
  - `user.bounce_address`
  - `user.date`
  - `user.update_date`
  - `user.inclusion`
  - `user.inclusion_ext`
  - `user.inclusion_label`
  - `user.gecos`
  - `user.number_messages`
  - `user.visibility`
  - `user.topics`
  - `user.subscribed`
  - `user.custom_attribute.<attribute name>`

**Comment by riku22** [comment]
Hi, @ikedas.

It worked.
Thank you very much.

Sincerely.
