### ISSUE TITLE
Typo in Documentation: "Mailing Lit"

### ISSUE THREAD

**Issue by rhamnousia** [sympa-community/sympa#967]
There appears to be a typo in some documentation: namely, that the phrase "mailing list" is spelled as "mailing lit." This is incorrect, and it appears in these files:

modified:   default/web_tt2/help_introduction.tt2
modified:   po/sympa/fr.po
modified:   po/sympa/ru.po
modified:   po/web_help/af.po
modified:   po/web_help/ar.po
modified:   po/web_help/bg.po
modified:   po/web_help/br.po
modified:   po/web_help/ca.po
modified:   po/web_help/cs.po
modified:   po/web_help/de.po
modified:   po/web_help/el.po
modified:   po/web_help/en_US.po
modified:   po/web_help/eo.po
modified:   po/web_help/es.po
modified:   po/web_help/et.po
modified:   po/web_help/eu.po
modified:   po/web_help/fi.po
modified:   po/web_help/fr.po
modified:   po/web_help/gl.po
modified:   po/web_help/hu.po
modified:   po/web_help/id.po
modified:   po/web_help/io.po
modified:   po/web_help/it.po
modified:   po/web_help/ja.po
modified:   po/web_help/ko.po
modified:   po/web_help/la.po
modified:   po/web_help/ml.po
modified:   po/web_help/nb.po
modified:   po/web_help/nl.po
modified:   po/web_help/nn.po
modified:   po/web_help/oc.po
modified:   po/web_help/pl.po
modified:   po/web_help/pt.po
modified:   po/web_help/pt_BR.po
modified:   po/web_help/rm.po
modified:   po/web_help/ro.po
modified:   po/web_help/ru.po
modified:   po/web_help/sv.po
modified:   po/web_help/tr.po
modified:   po/web_help/vi.po
modified:   po/web_help/web_help.pot
modified:   po/web_help/zh_CN.po
modified:   po/web_help/zh_TW.po

This list I have sourced from a commit I have made fixing the issue. I was trying to create a branch to push this commit to; however this has been disallowed with this project. I am not sure—therefore—how I am supposed to go about fixing this issue, so if someone could please clarify, it would be greatly appreciated. I would like to apologize in advance for my inexperience. Thank you very much for your time.

**Comment by rhamnousia** [comment]
Apparently some of the items on the list do not need to be modified. I made a script to automate the correction process and it appears that it was a bit overzealous.

**Comment by ikedas** [comment]
Hi,
To correct typo of English message, please correct translation in English catalog on [translation site](https://translate.sympa.org/).

Btw I couldn’t find the typo you reported in recent version of Sympa.

**Comment by racke** [comment]
I could find it:

```
~/sympa-community/sympa (sympa-6.2 )$ git grep "mailing lit" default/
default/web_tt2/help_introduction.tt2:        [%|helploc%]It is sometimes possible to send messages to a mailing lit without having subscribed to it. However, you need to be subscribed to a list to receive its messages.[%END%]

```

**Comment by ikedas** [comment]
Ok [you can correct](https://translate.sympa.org/en_US/web_help/translate/en_US.po#unit=9676).
Closed.

**Comment by racke** [comment]
Corrected the typo on the translation site.

**Comment by rhamnousia** [comment]
Thank you to everyone for your help.
