### ISSUE TITLE
Cannot include privileged owner from list even if it has to

### ISSUE THREAD

**Issue by jacot641** [sympa-community/sympa#969]
Trying to include a serie of privileged owner from other list. The included owners are not privileged even if I choose in the drop down menu to do so. Raising included owner to privileged is possible by hand afterwards, one by one.

Version
-------
6.2.54

Installation method
-------------------
Updated from source installed SYMPA 6.1.25 to , still from source, SYMPA 6.2.54.

Expected behavior
-----------------
Include owners from other list. Choose privileged owner in dropdown menu. Should included owners tagged with a star as privileged have.
owner_include, source_parameters <list>, profile "privileged"

Actual behavior
---------------
Included owners from list does not have a star. The elevation of right to privileged is possible by hand by listmaster.

Additional information
----------------------

err main::#1541 > main::do_edit_list#10622 >
Sympa::List::sync_include_admin#4854 > Sympa::Spindle::spin#95 >
Sympa::Request::Handler::include::_twist#188 >
Sympa::Request::Handler::include::_update_inclusion_table#552 >
Sympa::Database::do_prepared_query#382 Unable to execute SQL statement
"INSERT INTO inclusion_table (target_inclusion, role_inclusion,
source_inclusion, update_epoch_inclusion) VALUES (?, ?, ?, ?)": (23000)
Duplicate entry 'listea@unifr.ch-listeb@unifr.ch-owner' for key 'PRIMARY'
Jul  3 14:45:59 svx-sympa2 wwsympa[34828]: err main::#1541 >
main::do_edit_list#10622 > Sympa::List::sync_include_admin#4854 >
Sympa::Spindle::spin#95 > Sympa::Request::Handler::include::_twist#188 >
Sympa::Request::Handler::include::_update_inclusion_table#573 Unable to
update list Sympa::List <listeb@unifr.ch> in database

**Comment by ikedas** [comment]
@jacot641 , has the owner already been included as normal owner?  If they have been, they may not be included again as priveleged owner.

**Comment by jacot641** [comment]
Nope, he wasn't already included as normal owner. I just check once again with another list. Same result. Same error in log, and privileged included owner let him as "normal" owner.
And further, when I delete the inclusion from interface, it won't erase included owner as well (!).
No inclusion in config file, that's ok, but still entry in DB:

list_admin	user_admin	role_admin	update_admin	reception_admin	comment_admin	subscribed_admin	included_admin	include_sources_admin	info_admin	profile_admin	robot_admin	visibility_admin	date_epoch_admin	inclusion_admin	inclusion_ext_admin	inclusion_label_admin	update_epoch_admin
<list>	<email>	owner	\N	mail	\N	0	\N	\N	\N	normal	<robot>	noconceal	1595321946	1595321946	\N	include_list <list-name>	1595321946

Something get wrong with the DB updating.

**Comment by ikedas** [comment]
@jacot641 , could you please try [this patch](https://github.com/sympa-community/sympa/files/4958087/issue-969.patch.txt)?

A new list configuration parameter `owner_defaults` in data source section will control defaults of the included owners.

**Comment by ikedas** [comment]
@jacot641 , please throw the last patch away.  Please use [this patch](https://github.com/sympa-community/sympa/commit/245e57be0434b26e39b280250430370bf2ff5e5c.patch).

**Comment by ikedas** [comment]
Reopen: See the comments in #973
