### ISSUE TITLE
About "anonymous_sender"

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#974]
Hello.

I have a question about "anonymous_sender".
Is there a way to add the sender's name to the From field when using "anonymous_sender"?
As an example, I set "anonymous_sender" to "test@example.com".
If you send an email from the list in this state, the From header value will be "test@example.com", but the sender's name that was set when the list was posted will be cut.
I want to change the address to another address (here, "test@example.com") while keeping the name.
Is there any way?
I would appreciate any advice.

Best regards.

-----

お世話になります。
「anonymous_sender」について質問です。
「anonymous_sender」利用時にFromフィールドに送信者の名前を追加する方法はありますか？
例として、私は「anonymous_sender」に「test@example.com」を設定しました。
この状態でリストからメールを送信すると、Fromヘッダの値は「test@example.com」となりますが、リスト投稿時に設定されていた送信者の名前がカットされてしまいます。
これを名前を残しつつ、アドレスだけ別のアドレス（ここでは、「test@example.com」）に変更したいです。
何か方法はありますでしょうか。
アドバイスいただければ幸いです。
以上、よろしくお願いいたします。

**Comment by ikedas** [comment]
Message anonymization feature replaces `From:` field entirely.  Possible workaround is setting full mailbox (`Name <email>`) replacing both name and email (note that `Name` should be encoded).

送信者秘匿では`From:`フィールドを丸ごと置き換えてしまいます。`名前 <アドレス>` を設定すれば名前とアドレスを同時に置き換えることはできます (`名前` はエンコードが必要)。

**Comment by riku22** [comment]
Hello.

After doing various research, I selected "all" in "Protection mode" of "DMARC protection function" in the setting, and then selected "display_name" in "Sender rewriting format". It was realized.
However, if the receiver sees all the headers, the sender etc. will be known...
Thank you very much.

Best regards.

----------

いろいろ調べてみたところ、設定の「DMARC保護機能」の「保護モード」で「all」を選択した上で、「送信者書き換えの形式」で「display_name」を選択することで、とりあえず、やりたいことは実現できました。
ただ、受信者がヘッダをすべて見ると、送信者等がわかってしまいますが…。
ありがとうございました。

敬具。
