### ISSUE TITLE
message.footer along with PGP/MIME signature

### ISSUE THREAD

**Issue by mhow2** [sympa-community/sympa#976]
Running sympa 6.2.40 (Debian buster)

I have a list with `footer_type append` and a valid `message.footer`
When I send a message to the list with my PGP/MIME signature, the `message.footer` is not included in the resulting email sent by Sympa and I notice the following error in logs:

```
Jul 28 12:06:36 xxx sympa_msg[12105]: err main::#243 >
Sympa::Spindle::spin#83 > Sympa::Spindle::ProcessIncoming::_twist#204 >
Sympa::Message::check_smime_signature#1293 Sympa::Message
<sympa@ow2.org.1595930795.8193>: Unable to verify S/MIME signature:
Crypt: :SMIME#check: failed to check the signature: error:0D0D40D5:asn1
encoding routines:SMIME_read_ASN1:sig invalid mime type at /usr/shar
e/sympa/lib/Sympa/Message.pm line 1292.#012
```

So I guess the message is somehow "protected" (`Message.pm`)

```perl
1281     ## Messages that should not be altered (no footer)
1282     $self->{'protected'} = 1;
```

FYI, my MUA sends the following header:
```
MIME-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha512;
 boundary="Sig_/Z0v2u2k0icYKuuXQMgmlWFA";
protocol="application/pgp-signature"
```

I wanted to know:
- if it's expected
- If there is a solution to get both the PGP signature **and** `message.footer` included

Thanks !

**Comment by ikedas** [comment]
Yes, it's expected: The messges with `multipart/signed` content type won't be altered.

Currently, there are no ways to alter the body of such message.  Otherwise message signature would be broken.
