### ISSUE TITLE
Review.tt2 button correction.

### ISSUE THREAD

**Issue by MargoM** [sympa-community/sympa#98]
Hello!

I think some buttons ("Add" and "Multiple add") in review.tt2 are not in correct position. Screenshot: https://i.imgur.com/dZY2AYR.png
It seems that after this change https://github.com/sympa-community/sympa/commit/49f282562326461016a63936642d0c8aa740b647#diff-66948009965069770acd20e212cdbbe6 some html code (breaks and stuff) disappeared.

Sympa: 6.2.20.

Best wishes!

**Comment by ikedas** [comment]
@MargoM, could you give the modification to correct the problem?

Submitting pull request is better way.  But if you are not familiar with PR, please post the diff against current template.

**Comment by MargoM** [comment]
@ikedas, a suggested modification:

default/web_tt2/review.tt2, (https://github.com/sympa-community/sympa/blob/master/default/web_tt2/review.tt2)

```
      <label for="quietly">
        [%|loc%]Quiet (don't send welcome email)[%END%]
      </label>
+     <br />
      <input class="MainMenuLinks" type="submit" name="action_add"
       value="[%|loc%]Add[%END%]" />
    </div>
    </fieldset>
    </form>
    <h4>[%|loc%]To add multiple users:[%END%]</h4>
    <p>[%|loc%]Click the Multiple Add button below to bulk-add users using a form.  (Alternatively, consider using a data-source such as SQL or an Active Directory Group).[%END%]</p>
-   <div>
+   <p>
      <a class="button" href="[% 'import' | url_rel([list]) %]">
        [%|loc%]Multiple add[%END%]
      </a>
-   </div>
+   </p>
[%~ END %]
```

**Comment by ikedas** [comment]
Merged. Thanks for correction!
