### ISSUE TITLE
Stuck on Configuration for new Sympa Install

### ISSUE THREAD

**Issue by acastelletto** [sympa-community/sympa#980]
Hi everyone. Thanks in advance for helping out someone new to Sympa.
I'm stuck on my install of Sympa. I can't seem to get the web interface configured right. 

When I try the sympa url I believe I set up, I get the following error:
```
[Mon Aug 10 02:23:59 2020] [authz_core:error] [pid 76391:tid 139953807759104] [client 172.8.150.218:59462] AH01630: client denied by server configuration: /home/ljconnections/libraryjuiceconnections.com/html/sympa
```
Can anyone give me some pointers for the web configuration? Thanks in advance.

My web admin skills aren't as sharp as they should be so I feel like I'm missing something fundamental.
System info: I'm running things on CentOS using a Liquidweb host which is run through an Interwork control panel. This means that many configuration files sit in different places than they might in a stand alone server.
The httpd configuration, I pulled straight from the install instructions and it reads as follows:
```
LoadModule alias_module modules/mod_alias.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

<Location /sympa>
    SetHandler "proxy:unix:/run/sympa/wwsympa.socket|fcgi://"
    Require all granted
</Location>

<Location /static-sympa>
    Require all granted
</Location>
Alias /static-sympa /usr/share/sympa/static_content
```
The relevant section from the sympa.conf file looks like:
```
#######################################################################
# Configure HTTP server
# See https://sympa-community.github.io/manual/install/configure-http-server$
########################################################################

mhonarc             /usr/bin/mhonarc
log_facility        LOCAL1

# If you chose single domain setting, you may have to define following
# parameters in this sympa.conf file.  Otherwise, if you chose virtual
# domain setting (recommended), you should define them in robot.conf by
# each domain.

wwsympa_url        https://www.ourdomain.com/sympa
use_fast_cgi  1
#mhonarc        /usr/bin/mhonarc
static_content_url /static-sympa
static_content_path /usr/share/sympa/static_content
########################################################################
```

**Comment by ldidry** [comment]
I think you need to add this to your Apache configuration to fix the problem in your logs:
```
<Directory /home/ljconnections/libraryjuiceconnections.com/html/sympa>
    Require all granted
</Directory>
```

But I don’t understand why your Sympa would be in `/home/ljconnections/libraryjuiceconnections.com/html/sympa` and the static assets in `/usr/share/sympa/static_content`.

How did you installed Sympa? Where is it installed? All the Sympa stuff (configuration, `list_data`, `spool`, etc) should not be in a directory you can access from a web server (and your path `/home/ljconnections/libraryjuiceconnections.com/html/sympa` makes me believe it’s the case), a small error of configuration would make all the files, even the private ones, available from the web.

**Comment by ikedas** [comment]
Stagnating issue.  Close by now.
