### ISSUE TITLE
Qmail Configuration issues

### ISSUE THREAD

**Issue by acastelletto** [sympa-community/sympa#982]
Hi Sympa team,

Still working on my sympa installation. I solved the web access issues and wwsympa up, running, and working just fine. But, I'm running (I think) into issues with my configuration for QMail. 
Following the install directions, once I create the aliases and execute the test, I do see activity in the mail queue and it does appear to receive messages. However, when I create new list using the web interface, things begin to go wrong. The list itself gets created. When I subscribe a user to the list, they receive a confirmation email with a link. That all works alright. However, when I attempt to post to the list or send commands like unsubscribe or help, the mail bounces. Do you have an advice on how to fix these problems? 

Thanks.

**Comment by ikedas** [comment]
@acastelletto , could you please show whole configuration for your qmail and Sympa?

**Comment by racke** [comment]
See the mailing list post from John Levine with a Qmail recipe: https://listes.renater.fr/sympa/arc/sympa-users/2020-08/msg00027.html

**Comment by ikedas** [comment]
No update for ling time. Close.
