### ISSUE TITLE
Is it possible to hook my mail server to Sympa?

### ISSUE THREAD

**Issue by radamesi** [sympa-community/sympa#984]
Hi! We are trying to setup a brand new Sympa install.

Right now we have a fully functional mail server for our primary domain and we would like to use the list management capabilites built in Sympa, using a domain such as lists.ourdomain.com.

Does Sympa itself send/receive e-mails or is hooked up to the primary mail domain server and then the primary mail domain itself send the e-mails? We would highly appreciate any explanation.

It seems there are some parts in the documentation we do not understand pretty well.

Thank you for your advice!

**Comment by ikedas** [comment]
Hi @radamesi ,

I think it is possible. In the first place, how have you configured your Sympa?

**Comment by radamesi** [comment]
Well, we just started configuring it following the installation guide, so
we are stuck configuring Postfix.

We have configured a Proxmox LXC Container with Debian 10 and installed the
Sympa packages.

We would like to manage our lists using Sympa. A user would send an email
to the Sympa list, and then Sympa would send the email to our main Postfix
to deliver it.

Is that possible? Or should we set up a different mail server for Sympa and
then Sympa would send the emails?

Thank you for your patience.

**Comment by ikedas** [comment]
If you followed the [instruction for Postfix](https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html) in the manual, there are three map files:
- `virtual.sympa`
- `transport.sympa`
- `sympa_transport`

Among them, `sympa_transport` is not recommended editing manually.  However, if you want some addresses of the mail domain managed by Sympa to be excluded from mailing list service, you can add them to these files: `virtual.sympa` for virtual aliases and/or `transport.sympa` for transports.

**Comment by ikedas** [comment]
No more questions for long time. Close.
