### ISSUE TITLE
"Mail_footer.tt2" is not read

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#985]
Hello.

I created a file called "message_footer.tt2" in "$SYSCONFDIR/mail_tt2/".
Then I created a new list.
However, the contents of the created footer are not applied, because the above file is not read.
In addition, "merge_feature" is enabled.
Also, moving "message_footer.tt2" to "$SYSCONFDIR/[domain name]/mail_tt2/" did not change.
Are there any other items to set?
I would appreciate any advice.
The environment is Ubuntu 20.04, Sympa 6.2.56.

Best regards.

**Comment by ikedas** [comment]
Hi @riku22 ,

`message_footer.tt2` is not a mail template of the list but is a template of the list file created at the time of list creation by [families](https://sympa-community.github.io/manual/customize/basics-families.html).  Its location is

  ``$SYSCONFDIR/``my domain``/families/``_my family_``/message_footer.tt2``

or (for primary domain,  unrecommended)

  ``$SYSCONFDIR/families/``_my family_``/message_footer.tt2``

It will be used to generate ``$EXPLDIR``_list path_``/message_footer`` when a list will be created by the family.

**Comment by riku22** [comment]
Hello.

Oh, I see, it is necessary to form a family.
I tried creating a family called "test_family" and added a line "family_name test_family" to "config.tt2" of "create_list_templates".
After that, I tried creating a new list, but it seems that "message_footer.tt2" is not loaded although the family is defined.
I haven't written anything in the family configuration file "config.tt2". Do I need to write anything?

Best regards.

**Comment by ikedas** [comment]
With the list creation template under `create_list_templates`, `sympa.pl --create_list` command may create the new list. In this case only `config` can be extracted from `config.tt2`.  See "[List creation, editing and removal](https://sympa-community.github.io/manual/admin/list-creation.html)".

With the list creation template under `families`, `sympa.pl --add_list` command may create the new list (or `sympa.pl --instantiate_family` may create a set of lists) and `sympa.pl --modify_list` may update existing list. In these cases the files specified by `parsed_family_files` parameter can be extracted from corresponding `*.tt2` files (`message_footer(.tt2)` is included in it by default).  See "[List families](https://sympa-community.github.io/manual/customize/basics-families.html).

**Comment by riku22** [comment]
Hello.

I didn't notice it because I'm not using the command line.
Is it possible to create a new family list with WW Sympa?

Best regards.

**Comment by ikedas** [comment]
There are two ways for automatic creation of family lists.
- [Automatic list creation](https://sympa-community.github.io/manual/customize/automatic-lists.html) triggerred by the posts.
- [User-friendly automatic lists](https://sympa-community.github.io/manual/customize/friendly-automatic-lists.html) created using web interface.

The latter looks what you wish.

**Comment by riku22** [comment]
Hello.
Thank you very much.
It seems difficult, so I tried other methods.
Then I found that I could customize the footer for each domain and I'm currently investigating it.
But I'm basically fine, but I'm not sure how to print the subject of the list.
When I tried to output a list of variables that can be used in the template, it seems that there is a variable called "list_title". Is it not possible to use this?
I tried embedding it in "[domain name]/message_footer" like "[% list_title %]", but it seems that I can not get it well and it is blank.
This also seems to be different because "[% subject %]" is the subject of the email to be sent. ..
Best regards.

**Comment by ikedas** [comment]
`message_footer` (w/o extension "`.tt2`") itself cannot be extracted as template.  If it was, you might enable personalization (`merge_feature` parameter) of the list: It allows the message body to be extracted as if it was a template.
Personalization is applied at the time of message distribution, while `message_foogter.tt2` is extracted at the time of list creation.

**Comment by riku22** [comment]
Hello.

Yes, "merge_feature" is enabled.
Is there a way to embed the subject of a list like "test mailing list" in "message_footer"?
I tried using "[% list_title %]" and "[% subject %]" as variables, but it doesn't seem to work.

Best regards.

**Comment by ikedas** [comment]
Currently subject of a list cannot be used as template variable.  Please see also #959 .

**Comment by riku22** [comment]
Hello.

Hmm, let's consider a little more.
Family is a little difficult for me.
I have a configuration file, but creating an XML file is a bit difficult.

**Comment by ikedas** [comment]
Hi @riku22 ,
> However, this will result in an error that the owner cannot be found.

Could you please show these things?
- the content of `config.0` (or `config`) and `owner.dump` in the list directory, and;
- Complete error message.

**Comment by riku22** [comment]
Hello.

The contents of the "config" file are as follows.

```

owner
gecos Riku
email contact@example.com
profile privileged

subject Test mailing list

visibility conceal

family_name my_family

send privateoreditorkey

custom_subject [% list.name %]:[% list.sequence %]

footer_type append

merge_feature on

reject_mail_from_automates_feature on

rfc2369_header_fields archive,help,owner,post,subscribe,unsubscribe

subscribe owner

add owner_notify

unsubscribe owner

del owner_notify

invite owner

review owner

shared_doc
d_read private
d_edit private

process_archive on

archive
web_access private
mail_access private

latest_instantiation
email listmaster@ml.example.com
date_epoch 1599047355

creation
email listmaster@ml.example.com
date_epoch 1599047355

update
date_epoch 1599047355
email listmaster@ml.example.com

status open

serial 1
```

Also, the content of "owner.dump" was blank.
The details of the error are as follows.

```
Sep  2 20:49:15 sv01 sympa[3740]: notice Sympa::Spindle::ProcessRequest::_twist() Processing Sympa::Request <action=create_automatic_list;context=my_family@ml.example.com;listname=test>
Sep  2 20:49:15 sv01 sympa[3740]: err main::#764 > main::instantiate#1325 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_automatic_list::_twist#207 Template error. List test from family Sympa::Family <my_family@ml.example.com>, file message_footer.mime : file error - message_footer.mime.tt2: not found
Sep  2 20:49:15 sv01 sympa[3740]: info Sympa::List::_load_list_config_file() Bad entry "status %status%#015" in /var/lib/sympa/list_data/ml.example.com/test/config
Sep  2 20:49:15 sv01 sympa[3740]: notice Sympa::Request::Handler::create_automatic_list::_twist() Synchronizing list members...
Sep  2 20:49:15 sv01 sympa[3740]: notice Sympa::Request::Handler::create_automatic_list::_twist() ...done
Sep  2 20:49:16 sv01 sympa[3740]: err main::#764 > main::instantiate#1325 > Sympa::Spindle::spin#95 > Sympa::Request::Handler::create_automatic_list::_twist#295 > Sympa::Family::check_param_constraint#191 > Sympa::Family::get_constraints#248 > Sympa::Family::_load_param_constraint_conf#429 No file /etc/sympa/ml.example.com/families/my_family/param_constraint.conf. Assuming no constraints to apply
Sep  2 20:49:16 sv01 sympa[3740]: notice Sympa::Request::Handler::create_automatic_list::_twist() Synchronizing list members...
Sep  2 20:49:16 sv01 sympa[3740]: notice Sympa::Request::Handler::create_automatic_list::_twist() ...done
Sep  2 20:49:16 sv01 sympa[3740]: err main::#764 > main::instantiate#1330 > Sympa::List::new#413 The list "test" has got no owner defined
Sep  2 20:49:16 sv01 sympa[3740]: err main::#764 > main::instantiate#1330 > Sympa::List::new#414 > Sympa::List::set_status_error_config#456 The list Sympa::List <test@ml.example.com> is set in status error_config: no_owner_defined()
```

**Comment by ikedas** [comment]
I couldn't reproduce.  Could you please _attach_ the files (`config.tt2` and `config.0`) instead of pasting them.

**Comment by riku22** [comment]
Hello.

I'm sorry, but when I looked it up, there seemed to be a problem with "config.tt2".
solved.
Thank you very much.
