### ISSUE TITLE
CAS: logout_path does not work

### ISSUE THREAD

**Issue by kazimkoybasi** [sympa-community/sympa#986]
**Version**
-------
Sympa 6.2.56

**Installation method**
-------------------
Centos 7 Epel Repo

**Expected behavior**
-----------------
Sympa should redirect base_url/logouth_path but it does not.

**Actual behavior**
-----------------
![logout](https://user-images.githubusercontent.com/70519985/91718521-37b11880-eb9c-11ea-83e1-40d8069a6c48.png)

[auth.conf.txt](https://github.com/sympa-community/sympa/files/5150164/auth.conf.txt)

**
---------------
Whatever I write as logouth_path . It shows logout screen as attached but sympa does not logout and it seems to omit this value.

**Comment by ikedas** [comment]
Hi @kazimkoybasi ,
Could you please show us the log of HTTP server and Sympa, from when you successfully logged-in to when you see the message "You have logged out."?

**Comment by kazimkoybasi** [comment]
Hi @ikedas 

This is only log that I get in apache when I click logout button and sympa log  with log_level 2 is like  below.
[sympa_log.txt](https://github.com/sympa-community/sympa/files/5154170/sympa_log.txt)


10.10.0.25 - - [01/Sep/2020:08:25:47 +0300] "POST /sympa HTTP/1.1" 200 7829 "http://sympat.xxx.edu/sympa" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"

**Comment by ikedas** [comment]
I understood that you did these things:
1. You accessed to Sympa web site (not yet logging-in).
2. You logged in.
3. You acceessed to Sympa web site (already logging-in).
4. You performed "Logout" action.
5. You saw a message "You have logged out".

Could you please show us the log of HTTP server and Sympa, from 1. to 5. above?

**Comment by kazimkoybasi** [comment]
Hi @ikedas ,

I added correct logs below from step 1 to 5. 

[apache_log.txt](https://github.com/sympa-community/sympa/files/5154301/apache_log.txt)
[sympa_log.txt](https://github.com/sympa-community/sympa/files/5154323/sympa_log.txt)

**Comment by ikedas** [comment]
@kazimkoybasi , could you please apply [this patch](https://github.com/sympa-community/sympa/commit/3129c4b7e6b135c1e89d2d40d66e326e76417f31.patch), restart wwsympa and try again?

**Comment by kazimkoybasi** [comment]
Hi @ikedas ,

It is resolved after apply this patch. Thanks.

Regards.

**Comment by ikedas** [comment]
@kazimkoybasi , thanks for reporting bug and confirming fix!
