### ISSUE TITLE
Typo of "default/mail_tt2/helpfile.tt2"

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#990]
There seems to be an typo in the 29th line of the default mail template "default/mail_tt2/helpfile.tt2".
In the explanation of other "SET" commands, it is "<list>|*", so I think that it is probably a mistake and report it.

Version
-------
Sympa 6.2.56

Installation method
-------------------
deb

Expected behavior
-----------------
` [%|loc%]SET <list>|* DIGESTPLAIN    * Message reception in compilation mode, sent as a plain text email with all attachments[%END%]`

Actual behavior
---------------
` [%|loc%]SET <list|*> DIGESTPLAIN    * Message reception in compilation mode, sent as a plain text email with all attachments[%END%]`

**Comment by ikedas** [comment]
Fixed [on translation site](https://translate.sympa.org/en_US/sympa/translate/en_US.po#unit=60740).  This change will be available at the time of the next release.
