### ISSUE TITLE
How to forward a subscribe request to a moderator

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#991]
Hello.

I want to transfer my subscription to the list to moderators, is there any way?
I saved the following content as "subscribe.editor".

```
title moderator approval

!equal([sender],[email])           smtp,dkim,md5,smime -> request_auth([email])
is_subscriber([listname],[email])  smtp,dkim,md5,smime -> do_it
true()                             smtp,dkim,md5,smime -> editor
```

After that, I selected the above file in the settings and sent the subscription request, but the following error occurs.

```
Sep  6 14:09:19 sv01 sympa_msg[74804]: info Sympa::Spindle::AuthorizeRequest::_twist() SUBSCRIBE for Sympa::List <test@ml.example.com> from example@example.com aborted, unknown requested action "editor" in scenario "subscribe"
```

Is it possible to send the subscription request to the moderator?
I would appreciate any advice.
The environment is Ubuntu20, Sympa 6.2.56.

Best regards.

**Comment by ikedas** [comment]
Currently, it is not pssible to forward subscription request to the moderator.

Moderators' task is approving/rejecting the post.  Approving/rejecting the subscription is the task of owners. Thus, `editor` action is allowed only in `send.*` scenario, not in `subscribe.*` scenario.

**Comment by riku22** [comment]
Hello.

I see.
Thank you very much.
