### ISSUE TITLE
About "GET" command

### ISSUE THREAD

**Issue by riku22** [sympa-community/sympa#998]
Hello.
I have a question about the "GET" command of the mail command.
I want to get an email by specifying the sequence of the list like "GET test 100" with the "GET" command. Is this possible?
Currently, I think this command can only be obtained monthly.
I would appreciate it if you could tell me if there is any way.
Best regards.

**Comment by ikedas** [comment]
Hi @riku22 

Currently GET command gets messages of specified month, but cannot get particular message.

**Comment by riku22** [comment]
Hello.
I see.
Thank you.
Best regards.
